export const CliErrorCode = {
  AdmissionOverloaded: "admission_overloaded",
  AdmissionPayloadExceedsLimit: "admission_payload_exceeds_limit",
  ArchivedHardDeleteForbidden: "archived_hard_delete_forbidden",
  ArtifactReadFailed: "artifact_read_failed",
  ArtifactWriteRejected: "artifact_write_rejected",
  AuthoredRootNotIsolated: "authored_root_not_isolated",
  AuthorityIngressRejected: "authority_ingress_rejected",
  CloseoutPlaceholder: "closeout_placeholder",
  CommitCompletionGitRefMissing: "commit_completion_git_ref_missing",
  CommitCompletionNonCommitObject: "commit_completion_non_commit_object",
  ConflictingDeleteMode: "conflicting_delete_mode",
  ConflictMarkerPresent: "conflict_marker_present",
  ConflictingDecisionBodyInput: "conflicting_decision_body_input",
  ConflictingGovernanceMode: "conflicting_governance_mode",
  ConflictingLessonMode: "conflicting_lesson_mode",
  ConflictingMigrationMode: "conflicting_migration_mode",
  ConflictingSupersedeTarget: "conflicting_supersede_target",
  CommandReceiptContractMismatch: "command_receipt_contract_mismatch",
  CustomVerticalContractMissing: "custom_vertical_contract_missing",
  CustomVerticalProjectGateRequired: "custom_vertical_project_gate_required",
  CustomVerticalUserDevModeRequired: "custom_vertical_user_dev_mode_required",
  DaemonBackedPathRequired: "daemon_backed_path_required",
  DaemonRefreshBuildFailed: "daemon_refresh_build_failed",
  DaemonGenerationFenced: "DAEMON_GENERATION_FENCED",
  DaemonQueueDrainTimeout: "daemon_queue_drain_timeout",
  DaemonRequestOutcomeUnknown: "daemon_request_outcome_unknown",
  // PLT-Honest: daemon_unavailable used to be the only signal for every
  // failure to reach the daemon, including "it is honestly still starting".
  // That conflation is what made today's hint recommend `ha daemon restart`
  // — the action that killed the user's recovering daemon. The two codes
  // below split the honest states out without touching the existing
  // daemon_unavailable entry (another worker is repurposing it for
  // root-resolution failure).
  DaemonStarting: "daemon_starting",
  DaemonNotPresent: "daemon_not_present",
  DaemonUnavailable: "daemon_unavailable",
  DecodeFailed: "decode_failed",
  DecisionReadFailed: "decision_read_failed",
  DecisionBodyFileReadFailed: "decision_body_file_read_failed",
  DecisionChosenTooLong: "decision_chosen_too_long",
  DecisionWriteRejected: "decision_write_rejected",
  DeleteConfirmMismatch: "delete_confirm_mismatch",
  DeleteConfirmRequired: "delete_confirm_required",
  DuplicateAdoptClaim: "duplicate_adopt_claim",
  DuplicateExternalBinding: "duplicate_external_binding",
  FactWriteRejected: "fact_write_rejected",
  EngineOwnsStatus: "engine_owns_status",
  // Internal source-compatibility translations; the retired public codes are absent from the registry.
  get ExecutionCompletionRequired() { return "terminal_status_requires_task_complete" as const; },
  get ExecutionReviewRequired() { return "invalid_transition" as const; },
  get ExecutionSubmissionRequired() { return "invalid_transition" as const; },
  FullCutoverRetired: "full_cutover_retired",
  GeneratedTaskIdRequired: "generated_task_id_required",
  GuiLauncherUnavailable: "gui_launcher_unavailable",
  HarnessRootUnresolved: "harness_root_unresolved",
  HarnessSettingsInvalid: "harness_settings_invalid",
  InvalidCheckProfile: "invalid_check_profile",
  InvalidCheckScope: "invalid_check_scope",
  InvalidCompletionShell: "invalid_completion_shell",
  InvalidCiGate: "invalid_ci_gate",
  InvalidDecisionActor: "invalid_decision_actor",
  InvalidDecisionAmendPatch: "invalid_decision_amend_patch",
  InvalidDecisionEvidenceRelation: "invalid_decision_evidence_relation",
  InvalidDecisionLegacyRange: "invalid_decision_legacy_range",
  InvalidDecisionTier: "invalid_decision_tier",
  InvalidEntrypoint: "invalid_entrypoint",
  InvalidEvidence: "invalid_evidence",
  InvalidFactConfidence: "invalid_fact_confidence",
  InvalidFactId: "invalid_fact_id",
  InvalidDaemonLogInput: "invalid_daemon_log_input",
  InvalidJsonInput: "invalid_json_input",
  InvalidFactMemoryClass: "invalid_fact_memory_class",
  InvalidFactMemoryTag: "invalid_fact_memory_tag",
  InvalidLessonFilter: "invalid_lesson_filter",
  InvalidLocale: "invalid_locale",
  InvalidModuleStepState: "invalid_module_step_state",
  InvalidRegistryKey: "invalid_registry_key",
  InvalidRuntimeEventKind: "invalid_runtime_event_kind",
  InvalidRuntimeEventValue: "invalid_runtime_event_value",
  InvalidScriptFilter: "invalid_script_filter",
  InvalidSession: "invalid_session",
  InvalidStatus: "invalid_status",
  InvalidTaskMetadata: "invalid_task_metadata",
  InvalidTaskRelation: "invalid_task_relation",
  InvalidTransition: "invalid_transition",
  JournalUnavailable: "journal_unavailable",
  WriteOutcomeIndeterminate: "write_outcome_indeterminate",
  LegacyCollisionReportInvalid: "legacy_collision_report_invalid",
  LegacyDuplicateTarget: "legacy_duplicate_target",
  LegacyEntryNotFound: "legacy_entry_not_found",
  LegacyIndexInvalid: "legacy_index_invalid",
  LegacyIndexMissing: "legacy_index_missing",
  LegacyIndexSchemaInvalid: "legacy_index_schema_invalid",
  LegacyIndexTargetsMissing: "legacy_index_targets_missing",
  LegacyRebuildManualIdForbidden: "legacy_rebuild_manual_id_forbidden",
  LegacyRebuildPresetForbidden: "legacy_rebuild_preset_forbidden",
  LegacyStoredPathMissing: "legacy_stored_path_missing",
  LegacyUnsafeSource: "legacy_unsafe_source",
  MalformedSnapshot: "malformed_snapshot",
  ManualTaskIdForbidden: "manual_task_id_forbidden",
  MissingDecisionChoice: "missing_decision_choice",
  MissingDecisionQuestion: "missing_decision_question",
  MissingDecisionRejected: "missing_decision_rejected",
  MissingDeleteMode: "missing_delete_mode",
  MissingFactSource: "missing_fact_source",
  MissingFactStatement: "missing_fact_statement",
  MissingForceReason: "missing_force_reason",
  MissingLegacyId: "missing_legacy_id",
  MissingModule: "missing_module",
  MissingModuleFields: "missing_module_fields",
  MissingName: "missing_name",
  MissingPreset: "missing_preset",
  MissingProfile: "missing_profile",
  MissingReason: "missing_reason",
  MissingRequiredOption: "missing_required_option",
  MissingSession: "missing_session",
  MissingSupersedeTarget: "missing_supersede_target",
  MissingTask: "missing_task",
  MissingTaskId: "missing_task_id",
  MissingText: "missing_text",
  MissingTitle: "missing_title",
  MissingVertical: "missing_vertical",
  ModuleNotFound: "module_not_found",
  PresetManifestInvalid: "preset_manifest_invalid",
  PresetMaterializationFailed: "preset_materialization_failed",
  PresetNotFound: "preset_not_found",
  PresetPolicyInvalid: "preset_policy_invalid",
  PresetRuntimeUnavailable: "preset_runtime_unavailable",
  PresetReadScopeInvalid: "preset_read_scope_invalid",
  PresetReadScopeViolation: "preset_read_scope_violation",
  PresetScriptFailed: "preset_script_failed",
  PresetScriptNotFound: "preset_script_not_found",
  PresetScriptResultFailed: "preset_script_result_failed",
  PresetScriptResultInvalid: "preset_script_result_invalid",
  PresetUninstallBlocked: "preset_uninstall_blocked",
  PresetWriteScopeInvalid: "preset_write_scope_invalid",
  PresetWriteScopeViolation: "preset_write_scope_violation",
  ScriptContractInvalid: "script_contract_invalid",
  ScriptDeclaredProduceMismatch: "script_declared_produce_mismatch",
  ScriptFailed: "script_failed",
  ScriptNotFound: "script_not_found",
  ScriptResultFailed: "script_result_failed",
  ScriptResultInvalid: "script_result_invalid",
  ScriptScopeInvalidRead: "script_scope_invalid_read",
  ScriptScopeInvalidWrite: "script_scope_invalid_write",
  ScriptScopeViolationRead: "script_scope_violation_read",
  ScriptScopeViolationWrite: "script_scope_violation_write",
  SessionExportFailed: "session_export_failed",
  RelatedTaskHardDeleteForbidden: "related_task_hard_delete_forbidden",
  ReviewSchemaInvalid: "review_schema_invalid",
  RuntimeEventLedgerRejected: "runtime_event_ledger_rejected",
  StaleSnapshotRefused: "stale_snapshot_refused",
  StatusCheckFailed: "status_check_failed",
  SupersedeConfirmMismatch: "supersede_confirm_mismatch",
  SupersedeConfirmRequired: "supersede_confirm_required",
  SupersedeTargetNotFound: "supersede_target_not_found",
  TaskAlreadyExists: "task_already_exists",
  TaskLeaseRequired: "task_lease_required",
  TaskReturnToIdeaBlocked: "task_return_to_idea_blocked",
  TaskWipLimitReached: "task_wip_limit_reached",
  TaskPlanPlaceholder: "task_plan_placeholder",
  TaskTreeDirty: "task_tree_dirty",
  TaskNotFound: "task_not_found",
  TemplateCatalogInvalid: "template_catalog_invalid",
  TemplateRenderFailed: "template_render_failed",
  TerminalHardDeleteForbidden: "terminal_hard_delete_forbidden",
  TerminalReopenRequiresSupersede: "terminal_reopen_requires_supersede",
  TerminalServiceUnavailable: "terminal_service_unavailable",
  TerminalStatusRequiresTaskComplete: "terminal_status_requires_task_complete",
  UnclassifiedCommandFailure: "unclassified_command_failure",
  UnknownCommand: "unknown_command",
  UnknownHelpTopic: "unknown_help_topic",
  UnknownOption: "unknown_option",
  UserSettingsInvalid: "user_settings_invalid",
  VerticalDefinitionInvalid: "vertical_definition_invalid",
  InvalidWorktreeNamespace: "invalid_worktree_namespace",
  WorktreeBindingMissing: "worktree_binding_missing",
  WorktreeCommandFailed: "worktree_command_failed",
  WriteConflict: "write_conflict",
  WriteRejected: "write_rejected",
  EngineNotEnabled: "EngineNotEnabled",
  AdapterUnavailable: "AdapterUnavailable",
  ArchiveReferenceUnresolved: "archive_reference_unresolved",
  AuthMissing: "AuthMissing",
  CheckProfileFailed: "check_profile_failed",
  RefNotFound: "RefNotFound",
  ProjectionCheckFailed: "projection_check_failed",
  StatusUnmapped: "StatusUnmapped",
  RateLimited: "RateLimited",
  EngineUnreachable: "EngineUnreachable",
  Timeout: "Timeout"
} as const;

export type CliErrorCode = (typeof CliErrorCode)[keyof typeof CliErrorCode];

export type CliErrorCategory = "parse" | "command" | "domain" | "settings" | "extension" | "migration";
export type CliErrorFamily = "kernel-mapped" | "command-local";

export const cliKernelMappedErrorCodes = new Set<CliErrorCode>([
  CliErrorCode.AdmissionPayloadExceedsLimit,
  CliErrorCode.ArchivedHardDeleteForbidden,
  CliErrorCode.ArtifactReadFailed,
  CliErrorCode.ArtifactWriteRejected,
  CliErrorCode.AuthoredRootNotIsolated,
  CliErrorCode.AuthorityIngressRejected,
  CliErrorCode.DuplicateAdoptClaim,
  CliErrorCode.DuplicateExternalBinding,
  CliErrorCode.EngineOwnsStatus,
  CliErrorCode.GeneratedTaskIdRequired,
  CliErrorCode.InvalidTransition,
  CliErrorCode.JournalUnavailable,
  CliErrorCode.MalformedSnapshot,
  CliErrorCode.RelatedTaskHardDeleteForbidden,
  CliErrorCode.StaleSnapshotRefused,
  CliErrorCode.TaskAlreadyExists,
  CliErrorCode.TaskLeaseRequired,
  CliErrorCode.TaskReturnToIdeaBlocked,
  CliErrorCode.TaskWipLimitReached,
  CliErrorCode.TaskPlanPlaceholder,
  CliErrorCode.TaskNotFound,
  CliErrorCode.TerminalHardDeleteForbidden,
  CliErrorCode.TerminalReopenRequiresSupersede,
  CliErrorCode.WriteConflict,
  CliErrorCode.WriteRejected,
  CliErrorCode.EngineNotEnabled,
  CliErrorCode.AdapterUnavailable,
  CliErrorCode.AuthMissing,
  CliErrorCode.RefNotFound,
  CliErrorCode.StatusUnmapped,
  CliErrorCode.RateLimited,
  CliErrorCode.EngineUnreachable,
  CliErrorCode.Timeout
]);

export const cliCommandLocalErrorCodes = new Set<CliErrorCode>(
  Object.values(CliErrorCode).filter((code): code is CliErrorCode => !cliKernelMappedErrorCodes.has(code as CliErrorCode))
);

export interface CliError {
  readonly code: CliErrorCode;
  readonly hint: string;
  readonly context?: Readonly<Record<string, unknown>>;
}

export interface CliErrorCodeDefinition {
  readonly category: CliErrorCategory;
  readonly defaultHint: string;
}

export const cliErrorCodeRegistry = {
  [CliErrorCode.AdmissionOverloaded]: { category: "domain", defaultHint: "Shared daemon admission failed because the op/byte budget is full. Run `ha daemon status --json`, wait for admitted writes to settle, then retry the exact command." },
  [CliErrorCode.AdmissionPayloadExceedsLimit]: { category: "domain", defaultHint: "Shared daemon admission rejected this request because its operations or bytes exceed the protected per-request limit. Split it into multiple calls or pass a smaller `--evidence` value, then rerun the original command." },
  [CliErrorCode.ArchivedHardDeleteForbidden]: { category: "domain", defaultHint: "Hard delete was rejected because archived tasks retain audit history. Run `ha task show <task-id> --view trace`, then keep the archive or create a replacement with `ha task supersede <task-id> --title <follow-up-title>`." },
  [CliErrorCode.ArtifactReadFailed]: { category: "domain", defaultHint: "The requested task artifact could not be read because its path is missing or unreadable. Run `ha task show <task-id> --view trace`, correct the artifact path or permissions, then retry." },
  [CliErrorCode.ArtifactWriteRejected]: { category: "domain", defaultHint: "The task artifact write was rejected because the path or task state failed validation. Run `ha task artifact add --help`, correct the reported path or state, then retry the original command." },
  [CliErrorCode.AuthoredRootNotIsolated]: { category: "domain", defaultHint: "The canonical write was rejected because the authored root is not isolated from the outer Git repository. Run `ha init`, verify the authored root is an independent Git repository and ignored by the outer repository, then retry the original command." },
  [CliErrorCode.AuthorityIngressRejected]: { category: "domain", defaultHint: "Application authority ingress rejected the command because its options or action shape are not authorized for the canonical write path. Run `ha help` to inspect the supported shape, read the receipt `reason`, remove or correct the named option, then rerun the original command." },
  [CliErrorCode.ArchiveReferenceUnresolved]: { category: "command", defaultHint: "The archive was rejected because it would leave a task-owned relation endpoint unresolved. Run `ha relation list --entity task/<task-id> --json`, repair or retire the reported relation, then retry." },
  [CliErrorCode.CloseoutPlaceholder]: { category: "command", defaultHint: "Task completion requires closeout.md without template placeholder text; replace the placeholders. If closeout.md is already substantive, retry the exact command once unchanged to refresh a lagging read." },
  [CliErrorCode.CommitCompletionGitRefMissing]: { category: "command", defaultHint: "The requested commit ref is missing from the workspace repository; run git cat-file -e '<ref>^{commit}' and retry with an existing workspace commit." },
  [CliErrorCode.CommitCompletionNonCommitObject]: { category: "command", defaultHint: "The required commit object is missing because the requested ref names another Git object type; run git cat-file -t <ref>, then retry --commit-anchor with a commit SHA or ref." },
  [CliErrorCode.ConflictingDeleteMode]: { category: "parse", defaultHint: "The delete request was rejected because it selected more than one mode. Run `ha task delete --help`, keep exactly one of `--soft` or `--hard`, then retry." },
  [CliErrorCode.ConflictMarkerPresent]: { category: "command", defaultHint: "The command was rejected because Git conflict markers remain in authored files. Run `git status --short`, resolve the listed conflicts, then retry the original command." },
  [CliErrorCode.ConflictingDecisionBodyInput]: { category: "parse", defaultHint: "The Decision input was rejected because `--body` and `--body-file` are mutually exclusive. Run `ha decision propose --help`, keep exactly one body source, then retry." },
  [CliErrorCode.ConflictingGovernanceMode]: { category: "parse", defaultHint: "The governance rebuild was rejected because multiple execution modes were selected. Run `ha governance rebuild --help`, keep exactly one of `--dry-run`, `--archive`, or `--apply`, then retry." },
  [CliErrorCode.ConflictingLessonMode]: { category: "parse", defaultHint: "The lesson query was rejected because its mode flags conflict. Run `ha task list --help`, choose one `--lesson` mode, then retry." },
  [CliErrorCode.ConflictingMigrationMode]: { category: "parse", defaultHint: "The migration was rejected because preview and apply modes conflict. Run `ha migrate --help`, choose one supported mode, then retry." },
  [CliErrorCode.ConflictingSupersedeTarget]: { category: "parse", defaultHint: "The supersede request was rejected because both a new title and an existing replacement were selected. Run `ha task supersede --help`, choose `--title` or `--by`, then retry." },
  [CliErrorCode.CommandReceiptContractMismatch]: { category: "command", defaultHint: "The command result was rejected because it did not match its declared receipt contract. Run `ha capabilities --json`, inspect the command output schema, then rerun after correcting the reported result field." },
  [CliErrorCode.CustomVerticalContractMissing]: { category: "settings", defaultHint: "The custom vertical was rejected because its required contract file is missing. Run `ha vertical validate <path> --json`, add the reported contract file, then retry." },
  [CliErrorCode.CustomVerticalProjectGateRequired]: { category: "settings", defaultHint: "The custom vertical was rejected because project settings do not enable custom verticals. Run `ha doctor --json`, enable the reported project setting in `harness/harness.yaml`, then retry." },
  [CliErrorCode.CustomVerticalUserDevModeRequired]: { category: "settings", defaultHint: "The custom vertical was rejected because user development mode is disabled. Run `ha doctor --json`, enable the reported user setting, then retry `ha vertical validate <path> --json`." },
  [CliErrorCode.DaemonBackedPathRequired]: { category: "domain", defaultHint: "The command was rejected because normal canonical writes require the daemon-backed CLI path. Remove `HARNESS_DAEMON_MODE=direct`, then retry the original command; use direct mode only with the explicit recovery reason shown in the receipt." },
  [CliErrorCode.DaemonRefreshBuildFailed]: { category: "domain", defaultHint: "Daemon refresh replacement preflight failed. Correct the reported startup configuration error, then rerun `ha daemon refresh`." },
  [CliErrorCode.DaemonQueueDrainTimeout]: { category: "domain", defaultHint: "Daemon control requires the write queue to drain within the deadline, but in-flight operations failed to settle in time. Run `ha daemon status --json`, inspect the reported queue operation tuples, resolve or recover them, then retry the control request." },
  [CliErrorCode.DaemonRequestOutcomeUnknown]: { category: "domain", defaultHint: "The daemon request timed out, so its outcome is unknown and the write may already have taken effect. Verify the target entity before deciding whether to retry; for task writes, run `ha task list` or `ha task show <task-id>`." },
  [CliErrorCode.DaemonUnavailable]: { category: "domain", defaultHint: "The daemon-backed request was rejected because the daemon is unavailable to the CLI. Run `ha daemon status --json`, start or restore the reported daemon, then retry; use the receipt's direct recovery command only for an explicit recovery." },
  [CliErrorCode.DaemonStarting]: { category: "domain", defaultHint: "The daemon-backed write is blocked because the daemon is still starting; cold start on a large ledger can take 60-90s. Do NOT run 'ha daemon restart' — that kills the recovering daemon. Wait, then poll 'ha daemon status --json' until ready." },
  [CliErrorCode.DaemonNotPresent]: { category: "domain", defaultHint: "The daemon-backed write was rejected because no daemon process is running for this repo. Start one with 'ha daemon start --service', then retry." },
  [CliErrorCode.DecodeFailed]: { category: "extension", defaultHint: "The registry value was rejected because it could not be decoded with the declared schema. Run `ha doctor --json`, correct the reported registry entry, then retry the original command." },
  [CliErrorCode.DecisionReadFailed]: { category: "command", defaultHint: "The Decision document is missing or unreadable. Run `ha decision list --json` to select an existing Decision, then retry the original decision command with that id." },
  [CliErrorCode.DecisionBodyFileReadFailed]: { category: "parse", defaultHint: "The Decision `--body-file` is missing or unreadable. Verify `<path>` names a readable Markdown file, then rerun the original `ha decision ... --body-file <path>` command." },
  [CliErrorCode.DecisionChosenTooLong]: { category: "parse", defaultHint: "Decision proposal was rejected because one chosen entry is too long. Keep one yes/no judgment in each --chosen entry, split parallel judgments into more --chosen entries, move reasoning to --body, move implementation requirements to a task, and read harness/standards/decision-writing.md; if it is missing, run ha init to materialize it." },
  [CliErrorCode.DecisionWriteRejected]: { category: "command", defaultHint: "The canonical Decision write was rejected because its payload or current state failed validation. Inspect the receipt `reason`, correct the named field or state, then rerun the original `ha decision ...` command." },
  [CliErrorCode.DaemonGenerationFenced]: { category: "domain", defaultHint: "The write was rejected because this daemon's generation is stale (a newer daemon replaced it). Run `ha daemon status --json --include-generation-axes` to confirm the current generation, then retry the command against the current daemon; the durable outcome, if any, is recorded in its terminal journal." },
  [CliErrorCode.DeleteConfirmMismatch]: { category: "command", defaultHint: "Hard delete was rejected because `--confirm` does not exactly match the target task id. Run `ha task delete --help`, pass the same id to `--hard` and `--confirm`, then retry." },
  [CliErrorCode.DeleteConfirmRequired]: { category: "command", defaultHint: "Hard delete was rejected because the required `--confirm <task-id>` acknowledgment is missing. Run `ha task delete --help`, add the matching confirmation, then retry." },
  [CliErrorCode.DuplicateAdoptClaim]: { category: "domain", defaultHint: "The adopt request was rejected because this external claim is already bound. Run `ha task show <task-id> --view trace`, inspect the existing claim, and reuse it instead of retrying the duplicate." },
  [CliErrorCode.DuplicateExternalBinding]: { category: "domain", defaultHint: "The external binding was rejected because the provider reference is already attached to a task. Run `ha external snapshot <github|multica> <ref> --json`, locate the existing binding, then use its task." },
  [CliErrorCode.FactWriteRejected]: { category: "command", defaultHint: "The Fact write was rejected because its task, statement, source, or metadata failed validation. Run `ha fact record --help`, correct the reported field, then retry." },
  [CliErrorCode.EngineOwnsStatus]: { category: "domain", defaultHint: "The status change was rejected because an external engine owns this task state. Run `ha task show <task-id> --view trace`, update the state through the owning engine, then inspect it again." },
  [CliErrorCode.FullCutoverRetired]: { category: "migration", defaultHint: "The full-cutover command is retired because Legacy Intake is the supported migration path. Run `ha legacy verify --json`, then rebuild a selected entry with `ha task create --from-legacy <legacy-id>`." },
  [CliErrorCode.GeneratedTaskIdRequired]: { category: "domain", defaultHint: "Task creation was rejected because this write path requires a generated task id. Run `ha task create --title <title>`, remove any manual id input, then retry." },
  [CliErrorCode.GuiLauncherUnavailable]: { category: "command", defaultHint: "The GUI launch failed because no usable launcher or renderer is configured. Run `ha doctor --json`, configure the reported GUI dependency, then retry `ha gui`." },
  [CliErrorCode.HarnessRootUnresolved]: { category: "settings", defaultHint: "The command was rejected because the CLI could not resolve an initialized, registered harness repository root. Run `ha daemon repo list --json`, then rerun the original command with `ha --root <canonical-root>`." },
  [CliErrorCode.HarnessSettingsInvalid]: { category: "settings", defaultHint: "Project settings were rejected because `harness/harness.yaml` failed validation. Run `ha doctor --json`, correct the reported setting, then retry the original command." },
  [CliErrorCode.InvalidCheckProfile]: { category: "parse", defaultHint: "The check request was rejected because `--profile` is not a supported profile. Run `ha check --help`, choose `source-package`, `private-harness`, or `target-project`, then retry." },
  [CliErrorCode.InvalidCheckScope]: { category: "parse", defaultHint: "The check scope is invalid. Run `ha check --help`, choose exactly one existing `--task <task-id>` or repository-relative `--path <task-package-path>`, then retry." },
  [CliErrorCode.InvalidCompletionShell]: { category: "parse", defaultHint: "Unknown shell completion target. Run 'ha completion bash' or 'ha completion zsh'." },
  [CliErrorCode.InvalidCiGate]: { category: "parse", defaultHint: "The completion input was rejected because the CI gate value is invalid. Run `ha task complete --help`, choose `passed`, `failed`, or `not-applicable` for `--ci`, then retry." },
  [CliErrorCode.InvalidDecisionActor]: { category: "parse", defaultHint: "The Decision actor is invalid because it is not formatted as `kind:id`. Correct the actor field in `--json-input` or the input file, then rerun the original `ha decision ...` command." },
  [CliErrorCode.InvalidDecisionAmendPatch]: { category: "parse", defaultHint: "The Decision amend patch is invalid because its field is not amendable under the schema field contract. Run `ha decision amend <decision-id> --help`, choose a declared `--set` or `--append` field, then retry." },
  [CliErrorCode.InvalidDecisionEvidenceRelation]: { category: "parse", defaultHint: "The Decision evidence relation is invalid because it does not match `anchor:type:target:rationale`. Correct the `--evidence-relation` value, then rerun the original `ha decision propose ...` command." },
  [CliErrorCode.InvalidDecisionLegacyRange]: { category: "parse", defaultHint: "The Decision legacy range is invalid because it is not formatted as `E<n>-E<n>`. Rerun `ha decision list --legacy-range E1-E71 --json` with the intended inclusive range." },
  [CliErrorCode.InvalidDecisionTier]: { category: "parse", defaultHint: "The Decision tier is invalid because `--risk-tier` and `--urgency` accept only low, medium, or high. Correct the rejected option, then rerun the original `ha decision ...` command." },
  [CliErrorCode.InvalidEntrypoint]: { category: "parse", defaultHint: "The preset invocation was rejected because the named entrypoint is not declared by that preset. Run `ha preset inspect <id> --json`, choose a listed entrypoint, then retry." },
  [CliErrorCode.InvalidEvidence]: { category: "parse", defaultHint: "The evidence input was rejected because it does not match `type:PATH:summary`. Run `ha task progress append --help`, correct the `--evidence` value, then retry." },
  [CliErrorCode.InvalidDaemonLogInput]: { category: "parse", defaultHint: "The daemon log query was rejected because `--limit`, `--cursor`, `--levels`, `--since`, or `--errors` failed validation. Run `ha daemon logs --help`, correct the reported option, then retry." },
  [CliErrorCode.InvalidFactConfidence]: { category: "parse", defaultHint: "The Fact input was rejected because confidence must be low, medium, or high. Run `ha fact record --help`, correct `--confidence`, then retry." },
  [CliErrorCode.InvalidFactId]: { category: "parse", defaultHint: "The Fact input was rejected because the id does not match the Fact id format. Run `ha fact list --task <task-id> --json`, copy an existing id or omit generated-id input, then retry." },
  [CliErrorCode.InvalidJsonInput]: { category: "parse", defaultHint: "The command input was rejected because `--json-input` or `--from-file` is malformed or conflicts with another input source. Run `ha capabilities --json`, correct the JSON against the command schema, then retry." },
  [CliErrorCode.InvalidFactMemoryClass]: { category: "parse", defaultHint: "The Fact input was rejected because memory class must be semantic, episodic, or procedural. Run `ha fact record --help`, correct `--memory-class`, then retry." },
  [CliErrorCode.InvalidFactMemoryTag]: { category: "parse", defaultHint: "The Fact input was rejected because a memory tag is empty or malformed. Run `ha fact record --help`, correct or remove `--memory-tag`, then retry." },
  [CliErrorCode.InvalidLessonFilter]: { category: "parse", defaultHint: "The task query was rejected because the lesson filter is invalid. Run `ha task list --help`, choose `--lesson`, `--lesson present`, or `--lesson missing`, then retry." },
  [CliErrorCode.InvalidLocale]: { category: "parse", defaultHint: "The command was rejected because the locale is unsupported. Run `ha template render --help`, choose `zh-CN` or `en-US`, then retry." },
  [CliErrorCode.InvalidModuleStepState]: { category: "parse", defaultHint: "The module step update was rejected because the supplied state is unsupported. Run `ha module step --help`, choose a listed state, then retry." },
  [CliErrorCode.InvalidRegistryKey]: { category: "extension", defaultHint: "The extension registry entry was rejected because its key is malformed or reserved. Run `ha doctor --json`, correct the reported registry key, then retry." },
  [CliErrorCode.InvalidRuntimeEventKind]: { category: "parse", defaultHint: "The runtime event was rejected because `--kind` is unsupported. Run `ha event append --help`, choose a listed event kind, then retry." },
  [CliErrorCode.InvalidRuntimeEventValue]: { category: "parse", defaultHint: "The runtime event was rejected because one enum or numeric field is invalid. Run `ha event append --help`, correct the reported option, then retry." },
  [CliErrorCode.InvalidScriptFilter]: { category: "parse", defaultHint: "The script query was rejected because a source, purpose, or kind filter is invalid. Run `ha script list --help`, choose listed filter values, then retry." },
  [CliErrorCode.InvalidSession]: { category: "parse", defaultHint: "The command was rejected because the caller session id is malformed or unknown. Run `ha session show <session-id> --json`, select a valid session, then retry." },
  [CliErrorCode.InvalidStatus]: { category: "parse", defaultHint: "The lifecycle status is invalid for this command. Run `ha task show <task-id>` to inspect the current state, choose a status listed by the command help, then retry." },
  [CliErrorCode.InvalidTaskMetadata]: { category: "parse", defaultHint: "The task input was rejected because kind, risk tier, urgency, or another metadata value is unsupported. Run `ha task create --help`, correct the reported option, then retry." },
  [CliErrorCode.InvalidTaskRelation]: { category: "parse", defaultHint: "The task relation was rejected because its source, type, target, or rationale is invalid. Run `ha task relate --help`, correct the reported relation field, then retry." },
  [CliErrorCode.InvalidTransition]: { category: "domain", defaultHint: "The requested lifecycle transition is invalid from the task's current state. Run `ha task show <task-id>`, follow the displayed lifecycle action, then retry the original command." },
  [CliErrorCode.JournalUnavailable]: { category: "domain", defaultHint: "The write journal is unavailable, so the durable write outcome cannot be established. Run `ha daemon status --json`, restore the reported daemon or journal condition, then retry the original command." },
  [CliErrorCode.WriteOutcomeIndeterminate]: { category: "domain", defaultHint: "Write outcome is unknown for the operation IDs in the attached flush report. Run `ha daemon logs --errors --json`, compare those IDs with canonical Git state, and do not retry the original write blindly." },
  [CliErrorCode.LegacyCollisionReportInvalid]: { category: "migration", defaultHint: "The Legacy Intake collision report is invalid because `harness/legacy/collision-report.json` does not match its schema. Recreate it by rerunning `ha legacy index <source-path> --apply`." },
  [CliErrorCode.LegacyDuplicateTarget]: { category: "migration", defaultHint: "The Legacy Intake plan is invalid because multiple source entries map to one target. Correct the conflicting source paths, then rerun `ha legacy index <source-path> --apply`." },
  [CliErrorCode.LegacyEntryNotFound]: { category: "migration", defaultHint: "The requested legacy id is missing from `harness/legacy/index.json`. Run `ha legacy verify --json`, select an indexed id, then retry `ha task create --from-legacy <legacy-id>`." },
  [CliErrorCode.LegacyIndexInvalid]: { category: "migration", defaultHint: "The Legacy Intake index is invalid because `harness/legacy/index.json` does not match the runtime schema. Rebuild it with `ha legacy index <source-path> --apply`, then rerun the original command." },
  [CliErrorCode.LegacyIndexMissing]: { category: "migration", defaultHint: "The required Legacy Intake index `harness/legacy/index.json` is missing. Create it with `ha legacy index <source-path> --apply`, then rerun the original command." },
  [CliErrorCode.LegacyIndexSchemaInvalid]: { category: "migration", defaultHint: "The generated Legacy Intake index is invalid because it failed the runtime schema. Inspect the reported entry, correct the source metadata, then rerun `ha legacy index <source-path> --apply`." },
  [CliErrorCode.LegacyIndexTargetsMissing]: { category: "migration", defaultHint: "The Legacy Intake index is invalid because one or more stored target paths are missing. Run `ha legacy verify --json`, restore or re-index the reported paths, then retry." },
  [CliErrorCode.LegacyRebuildManualIdForbidden]: { category: "parse", defaultHint: "A legacy rebuild is rejected when a manual task id is also supplied because the rebuild creates a fresh id. Remove the manual id option, then rerun `ha task create --from-legacy <legacy-id>`." },
  [CliErrorCode.LegacyRebuildPresetForbidden]: { category: "parse", defaultHint: "A legacy rebuild is rejected when preset input is also supplied because those are separate creation paths. Remove the preset option, then rerun `ha task create --from-legacy <legacy-id>`." },
  [CliErrorCode.LegacyStoredPathMissing]: { category: "migration", defaultHint: "The indexed legacy entry is invalid because its stored path is missing. Run `ha legacy verify --json`, restore the reported source or rebuild the index, then retry." },
  [CliErrorCode.LegacyUnsafeSource]: { category: "migration", defaultHint: "The Legacy Intake source is rejected because it contains generated dependencies or the active harness workspace. Choose an external legacy source root, then rerun `ha legacy index <source-path> --apply`." },
  [CliErrorCode.MalformedSnapshot]: { category: "domain", defaultHint: "The external snapshot was rejected because its stored payload is malformed. Run `ha external snapshot <github|multica> <ref> --json` to refresh it, then retry the dependent command." },
  [CliErrorCode.ManualTaskIdForbidden]: { category: "parse", defaultHint: "Task creation was rejected because manual ids are forbidden on the generated-id path. Run `ha task create --title <title>` without an id option, then use the returned task id." },
  [CliErrorCode.MissingDecisionChoice]: { category: "parse", defaultHint: "The Decision proposal is missing required chosen text. Add at least one `--chosen <text>` judgment, then rerun `ha decision propose ...`." },
  [CliErrorCode.MissingDecisionQuestion]: { category: "parse", defaultHint: "The Decision proposal is missing its required question. Add `--question <text>`, then rerun `ha decision propose ...`." },
  [CliErrorCode.MissingDecisionRejected]: { category: "parse", defaultHint: "The Decision proposal is missing a required rejected alternative. Add `--rejected <text>` and its rationale, then rerun `ha decision propose ...`." },
  [CliErrorCode.MissingDeleteMode]: { category: "parse", defaultHint: "The delete request was rejected because neither `--soft` nor `--hard` selected a mode. Run `ha task delete --help`, choose one mode with its task id, then retry." },
  [CliErrorCode.MissingFactSource]: { category: "parse", defaultHint: "The Fact write was rejected because no source could be provided or inferred. Run `ha fact record --task <task-id> --statement <text> --source <source>`, then retry." },
  [CliErrorCode.MissingFactStatement]: { category: "parse", defaultHint: "The Fact write was rejected because its required statement is missing. Run `ha fact record --task <task-id> --statement <text>`, then retry." },
  [CliErrorCode.MissingForceReason]: { category: "parse", defaultHint: "The forced transition was rejected because `--reason` is required with `--force`. Run `ha task transition --help`, add a concrete reason, then retry." },
  [CliErrorCode.MissingLegacyId]: { category: "parse", defaultHint: "The legacy rebuild request is missing its required legacy id. Choose an id from `harness/legacy/index.json`, then rerun `ha task create --from-legacy <legacy-id>`." },
  [CliErrorCode.MissingModule]: { category: "parse", defaultHint: "The module command was rejected because its required module key is missing. Run `ha module list --json`, choose a key, then retry the original command." },
  [CliErrorCode.MissingModuleFields]: { category: "parse", defaultHint: "Module registration was rejected because both title and scope are required. Run `ha module register <key> --title <title> --scope <path>`, then retry." },
  [CliErrorCode.MissingName]: { category: "parse", defaultHint: "Initialization was rejected because `--name` has no value. Run `ha init --name <name>`, or remove the empty option to use the directory name." },
  [CliErrorCode.MissingPreset]: { category: "parse", defaultHint: "The preset command was rejected because its required preset id is missing. Run `ha preset list --json`, choose an id, then retry." },
  [CliErrorCode.MissingProfile]: { category: "parse", defaultHint: "The command was rejected because its required profile id is missing. Run `ha doctor --json`, select a configured profile, then retry with `--profile <id>`." },
  [CliErrorCode.MissingReason]: { category: "parse", defaultHint: "The lifecycle write was rejected because its auditable reason is missing. Run `ha task transition --help`, add `--reason <text>`, then retry." },
  [CliErrorCode.MissingRequiredOption]: { category: "parse", defaultHint: "The command was rejected because a required option is missing or empty. Run the command with `--help`, add the reported option with a non-empty value, then retry." },
  [CliErrorCode.MissingSession]: { category: "parse", defaultHint: "The session command was rejected because its required session id is missing. Run `ha session show --help`, add `--session <session-id>` or the required positional id, then retry." },
  [CliErrorCode.MissingSupersedeTarget]: { category: "parse", defaultHint: "The supersede request was rejected because no replacement was selected. Run `ha task supersede --help`, provide `--title <title>` or `--by <task-id>`, then retry." },
  [CliErrorCode.MissingTask]: { category: "parse", defaultHint: "The command was rejected because its required task id is missing. Run `ha task list --json`, choose a task id, then retry." },
  [CliErrorCode.MissingTaskId]: { category: "parse", defaultHint: "The command was rejected because its required task id is missing. Run `ha task list --json`, choose a task id, then retry." },
  [CliErrorCode.MissingText]: { category: "parse", defaultHint: "The progress update was rejected because its required text is missing. Run `ha task progress append <task-id> --text <update>`, then retry." },
  [CliErrorCode.MissingTitle]: { category: "parse", defaultHint: "Task creation was rejected because its required title is missing. Run `ha task create --title <title>`, then continue with the returned task id." },
  [CliErrorCode.MissingVertical]: { category: "parse", defaultHint: "The extension command was rejected because its required vertical id is missing. Run `ha vertical validate software/coding --json`, then retry with the intended vertical." },
  [CliErrorCode.ModuleNotFound]: { category: "extension", defaultHint: "The module command was rejected because the requested key is not registered. Run `ha module list --json`, choose an existing key or register it, then retry." },
  [CliErrorCode.PresetManifestInvalid]: { category: "extension", defaultHint: "The preset was rejected because its manifest failed schema validation. Run `ha preset validate <manifest> --json`, correct the reported field, then retry." },
  [CliErrorCode.PresetMaterializationFailed]: { category: "extension", defaultHint: "Preset installation was rejected because its files could not be materialized safely. Run `ha preset validate <manifest> --json`, fix the reported path or content, then retry." },
  [CliErrorCode.PresetNotFound]: { category: "extension", defaultHint: "The preset command was rejected because the requested id is not installed. Run `ha preset list --json`, choose an installed id or install the preset, then retry." },
  [CliErrorCode.PresetPolicyInvalid]: { category: "extension", defaultHint: "The preset was rejected because its policy document failed validation. Run `ha preset check <id> --json`, correct the reported policy field, then retry." },
  [CliErrorCode.PresetRuntimeUnavailable]: { category: "extension", defaultHint: "The preset entrypoint was rejected because the task's frozen contract has no compatible runtime. Run `ha preset inspect <id> --json`, choose a compatible entrypoint or preset, then retry." },
  [CliErrorCode.PresetReadScopeInvalid]: { category: "extension", defaultHint: "The preset script was rejected because its declared read scope is malformed. Run `ha preset validate <manifest> --json`, correct the read-scope declaration, then retry." },
  [CliErrorCode.PresetReadScopeViolation]: { category: "extension", defaultHint: "The preset script was rejected because it read outside its declared scope. Run `ha preset inspect <id> --json`, narrow the script reads or expand the reviewed manifest scope, then retry." },
  [CliErrorCode.PresetScriptFailed]: { category: "extension", defaultHint: "The preset entrypoint failed because its script exited unsuccessfully. Run `ha preset check <id> --json`, fix the reported script error, then retry the entrypoint." },
  [CliErrorCode.PresetScriptNotFound]: { category: "extension", defaultHint: "The preset entrypoint was rejected because its declared script file is missing. Run `ha preset validate <manifest> --json`, restore or correct the script path, then retry." },
  [CliErrorCode.PresetScriptResultFailed]: { category: "extension", defaultHint: "The preset entrypoint was rejected because the script reported a failed result. Run `ha preset check <id> --json`, resolve the reported failure, then retry." },
  [CliErrorCode.PresetScriptResultInvalid]: { category: "extension", defaultHint: "The preset entrypoint was rejected because the script result does not match its contract. Run `ha preset check <id> --json`, correct the result payload, then retry." },
  [CliErrorCode.PresetUninstallBlocked]: { category: "extension", defaultHint: "Preset uninstall was rejected because tasks still reference this preset. Run `ha task list --preset <id> --json`, migrate or archive those tasks, then retry." },
  [CliErrorCode.PresetWriteScopeInvalid]: { category: "extension", defaultHint: "The preset script was rejected because its declared write scope is malformed. Run `ha preset validate <manifest> --json`, correct the write-scope declaration, then retry." },
  [CliErrorCode.PresetWriteScopeViolation]: { category: "extension", defaultHint: "The preset script was rejected because it wrote outside its declared scope. Run `ha preset inspect <id> --json`, narrow the writes or expand the reviewed manifest scope, then retry." },
  [CliErrorCode.ScriptContractInvalid]: { category: "extension", defaultHint: "The extension script was rejected because its contract is missing or invalid. Run `ha script inspect <id> --json`, correct the reported contract field, then retry." },
  [CliErrorCode.ScriptDeclaredProduceMismatch]: { category: "extension", defaultHint: "The extension script was rejected because it produced files outside its declared outputs. Run `ha script inspect <id> --json`, align the script writes with the declared outputs, then retry." },
  [CliErrorCode.ScriptFailed]: { category: "extension", defaultHint: "The extension script failed because its process exited unsuccessfully. Run `ha script run <id> --dry-run --json`, fix the reported script error, then retry." },
  [CliErrorCode.ScriptNotFound]: { category: "extension", defaultHint: "The script command was rejected because the requested id is not installed. Run `ha script list --json`, choose an existing id, then retry." },
  [CliErrorCode.ScriptResultFailed]: { category: "extension", defaultHint: "The extension script was rejected because it reported a failed result. Run `ha script run <id> --dry-run --json`, resolve the reported failure, then retry." },
  [CliErrorCode.ScriptResultInvalid]: { category: "extension", defaultHint: "The extension script was rejected because its result does not match the declared contract. Run `ha script inspect <id> --json`, correct the result payload, then retry." },
  [CliErrorCode.ScriptScopeInvalidRead]: { category: "extension", defaultHint: "The extension script was rejected because its declared read scope is malformed. Run `ha script inspect <id> --json`, correct the read-scope declaration, then retry." },
  [CliErrorCode.ScriptScopeInvalidWrite]: { category: "extension", defaultHint: "The extension script was rejected because its declared write scope is malformed. Run `ha script inspect <id> --json`, correct the write-scope declaration, then retry." },
  [CliErrorCode.ScriptScopeViolationRead]: { category: "extension", defaultHint: "The extension script was rejected because it read outside its declared scope. Run `ha script inspect <id> --json`, narrow the reads or revise the reviewed scope, then retry." },
  [CliErrorCode.ScriptScopeViolationWrite]: { category: "extension", defaultHint: "The extension script was rejected because it wrote outside its declared scope. Run `ha script inspect <id> --json`, narrow the writes or revise the reviewed scope, then retry." },
  [CliErrorCode.SessionExportFailed]: { category: "command", defaultHint: "Session export failed because the selected transcript or session could not be decoded. Verify `--transcript-file <path>`, then rerun `ha session export --transcript-file <path> --json`." },
  [CliErrorCode.RelatedTaskHardDeleteForbidden]: { category: "domain", defaultHint: "Hard delete was rejected because the task still has active relations. Run `ha relation list --entity task/<task-id> --json`, repair or retire those relations, then retry or use soft delete." },
  [CliErrorCode.ReviewSchemaInvalid]: { category: "command", defaultHint: "The execution Review is invalid because its document does not match the required schema. Inspect `harness/tasks/<task-package>/reviews/<review-id>.md`, correct the reported field, then retry task completion." },
  [CliErrorCode.RuntimeEventLedgerRejected]: { category: "command", defaultHint: "The runtime event ledger rejected the session read or append because its durable record is unavailable or invalid. Run `ha event list --session <session-id> --json`, correct the reported ledger condition, then retry." },
  [CliErrorCode.StaleSnapshotRefused]: { category: "domain", defaultHint: "The external operation was rejected because its snapshot is stale. Run `ha external snapshot <github|multica> <ref> --json` to refresh the provider state, then retry." },
  [CliErrorCode.StatusCheckFailed]: { category: "command", defaultHint: "The status check failed because the runtime or deployment did not satisfy its health contract. Run `ha daemon status --check --json`, resolve the reported condition, then retry." },
  [CliErrorCode.SupersedeConfirmMismatch]: { category: "command", defaultHint: "The supersede request was rejected because `--confirm` does not match the old task id. Run `ha task supersede --help`, pass the old id as confirmation, then retry." },
  [CliErrorCode.SupersedeConfirmRequired]: { category: "command", defaultHint: "The supersede-by-existing request was rejected because `--confirm <old-task-id>` is missing. Run `ha task supersede --help`, add the matching confirmation, then retry." },
  [CliErrorCode.SupersedeTargetNotFound]: { category: "command", defaultHint: "The supersede request was rejected because the replacement task was not found. Run `ha task list --json`, choose an existing replacement id, then retry." },
  [CliErrorCode.TaskAlreadyExists]: { category: "domain", defaultHint: "Task creation was rejected because the target task already exists. Run `ha task show <task-id> --json`, reuse that task or create a new generated task with `ha task create --title <title>`." },
  [CliErrorCode.TaskLeaseRequired]: { category: "domain", defaultHint: "Task lease is required. Run 'ha task start <task-id>' before retrying." },
  [CliErrorCode.TaskReturnToIdeaBlocked]: {
    category: "domain",
    defaultHint: "Return to planned is blocked. Run 'ha task release <task-id>', then 'ha task retire-execution <task-id> --execution-id <execution-id> --reason <reason>' before retrying."
  },
  [CliErrorCode.TaskWipLimitReached]: {
    category: "domain",
    defaultHint: "Activation was rejected because settings.tasks.wipLimit is full. Run 'ha task transition <named-task-id> planned', or complete/archive a named task, then retry activation."
  },
  [CliErrorCode.TaskPlanPlaceholder]: { category: "command", defaultHint: "Active transition requires task_plan.md without template scaffold content; replace the scaffold. If task_plan.md is already substantive, retry the exact command once unchanged to refresh a lagging read." },
  [CliErrorCode.TaskTreeDirty]: { category: "command", defaultHint: "The task lifecycle write is rejected because the task package has uncommitted changes. Run `git status --short -- harness/tasks/<task-package>`, resolve those changes intentionally, then retry." },
  [CliErrorCode.TaskNotFound]: { category: "domain", defaultHint: "The command was rejected because the requested task was not found. Run `ha task list --json`, choose an existing task id, then retry." },
  [CliErrorCode.TemplateCatalogInvalid]: { category: "extension", defaultHint: "The template request was rejected because its catalog failed validation. Run `ha template list --catalog <path> --json`, correct the reported catalog entry, then retry." },
  [CliErrorCode.TemplateRenderFailed]: { category: "extension", defaultHint: "Template rendering failed because the selected template or input could not be resolved. Run `ha template list --json`, choose a valid template ref, then retry `ha template render <template-ref> --json`." },
  [CliErrorCode.TerminalHardDeleteForbidden]: { category: "domain", defaultHint: "Hard delete was rejected because terminal tasks retain completion history. Run `ha task show <task-id> --view trace`, then use `ha task archive <task-id> --reason <reason>` instead." },
  [CliErrorCode.TerminalReopenRequiresSupersede]: { category: "domain", defaultHint: "Reopen was rejected because terminal tasks require an auditable replacement. Run `ha task supersede <task-id> --title <follow-up-title>`, then continue work on the returned task." },
  [CliErrorCode.TerminalServiceUnavailable]: { category: "command", defaultHint: "The terminal operation failed because its local service is unavailable. Run `ha doctor --json`, restore the reported service dependency, then retry." },
  [CliErrorCode.TerminalStatusRequiresTaskComplete]: { category: "command", defaultHint: "Preferred path: ha task complete <id> --approve. If the task is already terminal and more work is required, run ha task supersede <id> --title <follow-up-title>." },
  [CliErrorCode.UnclassifiedCommandFailure]: { category: "command", defaultHint: "The command failed for an unexpected reason that the command group could not classify. Rerun the command; if it repeats, run `ha doctor --json` and inspect the reported condition, then contact maintenance with the receipt." },
  [CliErrorCode.UnknownCommand]: { category: "parse", defaultHint: "Unknown command. Run 'ha help' to inspect valid commands." },
  [CliErrorCode.UnknownHelpTopic]: { category: "parse", defaultHint: "Unknown help topic. Run 'ha help' to inspect valid commands." },
  [CliErrorCode.UnknownOption]: { category: "parse", defaultHint: "Unknown option. Run the command with '--help' to inspect valid options." },
  [CliErrorCode.UserSettingsInvalid]: { category: "settings", defaultHint: "User settings were rejected because one or more values failed validation. Run `ha doctor --json`, correct the reported user setting, then retry." },
  [CliErrorCode.VerticalDefinitionInvalid]: { category: "extension", defaultHint: "The vertical was rejected because its definition failed validation. Run `ha vertical validate <path> --json`, correct the reported field, then retry." },
  [CliErrorCode.InvalidWorktreeNamespace]: { category: "parse", defaultHint: "Worktree creation was rejected because the branch namespace is malformed or reserved. Run `ha worktree create --help`, choose a valid `--agent` or `--branch-prefix`, then retry." },
  [CliErrorCode.WorktreeBindingMissing]: { category: "command", defaultHint: "The worktree command was rejected because this task has no recorded worktree binding. Run `ha worktree create --task <task-id> --json`, then retry the status operation." },
  [CliErrorCode.WorktreeCommandFailed]: { category: "command", defaultHint: "The worktree operation failed because the underlying Git command was rejected. Run `git status --short`, resolve the reported repository condition, then retry `ha worktree status --task <task-id> --json`." },
  [CliErrorCode.WriteConflict]: { category: "domain", defaultHint: "The write was rejected because the authored state changed after it was read. Run `ha task show <task-id> --view trace`, reconcile with the current state, then retry the write." },
  [CliErrorCode.WriteRejected]: { category: "domain", defaultHint: "The write was rejected because its payload, lifecycle state, or authority context failed validation. Run `ha doctor --json`, inspect the receipt reason, correct the reported condition, then retry." },
  [CliErrorCode.EngineNotEnabled]: { category: "domain", defaultHint: "The engine request was rejected because the selected engine is not enabled. Run `ha doctor --json`, enable a configured engine or select an enabled profile, then retry." },
  [CliErrorCode.AdapterUnavailable]: { category: "domain", defaultHint: "The engine request was rejected because its required adapter is unavailable. Run `ha doctor --json`, install or configure the reported adapter, then retry." },
  [CliErrorCode.AuthMissing]: { category: "domain", defaultHint: "The command was rejected because required actor or provider authentication is missing. Run `ha doctor --json`, configure the reported credential or `HARNESS_ACTOR`, then retry." },
  [CliErrorCode.CheckProfileFailed]: { category: "command", defaultHint: "The check profile failed because one or more required gates reported errors. Run `ha check --profile source-package --json`, fix the named gate failures, then rerun the intended profile." },
  [CliErrorCode.RefNotFound]: { category: "domain", defaultHint: "The command was rejected because the requested provider or repository reference was not found. Run `git rev-parse --verify <ref>` or refresh it with `ha external snapshot github <ref> --json`, then retry." },
  [CliErrorCode.ProjectionCheckFailed]: { category: "command", defaultHint: "The projection check failed because derived state does not match authored records. Run `ha governance rebuild --dry-run --json`, inspect the reported drift, then apply the repair and retry." },
  [CliErrorCode.StatusUnmapped]: { category: "domain", defaultHint: "The provider item was rejected because its external status has no local mapping. Run `ha external snapshot <github|multica> <ref> --json`, inspect the raw status, then configure or choose a supported mapping." },
  [CliErrorCode.RateLimited]: { category: "domain", defaultHint: "The engine request was rejected because the provider rate limit is exhausted. Run `ha doctor --json`, wait for the reported reset or select another configured engine, then retry." },
  [CliErrorCode.EngineUnreachable]: { category: "domain", defaultHint: "The engine request failed because the configured engine endpoint is unreachable. Run `ha doctor --json`, restore the reported endpoint or network configuration, then retry." },
  [CliErrorCode.Timeout]: { category: "domain", defaultHint: "The operation failed because it did not finish before its deadline. Run `ha daemon status --json`, verify whether the write already completed, then retry only if the target state is unchanged." }
} satisfies Record<CliErrorCode, CliErrorCodeDefinition>;

export function cliError(code: CliErrorCode, hint?: string, context?: Readonly<Record<string, unknown>>): CliError {
  return { code, hint: hint ?? cliErrorCodeRegistry[code].defaultHint, ...(context ? { context } : {}) };
}

export function isCliErrorCode(value: unknown): value is CliErrorCode {
  return typeof value === "string" && Object.hasOwn(cliErrorCodeRegistry, value);
}

/**
 * Reads a {@link CliErrorCode} that a throw site attached to an error so a
 * catch block can pass it through without guessing. Catch blocks should
 * always fall back to an honest "unclassified" code when this returns
 * undefined — never to a specific diagnosis that the error did not carry.
 */
export function errorCodeFromThrown(error: unknown): CliErrorCode | undefined {
  if (error !== null && typeof error === "object" && "cliErrorCode" in error) {
    const code = (error as { readonly cliErrorCode?: unknown }).cliErrorCode;
    return isCliErrorCode(code) ? code : undefined;
  }
  return undefined;
}

/**
 * Attaches a {@link CliErrorCode} to an Error so a catch block can pass it
 * through. Use this at throw sites that know the honest semantic class of
 * the failure (parameter validation, missing option, etc.).
 */
export function withCliErrorCode(error: Error, code: CliErrorCode): Error & { readonly cliErrorCode: CliErrorCode } {
  return Object.assign(error, { cliErrorCode: code });
}

export function cliErrorFamily(code: CliErrorCode): CliErrorFamily {
  return cliKernelMappedErrorCodes.has(code) ? "kernel-mapped" : "command-local";
}

export function missingRequiredOptionErrorCode(name: string): CliErrorCode {
  switch (name) {
    case "--name":
      return CliErrorCode.MissingName;
    case "--module":
      return CliErrorCode.MissingModule;
    case "--preset":
      return CliErrorCode.MissingPreset;
    case "--profile":
      return CliErrorCode.MissingProfile;
    case "--vertical":
      return CliErrorCode.MissingVertical;
    default:
      throw new Error(`Unsupported required option: ${name}`);
  }
}
