export const CliErrorCode = {
  AdmissionOverloaded: "admission_overloaded",
  AdmissionPayloadExceedsLimit: "admission_payload_exceeds_limit",
  ArchivedHardDeleteForbidden: "archived_hard_delete_forbidden",
  ArtifactReadFailed: "artifact_read_failed",
  ArtifactWriteRejected: "artifact_write_rejected",
  AuthorityIngressRejected: "authority_ingress_rejected",
  CloseoutPlaceholder: "closeout_placeholder",
  CommitCompletionGitRefMissing: "commit_completion_git_ref_missing",
  CommitCompletionNonCommitObject: "commit_completion_non_commit_object",
  ConflictingDeleteMode: "conflicting_delete_mode",
  ConflictMarkerPresent: "conflict_marker_present",
  ConflictingDecisionBodyInput: "conflicting_decision_body_input",
  ConflictingGovernanceMode: "conflicting_governance_mode",
  ConflictingLessonMode: "conflicting_lesson_mode",
  ConflictingMigrationMode: "conflicting_migration_mode",
  ConflictingSupersedeTarget: "conflicting_supersede_target",
  CommandReceiptContractMismatch: "command_receipt_contract_mismatch",
  CustomVerticalContractMissing: "custom_vertical_contract_missing",
  CustomVerticalProjectGateRequired: "custom_vertical_project_gate_required",
  CustomVerticalUserDevModeRequired: "custom_vertical_user_dev_mode_required",
  DaemonRefreshBuildFailed: "daemon_refresh_build_failed",
  DaemonGenerationFenced: "DAEMON_GENERATION_FENCED",
  DaemonQueueDrainTimeout: "daemon_queue_drain_timeout",
  DaemonRequestOutcomeUnknown: "daemon_request_outcome_unknown",
  DecodeFailed: "decode_failed",
  DecisionReadFailed: "decision_read_failed",
  DecisionBodyFileReadFailed: "decision_body_file_read_failed",
  DecisionChosenTooLong: "decision_chosen_too_long",
  DecisionWriteRejected: "decision_write_rejected",
  DeleteConfirmMismatch: "delete_confirm_mismatch",
  DeleteConfirmRequired: "delete_confirm_required",
  DuplicateAdoptClaim: "duplicate_adopt_claim",
  DuplicateExternalBinding: "duplicate_external_binding",
  FactWriteRejected: "fact_write_rejected",
  EngineOwnsStatus: "engine_owns_status",
  // Internal source-compatibility translations; the retired public codes are absent from the registry.
  get ExecutionCompletionRequired() { return "terminal_status_requires_task_complete" as const; },
  get ExecutionReviewRequired() { return "invalid_transition" as const; },
  get ExecutionSubmissionRequired() { return "invalid_transition" as const; },
  FullCutoverRetired: "full_cutover_retired",
  GeneratedTaskIdRequired: "generated_task_id_required",
  GuiLauncherUnavailable: "gui_launcher_unavailable",
  HarnessSettingsInvalid: "harness_settings_invalid",
  InvalidCheckProfile: "invalid_check_profile",
  InvalidCompletionShell: "invalid_completion_shell",
  InvalidCiGate: "invalid_ci_gate",
  InvalidDecisionActor: "invalid_decision_actor",
  InvalidDecisionAmendPatch: "invalid_decision_amend_patch",
  InvalidDecisionEvidenceRelation: "invalid_decision_evidence_relation",
  InvalidDecisionLegacyRange: "invalid_decision_legacy_range",
  InvalidDecisionTier: "invalid_decision_tier",
  InvalidEntrypoint: "invalid_entrypoint",
  InvalidEvidence: "invalid_evidence",
  InvalidFactConfidence: "invalid_fact_confidence",
  InvalidFactId: "invalid_fact_id",
  InvalidJsonInput: "invalid_json_input",
  InvalidFactMemoryClass: "invalid_fact_memory_class",
  InvalidFactMemoryTag: "invalid_fact_memory_tag",
  InvalidLessonFilter: "invalid_lesson_filter",
  InvalidLocale: "invalid_locale",
  InvalidModuleStepState: "invalid_module_step_state",
  InvalidRegistryKey: "invalid_registry_key",
  InvalidRuntimeEventKind: "invalid_runtime_event_kind",
  InvalidRuntimeEventValue: "invalid_runtime_event_value",
  InvalidScriptFilter: "invalid_script_filter",
  InvalidSession: "invalid_session",
  InvalidStatus: "invalid_status",
  InvalidTaskMetadata: "invalid_task_metadata",
  InvalidTaskRelation: "invalid_task_relation",
  InvalidTransition: "invalid_transition",
  JournalUnavailable: "journal_unavailable",
  LegacyCollisionReportInvalid: "legacy_collision_report_invalid",
  LegacyDuplicateTarget: "legacy_duplicate_target",
  LegacyEntryNotFound: "legacy_entry_not_found",
  LegacyIndexInvalid: "legacy_index_invalid",
  LegacyIndexMissing: "legacy_index_missing",
  LegacyIndexSchemaInvalid: "legacy_index_schema_invalid",
  LegacyIndexTargetsMissing: "legacy_index_targets_missing",
  LegacyRebuildManualIdForbidden: "legacy_rebuild_manual_id_forbidden",
  LegacyRebuildPresetForbidden: "legacy_rebuild_preset_forbidden",
  LegacyStoredPathMissing: "legacy_stored_path_missing",
  LegacyUnsafeSource: "legacy_unsafe_source",
  MalformedSnapshot: "malformed_snapshot",
  ManualTaskIdForbidden: "manual_task_id_forbidden",
  MissingDecisionChoice: "missing_decision_choice",
  MissingDecisionQuestion: "missing_decision_question",
  MissingDecisionRejected: "missing_decision_rejected",
  MissingDeleteMode: "missing_delete_mode",
  MissingFactSource: "missing_fact_source",
  MissingFactStatement: "missing_fact_statement",
  MissingForceReason: "missing_force_reason",
  MissingLegacyId: "missing_legacy_id",
  MissingModule: "missing_module",
  MissingModuleFields: "missing_module_fields",
  MissingName: "missing_name",
  MissingPreset: "missing_preset",
  MissingProfile: "missing_profile",
  MissingReason: "missing_reason",
  MissingSession: "missing_session",
  MissingSupersedeTarget: "missing_supersede_target",
  MissingTask: "missing_task",
  MissingTaskId: "missing_task_id",
  MissingText: "missing_text",
  MissingTitle: "missing_title",
  MissingVertical: "missing_vertical",
  ModuleNotFound: "module_not_found",
  PresetManifestInvalid: "preset_manifest_invalid",
  PresetMaterializationFailed: "preset_materialization_failed",
  PresetNotFound: "preset_not_found",
  PresetPolicyInvalid: "preset_policy_invalid",
  PresetRuntimeUnavailable: "preset_runtime_unavailable",
  PresetReadScopeInvalid: "preset_read_scope_invalid",
  PresetReadScopeViolation: "preset_read_scope_violation",
  PresetScriptFailed: "preset_script_failed",
  PresetScriptNotFound: "preset_script_not_found",
  PresetScriptResultFailed: "preset_script_result_failed",
  PresetScriptResultInvalid: "preset_script_result_invalid",
  PresetUninstallBlocked: "preset_uninstall_blocked",
  PresetWriteScopeInvalid: "preset_write_scope_invalid",
  PresetWriteScopeViolation: "preset_write_scope_violation",
  ScriptContractInvalid: "script_contract_invalid",
  ScriptDeclaredProduceMismatch: "script_declared_produce_mismatch",
  ScriptFailed: "script_failed",
  ScriptNotFound: "script_not_found",
  ScriptResultFailed: "script_result_failed",
  ScriptResultInvalid: "script_result_invalid",
  ScriptScopeInvalidRead: "script_scope_invalid_read",
  ScriptScopeInvalidWrite: "script_scope_invalid_write",
  ScriptScopeViolationRead: "script_scope_violation_read",
  ScriptScopeViolationWrite: "script_scope_violation_write",
  SessionExportFailed: "session_export_failed",
  RelatedTaskHardDeleteForbidden: "related_task_hard_delete_forbidden",
  ReviewSchemaInvalid: "review_schema_invalid",
  RuntimeEventLedgerRejected: "runtime_event_ledger_rejected",
  StaleSnapshotRefused: "stale_snapshot_refused",
  StatusCheckFailed: "status_check_failed",
  SupersedeConfirmMismatch: "supersede_confirm_mismatch",
  SupersedeConfirmRequired: "supersede_confirm_required",
  SupersedeTargetNotFound: "supersede_target_not_found",
  TaskAlreadyExists: "task_already_exists",
  TaskLeaseRequired: "task_lease_required",
  TaskReturnToIdeaBlocked: "task_return_to_idea_blocked",
  TaskWipLimitReached: "task_wip_limit_reached",
  TaskPlanPlaceholder: "task_plan_placeholder",
  TaskTreeDirty: "task_tree_dirty",
  TaskNotFound: "task_not_found",
  TemplateCatalogInvalid: "template_catalog_invalid",
  TemplateRenderFailed: "template_render_failed",
  TerminalHardDeleteForbidden: "terminal_hard_delete_forbidden",
  TerminalReopenRequiresSupersede: "terminal_reopen_requires_supersede",
  TerminalServiceUnavailable: "terminal_service_unavailable",
  TerminalStatusRequiresTaskComplete: "terminal_status_requires_task_complete",
  UnknownCommand: "unknown_command",
  UnknownHelpTopic: "unknown_help_topic",
  UserSettingsInvalid: "user_settings_invalid",
  VerticalDefinitionInvalid: "vertical_definition_invalid",
  InvalidWorktreeNamespace: "invalid_worktree_namespace",
  WorktreeBindingMissing: "worktree_binding_missing",
  WorktreeCommandFailed: "worktree_command_failed",
  WriteConflict: "write_conflict",
  WriteRejected: "write_rejected",
  EngineNotEnabled: "EngineNotEnabled",
  AdapterUnavailable: "AdapterUnavailable",
  ArchiveReferenceUnresolved: "archive_reference_unresolved",
  AuthMissing: "AuthMissing",
  CheckProfileFailed: "check_profile_failed",
  RefNotFound: "RefNotFound",
  ProjectionCheckFailed: "projection_check_failed",
  StatusUnmapped: "StatusUnmapped",
  RateLimited: "RateLimited",
  EngineUnreachable: "EngineUnreachable",
  Timeout: "Timeout"
} as const;

export type CliErrorCode = (typeof CliErrorCode)[keyof typeof CliErrorCode];

export type CliErrorCategory = "parse" | "command" | "domain" | "settings" | "extension" | "migration";
export type CliErrorFamily = "kernel-mapped" | "command-local";

export const cliKernelMappedErrorCodes = new Set<CliErrorCode>([
  CliErrorCode.AdmissionPayloadExceedsLimit,
  CliErrorCode.ArchivedHardDeleteForbidden,
  CliErrorCode.ArtifactReadFailed,
  CliErrorCode.ArtifactWriteRejected,
  CliErrorCode.AuthorityIngressRejected,
  CliErrorCode.DuplicateAdoptClaim,
  CliErrorCode.DuplicateExternalBinding,
  CliErrorCode.EngineOwnsStatus,
  CliErrorCode.GeneratedTaskIdRequired,
  CliErrorCode.InvalidTransition,
  CliErrorCode.JournalUnavailable,
  CliErrorCode.MalformedSnapshot,
  CliErrorCode.RelatedTaskHardDeleteForbidden,
  CliErrorCode.StaleSnapshotRefused,
  CliErrorCode.TaskAlreadyExists,
  CliErrorCode.TaskLeaseRequired,
  CliErrorCode.TaskReturnToIdeaBlocked,
  CliErrorCode.TaskWipLimitReached,
  CliErrorCode.TaskPlanPlaceholder,
  CliErrorCode.TaskNotFound,
  CliErrorCode.TerminalHardDeleteForbidden,
  CliErrorCode.TerminalReopenRequiresSupersede,
  CliErrorCode.WriteConflict,
  CliErrorCode.WriteRejected,
  CliErrorCode.EngineNotEnabled,
  CliErrorCode.AdapterUnavailable,
  CliErrorCode.AuthMissing,
  CliErrorCode.RefNotFound,
  CliErrorCode.StatusUnmapped,
  CliErrorCode.RateLimited,
  CliErrorCode.EngineUnreachable,
  CliErrorCode.Timeout
]);

export const cliCommandLocalErrorCodes = new Set<CliErrorCode>(
  Object.values(CliErrorCode).filter((code): code is CliErrorCode => !cliKernelMappedErrorCodes.has(code as CliErrorCode))
);

export interface CliError {
  readonly code: CliErrorCode;
  readonly hint: string;
  readonly context?: Readonly<Record<string, unknown>>;
}

export interface CliErrorCodeDefinition {
  readonly category: CliErrorCategory;
  readonly defaultHint: string;
}

export const cliErrorCodeRegistry = {
  [CliErrorCode.AdmissionOverloaded]: { category: "domain", defaultHint: "Shared daemon admission failed because the op/byte budget is full. Run `ha daemon status --json`, wait for admitted writes to settle, then retry the exact command." },
  [CliErrorCode.AdmissionPayloadExceedsLimit]: { category: "domain", defaultHint: "Shared daemon admission rejected this request because its operations or bytes exceed the protected per-request limit. Split it into multiple calls or pass a smaller `--evidence` value, then rerun the original command." },
  [CliErrorCode.ArchivedHardDeleteForbidden]: { category: "domain", defaultHint: "Archived tasks cannot be hard deleted." },
  [CliErrorCode.ArtifactReadFailed]: { category: "domain", defaultHint: "Artifact read failed." },
  [CliErrorCode.ArtifactWriteRejected]: { category: "domain", defaultHint: "Artifact write was rejected." },
  [CliErrorCode.AuthorityIngressRejected]: { category: "domain", defaultHint: "Application authority ingress rejected the command because its options or action shape are not authorized for the canonical write path. Run `ha help` to inspect the supported shape, read the receipt `reason`, remove or correct the named option, then rerun the original command." },
  [CliErrorCode.ArchiveReferenceUnresolved]: { category: "command", defaultHint: "Archive would leave a task-owned relation endpoint unresolved." },
  [CliErrorCode.CloseoutPlaceholder]: { category: "command", defaultHint: "Task completion requires closeout.md without template placeholder text; replace the placeholders. If closeout.md is already substantive, retry the exact command once unchanged to refresh a lagging read." },
  [CliErrorCode.CommitCompletionGitRefMissing]: { category: "command", defaultHint: "The requested commit ref is missing from the workspace repository; run git cat-file -e '<ref>^{commit}' and retry with an existing workspace commit." },
  [CliErrorCode.CommitCompletionNonCommitObject]: { category: "command", defaultHint: "The required commit object is missing because the requested ref names another Git object type; run git cat-file -t <ref>, then retry --commit-anchor with a commit SHA or ref." },
  [CliErrorCode.ConflictingDeleteMode]: { category: "parse", defaultHint: "Use exactly one task delete mode." },
  [CliErrorCode.ConflictMarkerPresent]: { category: "command", defaultHint: "Resolve Git conflict markers before running this command." },
  [CliErrorCode.ConflictingDecisionBodyInput]: { category: "parse", defaultHint: "Use only one of --body or --body-file." },
  [CliErrorCode.ConflictingGovernanceMode]: { category: "parse", defaultHint: "Use exactly one governance rebuild mode." },
  [CliErrorCode.ConflictingLessonMode]: { category: "parse", defaultHint: "Use exactly one lesson command mode." },
  [CliErrorCode.ConflictingMigrationMode]: { category: "parse", defaultHint: "Use exactly one migration mode." },
  [CliErrorCode.ConflictingSupersedeTarget]: { category: "parse", defaultHint: "Use exactly one supersede target." },
  [CliErrorCode.CommandReceiptContractMismatch]: { category: "command", defaultHint: "Command receipt contract mismatch." },
  [CliErrorCode.CustomVerticalContractMissing]: { category: "settings", defaultHint: "Custom vertical contract is missing." },
  [CliErrorCode.CustomVerticalProjectGateRequired]: { category: "settings", defaultHint: "Project settings must enable custom verticals." },
  [CliErrorCode.CustomVerticalUserDevModeRequired]: { category: "settings", defaultHint: "User settings must enable custom vertical development mode." },
  [CliErrorCode.DaemonRefreshBuildFailed]: { category: "domain", defaultHint: "Daemon refresh replacement preflight failed. Correct the reported startup configuration error, then rerun `ha daemon refresh`." },
  [CliErrorCode.DaemonQueueDrainTimeout]: { category: "domain", defaultHint: "Daemon control requires the write queue to drain within the deadline, but in-flight operations failed to settle in time. Run `ha daemon status --json`, inspect the reported queue operation tuples, resolve or recover them, then retry the control request." },
  [CliErrorCode.DaemonRequestOutcomeUnknown]: { category: "domain", defaultHint: "The daemon request timed out, so its outcome is unknown and the write may already have taken effect. Verify the target entity before deciding whether to retry; for task writes, run `ha task list` or `ha task show <task-id>`." },
  [CliErrorCode.DecodeFailed]: { category: "extension", defaultHint: "Registry value failed to decode." },
  [CliErrorCode.DecisionReadFailed]: { category: "command", defaultHint: "The Decision document is missing or unreadable. Run `ha decision list --json` to select an existing Decision, then retry the original decision command with that id." },
  [CliErrorCode.DecisionBodyFileReadFailed]: { category: "parse", defaultHint: "The Decision `--body-file` is missing or unreadable. Verify `<path>` names a readable Markdown file, then rerun the original `ha decision ... --body-file <path>` command." },
  [CliErrorCode.DecisionChosenTooLong]: { category: "parse", defaultHint: "Decision proposal was rejected because one chosen entry is too long. Keep one yes/no judgment in each --chosen entry, split parallel judgments into more --chosen entries, move reasoning to --body, move implementation requirements to a task, and read harness/standards/decision-writing.md; if it is missing, run ha init to materialize it." },
  [CliErrorCode.DecisionWriteRejected]: { category: "command", defaultHint: "The canonical Decision write was rejected because its payload or current state failed validation. Inspect the receipt `reason`, correct the named field or state, then rerun the original `ha decision ...` command." },
  [CliErrorCode.DaemonGenerationFenced]: { category: "domain", defaultHint: "The write was rejected because this daemon's generation is stale (a newer daemon replaced it). Run `ha daemon status --json --include-generation-axes` to confirm the current generation, then retry the command against the current daemon; the durable outcome, if any, is recorded in its terminal journal." },
  [CliErrorCode.DeleteConfirmMismatch]: { category: "command", defaultHint: "Delete confirmation does not match the task id." },
  [CliErrorCode.DeleteConfirmRequired]: { category: "command", defaultHint: "Delete confirmation is required." },
  [CliErrorCode.DuplicateAdoptClaim]: { category: "domain", defaultHint: "Adopt claim already exists." },
  [CliErrorCode.DuplicateExternalBinding]: { category: "domain", defaultHint: "External binding already exists." },
  [CliErrorCode.FactWriteRejected]: { category: "command", defaultHint: "Fact write was rejected." },
  [CliErrorCode.EngineOwnsStatus]: { category: "domain", defaultHint: "Status is owned by an external engine." },
  [CliErrorCode.FullCutoverRetired]: { category: "migration", defaultHint: "The full-cutover command is retired because Legacy Intake is the supported migration path. Run `ha legacy verify --json`, then rebuild a selected entry with `ha task create --from-legacy <legacy-id>`." },
  [CliErrorCode.GeneratedTaskIdRequired]: { category: "domain", defaultHint: "Generated task id is required." },
  [CliErrorCode.GuiLauncherUnavailable]: { category: "command", defaultHint: "GUI launcher is unavailable." },
  [CliErrorCode.HarnessSettingsInvalid]: { category: "settings", defaultHint: "Project harness settings are invalid." },
  [CliErrorCode.InvalidCheckProfile]: { category: "parse", defaultHint: "Unknown check profile." },
  [CliErrorCode.InvalidCompletionShell]: { category: "parse", defaultHint: "Unknown shell completion target. Run 'ha completion bash' or 'ha completion zsh'." },
  [CliErrorCode.InvalidCiGate]: { category: "parse", defaultHint: "Unknown CI gate value." },
  [CliErrorCode.InvalidDecisionActor]: { category: "parse", defaultHint: "The Decision actor is invalid because it is not formatted as `kind:id`. Correct the actor field in `--json-input` or the input file, then rerun the original `ha decision ...` command." },
  [CliErrorCode.InvalidDecisionAmendPatch]: { category: "parse", defaultHint: "The Decision amend patch is invalid because its field is not amendable under the schema field contract. Run `ha decision amend <decision-id> --help`, choose a declared `--set` or `--append` field, then retry." },
  [CliErrorCode.InvalidDecisionEvidenceRelation]: { category: "parse", defaultHint: "The Decision evidence relation is invalid because it does not match `anchor:type:target:rationale`. Correct the `--evidence-relation` value, then rerun the original `ha decision propose ...` command." },
  [CliErrorCode.InvalidDecisionLegacyRange]: { category: "parse", defaultHint: "The Decision legacy range is invalid because it is not formatted as `E<n>-E<n>`. Rerun `ha decision list --legacy-range E1-E71 --json` with the intended inclusive range." },
  [CliErrorCode.InvalidDecisionTier]: { category: "parse", defaultHint: "The Decision tier is invalid because `--risk-tier` and `--urgency` accept only low, medium, or high. Correct the rejected option, then rerun the original `ha decision ...` command." },
  [CliErrorCode.InvalidEntrypoint]: { category: "parse", defaultHint: "Unknown preset entrypoint." },
  [CliErrorCode.InvalidEvidence]: { category: "parse", defaultHint: "Evidence value is invalid." },
  [CliErrorCode.InvalidFactConfidence]: { category: "parse", defaultHint: "Fact confidence is invalid." },
  [CliErrorCode.InvalidFactId]: { category: "parse", defaultHint: "Fact id is invalid." },
  [CliErrorCode.InvalidJsonInput]: { category: "parse", defaultHint: "JSON command input is invalid." },
  [CliErrorCode.InvalidFactMemoryClass]: { category: "parse", defaultHint: "Fact memory class is invalid." },
  [CliErrorCode.InvalidFactMemoryTag]: { category: "parse", defaultHint: "Fact memory tag is invalid." },
  [CliErrorCode.InvalidLessonFilter]: { category: "parse", defaultHint: "Lesson filter is invalid." },
  [CliErrorCode.InvalidLocale]: { category: "parse", defaultHint: "Locale is invalid." },
  [CliErrorCode.InvalidModuleStepState]: { category: "parse", defaultHint: "Module step state is invalid." },
  [CliErrorCode.InvalidRegistryKey]: { category: "extension", defaultHint: "Registry key is invalid." },
  [CliErrorCode.InvalidRuntimeEventKind]: { category: "parse", defaultHint: "Runtime event kind is invalid." },
  [CliErrorCode.InvalidRuntimeEventValue]: { category: "parse", defaultHint: "Runtime event value is invalid." },
  [CliErrorCode.InvalidScriptFilter]: { category: "parse", defaultHint: "Script filter is invalid." },
  [CliErrorCode.InvalidSession]: { category: "parse", defaultHint: "Caller session is invalid." },
  [CliErrorCode.InvalidStatus]: { category: "parse", defaultHint: "The lifecycle status is invalid for this command. Run `ha task show <task-id>` to inspect the current state, choose a status listed by the command help, then retry." },
  [CliErrorCode.InvalidTaskMetadata]: { category: "parse", defaultHint: "Task metadata value is invalid." },
  [CliErrorCode.InvalidTaskRelation]: { category: "parse", defaultHint: "Task relation is invalid." },
  [CliErrorCode.InvalidTransition]: { category: "domain", defaultHint: "The requested lifecycle transition is invalid from the task's current state. Run `ha task show <task-id>`, follow the displayed lifecycle action, then retry the original command." },
  [CliErrorCode.JournalUnavailable]: { category: "domain", defaultHint: "The write journal is unavailable, so the durable write outcome cannot be established. Run `ha daemon status --json`, restore the reported daemon or journal condition, then retry the original command." },
  [CliErrorCode.LegacyCollisionReportInvalid]: { category: "migration", defaultHint: "The Legacy Intake collision report is invalid because `harness/legacy/collision-report.json` does not match its schema. Recreate it by rerunning `ha legacy index <source-path> --apply`." },
  [CliErrorCode.LegacyDuplicateTarget]: { category: "migration", defaultHint: "The Legacy Intake plan is invalid because multiple source entries map to one target. Correct the conflicting source paths, then rerun `ha legacy index <source-path> --apply`." },
  [CliErrorCode.LegacyEntryNotFound]: { category: "migration", defaultHint: "The requested legacy id is missing from `harness/legacy/index.json`. Run `ha legacy verify --json`, select an indexed id, then retry `ha task create --from-legacy <legacy-id>`." },
  [CliErrorCode.LegacyIndexInvalid]: { category: "migration", defaultHint: "The Legacy Intake index is invalid because `harness/legacy/index.json` does not match the runtime schema. Rebuild it with `ha legacy index <source-path> --apply`, then rerun the original command." },
  [CliErrorCode.LegacyIndexMissing]: { category: "migration", defaultHint: "The required Legacy Intake index `harness/legacy/index.json` is missing. Create it with `ha legacy index <source-path> --apply`, then rerun the original command." },
  [CliErrorCode.LegacyIndexSchemaInvalid]: { category: "migration", defaultHint: "The generated Legacy Intake index is invalid because it failed the runtime schema. Inspect the reported entry, correct the source metadata, then rerun `ha legacy index <source-path> --apply`." },
  [CliErrorCode.LegacyIndexTargetsMissing]: { category: "migration", defaultHint: "The Legacy Intake index is invalid because one or more stored target paths are missing. Run `ha legacy verify --json`, restore or re-index the reported paths, then retry." },
  [CliErrorCode.LegacyRebuildManualIdForbidden]: { category: "parse", defaultHint: "A legacy rebuild is rejected when a manual task id is also supplied because the rebuild creates a fresh id. Remove the manual id option, then rerun `ha task create --from-legacy <legacy-id>`." },
  [CliErrorCode.LegacyRebuildPresetForbidden]: { category: "parse", defaultHint: "A legacy rebuild is rejected when preset input is also supplied because those are separate creation paths. Remove the preset option, then rerun `ha task create --from-legacy <legacy-id>`." },
  [CliErrorCode.LegacyStoredPathMissing]: { category: "migration", defaultHint: "The indexed legacy entry is invalid because its stored path is missing. Run `ha legacy verify --json`, restore the reported source or rebuild the index, then retry." },
  [CliErrorCode.LegacyUnsafeSource]: { category: "migration", defaultHint: "The Legacy Intake source is rejected because it contains generated dependencies or the active harness workspace. Choose an external legacy source root, then rerun `ha legacy index <source-path> --apply`." },
  [CliErrorCode.MalformedSnapshot]: { category: "domain", defaultHint: "Snapshot is malformed." },
  [CliErrorCode.ManualTaskIdForbidden]: { category: "parse", defaultHint: "Manual task id is forbidden." },
  [CliErrorCode.MissingDecisionChoice]: { category: "parse", defaultHint: "The Decision proposal is missing required chosen text. Add at least one `--chosen <text>` judgment, then rerun `ha decision propose ...`." },
  [CliErrorCode.MissingDecisionQuestion]: { category: "parse", defaultHint: "The Decision proposal is missing its required question. Add `--question <text>`, then rerun `ha decision propose ...`." },
  [CliErrorCode.MissingDecisionRejected]: { category: "parse", defaultHint: "The Decision proposal is missing a required rejected alternative. Add `--rejected <text>` and its rationale, then rerun `ha decision propose ...`." },
  [CliErrorCode.MissingDeleteMode]: { category: "parse", defaultHint: "Task delete mode is required." },
  [CliErrorCode.MissingFactSource]: { category: "parse", defaultHint: "Fact source is required." },
  [CliErrorCode.MissingFactStatement]: { category: "parse", defaultHint: "Fact statement is required." },
  [CliErrorCode.MissingForceReason]: { category: "parse", defaultHint: "Force reason is required." },
  [CliErrorCode.MissingLegacyId]: { category: "parse", defaultHint: "The legacy rebuild request is missing its required legacy id. Choose an id from `harness/legacy/index.json`, then rerun `ha task create --from-legacy <legacy-id>`." },
  [CliErrorCode.MissingModule]: { category: "parse", defaultHint: "Module key is required." },
  [CliErrorCode.MissingModuleFields]: { category: "parse", defaultHint: "Module title and scope are required." },
  [CliErrorCode.MissingName]: { category: "parse", defaultHint: "Name is required." },
  [CliErrorCode.MissingPreset]: { category: "parse", defaultHint: "Preset id is required." },
  [CliErrorCode.MissingProfile]: { category: "parse", defaultHint: "Profile id is required." },
  [CliErrorCode.MissingReason]: { category: "parse", defaultHint: "Reason is required." },
  [CliErrorCode.MissingSession]: { category: "parse", defaultHint: "Session id is required." },
  [CliErrorCode.MissingSupersedeTarget]: { category: "parse", defaultHint: "Supersede target is required." },
  [CliErrorCode.MissingTask]: { category: "parse", defaultHint: "Task id is required." },
  [CliErrorCode.MissingTaskId]: { category: "parse", defaultHint: "Task id is required." },
  [CliErrorCode.MissingText]: { category: "parse", defaultHint: "Text is required." },
  [CliErrorCode.MissingTitle]: { category: "parse", defaultHint: "Task title is required." },
  [CliErrorCode.MissingVertical]: { category: "parse", defaultHint: "Vertical id is required." },
  [CliErrorCode.ModuleNotFound]: { category: "extension", defaultHint: "Module was not found." },
  [CliErrorCode.PresetManifestInvalid]: { category: "extension", defaultHint: "Preset manifest failed validation." },
  [CliErrorCode.PresetMaterializationFailed]: { category: "extension", defaultHint: "Preset materialization failed." },
  [CliErrorCode.PresetNotFound]: { category: "extension", defaultHint: "Preset was not found." },
  [CliErrorCode.PresetPolicyInvalid]: { category: "extension", defaultHint: "Preset policy is invalid." },
  [CliErrorCode.PresetRuntimeUnavailable]: { category: "extension", defaultHint: "Preset runtime is unavailable for the Task's frozen contract." },
  [CliErrorCode.PresetReadScopeInvalid]: { category: "extension", defaultHint: "Preset script read scope is invalid." },
  [CliErrorCode.PresetReadScopeViolation]: { category: "extension", defaultHint: "Preset script read scope was violated." },
  [CliErrorCode.PresetScriptFailed]: { category: "extension", defaultHint: "Preset script failed." },
  [CliErrorCode.PresetScriptNotFound]: { category: "extension", defaultHint: "Preset script was not found." },
  [CliErrorCode.PresetScriptResultFailed]: { category: "extension", defaultHint: "Preset script reported failure." },
  [CliErrorCode.PresetScriptResultInvalid]: { category: "extension", defaultHint: "Preset script result is invalid." },
  [CliErrorCode.PresetUninstallBlocked]: { category: "extension", defaultHint: "Preset uninstall is blocked by inbound Tasks." },
  [CliErrorCode.PresetWriteScopeInvalid]: { category: "extension", defaultHint: "Preset script write scope is invalid." },
  [CliErrorCode.PresetWriteScopeViolation]: { category: "extension", defaultHint: "Preset script write scope was violated." },
  [CliErrorCode.ScriptContractInvalid]: { category: "extension", defaultHint: "Script contract is invalid." },
  [CliErrorCode.ScriptDeclaredProduceMismatch]: { category: "extension", defaultHint: "Script produced files outside its declared outputs." },
  [CliErrorCode.ScriptFailed]: { category: "extension", defaultHint: "Script execution failed." },
  [CliErrorCode.ScriptNotFound]: { category: "extension", defaultHint: "Script was not found." },
  [CliErrorCode.ScriptResultFailed]: { category: "extension", defaultHint: "Script reported a failed result." },
  [CliErrorCode.ScriptResultInvalid]: { category: "extension", defaultHint: "Script result is invalid." },
  [CliErrorCode.ScriptScopeInvalidRead]: { category: "extension", defaultHint: "Script read scope is invalid." },
  [CliErrorCode.ScriptScopeInvalidWrite]: { category: "extension", defaultHint: "Script write scope is invalid." },
  [CliErrorCode.ScriptScopeViolationRead]: { category: "extension", defaultHint: "Script read scope was violated." },
  [CliErrorCode.ScriptScopeViolationWrite]: { category: "extension", defaultHint: "Script write scope was violated." },
  [CliErrorCode.SessionExportFailed]: { category: "command", defaultHint: "Session export failed because the selected transcript or session could not be decoded. Verify `--transcript-file <path>`, then rerun `ha session export --transcript-file <path> --json`." },
  [CliErrorCode.RelatedTaskHardDeleteForbidden]: { category: "domain", defaultHint: "Related tasks cannot be hard deleted." },
  [CliErrorCode.ReviewSchemaInvalid]: { category: "command", defaultHint: "The execution Review is invalid because its document does not match the required schema. Inspect `harness/tasks/<task-package>/reviews/<review-id>.md`, correct the reported field, then retry task completion." },
  [CliErrorCode.RuntimeEventLedgerRejected]: { category: "command", defaultHint: "The runtime event ledger rejected the session read or append because its durable record is unavailable or invalid. Run `ha event list --session <session-id> --json`, correct the reported ledger condition, then retry." },
  [CliErrorCode.StaleSnapshotRefused]: { category: "domain", defaultHint: "Stale snapshot was refused." },
  [CliErrorCode.StatusCheckFailed]: { category: "command", defaultHint: "Status check failed." },
  [CliErrorCode.SupersedeConfirmMismatch]: { category: "command", defaultHint: "Supersede confirmation does not match." },
  [CliErrorCode.SupersedeConfirmRequired]: { category: "command", defaultHint: "Supersede confirmation is required." },
  [CliErrorCode.SupersedeTargetNotFound]: { category: "command", defaultHint: "Supersede target was not found." },
  [CliErrorCode.TaskAlreadyExists]: { category: "domain", defaultHint: "Task already exists." },
  [CliErrorCode.TaskLeaseRequired]: { category: "domain", defaultHint: "Task lease is required. Run 'ha task start <task-id>' before retrying." },
  [CliErrorCode.TaskReturnToIdeaBlocked]: {
    category: "domain",
    defaultHint: "Return to planned is blocked. Run 'ha task release <task-id>', then 'ha task retire-execution <task-id> --execution-id <execution-id> --reason <reason>' before retrying."
  },
  [CliErrorCode.TaskWipLimitReached]: {
    category: "domain",
    defaultHint: "Activation was rejected because settings.tasks.wipLimit is full. Run 'ha task transition <named-task-id> planned', or complete/archive a named task, then retry activation."
  },
  [CliErrorCode.TaskPlanPlaceholder]: { category: "command", defaultHint: "Active transition requires task_plan.md without template scaffold content; replace the scaffold. If task_plan.md is already substantive, retry the exact command once unchanged to refresh a lagging read." },
  [CliErrorCode.TaskTreeDirty]: { category: "command", defaultHint: "The task lifecycle write is rejected because the task package has uncommitted changes. Run `git status --short -- harness/tasks/<task-package>`, resolve those changes intentionally, then retry." },
  [CliErrorCode.TaskNotFound]: { category: "domain", defaultHint: "Task was not found." },
  [CliErrorCode.TemplateCatalogInvalid]: { category: "extension", defaultHint: "Template catalog is invalid." },
  [CliErrorCode.TemplateRenderFailed]: { category: "extension", defaultHint: "Template render failed." },
  [CliErrorCode.TerminalHardDeleteForbidden]: { category: "domain", defaultHint: "Terminal tasks cannot be hard deleted." },
  [CliErrorCode.TerminalReopenRequiresSupersede]: { category: "domain", defaultHint: "Terminal tasks require supersede to reopen." },
  [CliErrorCode.TerminalServiceUnavailable]: { category: "command", defaultHint: "Terminal service is unavailable." },
  [CliErrorCode.TerminalStatusRequiresTaskComplete]: { category: "command", defaultHint: "Preferred path: ha task complete <id> --approve. If the task is already terminal and more work is required, run ha task supersede <id> --title <follow-up-title>." },
  [CliErrorCode.UnknownCommand]: { category: "parse", defaultHint: "Unknown command. Run 'ha help' to inspect valid commands." },
  [CliErrorCode.UnknownHelpTopic]: { category: "parse", defaultHint: "Unknown help topic. Run 'ha help' to inspect valid commands." },
  [CliErrorCode.UserSettingsInvalid]: { category: "settings", defaultHint: "User settings are invalid." },
  [CliErrorCode.VerticalDefinitionInvalid]: { category: "extension", defaultHint: "Vertical definition is invalid." },
  [CliErrorCode.InvalidWorktreeNamespace]: { category: "parse", defaultHint: "Worktree branch namespace is invalid." },
  [CliErrorCode.WorktreeBindingMissing]: { category: "command", defaultHint: "Worktree binding is missing." },
  [CliErrorCode.WorktreeCommandFailed]: { category: "command", defaultHint: "Worktree command failed." },
  [CliErrorCode.WriteConflict]: { category: "domain", defaultHint: "Write conflict." },
  [CliErrorCode.WriteRejected]: { category: "domain", defaultHint: "Write was rejected." },
  [CliErrorCode.EngineNotEnabled]: { category: "domain", defaultHint: "Engine is not enabled." },
  [CliErrorCode.AdapterUnavailable]: { category: "domain", defaultHint: "Adapter is unavailable." },
  [CliErrorCode.AuthMissing]: { category: "domain", defaultHint: "Authentication is missing." },
  [CliErrorCode.CheckProfileFailed]: { category: "command", defaultHint: "Check profile failed." },
  [CliErrorCode.RefNotFound]: { category: "domain", defaultHint: "Reference was not found." },
  [CliErrorCode.ProjectionCheckFailed]: { category: "command", defaultHint: "Projection check failed." },
  [CliErrorCode.StatusUnmapped]: { category: "domain", defaultHint: "Status is unmapped." },
  [CliErrorCode.RateLimited]: { category: "domain", defaultHint: "Engine request was rate limited." },
  [CliErrorCode.EngineUnreachable]: { category: "domain", defaultHint: "Engine is unreachable." },
  [CliErrorCode.Timeout]: { category: "domain", defaultHint: "Operation timed out." }
} satisfies Record<CliErrorCode, CliErrorCodeDefinition>;

export function cliError(code: CliErrorCode, hint?: string, context?: Readonly<Record<string, unknown>>): CliError {
  return { code, hint: hint ?? cliErrorCodeRegistry[code].defaultHint, ...(context ? { context } : {}) };
}

export function isCliErrorCode(value: unknown): value is CliErrorCode {
  return typeof value === "string" && Object.hasOwn(cliErrorCodeRegistry, value);
}

export function cliErrorFamily(code: CliErrorCode): CliErrorFamily {
  return cliKernelMappedErrorCodes.has(code) ? "kernel-mapped" : "command-local";
}

export function missingRequiredOptionErrorCode(name: string): CliErrorCode {
  switch (name) {
    case "--name":
      return CliErrorCode.MissingName;
    case "--module":
      return CliErrorCode.MissingModule;
    case "--preset":
      return CliErrorCode.MissingPreset;
    case "--profile":
      return CliErrorCode.MissingProfile;
    case "--vertical":
      return CliErrorCode.MissingVertical;
    default:
      throw new Error(`Unsupported required option: ${name}`);
  }
}
