import { daemonProtocolCommands, resolveThinCliCommand, safePath, thinCliCommands, type SafePath } from "../../../daemon/src/protocol/daemon-protocol.contract.ts";
export const thinCliLocalErrorCodes = Object.freeze(["daemon_disconnect", "duplicate_field", "invalid_field", "missing_field", "unknown_field", "unsupported_command"]);
export function renderThinHelp(): string { return ["Harness Anything thin CLI", "", "Commands:", ...thinCliCommands.map(({ usage, summary }) => `  ${usage}\n    ${summary}`)].join("\n"); }
export interface ThinCommand { readonly rootDir: SafePath; readonly repoId?: string; readonly json: boolean; readonly method: string; readonly action: Readonly<Record<string, unknown>> & { readonly kind: string }; }
export type ThinParseResult = { readonly ok: true; readonly command: ThinCommand } | { readonly ok: false; readonly code: string; readonly nextAction: string; readonly json: boolean };
export interface ThinCliInput { readonly name: string; readonly kind: "single" | "repeated" | "boolean"; readonly required: boolean; readonly enum?: readonly string[]; readonly regex?: string; readonly error: { readonly code: string; readonly nextAction: string }; } type ProtocolCommand = (typeof daemonProtocolCommands)[number]; type ThinCliInputDirectory = ReadonlyMap<string, readonly ThinCliInput[]>;
export function deriveThinCliInputs(command: { readonly id: string; readonly inputs?: readonly unknown[]; readonly flags?: readonly unknown[] }): readonly ThinCliInput[] { if (!Array.isArray(command.inputs)) throw new Error(`${command.id} inputs must be an array`); const names = new Set<string>(); for (const value of command.inputs) { if (!isInput(value) || names.has(value.name)) throw new Error(`${command.id} has an invalid input facet`); names.add(value.name); if (value.enum !== undefined && (!Array.isArray(value.enum) || value.enum.length === 0 || value.enum.some((entry) => !nonEmpty(entry)))) throw new Error(`${command.id}:${value.name} enum is invalid`); if (value.regex !== undefined) try { void new RegExp(value.regex, "u"); } catch { throw new Error(`${command.id}:${value.name} regex is invalid`); } } if (!Array.isArray(command.flags) || JSON.stringify(command.flags) !== JSON.stringify(command.inputs)) throw new Error(`${command.id} inputs and flags differ`); return Object.freeze(command.inputs as readonly ThinCliInput[]); }
function isInput(value: unknown): value is ThinCliInput { if (value === null || typeof value !== "object") return false; const input = value as Partial<ThinCliInput>; return typeof input.name === "string" && input.name.startsWith("--") && ["single", "repeated", "boolean"].includes(input.kind ?? "") && Object.hasOwn(input, "required") && typeof input.required === "boolean" && input.error !== undefined && typeof input.error.code === "string" && nonEmpty(input.error.nextAction); } function deriveInputDirectory(commands: readonly { readonly id: string; readonly inputs?: readonly unknown[]; readonly flags?: readonly unknown[] }[]): ThinCliInputDirectory { return new Map(commands.map((command) => [command.id, deriveThinCliInputs(command)])); }
export function parseThinCommand(argv: readonly string[], cwd = process.cwd(), commands: readonly ProtocolCommand[] = daemonProtocolCommands): ThinParseResult {
  const rootDir = safePath(globalOption(argv, "--root") ?? cwd), repoId = globalOption(argv, "--repo"), json = argv.includes("--json"), args = stripGlobals(argv), route = commands === daemonProtocolCommands ? resolveThinCliCommand(args) : commands.find((entry) => entry.path.every((token, index) => args[index] === token)), inputs = deriveInputDirectory(commands);
  const routed = parseRouted(route, args, rootDir, repoId, json, inputs); if (routed) return routed;
  if (!route || args[0] !== "task") return rejected("unsupported_command", "Only task lifecycle, receipt show, and explicit daemon commands exist on rebuild.", json);
  return parseTask(route.id, args, rootDir, repoId, json, inputs);
}
function parseRouted(route: ProtocolCommand | undefined, args: readonly string[], rootDir: SafePath, repoId: string | undefined, json: boolean, inputs: ThinCliInputDirectory): ThinParseResult | undefined {
  if (route?.id === "repo-bootstrap") { const f = readFlags(route.id, args.slice(1), inputs); if (!f.ok) return rejected(f.code, f.nextAction, json); return accepted(rootDir, undefined, json, { kind: "repo-bootstrap", repoId: f.one.get("--repo-id"), personId: f.one.get("--person-id"), displayName: f.one.get("--display-name") }); }
  if (route?.id === "receipt-show" && nonEmpty(args[2]) && args.length === 3) return accepted(rootDir, repoId, json, { kind: "receipt-show", opId: args[2] });
  if (route?.id.startsWith("doc-")) return parseDoc(route.id, args, rootDir, repoId, json, inputs); if (route?.id.startsWith("fact-")) return parseFact(route.id, args, rootDir, repoId, json, inputs); if (route?.id.startsWith("decision-")) return parseDecision(route.id, args, rootDir, repoId, json, inputs);
  if (route?.phase.startsWith("Preset-")) return parsePreset(route, args, rootDir, repoId, json, inputs); return undefined;
}
function parsePreset(route: ProtocolCommand, args: readonly string[], rootDir: SafePath, repoId: string | undefined, json: boolean, inputs: ThinCliInputDirectory): ThinParseResult {
  const positionalField = "positional" in route ? route.positional : undefined, positionalFields = "positionalFields" in route ? route.positionalFields : undefined, positional = positionalField ? args[route.path.length] : undefined, offset = route.path.length + (positionalField ? 1 : 0), f = readFlags(route.id, args.slice(offset), inputs); if (!f.ok) return rejected(f.code, f.nextAction, json); if (positionalField && !nonEmpty(positional)) return rejected("missing_field", `${positionalField} is required.`, json);
  const matched = positionalFields && positional ? /^preset:([a-z0-9][a-z0-9-]{0,127})\/([A-Za-z0-9._-]+)$/u.exec(positional) : null; if (positionalFields && !matched) return rejected("invalid_field", "Use preset:<id>/<entrypoint>.", json); let payload: Record<string, unknown>; const declared = route.inputs as readonly (ThinCliInput & { readonly field: string; readonly codec?: "json" })[];
  try { payload = Object.fromEntries(declared.flatMap((input) => { const value = f.one.get(input.name); return value ? [[input.field, input.codec === "json" ? JSON.parse(value) : value]] : []; })); } catch { return rejectInput(inputs, route.id, "--inputs", json); }
  const position = matched && positionalFields ? { [positionalFields[0]]: matched[1], [positionalFields[1]]: matched[2] } : positionalField ? { [positionalField]: positional } : {}; return accepted(rootDir, repoId, json, { kind: route.id, ...position, ...payload }, route.method);
}
function parseTask(id: string, args: readonly string[], rootDir: SafePath, repoId: string | undefined, json: boolean, inputs: ThinCliInputDirectory): ThinParseResult { const verb = args[1]; if (id === "task-show" && nonEmpty(args[2]) && args.length === 3) return accepted(rootDir, repoId, json, { kind: "task-show", verb, taskId: args[2] }); const taskId = args[2]; if (!nonEmpty(taskId)) return rejected("missing_field", `Run ha task ${verb ?? "<verb>"} <task-id>.`, json); if (id === "task-start") return oneExecution(rootDir, repoId, json, args, taskId, "task-start", "StartExecution", inputs); if (id === "task-submit") return parseSubmit(rootDir, repoId, json, args, taskId, inputs); if (id === "task-review-execution") return parseReview(rootDir, repoId, json, args, taskId, inputs); if (id === "task-complete") return oneExecution(rootDir, repoId, json, args, taskId, "task-complete", "CompleteTask", inputs, "--gate-receipt"); return rejected("unsupported_command", "Use task create, start, submit, review-execution, complete, or show.", json); }
function parseSubmit(rootDir: SafePath, repoId: string | undefined, json: boolean, args: readonly string[], taskId: string, inputs: ThinCliInputDirectory): ThinParseResult { const f = readFlags("task-submit", args.slice(3), inputs); if (!f.ok) return rejected(f.code, f.nextAction, json); return accepted(rootDir, repoId, json, { kind: "task-submit", verb: args[1], commandType: "SubmitExecution", taskId, executionId: f.one.get("--execution-id"), claim: f.one.get("--claim"), commitSha: f.one.get("--commit-sha"), deliverables: f.many.get("--deliverable") ?? [], evidenceRefs: f.many.get("--evidence-ref") ?? [], verification: f.many.get("--verification") ?? [], knownGaps: f.many.get("--known-gap") ?? [], residualRisks: f.many.get("--residual-risk") ?? [] }); }
function parseReview(rootDir: SafePath, repoId: string | undefined, json: boolean, args: readonly string[], taskId: string, inputs: ThinCliInputDirectory): ThinParseResult { const f = readFlags("task-review-execution", args.slice(3), inputs); if (!f.ok) return rejected(f.code, f.nextAction, json); return accepted(rootDir, repoId, json, { kind: "task-review-execution", verb: args[1], commandType: "RecordReview", taskId, executionId: f.one.get("--execution-id"), reviewKind: f.one.get("--kind"), verdict: f.one.get("--verdict"), reviewId: f.one.get("--review-id"), reason: f.one.get("--reason"), commitSha: f.one.get("--commit-sha"), iteration: Number(f.one.get("--iteration")), evidenceChecked: f.many.get("--evidence-checked") ?? [], archiveWarningsAcknowledged: f.booleans.has("--acknowledge-archive-warnings") }); }
function parseDoc(id: string, args: readonly string[], rootDir: SafePath, repoId: string | undefined, json: boolean, inputs: ThinCliInputDirectory): ThinParseResult { if (id === "doc-materialize") return args.length === 2 ? accepted(rootDir, repoId, json, { kind: id }) : rejected("unknown_field", "ha doc materialize takes no options.", json); const sync = id === "doc-sync-submit" || id === "doc-sync-dry-run", f = readFlags(id, args.slice(sync ? 3 : 2), inputs); if (!f.ok) return rejected(f.code, f.nextAction, json); const paths = f.many.get("--path") ?? []; if (id === "doc-show") return accepted(rootDir, repoId, json, { kind: id, path: f.one.get("--path") }); if (id === "doc-status") return accepted(rootDir, repoId, json, { kind: id, paths }); if (id === "doc-sync-dry-run") return accepted(rootDir, repoId, json, { kind: "doc-dry-run", paths }); const executionId = f.one.get("--execution-id"); return accepted(rootDir, repoId, json, { kind: "doc-submit", ...(executionId ? { executionId } : {}), paths }); }
function parseFact(id: string, args: readonly string[], rootDir: SafePath, repoId: string | undefined, json: boolean, inputs: ThinCliInputDirectory): ThinParseResult { if (id === "fact-record") return parseFactRecord(args, rootDir, repoId, json, inputs); if (id === "fact-search") return parseFactSearch(args, rootDir, repoId, json, inputs); if (id === "fact-show") return parseFactShow(args, rootDir, repoId, json, inputs); return rejected("unsupported_command", "Use fact record, search, or show.", json); }
function parseFactRecord(args: readonly string[], rootDir: SafePath, repoId: string | undefined, json: boolean, inputs: ThinCliInputDirectory): ThinParseResult { const f = readFlags("fact-record", args.slice(2), inputs); if (!f.ok) return rejected(f.code, f.nextAction, json); const taskId = f.one.get("--task"), statement = f.one.get("--statement"), evidenceSource = f.one.get("--source"), observedAt = f.one.get("--observed-at"), confidence = f.one.get("--confidence") ?? "medium", memoryClass = f.one.get("--memory-class") ?? "episodic", supersedes = f.one.get("--supersedes"), rationale = f.one.get("--rationale"); if (Boolean(supersedes) !== Boolean(rationale)) return rejectInput(inputs, "fact-record", "--rationale", json); return accepted(rootDir, repoId, json, { kind: "fact-record", taskId, statement, evidenceSource, ...(observedAt ? { observedAt } : {}), confidence, memoryClass, memoryTags: f.many.get("--memory-tag") ?? [], ...(supersedes && rationale ? { supersedes: { factRef: supersedes, rationale } } : {}) }); }
function parseFactSearch(args: readonly string[], rootDir: SafePath, repoId: string | undefined, json: boolean, inputs: ThinCliInputDirectory): ThinParseResult { const query = args[2]?.startsWith("--") ? undefined : args[2], f = readFlags("fact-search", args.slice(query ? 3 : 2), inputs); if (!f.ok) return rejected(f.code, f.nextAction, json); const confidence = f.one.get("--confidence"), memoryClass = f.one.get("--memory-class"); return accepted(rootDir, repoId, json, { kind: "fact-search", ...(query ? { query } : {}), ...(f.one.get("--task") ? { taskId: f.one.get("--task") } : {}), ...(confidence ? { confidence } : {}), ...(memoryClass ? { memoryClass } : {}) }); }
function parseFactShow(args: readonly string[], rootDir: SafePath, repoId: string | undefined, json: boolean, inputs: ThinCliInputDirectory): ThinParseResult { const f = readFlags("fact-show", args.slice(2), inputs); if (!f.ok) return rejected(f.code, f.nextAction, json); return accepted(rootDir, repoId, json, { kind: "fact-show", taskId: f.one.get("--task"), factId: f.one.get("--id") }); }
function parseDecision(id: string, args: readonly string[], rootDir: SafePath, repoId: string | undefined, json: boolean, inputs: ThinCliInputDirectory): ThinParseResult { const noId = id === "decision-propose" || id === "decision-search", nested = id.startsWith("decision-claim-") || id === "decision-relation-retire", decisionId = noId ? undefined : args[nested ? 3 : 2]; if (!noId && !nonEmpty(decisionId)) return rejected("missing_field", "Decision id is required.", json); if (id === "decision-propose") return parseProposal(args, rootDir, repoId, json, inputs); if (["decision-accept", "decision-reject", "decision-defer"].includes(id)) return parseDisposition(id, decisionId!, args, rootDir, repoId, json, inputs); if (id === "decision-retire") return parseReason(id, decisionId!, args.slice(3), rootDir, repoId, json, inputs); if (id.startsWith("decision-claim-")) return parseClaim(id, decisionId!, args, rootDir, repoId, json, inputs); if (id === "decision-relate" || id === "decision-relation-retire") return parseDecisionRelation(id, decisionId!, args, rootDir, repoId, json, inputs); if (id === "decision-reckon") return parseReckon(decisionId!, args, rootDir, repoId, json, inputs); if (id === "decision-search" || id === "decision-show") return parseDecisionRead(id, decisionId, args, rootDir, repoId, json, inputs); return rejected("unsupported_command", "Use a canonical Decision command.", json); }
function parseProposal(args: readonly string[], rootDir: SafePath, repoId: string | undefined, json: boolean, inputs: ThinCliInputDirectory): ThinParseResult { const f = readFlags("decision-propose", args.slice(2), inputs); if (!f.ok) return rejected(f.code, f.nextAction, json); const chosen = jsonValues(f.many.get("--chosen") ?? []), rejectedOptions = jsonValues(f.many.get("--rejected") ?? []); if (!chosen || !rejectedOptions) return rejectInput(inputs, "decision-propose", "--chosen", json); return accepted(rootDir, repoId, json, { kind: "decision-propose", title: f.one.get("--title"), question: f.one.get("--question"), riskTier: f.one.get("--risk-tier") ?? "medium", urgency: f.one.get("--urgency") ?? "medium", vertical: f.one.get("--vertical") ?? "default", preset: f.one.get("--preset") ?? "default", decisionClass: f.one.get("--decision-class") ?? "ordinary", appliesTo: { modules: f.many.get("--module") ?? [], productLines: f.many.get("--product-line") ?? [] }, chosen, rejected: rejectedOptions }); }
function parseDisposition(id: string, decisionId: string, args: readonly string[], rootDir: SafePath, repoId: string | undefined, json: boolean, inputs: ThinCliInputDirectory): ThinParseResult { const f = readFlags(id, args.slice(3), inputs); if (!f.ok) return rejected(f.code, f.nextAction, json); const rationale = f.one.get("--rationale"); return accepted(rootDir, repoId, json, { kind: id, decisionId, ...(id === "decision-accept" ? { rationale } : { reason: rationale }) }); }
function parseReason(id: string, decisionId: string, tokens: readonly string[], rootDir: SafePath, repoId: string | undefined, json: boolean, inputs: ThinCliInputDirectory): ThinParseResult { const f = readFlags(id, tokens, inputs); return f.ok ? accepted(rootDir, repoId, json, { kind: id, decisionId, reason: f.one.get("--reason") }) : rejected(f.code, f.nextAction, json); }
function parseClaim(id: string, decisionId: string, args: readonly string[], rootDir: SafePath, repoId: string | undefined, json: boolean, inputs: ThinCliInputDirectory): ThinParseResult { const add = id === "decision-claim-add", f = readFlags(id, args.slice(4), inputs); if (!f.ok) return rejected(f.code, f.nextAction, json); const claimId = f.one.get("--id"); return add ? accepted(rootDir, repoId, json, { kind: id, decisionId, claimId, text: f.one.get("--text"), loadBearing: !f.booleans.has("--non-load-bearing") }) : accepted(rootDir, repoId, json, { kind: id, decisionId, claimId, mode: f.one.get("--mode") }); }
function parseDecisionRelation(id: string, decisionId: string, args: readonly string[], rootDir: SafePath, repoId: string | undefined, json: boolean, inputs: ThinCliInputDirectory): ThinParseResult { const retire = id === "decision-relation-retire", f = readFlags(id, args.slice(retire ? 4 : 3), inputs); if (!f.ok) return rejected(f.code, f.nextAction, json); if (retire) return accepted(rootDir, repoId, json, { kind: id, decisionId, relationId: f.one.get("--relation"), reason: f.one.get("--reason") }); return accepted(rootDir, repoId, json, { kind: id, decisionId, ...(f.one.get("--anchor") ? { anchor: f.one.get("--anchor") } : {}), relationType: f.one.get("--type"), target: f.one.get("--target"), rationale: f.one.get("--rationale") }); }
function parseReckon(decisionId: string, args: readonly string[], rootDir: SafePath, repoId: string | undefined, json: boolean, inputs: ThinCliInputDirectory): ThinParseResult { const f = readFlags("decision-reckon", args.slice(3), inputs); return f.ok ? accepted(rootDir, repoId, json, { kind: "decision-reckon", decisionId, taskId: f.one.get("--task") }) : rejected(f.code, f.nextAction, json); }
function parseDecisionRead(id: string, decisionId: string | undefined, args: readonly string[], rootDir: SafePath, repoId: string | undefined, json: boolean, inputs: ThinCliInputDirectory): ThinParseResult { if (id === "decision-show") { const f = readFlags(id, args.slice(3), inputs); return f.ok ? accepted(rootDir, repoId, json, { kind: id, decisionId, includeBody: f.booleans.has("--include-body") }) : rejected(f.code, f.nextAction, json); } const query = args[2]?.startsWith("--") ? undefined : args[2], f = readFlags(id, args.slice(query ? 3 : 2), inputs); if (!f.ok) return rejected(f.code, f.nextAction, json); const state = f.one.get("--state"); return accepted(rootDir, repoId, json, { kind: id, ...(query ? { query } : {}), ...(state ? { state } : {}), ...(f.one.get("--risk-tier") ? { riskTier: f.one.get("--risk-tier") } : {}), ...(f.one.get("--vertical") ? { vertical: f.one.get("--vertical") } : {}) }); }
function oneExecution(rootDir: SafePath, repoId: string | undefined, json: boolean, args: readonly string[], taskId: string, kind: string, commandType: string, inputs: ThinCliInputDirectory, repeated?: string): ThinParseResult { const f = readFlags(kind, args.slice(3), inputs); if (!f.ok) return rejected(f.code, f.nextAction, json); const gateReceipts: { readonly gateId: string; readonly receiptRef: string }[] = []; if (repeated) for (const value of f.many.get(repeated) ?? []) { const parsed = splitGateReceipt(value); if (!parsed) return rejectInput(inputs, kind, repeated, json); gateReceipts.push(parsed); } return accepted(rootDir, repoId, json, { kind, verb: args[1], commandType, taskId, executionId: f.one.get("--execution-id"), ...(repeated ? { gateReceipts } : {}) }); }
function readFlags(commandId: string, tokens: readonly string[], directory: ThinCliInputDirectory): { readonly ok: true; readonly one: Map<string, string>; readonly many: Map<string, string[]>; readonly booleans: Set<string> } | { readonly ok: false; readonly code: string; readonly nextAction: string } { const inputs = directory.get(commandId) ?? [], singles = new Set<string>(), repeated = new Set<string>(), booleans = new Set<string>(), one = new Map<string, string>(), many = new Map<string, string[]>(), flags = new Set<string>(); for (const input of inputs) (input.kind === "single" ? singles : input.kind === "repeated" ? repeated : booleans).add(input.name); for (let index = 0; index < tokens.length;) { const name = tokens[index]; if (name && booleans.has(name)) { if (flags.has(name)) return { ok: false, code: "duplicate_field", nextAction: `${name} may appear once.` }; flags.add(name); index += 1; continue; } const input = inputs.find((candidate) => candidate.name === name), value = tokens[index + 1]; if (!input || !singles.has(input.name) && !repeated.has(input.name)) return { ok: false, code: "unknown_field", nextAction: `Unknown option ${name ?? "<missing>"}.` }; if (!nonEmpty(value) || value.startsWith("--")) return { ok: false, ...input.error }; if (singles.has(input.name)) { if (one.has(input.name)) return { ok: false, code: "duplicate_field", nextAction: `${input.name} may appear once.` }; one.set(input.name, value); } else many.set(input.name, [...many.get(input.name) ?? [], value]); index += 2; } for (const input of inputs) { const values = input.kind === "single" ? one.has(input.name) ? [one.get(input.name)!] : [] : input.kind === "repeated" ? many.get(input.name) ?? [] : flags.has(input.name) ? [input.name] : []; if (input.required && values.length === 0) return { ok: false, ...input.error }; if (values.some((value) => input.enum !== undefined && !input.enum.includes(value) || input.regex !== undefined && !new RegExp(input.regex, "u").test(value))) return { ok: false, ...input.error }; } return { ok: true, one, many, booleans: flags }; }
function rejectInput(directory: ThinCliInputDirectory, commandId: string, name: string, json: boolean): ThinParseResult { const error = directory.get(commandId)?.find((input) => input.name === name)?.error; return rejected(error?.code ?? "invalid_field", error?.nextAction ?? `${name} is invalid.`, json); }
function jsonValues(values: readonly string[]): readonly unknown[] | null { try { const parsed = values.map((value) => JSON.parse(value) as unknown); return parsed.every((value) => value && typeof value === "object" && !Array.isArray(value)) ? parsed : null; } catch (error) { consumeKnownError(error); return null; } } function consumeKnownError(error: unknown): void { void error; }
function splitGateReceipt(value: string): { readonly gateId: string; readonly receiptRef: string } | undefined { const at = value.indexOf(":"); return at < 1 || at === value.length - 1 ? undefined : { gateId: value.slice(0, at), receiptRef: value.slice(at + 1) }; }
function accepted(rootDir: SafePath, repoId: string | undefined, json: boolean, action: ThinCommand["action"], method = "repo.task.run"): ThinParseResult { return { ok: true, command: { rootDir, ...(repoId ? { repoId } : {}), json, method, action } }; }
function rejected(code: string, nextAction: string, json: boolean): ThinParseResult { return { ok: false, code, nextAction, json }; }
function globalOption(argv: readonly string[], name: string): string | undefined { const at = argv.indexOf(name); return at < 0 ? undefined : argv[at + 1]; }
function stripGlobals(argv: readonly string[]): string[] { return argv.filter((value, index) => value !== "--json" && !["--root", "--repo"].includes(value) && !["--root", "--repo"].includes(argv[index - 1] ?? "")); }
function nonEmpty(value: string | undefined): value is string { return typeof value === "string" && value.trim().length > 0; }
