import { daemonProtocolCommands, resolveThinCliCommand, safePath, thinCliCommands, type SafePath } from "../../../daemon/src/protocol/daemon-protocol.contract.ts";
export const thinCliLocalErrorCodes = Object.freeze(["daemon_disconnect", "duplicate_field", "invalid_field", "missing_field", "unknown_field", "unsupported_command"]);
export function renderThinHelp(): string { return ["Harness Anything thin CLI", "", "Commands:", ...thinCliCommands.map(({ usage, summary }) => `  ${usage}\n    ${summary}`)].join("\n"); }
export interface ThinCommand { readonly rootDir: SafePath; readonly repoId?: string; readonly json: boolean; readonly method: string; readonly action: Readonly<Record<string, unknown>> & { readonly kind: string }; }
export type ThinParseResult = { readonly ok: true; readonly command: ThinCommand } | { readonly ok: false; readonly code: string; readonly nextAction: string; readonly json: boolean };
export interface ThinCliInput { readonly name: string; readonly kind: "single" | "repeated" | "boolean"; readonly required: boolean; }
export function deriveThinCliInputs(command: { readonly id: string; readonly path: readonly string[]; readonly usage: string; readonly flags?: readonly { readonly name: string }[] }): readonly ThinCliInput[] { const inputs = [...command.usage.matchAll(/--[a-z][a-z0-9-]*/gu)].flatMap((match) => { const name = match[0]; if (command.path.includes(name)) return []; const prefix = command.usage.slice(0, match.index), tail = command.usage.slice((match.index ?? 0) + name.length), value = /^\s+(<\S+)/u.exec(tail)?.[1]; return [Object.freeze({ name, kind: value ? value.endsWith("...") ? "repeated" : "single" : /^\]?\.\.\./u.test(tail) ? "repeated" : "boolean", required: prefix.lastIndexOf("[") <= prefix.lastIndexOf("]") })]; }); if (command.flags) { const declared = new Set(command.flags.map(({ name }) => name)), derived = new Set(inputs.map(({ name }) => name)); if (declared.size !== derived.size || [...declared].some((name) => !derived.has(name))) throw new Error(`${command.id} usage and flags differ`); } return Object.freeze(inputs); }
const thinCliInputDirectory = new Map<string, readonly ThinCliInput[]>(daemonProtocolCommands.map((command) => [command.id, deriveThinCliInputs(command)]));
export function parseThinCommand(argv: readonly string[], cwd = process.cwd()): ThinParseResult {
  const rootDir = safePath(globalOption(argv, "--root") ?? cwd), repoId = globalOption(argv, "--repo"), json = argv.includes("--json"), args = stripGlobals(argv), route = resolveThinCliCommand(args);
  const routed = parseRouted(route, args, rootDir, repoId, json); if (routed) return routed;
  if (!route || args[0] !== "task") return rejected("unsupported_command", "Only task lifecycle, receipt show, and explicit daemon commands exist on rebuild.", json);
  return parseTask(route.id, args, rootDir, repoId, json);
}
function parseRouted(route: ReturnType<typeof resolveThinCliCommand>, args: readonly string[], rootDir: SafePath, repoId: string | undefined, json: boolean): ThinParseResult | undefined {
  if (route?.id === "repo-bootstrap") { const f = readFlags(route.id, args.slice(1)), initRepoId = f.ok ? f.one.get("--repo-id") : undefined, personId = f.ok ? f.one.get("--person-id") : undefined, displayName = f.ok ? f.one.get("--display-name") : undefined; if (!f.ok) return rejected(f.code, f.nextAction, json); return nonEmpty(initRepoId) && nonEmpty(personId) && nonEmpty(displayName) ? accepted(rootDir, undefined, json, { kind: "repo-bootstrap", repoId: initRepoId, personId, displayName }) : rejected("missing_field", "Init requires repo-id, person-id, and display-name.", json); }
  if (route?.id === "receipt-show" && nonEmpty(args[2]) && args.length === 3) return accepted(rootDir, repoId, json, { kind: "receipt-show", opId: args[2] });
  if (route?.id.startsWith("doc-")) return parseDoc(route.id, args, rootDir, repoId, json); if (route?.id.startsWith("fact-")) return parseFact(route.id, args, rootDir, repoId, json); if (route?.id.startsWith("decision-")) return parseDecision(route.id, args, rootDir, repoId, json);
  if (route?.phase.startsWith("Preset-") && "flags" in route) return parsePreset(route, args, rootDir, repoId, json); return undefined;
}
function parsePreset(route: NonNullable<ReturnType<typeof resolveThinCliCommand>>, args: readonly string[], rootDir: SafePath, repoId: string | undefined, json: boolean): ThinParseResult {
  if (!("flags" in route)) return rejected("unsupported_command", "Use a preset command.", json); const positionalField = "positional" in route ? route.positional : undefined, positionalFields = "positionalFields" in route ? route.positionalFields : undefined, positional = positionalField ? args[route.path.length] : undefined, offset = route.path.length + (positionalField ? 1 : 0), f = readFlags(route.id, args.slice(offset)); if (!f.ok) return rejected(f.code, f.nextAction, json); if (positionalField && !nonEmpty(positional)) return rejected("missing_field", `${positionalField} is required.`, json);
  const matched = positionalFields && positional ? /^preset:([a-z0-9][a-z0-9-]{0,127})\/([A-Za-z0-9._-]+)$/u.exec(positional) : null; if (positionalFields && !matched) return rejected("invalid_field", "Use preset:<id>/<entrypoint>.", json); let payload: Record<string, unknown>;
  try { payload = Object.fromEntries(route.flags.flatMap((flag) => { const value = f.one.get(flag.name); return value ? [[flag.field, "codec" in flag && flag.codec === "json" ? JSON.parse(value) : value]] : []; })); } catch { return rejected("invalid_field", "--inputs must be a JSON object.", json); }
  for (const flag of route.flags) if ("required" in flag && flag.required && !payload[flag.field]) return rejected("missing_field", `${flag.name} is required.`, json); const position = matched && positionalFields ? { [positionalFields[0]]: matched[1], [positionalFields[1]]: matched[2] } : positionalField ? { [positionalField]: positional } : {}; return accepted(rootDir, repoId, json, { kind: route.id, ...position, ...payload }, route.method);
}
function parseTask(id: string, args: readonly string[], rootDir: SafePath, repoId: string | undefined, json: boolean): ThinParseResult { const verb = args[1]; if (id === "task-show" && nonEmpty(args[2]) && args.length === 3) return accepted(rootDir, repoId, json, { kind: "task-show", verb, taskId: args[2] }); const taskId = args[2]; if (!nonEmpty(taskId)) return rejected("missing_field", `Run ha task ${verb ?? "<verb>"} <task-id>.`, json); if (id === "task-start") return oneExecution(rootDir, repoId, json, args, taskId, "task-start", "StartExecution"); if (id === "task-submit") return parseSubmit(rootDir, repoId, json, args, taskId); if (id === "task-review-execution") return parseReview(rootDir, repoId, json, args, taskId); if (id === "task-complete") return oneExecution(rootDir, repoId, json, args, taskId, "task-complete", "CompleteTask", "--gate-receipt"); return rejected("unsupported_command", "Use task create, start, submit, review-execution, complete, or show.", json); }
function parseSubmit(rootDir: SafePath, repoId: string | undefined, json: boolean, args: readonly string[], taskId: string): ThinParseResult { const f = readFlags("task-submit", args.slice(3)); if (!f.ok) return rejected(f.code, f.nextAction, json); const executionId = f.one.get("--execution-id"), claim = f.one.get("--claim"), commitSha = f.one.get("--commit-sha"); if (!nonEmpty(executionId) || !nonEmpty(claim) || !commitSha?.match(/^[0-9a-f]{40}$/u)) return rejected("invalid_field", "Submit requires execution-id, claim, and a 40-character commit-sha.", json); return accepted(rootDir, repoId, json, { kind: "task-submit", verb: args[1], commandType: "SubmitExecution", taskId, executionId, claim, commitSha, deliverables: f.many.get("--deliverable") ?? [], evidenceRefs: f.many.get("--evidence-ref") ?? [], verification: f.many.get("--verification") ?? [], knownGaps: f.many.get("--known-gap") ?? [], residualRisks: f.many.get("--residual-risk") ?? [] }); }
function parseReview(rootDir: SafePath, repoId: string | undefined, json: boolean, args: readonly string[], taskId: string): ThinParseResult { const f = readFlags("task-review-execution", args.slice(3)); if (!f.ok) return rejected(f.code, f.nextAction, json); const executionId = f.one.get("--execution-id"), reviewKind = f.one.get("--kind"), verdict = f.one.get("--verdict"), reviewId = f.one.get("--review-id"), reason = f.one.get("--reason"), commitSha = f.one.get("--commit-sha"), round = Number(f.one.get("--iteration")); if (!nonEmpty(executionId) || !["anti_entropy", "acceptance"].includes(reviewKind ?? "") || !["approved", "changes_requested", "dismissed"].includes(verdict ?? "") || !nonEmpty(reviewId) || !nonEmpty(reason) || !commitSha?.match(/^[0-9a-f]{40}$/u) || round !== 0 && round !== 1) return rejected("invalid_field", "Review requires execution-id, kind, verdict, review-id, reason, commit-sha, and iteration 0|1.", json); return accepted(rootDir, repoId, json, { kind: "task-review-execution", verb: args[1], commandType: "RecordReview", taskId, executionId, reviewKind, verdict, reviewId, reason, commitSha, iteration: round, evidenceChecked: f.many.get("--evidence-checked") ?? [], archiveWarningsAcknowledged: f.booleans.has("--acknowledge-archive-warnings") }); }
function parseDoc(id: string, args: readonly string[], rootDir: SafePath, repoId: string | undefined, json: boolean): ThinParseResult { if (id === "doc-materialize") return args.length === 2 ? accepted(rootDir, repoId, json, { kind: id }) : rejected("unknown_field", "ha doc materialize takes no options.", json); const sync = id === "doc-sync-submit" || id === "doc-sync-dry-run", f = readFlags(id, args.slice(sync ? 3 : 2)); if (!f.ok) return rejected(f.code, f.nextAction, json); const paths = f.many.get("--path") ?? []; if (id === "doc-show") { const selected = f.one.get("--path"); return selected ? accepted(rootDir, repoId, json, { kind: id, path: selected }) : rejected("missing_field", "Add --path <authored-relative-path>.", json); } if (id === "doc-status") return accepted(rootDir, repoId, json, { kind: id, paths }); if (id === "doc-sync-dry-run") return accepted(rootDir, repoId, json, { kind: "doc-dry-run", paths }); const executionId = f.one.get("--execution-id"); return accepted(rootDir, repoId, json, { kind: "doc-submit", ...(executionId ? { executionId } : {}), paths }); }
function parseFact(id: string, args: readonly string[], rootDir: SafePath, repoId: string | undefined, json: boolean): ThinParseResult { if (id === "fact-record") return parseFactRecord(args, rootDir, repoId, json); if (id === "fact-search") return parseFactSearch(args, rootDir, repoId, json); if (id === "fact-show") return parseFactShow(args, rootDir, repoId, json); return rejected("unsupported_command", "Use fact record, search, or show.", json); }
function parseFactRecord(args: readonly string[], rootDir: SafePath, repoId: string | undefined, json: boolean): ThinParseResult { const f = readFlags("fact-record", args.slice(2)); if (!f.ok) return rejected(f.code, f.nextAction, json); const taskId = f.one.get("--task"), statement = f.one.get("--statement"), evidenceSource = f.one.get("--source"), observedAt = f.one.get("--observed-at"), confidence = f.one.get("--confidence") ?? "medium", memoryClass = f.one.get("--memory-class") ?? "episodic", supersedes = f.one.get("--supersedes"), rationale = f.one.get("--rationale"); if (!nonEmpty(taskId) || !nonEmpty(statement) || !nonEmpty(evidenceSource)) return rejected("missing_field", "Fact record requires --task, --statement, and --source.", json); if (!["low", "medium", "high"].includes(confidence) || !["semantic", "episodic", "procedural"].includes(memoryClass) || observedAt !== undefined && !Number.isFinite(Date.parse(observedAt)) || Boolean(supersedes) !== Boolean(rationale) || rationale !== undefined && [...rationale].length > 199) return rejected("invalid_field", "Use valid confidence/memory values and pair --supersedes with a rationale of at most 199 characters.", json); return accepted(rootDir, repoId, json, { kind: "fact-record", taskId, statement, evidenceSource, ...(observedAt ? { observedAt } : {}), confidence, memoryClass, memoryTags: f.many.get("--memory-tag") ?? [], ...(supersedes && rationale ? { supersedes: { factRef: supersedes, rationale } } : {}) }); }
function parseFactSearch(args: readonly string[], rootDir: SafePath, repoId: string | undefined, json: boolean): ThinParseResult { const query = args[2]?.startsWith("--") ? undefined : args[2], f = readFlags("fact-search", args.slice(query ? 3 : 2)); if (!f.ok) return rejected(f.code, f.nextAction, json); const confidence = f.one.get("--confidence"), memoryClass = f.one.get("--memory-class"); if (confidence && !["low", "medium", "high"].includes(confidence) || memoryClass && !["semantic", "episodic", "procedural"].includes(memoryClass)) return rejected("invalid_field", "Fact search filters are invalid.", json); return accepted(rootDir, repoId, json, { kind: "fact-search", ...(query ? { query } : {}), ...(f.one.get("--task") ? { taskId: f.one.get("--task") } : {}), ...(confidence ? { confidence } : {}), ...(memoryClass ? { memoryClass } : {}) }); }
function parseFactShow(args: readonly string[], rootDir: SafePath, repoId: string | undefined, json: boolean): ThinParseResult { const f = readFlags("fact-show", args.slice(2)); if (!f.ok) return rejected(f.code, f.nextAction, json); const taskId = f.one.get("--task"), factId = f.one.get("--id"); if (!nonEmpty(taskId) || !nonEmpty(factId)) return rejected("missing_field", "Fact show requires --task and --id.", json); return /^F-[0-9A-HJKMNP-TV-Z]{8}$/u.test(factId) ? accepted(rootDir, repoId, json, { kind: "fact-show", taskId, factId }) : rejected("invalid_field", "Fact id must use F- plus eight Crockford characters.", json); }
function parseDecision(id: string, args: readonly string[], rootDir: SafePath, repoId: string | undefined, json: boolean): ThinParseResult { const noId = id === "decision-propose" || id === "decision-search", nested = id.startsWith("decision-claim-") || id === "decision-relation-retire", decisionId = noId ? undefined : args[nested ? 3 : 2]; if (!noId && !nonEmpty(decisionId)) return rejected("missing_field", "Decision id is required.", json); if (id === "decision-propose") return parseProposal(args, rootDir, repoId, json); if (["decision-accept", "decision-reject", "decision-defer"].includes(id)) return parseDisposition(id, decisionId!, args, rootDir, repoId, json); if (id === "decision-retire") return parseReason(id, decisionId!, args.slice(3), rootDir, repoId, json); if (id.startsWith("decision-claim-")) return parseClaim(id, decisionId!, args, rootDir, repoId, json); if (id === "decision-relate" || id === "decision-relation-retire") return parseDecisionRelation(id, decisionId!, args, rootDir, repoId, json); if (id === "decision-reckon") return parseReckon(decisionId!, args, rootDir, repoId, json); if (id === "decision-search" || id === "decision-show") return parseDecisionRead(id, decisionId, args, rootDir, repoId, json); return rejected("unsupported_command", "Use a canonical Decision command.", json); }
function parseProposal(args: readonly string[], rootDir: SafePath, repoId: string | undefined, json: boolean): ThinParseResult { const f = readFlags("decision-propose", args.slice(2)); if (!f.ok) return rejected(f.code, f.nextAction, json); const title = f.one.get("--title"), question = f.one.get("--question"), chosenRaw = f.many.get("--chosen"), rejectedRaw = f.many.get("--rejected"); if (!nonEmpty(title) || !nonEmpty(question) || [...question].length > 499 || !chosenRaw?.length || !rejectedRaw?.length) return rejected("invalid_field", "Propose requires title, a question of at most 499 characters, chosen JSON, and rejected JSON.", json); const chosen = jsonValues(chosenRaw), rejectedOptions = jsonValues(rejectedRaw); return chosen && rejectedOptions ? accepted(rootDir, repoId, json, { kind: "decision-propose", title, question, riskTier: f.one.get("--risk-tier") ?? "medium", urgency: f.one.get("--urgency") ?? "medium", vertical: f.one.get("--vertical") ?? "default", preset: f.one.get("--preset") ?? "default", decisionClass: f.one.get("--decision-class") ?? "ordinary", appliesTo: { modules: f.many.get("--module") ?? [], productLines: f.many.get("--product-line") ?? [] }, chosen, rejected: rejectedOptions }) : rejected("invalid_field", "Chosen and rejected values must be JSON objects.", json); }
function parseDisposition(id: string, decisionId: string, args: readonly string[], rootDir: SafePath, repoId: string | undefined, json: boolean): ThinParseResult { const f = readFlags(id, args.slice(3)); if (!f.ok) return rejected(f.code, f.nextAction, json); const rationale = f.one.get("--rationale"); return short(rationale) ? accepted(rootDir, repoId, json, { kind: id, decisionId, ...(id === "decision-accept" ? { rationale } : { reason: rationale }) }) : rejected("invalid_field", "A rationale of 1..199 characters is required.", json); }
function parseReason(id: string, decisionId: string, tokens: readonly string[], rootDir: SafePath, repoId: string | undefined, json: boolean): ThinParseResult { const f = readFlags(id, tokens); if (!f.ok) return rejected(f.code, f.nextAction, json); const reason = f.one.get("--reason"); return short(reason) ? accepted(rootDir, repoId, json, { kind: id, decisionId, reason }) : rejected("invalid_field", "A reason of 1..199 characters is required.", json); }
function parseClaim(id: string, decisionId: string, args: readonly string[], rootDir: SafePath, repoId: string | undefined, json: boolean): ThinParseResult { const add = id === "decision-claim-add", f = readFlags(id, args.slice(4)); if (!f.ok) return rejected(f.code, f.nextAction, json); const claimId = f.one.get("--id"); if (!claimId?.match(/^C[A-Za-z0-9_-]+$/u)) return rejected("invalid_field", "Claim requires a C-prefixed --id.", json); if (add) { const text = f.one.get("--text"); return nonEmpty(text) ? accepted(rootDir, repoId, json, { kind: id, decisionId, claimId, text, loadBearing: !f.booleans.has("--non-load-bearing") }) : rejected("invalid_field", "Claim requires --text.", json); } const mode = f.one.get("--mode"); return ["evidenced", "delivered", "standing_policy"].includes(mode ?? "") ? accepted(rootDir, repoId, json, { kind: id, decisionId, claimId, mode }) : rejected("invalid_field", "Fulfillment requires evidenced|delivered|standing_policy mode.", json); }
function parseDecisionRelation(id: string, decisionId: string, args: readonly string[], rootDir: SafePath, repoId: string | undefined, json: boolean): ThinParseResult { const retire = id === "decision-relation-retire", f = readFlags(id, args.slice(retire ? 4 : 3)); if (!f.ok) return rejected(f.code, f.nextAction, json); if (retire) { const relationId = f.one.get("--relation"), reason = f.one.get("--reason"); return relationId?.match(/^rel_[0-9a-f]{16}$/u) && short(reason) ? accepted(rootDir, repoId, json, { kind: id, decisionId, relationId, reason }) : rejected("invalid_field", "Relation retire requires a deterministic relation id and reason.", json); } const relationType = f.one.get("--type"), target = f.one.get("--target"), rationale = f.one.get("--rationale"); return nonEmpty(relationType) && nonEmpty(target) && short(rationale) ? accepted(rootDir, repoId, json, { kind: id, decisionId, ...(f.one.get("--anchor") ? { anchor: f.one.get("--anchor") } : {}), relationType, target, rationale }) : rejected("invalid_field", "Relate requires type, target, and a rationale of 1..199 characters.", json); }
function parseReckon(decisionId: string, args: readonly string[], rootDir: SafePath, repoId: string | undefined, json: boolean): ThinParseResult { const f = readFlags("decision-reckon", args.slice(3)); if (!f.ok) return rejected(f.code, f.nextAction, json); const taskId = f.one.get("--task"); return nonEmpty(taskId) ? accepted(rootDir, repoId, json, { kind: "decision-reckon", decisionId, taskId }) : rejected("missing_field", "Reckon requires --task.", json); }
function parseDecisionRead(id: string, decisionId: string | undefined, args: readonly string[], rootDir: SafePath, repoId: string | undefined, json: boolean): ThinParseResult { if (id === "decision-show") { const f = readFlags(id, args.slice(3)); return f.ok ? accepted(rootDir, repoId, json, { kind: id, decisionId, includeBody: f.booleans.has("--include-body") }) : rejected(f.code, f.nextAction, json); } const query = args[2]?.startsWith("--") ? undefined : args[2], f = readFlags(id, args.slice(query ? 3 : 2)); if (!f.ok) return rejected(f.code, f.nextAction, json); const state = f.one.get("--state"); if (state && !["proposed", "accepted", "rejected", "deferred", "retired"].includes(state)) return rejected("invalid_field", "Decision state filter is invalid.", json); return accepted(rootDir, repoId, json, { kind: id, ...(query ? { query } : {}), ...(state ? { state } : {}), ...(f.one.get("--risk-tier") ? { riskTier: f.one.get("--risk-tier") } : {}), ...(f.one.get("--vertical") ? { vertical: f.one.get("--vertical") } : {}) }); }
function oneExecution(rootDir: SafePath, repoId: string | undefined, json: boolean, args: readonly string[], taskId: string, kind: string, commandType: string, repeated?: string): ThinParseResult { const f = readFlags(kind, args.slice(3)); if (!f.ok) return rejected(f.code, f.nextAction, json); const executionId = f.one.get("--execution-id"); if (!nonEmpty(executionId)) return rejected("missing_field", "Add --execution-id <execution-id>.", json); const gateReceipts: { readonly gateId: string; readonly receiptRef: string }[] = []; if (repeated) for (const value of f.many.get(repeated) ?? []) { const parsed = splitGateReceipt(value); if (!parsed) return rejected("invalid_field", "Use --gate-receipt <gate-id>:<receipt-ref>.", json); gateReceipts.push(parsed); } return accepted(rootDir, repoId, json, { kind, verb: args[1], commandType, taskId, executionId, ...(repeated ? { gateReceipts } : {}) }); }
function readFlags(commandId: string, tokens: readonly string[]): { readonly ok: true; readonly one: Map<string, string>; readonly many: Map<string, string[]>; readonly booleans: Set<string> } | { readonly ok: false; readonly code: string; readonly nextAction: string } { const inputs = thinCliInputDirectory.get(commandId) ?? [], singles = new Set(inputs.filter(({ kind }) => kind === "single").map(({ name }) => name)), repeated = new Set(inputs.filter(({ kind }) => kind === "repeated").map(({ name }) => name)), booleans = new Set(inputs.filter(({ kind }) => kind === "boolean").map(({ name }) => name)), one = new Map<string, string>(), many = new Map<string, string[]>(), flags = new Set<string>(); for (let index = 0; index < tokens.length;) { const name = tokens[index]; if (name && booleans.has(name)) { if (flags.has(name)) return { ok: false, code: "duplicate_field", nextAction: `${name} may appear once.` }; flags.add(name); index += 1; continue; } const value = tokens[index + 1]; if (!name || !singles.has(name) && !repeated.has(name)) return { ok: false, code: "unknown_field", nextAction: `Unknown option ${name ?? "<missing>"}.` }; if (!nonEmpty(value) || value.startsWith("--")) return { ok: false, code: "missing_field", nextAction: `${name} requires a value.` }; if (singles.has(name)) { if (one.has(name)) return { ok: false, code: "duplicate_field", nextAction: `${name} may appear once.` }; one.set(name, value); } else many.set(name, [...many.get(name) ?? [], value]); index += 2; } return { ok: true, one, many, booleans: flags }; }
function jsonValues(values: readonly string[]): readonly unknown[] | null { try { const parsed = values.map((value) => JSON.parse(value) as unknown); return parsed.every((value) => value && typeof value === "object" && !Array.isArray(value)) ? parsed : null; } catch (error) { consumeKnownError(error); return null; } } function consumeKnownError(error: unknown): void { void error; }
function splitGateReceipt(value: string): { readonly gateId: string; readonly receiptRef: string } | undefined { const at = value.indexOf(":"); return at < 1 || at === value.length - 1 ? undefined : { gateId: value.slice(0, at), receiptRef: value.slice(at + 1) }; }
function accepted(rootDir: SafePath, repoId: string | undefined, json: boolean, action: ThinCommand["action"], method = "repo.task.run"): ThinParseResult { return { ok: true, command: { rootDir, ...(repoId ? { repoId } : {}), json, method, action } }; }
function rejected(code: string, nextAction: string, json: boolean): ThinParseResult { return { ok: false, code, nextAction, json }; }
function globalOption(argv: readonly string[], name: string): string | undefined { const at = argv.indexOf(name); return at < 0 ? undefined : argv[at + 1]; }
function stripGlobals(argv: readonly string[]): string[] { return argv.filter((value, index) => value !== "--json" && !["--root", "--repo"].includes(value) && !["--root", "--repo"].includes(argv[index - 1] ?? "")); }
function nonEmpty(value: string | undefined): value is string { return typeof value === "string" && value.trim().length > 0; }
function short(value: string | undefined): value is string { return nonEmpty(value) && [...value].length <= 199; }
