// harness-test-tier: integration
import assert from "node:assert/strict";
import { execFileSync } from "node:child_process";
import { mkdtempSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import path from "node:path";
import test from "node:test";
import { makeTaskEventStore, makeTaskProjection, type AgentRuntimeEventV1, type FrozenWritePlan, type RuntimeSession } from "../../kernel/src/index.ts";
import { makeAgentRuntimeReadModel } from "../src/agent-runtime-read.ts"; import { validateAgentRuntimeOverview } from "../src/agent-runtime-contract.ts";
import { makeAgentRuntimeStreamHub } from "../src/agent-runtime-stream.ts";
import { daemonGuiReadMethods, daemonGuiStreamFacets, jsonRpcMethodContracts } from "../src/protocol/daemon-protocol.contract.ts";
import { parseDaemonGuiReadResult } from "../src/protocol/gui-result-validation.ts";
import { canonicalRoot, workspaceId } from "../src/protocol/daemon-protocol.contract.ts"; import { openRepoCell } from "../src/repo-cell.ts";
import { createJsonRpcProtocolServer } from "../src/protocol/json-rpc-server.ts"; import { currentDaemonProtocolVersion } from "../src/protocol/version.ts"; import type { DaemonHost } from "../src/daemon-host.ts";

const actor = { principal: { personId: "person-runtime" }, executor: null } as const;
test("runtime read facets expose safe overview/session/events through the shared contract registry", () => withRuntime(({ store, projection, stream, events }) => {
  const reads = makeAgentRuntimeReadModel({ store, projection, stream }), overview = parseDaemonGuiReadResult("repo.agentRuntime.overview", reads.overview({}));
  assert.deepEqual(daemonGuiReadMethods.filter(({ phase }) => phase === "Runtime-B").map(({ method }) => method), ["repo.agentRuntime.overview", "repo.agentRuntime.sessions.read", "repo.agentRuntime.events.read"]);
  assert.deepEqual(daemonGuiStreamFacets.filter(({ phase }) => phase === "Runtime-B").map(({ method }) => method), ["repo.agentRuntime.attach"]); assert.equal(jsonRpcMethodContracts.some(({ method }) => method === "repo.agentRuntime.attach"), true);
  assert.deepEqual(overview.installations[0]?.profiles, [{ profileId: "default", label: "Default" }]); assert.deepEqual(overview.installations[0]?.credentialState, "configured"); assert.deepEqual(overview.sessions[0]?.liveness, "live"); assert.deepEqual(overview.sessions[0]?.associations[0], { taskId: "task-runtime", executionId: "execution-runtime", holder: null, lease: null });
  assert.deepEqual(secretKeys(overview), []); assert.deepEqual(reads.session({ runtimeSessionId: "runtime-session" }).session.runtimeSessionId, "runtime-session");
  const lifecycle = reads.events({ runtimeSessionId: "runtime-session", afterCursor: `lifecycle:${events[1]!.workspaceRevision}` }); assert.deepEqual(lifecycle.events.map(({ type }) => type), ["runtime_session_task_bound"]); assert.equal(lifecycle.cursor, `lifecycle:${store.read().revision}`);
  assert.notEqual(validateAgentRuntimeOverview({ ...overview, credential: "secret" }).length, 0); assert.notEqual(validateAgentRuntimeOverview({ ...overview, installations: [{ ...overview.installations[0], credentialState: "configured:secret" }] }).length, 0);
}));

test("attach catches up from cursor, gaps require snapshot, and unsupported is typed", async () => withRuntime(async ({ stream, session }) => {
  for (let index = 0; index < 3; index += 1) stream.publish(session.runtimeSessionId, { type: "activity", activity: index === 2 ? "message" : "thinking" });
  const resumed = stream.attach(session.runtimeSessionId, "stream:1"); assert.equal(resumed.initial.ok && resumed.initial.status, "attached"); assert.deepEqual(resumed.initial.ok && resumed.initial.events.map(({ cursor }) => cursor), ["stream:2", "stream:3"]); resumed.detach();
  for (let index = 0; index < 35; index += 1) stream.publish(session.runtimeSessionId, { type: "heartbeat" });
  const gap = stream.attach(session.runtimeSessionId, "stream:0"); assert.equal(gap.initial.ok && gap.initial.status, "gap"); assert.deepEqual(gap.initial.ok && gap.initial.events[0], { schema: "agent-runtime-attach-event/v1", type: "gap", runtimeSessionId: "runtime-session", cursor: "stream:38", occurredAt: "2026-08-13T00:00:00.000Z", required: "snapshot" }); gap.detach();
  const restarted = makeAgentRuntimeStreamHub({ readSession: () => session, canAttach: ({ attachable }) => attachable, now: () => new Date("2026-08-13T00:00:00.000Z") }).attach(session.runtimeSessionId, "stream:38"); assert.equal(restarted.initial.ok && restarted.initial.status, "gap"); assert.equal(restarted.initial.ok && restarted.initial.events[0]?.type, "gap"); restarted.detach();
  session.attachable = false; const unsupported = stream.attach(session.runtimeSessionId, "stream:38").initial; assert.deepEqual(unsupported, { ok: false, code: "unsupported", runtimeSessionId: "runtime-session", hint: "This provider session does not expose read-only live frames." }); session.attachable = true; const capabilityMissing = makeAgentRuntimeStreamHub({ readSession: () => session, canAttach: () => false }).attach(session.runtimeSessionId, "stream:0").initial; assert.equal(capabilityMissing.ok, false); assert.equal(!capabilityMissing.ok && capabilityMissing.code, "unsupported");
}));

test("slow subscribers gap without blocking daemon writer requests, and detach does not alter the native session", async () => withRuntime(async ({ stream, session }) => {
  const slow = stream.attach(session.runtimeSessionId, "stream:0"), before = structuredClone(session), started = performance.now(); for (let index = 0; index < 2_000; index += 1) stream.publish(session.runtimeSessionId, { type: "heartbeat" }); const elapsed = performance.now() - started;
  assert.equal(elapsed < 200, true, `publication took ${elapsed}ms`); assert.equal((await slow.next())?.type, "gap"); slow.detach(); assert.equal(await slow.next(), null); assert.deepEqual(session, before);
  let writes = 0; const host = { attach: async (_repoId: string, runtimeSessionId: string, afterCursor: string) => stream.attach(runtimeSessionId, afterCursor), run: async () => { writes += 1; return { outcome: "applied", opId: "writer-op" }; }, read: async () => ({}), bootstrap: async () => ({}), admin: async () => ({}), issueRuntimeWitness: async () => stream.issueWitnessToken(session.runtimeSessionId, { principalId: "person-owner", source: "local" }), bindRuntimeWitness: (_repoId: string, token: string) => stream.bindWitness(token), publishRuntimeWitness: (_repoId: string, token: string, signal: Parameters<typeof stream.publish>[1]) => stream.publish(stream.bindWitness(token).runtimeSessionId, signal), status: () => ({ daemonId: "runtime-test", pid: process.pid, repos: [] }), close: async () => undefined } as unknown as DaemonHost;
  const server = createJsonRpcProtocolServer({ host, authContext: { transportKind: "unix-socket" }, emit: () => new Promise(() => undefined) }); await server.handle({ jsonrpc: "2.0", id: 1, method: "protocol.hello", params: { protocolVersion: currentDaemonProtocolVersion } }); await server.handle({ jsonrpc: "2.0", id: 2, method: "repo.agentRuntime.attach", params: { repo: { repoId: "runtime-test" }, payload: { runtimeSessionId: session.runtimeSessionId, afterCursor: "stream:2000" } } }); stream.publish(session.runtimeSessionId, { type: "heartbeat" }); const written = await server.handle({ jsonrpc: "2.0", id: 3, method: "repo.task.create", params: { repo: { repoId: "runtime-test" }, payload: { title: "Runtime" } } }); assert.equal(writes, 1); assert.equal(!Array.isArray(written) && written && "result" in written && written.result.ok, true); server.close();
}));

test("daemon witness token binds a session-scoped agent executor from server state and ignores provider identity fields", () => withRuntime(({ stream, session }) => {
  const issued = stream.issueWitnessToken(session.runtimeSessionId, { principalId: "person-owner", source: "local" }), bound = stream.bindWitness(issued.token); assert.deepEqual(bound, { runtimeSessionId: session.runtimeSessionId, actor: { principal: { personId: "person-owner" }, executor: { kind: "agent", id: `runtime-session:${session.runtimeSessionId}` } }, source: "local" }); assert.deepEqual(stream.bindWitness(issued.token), bound); assert.throws(() => stream.bindWitness("provider-supplied"), /missing or expired/iu);
}));

test("task writes keep aggregate CAS after runtime events advance the shared workspace revision", async () => { const rootDir = mkdtempSync(path.join(tmpdir(), "ha-runtime-task-cas-")); let cell: Awaited<ReturnType<typeof openRepoCell>> | undefined; try { initRepo(rootDir); cell = await openRepoCell({ repoId: workspaceId("runtime-cas"), rootDir: canonicalRoot(rootDir), ownerId: "runtime-cas-1" }); assert.equal((await cell.run({ kind: "task-create", taskId: "task-runtime", title: "Runtime CAS" }, { actor, source: "local" })).outcome, "applied"); await cell.close(); cell = undefined; const runtime = fixtureAtRevision(rootDir, 2); for (const event of runtime) makeTaskEventStore({ repoId: "runtime-cas", rootDir }).append({ event, plan: runtimeWritePlan(event), blobs: [] }); cell = await openRepoCell({ repoId: workspaceId("runtime-cas"), rootDir: canonicalRoot(rootDir), ownerId: "runtime-cas-2" }); assert.equal((await cell.run({ kind: "task-start", taskId: "task-runtime", executionId: "execution-runtime" }, { actor, source: "local" })).outcome, "applied"); } finally { await cell?.close(); rmSync(rootDir, { recursive: true, force: true }); } });

async function withRuntime<T>(use: (fixture: ReturnType<typeof fixture>) => T | Promise<T>): Promise<T> { const rootDir = mkdtempSync(path.join(tmpdir(), "ha-runtime-b-")); try { initRepo(rootDir); return await use(fixture(rootDir)); } finally { rmSync(rootDir, { recursive: true, force: true }); } }
function fixture(rootDir: string) { const store = makeTaskEventStore({ repoId: "runtime-b", rootDir }), projection = makeTaskProjection({ rootDir, eventStore: store }), events = [installation(), started(), taskBound()]; for (const event of events) { store.append({ event, plan: runtimeWritePlan(event), blobs: [] }); projection.apply(event); } const session = projection.readRuntimeSession("runtime-session") as RuntimeSession & { attachable: boolean }, fixedNow = new Date("2026-08-13T00:00:00.000Z"), stream = makeAgentRuntimeStreamHub({ readSession: () => session, canAttach: ({ attachable }) => attachable, now: () => fixedNow }); return { store, projection, stream, events, session }; }
function runtimeWritePlan(event: AgentRuntimeEventV1): FrozenWritePlan { return Object.freeze({ commandType: event.type, targets: Object.freeze([{ kind: "event_file", path: `harness/events/${event.opId}.json`, operation: "create" }, { kind: "event_head", path: "harness/events/head.json", operation: "replace" }, { kind: "projection_invalidation", projection: "agent-runtime/v1", key: event.opId }].map((target) => Object.freeze(target))) }) as FrozenWritePlan; }
function event<T extends AgentRuntimeEventV1["type"]>(type: T, payload: Extract<AgentRuntimeEventV1, { readonly type: T }>["payload"], revision: number): AgentRuntimeEventV1 { return { schema: "agent-runtime-event/v1", eventId: `event-${revision}`, workspaceRevision: revision, opId: `op-${revision}`, actor, source: "local", occurredAt: `2026-08-13T00:00:0${revision}.000Z`, type, payload } as AgentRuntimeEventV1; }
function installation(): AgentRuntimeEventV1 { return event("runtime_installation_observed", { installationId: "installation-runtime", kindId: "codex", protocolFamily: "codex", hostRef: "host:local", version: "1.0.0", discoverySource: "wrapper", capabilities: ["structured_witness", "attach"], authState: "configured" }, 1); }
function started(): AgentRuntimeEventV1 { return event("runtime_session_started", { runtimeSessionId: "runtime-session", installationId: "installation-runtime", kindId: "codex", launchGeneration: 1, attachable: true }, 2); }
function taskBound(): AgentRuntimeEventV1 { return event("runtime_session_task_bound", { runtimeSessionId: "runtime-session", taskId: "task-runtime", executionId: "execution-runtime", providerSessionId: "provider-runtime", transcriptRef: "file:runtime/session.jsonl" }, 3); }
function fixtureAtRevision(_rootDir: string, revision: number): AgentRuntimeEventV1[] { const values = [installation(), started()]; return values.map((value, index) => ({ ...value, eventId: `event-cas-${revision + index}`, opId: `op-cas-${revision + index}`, workspaceRevision: revision + index, occurredAt: `2026-08-13T00:01:0${index}.000Z` } as AgentRuntimeEventV1)); }
function secretKeys(value: unknown, found: string[] = []): string[] { if (Array.isArray(value)) { value.forEach((item) => secretKeys(item, found)); return found; } if (!value || typeof value !== "object") return found; for (const [key, item] of Object.entries(value)) { if (["credential", "secret", "token", "transcript", "stdout", "stderr"].includes(key)) found.push(key); secretKeys(item, found); } return found; }
function initRepo(rootDir: string): void { git(rootDir, "init", "-q"); git(rootDir, "config", "user.name", "Runtime B Test"); git(rootDir, "config", "user.email", "runtime-b@example.invalid"); git(rootDir, "commit", "--allow-empty", "-qm", "base"); }
function git(rootDir: string, ...args: readonly string[]): string { return execFileSync("git", ["-C", rootDir, ...args], { encoding: "utf8" }).trim(); }
