// harness-test-tier: integration
import assert from "node:assert/strict";
import { execFileSync } from "node:child_process";
import { cpSync, existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import path from "node:path";
import test from "node:test";
import { makeTaskEventStore, makeTaskProjection, serializeCanonicalEvent } from "../../kernel/src/index.ts";
import { canonicalRoot, workspaceId } from "../src/protocol/daemon-protocol.contract.ts";
import { readDocReceipt } from "../src/doc-sync-actions.ts";
import { openRepoCell } from "../src/repo-cell.ts";

const actor = { principal: { personId: "person-owner" }, executor: { kind: "agent", id: "codex" } } as const;

test("status, dry-run, and submit share the repeatable-path scanner and automatic base", async () => {
  const rootDir = mkdtempSync(path.join(tmpdir(), "ha-doc-a-scanner-")); initRepo(rootDir); const cell = await openRepoCell({ repoId: workspaceId("scanner"), rootDir: canonicalRoot(rootDir), ownerId: "scanner-daemon" }), binding = { actor, source: "local" as const };
  try { write(rootDir, "context/a.md", "# A\n\nfirst\n"); write(rootDir, "context/b.md", "# B\n\nsecond\n"); write(rootDir, "tasks/task-one/progress.md", "# Progress\n"); write(rootDir, "context/ignored.json", "{}\n"); const before = git(rootDir, "rev-parse", "HEAD"), status = await cell.run({ kind: "doc-status", paths: [] }, binding), statusRows = rows(status.evidence);
    assert.deepEqual(statusRows.map((row) => [row.path, row.state]), [["context/a.md", "eligible"], ["context/b.md", "eligible"], ["tasks/task-one/progress.md", "blocked"]]); assert.equal(git(rootDir, "rev-parse", "HEAD"), before);
    const dry = await cell.run({ kind: "doc-dry-run", paths: ["context/a.md", "context/b.md"] }, binding); assert.deepEqual(rows(dry.evidence), statusRows.slice(0, 2)); assert.equal(git(rootDir, "rev-parse", "HEAD"), before);
    const submitted = await cell.run({ kind: "doc-submit", paths: ["context/a.md"] }, binding); assert.equal(submitted.outcome, "applied", JSON.stringify(submitted)); const event = makeTaskEventStore({ repoId: "scanner", rootDir }).readEvent(submitted.opId); assert.equal(event?.schema, "doc-event/v1"); if (event?.schema === "doc-event/v1") { assert.equal(event.payload.baseLedgerSha.sha, before); assert.equal(event.payload.executionId, null); assert.deepEqual(event.payload.changes.map((change) => change.path), ["context/a.md"]); }
    assert.deepEqual(git(rootDir, "status", "--porcelain", "-uall").split("\n").filter((line) => line.includes(" harness/")).sort(), ["?? harness/context/b.md", "?? harness/context/ignored.json", "?? harness/tasks/task-one/progress.md"]);
    write(rootDir, "context/a.md", "# Renamed\n\nfirst\n"); const acceptedCut = git(rootDir, "rev-parse", "HEAD"), blocked = await cell.run({ kind: "doc-dry-run", paths: ["context/a.md"] }, binding); assert.equal(rows(blocked.evidence)[0]?.state, "blocked"); const rejected = await cell.run({ kind: "doc-submit", paths: ["context/a.md"] }, binding); assert.equal(rejected.outcome, "rejected"); assert.equal(rejected.code, "preview_blocked"); assert.equal(git(rootDir, "rev-parse", "HEAD"), acceptedCut);
  } finally { await cell.close(); rmSync(rootDir, { recursive: true, force: true }); }
});

test("a committed DocEvent reports pending with its stable receipt id until L2 reaches the event cut", async () => {
  const rootDir = mkdtempSync(path.join(tmpdir(), "ha-doc-a-pending-")), repoId = workspaceId("doc-pending"), binding = { actor, source: "local" as const }; initRepo(rootDir); const cell = await openRepoCell({ repoId, rootDir: canonicalRoot(rootDir), ownerId: "doc-pending" });
  try { await cell.run({ kind: "task-create", taskId: "task-pending", title: "Pending" }, binding); write(rootDir, "context/pending.md", "# Pending\n"); const applied = await cell.run({ kind: "doc-submit", paths: ["context/pending.md"] }, binding); assert.equal(applied.outcome, "applied"); await cell.close(); const store = makeTaskEventStore({ repoId, rootDir }), event = store.readEvent(applied.opId); if (event?.schema !== "doc-event/v1") throw new Error("DocEvent missing"); const projection = makeTaskProjection({ rootDir, eventStore: store, projectionPath: path.join(rootDir, ".harness/pending.sqlite"), catchUpLimit: 1 }), pending = readDocReceipt({ binding, workspaceId: repoId, rootDir, store, projection, now: () => "2026-08-14T00:00:00.000Z" }, event); assert.equal(pending.outcome, "pending"); assert.equal(pending.opId, event.opId); assert.equal(pending.proof?.committedRevision, event.workspaceRevision); assert.equal(pending.proof?.canonicalVisible, false); assert.match(pending.nextAction ?? "", new RegExp(`receipt show ${event.opId}`, "u")); }
  finally { await cell.close(); rmSync(rootDir, { recursive: true, force: true }); }
});

test("materialize restores task-bootstrap and doc-event files and is idempotent", async () => {
  const rootDir = mkdtempSync(path.join(tmpdir(), "ha-doc-a-materialize-")); initRepo(rootDir); const cell = await openRepoCell({ repoId: workspaceId("materialize"), rootDir: canonicalRoot(rootDir), ownerId: "materialize-daemon" }), binding = { actor, source: "local" as const };
  try { assert.equal((await cell.run({ kind: "task-create", taskId: "task-materialize", title: "Materialize" }, binding)).outcome, "applied"); const packagePath = "tasks/task-materialize-materialize", taskRoot = path.join(rootDir, "harness", packagePath), prosePaths = [`${packagePath}/task_plan.md`, `${packagePath}/closeout.md`]; for (const logical of prosePaths) write(rootDir, logical, `${readFileSync(path.join(rootDir, "harness", logical), "utf8")}\n## Project Extension\n\nCanonical prose update.\n`); const prose = await cell.run({ kind: "doc-submit", paths: prosePaths }, binding); assert.equal(prose.outcome, "applied", JSON.stringify(prose)); const proseEvent = makeTaskEventStore({ repoId: "materialize", rootDir }).readEvent(prose.opId); assert.equal(proseEvent?.schema, "doc-event/v1"); if (proseEvent?.schema === "doc-event/v1") assert.deepEqual(proseEvent.payload.changes.map(({ path: target }) => target).sort(), [...prosePaths].sort()); write(rootDir, "context/notes.md", "# Notes\n\ncanonical\n"); assert.equal((await cell.run({ kind: "doc-submit", paths: ["context/notes.md"] }, binding)).outcome, "applied"); const cut = git(rootDir, "rev-parse", "HEAD"), count = git(rootDir, "rev-list", "--count", "HEAD"); rmSync(taskRoot, { recursive: true, force: true }); rmSync(path.join(rootDir, "harness/context/notes.md"));
    const first = await cell.run({ kind: "doc-materialize" }, binding), firstReport = materializeReport(first.evidence); assert.equal(first.outcome, "applied", JSON.stringify(first)); assert.equal(firstReport.changed.includes("context/notes.md"), true); assert.equal(firstReport.changed.some((value) => value.startsWith(`${packagePath}/`)), true); assert.equal(existsSync(taskRoot), true); for (const logical of prosePaths) assert.match(readFileSync(path.join(rootDir, "harness", logical), "utf8"), /Canonical prose update/u); assert.equal(git(rootDir, "diff", "--name-only"), "");
    const second = await cell.run({ kind: "doc-materialize" }, binding), secondReport = materializeReport(second.evidence); assert.deepEqual(secondReport.changed, []); assert.deepEqual(secondReport.conflicts, []); assert.equal(git(rootDir, "rev-parse", "HEAD"), cut); assert.equal(git(rootDir, "rev-list", "--count", "HEAD"), count); assert.equal(git(rootDir, "diff", "--name-only"), "");
  } finally { await cell.close(); rmSync(rootDir, { recursive: true, force: true }); }
});

test("materialize preserves a divergent local edit in one ignored deterministic conflict scratch", async () => {
  const rootDir = mkdtempSync(path.join(tmpdir(), "ha-doc-a-conflict-")); initRepo(rootDir); const cell = await openRepoCell({ repoId: workspaceId("conflict"), rootDir: canonicalRoot(rootDir), ownerId: "conflict-daemon" }), binding = { actor, source: "local" as const }, canonical = "# Notes\n\ncanonical\n", local = "# Notes\n\nlocal draft\n";
  try { write(rootDir, "context/notes.md", canonical); assert.equal((await cell.run({ kind: "doc-submit", paths: ["context/notes.md"] }, binding)).outcome, "applied"); write(rootDir, "context/notes.md", local); const first = materializeReport((await cell.run({ kind: "doc-materialize" }, binding)).evidence); assert.deepEqual(first.changed, ["context/notes.md"]); assert.equal(first.conflicts.length, 1); assert.equal(readFileSync(path.join(rootDir, first.conflicts[0]!), "utf8"), local); assert.equal(readFileSync(path.join(rootDir, "harness/context/notes.md"), "utf8"), canonical); assert.equal(git(rootDir, "status", "--porcelain", "-uall").includes("conflict-"), false); const second = materializeReport((await cell.run({ kind: "doc-materialize" }, binding)).evidence); assert.deepEqual(second, { changed: [], conflicts: [] });
  } finally { await cell.close(); rmSync(rootDir, { recursive: true, force: true }); }
});

test("an authored branch advanced outside the daemon returns indeterminate with reconcile guidance", async () => {
  const rootDir = mkdtempSync(path.join(tmpdir(), "ha-doc-a-diverged-")); initRepo(rootDir); const cell = await openRepoCell({ repoId: workspaceId("diverged"), rootDir: canonicalRoot(rootDir), ownerId: "diverged-daemon" }), binding = { actor, source: "local" as const };
  try { write(rootDir, "context/notes.md", "# Notes\n"); git(rootDir, "add", "harness/context/notes.md"); git(rootDir, "commit", "-qm", "external advance"); const result = await cell.run({ kind: "doc-submit", paths: ["context/notes.md"] }, binding); assert.equal(result.outcome, "indeterminate"); assert.equal(result.code, "publication_indeterminate"); assert.match(result.nextAction ?? "", /reconcile/iu); assert.equal(cell.status().state, "unavailable"); }
  finally { await cell.close(); rmSync(rootDir, { recursive: true, force: true }); }
});

test("artifact add is the untracked UTF-8 canonical subset of doc submit", async () => { const parent = mkdtempSync(path.join(tmpdir(), "ha-artifact-equivalence-")), left = path.join(parent, "left"), right = path.join(parent, "right"), now = () => "2026-08-14T00:00:00.000Z", binding = { actor, source: "local" as const }, repoId = workspaceId("artifact-equivalence"); mkdirSync(left); initRepo(left); const seed = await openRepoCell({ repoId, rootDir: canonicalRoot(left), ownerId: "artifact-seed", now });
  try { assert.equal((await seed.run({ kind: "task-create", taskId: "task-artifact", title: "Artifacts" }, binding)).outcome, "applied"); await seed.close(); cpSync(left, right, { recursive: true }); const artifactCell = await openRepoCell({ repoId, rootDir: canonicalRoot(left), ownerId: "artifact-route", now }), docCell = await openRepoCell({ repoId, rootDir: canonicalRoot(right), ownerId: "doc-route", now }), destination = "tasks/task-artifact-artifacts/artifacts/report.md", source = path.join(left, "incoming.md"), body = "# Report\n\nCanonical evidence.\n"; writeFileSync(source, body); write(right, destination, body);
    try { const artifact = await artifactCell.run({ kind: "task-artifact-add", taskId: "task-artifact", source: "incoming.md", destination: "report.md" }, binding) as Record<string, unknown>, doc = await docCell.run({ kind: "doc-submit", paths: [destination] }, binding) as Record<string, unknown>; assert.equal(artifact.outcome, "applied", JSON.stringify(artifact)); assert.equal(doc.outcome, "applied", JSON.stringify(doc)); assert.deepEqual({ opId: artifact.opId, revision: artifact.revision, commitSha: artifact.commitSha, settlement: artifact.settlement, receiptId: artifact.receiptId }, { opId: doc.opId, revision: doc.revision, commitSha: doc.commitSha, settlement: doc.settlement, receiptId: doc.receiptId }); const artifactStore = makeTaskEventStore({ repoId, rootDir: left }), docStore = makeTaskEventStore({ repoId, rootDir: right }), artifactEvent = artifactStore.readEvent(String(artifact.opId)), docEvent = docStore.readEvent(String(doc.opId)); assert.ok(artifactEvent && docEvent); assert.equal(serializeCanonicalEvent(artifactEvent), serializeCanonicalEvent(docEvent)); assert.equal(readFileSync(path.join(left, "harness/events/head.json"), "utf8"), readFileSync(path.join(right, "harness/events/head.json"), "utf8")); const shown = await artifactCell.run({ kind: "receipt-show", opId: String(artifact.receiptId) }, binding) as Record<string, unknown>; assert.equal(shown.receiptId, artifact.receiptId); assert.equal(shown.commitSha, artifact.commitSha);
      writeFileSync(source, "next\n"); const collision = await artifactCell.run({ kind: "task-artifact-add", taskId: "task-artifact", source: "incoming.md", destination: "report.md" }, binding); assert.equal(collision.code, "artifact_collision"); writeFileSync(path.join(left, "harness", destination), "edited\n"); const trackedEdit = await artifactCell.run({ kind: "task-artifact-add", taskId: "task-artifact", source: "incoming.md", destination: "report.md" }, binding); assert.equal(trackedEdit.code, "artifact_tracked_edit"); assert.match(trackedEdit.nextAction ?? "", /ha doc sync --submit --path/u); const trackedSource = await artifactCell.run({ kind: "task-artifact-add", taskId: "task-artifact", source: `harness/${destination}`, destination: "other.md" }, binding); assert.equal(trackedSource.code, "artifact_source_tracked"); writeFileSync(path.join(left, "bad.md"), Buffer.from([0xff])); assert.equal((await artifactCell.run({ kind: "task-artifact-add", taskId: "task-artifact", source: "bad.md", destination: "bad.md" }, binding)).code, "artifact_invalid_utf8"); writeFileSync(path.join(left, "crlf.md"), "bad\r\n"); assert.equal((await artifactCell.run({ kind: "task-artifact-add", taskId: "task-artifact", source: "crlf.md", destination: "crlf.md" }, binding)).code, "artifact_invalid_lf"); assert.equal((await artifactCell.run({ kind: "task-artifact-add", taskId: "task-artifact", source: "incoming.md", destination: "../escape.md" }, binding)).code, "invalid_artifact_path"); }
    finally { await artifactCell.close(); await docCell.close(); }
  } finally { await seed.close(); rmSync(parent, { recursive: true, force: true }); }
});

test("artifact unknown settlement returns the canonical DocEvent receipt id without retrying", async () => { const rootDir = mkdtempSync(path.join(tmpdir(), "ha-artifact-unknown-")); initRepo(rootDir); let armed = false, cell = await openRepoCell({ repoId: workspaceId("artifact-unknown"), rootDir: canonicalRoot(rootDir), ownerId: "artifact-unknown-one", now: () => "2026-08-14T00:00:00.000Z", killpoint: (point) => { if (armed && point === "before_response_write") throw new Error("response lost"); } }); const binding = { actor, source: "local" as const };
  try { assert.equal((await cell.run({ kind: "task-create", taskId: "task-unknown", title: "Unknown" }, binding)).outcome, "applied"); writeFileSync(path.join(rootDir, "unknown.md"), "# Unknown\n"); armed = true; const unknown = await cell.run({ kind: "task-artifact-add", taskId: "task-unknown", source: "unknown.md", destination: "unknown.md" }, binding); assert.equal(unknown.outcome, "indeterminate"); assert.equal(unknown.code, "publication_indeterminate"); assert.match(unknown.opId, /^op_/u); assert.match(unknown.nextAction ?? "", new RegExp(`receipt show ${unknown.opId}`, "u")); assert.equal(makeTaskEventStore({ repoId: "artifact-unknown", rootDir }).read().revision, 2); await cell.close(); cell = await openRepoCell({ repoId: workspaceId("artifact-unknown"), rootDir: canonicalRoot(rootDir), ownerId: "artifact-unknown-two", now: () => "2026-08-14T00:00:00.000Z" }); const settled = await cell.run({ kind: "receipt-show", opId: unknown.opId }, binding) as Record<string, unknown>; assert.equal(settled.outcome, "applied"); assert.equal(settled.receiptId, unknown.opId); }
  finally { await cell.close(); rmSync(rootDir, { recursive: true, force: true }); }
});

function rows(evidence: string | undefined): readonly { readonly path: string; readonly state: string }[] { assert.match(evidence ?? "", /^doc-scan:/u); return (JSON.parse((evidence ?? "").slice("doc-scan:".length)) as { rows: readonly { path: string; state: string }[] }).rows; }
function materializeReport(evidence: string | undefined): { readonly changed: readonly string[]; readonly conflicts: readonly string[] } { assert.match(evidence ?? "", /^doc-materialize:/u); return JSON.parse((evidence ?? "").slice("doc-materialize:".length)) as { changed: readonly string[]; conflicts: readonly string[] }; }
function write(rootDir: string, target: string, body: string): void { const file = path.join(rootDir, "harness", target); mkdirSync(path.dirname(file), { recursive: true }); writeFileSync(file, body); }
function initRepo(rootDir: string): void { git(rootDir, "init", "-q"); git(rootDir, "config", "user.name", "Doc A Test"); git(rootDir, "config", "user.email", "doc-a@example.invalid"); git(rootDir, "commit", "--allow-empty", "-qm", "base"); }
function git(rootDir: string, ...args: readonly string[]): string { return execFileSync("git", ["-C", rootDir, ...args], { encoding: "utf8" }).trim(); }
