// harness-test-tier: integration
import assert from "node:assert/strict";
import { execFileSync } from "node:child_process";
import { mkdirSync, mkdtempSync, readFileSync, readdirSync, rmSync, statSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import path from "node:path";
import test from "node:test";
import { deriveRelationId, makeTaskEventStore } from "../../kernel/src/index.ts";
import { canonicalRoot, workspaceId } from "../src/protocol/daemon-protocol.contract.ts";
import { openRepoCell } from "../src/repo-cell.ts";

const actor = { principal: { personId: "migration-owner" }, executor: { kind: "agent", id: "codex" } } as const;

test("legacy copy -> initialized repository -> migration import -> reconciliation", async () => {
  const scratch = mkdtempSync(path.join(tmpdir(), "ha-migrate-import-")), source = path.join(scratch, "legacy"), destination = path.join(scratch, "new"); let cell: Awaited<ReturnType<typeof openRepoCell>> | undefined;
  try {
    legacyFixture(source); initRepo(destination); const sourceBefore = snapshot(source);
    cell = await openRepoCell({ repoId: workspaceId("migration-target"), rootDir: canonicalRoot(destination), ownerId: "migration-daemon", now: () => "2026-06-01T00:00:00.000Z" });
    const before = makeTaskEventStore({ repoId: "migration-target", rootDir: destination }).readHead()?.revision ?? 0, dryRun = await cell.run({ kind: "migrate-import", sourceRoot: source, dryRun: true }, { actor, source: "local" }) as Record<string, unknown>;
    assert.equal(dryRun.exitCode, 3, JSON.stringify(dryRun)); assert.equal(makeTaskEventStore({ repoId: "migration-target", rootDir: destination }).readHead()?.revision ?? 0, before); assert.deepEqual(snapshot(source), sourceBefore); assert.match(String(dryRun.summary), /\| task \| 2 \| 1 \| 1 \| 1 \| PASS \|/u); assert.match(String(dryRun.summary), /\| relation \| 2 \| 0 \| 2 \| 2 \| PASS \|/u); assert.match(String(dryRun.summary), /Format validation: 1 skipped/u);
    const applied = await cell.run({ kind: "migrate-import", sourceRoot: source }, { actor, source: "local" }) as Record<string, unknown>; assert.equal(applied.exitCode, 3, JSON.stringify(applied)); assert.match(String(applied.summary), /Reconciliation: PASS/u); assert.deepEqual(snapshot(source), sourceBefore);
    const store = makeTaskEventStore({ repoId: "migration-target", rootDir: destination }), events = store.read().events.filter((event) => event.schema === "migration-import-event/v1"); assert.equal(events.length, 6); assert.equal(events.every((event) => event.source === "migration-import/v1" && event.payload.generation === "v0" && typeof event.payload.migratedFrom === "string"), true); assert.deepEqual(events.slice(0, 3).map(({ occurredAt }) => occurredAt), ["2026-01-01T00:00:00.000Z", "2026-01-02T00:00:00.000Z", "2026-01-03T00:00:00.000Z"]);
    const tasks = await cell.read("repo.tasks.list"), task = tasks.rows.find(({ taskId }) => taskId === "task_legacy"); assert.equal(task?.generation, "v0"); assert.equal(task?.snapshot.task?.status, "done");
    const graph = await cell.read("repo.triadic.relationGraph"), migratedFactEdge = graph.edges.find(({ targetRef }) => targetRef === "fact/task_legacy/F-MGRATEDX"); assert.equal(graph.edges.length, 2); assert.equal(migratedFactEdge?.sourceRef, "decision/dec_LEGACY/C1"); assert.equal(migratedFactEdge?.targetRef, "fact/task_legacy/F-MGRATEDX"); assert.equal(graph.coverageRows.length, 1); assert.equal(graph.coverageRows[0]?.status, "covered");
    const mapPath = path.join(destination, "harness", String(applied.idMapPath)); const idMap = JSON.parse(readFileSync(mapPath, "utf8")) as { maps: { task: Record<string, string>; relation: Record<string, string> }; skipped: unknown[] }; assert.equal(idMap.maps.task.task_legacy, "task_legacy"); assert.equal(Object.keys(idMap.maps.relation).length, 2); assert.equal(idMap.skipped.length, 1);
  } finally { await cell?.close(); rmSync(scratch, { recursive: true, force: true }); }
});

function legacyFixture(root: string): void { const taskRoot = path.join(root, "harness/tasks/task_legacy-old"), badRoot = path.join(root, "harness/tasks/task_bad"), decisionRoot = path.join(root, "harness/decisions/decision-dec_LEGACY"); mkdirSync(taskRoot, { recursive: true }); mkdirSync(badRoot, { recursive: true }); mkdirSync(decisionRoot, { recursive: true }); writeFileSync(path.join(root, "harness/harness.yaml"), "schema: harness-anything/v1\nlayout:\n  authoredRoot: harness\n  localRoot: .harness\n");
  writeFileSync(path.join(taskRoot, "INDEX.md"), "---\nschema: task-package/v2\ntask_id: task_legacy\ntitle: Legacy done task\nlifecycle:\n  status: done\n  engine: local\n  bindingCreatedAt: 2026-01-01T00:00:00.000Z\n---\n\n# Legacy done task\n"); writeFileSync(path.join(badRoot, "INDEX.md"), "# missing frontmatter\n");
  writeFileSync(path.join(taskRoot, "facts.md"), "# Facts\n\n- {fact_id: F-ABCDEFGH, statement: Observed migration, source: legacy-test, observedAt: 2026-01-02T00:00:00.000Z, confidence: high, memoryClass: semantic, memoryTags: [pattern], provenance: [{runtime: codex, sessionId: legacy-session, boundAt: 2026-01-02T00:00:00.000Z}]}\n- {fact_id: F-MGRATEDX, statement: Archived execution evidence, source: legacy-test, observedAt: 2026-01-02T12:00:00.000Z, confidence: high, memoryClass: episodic, memoryTags: [], provenance: [{runtime: codex, sessionId: legacy-session, boundAt: 2026-01-02T12:00:00.000Z}], migration: {schema: fact-migration/v1, state: migrated, plan_id: fxm_test, execution_ref: execution/task_legacy/exe_test, evidence_id: fact-migration:fxm_test:F-MGRATEDX, migrated_at: 2026-01-04T00:00:00.000Z}}\n");
  const relation = { relation_id: deriveRelationId({ source: "decision/dec_LEGACY/C1", target: "fact/task_legacy/F-ABCDEFGH", type: "evidenced-by", direction: "directed" }), source: "decision/dec_LEGACY/C1", target: "fact/task_legacy/F-ABCDEFGH", type: "evidenced-by", strength: "strong", direction: "directed", origin: "declared", rationale: "Legacy observation supports the claim.", state: "active" };
  const migratedFactRelation = { relation_id: deriveRelationId({ source: "decision/dec_LEGACY/C1", target: "fact/task_legacy/F-MGRATEDX", type: "evidenced-by", direction: "directed" }), source: "decision/dec_LEGACY/C1", target: "fact/task_legacy/F-MGRATEDX", type: "evidenced-by", strength: "strong", direction: "directed", origin: "declared", rationale: "The historical relation keeps its migrated fact endpoint resolvable.", state: "retired" };
  writeFileSync(path.join(decisionRoot, "decision.md"), `---\nschema: decision-package/v1\ndecision_id: dec_LEGACY\nworkspaceRevision: 7\ntitle: "Legacy decision"\nstate: active\nriskTier: medium\nurgency: medium\nvertical: "software/coding"\npreset: "standard-task"\ndecisionClass: ordinary\napplies_to: {"modules":["kernel"],"productLines":["harness"]}\nproposedAt: "2026-01-01T12:00:00.000Z"\ndecidedAt: "2026-01-03T00:00:00.000Z"\nquestion: "Should the history migrate?"\nchosen: [{"id":"CH1","text":"Migrate it"}]\nrejected: [{"id":"RJ1","text":"Drop it","whyNot":"History is required"}]\nclaims: [{"id":"C1","text":"History remains auditable","loadBearing":true,"fulfillment":"evidenced"}]\nrelations: ${JSON.stringify([relation, migratedFactRelation])}\n---\n\n# Legacy decision\n\nPreserved prose.\n`); }
function initRepo(root: string): void { mkdirSync(root, { recursive: true }); git(root, "init", "-q"); git(root, "config", "user.name", "Migration Test"); git(root, "config", "user.email", "migration@example.invalid"); mkdirSync(path.join(root, "harness"), { recursive: true }); writeFileSync(path.join(root, "harness/harness.yaml"), "schema: harness-anything/v1\nlayout:\n  authoredRoot: harness\n  localRoot: .harness\n"); git(root, "add", "."); git(root, "commit", "-qm", "initialized"); }
function snapshot(root: string): readonly string[] { const walk = (dir: string): string[] => readdirSync(dir, { withFileTypes: true }).flatMap((entry) => { const target = path.join(dir, entry.name); return entry.isDirectory() ? walk(target) : [`${path.relative(root, target)}:${statSync(target).size}:${readFileSync(target, "utf8")}`]; }); return walk(root).sort(); }
function git(root: string, ...args: string[]): string { return execFileSync("git", args, { cwd: root, encoding: "utf8" }).trim(); }
