// harness-test-tier: integration
import assert from "node:assert/strict";
import { execFileSync } from "node:child_process";
import { mkdirSync, mkdtempSync, readFileSync, readdirSync, rmSync, statSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import path from "node:path";
import test from "node:test";
import { deriveRelationId, makeTaskEventStore } from "../../kernel/src/index.ts";
import { canonicalRoot, workspaceId } from "../src/protocol/daemon-protocol.contract.ts";
import { openRepoCell } from "../src/repo-cell.ts";

const actor = { principal: { personId: "migration-owner" }, executor: { kind: "agent", id: "codex" } } as const;

test("legacy copy -> initialized repository -> migration import -> reconciliation", async () => {
  const scratch = mkdtempSync(path.join(tmpdir(), "ha-migrate-import-")), source = path.join(scratch, "legacy"), destination = path.join(scratch, "new"); let cell: Awaited<ReturnType<typeof openRepoCell>> | undefined;
  try {
    legacyFixture(source); initRepo(destination); const sourceBefore = snapshot(source);
    cell = await openRepoCell({ repoId: workspaceId("migration-target"), rootDir: canonicalRoot(destination), ownerId: "migration-daemon", now: () => "2026-06-01T00:00:00.000Z" });
    const before = makeTaskEventStore({ repoId: "migration-target", rootDir: destination }).readHead()?.revision ?? 0, dryRun = await cell.run({ kind: "migrate-import", sourceRoot: source, dryRun: true }, { actor, source: "local" }) as Record<string, unknown>;
    assert.equal(dryRun.exitCode, 1, JSON.stringify(dryRun)); assert.equal(makeTaskEventStore({ repoId: "migration-target", rootDir: destination }).readHead()?.revision ?? 0, before); assert.deepEqual(snapshot(source), sourceBefore); assert.match(String(dryRun.summary), /\| task \| 2 \| 1 \| 1 \| 1 \| PASS \|/u); assert.match(String(dryRun.summary), /\| relation \| 2 \| 0 \| 2 \| 2 \| PASS \|/u); assert.match(String(dryRun.summary), /Format validation: 1 skipped/u); assert.match(String(dryRun.summary), /\| task:facts\.md \| required \| 1 \| FAIL \|/u);
    const applied = await cell.run({ kind: "migrate-import", sourceRoot: source }, { actor, source: "local" }) as Record<string, unknown>; assert.equal(applied.exitCode, 1, JSON.stringify(applied)); assert.equal(applied.idMapPath, null); assert.match(String(applied.summary), /Authored reconciliation: FAIL/u); assert.deepEqual(snapshot(source), sourceBefore); assert.equal(makeTaskEventStore({ repoId: "migration-target", rootDir: destination }).readHead()?.revision ?? 0, before);
  } finally { await cell?.close(); rmSync(scratch, { recursive: true, force: true }); }
});

test("authored coverage rejects an unclassified source path before any migration write", async () => {
  const scratch = mkdtempSync(path.join(tmpdir(), "ha-migrate-coverage-")), source = path.join(scratch, "legacy"), destination = path.join(scratch, "new"); let cell: Awaited<ReturnType<typeof openRepoCell>> | undefined;
  try {
    coverageGapFixture(source); initRepo(destination); const sourceBefore = snapshot(source);
    cell = await openRepoCell({ repoId: workspaceId("migration-coverage-target"), rootDir: canonicalRoot(destination), ownerId: "migration-daemon", now: () => "2026-06-01T00:00:00.000Z" });
    const before = makeTaskEventStore({ repoId: "migration-coverage-target", rootDir: destination }).readHead()?.revision ?? 0, result = await cell.run({ kind: "migrate-import", sourceRoot: source }, { actor, source: "local" }) as Record<string, unknown>;
    assert.equal(result.exitCode, 1, JSON.stringify(result)); assert.equal(result.outcome, "rejected"); assert.equal(makeTaskEventStore({ repoId: "migration-coverage-target", rootDir: destination }).readHead()?.revision ?? 0, before); assert.deepEqual(snapshot(source), sourceBefore);
    assert.match(String(result.summary), /Authored reconciliation: FAIL/u); assert.match(String(result.summary), /\| task:task_plan\.md \| required \| 1 \| FAIL \|/u); assert.match(String(result.summary), /\| objects\/\*\* \| excluded \| 1 \| PASS \|/u); assert.match(String(result.summary), /DECISION_REQUIRED people\.yaml/u); assert.match(String(result.summary), /UNCOVERED mystery\/orphan\.md/u);
  } finally { await cell?.close(); rmSync(scratch, { recursive: true, force: true }); }
});

test("authored coverage permits a source whose every file is migrated or explicitly excluded", async () => {
  const scratch = mkdtempSync(path.join(tmpdir(), "ha-migrate-covered-")), source = path.join(scratch, "legacy"), destination = path.join(scratch, "new"); let cell: Awaited<ReturnType<typeof openRepoCell>> | undefined;
  try {
    coverageCompleteFixture(source); initRepo(destination); cell = await openRepoCell({ repoId: workspaceId("migration-covered-target"), rootDir: canonicalRoot(destination), ownerId: "migration-daemon", now: () => "2026-06-01T00:00:00.000Z" });
    const result = await cell.run({ kind: "migrate-import", sourceRoot: source }, { actor, source: "local" }) as Record<string, unknown>; assert.equal(result.exitCode, 0, JSON.stringify(result)); assert.equal(result.outcome, "applied"); assert.match(String(result.summary), /Authored reconciliation: PASS/u); assert.match(String(result.idMapPath), /^migrations\/import_[0-9a-f]+\/id-map\.json$/u);
    const tasks = await cell.read("repo.tasks.list"); assert.equal(tasks.rows.find(({ taskId }) => taskId === "task_coverage")?.generation, "v0");
  } finally { await cell?.close(); rmSync(scratch, { recursive: true, force: true }); }
});

function legacyFixture(root: string): void { const taskRoot = path.join(root, "harness/tasks/task_legacy-old"), badRoot = path.join(root, "harness/tasks/task_bad"), decisionRoot = path.join(root, "harness/decisions/decision-dec_LEGACY"); mkdirSync(taskRoot, { recursive: true }); mkdirSync(badRoot, { recursive: true }); mkdirSync(decisionRoot, { recursive: true }); writeFileSync(path.join(root, "harness/harness.yaml"), "schema: harness-anything/v1\nlayout:\n  authoredRoot: harness\n  localRoot: .harness\n");
  writeFileSync(path.join(taskRoot, "INDEX.md"), "---\nschema: task-package/v2\ntask_id: task_legacy\ntitle: Legacy done task\nlifecycle:\n  status: done\n  engine: local\n  bindingCreatedAt: 2026-01-01T00:00:00.000Z\n---\n\n# Legacy done task\n"); writeFileSync(path.join(badRoot, "INDEX.md"), "# missing frontmatter\n");
  writeFileSync(path.join(taskRoot, "facts.md"), "# Facts\n\n- {fact_id: F-ABCDEFGH, statement: Observed migration, source: legacy-test, observedAt: 2026-01-02T00:00:00.000Z, confidence: high, memoryClass: semantic, memoryTags: [pattern], provenance: [{runtime: codex, sessionId: legacy-session, boundAt: 2026-01-02T00:00:00.000Z}]}\n- {fact_id: F-MGRATEDX, statement: Archived execution evidence, source: legacy-test, observedAt: 2026-01-02T12:00:00.000Z, confidence: high, memoryClass: episodic, memoryTags: [], provenance: [{runtime: codex, sessionId: legacy-session, boundAt: 2026-01-02T12:00:00.000Z}], migration: {schema: fact-migration/v1, state: migrated, plan_id: fxm_test, execution_ref: execution/task_legacy/exe_test, evidence_id: fact-migration:fxm_test:F-MGRATEDX, migrated_at: 2026-01-04T00:00:00.000Z}}\n");
  const relation = { relation_id: deriveRelationId({ source: "decision/dec_LEGACY/C1", target: "fact/task_legacy/F-ABCDEFGH", type: "evidenced-by", direction: "directed" }), source: "decision/dec_LEGACY/C1", target: "fact/task_legacy/F-ABCDEFGH", type: "evidenced-by", strength: "strong", direction: "directed", origin: "declared", rationale: "Legacy observation supports the claim.", state: "active" };
  const migratedFactRelation = { relation_id: deriveRelationId({ source: "decision/dec_LEGACY/C1", target: "fact/task_legacy/F-MGRATEDX", type: "evidenced-by", direction: "directed" }), source: "decision/dec_LEGACY/C1", target: "fact/task_legacy/F-MGRATEDX", type: "evidenced-by", strength: "strong", direction: "directed", origin: "declared", rationale: "The historical relation keeps its migrated fact endpoint resolvable.", state: "retired" };
  writeFileSync(path.join(decisionRoot, "decision.md"), `---\nschema: decision-package/v1\ndecision_id: dec_LEGACY\nworkspaceRevision: 7\ntitle: "Legacy decision"\nstate: active\nriskTier: medium\nurgency: medium\nvertical: "software/coding"\npreset: "standard-task"\ndecisionClass: ordinary\napplies_to: {"modules":["kernel"],"productLines":["harness"]}\nproposedAt: "2026-01-01T12:00:00.000Z"\ndecidedAt: "2026-01-03T00:00:00.000Z"\nquestion: "Should the history migrate?"\nchosen: [{"id":"CH1","text":"Migrate it"}]\nrejected: [{"id":"RJ1","text":"Drop it","whyNot":"History is required"}]\nclaims: [{"id":"C1","text":"History remains auditable","loadBearing":true,"fulfillment":"evidenced"}]\nrelations: ${JSON.stringify([relation, migratedFactRelation])}\n---\n\n# Legacy decision\n\nPreserved prose.\n`); }
function coverageGapFixture(root: string): void { coverageCompleteFixture(root); const taskRoot = path.join(root, "harness/tasks/task_coverage-old"), mysteryRoot = path.join(root, "harness/mystery"), objectsRoot = path.join(root, "harness/objects/sha256/aa"); mkdirSync(mysteryRoot, { recursive: true }); mkdirSync(objectsRoot, { recursive: true }); writeFileSync(path.join(taskRoot, "task_plan.md"), "# Authored plan\n"); writeFileSync(path.join(mysteryRoot, "orphan.md"), "# This path has no migration rule\n"); writeFileSync(path.join(objectsRoot, "blob"), "rebuildable CAS\n"); writeFileSync(path.join(root, "harness/people.yaml"), '{"schema":"harness-people/v1","people":[],"roles":[]}\n'); }
function coverageCompleteFixture(root: string): void { const taskRoot = path.join(root, "harness/tasks/task_coverage-old"); mkdirSync(taskRoot, { recursive: true }); writeFileSync(path.join(root, "harness/harness.yaml"), "schema: harness-anything/v1\nlayout:\n  authoredRoot: harness\n  localRoot: .harness\n"); writeFileSync(path.join(taskRoot, "INDEX.md"), "---\nschema: task-package/v2\ntask_id: task_coverage\ntitle: Coverage fixture\nlifecycle:\n  status: done\n  engine: local\n  bindingCreatedAt: 2026-01-01T00:00:00.000Z\n---\n\n# Coverage fixture\n"); }
function initRepo(root: string): void { mkdirSync(root, { recursive: true }); git(root, "init", "-q"); git(root, "config", "user.name", "Migration Test"); git(root, "config", "user.email", "migration@example.invalid"); mkdirSync(path.join(root, "harness"), { recursive: true }); writeFileSync(path.join(root, "harness/harness.yaml"), "schema: harness-anything/v1\nlayout:\n  authoredRoot: harness\n  localRoot: .harness\n"); git(root, "add", "."); git(root, "commit", "-qm", "initialized"); }
function snapshot(root: string): readonly string[] { const walk = (dir: string): string[] => readdirSync(dir, { withFileTypes: true }).flatMap((entry) => { const target = path.join(dir, entry.name); return entry.isDirectory() ? walk(target) : [`${path.relative(root, target)}:${statSync(target).size}:${readFileSync(target, "utf8")}`]; }); return walk(root).sort(); }
function git(root: string, ...args: string[]): string { return execFileSync("git", args, { cwd: root, encoding: "utf8" }).trim(); }
