import type { PolicyActionRule, PolicyDeclarationV1 } from "./policy.ts";

const repositoryWriteActions = Object.freeze([
  "agent-create",
  "agent-install",
  "ci-observe-pull",
  "decision-amend",
  "decision-claim-add",
  "decision-claim-fulfill",
  "decision-propose",
  "decision-reckon",
  "relation-reconfirm",
  "relation-relate",
  "relation-unrelate",
  "decision-repin",
  "decision-retire",
  "decision-supersede",
  "decision-transition",
  "distill-candidate",
  "distill-promote",
  "dispatch-records-migrate",
  "doc-conflict-discard-local",
  "decision-digests-migrate",
  "doc-conflict-overwrite-center",
  "doc-conflict-resolve",
  "doc-materialize",
  "doc-retire",
  "doc-submit",
  "entity-import",
  "entity-update",
  "entity-archive",
  "entity-migrate-squads",
  "fact-reclassify",
  "fact-record",
  "fact-rekey",
  "fact-type-register",
  "ledger-migrate",
  "migrate-import",
  "preset-install",
  "preset-run-start",
  "preset-seed",
  "preset-uninstall",
  "preset-upgrade",
  "projection-rebuild",
  "relation-events-migrate",
  "runtime-batch",
  "runtime-cancel",
  "runtime-instance-login",
  "runtime-instance-logout",
  "runtime-run",
  "runtime-spawn",
  "schedule-claim",
  "schedule-create",
  "schedule-delete",
  "schedule-disable",
  "schedule-dispatch-link",
  "schedule-enable",
  "schedule-missed",
  "schedule-run-now",
  "schedule-settle",
  "schedule-update",
  "script-run",
  "settings-update",
  "squad-cancel",
  "squad-install",
  "squad-run",
  "task-amend",
  "task-archive",
  "task-artifact-add",
  "task-closeout",
  "task-code-doc-reconcile",
  "task-code-doc-repoint",
  "task-complete",
  "task-contract-migrate",
  "task-create",
  "task-declare-executor",
  "task-delete",
  "task-pin",
  "task-progress-append",
  "task-release",
  "task-reopen",
  "task-review-consent",
  "task-start",
  "task-submit",
  "task-supersede",
  "task-transition",
  "task-unpin",
  "terminal-input",
  "terminal-resize",
  "terminal-spawn",
  "terminal-terminate",
] as const);

const arbiterActions = Object.freeze([
  "decision-accept",
  "decision-defer",
  "decision-reject",
  "task-review-execution",
] as const);

const administrationActions = Object.freeze([
  "daemon-control-request",
  "daemon-fleet-center-start",
  "daemon-fleet-edge-sync",
  "daemon-repo-register",
  "daemon-repo-unregister",
  "daemon-start",
  "daemon-stop",
  "people-add",
  "people-bind",
  "people-delegate",
  "people-remove",
  "people-revoke-delegation",
  "people-set-role",
  "repo-bootstrap",
  "runtime-instance-create",
  "runtime-instance-delete",
  "runtime-instance-github-credential-set",
  "runtime-instance-github-credential-unset",
  "runtime-instance-list",
  "runtime-instance-show",
  "runtime-instance-update",
] as const);

export const durablePolicyActions = Object.freeze([
  ...repositoryWriteActions,
  ...arbiterActions,
  ...administrationActions,
] as const);

const roleRule = (
  action: string,
  role: string,
  defaultBindingAllowed: boolean,
  assignmentAllowed: boolean,
): PolicyActionRule => ({
  action,
  anyOf: [
    { allOf: [{ predicate: "hasRoleBinding", role }] },
    { allOf: [{ predicate: "hasRoleBinding", role: "owner" }] },
    ...(defaultBindingAllowed ? [{ allOf: [{ predicate: "hasDefaultBinding" as const }] }] : []),
    ...(assignmentAllowed ? [{ allOf: [{ predicate: "hasAssignmentBinding" as const }] }] : []),
  ],
});

/** The single built-in policy package consumed by the kernel AuthorizationPort. */
const defaultPolicyDeclaration = {
  schema: "policy/v1",
  id: "default",
  version: 5,
  predicates: Object.freeze([
    { predicate: "hasRoleBinding", role: "repo-write" },
    { predicate: "hasRoleBinding", role: "arbiter" },
    { predicate: "hasRoleBinding", role: "admin" },
    { predicate: "hasRoleBinding", role: "owner" },
    { predicate: "hasDefaultBinding" },
    { predicate: "hasAssignmentBinding" },
  ]),
  actions: durablePolicyActions,
  rules: Object.freeze([
    ...repositoryWriteActions.map((action) => roleRule(action, "repo-write", true, true)),
    ...arbiterActions.map((action) => roleRule(action, "arbiter", true, false)),
    ...administrationActions.map((action) => roleRule(action, "admin", true, false)),
  ]),
} satisfies PolicyDeclarationV1;

export const DEFAULT_POLICY: PolicyDeclarationV1 = Object.freeze(defaultPolicyDeclaration);

export const defaultPolicy = DEFAULT_POLICY;
