import { deriveRelationId, relationDirections, relationOrigins, relationStates, relationStrengths, relationTypes, type EntityRelationRecord } from "./entity-relation.ts";
import { decisionStates, factConfidenceLevels, factMemoryClasses, factMemoryTags, factProvenanceRuntimes, type DecisionDocumentState, type FactConfidence, type FactMemoryClass, type FactMemoryTag, type FactProvenanceRuntime } from "./fact-event.ts";
import { validateTaskV1, type TaskV1 } from "./task.ts";
import { freezeDeclaredWritePlan, hasOnlyFields, isFrozenWritePlan, isNonEmptyString, isRecord, serializeEventEnvelope, type ActorIdentity, type EventEnvelope, type FrozenWritePlan, type WriteTarget } from "./write-chain.contract.ts";
import { normalizeRelativeDocumentPath } from "../layout/portable-path.ts";
import { stableStringify } from "../integrity/stable-hash.ts";
import { validateArchivedExecutionV0, type ArchivedExecutionV0 } from "./execution.ts";

export const MIGRATION_IMPORT_SOURCE = "migration-import/v1" as const;
export const MIGRATION_DOCUMENT_POLICY_ID = "typed-migration-import/v1" as const;
export interface MigrationDocumentClaim { readonly path: string; readonly sha256: string; readonly size: number; readonly mediaType: string; readonly policyId: typeof MIGRATION_DOCUMENT_POLICY_ID } export interface MigrationReferencedContentClaim { readonly sha256: string; readonly size: number; readonly mediaType: string }
export interface MigrationFact { readonly taskId: string; readonly factId: string; readonly statement: string; readonly evidenceSource: string; readonly observedAt: string; readonly confidence: FactConfidence; readonly memoryClass: FactMemoryClass; readonly memoryTags: readonly FactMemoryTag[]; readonly provenance: readonly { readonly runtime: FactProvenanceRuntime; readonly sessionId: string; readonly boundAt: string }[] }
export type MigrationEntity =
  | { readonly kind: "task"; readonly task: TaskV1; readonly originalStatus: string; readonly packagePath: string; readonly documentClaim: MigrationDocumentClaim }
  | { readonly kind: "decision"; readonly decision: DecisionDocumentState; readonly documentClaim: MigrationDocumentClaim }
  | { readonly kind: "fact"; readonly fact: MigrationFact; readonly documentClaim: MigrationDocumentClaim }
  | { readonly kind: "execution"; readonly execution: ArchivedExecutionV0; readonly documentClaim: MigrationDocumentClaim }
  | { readonly kind: "task-document"; readonly taskId: string; readonly documentClaim: MigrationDocumentClaim } | { readonly kind: "repo-document"; readonly documentClaim: MigrationDocumentClaim; readonly referencedContentClaims: readonly MigrationReferencedContentClaim[] }
  | { readonly kind: "relation"; readonly relation: EntityRelationRecord; readonly ownerRef: string }
  | { readonly kind: "id-map"; readonly importId: string; readonly documentClaim: MigrationDocumentClaim };
export type MigrationImportEventV1 = EventEnvelope<"migration-import-event/v1", "entity_migrated", ActorIdentity, { readonly migratedFrom: string; readonly generation: "v0"; readonly entity: MigrationEntity }> & { readonly source: typeof MIGRATION_IMPORT_SOURCE };

export function isMigrationImportEvent(event: { readonly schema: string }): event is MigrationImportEventV1 { return event.schema === "migration-import-event/v1"; }
export function migrationImportClaims(event: MigrationImportEventV1): readonly MigrationDocumentClaim[] { return "documentClaim" in event.payload.entity ? [event.payload.entity.documentClaim] : []; } export function migrationImportContentClaims(event: MigrationImportEventV1): readonly (MigrationDocumentClaim | MigrationReferencedContentClaim)[] { const entity = event.payload.entity; return [...migrationImportClaims(event), ...(entity.kind === "repo-document" ? entity.referencedContentClaims : [])]; }
export function validateMigrationImportEvent(value: unknown): readonly string[] {
  if (!isRecord(value) || !hasOnlyFields(value, ["schema", "eventId", "workspaceRevision", "opId", "type", "actor", "source", "occurredAt", "payload"]) || value.schema !== "migration-import-event/v1" || value.type !== "entity_migrated" || value.source !== MIGRATION_IMPORT_SOURCE || !isRecord(value.payload) || !hasOnlyFields(value.payload, ["migratedFrom", "generation", "entity"]) || !isNonEmptyString(value.payload.migratedFrom) || value.payload.generation !== "v0" || !isRecord(value.payload.entity)) return ["migration import event envelope or provenance is invalid"];
  try { serializeEventEnvelope(value as unknown as MigrationImportEventV1); } catch { return ["migration import event identity is invalid"]; }
  const entity = value.payload.entity;
  if (entity.kind === "task") return validTaskEntity(entity) ? [] : ["migration task entity is invalid"];
  if (entity.kind === "decision") return validDecisionEntity(entity) ? [] : ["migration decision entity is invalid"];
  if (entity.kind === "fact") return validFactEntity(entity) ? [] : ["migration fact entity is invalid"];
  if (entity.kind === "execution") return validExecutionEntity(entity) ? [] : ["migration execution entity is invalid"];
  if (entity.kind === "task-document") return validTaskDocumentEntity(entity) ? [] : ["migration task document entity is invalid"]; if (entity.kind === "repo-document") return validRepoDocumentEntity(entity) ? [] : ["migration repo document entity is invalid"];
  if (entity.kind === "relation") return validRelationEntity(entity) ? [] : ["migration relation entity is invalid"];
  return entity.kind === "id-map" && hasOnlyFields(entity, ["kind", "importId", "documentClaim"]) && isNonEmptyString(entity.importId) && validClaim(entity.documentClaim, "application/json") ? [] : ["migration id-map entity is invalid"];
}
export function migrationImportWritePlan(event: MigrationImportEventV1): FrozenWritePlan<"MigrationImport"> { const entity = event.payload.entity, key = event.payload.migratedFrom, targets: WriteTarget[] = [{ kind: "event_file", path: `harness/events/${event.opId}.json`, operation: "create" }, { kind: "event_head", path: "harness/events/head.json", operation: "replace" }, { kind: "projection_invalidation", projection: `migration-${entity.kind}/v1`, key }]; for (const claim of migrationImportClaims(event)) targets.push({ kind: "authored_file", path: claim.path, operation: "replace", sha256: claim.sha256, size: claim.size, mediaType: claim.mediaType }, { kind: "content_blob", sha256: claim.sha256, size: claim.size, mediaType: claim.mediaType }, { kind: "projection_invalidation", projection: "document/v1", key: claim.path }); if (entity.kind === "repo-document") for (const claim of entity.referencedContentClaims) targets.push({ kind: "content_blob", sha256: claim.sha256, size: claim.size, mediaType: claim.mediaType }); return freezeDeclaredWritePlan({ commandType: "MigrationImport", targets }, ["MigrationImport"]); }
export function assertMigrationImportWritePlan(event: MigrationImportEventV1, plan: FrozenWritePlan | undefined): void { const shape = (value: FrozenWritePlan) => stableStringify({ commandType: value.commandType, targets: value.targets.map(stableStringify).sort() }); if (!plan || !isFrozenWritePlan(plan) || shape(plan) !== shape(migrationImportWritePlan(event))) throw new Error("migration import plan must exactly declare event, entity, document, and blob targets"); }

function validTaskEntity(value: Readonly<Record<string, unknown>>): boolean { return hasOnlyFields(value, ["kind", "task", "originalStatus", "packagePath", "documentClaim"]) && validateTaskV1(value.task).length === 0 && isNonEmptyString(value.originalStatus) && typeof value.packagePath === "string" && value.packagePath.startsWith(`tasks/${(value.task as TaskV1).taskId}-`) && validClaim(value.documentClaim, "text/markdown") && (value.documentClaim as MigrationDocumentClaim).path === `${value.packagePath}/INDEX.md`; }
function validDecisionEntity(value: Readonly<Record<string, unknown>>): boolean { if (!hasOnlyFields(value, ["kind", "decision", "documentClaim"]) || !isRecord(value.decision) || !validClaim(value.documentClaim, "text/markdown")) return false; const decision = value.decision, claim = value.documentClaim as MigrationDocumentClaim; return /^dec_[A-Za-z0-9_-]+$/u.test(String(decision.decisionId)) && (decisionStates as readonly unknown[]).includes(decision.state) && isNonEmptyString(decision.title) && timestamp(decision.proposedAt) && (decision.decidedAt === null || timestamp(decision.decidedAt)) && claim.path === `decisions/decision-${String(decision.decisionId)}/decision.md` && Array.isArray(decision.chosen) && Array.isArray(decision.rejected) && Array.isArray(decision.claims) && Array.isArray(decision.relations) && Array.isArray(decision.judgmentConsents); }
function validFactEntity(value: Readonly<Record<string, unknown>>): boolean { if (!hasOnlyFields(value, ["kind", "fact", "documentClaim"]) || !isRecord(value.fact) || !validClaim(value.documentClaim, "text/markdown")) return false; const fact = value.fact; return isNonEmptyString(fact.taskId) && /^F-[0-9A-HJKMNP-TV-Z]{8}$/u.test(String(fact.factId)) && isNonEmptyString(fact.statement) && isNonEmptyString(fact.evidenceSource) && timestamp(fact.observedAt) && (factConfidenceLevels as readonly unknown[]).includes(fact.confidence) && (factMemoryClasses as readonly unknown[]).includes(fact.memoryClass) && Array.isArray(fact.memoryTags) && fact.memoryTags.every((tag) => (factMemoryTags as readonly unknown[]).includes(tag)) && Array.isArray(fact.provenance) && fact.provenance.length > 0 && fact.provenance.every((entry) => isRecord(entry) && hasOnlyFields(entry, ["runtime", "sessionId", "boundAt"]) && (factProvenanceRuntimes as readonly unknown[]).includes(entry.runtime) && isNonEmptyString(entry.sessionId) && timestamp(entry.boundAt)); }
function validExecutionEntity(value: Readonly<Record<string, unknown>>): boolean { if (!hasOnlyFields(value, ["kind", "execution", "documentClaim"]) || validateArchivedExecutionV0(value.execution).length || !validClaim(value.documentClaim, "application/json")) return false; const execution = value.execution as ArchivedExecutionV0, claim = value.documentClaim as MigrationDocumentClaim; return claim.path.startsWith(`tasks/${execution.taskId}-`) && claim.path.endsWith(`/executions/${execution.executionId}.md`); }
function validTaskDocumentEntity(value: Readonly<Record<string, unknown>>): boolean { if (!hasOnlyFields(value, ["kind", "taskId", "documentClaim"]) || !isNonEmptyString(value.taskId) || !validClaim(value.documentClaim)) return false; const claim = value.documentClaim as MigrationDocumentClaim; return claim.path.startsWith(`tasks/${value.taskId}-`) && !/^tasks\/[^/]+\/INDEX\.md$/u.test(claim.path) && !/^tasks\/[^/]+\/executions\/[^/]+\.md$/u.test(claim.path); } function validRepoDocumentEntity(value: Readonly<Record<string, unknown>>): boolean { if (!hasOnlyFields(value, ["kind", "documentClaim", "referencedContentClaims"]) || !validClaim(value.documentClaim) || !Array.isArray(value.referencedContentClaims) || !value.referencedContentClaims.every(validReferencedContentClaim)) return false; const claim = value.documentClaim as MigrationDocumentClaim, references = value.referencedContentClaims as readonly MigrationReferencedContentClaim[], hashes = references.map(({ sha256 }) => sha256); return new Set(hashes).size === hashes.length && !hashes.includes(claim.sha256) && !/^(?:tasks\/[^/]+\/|decisions\/[^/]+\/|presets(?:\/|$)|objects(?:\/|$)|events(?:\/|$))/u.test(claim.path) && claim.path !== "harness.yaml"; }
function validRelationEntity(value: Readonly<Record<string, unknown>>): boolean { if (!hasOnlyFields(value, ["kind", "relation", "ownerRef"]) || !isRecord(value.relation) || !isNonEmptyString(value.ownerRef)) return false; const relation = value.relation; return hasOnlyFields(relation, ["relation_id", "source", "target", "type", "strength", "direction", "origin", "rationale", "state"]) && relation.relation_id === deriveRelationId(relation as unknown as EntityRelationRecord) && isNonEmptyString(relation.source) && isNonEmptyString(relation.target) && (relationTypes as readonly unknown[]).includes(relation.type) && (relationStrengths as readonly unknown[]).includes(relation.strength) && (relationDirections as readonly unknown[]).includes(relation.direction) && (relationOrigins as readonly unknown[]).includes(relation.origin) && (relationStates as readonly unknown[]).includes(relation.state) && isNonEmptyString(relation.rationale); }
function validClaim(value: unknown, mediaType?: MigrationDocumentClaim["mediaType"]): value is MigrationDocumentClaim { if (!isRecord(value) || !hasOnlyFields(value, ["path", "sha256", "size", "mediaType", "policyId"]) || !isNonEmptyString(value.mediaType) || mediaType !== undefined && value.mediaType !== mediaType || value.policyId !== MIGRATION_DOCUMENT_POLICY_ID || !/^[0-9a-f]{64}$/u.test(String(value.sha256)) || !Number.isSafeInteger(value.size) || (value.size as number) < 0) return false; try { return normalizeRelativeDocumentPath(String(value.path)) === value.path; } catch { return false; } } function validReferencedContentClaim(value: unknown): value is MigrationReferencedContentClaim { return isRecord(value) && hasOnlyFields(value, ["sha256", "size", "mediaType"]) && /^[0-9a-f]{64}$/u.test(String(value.sha256)) && Number.isSafeInteger(value.size) && (value.size as number) >= 0 && isNonEmptyString(value.mediaType); }
function timestamp(value: unknown): value is string { return typeof value === "string" && Number.isFinite(Date.parse(value)); }
