import type { StatusVocabulary } from "./status-vocabulary-types.ts";

export const statusVocabularies: readonly StatusVocabulary[] = [
  {
    id: "task.status",
    entity: "Task",
    field: "status",
    module: "packages/kernel/src/domain/lifecycle-status.ts",
    anchor: "domainStatuses",
    words: ["planned", "active", "blocked", "in_review", "done", "cancelled"],
  },
  {
    id: "task.status.open",
    entity: "Task",
    field: "status",
    module: "packages/kernel/src/domain/lifecycle-status.ts",
    anchor: "openDomainStatuses",
    words: ["planned", "active", "blocked", "in_review"],
    subsetOf: "task.status",
    note: "Coarse open class of task statuses.",
  },
  {
    id: "task.status.terminal",
    entity: "Task",
    field: "status",
    module: "packages/kernel/src/domain/lifecycle-status.ts",
    anchor: "terminalDomainStatuses",
    words: ["done", "cancelled"],
    subsetOf: "task.status",
    note: "Coarse terminal class of task statuses.",
  },
  {
    id: "task.status.review-artifacts",
    entity: "Task",
    field: "status",
    module: "packages/kernel/src/domain/lifecycle-status.ts",
    anchor: "reviewArtifactStatuses",
    words: ["in_review", "done"],
    subsetOf: "task.status",
    note: "Statuses whose review artifacts are required.",
  },
  {
    id: "task.status.wip-occupying",
    entity: "Task",
    field: "status",
    module: "packages/kernel/src/domain/task-wip-policy.ts",
    anchor: "taskWipOccupyingStatuses",
    words: ["active", "blocked", "in_review"],
    subsetOf: "task.status",
    note: "Statuses that occupy a WIP slot.",
  },
  {
    id: "task.status.replay",
    entity: "Task",
    field: "status",
    module: "packages/kernel/src/domain/task.ts",
    anchor: "replayTaskStatuses",
    words: ["planned", "active", "blocked", "in_review", "done", "cancelled"],
    subsetOf: "task.status",
    note: "Task/v1 wire validator set; same words, same meanings.",
  },
  {
    id: "decision.state",
    entity: "Decision",
    field: "state",
    module: "packages/kernel/src/domain/decision-event-types.ts",
    anchor: "decisionStates",
    words: ["proposed", "in_effect", "rejected", "deferred", "superseded", "outcome_retired"],
  },
  {
    id: "decision.judgment.target",
    entity: "Decision",
    field: "judgment targetState",
    module: "packages/kernel/src/domain/decision-event-types.ts",
    anchor: "#targetState",
    words: ["in_effect", "rejected", "deferred"],
    subsetOf: "decision.state",
    note: "Consent target states of the three judgment actions.",
  },
  {
    id: "execution.state",
    entity: "Execution",
    field: "state",
    module: "packages/kernel/src/domain/execution.ts",
    anchor: "executionStates",
    words: ["active", "submitted", "accepted", "changes_requested", "abandoned"],
  },
  {
    id: "execution.state.v1",
    entity: "Execution",
    field: "state",
    module: "packages/kernel/src/domain/execution.ts",
    anchor: "executionV1States",
    words: ["active", "submitted", "changes_requested", "accepted"],
    subsetOf: "execution.state",
    note: "Native execution/v1 subset (archived v0 adds abandoned).",
  },
  {
    id: "lease.phase",
    entity: "Lease",
    field: "phase",
    module: "packages/kernel/src/domain/execution.ts",
    anchor: "leasePhases",
    words: ["reserving", "held", "orphaned", "released"],
  },
  {
    id: "relation.state",
    entity: "RelationEdge",
    field: "state",
    module: "packages/kernel/src/domain/entity-relation.ts",
    anchor: "relationStates",
    words: ["active", "edge_retired", "deleted"],
  },
  {
    id: "task-blocking.assessment",
    entity: "Task",
    field: "blocking state",
    module: "packages/kernel/src/domain/task-blocking.ts",
    anchor: "BlockingAssessmentState",
    words: ["blocked", "clear", "unknown"],
    note: "Verdict of blockingOf per task; distinct from task.status blocked (a lifecycle state), hence entity-scoped.",
  },
  {
    id: "decision-coverage.status",
    entity: "Decision",
    field: "claim coverage status",
    module: "packages/kernel/src/domain/decision-coverage.ts",
    anchor: "#status",
    words: ["covered", "uncovered"],
    note: "Verdict of coverageOf per claim; a read-model judgment, not a Decision lifecycle state.",
  },
  {
    id: "fact.liveness",
    entity: "FactRecord",
    field: "liveness",
    module: "packages/kernel/src/domain/fact-liveness.ts",
    anchor: "FactLiveness",
    words: ["standing", "superseded_fact"],
    note:
      "Single domain derivation of fact liveness (factLiveness); same two words and meanings as " +
      "fact-record.state, now computed in one place.",
  },
  {
    id: "closeout.gate-status",
    entity: "TaskCloseout",
    field: "gate status",
    module: "packages/kernel/src/domain/closeout-readiness.ts",
    anchor: "CloseoutGateStatus",
    words: ["passed", "failed", "missing", "unknown"],
    note: "Per-gate verdict inside closeoutReadiness; the readiness label aggregates these.",
  },
  {
    id: "task-blocking.availability",
    entity: "Task",
    field: "blocking projection availability",
    module: "packages/kernel/src/domain/task-blocking.ts",
    anchor: "BlockingAvailabilityState",
    words: ["ready", "loading", "error"],
    note: "Relation-projection availability feeding blockingOf; degraded states make every task's blocking unknown.",
  },
  {
    id: "package.disposition",
    entity: "Package",
    field: "disposition",
    module: "packages/kernel/src/domain/package-disposition.ts",
    anchor: "packageDispositions",
    words: ["active", "archived", "tombstoned"],
  },
  {
    id: "task-package.disposition",
    entity: "Package",
    field: "disposition",
    module: "packages/kernel/src/domain/task.ts",
    anchor: "TaskPackageDisposition",
    words: ["active", "archived", "tombstoned"],
    subsetOf: "package.disposition",
    note: "Inline alias of the package disposition vocabulary on Task documents.",
  },
  {
    id: "task-wip.package-disposition",
    entity: "Package",
    field: "disposition",
    module: "packages/kernel/src/domain/task-wip-policy.ts",
    anchor: "#packageDisposition",
    words: ["active", "archived", "tombstoned"],
    subsetOf: "package.disposition",
    note: "WIP snapshot entry mirror of the package disposition vocabulary.",
  },
  {
    id: "fact-record.state",
    entity: "FactRecord",
    field: "state",
    module: "packages/kernel/src/domain/fact-event.ts",
    anchor: "#state",
    words: ["standing", "superseded_fact"],
    note:
      "Per-fact row state in authored facts documents; the SQL projection derives the same two words from active " +
      "supersedes-fact edges.",
  },
  {
    id: "review.verdict",
    entity: "Review",
    field: "verdict",
    module: "packages/kernel/src/domain/review.ts",
    anchor: "reviewVerdicts",
    words: ["approved", "changes_requested", "dismissed"],
  },
  {
    id: "runtime.liveness",
    entity: "RuntimeSession",
    field: "liveness",
    module: "packages/kernel/src/domain/agent-runtime.ts",
    anchor: "runtimeLivenessStates",
    words: ["live", "stale", "unknown", "exited"],
  },
  {
    id: "runtime.outcome",
    entity: "RuntimeSession",
    field: "outcome",
    module: "packages/kernel/src/domain/agent-runtime.ts",
    anchor: "#outcome",
    words: ["succeeded", "failed", "unknown", "cancelled"],
  },
  {
    id: "runtime.semantic-state",
    entity: "RuntimeSession",
    field: "semantic state",
    module: "packages/kernel/src/domain/agent-runtime.ts",
    anchor: "RuntimeSessionSemanticState",
    words: ["running", "succeeded", "failed", "cancelled", "ended-indeterminate", "unavailable"],
    note: "A judgment derived from the independent liveness and outcome facts; not a stored field.",
  },
  {
    id: "wire.dispatch-status",
    entity: "DaemonWire",
    field: "status",
    module: "packages/daemon/src/protocol/daemon-protocol-gui-types.ts",
    anchor: "#status",
    words: ["running", "succeeded", "failed", "unknown", "cancelled"],
    mirrorOf: "runtime.outcome",
    plusWords: ["running"],
    note: "TaskDispatchRow.status is the session outcome plus \"running\" while a dispatch is in flight.",
  },
  {
    id: "runtime.transcript-reachability",
    entity: "RuntimeSession",
    field: "transcript reachability",
    module: "packages/kernel/src/domain/agent-runtime.ts",
    anchor: "transcriptReachabilityStates",
    words: ["by_session_id", "dispatch_stream_only", "unavailable"],
  },
  {
    id: "receipt.outcome",
    entity: "WriteReceipt",
    field: "outcome",
    module: "packages/kernel/src/domain/write-chain.contract.ts",
    anchor: "writeReceiptOutcomes",
    words: ["applied", "pending", "indeterminate", "op_rejected"],
  },
  {
    id: "receipt.detail.outcome",
    entity: "WriteReceipt",
    field: "outcome",
    module: "packages/kernel/src/domain/receipt-domain-registry.ts",
    anchor: "#outcome",
    words: ["applied", "pending", "indeterminate", "op_rejected"],
    subsetOf: "receipt.outcome",
    note: "The WriteReceipt interface repeats the outcome vocabulary; must stay equal to writeReceiptOutcomes.",
  },
  {
    id: "recovery.state",
    entity: "Recovery",
    field: "state",
    module: "packages/kernel/src/domain/write-chain.contract.ts",
    anchor: "recoveryStates",
    words: ["queued", "running", "exhausted", "failed", "drained"],
  },
  {
    id: "closeout.readiness",
    entity: "TaskCloseout",
    field: "readiness",
    module: "packages/kernel/src/domain/closeout-readiness.ts",
    anchor: "closeoutReadinesses",
    words: ["not_required", "missing", "incomplete", "ready", "passed", "failed"],
  },
  {
    id: "task.session-disposition",
    entity: "Task",
    field: "sessionBinding disposition",
    module: "packages/kernel/src/domain/task-lifecycle-contract-internal-types.ts",
    anchor: "#sessionDisposition",
    words: ["complete", "partial", "unavailable"],
    note: "Witness availability, not entity standing.",
  },
  {
    id: "vertical-script.disposition",
    entity: "VerticalScript",
    field: "disposition",
    module: "packages/kernel/src/domain/vertical-script-action.ts",
    anchor: "#disposition",
    words: ["create", "replace"],
  },

  // GUI model mirrors (renderer may not import kernel runtime values; the gate locks text equality).
  {
    id: "gui.task.status",
    entity: "GuiAdapter",
    field: "status",
    module: "packages/gui/src/renderer/model/types.ts",
    anchor: "CanonicalStatus",
    words: ["planned", "active", "blocked", "in_review", "done", "cancelled"],
    mirrorOf: "task.status",
  },
  {
    id: "gui.task.snapshot-status",
    entity: "GuiAdapter",
    field: "status",
    module: "packages/gui/src/renderer/model/types.ts",
    anchor: "SnapshotStatus",
    words: ["planned", "active", "blocked", "in_review", "done", "cancelled", "unknown"],
    mirrorOf: "task.status",
    plusWords: ["unknown"],
  },
  {
    id: "gui.decision.state",
    entity: "GuiAdapter",
    field: "state",
    module: "packages/gui/src/renderer/model/types.ts",
    anchor: "DecisionState",
    words: ["proposed", "in_effect", "rejected", "deferred", "superseded", "outcome_retired", "unknown"],
    mirrorOf: "decision.state",
    plusWords: ["unknown"],
  },
  {
    id: "gui.package.disposition",
    entity: "GuiAdapter",
    field: "disposition",
    module: "packages/gui/src/renderer/model/types.ts",
    anchor: "PackageDisposition",
    words: ["active", "archived", "tombstoned"],
    mirrorOf: "package.disposition",
  },

  // Daemon wire-protocol mirrors. The contract sits on the CLI's eager startup path, so
  // it must not import the kernel barrel (the p50 overhead gate refuses eager module
  // growth); the mirrors stay plain data and the ratchet gate locks them to the kernel.
  {
    id: "daemon.task.status",
    entity: "DaemonWire",
    field: "status",
    module: "packages/daemon/src/protocol/daemon-protocol-vocabulary.ts",
    anchor: "taskStatusWords",
    words: ["planned", "active", "blocked", "in_review", "done", "cancelled"],
    mirrorOf: "task.status",
  },
  {
    id: "daemon.execution.state",
    entity: "DaemonWire",
    field: "state",
    module: "packages/daemon/src/protocol/daemon-protocol-vocabulary.ts",
    anchor: "executionStateWords",
    words: ["active", "submitted", "accepted", "changes_requested", "abandoned"],
    mirrorOf: "execution.state",
  },
  {
    id: "daemon.execution.state-v1",
    entity: "DaemonWire",
    field: "state",
    module: "packages/daemon/src/protocol/daemon-protocol-vocabulary.ts",
    anchor: "executionV1StateWords",
    words: ["active", "submitted", "changes_requested", "accepted"],
    mirrorOf: "execution.state.v1",
  },
  {
    id: "daemon.lease.phase",
    entity: "DaemonWire",
    field: "phase",
    module: "packages/daemon/src/protocol/daemon-protocol-vocabulary.ts",
    anchor: "leasePhaseWords",
    words: ["reserving", "held", "orphaned", "released"],
    mirrorOf: "lease.phase",
  },
  {
    id: "daemon.relation.state",
    entity: "DaemonWire",
    field: "state",
    module: "packages/daemon/src/protocol/daemon-protocol-vocabulary.ts",
    anchor: "relationStateWords",
    words: ["active", "edge_retired", "deleted"],
    mirrorOf: "relation.state",
  },
  {
    id: "daemon.package.disposition",
    entity: "DaemonWire",
    field: "disposition",
    module: "packages/daemon/src/protocol/daemon-protocol-vocabulary.ts",
    anchor: "packageDispositionWords",
    words: ["active", "archived", "tombstoned"],
    mirrorOf: "package.disposition",
  },
  {
    id: "daemon.review.verdict",
    entity: "DaemonWire",
    field: "verdict",
    module: "packages/daemon/src/protocol/daemon-protocol-vocabulary.ts",
    anchor: "reviewVerdictWords",
    words: ["approved", "changes_requested", "dismissed"],
    mirrorOf: "review.verdict",
  },
  {
    id: "daemon.decision.state",
    entity: "DaemonWire",
    field: "state",
    module: "packages/daemon/src/protocol/daemon-protocol-vocabulary.ts",
    anchor: "decisionStateWords",
    words: ["proposed", "in_effect", "rejected", "deferred", "superseded", "outcome_retired"],
    mirrorOf: "decision.state",
  },
  {
    id: "daemon.receipt.outcome",
    entity: "DaemonWire",
    field: "outcome",
    module: "packages/daemon/src/protocol/daemon-protocol-vocabulary.ts",
    anchor: "receiptOutcomeWords",
    words: ["applied", "pending", "indeterminate", "op_rejected"],
    mirrorOf: "receipt.outcome",
  },
];
