import { isNativeCommitSha, validateExecutionV1, validateLeaseHolder, validateLeaseV1 } from "./execution.ts";
import type { ExecutionV1, LeaseHolder, LeaseV1 } from "./execution.ts";
import { validateReviewConsentV1, validateReviewV1 } from "./review.ts";
import type { ReviewConsentV1, ReviewV1 } from "./review.ts";
import { validateActorAxes, validateTaskV1 } from "./task.ts";
import type { ActorAxes, ContractValidationIssue, TaskV1 } from "./task.ts";
import { validateTaskGraph } from "./task-graph.ts";
import type { TaskEdgeTaken } from "./task-graph.ts";
import { validateCodeDocWitnessV1, type CodeDocWitnessV1 } from "./code-doc-witness.ts";
import { validateCompletionGateWitnessV1, type CompletionGateWitnessV1 } from "./completion-gate-witness.ts";
import { hasOnlyFields, isNonEmptyString, isRecord, serializeEventEnvelope, validateWriteSource } from "./write-chain.contract.ts";
import type { EventEnvelope } from "./write-chain.contract.ts";
import { normalizeRelativeDocumentPath } from "../layout/portable-path.ts";
import { stableStringify } from "../integrity/stable-hash.ts";
export const taskEventTypes = ["task_created", "execution_started", "lease_renewed", "execution_submitted", "review_recorded", "review_consent_recorded", "code_doc_reconciled", "completion_gate_verified", "task_completed"] as const;
export type TaskEventType = (typeof taskEventTypes)[number];
export interface LifecycleDocumentClaim { readonly path: string; readonly sha256: string; readonly size: number; readonly mediaType: "text/markdown" | "application/json"; readonly policyId: "typed-machine-writer/v1" }
type TaskEventEnvelope<T extends TaskEventType, P> = EventEnvelope<"task-event/v1", T, ActorAxes, P & { readonly documentClaims: readonly LifecycleDocumentClaim[] }> & { readonly taskId: string };
export type TaskCreatedEvent = EventEnvelope<"task-event/v1", "task_created", ActorAxes, { readonly task: TaskV1; readonly documentClaims?: readonly LifecycleDocumentClaim[] }> & { readonly taskId: string };
export type LeaseChangeReason = "initial_claim" | "same_principal_reconnect" | "ttl_expired_takeover";
export type ExecutionStartedEvent = TaskEventEnvelope<"execution_started", { readonly task: TaskV1; readonly execution: ExecutionV1; readonly lease: LeaseV1; readonly previousHolder: LeaseHolder | null; readonly leaseExpiresAt: string; readonly reason: LeaseChangeReason }>;
export type LeaseRenewedEvent = TaskEventEnvelope<"lease_renewed", { readonly task: TaskV1; readonly execution: ExecutionV1; readonly lease: LeaseV1; readonly previousHolder: LeaseHolder; readonly leaseExpiresAt: string; readonly reason: "same_principal_reconnect" }>;
export type ExecutionSubmittedEvent = TaskEventEnvelope<"execution_submitted", { readonly task: TaskV1; readonly execution: ExecutionV1; readonly edge: TaskEdgeTaken }>;
export type ReviewRecordedEvent = TaskEventEnvelope<"review_recorded", { readonly task: TaskV1; readonly execution: ExecutionV1; readonly review: ReviewV1; readonly edge?: TaskEdgeTaken }>;
export type ReviewConsentRecordedEvent = TaskEventEnvelope<"review_consent_recorded", { readonly task: TaskV1; readonly execution: ExecutionV1; readonly review: ReviewV1; readonly consent: ReviewConsentV1 }>;
export type CodeDocReconciledEvent = TaskEventEnvelope<"code_doc_reconciled", { readonly task: TaskV1; readonly execution: ExecutionV1; readonly witness: CodeDocWitnessV1 }>;
export type CompletionGateVerifiedEvent = TaskEventEnvelope<"completion_gate_verified", { readonly task: TaskV1; readonly execution: ExecutionV1; readonly witness: CompletionGateWitnessV1 }>;
export type TaskCompletedEvent = TaskEventEnvelope<"task_completed", { readonly task: TaskV1; readonly execution: ExecutionV1 }>;
export type TaskEventV1 = TaskCreatedEvent | ExecutionStartedEvent | LeaseRenewedEvent | ExecutionSubmittedEvent | ReviewRecordedEvent | ReviewConsentRecordedEvent | CodeDocReconciledEvent | CompletionGateVerifiedEvent | TaskCompletedEvent;
export type TaskLifecycleErrorCode = "invalid_schema" | "invalid_transition" | "invalid_proof" | "invalid_graph" | "manual_intervention_required" | "frozen_write_plan";
export class TaskLifecycleContractError extends Error { readonly code: TaskLifecycleErrorCode; readonly issues: readonly ContractValidationIssue[]; constructor(code: TaskLifecycleErrorCode, issues: readonly ContractValidationIssue[]) { super(issues.map((issue) => issue.message).join("; ")); this.name = "TaskLifecycleContractError"; this.code = code; this.issues = issues; } }
export const TASK_EVENT_V1_SCHEMA = Object.freeze({ id: "task-event/v1", required: Object.freeze(["schema", "eventId", "workspaceRevision", "opId", "taskId", "type", "actor", "source", "occurredAt", "payload"]), types: taskEventTypes });
export function validateTaskEvent(value: unknown): readonly ContractValidationIssue[] {
  if (!isRecord(value) || !hasOnlyFields(value, TASK_EVENT_V1_SCHEMA.required)) return [bad("task-event/v1 fields are incomplete or unknown")]; const issues: ContractValidationIssue[] = [];
  if (value.schema !== "task-event/v1") issues.push({ code: "invalid_schema", message: "event must use task-event/v1" });
  if (!isNonEmptyString(value.eventId) || !isNonEmptyString(value.opId) || !isNonEmptyString(value.taskId) || !isNonEmptyString(value.occurredAt) || !Number.isInteger(value.workspaceRevision) || (value.workspaceRevision as number) < 1 || !taskEventTypes.includes(value.type as TaskEventType)) issues.push(bad("event identity, revision, or type is invalid"));
  issues.push(...validateActorAxes(value.actor)); if (validateWriteSource(value.source).length) issues.push(bad("event source is invalid")); if (!isRecord(value.payload)) return [...issues, bad("event payload must be an object")];
  const payload = value.payload, fields = payloadFields(String(value.type), Object.hasOwn(payload, "edge")), claims = payload.documentClaims;
  const claimlessFields = value.type === "task_created" ? ["task"] : payloadFields(String(value.type), Object.hasOwn(payload, "edge")).filter((field) => field !== "documentClaims");
  const validPayloadFields = (value.type === "task_created" || value.type === "lease_renewed") && claims === undefined ? hasOnlyFields(payload, claimlessFields) : hasOnlyFields(payload, fields);
  if (!validPayloadFields || claims !== undefined && (!Array.isArray(claims) || claims.some((claim) => !validClaim(claim)))) return [...issues, bad(`${String(value.type)} payload fields or document claims are invalid`)];
  issues.push(...validateTaskV1(payload.task)); if (value.type !== "task_created") issues.push(...validateExecutionV1(payload.execution));
  if (value.type === "execution_started" || value.type === "lease_renewed") { issues.push(...validateLeaseV1(payload.lease)); if (payload.previousHolder !== null) issues.push(...validateLeaseHolder(payload.previousHolder)); if (!isNonEmptyString(payload.leaseExpiresAt) || !["initial_claim", "same_principal_reconnect", "ttl_expired_takeover"].includes(String(payload.reason)) || value.type === "lease_renewed" && (payload.previousHolder === null || payload.reason !== "same_principal_reconnect")) issues.push(bad("lease event history is invalid")); }
  if (value.type === "review_recorded") issues.push(...validateReviewV1(payload.review)); if (value.type === "review_consent_recorded") issues.push(...validateReviewV1(payload.review), ...validateReviewConsentV1(payload.consent)); if (value.type === "code_doc_reconciled") issues.push(...validateCodeDocWitnessV1(payload.witness)); if (value.type === "completion_gate_verified") { issues.push(...validateCompletionGateWitnessV1(payload.witness)); if (isRecord(payload.witness) && (payload.witness.receiptId !== value.opId || payload.witness.taskId !== value.taskId || stableStringify(payload.witness.actor) !== stableStringify(value.actor) || stableStringify(payload.witness.source) !== stableStringify(value.source))) issues.push(bad("completion gate witness must be pinned to its canonical event receipt")); } if ("edge" in payload) issues.push(...validateEdge(payload.edge));
  if (isRecord(payload.task) && "graph" in payload.task) issues.push(...validateTaskGraph(payload.task.graph)); if (isRecord(payload.task) && payload.task.taskId !== value.taskId) issues.push(bad("payload Task identity must match the envelope")); return issues;
}
function payloadFields(type: string, edge: boolean): readonly string[] { const common = ["task", "execution", "documentClaims"]; if (type === "task_created") return ["task", "documentClaims"]; if (type === "execution_started" || type === "lease_renewed") return [...common, "lease", "previousHolder", "leaseExpiresAt", "reason"]; if (type === "execution_submitted") return [...common, "edge"]; if (type === "review_recorded") return [...common, "review", ...(edge ? ["edge"] : [])]; if (type === "review_consent_recorded") return [...common, "review", "consent"]; if (type === "code_doc_reconciled" || type === "completion_gate_verified") return [...common, "witness"]; return common; }
function validClaim(value: unknown): value is LifecycleDocumentClaim { if (!isRecord(value) || !hasOnlyFields(value, ["path", "sha256", "size", "mediaType", "policyId"]) || !/^[0-9a-f]{64}$/u.test(String(value.sha256)) || !Number.isSafeInteger(value.size) || (value.size as number) < 0 || !["text/markdown", "application/json"].includes(String(value.mediaType)) || value.policyId !== "typed-machine-writer/v1") return false; try { return normalizeRelativeDocumentPath(String(value.path)) === value.path; } catch { return false; } }
function validateEdge(value: unknown): readonly ContractValidationIssue[] { return !isRecord(value) || !hasOnlyFields(value, ["edgeId", "from", "to", "on", "actorRole", "reason", "commitSha", "iteration"]) || !isNonEmptyString(value.edgeId) || !isNonEmptyString(value.reason) || !["implementation", "review"].includes(String(value.from)) || !["implementation", "review"].includes(String(value.to)) || !["submitted", "changes_requested"].includes(String(value.on)) || !["executor", "reviewer"].includes(String(value.actorRole)) || !isNativeCommitSha(value.commitSha) || !Number.isInteger(value.iteration) || (value.iteration as number) < 0 || (value.iteration as number) > 1 ? [{ code: "invalid_edge_evidence", message: "taken edge requires its audit fields" }] : []; }
function bad(message: string): ContractValidationIssue { return { code: "invalid_event_payload", message }; }
export function serializeTaskEvent(value: TaskEventV1): string { const issues = validateTaskEvent(value); if (issues.length) throw new TaskLifecycleContractError("invalid_schema", issues); return serializeEventEnvelope(value); }
