// harness-test-tier: integration
import assert from "node:assert/strict";
import { mkdirSync, writeFileSync } from "node:fs";
import path from "node:path";
import test from "node:test";
import { REPLAY_TASK_GRAPH, checkTaskProjection, compileDecisionWrite, compileFactWrite, decisionWritePlan, deriveRelationId, formatRelationFlowRecord, makeTaskProjection, readRelationGraphProjection, taskLifecycleWritePlan, type DecisionEventDraftV1, type EntityRelationRecord, type FactEventDraftV1, type TaskEventV1 } from "../../src/index.ts";
import { withTempStore } from "./helpers.ts";

const actor = { principal: { personId: "proposer" }, executor: null } as const;

test("real post-merge entry resolves event-backed Decision anchors and rejects unknown anchors", () => { withTempStore((rootDir) => { const fixture = projectionFixture(rootDir); applyDecision(fixture, proposal(1, "dec_KNOWN")); writeTask(rootDir, "task-authored", relation({ source: "task/task-authored", target: "decision/dec_KNOWN/CH1", type: "implements" })); const pass = checkTaskProjection({ rootDir, postMerge: true }); assert.equal(pass.ok, true, JSON.stringify(pass.warnings));
    writeTask(rootDir, "task-authored", relation({ source: "task/task-authored", target: "decision/dec_KNOWN/CH404", type: "implements" })); const fail = checkTaskProjection({ rootDir, postMerge: true }); assert.equal(fail.ok, false); assert.equal(fail.warnings.some(({ code }) => code === "relation_endpoint_unknown"), true); }); });

test("GUI graph and post-merge consume the same event-backed Decision/Fact edge truth", () => { withTempStore((rootDir) => { const fixture = projectionFixture(rootDir); applyDecision(fixture, proposal(1, "dec_GRAPH")); applyFact(fixture, fact(2)); const edge = relation({ source: "decision/dec_GRAPH/C1", target: "fact/task-evidence/F-DEADBEEF", type: "evidenced-by" }); applyDecision(fixture, claim(3, "dec_GRAPH")); applyDecision(fixture, related(4, "dec_GRAPH", edge)); const graph = readRelationGraphProjection({ rootDir }); assert.deepEqual(graph.edges.map(({ relationId }) => relationId), [edge.relation_id]); assert.equal(checkTaskProjection({ rootDir, postMerge: true }).ok, true); }); });

test("real post-merge cycle check includes canonical Decision edges and task-authored edges", () => { withTempStore((rootDir) => { const fixture = projectionFixture(rootDir), projection = fixture.projection, created = taskCreated(1, "task-cycle"); projection.apply(created, taskLifecycleWritePlan(created)); applyDecision(fixture, proposal(2, "dec_CYCLE")); const derives = relation({ source: "decision/dec_CYCLE", target: "task/task-cycle", type: "derives" }); applyDecision(fixture, related(3, "dec_CYCLE", derives)); writeTask(rootDir, "task-cycle", relation({ source: "task/task-cycle", target: "decision/dec_CYCLE", type: "implements" })); const result = checkTaskProjection({ rootDir, postMerge: true }); assert.equal(result.ok, false); assert.equal(result.warnings.some(({ code }) => code === "relation_cycle_detected"), true); }); });

test("Decision projection requires exact plan, content hash, render, consent pin, and document base", () => { withTempStore((rootDir) => { const fixture = projectionFixture(rootDir), draft = proposal(1, "dec_EXACT"), compiled = compileDecisionWrite({ event: draft, currentDecision: null, currentRelations: [], currentDocument: null }), forgedSha = "0".repeat(64), forged = { ...compiled.event, payload: { ...compiled.event.payload, decisionDocumentClaim: { ...compiled.event.payload.decisionDocumentClaim, sha256: forgedSha } } }; fixture.blobs.set(forgedSha, Buffer.from(compiled.body)); assert.throws(() => fixture.projection.apply(compiled.event), /write plan/u); assert.throws(() => fixture.projection.apply(forged, decisionWritePlan(forged)), /projection mismatch/u); assert.equal(fixture.projection.readDecision("dec_EXACT").decision, null);
  applyDecision(fixture, draft); const next = compileCurrent(fixture, accepted(2, "dec_EXACT")), tampered = { ...next.event, payload: { ...next.event.payload, judgmentConsent: { ...next.event.payload.judgmentConsent, machineDigest: `sha256:${"0".repeat(64)}` as const } } }, stale = { ...next.event, payload: { ...next.event.payload, baseDocumentSha256: "0".repeat(64) } }; fixture.blobs.set(next.blobs[0].sha256, Buffer.from(next.body)); assert.throws(() => fixture.projection.apply(tampered, decisionWritePlan(tampered)), /machine content cut/u); assert.throws(() => fixture.projection.apply(stale, decisionWritePlan(stale)), /base.*mismatch/u); assert.equal(fixture.projection.readDecision("dec_EXACT").decision?.state, "proposed"); }); });

function proposal(revision: number, decisionId: string): DecisionEventDraftV1 { return { schema: "decision-event/v1", eventId: `event-${revision}`, workspaceRevision: revision, opId: `op-${revision}`, decisionId, type: "decision_proposed", actor, source: "local", occurredAt: "2026-08-13T00:00:00.000Z", payload: { title: "Canonical Decision", question: "Is this event-backed?", riskTier: "medium", urgency: "medium", vertical: "test", preset: "default", appliesTo: { modules: ["kernel"], productLines: [] }, decisionClass: "ordinary", chosen: [{ id: "CH1", text: "Use events" }], rejected: [{ id: "RJ1", text: "Use files", whyNot: "Files are not canonical." }] } }; }
function claim(revision: number, decisionId: string): DecisionEventDraftV1 { return { schema: "decision-event/v1", eventId: `event-${revision}`, workspaceRevision: revision, opId: `op-${revision}`, decisionId, type: "decision_claim_declared", actor, source: "local", occurredAt: "2026-08-13T00:00:00.000Z", payload: { claimId: "C1", text: "The relation truth is shared.", loadBearing: true } }; }
function accepted(revision: number, decisionId: string): DecisionEventDraftV1 { return { schema: "decision-event/v1", eventId: `event-${revision}`, workspaceRevision: revision, opId: `op-${revision}`, decisionId, type: "decision_accepted", actor: { principal: { personId: "arbiter" }, executor: null }, source: "local", occurredAt: "2026-08-13T00:00:01.000Z", payload: { rationale: "Independent approval.", judgmentOnlyRationale: "Explicit judgment-only approval." } }; }
function related(revision: number, decisionId: string, record: EntityRelationRecord): DecisionEventDraftV1 { return { schema: "decision-event/v1", eventId: `event-${revision}`, workspaceRevision: revision, opId: `op-${revision}`, decisionId, type: "decision_related", actor, source: "local", occurredAt: "2026-08-13T00:00:00.000Z", payload: { relation: record } }; }
function fact(revision: number): FactEventDraftV1 { return { schema: "fact-event/v1", eventId: `event-${revision}`, workspaceRevision: revision, opId: `op-${revision}`, taskId: "task-evidence", factId: "F-DEADBEEF", type: "fact_recorded", actor, source: "local", occurredAt: "2026-08-13T00:00:00.000Z", payload: { statement: "Event-backed evidence", evidenceSource: "test", observedAt: "2026-08-13T00:00:00.000Z", confidence: "high", memoryClass: "semantic", memoryTags: [], provenance: [{ runtime: "human", sessionId: "test", boundAt: "2026-08-13T00:00:00.000Z" }] } }; }
function taskCreated(revision: number, taskId: string): TaskEventV1 { return { schema: "task-event/v1", eventId: `event-${revision}`, workspaceRevision: revision, opId: `op-${revision}`, taskId, type: "task_created", actor, source: "local", occurredAt: "2026-08-13T00:00:00.000Z", payload: { task: { schema: "task/v1", taskId, title: "Cycle task", taskClass: "standard", status: "planned", graph: REPLAY_TASK_GRAPH, currentNode: "implementation", iteration: 0, createdBy: actor, completionGateIds: [], presetSnapshotDigest: null } } }; }
function relation(input: Pick<EntityRelationRecord, "source" | "target" | "type">): EntityRelationRecord { const identity = { ...input, direction: "directed" as const }; return { relation_id: deriveRelationId(identity), ...identity, strength: "strong", origin: "declared", rationale: "Production entry fixture.", state: "active" }; }
function projectionFixture(rootDir: string) { const blobs = new Map<string, Uint8Array>(), eventStore = { readHead: () => null, readBatch: () => ({ sourceRevision: 0, events: [], cursor: null, done: true, accessedItems: 0 }), readContentBlob: (sha256: string) => blobs.get(sha256) ?? null }; return { blobs, projection: makeTaskProjection({ rootDir, eventStore }) }; }
function compileCurrent(fixture: ReturnType<typeof projectionFixture>, event: DecisionEventDraftV1) { const { projection } = fixture, current = projection.readDecision(event.decisionId).decision, path = `decisions/decision-${event.decisionId}/decision.md`, document = projection.readDocument(path).document, relations = projection.readDecisionGraph().edges.filter((edge) => edge.ownerRef === `decision/${event.decisionId}`).map((edge) => ({ relation_id: edge.relationId, source: edge.sourceRef, target: edge.targetRef, type: edge.relationType, strength: edge.strength, direction: edge.direction, origin: edge.origin, rationale: edge.rationale, state: edge.state })); return compileDecisionWrite({ event, currentDecision: current, currentRelations: relations, currentDocument: document }); }
function applyDecision(fixture: ReturnType<typeof projectionFixture>, event: DecisionEventDraftV1): void { const compiled = compileCurrent(fixture, event); fixture.blobs.set(compiled.blobs[0].sha256, Buffer.from(compiled.body)); fixture.projection.apply(compiled.event, compiled.plan); }
function applyFact(fixture: ReturnType<typeof projectionFixture>, event: FactEventDraftV1): void { const compiled = compileFactWrite({ event, packagePath: `tasks/${event.taskId}-evidence`, currentFacts: fixture.projection.searchFacts({ taskId: event.taskId }).facts }); fixture.blobs.set(compiled.blobs[0].sha256, Buffer.from(compiled.body)); fixture.projection.apply(compiled.event, compiled.plan); }
function writeTask(rootDir: string, taskId: string, record: EntityRelationRecord): void { const taskRoot = path.join(rootDir, "harness/tasks", taskId); mkdirSync(taskRoot, { recursive: true }); writeFileSync(path.join(taskRoot, "INDEX.md"), ["---", "schema: task-package/v2", `task_id: ${taskId}`, `title: ${taskId}`, "lifecycle:", "  engine: local", "  status: active", "packageDisposition: active", "vertical: default", "preset: default", "relations:", formatRelationFlowRecord(record), "---", "", `# ${taskId}`, ""].join("\n")); }
