// harness-test-tier: integration
import assert from "node:assert/strict";
import { mkdirSync, writeFileSync } from "node:fs";
import path from "node:path";
import test from "node:test";
import { REPLAY_TASK_GRAPH, checkTaskProjection, deriveRelationId, formatRelationFlowRecord, makeTaskProjection, readRelationGraphProjection, type DecisionEventV1, type EntityRelationRecord, type FactEventV1, type TaskEventV1 } from "../../src/index.ts";
import { withTempStore } from "./helpers.ts";

const actor = { principal: { personId: "proposer" }, executor: null } as const, emptyStore = { readHead: () => null, readBatch: () => ({ sourceRevision: 0, events: [], cursor: null, done: true, accessedItems: 0 }), readContentBlob: () => null };

test("real post-merge entry resolves event-backed Decision anchors and rejects unknown anchors", () => { withTempStore((rootDir) => { const projection = makeTaskProjection({ rootDir, eventStore: emptyStore }); projection.apply(proposal(1, "dec_KNOWN")); writeTask(rootDir, "task-authored", relation({ source: "task/task-authored", target: "decision/dec_KNOWN/CH1", type: "implements" })); const pass = checkTaskProjection({ rootDir, postMerge: true }); assert.equal(pass.ok, true, JSON.stringify(pass.warnings));
    writeTask(rootDir, "task-authored", relation({ source: "task/task-authored", target: "decision/dec_KNOWN/CH404", type: "implements" })); const fail = checkTaskProjection({ rootDir, postMerge: true }); assert.equal(fail.ok, false); assert.equal(fail.warnings.some(({ code }) => code === "relation_endpoint_unknown"), true); }); });

test("GUI graph and post-merge consume the same event-backed Decision/Fact edge truth", () => { withTempStore((rootDir) => { const projection = makeTaskProjection({ rootDir, eventStore: emptyStore }); projection.apply(proposal(1, "dec_GRAPH")); projection.apply(fact(2)); const edge = relation({ source: "decision/dec_GRAPH/C1", target: "fact/task-evidence/F-DEADBEEF", type: "evidenced-by" }); projection.apply(claim(3, "dec_GRAPH")); projection.apply(related(4, "dec_GRAPH", edge)); const graph = readRelationGraphProjection({ rootDir }); assert.deepEqual(graph.edges.map(({ relationId }) => relationId), [edge.relation_id]); assert.equal(checkTaskProjection({ rootDir, postMerge: true }).ok, true); }); });

test("real post-merge cycle check includes canonical Decision edges and task-authored edges", () => { withTempStore((rootDir) => { const projection = makeTaskProjection({ rootDir, eventStore: emptyStore }); projection.apply(taskCreated(1, "task-cycle")); projection.apply(proposal(2, "dec_CYCLE")); const derives = relation({ source: "decision/dec_CYCLE", target: "task/task-cycle", type: "derives" }); projection.apply(related(3, "dec_CYCLE", derives)); writeTask(rootDir, "task-cycle", relation({ source: "task/task-cycle", target: "decision/dec_CYCLE", type: "implements" })); const result = checkTaskProjection({ rootDir, postMerge: true }); assert.equal(result.ok, false); assert.equal(result.warnings.some(({ code }) => code === "relation_cycle_detected"), true); }); });

function proposal(revision: number, decisionId: string): DecisionEventV1 { return { schema: "decision-event/v1", eventId: `event-${revision}`, workspaceRevision: revision, opId: `op-${revision}`, decisionId, type: "decision_proposed", actor, source: "local", occurredAt: "2026-08-13T00:00:00.000Z", payload: { title: "Canonical Decision", question: "Is this event-backed?", riskTier: "medium", urgency: "medium", vertical: "test", preset: "default", appliesTo: { modules: ["kernel"], productLines: [] }, decisionClass: "ordinary", chosen: [{ id: "CH1", text: "Use events" }], rejected: [{ id: "RJ1", text: "Use files", whyNot: "Files are not canonical." }] } }; }
function claim(revision: number, decisionId: string): DecisionEventV1 { return { schema: "decision-event/v1", eventId: `event-${revision}`, workspaceRevision: revision, opId: `op-${revision}`, decisionId, type: "decision_claim_declared", actor, source: "local", occurredAt: "2026-08-13T00:00:00.000Z", payload: { claimId: "C1", text: "The relation truth is shared.", loadBearing: true } }; }
function related(revision: number, decisionId: string, record: EntityRelationRecord): DecisionEventV1 { return { schema: "decision-event/v1", eventId: `event-${revision}`, workspaceRevision: revision, opId: `op-${revision}`, decisionId, type: "decision_related", actor, source: "local", occurredAt: "2026-08-13T00:00:00.000Z", payload: { relation: record } }; }
function fact(revision: number): FactEventV1 { return { schema: "fact-event/v1", eventId: `event-${revision}`, workspaceRevision: revision, opId: `op-${revision}`, taskId: "task-evidence", factId: "F-DEADBEEF", type: "fact_recorded", actor, source: "local", occurredAt: "2026-08-13T00:00:00.000Z", payload: { statement: "Event-backed evidence", evidenceSource: "test", observedAt: "2026-08-13T00:00:00.000Z", confidence: "high", memoryClass: "semantic", memoryTags: [], provenance: [{ runtime: "human", sessionId: "test", boundAt: "2026-08-13T00:00:00.000Z" }] } }; }
function taskCreated(revision: number, taskId: string): TaskEventV1 { return { schema: "task-event/v1", eventId: `event-${revision}`, workspaceRevision: revision, opId: `op-${revision}`, taskId, type: "task_created", actor, source: "local", occurredAt: "2026-08-13T00:00:00.000Z", payload: { task: { schema: "task/v1", taskId, title: "Cycle task", taskClass: "standard", status: "planned", graph: REPLAY_TASK_GRAPH, currentNode: "implementation", iteration: 0, createdBy: actor, completionGateIds: [], presetSnapshotDigest: null } } }; }
function relation(input: Pick<EntityRelationRecord, "source" | "target" | "type">): EntityRelationRecord { const identity = { ...input, direction: "directed" as const }; return { relation_id: deriveRelationId(identity), ...identity, strength: "strong", origin: "declared", rationale: "Production entry fixture.", state: "active" }; }
function writeTask(rootDir: string, taskId: string, record: EntityRelationRecord): void { const taskRoot = path.join(rootDir, "harness/tasks", taskId); mkdirSync(taskRoot, { recursive: true }); writeFileSync(path.join(taskRoot, "INDEX.md"), ["---", "schema: task-package/v2", `task_id: ${taskId}`, `title: ${taskId}`, "lifecycle:", "  engine: local", "  status: active", "packageDisposition: active", "vertical: default", "preset: default", "relations:", formatRelationFlowRecord(record), "---", "", `# ${taskId}`, ""].join("\n")); }
