// harness-test-tier: integration
import assert from "node:assert/strict";
import { execFileSync } from "node:child_process";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { DatabaseSync } from "node:sqlite";
import test from "node:test";
import { REPLAY_TASK_GRAPH, checkTaskProjection, compileDecisionWrite, compileFactWrite, decisionWritePlan, deriveRelationId, formatRelationFlowRecord, makeTaskProjection, projectDecisionReadiness, readRelationGraphProjection, taskLifecycleWritePlan, type DecisionEventDraftV1, type EntityRelationRecord, type FactEventDraftV1, type TaskEventV1 } from "../../src/index.ts";
import { withTempStore } from "./helpers.ts";

const actor = { principal: { personId: "proposer" }, executor: null } as const;

test("real post-merge entry resolves event-backed Decision anchors and rejects unknown anchors", () => { withTempStore((rootDir) => { const fixture = projectionFixture(rootDir); applyDecision(fixture, proposal(1, "dec_KNOWN")); writeTask(rootDir, "task-authored", relation({ source: "task/task-authored", target: "decision/dec_KNOWN/CH1", type: "implements" })); const pass = checkTaskProjection({ rootDir, postMerge: true }); assert.equal(pass.ok, true, JSON.stringify(pass.warnings));
    writeTask(rootDir, "task-authored", relation({ source: "task/task-authored", target: "decision/dec_KNOWN/CH404", type: "implements" })); const fail = checkTaskProjection({ rootDir, postMerge: true }); assert.equal(fail.ok, false); assert.equal(fail.warnings.some(({ code }) => code === "relation_endpoint_unknown"), true); }); });

test("GUI graph reads task and relation truth from one read-only L2 database", () => { withTempStore((rootDir) => { const projectionPath = path.join(rootDir, ".harness/cache/projections.sqlite"); seedRelationProjection(projectionPath); const before = readFileSync(projectionPath), graph = readRelationGraphProjection({ rootDir }); assert.deepEqual(graph.edges.map(({ relationId }) => relationId), ["rel_positive"]); assert.deepEqual(graph.taskRows.map(({ taskId }) => taskId), ["task-positive"]); assert.equal(graph.facts[0]?.schema, "task-fact-row/v1"); assert.deepEqual(readFileSync(projectionPath), before, "read path must not rebuild or mutate canonical L2"); }); });

test("GUI graph distinguishes unavailable truth from an empty relation set without creating a cache", () => { withTempStore((rootDir) => { const projectionPath = path.join(rootDir, ".harness/cache/projections.sqlite"), graph = readRelationGraphProjection({ rootDir }); assert.deepEqual(graph.edges, []); assert.equal(graph.warnings.some(({ code, severity }) => code === "relation_truth_unavailable" && severity === "hard-fail"), true); assert.equal(existsSync(projectionPath), false); }); });

test("post-merge continues to consume event-backed Decision/Fact truth", () => { withTempStore((rootDir) => { const fixture = projectionFixture(rootDir); applyDecision(fixture, proposal(1, "dec_GRAPH")); applyFact(fixture, fact(2)); const edge = relation({ source: "decision/dec_GRAPH/C1", target: "fact/task-evidence/F-DEADBEEF", type: "evidenced-by" }); applyDecision(fixture, claim(3, "dec_GRAPH")); applyDecision(fixture, related(4, "dec_GRAPH", edge)); assert.equal(checkTaskProjection({ rootDir, postMerge: true }).ok, true); }); });

test("Decision readiness is commit-bound and ignores uncommitted worktree guesses", () => { withTempStore((rootDir) => { git(rootDir, "init"); git(rootDir, "config", "user.name", "Fixture"); git(rootDir, "config", "user.email", "fixture@example.test"); mkdirSync(path.join(rootDir, "packages/kernel"), { recursive: true }); writeFileSync(path.join(rootDir, "packages/kernel/index.ts"), "export const ready = true;\n"); git(rootDir, "add", "."); git(rootDir, "commit", "-m", "base", { GIT_AUTHOR_DATE: "2026-08-01T00:00:00Z", GIT_COMMITTER_DATE: "2026-08-01T00:00:00Z" }); const base = git(rootDir, "rev-parse", "HEAD"), decision = { decisionId: "dec_READY", proposedAt: "2026-08-02T00:00:00.000Z", appliesTo: { modules: ["kernel"], productLines: [] } };
  const source = testReadinessSource(); let readiness = projectDecisionReadiness({ rootDir, commitSha: base, decisions: [decision] }, source)[0]!; assert.equal(readiness.appliesToDrift.state, "clear"); assert.equal(readiness.conflictMarker.state, "clear"); writeFileSync(path.join(rootDir, "packages/kernel/index.ts"), "<<<<<<< local\n=======\n>>>>>>> remote\n"); readiness = projectDecisionReadiness({ rootDir, commitSha: base, decisions: [decision] }, source)[0]!; assert.equal(readiness.conflictMarker.state, "clear", "uncommitted worktree markers are not canonical truth");
  git(rootDir, "add", "."); git(rootDir, "commit", "-m", "canonical conflict", { GIT_AUTHOR_DATE: "2026-08-03T00:00:00Z", GIT_COMMITTER_DATE: "2026-08-03T00:00:00Z" }); const head = git(rootDir, "rev-parse", "HEAD"); readiness = projectDecisionReadiness({ rootDir, commitSha: head, decisions: [decision] }, source)[0]!; assert.equal(readiness.appliesToDrift.state, "drift"); assert.deepEqual(readiness.appliesToDrift.paths, ["packages/kernel/index.ts"]); assert.equal(readiness.conflictMarker.state, "conflict"); assert.deepEqual(readiness.conflictMarker.paths, ["packages/kernel/index.ts"]); const unknown = projectDecisionReadiness({ rootDir, commitSha: head, decisions: [{ ...decision, appliesTo: { modules: ["missing-module"], productLines: [] } }] }, source)[0]!; assert.equal(unknown.appliesToDrift.state, "unknown"); assert.equal(unknown.conflictMarker.state, "unknown"); }); });

test("real post-merge cycle check includes canonical Decision edges and task-authored edges", () => { withTempStore((rootDir) => { const fixture = projectionFixture(rootDir), projection = fixture.projection, created = taskCreated(1, "task-cycle"); projection.apply(created, taskLifecycleWritePlan(created)); applyDecision(fixture, proposal(2, "dec_CYCLE")); const derives = relation({ source: "decision/dec_CYCLE", target: "task/task-cycle", type: "derives" }); applyDecision(fixture, related(3, "dec_CYCLE", derives)); writeTask(rootDir, "task-cycle", relation({ source: "task/task-cycle", target: "decision/dec_CYCLE", type: "implements" })); const result = checkTaskProjection({ rootDir, postMerge: true }); assert.equal(result.ok, false); assert.equal(result.warnings.some(({ code }) => code === "relation_cycle_detected"), true); }); });

test("Decision projection requires exact plan, content hash, render, consent pin, and document base", () => { withTempStore((rootDir) => { const fixture = projectionFixture(rootDir), draft = proposal(1, "dec_EXACT"), compiled = compileDecisionWrite({ event: draft, currentDecision: null, currentRelations: [], currentDocument: null }), forgedSha = "0".repeat(64), forged = { ...compiled.event, payload: { ...compiled.event.payload, decisionDocumentClaim: { ...compiled.event.payload.decisionDocumentClaim, sha256: forgedSha } } }; fixture.blobs.set(forgedSha, Buffer.from(compiled.body)); assert.throws(() => fixture.projection.apply(compiled.event), /write plan/u); assert.throws(() => fixture.projection.apply(forged, decisionWritePlan(forged)), /projection mismatch/u); assert.equal(fixture.projection.readDecision("dec_EXACT").decision, null);
  applyDecision(fixture, draft); const next = compileCurrent(fixture, accepted(2, "dec_EXACT")), tampered = { ...next.event, payload: { ...next.event.payload, judgmentConsent: { ...next.event.payload.judgmentConsent, machineDigest: `sha256:${"0".repeat(64)}` as const } } }, stale = { ...next.event, payload: { ...next.event.payload, baseDocumentSha256: "0".repeat(64) } }; fixture.blobs.set(next.blobs[0].sha256, Buffer.from(next.body)); assert.throws(() => fixture.projection.apply(tampered, decisionWritePlan(tampered)), /machine content cut/u); assert.throws(() => fixture.projection.apply(stale, decisionWritePlan(stale)), /base.*mismatch/u); assert.equal(fixture.projection.readDecision("dec_EXACT").decision?.state, "proposed"); }); });

function proposal(revision: number, decisionId: string): DecisionEventDraftV1 { return { schema: "decision-event/v1", eventId: `event-${revision}`, workspaceRevision: revision, opId: `op-${revision}`, decisionId, type: "decision_proposed", actor, source: "local", occurredAt: "2026-08-13T00:00:00.000Z", payload: { title: "Canonical Decision", question: "Is this event-backed?", riskTier: "medium", urgency: "medium", vertical: "test", preset: "default", appliesTo: { modules: ["kernel"], productLines: [] }, decisionClass: "ordinary", chosen: [{ id: "CH1", text: "Use events" }], rejected: [{ id: "RJ1", text: "Use files", whyNot: "Files are not canonical." }], body: "\n# Canonical Decision\n", claims: [], fulfillments: [], relations: [] } }; }
function claim(revision: number, decisionId: string): DecisionEventDraftV1 { return { schema: "decision-event/v1", eventId: `event-${revision}`, workspaceRevision: revision, opId: `op-${revision}`, decisionId, type: "decision_claim_declared", actor, source: "local", occurredAt: "2026-08-13T00:00:00.000Z", payload: { claimId: "C1", text: "The relation truth is shared.", loadBearing: true } }; }
function accepted(revision: number, decisionId: string): DecisionEventDraftV1 { return { schema: "decision-event/v1", eventId: `event-${revision}`, workspaceRevision: revision, opId: `op-${revision}`, decisionId, type: "decision_accepted", actor: { principal: { personId: "arbiter" }, executor: null }, source: "local", occurredAt: "2026-08-13T00:00:01.000Z", payload: { rationale: "Independent approval.", judgmentOnlyRationale: "Explicit judgment-only approval." } }; }
function related(revision: number, decisionId: string, record: EntityRelationRecord): DecisionEventDraftV1 { return { schema: "decision-event/v1", eventId: `event-${revision}`, workspaceRevision: revision, opId: `op-${revision}`, decisionId, type: "decision_related", actor, source: "local", occurredAt: "2026-08-13T00:00:00.000Z", payload: { relation: record } }; }
function fact(revision: number): FactEventDraftV1 { return { schema: "fact-event/v1", eventId: `event-${revision}`, workspaceRevision: revision, opId: `op-${revision}`, taskId: "task-evidence", factId: "F-DEADBEEF", type: "fact_recorded", actor, source: "local", occurredAt: "2026-08-13T00:00:00.000Z", payload: { statement: "Event-backed evidence", evidenceSource: "test", observedAt: "2026-08-13T00:00:00.000Z", confidence: "high", memoryClass: "semantic", memoryTags: [], provenance: [{ runtime: "human", sessionId: "test", boundAt: "2026-08-13T00:00:00.000Z" }] } }; }
function taskCreated(revision: number, taskId: string): TaskEventV1 { return { schema: "task-event/v1", eventId: `event-${revision}`, workspaceRevision: revision, opId: `op-${revision}`, taskId, type: "task_created", actor, source: "local", occurredAt: "2026-08-13T00:00:00.000Z", payload: { task: { schema: "task/v1", taskId, title: "Cycle task", taskClass: "standard", status: "planned", graph: REPLAY_TASK_GRAPH, currentNode: "implementation", iteration: 0, createdBy: actor, completionGateIds: [], presetSnapshotDigest: null } } }; }
function relation(input: Pick<EntityRelationRecord, "source" | "target" | "type">): EntityRelationRecord { const identity = { ...input, direction: "directed" as const }; return { relation_id: deriveRelationId(identity), ...identity, strength: "strong", origin: "declared", rationale: "Production entry fixture.", state: "active" }; }
function projectionFixture(rootDir: string) { const blobs = new Map<string, Uint8Array>(), eventStore = { readHead: () => null, readBatch: () => ({ sourceRevision: 0, events: [], cursor: null, done: true, accessedItems: 0 }), readContentBlob: (sha256: string) => blobs.get(sha256) ?? null }; return { blobs, projection: makeTaskProjection({ rootDir, eventStore }) }; }
function compileCurrent(fixture: ReturnType<typeof projectionFixture>, event: DecisionEventDraftV1) { const { projection } = fixture, current = projection.readDecision(event.decisionId).decision, path = `decisions/decision-${event.decisionId}/decision.md`, document = projection.readDocument(path).document, relations = projection.readDecisionGraph().edges.filter((edge) => edge.ownerRef === `decision/${event.decisionId}`).map((edge) => ({ relation_id: edge.relationId, source: edge.sourceRef, target: edge.targetRef, type: edge.relationType, strength: edge.strength, direction: edge.direction, origin: edge.origin, rationale: edge.rationale, state: edge.state })); return compileDecisionWrite({ event, currentDecision: current, currentRelations: relations, currentDocument: document }); }
function applyDecision(fixture: ReturnType<typeof projectionFixture>, event: DecisionEventDraftV1): void { const compiled = compileCurrent(fixture, event); fixture.blobs.set(compiled.blobs[0].sha256, Buffer.from(compiled.body)); fixture.projection.apply(compiled.event, compiled.plan); }
function applyFact(fixture: ReturnType<typeof projectionFixture>, event: FactEventDraftV1): void { const compiled = compileFactWrite({ event, packagePath: `tasks/${event.taskId}-evidence`, currentFacts: fixture.projection.searchFacts({ taskId: event.taskId }).facts }); fixture.blobs.set(compiled.blobs[0].sha256, Buffer.from(compiled.body)); fixture.projection.apply(compiled.event, compiled.plan); }
function writeTask(rootDir: string, taskId: string, record: EntityRelationRecord): void { const taskRoot = path.join(rootDir, "harness/tasks", taskId); mkdirSync(taskRoot, { recursive: true }); writeFileSync(path.join(taskRoot, "INDEX.md"), ["---", "schema: task-package/v2", `task_id: ${taskId}`, `title: ${taskId}`, "lifecycle:", "  engine: local", "  status: active", "packageDisposition: active", "vertical: default", "preset: default", "relations:", formatRelationFlowRecord(record), "---", "", `# ${taskId}`, ""].join("\n")); }
function seedRelationProjection(projectionPath: string): void { mkdirSync(path.dirname(projectionPath), { recursive: true }); const db = new DatabaseSync(projectionPath); try { db.exec(`
  CREATE TABLE task_projection (task_id TEXT PRIMARY KEY,title TEXT NOT NULL,parent_task_id TEXT,canonical_status TEXT NOT NULL,coordination_status TEXT NOT NULL,raw_status TEXT NOT NULL,package_disposition TEXT NOT NULL,closeout_readiness TEXT NOT NULL,lifecycle_engine TEXT NOT NULL,freshness TEXT NOT NULL,updated_at TEXT NOT NULL,source TEXT NOT NULL,source_path TEXT NOT NULL,work_kind TEXT,risk_tier TEXT,urgency TEXT,vertical TEXT,preset TEXT,profile TEXT,module_key TEXT,module_title TEXT,has_lesson_candidates INTEGER NOT NULL);
  CREATE TABLE relation_edges (relation_id TEXT PRIMARY KEY,source_ref TEXT NOT NULL,target_ref TEXT NOT NULL,relation_type TEXT NOT NULL,direction TEXT NOT NULL,strength TEXT NOT NULL,origin TEXT NOT NULL,state TEXT NOT NULL,rationale TEXT NOT NULL,owner_ref TEXT NOT NULL,source_path TEXT NOT NULL,record_index INTEGER NOT NULL);
  CREATE TABLE relation_coverage (claim_ref TEXT PRIMARY KEY,decision_ref TEXT NOT NULL,status TEXT NOT NULL,fulfillment TEXT NOT NULL,covering_fact_ref TEXT,refuting_fact_refs_json TEXT,relation_path_json TEXT NOT NULL);
  CREATE TABLE task_fact_anchors (fact_ref TEXT PRIMARY KEY,task_id TEXT NOT NULL,fact_id TEXT NOT NULL,source_path TEXT NOT NULL);
  CREATE TABLE task_fact_projection (fact_ref TEXT PRIMARY KEY,task_id TEXT NOT NULL,fact_id TEXT NOT NULL,schema_name TEXT NOT NULL,statement TEXT NOT NULL,source TEXT NOT NULL,observed_at TEXT NOT NULL,confidence TEXT NOT NULL,memory_class TEXT NOT NULL,memory_tags_json TEXT NOT NULL,provenance_json TEXT NOT NULL);
  INSERT INTO task_projection VALUES ('task-positive','Positive',NULL,'active','open','active','active','not_ready','kernel/task-lifecycle/v1','fresh','2026-08-14T00:00:00.000Z','local-document','harness/tasks/task-positive/INDEX.md',NULL,'medium','medium','software/coding','standard-task',NULL,'kernel','Kernel',0);
  INSERT INTO relation_edges VALUES ('rel_positive','decision/dec_01KXA7811SVVT8P66HNDFZQ7DF/CH1','task/task-positive','derives','directed','strong','declared','active','positive','decision/dec_01KXA7811SVVT8P66HNDFZQ7DF','harness/decisions/decision-dec_01KXA7811SVVT8P66HNDFZQ7DF/decision.md',0);
  INSERT INTO relation_coverage VALUES ('decision/dec_01KXA7811SVVT8P66HNDFZQ7DF/CH1','decision/dec_01KXA7811SVVT8P66HNDFZQ7DF','covered','standing-policy',NULL,'[]','["rel_positive"]');
  INSERT INTO task_fact_anchors VALUES ('fact/task-positive/F-POSITIVE','task-positive','F-POSITIVE','harness/tasks/task-positive/facts.md');
  INSERT INTO task_fact_projection VALUES ('fact/task-positive/F-POSITIVE','task-positive','F-POSITIVE','task-fact-row/v1','Observed','fixture','2026-08-14T00:00:00.000Z','high','semantic','[]','[]');`); } finally { db.close(); } }
function git(rootDir: string, ...argsAndMaybeEnv: Array<string | Record<string, string>>): string { const maybeEnv = argsAndMaybeEnv.at(-1), env = typeof maybeEnv === "object" ? maybeEnv : {}, args = argsAndMaybeEnv.filter((value): value is string => typeof value === "string"); return execFileSync("git", args, { cwd: rootDir, encoding: "utf8", env: { ...process.env, ...env } }).trim(); }
function testReadinessSource() { return { run: (rootDir: string, args: readonly string[], allowNoMatch = false) => { try { return { ok: true, stdout: git(rootDir, ...args) }; } catch (error) { const status = typeof error === "object" && error && "status" in error ? Number(error.status) : null; return { ok: allowNoMatch && status === 1, stdout: "" }; } } }; }
