// harness-test-tier: integration
import assert from "node:assert/strict";
import { spawnSync } from "node:child_process";
import { existsSync, mkdirSync, mkdtempSync, readFileSync, readdirSync, realpathSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import path from "node:path";
import test from "node:test";
import { safePath } from "../../daemon/src/protocol/daemon-protocol.contract.ts";
import { runCommandThroughDaemon } from "../src/daemon/client.ts";

const cli = path.resolve("packages/cli/src/index.ts");

test("real CLI runs, archives task-bound dispatches, resumes, waits through status, streams, and cancels idempotently", async () => {
  const parent = mkdtempSync(path.join(tmpdir(), "ha-runtime-cli-")), root = path.join(parent, "repo"), userRoot = path.join(parent, "user"), binRoot = path.join(parent, "bin"), promptFile = path.join(root, "prompt.txt"), tracker = path.join(root, ".batch-tracker"), version = "0.0.0-runtime-cli-fixture";
  mkdirSync(root, { recursive: true }); mkdirSync(binRoot, { recursive: true }); writeProvider(path.join(binRoot, "codex"), version);
  const env = { ...process.env, HOME: path.join(parent, "home"), PATH: `${binRoot}${path.delimiter}${process.env.PATH ?? ""}`, HARNESS_DAEMON_USER_ROOT: userRoot, HARNESS_DAEMON_ID: "runtime-cli-test", HARNESS_ACTOR: "agent:runtime-cli-test" };
  try {
    assert.equal(run(root, env, ["daemon", "start", "--service"]).ok, true); run(root, env, ["init", "--repo-id", "runtime-cli", "--person-id", "owner", "--display-name", "Owner"]);
    const identities = [{ id: "fable", name: "Fable", instructions: "Lead precisely.", runtime_type: "codex" }, { id: "terra", name: "Terra", instructions: "Review precisely.", runtime_type: "codex" }, { id: "outsider", name: "Outsider", instructions: "Work outside the squad.", runtime_type: "codex" }, { id: "opencode-worker", name: "OpenCode Worker", instructions: "Use OpenCode.", runtime_type: "opencode" }], squadSource = path.join(parent, "core-squad");
    for (const identity of identities) { const agentSource = path.join(parent, identity.id); writeIdentity(agentSource, { id: identity.id, title: identity.name, kind: "agent", agent: { ...identity, skills: ["review"], prompts: ["prompt://review"], preset: "standard-task" } }); run(root, env, ["agent", "install", "--source", agentSource]); }
    writeIdentity(squadSource, { id: "core-squad", title: "Core Squad", kind: "squad", squad: { id: "core-squad", name: "Core Squad", leader: "fable", workers: ["terra", "opencode-worker"], roster: "# Core Squad\n\nFable delegates to Terra and OpenCode Worker." } }); run(root, env, ["squad", "install", "--source", squadSource]); const agents = JSON.parse(String(run(root, env, ["agent", "list"]).evidence)) as { agents: Array<{ id: string }> }, squads = JSON.parse(String(run(root, env, ["squad", "list"]).evidence)) as { squads: Array<{ id: string }> }; assert.deepEqual(agents.agents.map(({ id }) => id), ["fable", "opencode-worker", "outsider", "terra"]); assert.deepEqual(squads.squads.map(({ id }) => id), ["core-squad"]);
    writeIdentity(squadSource, { id: "core-squad", title: "Core Squad", kind: "squad", squad: { id: "core-squad", name: "Core Squad", leader: "fable", workers: ["terra", "opencode-worker"], roster: "# Core Squad\n\nFable delegates; humans edited this roster." } }); run(root, env, ["squad", "install", "--source", squadSource]); const squad = JSON.parse(String(run(root, env, ["squad", "inspect", "core-squad"]).evidence)) as { squad: { roster: string } }; assert.match(squad.squad.roster, /humans edited/u);
    const taskId = "task-runtime-archive", executionId = "exec-runtime-archive", created = run(root, env, ["task", "create", "--id", taskId, "--admin", "--title", "Runtime archive"]), packagePath = String(created.packagePath), artifactRoot = path.join(root, "harness", packagePath, "artifacts");
    const inventory = run(root, env, ["runtime", "instance", "list"]), installation = (inventory.installations as Array<Record<string, unknown>>).find((row) => row.kindId === "codex" && row.version === `codex ${version}`); assert.ok(installation, JSON.stringify(inventory));
    run(root, env, ["runtime", "instance", "create", "--id", "cli-worker", "--name", "CLI Worker", "--kind", "codex", "--installation", String(installation.installationId), "--provider", "openai", "--model", "runtime-test-model", "--auth", "subscription"]);
    writeFileSync(promptFile, "file prompt"); const fromFile = run(root, env, ["runtime", "run", "cli-worker", "--prompt-file", "prompt.txt", "--no-stream"]); assert.equal((fromFile.result as Record<string, unknown>).text, "final:file prompt");
    for (const directory of ["missions", "dispatches", "reports"]) assert.equal(existsSync(path.join(artifactRoot, directory)), false, `${directory} must not exist without --task`);
    const resumed = run(root, env, ["runtime", "run", "cli-worker", "--prompt", "second turn", "--resume", "provider-cli-session", "--no-stream"]); assert.equal((resumed.result as Record<string, unknown>).text, "resumed:provider-cli-session:second turn"); assert.equal((resumed.session as Record<string, unknown>).providerSessionId, "provider-cli-session");
    const streamed = spawnSync(process.execPath, [cli, "--root", root, "runtime", "run", "cli-worker", "--prompt", "stream prompt"], { encoding: "utf8", env }); assert.equal(streamed.status, 0, streamed.stderr); assert.equal(streamed.stdout.trim(), "final:stream prompt");
    run(root, env, ["task", "start", taskId, "--execution-id", executionId]); const assembledPrompt = "# Agent Identity: Terra (terra)\n\nReview precisely.\n\n# Mission\n\nbound prompt", bound = run(root, env, ["runtime", "run", "cli-worker", "--agent", "fable", "--to", "terra", "--prompt", "bound prompt", "--task", taskId, "--no-stream"]), boundSpawn = bound.spawn as Record<string, unknown>, boundDispatchId = String(boundSpawn.dispatchId), boundDispatch = JSON.parse(readFileSync(path.join(artifactRoot, "dispatches", `${boundDispatchId}.json`), "utf8")) as Record<string, unknown>;
    assert.equal(readFileSync(path.join(artifactRoot, "missions", `${boundDispatchId}.md`), "utf8"), assembledPrompt); assert.equal(readFileSync(path.join(artifactRoot, "reports", `${boundDispatchId}.md`), "utf8"), `final:${assembledPrompt}`); assert.deepEqual(boundDispatch, { schema: "runtime-dispatch/v1", dispatchId: boundDispatchId, taskId, executionId, agentId: "terra", agentName: "Terra", delegatedByAgentId: "fable", delegatedByAgentName: "Fable", squadId: "core-squad", instanceId: "cli-worker", model: "runtime-test-model", reasoningEffort: null, cwd: realpathSync(root), missionRef: `${packagePath}/artifacts/missions/${boundDispatchId}.md`, runtimeSessionId: bound.runtimeSessionId, providerSessionId: "provider-cli-session", startedAt: boundDispatch.startedAt, endedAt: boundDispatch.endedAt, outcome: "succeeded", exitCode: 0, resultRef: (bound.result as Record<string, unknown>).ref, eventStreamRef: `file:.harness/runtime/dispatches/${boundDispatchId}.jsonl` }); assert.match(String(boundDispatch.startedAt), /^\d{4}-\d{2}-\d{2}T/u); assert.match(String(boundDispatch.endedAt), /^\d{4}-\d{2}-\d{2}T/u); assert.doesNotMatch(JSON.stringify(boundDispatch), /(?:api.?key|credential|environment|token)/iu); assert.equal(existsSync(path.join(root, ".harness", "runtime", "dispatches", `${boundDispatchId}.jsonl`)), true);
    const dispatchRow = (run(root, env, ["task", "dispatches", taskId]).dispatches as Array<Record<string, unknown>>).find((row) => row.dispatchId === boundDispatchId); assert.deepEqual(dispatchRow && { agentId: dispatchRow.agentId, delegatedByAgentId: dispatchRow.delegatedByAgentId, squadId: dispatchRow.squadId }, { agentId: "terra", delegatedByAgentId: "fable", squadId: "core-squad" });
    const outsider = runMaybe(root, env, ["runtime", "run", "cli-worker", "--agent", "fable", "--to", "outsider", "--prompt", "reject outsider", "--task", taskId, "--no-stream"]); assert.equal(outsider.status, 1); assert.equal(outsider.receipt.code, "squad_member_not_found");
    const mismatch = runMaybe(root, env, ["runtime", "run", "cli-worker", "--agent", "fable", "--to", "opencode-worker", "--prompt", "reject mismatch", "--task", taskId, "--no-stream"]); assert.equal(mismatch.status, 1); assert.equal(mismatch.receipt.code, "agent_runtime_type_mismatch");
    const existingSource = path.join(root, "existing-mission.txt"); writeFileSync(existingSource, "existing mission"); run(root, env, ["task", "artifact", "add", taskId, "--source", "existing-mission.txt", "--destination", "existing-mission.md"]); const existingPrompt = path.join("harness", packagePath, "artifacts", "existing-mission.md"), reused = run(root, env, ["runtime", "run", "cli-worker", "--prompt-file", existingPrompt, "--task", taskId, "--no-stream"]), reusedDispatchId = String((reused.spawn as Record<string, unknown>).dispatchId), reusedDispatch = JSON.parse(readFileSync(path.join(artifactRoot, "dispatches", `${reusedDispatchId}.json`), "utf8")) as Record<string, unknown>;
    assert.equal(reusedDispatch.missionRef, `${packagePath}/artifacts/existing-mission.md`); assert.deepEqual(readdirSync(path.join(artifactRoot, "missions")), [`${boundDispatchId}.md`]); assert.equal(readFileSync(path.join(artifactRoot, "reports", `${reusedDispatchId}.md`), "utf8"), "final:existing mission");
    const listed = run(root, env, ["runtime", "status"]), sessions = listed.sessions as Array<Record<string, unknown>>; assert.equal(sessions.length, 5); assert.match(streamed.stderr, /\[message\] live:stream prompt/u, JSON.stringify(sessions)); const detail = run(root, env, ["runtime", "status", String(resumed.runtimeSessionId)]); assert.equal((detail.result as Record<string, unknown>).text, "resumed:provider-cli-session:second turn"); const waited = run(root, env, ["runtime", "status", String(resumed.runtimeSessionId), "--wait", "--no-stream"]); assert.equal(waited.command, "runtime-status"); assert.equal(waited.summary, "resumed:provider-cli-session:second turn");
    writeFileSync(path.join(root, "batch-prompt.txt"), "batch hold from file"); writeFileSync(path.join(root, "batch.json"), JSON.stringify({ schema: "runtime-batch/v1", maxConcurrency: 2, dispatches: [{ instance: "cli-worker", agent: "fable", to: "missing-agent", prompt: "must reject", task: taskId }, { instance: "cli-worker", agent: "fable", to: "terra", model: "runtime-test-model", effort: "high", prompt: "batch hold one", task: taskId }, { instance: "cli-worker", agent: "fable", to: "terra", prompt: "batch hold two", cwd: ".", task: taskId }, { instance: "cli-worker", agent: "fable", to: "terra", "prompt-file": "batch-prompt.txt", task: taskId }] }, null, 2));
    const batch = runMaybe(root, env, ["runtime", "batch", "batch.json"]); assert.equal(batch.status, 1, `${batch.stderr}\n${JSON.stringify(batch.receipt)}`); assert.equal(batch.receipt.command, "runtime-batch"); assert.equal(batch.receipt.outcome, "partial_failure"); const batchRows = batch.receipt.dispatches as Array<Record<string, unknown>>; assert.equal(batchRows.length, 4); assert.deepEqual(batchRows.map((row) => row.status), ["rejected", "succeeded", "succeeded", "succeeded"], JSON.stringify(batch.receipt)); assert.equal(batchRows[0]?.code, "squad_member_not_found"); assert.match(String(batchRows[0]?.reason), /missing-agent/u); assert.equal(batchRows.slice(1).every((row) => typeof row.dispatchId === "string" && typeof row.runtimeSessionId === "string"), true);
    const batchDispatchIds = new Set(batchRows.slice(1).map((row) => String(row.dispatchId))), batchDispatches = (run(root, env, ["task", "dispatches", taskId]).dispatches as Array<Record<string, unknown>>).filter((row) => batchDispatchIds.has(String(row.dispatchId))); assert.equal(batchDispatches.length, 3); assert.equal(batchDispatches.every((row) => row.agentId === "terra" && row.delegatedByAgentId === "fable" && row.squadId === "core-squad"), true, JSON.stringify(batchDispatches)); assert.equal((JSON.parse(readFileSync(path.join(artifactRoot, "dispatches", `${String(batchRows[1]?.dispatchId)}.json`), "utf8")) as Record<string, unknown>).reasoningEffort, "high");
    const events = readFileSync(tracker, "utf8").trim().split("\n"); let active = 0, peak = 0; for (const event of events) { active += event === "start" ? 1 : -1; peak = Math.max(peak, active); } assert.equal(events.filter((event) => event === "start").length, 3); assert.equal(events.filter((event) => event === "end").length, 3); assert.ok(peak <= 2, `batch exceeded declared concurrency: ${events.join(",")}`);
    const detached = run(root, env, ["runtime", "run", "cli-worker", "--prompt", "hold", "--task", taskId, "--detach"]), detachedDispatchId = String(detached.dispatchId), detachedSessionId = String(detached.runtimeSessionId), running = run(root, env, ["task", "dispatches", taskId]); assert.equal(detached.outcome, "running"); assert.equal((running.dispatches as Array<Record<string, unknown>>).find((row) => row.dispatchId === detachedDispatchId)?.status, "running");
    assert.equal(run(root, env, ["runtime", "cancel", detachedSessionId]).detail, "cancelled"); assert.equal(run(root, env, ["runtime", "cancel", detachedSessionId]).detail, "already-exited"); const cancelled = await eventually(() => run(root, env, ["task", "dispatches", taskId])), cancelledRow = (cancelled.dispatches as Array<Record<string, unknown>>).find((row) => row.dispatchId === detachedDispatchId)!; assert.equal(cancelledRow.status, "cancelled"); assert.equal((JSON.parse(readFileSync(path.join(artifactRoot, "dispatches", `${detachedDispatchId}.json`), "utf8")) as Record<string, unknown>).outcome, "cancelled"); assert.equal(readFileSync(path.join(artifactRoot, "reports", `${detachedDispatchId}.md`), "utf8"), "live:hold"); const resumedDispatch = run(root, env, ["runtime", "run", "--resume-dispatch", detachedDispatchId, "--prompt", "follow up", "--no-stream"]); assert.equal((resumedDispatch.result as Record<string, unknown>).text, "resumed:provider-cli-session:follow up");
    // #1572: with HARNESS_ACTOR declared, the daemon request log is the server-side proof that executor
    // attribution still arrives — inside the action for repo.task.run writes (task start) and at payload
    // level for preset methods (task create) — while nothing is ever rejected for an undeclared executor.
    const requests = readFileSync(path.join(root, ".harness", "requests", "requests.jsonl"), "utf8").trim().split("\n").map((line) => JSON.parse(line) as Record<string, unknown>);
    assert.deepEqual(requests.find((entry) => entry.method === "repo.task.run" && entry.command === "task-start")?.executor, { kind: "agent", id: "runtime-cli-test" });
    assert.deepEqual(requests.find((entry) => entry.method === "repo.task.create")?.executor, { kind: "agent", id: "runtime-cli-test" });
    assert.equal(requests.some((entry) => entry.code === "invalid_request"), false, JSON.stringify(requests.filter((entry) => entry.code === "invalid_request")));
    // A contracted read method with no CLI argv (repo.tasks.documents.list declares a closed payload
    // without executor) stands in for "the next new command": with an explicit HARNESS_ACTOR, injection
    // must follow the daemon-declared surface, so the real daemon accepts the request instead of
    // rejecting an undeclared executor.
    const probe = await runCommandThroughDaemon({ rootDir: safePath(root), repoId: "runtime-cli", json: true, method: "repo.tasks.documents.list", action: { kind: "task-documents-list", taskId } }, undefined, { env: { ...env, HARNESS_ACTOR: "agent:injection-probe" } });
    assert.equal(probe.ok, true, JSON.stringify(probe));
  } finally { runMaybe(root, env, ["daemon", "stop"]); rmSync(parent, { recursive: true, force: true }); }
});

async function eventually<T>(read: () => T): Promise<T> { let last: T | undefined; for (let attempt = 0; attempt < 100; attempt += 1) { last = read(); const rows = (last as Record<string, unknown>).dispatches; if (Array.isArray(rows) && rows.some((row) => (row as Record<string, unknown>).status === "cancelled")) return last; await new Promise((resolve) => setTimeout(resolve, 20)); } throw new Error(`dispatch did not settle: ${JSON.stringify(last)}`); }
function run(root: string, env: NodeJS.ProcessEnv, args: readonly string[]): Record<string, unknown> { const result = runMaybe(root, env, args); assert.equal(result.status, 0, `${result.stderr}\n${JSON.stringify(result.receipt)}`); return result.receipt; }
function runMaybe(root: string, env: NodeJS.ProcessEnv, args: readonly string[]): { readonly status: number | null; readonly receipt: Record<string, unknown>; readonly stderr: string } { const result = spawnSync(process.execPath, [cli, "--root", root, "--json", ...args], { encoding: "utf8", env }); return { status: result.status, receipt: result.stdout.trim() ? JSON.parse(result.stdout) as Record<string, unknown> : {}, stderr: result.stderr }; }
function writeIdentity(target: string, identity: Record<string, unknown>): void { const kind = String(identity.kind) as "agent" | "squad", declaration = kind === "agent" ? identity.agent : identity.squad; mkdirSync(target, { recursive: true }); writeFileSync(path.join(target, kind === "agent" ? "agent.json" : "squad.json"), `${JSON.stringify({ schema: `${kind}-declaration/v1`, ...declaration }, null, 2)}\n`); }
function writeProvider(target: string, version: string): void { writeFileSync(target, `#!${process.execPath}\nconst fs = require("node:fs");\nconst args = process.argv.slice(2);\nif (args[0] === "--version") { console.log("codex ${version}"); process.exit(0); }\nif (args[0] === "login" && args[1] === "status") process.exit(0);\nconst prompt = fs.readFileSync(0, "utf8");\nconst resumed = args[0] === "exec" && args[1] === "resume";\nconst session = resumed ? args.at(-2) : "provider-cli-session";\nconst batch = prompt.includes("batch hold"), mark = (event) => { if (batch) fs.appendFileSync(".batch-tracker", event + "\\n"); };\nconst emit = () => { mark("start"); console.log(JSON.stringify({ type: "thread.started", thread_id: session })); console.log(JSON.stringify({ type: "item.completed", item: { id: "live", type: "agent_message", text: "live:" + prompt } })); if (prompt === "hold") setInterval(() => {}, 1000); else { console.log(JSON.stringify({ type: "item.completed", item: { id: "final", type: "agent_message", text: resumed ? "resumed:" + session + ":" + prompt : "final:" + prompt } })); console.log(JSON.stringify({ type: "turn.completed", usage: { input_tokens: 1, output_tokens: 1 } })); mark("end"); } };\nif (prompt === "stream prompt") setTimeout(emit, 3000); else if (batch) setTimeout(emit, 250); else emit();\n`, { mode: 0o755 }); }
