import { daemonGuiStreamFacets, type DaemonGuiStreamPayloadMap } from "@harness-anything/daemon/protocol/daemon-protocol.contract"; import { assertPreloadPayload } from "./allowlist.ts";
let sequence = 0; export type AgentRuntimePreloadStream = (payload: DaemonGuiStreamPayloadMap["repo.agentRuntime.attach"], onValue: (value: unknown) => void) => () => void; export type TerminalPreloadStream = (payload: DaemonGuiStreamPayloadMap["repo.terminal.attach"], onValue: (value: unknown) => void) => () => void;
interface RendererIpc { readonly on: (channel: string, listener: (event: unknown, value: unknown) => void) => void; readonly send: (channel: string, value: unknown) => void; readonly removeListener: (channel: string, listener: (event: unknown, value: unknown) => void) => void }
export function agentRuntimePreloadApi(ipc: RendererIpc): { readonly attachAgentRuntime: AgentRuntimePreloadStream; readonly attachTerminal: TerminalPreloadStream } {
  const result: Record<string, (payload: never, onValue: (value: unknown) => void) => () => void> = {};
  for (const facet of daemonGuiStreamFacets) result[facet.guiBridgeMethod] = ((payload: unknown, onValue: (value: unknown) => void) => { assertPreloadPayload(facet.guiBridgeMethod, payload); if (typeof onValue !== "function") throw new Error("Stream listener is required.");
    const subscriptionId = `renderer-${++sequence}`, frameChannel = `harness:${facet.guiBridgeMethod}:frame:${subscriptionId}`, listener = (_event: unknown, value: unknown) => onValue(value); ipc.on(frameChannel, listener); ipc.send(`harness:${facet.guiBridgeMethod}`, { subscriptionId, payload });
    let detached = false; return () => { if (detached) return; detached = true; ipc.removeListener(frameChannel, listener); ipc.send(`harness:${facet.guiBridgeMethod}:detach`, { subscriptionId }); }; }) as never;
  return result as unknown as { readonly attachAgentRuntime: AgentRuntimePreloadStream; readonly attachTerminal: TerminalPreloadStream }; }
