import type { DaemonGuiRpcReadMethod } from "./daemon-protocol-gui-types.ts";
import { shape } from "./daemon-protocol-gui-types.ts";
import {
  DAEMON_AGENDA_SCHEMA,
  DAEMON_AGENT_ENTITY_CATALOG_SCHEMA,
  DAEMON_AGENT_ENTITY_DETAIL_SCHEMA,
  DAEMON_AGENT_RUNTIME_EVENTS_SCHEMA,
  DAEMON_AGENT_RUNTIME_OVERVIEW_SCHEMA,
  DAEMON_AGENT_RUNTIME_SESSION_SCHEMA,
  DAEMON_AGENT_SKILL_CATALOG_SCHEMA,
  DAEMON_CONTROL_RECEIPT_SCHEMA,
  DAEMON_DECISION_LIST_SCHEMA,
  DAEMON_DOCUMENT_READ_SCHEMA,
  DAEMON_PROTOCOL_ERROR_SCHEMA,
  DAEMON_RELATION_GRAPH_SCHEMA,
  DAEMON_SQUAD_ENTITY_CATALOG_SCHEMA,
  DAEMON_SQUAD_ENTITY_DETAIL_SCHEMA,
  DAEMON_SQUAD_RUN_LIST_SCHEMA,
  DAEMON_SQUAD_RUN_READ_SCHEMA,
  DAEMON_TASK_DISPATCHES_SCHEMA,
  DAEMON_TASK_DOCUMENT_LIST_SCHEMA,
  DAEMON_TASK_SNAPSHOT_LIST_SCHEMA,
  DAEMON_WORKSPACE_SUMMARY_SCHEMA,
  daemonAgendaPayloadShape,
  daemonRelationQueryPayloadShape,
  daemonTaskQueryPayloadShape,
  GUI_CATALOG_PRESET_SCHEMA,
  GUI_CATALOG_SNAPSHOT_SCHEMA,
  GUI_SYSTEM_STATUS_SCHEMA,
  TERMINAL_SESSION_LIST_SCHEMA,
} from "./daemon-protocol-schema-ids.ts";

export const daemonGuiReadMethods = Object.freeze([
  {
    id: "gui.system.read",
    phase: "W5-GUI-S3",
    method: "daemon.gui.system.read",
    requiresRepo: false,
    params: shape({}),
    guiBridgeMethod: "getSystemStatus",
    httpMethod: "GET",
    path: "/api/system",
    inputSchemaId: "gui.empty/v1",
    outputSchemaId: GUI_SYSTEM_STATUS_SCHEMA.id,
    errorSchemaId: DAEMON_PROTOCOL_ERROR_SCHEMA.id,
    serviceMethod: "getSystemStatus",
    auth: "local-session-token",
    commandClass: "repo-read",
  },
  {
    id: "gui.control.receipt",
    phase: "W5-GUI-S3",
    method: "daemon.gui.control.receipt",
    requiresRepo: false,
    params: shape({ payload: shape({ operationId: "string" }) }),
    guiBridgeMethod: "getDaemonControlReceipt",
    httpMethod: "GET",
    path: "/api/system/control/:operationId",
    inputSchemaId: "gui.daemon-control-receipt/v1",
    outputSchemaId: DAEMON_CONTROL_RECEIPT_SCHEMA.id,
    errorSchemaId: DAEMON_PROTOCOL_ERROR_SCHEMA.id,
    serviceMethod: "getDaemonControlReceipt",
    auth: "local-session-token",
    commandClass: "repo-read",
  },
  {
    id: "tasks.list",
    phase: "W2-GUI",
    method: "repo.tasks.list",
    requiresRepo: true,
    params: shape({
      repo: shape({ repoId: "string" }),
      payload: daemonTaskQueryPayloadShape,
    }),
    guiBridgeMethod: "getTasks",
    httpMethod: "GET",
    path: "/api/tasks",
    inputSchemaId: "gui.task-query/v1",
    outputSchemaId: DAEMON_TASK_SNAPSHOT_LIST_SCHEMA.id,
    errorSchemaId: DAEMON_PROTOCOL_ERROR_SCHEMA.id,
    serviceMethod: "listTasks",
    auth: "local-session-token",
    commandClass: "repo-read",
  },
  {
    id: "workspace.summary.read",
    phase: "W2-GUI",
    method: "repo.workspace.summary.read",
    requiresRepo: true,
    params: shape({ repo: shape({ repoId: "string" }) }),
    guiBridgeMethod: "getWorkspaceSummary",
    httpMethod: "GET",
    path: "/api/workspace/summary",
    inputSchemaId: "gui.empty/v1",
    outputSchemaId: DAEMON_WORKSPACE_SUMMARY_SCHEMA.id,
    errorSchemaId: DAEMON_PROTOCOL_ERROR_SCHEMA.id,
    serviceMethod: "readWorkspaceSummary",
    auth: "local-session-token",
    commandClass: "repo-read",
  },
  {
    id: "agenda.read",
    phase: "W3",
    method: "repo.agenda.read",
    requiresRepo: true,
    params: shape({
      repo: shape({ repoId: "string" }),
      payload: daemonAgendaPayloadShape,
    }),
    guiBridgeMethod: "getAgenda",
    httpMethod: "GET",
    path: "/api/agenda",
    inputSchemaId: "gui.agenda-query/v1",
    outputSchemaId: DAEMON_AGENDA_SCHEMA.id,
    errorSchemaId: DAEMON_PROTOCOL_ERROR_SCHEMA.id,
    serviceMethod: "readAgenda",
    auth: "local-session-token",
    commandClass: "repo-read",
  },
  {
    id: "triadic.relationGraph",
    phase: "W2-GUI",
    method: "repo.triadic.relationGraph",
    requiresRepo: true,
    params: shape({
      repo: shape({ repoId: "string" }),
      payload: daemonRelationQueryPayloadShape,
    }),
    guiBridgeMethod: "getRelationGraph",
    httpMethod: "GET",
    path: "/api/triadic/relation-graph",
    inputSchemaId: "gui.relation-query/v1",
    outputSchemaId: DAEMON_RELATION_GRAPH_SCHEMA.id,
    errorSchemaId: DAEMON_PROTOCOL_ERROR_SCHEMA.id,
    serviceMethod: "readRelationGraph",
    auth: "local-session-token",
    commandClass: "repo-read",
  },
  {
    id: "decisions.list",
    phase: "W2-GUI",
    method: "repo.decisions.list",
    requiresRepo: true,
    params: shape({ repo: shape({ repoId: "string" }) }),
    guiBridgeMethod: "getDecisions",
    httpMethod: "GET",
    path: "/api/decisions",
    inputSchemaId: "gui.empty/v1",
    outputSchemaId: DAEMON_DECISION_LIST_SCHEMA.id,
    errorSchemaId: DAEMON_PROTOCOL_ERROR_SCHEMA.id,
    serviceMethod: "listDecisions",
    auth: "local-session-token",
    commandClass: "repo-read",
  },
  {
    id: "tasks.document.read",
    phase: "DocSync-B",
    method: "repo.tasks.document.read",
    requiresRepo: true,
    params: shape({
      repo: shape({ repoId: "string" }),
      payload: shape({ taskId: "string", path: "string" }),
    }),
    guiBridgeMethod: "getTaskDocument",
    httpMethod: "GET",
    path: "/api/tasks/:taskId/documents/:path",
    inputSchemaId: "gui.task-document/v1",
    outputSchemaId: DAEMON_DOCUMENT_READ_SCHEMA.id,
    errorSchemaId: DAEMON_PROTOCOL_ERROR_SCHEMA.id,
    serviceMethod: "readDocument",
    auth: "local-session-token",
    commandClass: "repo-read",
  },
  {
    id: "tasks.documents.list",
    phase: "DocSync-B",
    method: "repo.tasks.documents.list",
    requiresRepo: true,
    params: shape({
      repo: shape({ repoId: "string" }),
      payload: shape({ taskId: "string" }),
    }),
    guiBridgeMethod: "getTaskDocuments",
    httpMethod: "GET",
    path: "/api/tasks/:taskId/documents",
    inputSchemaId: "gui.task-document-list/v1",
    outputSchemaId: DAEMON_TASK_DOCUMENT_LIST_SCHEMA.id,
    errorSchemaId: DAEMON_PROTOCOL_ERROR_SCHEMA.id,
    serviceMethod: "listTaskDocuments",
    auth: "local-session-token",
    commandClass: "repo-read",
  },
  {
    id: "agentRuntime.overview",
    phase: "Runtime-B",
    method: "repo.agentRuntime.overview",
    requiresRepo: true,
    params: shape({
      repo: shape({ repoId: "string" }),
      payload: shape({ taskId: "string?", limit: "number?", cursor: "string?" }),
    }),
    guiBridgeMethod: "getAgentRuntimeOverview",
    httpMethod: "GET",
    path: "/api/agent-runtime",
    inputSchemaId: "gui.agent-runtime-overview/v1",
    outputSchemaId: DAEMON_AGENT_RUNTIME_OVERVIEW_SCHEMA.id,
    errorSchemaId: DAEMON_PROTOCOL_ERROR_SCHEMA.id,
    serviceMethod: "readAgentRuntimeOverview",
    auth: "local-session-token",
    commandClass: "repo-read",
  },
  {
    id: "agentRuntime.sessions.read",
    phase: "Runtime-B",
    method: "repo.agentRuntime.sessions.read",
    requiresRepo: true,
    params: shape({
      repo: shape({ repoId: "string" }),
      payload: shape({ runtimeSessionId: "string?", taskId: "string?", dispatchId: "string?" }),
    }),
    guiBridgeMethod: "getAgentRuntimeSession",
    httpMethod: "GET",
    path: "/api/agent-runtime/sessions/:id",
    inputSchemaId: "gui.agent-runtime-session/v1",
    outputSchemaId: DAEMON_AGENT_RUNTIME_SESSION_SCHEMA.id,
    errorSchemaId: DAEMON_PROTOCOL_ERROR_SCHEMA.id,
    serviceMethod: "readAgentRuntimeSession",
    auth: "local-session-token",
    commandClass: "repo-read",
  },
  {
    id: "agentRuntime.events.read",
    phase: "Runtime-B",
    method: "repo.agentRuntime.events.read",
    requiresRepo: true,
    params: shape({
      repo: shape({ repoId: "string" }),
      payload: shape({ runtimeSessionId: "string", afterCursor: "string" }),
    }),
    guiBridgeMethod: "getAgentRuntimeEvents",
    httpMethod: "GET",
    path: "/api/agent-runtime/sessions/:id/events",
    inputSchemaId: "gui.agent-runtime-events/v1",
    outputSchemaId: DAEMON_AGENT_RUNTIME_EVENTS_SCHEMA.id,
    errorSchemaId: DAEMON_PROTOCOL_ERROR_SCHEMA.id,
    serviceMethod: "readAgentRuntimeEvents",
    auth: "local-session-token",
    commandClass: "repo-read",
  },
  {
    id: "task.dispatches",
    phase: "Runtime-B",
    method: "repo.task.dispatches",
    requiresRepo: true,
    params: shape({
      repo: shape({ repoId: "string" }),
      payload: shape({
        taskId: "string?",
        taskIds: "array?",
        limit: "number?",
        cursor: "string?",
      }),
    }),
    guiBridgeMethod: "getTaskDispatches",
    httpMethod: "GET",
    path: "/api/tasks/:taskId/dispatches",
    inputSchemaId: "gui.task-dispatches/v1",
    outputSchemaId: DAEMON_TASK_DISPATCHES_SCHEMA.id,
    errorSchemaId: DAEMON_PROTOCOL_ERROR_SCHEMA.id,
    serviceMethod: "readTaskDispatches",
    auth: "local-session-token",
    commandClass: "repo-read",
  },
  {
    id: "agent.entities.list",
    phase: "Runtime-B",
    method: "repo.agent.entities.list",
    requiresRepo: true,
    params: shape({ repo: shape({ repoId: "string" }) }),
    guiBridgeMethod: "listAgents",
    httpMethod: "GET",
    path: "/api/agents",
    inputSchemaId: "gui.empty/v1",
    outputSchemaId: DAEMON_AGENT_ENTITY_CATALOG_SCHEMA.id,
    errorSchemaId: DAEMON_PROTOCOL_ERROR_SCHEMA.id,
    serviceMethod: "listAgents",
    auth: "local-session-token",
    commandClass: "repo-read",
  },
  {
    id: "agent.entity.read",
    phase: "Runtime-B",
    method: "repo.agent.entity.read",
    requiresRepo: true,
    params: shape({
      repo: shape({ repoId: "string" }),
      payload: shape({ agentId: "string" }),
    }),
    guiBridgeMethod: "showAgent",
    httpMethod: "GET",
    path: "/api/agents/:agentId",
    inputSchemaId: "gui.agent-entity-read/v1",
    outputSchemaId: DAEMON_AGENT_ENTITY_DETAIL_SCHEMA.id,
    errorSchemaId: DAEMON_PROTOCOL_ERROR_SCHEMA.id,
    serviceMethod: "showAgent",
    auth: "local-session-token",
    commandClass: "repo-read",
  },
  {
    id: "agent.skills.list",
    phase: "Runtime-B",
    method: "repo.agent.skills.list",
    requiresRepo: true,
    params: shape({ repo: shape({ repoId: "string" }) }),
    guiBridgeMethod: "listAgentSkills",
    httpMethod: "GET",
    path: "/api/agent-skills",
    inputSchemaId: "gui.empty/v1",
    outputSchemaId: DAEMON_AGENT_SKILL_CATALOG_SCHEMA.id,
    errorSchemaId: DAEMON_PROTOCOL_ERROR_SCHEMA.id,
    serviceMethod: "listAgentSkills",
    auth: "local-session-token",
    commandClass: "repo-read",
  },
  {
    id: "squad.entities.list",
    phase: "Runtime-B",
    method: "repo.squad.entities.list",
    requiresRepo: true,
    params: shape({ repo: shape({ repoId: "string" }) }),
    guiBridgeMethod: "listSquads",
    httpMethod: "GET",
    path: "/api/squads",
    inputSchemaId: "gui.empty/v1",
    outputSchemaId: DAEMON_SQUAD_ENTITY_CATALOG_SCHEMA.id,
    errorSchemaId: DAEMON_PROTOCOL_ERROR_SCHEMA.id,
    serviceMethod: "listSquads",
    auth: "local-session-token",
    commandClass: "repo-read",
  },
  {
    id: "squad.entity.read",
    phase: "Runtime-B",
    method: "repo.squad.entity.read",
    requiresRepo: true,
    params: shape({
      repo: shape({ repoId: "string" }),
      payload: shape({ squadId: "string" }),
    }),
    guiBridgeMethod: "showSquad",
    httpMethod: "GET",
    path: "/api/squads/:squadId",
    inputSchemaId: "gui.squad-entity-read/v1",
    outputSchemaId: DAEMON_SQUAD_ENTITY_DETAIL_SCHEMA.id,
    errorSchemaId: DAEMON_PROTOCOL_ERROR_SCHEMA.id,
    serviceMethod: "showSquad",
    auth: "local-session-token",
    commandClass: "repo-read",
  },
  {
    id: "squad.runs.list",
    phase: "Runtime-B",
    method: "repo.squad.runs.list",
    requiresRepo: true,
    params: shape({
      repo: shape({ repoId: "string" }),
      payload: shape({ since: "string?", query: "string?", limit: "number?", cursor: "string?" }),
    }),
    guiBridgeMethod: "listSquadRuns",
    httpMethod: "GET",
    path: "/api/squad-runs",
    inputSchemaId: "gui.squad-run-query/v1",
    outputSchemaId: DAEMON_SQUAD_RUN_LIST_SCHEMA.id,
    errorSchemaId: DAEMON_PROTOCOL_ERROR_SCHEMA.id,
    serviceMethod: "listSquadRuns",
    auth: "local-session-token",
    commandClass: "repo-read",
  },
  {
    id: "squad.runs.read",
    phase: "Runtime-B",
    method: "repo.squad.runs.read",
    requiresRepo: true,
    params: shape({
      repo: shape({ repoId: "string" }),
      payload: shape({ squadRunId: "string" }),
    }),
    guiBridgeMethod: "readSquadRun",
    httpMethod: "GET",
    path: "/api/squad-runs/:squadRunId",
    inputSchemaId: "gui.squad-run-read/v1",
    outputSchemaId: DAEMON_SQUAD_RUN_READ_SCHEMA.id,
    errorSchemaId: DAEMON_PROTOCOL_ERROR_SCHEMA.id,
    serviceMethod: "readSquadRun",
    auth: "local-session-token",
    commandClass: "repo-read",
  },
  {
    id: "gui.catalog.snapshot",
    phase: "W5-GUI-S3",
    method: "repo.gui.catalog.snapshot",
    requiresRepo: true,
    params: shape({ repo: shape({ repoId: "string" }) }),
    guiBridgeMethod: "getCatalogSnapshot",
    httpMethod: "GET",
    path: "/api/catalog",
    inputSchemaId: "gui.empty/v1",
    outputSchemaId: GUI_CATALOG_SNAPSHOT_SCHEMA.id,
    errorSchemaId: DAEMON_PROTOCOL_ERROR_SCHEMA.id,
    serviceMethod: "getCatalogSnapshot",
    auth: "local-session-token",
    commandClass: "repo-read",
  },
  {
    id: "gui.catalog.preset.read",
    phase: "W5-GUI-S3",
    method: "repo.gui.catalog.preset.read",
    requiresRepo: true,
    params: shape({
      repo: shape({ repoId: "string" }),
      payload: shape({
        presetId: "string",
        profileId: "string?",
        locale: "string?",
      }),
    }),
    guiBridgeMethod: "getCatalogPreset",
    httpMethod: "GET",
    path: "/api/catalog/presets/:presetId",
    inputSchemaId: "gui.catalog-preset/v1",
    outputSchemaId: GUI_CATALOG_PRESET_SCHEMA.id,
    errorSchemaId: DAEMON_PROTOCOL_ERROR_SCHEMA.id,
    serviceMethod: "getCatalogPreset",
    auth: "local-session-token",
    commandClass: "repo-read",
  },
  {
    id: "terminal.sessions.list",
    phase: "W5-GUI-S3",
    method: "repo.terminal.sessions.list",
    requiresRepo: true,
    params: shape({ repo: shape({ repoId: "string" }) }),
    guiBridgeMethod: "listTerminalSessions",
    httpMethod: "GET",
    path: "/api/terminal/sessions",
    inputSchemaId: "gui.empty/v1",
    outputSchemaId: TERMINAL_SESSION_LIST_SCHEMA.id,
    errorSchemaId: DAEMON_PROTOCOL_ERROR_SCHEMA.id,
    serviceMethod: "listTerminalSessions",
    auth: "local-session-token",
    commandClass: "repo-read",
  },
] as const satisfies ReadonlyArray<{
  readonly method: DaemonGuiRpcReadMethod;
  readonly [key: string]: unknown;
}>);
