import { existsSync, realpathSync } from "node:fs";
import path from "node:path";
import { isJsonObject, type JsonObject } from "./json-rpc-types.ts";
import type { AgentRuntimeEventsResult, AgentRuntimeOverviewResult, AgentRuntimeSessionResult } from "../agent-runtime-contract.ts";
import type { AgentRuntimeAttachResult } from "../agent-runtime-stream.ts";
import { cliInput, defineCliCommand, presetCommands, presetMethods } from "../../../preset/src/preset-command-contract.ts";
declare const safePathBrand: unique symbol, canonicalRootBrand: unique symbol, endpointIdentityBrand: unique symbol, workspaceIdBrand: unique symbol;
export type SafePath = string & { readonly [safePathBrand]: true }; export type CanonicalRoot = SafePath & { readonly [canonicalRootBrand]: true };
export type EndpointIdentity = string & { readonly [endpointIdentityBrand]: true }; export type WorkspaceId = string & { readonly [workspaceIdBrand]: true };
export function safePath(value: string): SafePath { return path.resolve(value) as SafePath; }
export function canonicalRoot(value: string, allowMissing = false): CanonicalRoot { const resolved = path.resolve(value); if (existsSync(resolved)) return realpathSync.native(resolved) as CanonicalRoot;
  const parent = path.dirname(resolved); if (!allowMissing || !existsSync(parent)) throw new DaemonProtocolContractError("invalid_root", `Canonical root does not exist: ${resolved}`);
  return path.join(realpathSync.native(parent), path.basename(resolved)) as CanonicalRoot; }
export function endpointIdentity(value: string): EndpointIdentity { if (!value.trim()) throw new DaemonProtocolContractError("invalid_endpoint", "Endpoint identity is required."); return value as EndpointIdentity; }
export function workspaceId(value: string): WorkspaceId { if (!/^[a-z][a-z0-9-]{0,62}$/u.test(value)) throw new DaemonProtocolContractError("invalid_workspace", "Workspace id is invalid."); return value as WorkspaceId; }
const daemonOwnedProtocolCommands = Object.freeze([
  defineCliCommand({ id: "repo-bootstrap", phase: "W3", path: ["init"], summary: "Initialize and register a workspace through the explicit daemon.", method: "daemon.repo.bootstrap", commandClass: "admin", inputs: [cliInput("--repo-id", "single", true, { code: "missing_field", nextAction: "Init requires repo-id, person-id, and display-name." }), cliInput("--person-id", "single", true, { code: "missing_field", nextAction: "Init requires repo-id, person-id, and display-name." }), cliInput("--display-name", "single", true, { code: "missing_field", nextAction: "Init requires repo-id, person-id, and display-name." })] }), defineCliCommand({ id: "task-start", phase: "W3", path: ["task", "start", "<task-id>"], summary: "Acquire the task execution lease.", method: "repo.task.run", commandClass: "repo-write", inputs: [cliInput("--execution-id", "single", true, { code: "missing_field", nextAction: "Add --execution-id <execution-id>." })] }), defineCliCommand({ id: "task-progress-append", phase: "W3", path: ["task", "progress", "append", "<task-id>"], summary: "Append typed progress through the active task lease.", method: "repo.task.run", commandClass: "repo-write", inputs: [cliInput("--text", "single", true, { code: "missing_field", nextAction: "Add --text <progress-text>." }), cliInput("--evidence", "repeated", false, { code: "invalid_field", nextAction: "Use --evidence <type>:<path>:<summary> with a canonical relative path." }, { regex: "^[a-z][a-z0-9_-]{0,31}:[^:]+:.+$" })] }), defineCliCommand({ id: "task-submit", phase: "W3", path: ["task", "submit", "<task-id>"], summary: "Submit leased execution evidence.", method: "repo.task.run", commandClass: "repo-write", inputs: [cliInput("--execution-id", "single", true, { code: "invalid_field", nextAction: "Submit requires execution-id, claim, and a valid commit sha." }), cliInput("--claim", "single", true, { code: "invalid_field", nextAction: "Submit requires execution-id, claim, and a valid commit sha." }), cliInput("--commit-sha", "single", true, { code: "invalid_field", nextAction: "Submit requires execution-id, claim, and a valid commit sha." }, { regex: "^[0-9a-f]{40}$" }), ...["--deliverable", "--evidence-ref", "--verification", "--known-gap", "--residual-risk"].map((name) => cliInput(name, "repeated", false, { code: "invalid_field", nextAction: `${name} requires a non-empty value.` }))] }),
  defineCliCommand({ id: "task-review-execution", phase: "W3", path: ["task", "review-execution", "<task-id>"], summary: "Record an execution review.", method: "repo.task.run", commandClass: "arbiter", inputs: [cliInput("--execution-id", "single", true, { code: "invalid_field", nextAction: "Review requires execution-id, kind, verdict, review-id, reason, commit-sha, and iteration 0|1." }), cliInput("--kind", "single", true, { code: "invalid_field", nextAction: "Review kind must be anti_entropy or acceptance." }, { enum: ["anti_entropy", "acceptance"] }), cliInput("--verdict", "single", true, { code: "invalid_field", nextAction: "Review verdict must be approved, changes_requested, or dismissed." }, { enum: ["approved", "changes_requested", "dismissed"] }), cliInput("--review-id", "single", true, { code: "invalid_field", nextAction: "Review requires a review id." }), cliInput("--reason", "single", true, { code: "invalid_field", nextAction: "Review requires a reason." }), cliInput("--commit-sha", "single", true, { code: "invalid_field", nextAction: "Review requires a valid commit sha." }, { regex: "^[0-9a-f]{40}$" }), cliInput("--iteration", "single", true, { code: "invalid_field", nextAction: "Review iteration must be 0 or 1." }, { enum: ["0", "1"] }), cliInput("--evidence-checked", "repeated", false, { code: "invalid_field", nextAction: "--evidence-checked requires a non-empty value." }), cliInput("--acknowledge-archive-warnings", "boolean", false, { code: "invalid_field", nextAction: "Use --acknowledge-archive-warnings once." })] }), defineCliCommand({ id: "task-complete", phase: "W3", path: ["task", "complete", "<task-id>"], summary: "Complete a leased task.", method: "repo.task.run", commandClass: "repo-write", inputs: [cliInput("--execution-id", "single", true, { code: "missing_field", nextAction: "Add --execution-id <execution-id>." }), cliInput("--gate-receipt", "repeated", false, { code: "invalid_field", nextAction: "Use --gate-receipt <gate-id>:<receipt-ref>." }, { regex: "^[^:]+:.+$" })] }), defineCliCommand({ id: "task-show", phase: "W3", path: ["task", "show", "<task-id>"], summary: "Read the task projection.", method: "repo.task.run", commandClass: "repo-read", inputs: [] }), defineCliCommand({ id: "receipt-show", phase: "W3", path: ["receipt", "show", "<op-id>"], summary: "Read a write receipt.", method: "repo.task.run", commandClass: "repo-read", inputs: [] }),
  defineCliCommand({ id: "doc-status", phase: "DocSync-B", path: ["doc", "status"], summary: "Scan the authored root for document candidates.", method: "repo.task.run", commandClass: "repo-read", inputs: [cliInput("--path", "repeated", false, { code: "invalid_field", nextAction: "--path requires an authored-relative path." })] }), defineCliCommand({ id: "doc-sync-dry-run", actionKind: "doc-dry-run", phase: "DocSync-B", path: ["doc", "sync", "--dry-run"], summary: "Preview the scanner selection without writing.", method: "repo.task.run", commandClass: "repo-read", inputs: [cliInput("--path", "repeated", false, { code: "invalid_field", nextAction: "--path requires an authored-relative path." })] }), defineCliCommand({ id: "doc-sync-submit", actionKind: "doc-submit", phase: "DocSync-B", path: ["doc", "sync", "--submit"], summary: "Submit eligible scanner candidates through the resident daemon.", method: "repo.task.run", commandClass: "repo-write", inputs: [cliInput("--execution-id", "single", false, { code: "invalid_field", nextAction: "--execution-id requires a non-empty value." }), cliInput("--path", "repeated", false, { code: "invalid_field", nextAction: "--path requires an authored-relative path." })] }), defineCliCommand({ id: "doc-materialize", phase: "DocSync-B", path: ["doc", "materialize"], summary: "Restore the current canonical document cut to the worktree.", method: "repo.task.run", commandClass: "repo-write", inputs: [] }), defineCliCommand({ id: "doc-show", phase: "DocSync-B", path: ["doc", "show"], summary: "Show a canonical projected document.", method: "repo.task.run", commandClass: "repo-read", inputs: [cliInput("--path", "single", true, { code: "missing_field", nextAction: "Add --path <authored-relative-path>." })] }),
  defineCliCommand({ id: "fact-record", phase: "DecisionFact-A", path: ["fact", "record"], summary: "Record an immutable Fact event.", method: "repo.task.run", commandClass: "repo-write", inputs: [cliInput("--task", "single", true, { code: "missing_field", nextAction: "Fact record requires --task, --statement, and --source." }), cliInput("--statement", "single", true, { code: "missing_field", nextAction: "Fact record requires --task, --statement, and --source." }), cliInput("--source", "single", true, { code: "missing_field", nextAction: "Fact record requires --task, --statement, and --source." }), cliInput("--observed-at", "single", false, { code: "invalid_field", nextAction: "Use an ISO-8601 UTC timestamp for --observed-at." }, { regex: "^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}(?:\\.[0-9]+)?Z$" }), cliInput("--confidence", "single", false, { code: "invalid_field", nextAction: "Confidence must be low, medium, or high." }, { enum: ["low", "medium", "high"] }), cliInput("--memory-class", "single", false, { code: "invalid_field", nextAction: "Memory class must be semantic, episodic, or procedural." }, { enum: ["semantic", "episodic", "procedural"] }), cliInput("--memory-tag", "repeated", false, { code: "invalid_field", nextAction: "--memory-tag requires a non-empty value." }), cliInput("--supersedes", "single", false, { code: "invalid_field", nextAction: "Pair --supersedes with a rationale of at most 199 characters." }), cliInput("--rationale", "single", false, { code: "invalid_field", nextAction: "Pair --supersedes with a rationale of at most 199 characters." }, { regex: "^[\\s\\S]{1,199}$" })] }),
  defineCliCommand({ id: "fact-search", phase: "DecisionFact-A", path: ["fact", "search", "[query]"], summary: "Search the Fact FTS projection.", method: "repo.task.run", commandClass: "repo-read", inputs: [cliInput("--task", "single", false, { code: "invalid_field", nextAction: "--task requires a task id." }), cliInput("--confidence", "single", false, { code: "invalid_field", nextAction: "Fact search confidence must be low, medium, or high." }, { enum: ["low", "medium", "high"] }), cliInput("--memory-class", "single", false, { code: "invalid_field", nextAction: "Fact search memory class must be semantic, episodic, or procedural." }, { enum: ["semantic", "episodic", "procedural"] })] }), defineCliCommand({ id: "fact-show", phase: "DecisionFact-A", path: ["fact", "show"], summary: "Show one projected Fact.", method: "repo.task.run", commandClass: "repo-read", inputs: [cliInput("--task", "single", true, { code: "missing_field", nextAction: "Fact show requires --task and --id." }), cliInput("--id", "single", true, { code: "invalid_field", nextAction: "Use F- followed by eight Crockford characters." }, { regex: "^F-[0-9A-HJKMNP-TV-Z]{8}$" })] }),
  defineCliCommand({ id: "decision-propose", phase: "DecisionFact-B", path: ["decision", "propose"], summary: "Propose an immutable Decision.", method: "repo.task.run", commandClass: "repo-write", inputs: [cliInput("--title", "single", true, { code: "invalid_field", nextAction: "Propose requires title, question, chosen JSON, and rejected JSON." }), cliInput("--question", "single", true, { code: "invalid_field", nextAction: "Question must contain 1..499 characters." }, { regex: "^[\\s\\S]{1,499}$" }), cliInput("--chosen", "repeated", true, { code: "invalid_field", nextAction: "Chosen and rejected values must be JSON objects." }), cliInput("--rejected", "repeated", true, { code: "invalid_field", nextAction: "Chosen and rejected values must be JSON objects." }), ...["--risk-tier", "--urgency", "--vertical", "--preset", "--decision-class"].map((name) => cliInput(name, "single", false, { code: "invalid_field", nextAction: `${name} requires a non-empty value.` })), cliInput("--module", "repeated", false, { code: "invalid_field", nextAction: "--module requires a non-empty value." }), cliInput("--product-line", "repeated", false, { code: "invalid_field", nextAction: "--product-line requires a non-empty value." })] }), defineCliCommand({ id: "decision-accept", phase: "DecisionFact-B", path: ["decision", "accept", "<id>"], summary: "Accept a proposed Decision as independent arbiter.", method: "repo.task.run", commandClass: "arbiter", inputs: [cliInput("--rationale", "single", true, { code: "invalid_field", nextAction: "A rationale of 1..199 characters is required." }, { regex: "^[\\s\\S]{1,199}$" })] }), defineCliCommand({ id: "decision-reject", phase: "DecisionFact-B", path: ["decision", "reject", "<id>"], summary: "Reject a proposed Decision as independent arbiter.", method: "repo.task.run", commandClass: "arbiter", inputs: [cliInput("--rationale", "single", true, { code: "invalid_field", nextAction: "A rationale of 1..199 characters is required." }, { regex: "^[\\s\\S]{1,199}$" })] }), defineCliCommand({ id: "decision-defer", phase: "DecisionFact-B", path: ["decision", "defer", "<id>"], summary: "Defer a proposed Decision as independent arbiter.", method: "repo.task.run", commandClass: "arbiter", inputs: [cliInput("--rationale", "single", true, { code: "invalid_field", nextAction: "A rationale of 1..199 characters is required." }, { regex: "^[\\s\\S]{1,199}$" })] }), defineCliCommand({ id: "decision-retire", phase: "DecisionFact-B", path: ["decision", "retire", "<id>"], summary: "Retire an accepted Decision.", method: "repo.task.run", commandClass: "repo-write", inputs: [cliInput("--reason", "single", true, { code: "invalid_field", nextAction: "A reason of 1..199 characters is required." }, { regex: "^[\\s\\S]{1,199}$" })] }),
  defineCliCommand({ id: "decision-claim-add", phase: "DecisionFact-B", path: ["decision", "claim", "add", "<id>"], summary: "Append a Decision claim.", method: "repo.task.run", commandClass: "repo-write", inputs: [cliInput("--id", "single", true, { code: "invalid_field", nextAction: "Claim requires a C-prefixed --id." }, { regex: "^C[A-Za-z0-9_-]+$" }), cliInput("--text", "single", true, { code: "invalid_field", nextAction: "Claim requires --text." }), cliInput("--non-load-bearing", "boolean", false, { code: "invalid_field", nextAction: "Use --non-load-bearing once." })] }), defineCliCommand({ id: "decision-claim-fulfill", phase: "DecisionFact-B", path: ["decision", "claim", "fulfill", "<id>"], summary: "Declare a claim fulfillment mode.", method: "repo.task.run", commandClass: "repo-write", inputs: [cliInput("--id", "single", true, { code: "invalid_field", nextAction: "Claim requires a C-prefixed --id." }, { regex: "^C[A-Za-z0-9_-]+$" }), cliInput("--mode", "single", true, { code: "invalid_field", nextAction: "Fulfillment requires evidenced, delivered, or standing_policy mode." }, { enum: ["evidenced", "delivered", "standing_policy"] })] }), defineCliCommand({ id: "decision-relate", phase: "DecisionFact-B", path: ["decision", "relate", "<id>"], summary: "Append a Decision-owned relation.", method: "repo.task.run", commandClass: "repo-write", inputs: [cliInput("--anchor", "single", false, { code: "invalid_field", nextAction: "--anchor requires a non-empty id." }), cliInput("--type", "single", true, { code: "invalid_field", nextAction: "Relate requires type, target, and a rationale of 1..199 characters." }), cliInput("--target", "single", true, { code: "invalid_field", nextAction: "Relate requires type, target, and a rationale of 1..199 characters." }), cliInput("--rationale", "single", true, { code: "invalid_field", nextAction: "Relate requires type, target, and a rationale of 1..199 characters." }, { regex: "^[\\s\\S]{1,199}$" })] }), defineCliCommand({ id: "decision-relation-retire", phase: "DecisionFact-B", path: ["decision", "relation", "retire", "<id>"], summary: "Retire a Decision-owned relation.", method: "repo.task.run", commandClass: "repo-write", inputs: [cliInput("--relation", "single", true, { code: "invalid_field", nextAction: "Relation retire requires a deterministic relation id and reason." }, { regex: "^rel_[0-9a-f]{16}$" }), cliInput("--reason", "single", true, { code: "invalid_field", nextAction: "Relation retire requires a deterministic relation id and reason." }, { regex: "^[\\s\\S]{1,199}$" })] }),
  defineCliCommand({ id: "decision-reckon", phase: "DecisionFact-B", path: ["decision", "reckon", "<id>"], summary: "Record coverage at the exact projected basis revision.", method: "repo.task.run", commandClass: "repo-write", inputs: [cliInput("--task", "single", true, { code: "missing_field", nextAction: "Reckon requires --task." })] }), defineCliCommand({ id: "decision-search", phase: "DecisionFact-B", path: ["decision", "search", "[query]"], summary: "Search the Decision FTS projection.", method: "repo.task.run", commandClass: "repo-read", inputs: [cliInput("--state", "single", false, { code: "invalid_field", nextAction: "Decision state filter is invalid." }, { enum: ["proposed", "accepted", "rejected", "deferred", "retired"] }), cliInput("--risk-tier", "single", false, { code: "invalid_field", nextAction: "--risk-tier requires a non-empty value." }), cliInput("--vertical", "single", false, { code: "invalid_field", nextAction: "--vertical requires a non-empty value." })] }), defineCliCommand({ id: "decision-show", phase: "DecisionFact-B", path: ["decision", "show", "<id>"], summary: "Show one projected Decision and optional body join.", method: "repo.task.run", commandClass: "repo-read", inputs: [cliInput("--include-body", "boolean", false, { code: "invalid_field", nextAction: "Use --include-body once." })] }),
  defineCliCommand({ id: "daemon-repo-register", phase: "W3", path: ["daemon", "repo", "register"], summary: "Register an initialized workspace.", method: "daemon.repo.register", commandClass: "admin", inputs: [cliInput("--repo-id", "single", true, { code: "missing_field", nextAction: "Register requires --repo-id and --root." }), cliInput("--root", "single", true, { code: "missing_field", nextAction: "Register requires --repo-id and --root." })] }), defineCliCommand({ id: "daemon-repo-unregister", phase: "W3", path: ["daemon", "repo", "unregister"], summary: "Disable a registered workspace.", method: "daemon.repo.unregister", commandClass: "admin", inputs: [cliInput("--repo-id", "single", true, { code: "missing_field", nextAction: "Unregister requires --repo-id." })] }), defineCliCommand({ id: "daemon-start", phase: "W3", path: ["daemon", "start", "--service"], summary: "Explicitly start the resident daemon.", method: "protocol.hello", commandClass: "admin", inputs: [] }), defineCliCommand({ id: "daemon-status", phase: "W3", path: ["daemon", "status"], summary: "Show daemon and RepoCell status.", method: "daemon.status", commandClass: "repo-read", inputs: [] }),
  defineCliCommand({ id: "daemon-stop", phase: "W3", path: ["daemon", "stop"], summary: "Stop the resident daemon.", method: "protocol.hello", commandClass: "admin", inputs: [] })
] as const);
export const daemonProtocolCommands = Object.freeze([...daemonOwnedProtocolCommands, ...presetCommands]);
export const thinCliCommands = Object.freeze(daemonProtocolCommands.map(({ usage, summary }) => ({ usage, summary })));
export function resolveThinCliCommand(args: readonly string[]): (typeof daemonProtocolCommands)[number] | undefined { return daemonProtocolCommands.find((entry) => entry.path.every((token, index) => args[index] === token)); }
export function commandClassForAction(kind: string): "repo-read" | "repo-write" | "arbiter" | "admin" { const descriptor = daemonProtocolCommands.find((entry) => ("actionKind" in entry ? entry.actionKind : entry.id) === kind) ?? presetMethods.find((entry) => entry.actionKind === kind); if (!descriptor) throw new DaemonProtocolContractError("unsupported_command", `No command descriptor exists for ${kind}.`); return descriptor.commandClass; }
export function actionForDaemonMethod(method: string, payload: JsonObject): JsonObject & { readonly kind: string } { if (method === "repo.task.run") { const action = payload.action as JsonObject & { readonly kind: string }, descriptor = daemonProtocolCommands.find((entry) => ("actionKind" in entry ? entry.actionKind : entry.id) === action.kind); if (descriptor?.method !== method) throw new DaemonProtocolContractError("unsupported_command", `${action.kind} requires its closed method descriptor.`); return action; } const descriptor = presetMethods.find((entry) => entry.method === method); if (!descriptor) throw new DaemonProtocolContractError("unsupported_command", `No action descriptor exists for ${method}.`); return { kind: descriptor.actionKind, ...payload }; }
type RpcShape = { readonly fields: Readonly<Record<string, "string" | "number" | "boolean?" | "string?" | "json" | "json?" | RpcShape>>; readonly open?: boolean };
const shape = (fields: RpcShape["fields"], open = false): RpcShape => ({ fields, open });
export type DaemonGuiReadResultMap = {
  readonly "repo.tasks.list": { readonly ok: true } & import("../../../kernel/src/projection/rebuildable-task-projection.ts").TaskProjectionListRead;
  readonly "repo.triadic.relationGraph": { readonly ok: true; readonly facts: readonly import("../../../kernel/src/projection/fact-event-projection.ts").FactProjectionRow[] } & ReturnType<typeof import("../../../kernel/src/projection/sqlite-task-projection.ts").readRelationGraphProjection>;
  readonly "repo.decisions.list": { readonly ok: true; readonly decisions: readonly import("../../../kernel/src/projection/fact-event-projection.ts").DecisionProjectionRow[]; readonly warnings: readonly import("../../../kernel/src/projection/types.ts").ProjectionWarning[] }; readonly "repo.tasks.document.read": { readonly ok: true; readonly status: "ready" | "pending"; readonly taskId: string; readonly path: string; readonly body: string; readonly blobSha256: string | null; readonly watermark: number; readonly sourceRevision: number };
  readonly "repo.agentRuntime.overview": AgentRuntimeOverviewResult; readonly "repo.agentRuntime.sessions.read": AgentRuntimeSessionResult; readonly "repo.agentRuntime.events.read": AgentRuntimeEventsResult;
};
export type DaemonGuiReadMethod = keyof DaemonGuiReadResultMap;
export type DaemonGuiReadPayloadMap = { readonly "repo.tasks.list": Readonly<Record<string, never>>; readonly "repo.triadic.relationGraph": Readonly<Record<string, never>>; readonly "repo.decisions.list": Readonly<Record<string, never>>; readonly "repo.tasks.document.read": { readonly taskId: string; readonly path: string }; readonly "repo.agentRuntime.overview": { readonly taskId?: string }; readonly "repo.agentRuntime.sessions.read": { readonly runtimeSessionId: string }; readonly "repo.agentRuntime.events.read": { readonly runtimeSessionId: string; readonly afterCursor: string } };
export type DaemonGuiStreamResultMap = { readonly "repo.agentRuntime.attach": AgentRuntimeAttachResult }; export type DaemonGuiStreamMethod = keyof DaemonGuiStreamResultMap;
export type DaemonGuiStreamPayloadMap = { readonly "repo.agentRuntime.attach": { readonly runtimeSessionId: string; readonly afterCursor: string } };
export interface DaemonProtocolErrorResult { readonly schema: "command-receipt/v2"; readonly ok: false; readonly command: string; readonly outcome: "rejected"; readonly opId: "N/A"; readonly origin: "daemon"; readonly code: string; readonly evidence: string; readonly error: { readonly code: string; readonly hint: string }; readonly nextAction: string } export const DAEMON_TASK_SNAPSHOT_LIST_SCHEMA = Object.freeze({ id: "daemon.task-snapshot-list/v1", required: Object.freeze(["ok", "status", "rows", "watermark", "sourceRevision", "warnings"]) });
export const DAEMON_RELATION_GRAPH_SCHEMA = Object.freeze({ id: "daemon.relation-graph/v1", required: Object.freeze(["ok", "edges", "coverageRows", "factAnchors", "facts", "warnings"]) }), DAEMON_DECISION_LIST_SCHEMA = Object.freeze({ id: "daemon.decision-list/v1", required: Object.freeze(["ok", "decisions", "warnings"]) }), DAEMON_DOCUMENT_READ_SCHEMA = Object.freeze({ id: "daemon.document-read/v1", required: Object.freeze(["ok", "status", "taskId", "path", "body", "blobSha256", "watermark", "sourceRevision"]) }), DAEMON_PROTOCOL_ERROR_SCHEMA = Object.freeze({ id: "daemon.protocol-error/v1", required: Object.freeze(["schema", "ok", "command", "outcome", "opId", "origin", "code", "evidence", "error", "nextAction"]) });
export const DAEMON_AGENT_RUNTIME_OVERVIEW_SCHEMA = Object.freeze({ id: "daemon.agent-runtime-overview/v1" }), DAEMON_AGENT_RUNTIME_SESSION_SCHEMA = Object.freeze({ id: "daemon.agent-runtime-session/v1" }), DAEMON_AGENT_RUNTIME_EVENTS_SCHEMA = Object.freeze({ id: "daemon.agent-runtime-events/v1" }), DAEMON_AGENT_RUNTIME_ATTACH_SCHEMA = Object.freeze({ id: "daemon.agent-runtime-attach/v1" }), DAEMON_AGENT_RUNTIME_ATTACH_EVENT_SCHEMA = Object.freeze({ id: "daemon.agent-runtime-attach-event/v1" });
export const daemonGuiReadMethods = Object.freeze([
  { id: "tasks.list", phase: "W2-GUI", method: "repo.tasks.list", requiresRepo: true, params: shape({ repo: shape({ repoId: "string" }) }), guiBridgeMethod: "getTasks", httpMethod: "GET", path: "/api/tasks", inputSchemaId: "gui.empty/v1", outputSchemaId: DAEMON_TASK_SNAPSHOT_LIST_SCHEMA.id, errorSchemaId: DAEMON_PROTOCOL_ERROR_SCHEMA.id, serviceMethod: "listTasks", auth: "local-session-token", commandClass: "repo-read" },
  { id: "triadic.relationGraph", phase: "W2-GUI", method: "repo.triadic.relationGraph", requiresRepo: true, params: shape({ repo: shape({ repoId: "string" }) }), guiBridgeMethod: "getRelationGraph", httpMethod: "GET", path: "/api/triadic/relation-graph", inputSchemaId: "gui.empty/v1", outputSchemaId: DAEMON_RELATION_GRAPH_SCHEMA.id, errorSchemaId: DAEMON_PROTOCOL_ERROR_SCHEMA.id, serviceMethod: "readRelationGraph", auth: "local-session-token", commandClass: "repo-read" },
  { id: "decisions.list", phase: "W2-GUI", method: "repo.decisions.list", requiresRepo: true, params: shape({ repo: shape({ repoId: "string" }) }), guiBridgeMethod: "getDecisions", httpMethod: "GET", path: "/api/decisions", inputSchemaId: "gui.empty/v1", outputSchemaId: DAEMON_DECISION_LIST_SCHEMA.id, errorSchemaId: DAEMON_PROTOCOL_ERROR_SCHEMA.id, serviceMethod: "listDecisions", auth: "local-session-token", commandClass: "repo-read" }, { id: "tasks.document.read", phase: "DocSync-B", method: "repo.tasks.document.read", requiresRepo: true, params: shape({ repo: shape({ repoId: "string" }), payload: shape({ taskId: "string", path: "string" }) }), guiBridgeMethod: "getTaskDocument", httpMethod: "GET", path: "/api/tasks/:taskId/documents/:path", inputSchemaId: "gui.task-document/v1", outputSchemaId: DAEMON_DOCUMENT_READ_SCHEMA.id, errorSchemaId: DAEMON_PROTOCOL_ERROR_SCHEMA.id, serviceMethod: "readDocument", auth: "local-session-token", commandClass: "repo-read" },
  { id: "agentRuntime.overview", phase: "Runtime-B", method: "repo.agentRuntime.overview", requiresRepo: true, params: shape({ repo: shape({ repoId: "string" }), payload: shape({}, true) }), guiBridgeMethod: "getAgentRuntimeOverview", httpMethod: "GET", path: "/api/agent-runtime", inputSchemaId: "gui.agent-runtime-overview/v1", outputSchemaId: DAEMON_AGENT_RUNTIME_OVERVIEW_SCHEMA.id, errorSchemaId: DAEMON_PROTOCOL_ERROR_SCHEMA.id, serviceMethod: "readAgentRuntimeOverview", auth: "local-session-token", commandClass: "repo-read" },
  { id: "agentRuntime.sessions.read", phase: "Runtime-B", method: "repo.agentRuntime.sessions.read", requiresRepo: true, params: shape({ repo: shape({ repoId: "string" }), payload: shape({ runtimeSessionId: "string" }) }), guiBridgeMethod: "getAgentRuntimeSession", httpMethod: "GET", path: "/api/agent-runtime/sessions/:id", inputSchemaId: "gui.agent-runtime-session/v1", outputSchemaId: DAEMON_AGENT_RUNTIME_SESSION_SCHEMA.id, errorSchemaId: DAEMON_PROTOCOL_ERROR_SCHEMA.id, serviceMethod: "readAgentRuntimeSession", auth: "local-session-token", commandClass: "repo-read" },
  { id: "agentRuntime.events.read", phase: "Runtime-B", method: "repo.agentRuntime.events.read", requiresRepo: true, params: shape({ repo: shape({ repoId: "string" }), payload: shape({ runtimeSessionId: "string", afterCursor: "string" }) }), guiBridgeMethod: "getAgentRuntimeEvents", httpMethod: "GET", path: "/api/agent-runtime/sessions/:id/events", inputSchemaId: "gui.agent-runtime-events/v1", outputSchemaId: DAEMON_AGENT_RUNTIME_EVENTS_SCHEMA.id, errorSchemaId: DAEMON_PROTOCOL_ERROR_SCHEMA.id, serviceMethod: "readAgentRuntimeEvents", auth: "local-session-token", commandClass: "repo-read" }
] as const satisfies ReadonlyArray<{ readonly method: DaemonGuiReadMethod; readonly [key: string]: unknown }>);
export const daemonGuiStreamFacets = Object.freeze([{ id: "agentRuntime.attach", phase: "Runtime-B", method: "repo.agentRuntime.attach", eventMethod: "repo.agentRuntime.attach.frame", requiresRepo: true, params: shape({ repo: shape({ repoId: "string" }), payload: shape({ runtimeSessionId: "string", afterCursor: "string" }) }), guiBridgeMethod: "attachAgentRuntime", httpMethod: "STREAM", path: "/api/agent-runtime/sessions/:id/attach", inputSchemaId: "gui.agent-runtime-attach/v1", outputSchemaId: DAEMON_AGENT_RUNTIME_ATTACH_SCHEMA.id, eventSchemaId: DAEMON_AGENT_RUNTIME_ATTACH_EVENT_SCHEMA.id, errorSchemaId: DAEMON_PROTOCOL_ERROR_SCHEMA.id, serviceMethod: "attachAgentRuntime", auth: "local-session-token", commandClass: "repo-read" }] as const);
const recordWith = (value: unknown, fields: readonly string[]): value is JsonObject => isJsonObject(value) && fields.every((field) => Object.hasOwn(value, field));
const nonEmpty = (value: unknown): value is string => typeof value === "string" && value.length > 0, integer = (value: unknown): value is number => Number.isInteger(value);
const stringArray = (value: unknown): value is readonly string[] => Array.isArray(value) && value.every(nonEmpty), warningArray = (value: unknown): boolean => Array.isArray(value) && value.every((warning) => recordWith(warning, ["code", "source", "severity", "message"]) && nonEmpty(warning.code) && nonEmpty(warning.source) && nonEmpty(warning.severity) && nonEmpty(warning.message));
const snapshot = (value: unknown): boolean => recordWith(value, ["revision", "task", "executions", "reviews", "edgesTaken", "lease"]) && integer(value.revision) && (value.task === null || isJsonObject(value.task)) && Array.isArray(value.executions) && Array.isArray(value.reviews) && Array.isArray(value.edgesTaken) && (value.lease === null || isJsonObject(value.lease));
export function validateDaemonTaskSnapshotList(value: unknown): readonly string[] { if (!recordWith(value, DAEMON_TASK_SNAPSHOT_LIST_SCHEMA.required) || value.ok !== true || (value.status !== "ready" && value.status !== "pending") || !integer(value.watermark) || !integer(value.sourceRevision) || !warningArray(value.warnings) || !Array.isArray(value.rows) || value.rows.some((row) => !recordWith(row, ["taskId", "workspaceRevision", "updatedAt", "snapshot"]) || !nonEmpty(row.taskId) || !integer(row.workspaceRevision) || !nonEmpty(row.updatedAt) || !snapshot(row.snapshot))) return ["daemon task snapshot list is invalid"]; return []; }
export function validateDaemonRelationGraph(value: unknown): readonly string[] { if (!recordWith(value, DAEMON_RELATION_GRAPH_SCHEMA.required) || value.ok !== true || !warningArray(value.warnings) || !Array.isArray(value.edges) || value.edges.some((edge) => !recordWith(edge, ["relationId", "sourceRef", "targetRef", "relationType", "direction", "strength", "origin", "state", "rationale", "ownerRef", "sourcePath", "recordIndex"]) || !integer(edge.recordIndex) || ["relationId", "sourceRef", "targetRef", "relationType", "direction", "strength", "origin", "state", "rationale", "ownerRef", "sourcePath"].some((field) => !nonEmpty(edge[field]))) || !Array.isArray(value.coverageRows) || value.coverageRows.some((row) => !recordWith(row, ["decisionRef", "claimRef", "status", "fulfillment", "refutingFactRefs", "relationPath", "basisRevision"]) || !nonEmpty(row.decisionRef) || !nonEmpty(row.claimRef) || row.status !== "covered" && row.status !== "uncovered" || row.fulfillment !== null && !["evidenced", "delivered", "standing_policy"].includes(String(row.fulfillment)) || !stringArray(row.refutingFactRefs) || !stringArray(row.relationPath) || !integer(row.basisRevision) || row.coveringFactRef !== undefined && !nonEmpty(row.coveringFactRef)) || !Array.isArray(value.factAnchors) || value.factAnchors.some((row) => !recordWith(row, ["factRef", "taskId", "factId", "sourcePath"]) || ["factRef", "taskId", "factId", "sourcePath"].some((field) => !nonEmpty(row[field]))) || !Array.isArray(value.facts) || value.facts.some((row) => !recordWith(row, ["schema", "ref", "taskId", "factId", "statement", "evidenceSource", "observedAt", "confidence", "memoryClass", "memoryTags", "provenance", "actor", "source", "occurredAt", "workspaceRevision", "state"]) || row.schema !== "fact-row/v1" || !integer(row.workspaceRevision) || ["ref", "taskId", "factId", "statement", "evidenceSource", "observedAt", "confidence", "memoryClass", "occurredAt", "state"].some((field) => !nonEmpty(row[field])))) return ["daemon relation graph is invalid"]; return []; }
export function validateDaemonDecisionList(value: unknown): readonly string[] { const fields = ["schema", "decisionId", "state", "title", "question", "riskTier", "urgency", "vertical", "preset", "decisionClass", "appliesTo", "proposer", "arbiter", "proposedAt", "decidedAt", "workspaceRevision", "chosen", "rejected", "claims", "body"]; if (!recordWith(value, DAEMON_DECISION_LIST_SCHEMA.required) || Object.keys(value).some((key) => !DAEMON_DECISION_LIST_SCHEMA.required.includes(key as never)) || value.ok !== true || !warningArray(value.warnings) || !Array.isArray(value.decisions) || value.decisions.some((row) => !recordWith(row, fields) || Object.keys(row).some((key) => !fields.includes(key)) || row.schema !== "decision-row/v1" || !integer(row.workspaceRevision) || ["decisionId", "state", "title", "question", "riskTier", "urgency", "vertical", "preset", "decisionClass", "proposedAt"].some((field) => !nonEmpty(row[field])) || !Array.isArray(row.chosen) || !Array.isArray(row.rejected) || !Array.isArray(row.claims) || !isJsonObject(row.appliesTo) || !isJsonObject(row.proposer) || row.arbiter !== null && !isJsonObject(row.arbiter) || row.body !== null && !isJsonObject(row.body))) return ["daemon decision list is invalid"]; return []; } export function validateDaemonDocumentRead(value: unknown): readonly string[] { if (!recordWith(value, DAEMON_DOCUMENT_READ_SCHEMA.required) || value.ok !== true || (value.status !== "ready" && value.status !== "pending") || !nonEmpty(value.taskId) || !nonEmpty(value.path) || typeof value.body !== "string" || (value.blobSha256 !== null && (typeof value.blobSha256 !== "string" || !/^[0-9a-f]{64}$/u.test(value.blobSha256))) || !integer(value.watermark) || !integer(value.sourceRevision)) return ["daemon document read is invalid"]; return []; }
export function validateDaemonProtocolError(value: unknown): readonly string[] { if (!recordWith(value, DAEMON_PROTOCOL_ERROR_SCHEMA.required) || value.schema !== "command-receipt/v2" || value.ok !== false || value.outcome !== "rejected" || value.opId !== "N/A" || value.origin !== "daemon" || !recordWith(value.error, ["code", "hint"]) || [value.command, value.code, value.evidence, value.nextAction, value.error.code, value.error.hint].some((item) => !nonEmpty(item)) || value.code !== value.error.code) return ["daemon protocol error is invalid"]; return []; }
type ResultValidator = (value: unknown) => readonly string[];
function serializeSchema(value: unknown, validate: ResultValidator): string { const errors = validate(value); if (errors.length) throw new DaemonProtocolContractError("invalid_result", errors.join("; ")); return `${JSON.stringify(value)}\n`; }
export const serializeDaemonTaskSnapshotList = (value: unknown): string => serializeSchema(value, validateDaemonTaskSnapshotList), serializeDaemonRelationGraph = (value: unknown): string => serializeSchema(value, validateDaemonRelationGraph), serializeDaemonDecisionList = (value: unknown): string => serializeSchema(value, validateDaemonDecisionList), serializeDaemonDocumentRead = (value: unknown): string => serializeSchema(value, validateDaemonDocumentRead), serializeDaemonProtocolError = (value: unknown): string => serializeSchema(value, validateDaemonProtocolError);
export function daemonProtocolError(command: string, code: string, hint: string): DaemonProtocolErrorResult { return { schema: "command-receipt/v2", ok: false, command, outcome: "rejected", opId: "N/A", origin: "daemon", code, evidence: `rejection:${code}`, error: { code, hint }, nextAction: hint }; }
export const daemonProtocolMethods = Object.freeze([
  { id: "protocol.hello", phase: "W3", method: "protocol.hello", requiresRepo: false, params: shape({ protocolVersion: "number" }) }, { id: "daemon.status", phase: "W3", method: "daemon.status", requiresRepo: false, params: shape({}) }, { id: "daemon.repo.bootstrap", phase: "W3", method: "daemon.repo.bootstrap", requiresRepo: false, params: shape({ rootDir: "string", repoId: "string", personId: "string", displayName: "string" }) }, { id: "daemon.repo.register", phase: "W3", method: "daemon.repo.register", requiresRepo: false, params: shape({ rootDir: "string", repoId: "string" }) }, { id: "daemon.repo.unregister", phase: "W3", method: "daemon.repo.unregister", requiresRepo: false, params: shape({ repoId: "string" }) },
  { id: "repo.task.run", phase: "W3", method: "repo.task.run", requiresRepo: true, params: shape({ repo: shape({ repoId: "string" }), payload: shape({ action: shape({ kind: "string" }, true) }) }) }
] as const);
const allDaemonProtocolMethods = Object.freeze([...daemonProtocolMethods, ...presetMethods, ...daemonGuiReadMethods, ...daemonGuiStreamFacets]);
export const jsonRpcMethodContracts = Object.freeze(allDaemonProtocolMethods.map(({ method, requiresRepo }) => ({ method, requiresRepo })));
export function isDaemonGuiReadMethod(method: string): method is DaemonGuiReadMethod { return daemonGuiReadMethods.some((entry) => entry.method === method); }
export function isDaemonGuiStreamMethod(method: string): method is DaemonGuiStreamMethod { return daemonGuiStreamFacets.some((entry) => entry.method === method); }
export function validateDaemonRpcCall(value: unknown): readonly string[] { if (!isJsonObject(value) || typeof value.method !== "string") return ["RPC method is required"]; const method = allDaemonProtocolMethods.find((entry) => entry.method === value.method); if (!method) return ["RPC method is not contracted"];
  return validateShape(value.params === undefined ? {} : value.params, method.params, "params"); }
export function parseDaemonRpcParams(method: string, params: unknown): { readonly ok: true; readonly params: JsonObject } | { readonly ok: false; readonly errors: readonly string[] } { const candidateParams = params === undefined ? {} : params, errors = validateDaemonRpcCall({ method, params: candidateParams });
  return errors.length ? { ok: false, errors } : { ok: true, params: candidateParams as JsonObject }; }
function validateShape(value: unknown, expected: RpcShape, prefix: string): string[] { if (!isJsonObject(value)) return [`${prefix} must be an object`]; const errors: string[] = []; if (!expected.open) for (const field of Object.keys(value)) if (!Object.hasOwn(expected.fields, field)) errors.push(`${prefix}.${field} is not allowed`);
  for (const [field, rule] of Object.entries(expected.fields)) { const item = value[field]; if ((rule === "string?" || rule === "json?" || rule === "boolean?") && item === undefined) continue; if (rule === "json" || rule === "json?") { if (!isJsonObject(item)) errors.push(`${prefix}.${field} must be object`); } else if (rule === "string" || rule === "string?" || rule === "number" || rule === "boolean?") { const type = rule === "string?" ? "string" : rule === "boolean?" ? "boolean" : rule; if (typeof item !== type || (type === "string" && !item)) errors.push(`${prefix}.${field} must be ${type}`); }
    else errors.push(...validateShape(item, rule, `${prefix}.${field}`)); } return errors; }
export const DAEMON_RPC_SCHEMA = Object.freeze({ id: "w3-daemon-rpc/v1", methods: allDaemonProtocolMethods.map(({ method, params }) => ({ method, params })) });
export function serializeDaemonRpcCall(value: unknown): string { const errors = validateDaemonRpcCall(value); if (errors.length) throw new DaemonProtocolContractError("invalid_rpc", errors.join("; ")); return `${JSON.stringify(value)}\n`; }
export class DaemonProtocolContractError extends Error { readonly code: string; constructor(code: string, message: string) { super(message); this.name = "DaemonProtocolContractError"; this.code = code; } }
export const daemonGuiReadSchemas = Object.freeze([{ id: DAEMON_TASK_SNAPSHOT_LIST_SCHEMA.id, schema: "packages/daemon/src/protocol/daemon-protocol.contract.ts#DAEMON_TASK_SNAPSHOT_LIST_SCHEMA", parser: "packages/daemon/src/protocol/daemon-protocol.contract.ts#validateDaemonTaskSnapshotList", writer: "packages/daemon/src/protocol/daemon-protocol.contract.ts#serializeDaemonTaskSnapshotList", error: "packages/daemon/src/protocol/daemon-protocol.contract.ts#DaemonProtocolContractError", negativeFixtures: Object.freeze(["packages/daemon/fixtures/contracts/daemon-task-snapshot-list-invalid.json"]) },
  { id: DAEMON_RELATION_GRAPH_SCHEMA.id, schema: "packages/daemon/src/protocol/daemon-protocol.contract.ts#DAEMON_RELATION_GRAPH_SCHEMA", parser: "packages/daemon/src/protocol/daemon-protocol.contract.ts#validateDaemonRelationGraph", writer: "packages/daemon/src/protocol/daemon-protocol.contract.ts#serializeDaemonRelationGraph", error: "packages/daemon/src/protocol/daemon-protocol.contract.ts#DaemonProtocolContractError", negativeFixtures: Object.freeze(["packages/daemon/fixtures/contracts/daemon-relation-graph-invalid.json"]) },
  { id: DAEMON_DECISION_LIST_SCHEMA.id, schema: "packages/daemon/src/protocol/daemon-protocol.contract.ts#DAEMON_DECISION_LIST_SCHEMA", parser: "packages/daemon/src/protocol/daemon-protocol.contract.ts#validateDaemonDecisionList", writer: "packages/daemon/src/protocol/daemon-protocol.contract.ts#serializeDaemonDecisionList", error: "packages/daemon/src/protocol/daemon-protocol.contract.ts#DaemonProtocolContractError", negativeFixtures: Object.freeze(["packages/daemon/fixtures/contracts/daemon-decision-list-invalid.json"]) },
  { id: DAEMON_DOCUMENT_READ_SCHEMA.id, schema: "packages/daemon/src/protocol/daemon-protocol.contract.ts#DAEMON_DOCUMENT_READ_SCHEMA", parser: "packages/daemon/src/protocol/daemon-protocol.contract.ts#validateDaemonDocumentRead", writer: "packages/daemon/src/protocol/daemon-protocol.contract.ts#serializeDaemonDocumentRead", error: "packages/daemon/src/protocol/daemon-protocol.contract.ts#DaemonProtocolContractError", negativeFixtures: Object.freeze(["packages/daemon/fixtures/contracts/daemon-document-read-invalid.json"]) }, { id: DAEMON_PROTOCOL_ERROR_SCHEMA.id, schema: "packages/daemon/src/protocol/daemon-protocol.contract.ts#DAEMON_PROTOCOL_ERROR_SCHEMA", parser: "packages/daemon/src/protocol/daemon-protocol.contract.ts#validateDaemonProtocolError", writer: "packages/daemon/src/protocol/daemon-protocol.contract.ts#serializeDaemonProtocolError", error: "packages/daemon/src/protocol/daemon-protocol.contract.ts#DaemonProtocolContractError", negativeFixtures: Object.freeze(["packages/daemon/fixtures/contracts/daemon-protocol-error-invalid.json"]) },
  { id: DAEMON_AGENT_RUNTIME_OVERVIEW_SCHEMA.id, schema: "packages/daemon/src/protocol/daemon-protocol.contract.ts#DAEMON_AGENT_RUNTIME_OVERVIEW_SCHEMA", parser: "packages/daemon/src/agent-runtime-contract.ts#validateAgentRuntimeOverview", writer: "packages/daemon/src/agent-runtime-contract.ts#serializeAgentRuntimeOverview", error: "packages/daemon/src/protocol/daemon-protocol.contract.ts#DaemonProtocolContractError", negativeFixtures: Object.freeze(["packages/daemon/fixtures/contracts/daemon-agent-runtime-overview-invalid.json"]) }, { id: DAEMON_AGENT_RUNTIME_SESSION_SCHEMA.id, schema: "packages/daemon/src/protocol/daemon-protocol.contract.ts#DAEMON_AGENT_RUNTIME_SESSION_SCHEMA", parser: "packages/daemon/src/agent-runtime-contract.ts#validateAgentRuntimeSession", writer: "packages/daemon/src/agent-runtime-contract.ts#serializeAgentRuntimeSession", error: "packages/daemon/src/protocol/daemon-protocol.contract.ts#DaemonProtocolContractError", negativeFixtures: Object.freeze(["packages/daemon/fixtures/contracts/daemon-agent-runtime-session-invalid.json"]) },
  { id: DAEMON_AGENT_RUNTIME_EVENTS_SCHEMA.id, schema: "packages/daemon/src/protocol/daemon-protocol.contract.ts#DAEMON_AGENT_RUNTIME_EVENTS_SCHEMA", parser: "packages/daemon/src/agent-runtime-contract.ts#validateAgentRuntimeEvents", writer: "packages/daemon/src/agent-runtime-contract.ts#serializeAgentRuntimeEvents", error: "packages/daemon/src/protocol/daemon-protocol.contract.ts#DaemonProtocolContractError", negativeFixtures: Object.freeze(["packages/daemon/fixtures/contracts/daemon-agent-runtime-events-invalid.json"]) }, { id: DAEMON_AGENT_RUNTIME_ATTACH_SCHEMA.id, schema: "packages/daemon/src/protocol/daemon-protocol.contract.ts#DAEMON_AGENT_RUNTIME_ATTACH_SCHEMA", parser: "packages/daemon/src/agent-runtime-stream.ts#validateAgentRuntimeAttach", writer: "packages/daemon/src/agent-runtime-stream.ts#serializeAgentRuntimeAttach", error: "packages/daemon/src/protocol/daemon-protocol.contract.ts#DaemonProtocolContractError", negativeFixtures: Object.freeze(["packages/daemon/fixtures/contracts/daemon-agent-runtime-attach-invalid.json"]) }, { id: DAEMON_AGENT_RUNTIME_ATTACH_EVENT_SCHEMA.id, schema: "packages/daemon/src/protocol/daemon-protocol.contract.ts#DAEMON_AGENT_RUNTIME_ATTACH_EVENT_SCHEMA", parser: "packages/daemon/src/agent-runtime-stream.ts#validateAgentRuntimeAttachEvent", writer: "packages/daemon/src/agent-runtime-stream.ts#serializeAgentRuntimeAttachEvent", error: "packages/daemon/src/protocol/daemon-protocol.contract.ts#DaemonProtocolContractError", negativeFixtures: Object.freeze(["packages/daemon/fixtures/contracts/daemon-agent-runtime-attach-event-invalid.json"]) }]);
export default Object.freeze({ id: "w3-daemon-protocol", phases: Object.freeze(["W3", "W2-GUI", "DocSync-B", "Runtime-B", "DecisionFact-A", "DecisionFact-B"]), commands: daemonOwnedProtocolCommands, methods: Object.freeze([...daemonProtocolMethods, ...daemonGuiReadMethods, ...daemonGuiStreamFacets]), gates: Object.freeze([]), guards: Object.freeze([]), schemas: Object.freeze([{ id: DAEMON_RPC_SCHEMA.id,
    schema: "packages/daemon/src/protocol/daemon-protocol.contract.ts#DAEMON_RPC_SCHEMA", parser: "packages/daemon/src/protocol/daemon-protocol.contract.ts#validateDaemonRpcCall", writer: "packages/daemon/src/protocol/daemon-protocol.contract.ts#serializeDaemonRpcCall", error: "packages/daemon/src/protocol/daemon-protocol.contract.ts#DaemonProtocolContractError",
    negativeFixtures: Object.freeze(["packages/daemon/fixtures/contracts/w3-daemon-rpc-invalid.json"]) }, ...daemonGuiReadSchemas]) });
