import { existsSync, realpathSync } from "node:fs";
import path from "node:path";
import { isJsonObject, type JsonObject } from "./json-rpc-types.ts";
import { validateAgentRuntimeEvents, validateAgentRuntimeOverview, validateAgentRuntimeSession, type AgentRuntimeEventsResult, type AgentRuntimeOverviewResult, type AgentRuntimeSessionResult } from "../agent-runtime-read.ts";
import { validateAgentRuntimeAttach, validateAgentRuntimeAttachEvent, type AgentRuntimeAttachEvent, type AgentRuntimeAttachResult } from "../agent-runtime-stream.ts";
declare const safePathBrand: unique symbol, canonicalRootBrand: unique symbol, endpointIdentityBrand: unique symbol, workspaceIdBrand: unique symbol;
export type SafePath = string & { readonly [safePathBrand]: true }; export type CanonicalRoot = SafePath & { readonly [canonicalRootBrand]: true };
export type EndpointIdentity = string & { readonly [endpointIdentityBrand]: true }; export type WorkspaceId = string & { readonly [workspaceIdBrand]: true };
export function safePath(value: string): SafePath { return path.resolve(value) as SafePath; }
export function canonicalRoot(value: string, allowMissing = false): CanonicalRoot { const resolved = path.resolve(value); if (existsSync(resolved)) return realpathSync.native(resolved) as CanonicalRoot;
  const parent = path.dirname(resolved); if (!allowMissing || !existsSync(parent)) throw new DaemonProtocolContractError("invalid_root", `Canonical root does not exist: ${resolved}`);
  return path.join(realpathSync.native(parent), path.basename(resolved)) as CanonicalRoot; }
export function endpointIdentity(value: string): EndpointIdentity { if (!value.trim()) throw new DaemonProtocolContractError("invalid_endpoint", "Endpoint identity is required."); return value as EndpointIdentity; }
export function workspaceId(value: string): WorkspaceId { if (!/^[a-z][a-z0-9-]{0,62}$/u.test(value)) throw new DaemonProtocolContractError("invalid_workspace", "Workspace id is invalid."); return value as WorkspaceId; }
export const daemonProtocolCommands = Object.freeze([
  { id: "repo-bootstrap", phase: "W3", path: ["init"], usage: "ha init --repo-id <id> --person-id <id> --display-name <name>", summary: "Initialize and register a workspace through the explicit daemon.", method: "daemon.repo.bootstrap" }, { id: "task-create", phase: "W3", path: ["task", "create"], usage: "ha task create --title <title> [--task-id <id>] [--completion-gate <id>]", summary: "Create a task.", method: "repo.task.run" }, { id: "task-start", phase: "W3", path: ["task", "start"], usage: "ha task start <task-id> --execution-id <id>", summary: "Acquire the task execution lease.", method: "repo.task.run" }, { id: "task-submit", phase: "W3", path: ["task", "submit"], usage: "ha task submit <task-id> --execution-id <id> --claim <text> --commit-sha <sha>", summary: "Submit leased execution evidence.", method: "repo.task.run" },
  { id: "task-review-execution", phase: "W3", path: ["task", "review-execution"], usage: "ha task review-execution <task-id> --execution-id <id> --kind <kind> --verdict <verdict> --review-id <id> --reason <text> --commit-sha <sha> --iteration <0|1>", summary: "Record an execution review.", method: "repo.task.run" }, { id: "task-complete", phase: "W3", path: ["task", "complete"], usage: "ha task complete <task-id> --execution-id <id> [--gate-receipt <gate-id>:<receipt-ref>]", summary: "Complete a leased task.", method: "repo.task.run" }, { id: "task-show", phase: "W3", path: ["task", "show"], usage: "ha task show <task-id>", summary: "Read the task projection.", method: "repo.task.run" }, { id: "receipt-show", phase: "W3", path: ["receipt", "show"], usage: "ha receipt show <op-id>", summary: "Read a write receipt.", method: "repo.task.run" }, { id: "doc-status", phase: "DocSync-B", path: ["doc", "status"], usage: "ha doc status --path <path>", summary: "Read a canonical document cut.", method: "repo.task.run" }, { id: "doc-sync-submit", phase: "DocSync-B", path: ["doc", "sync", "--submit"], usage: "ha doc sync --submit --execution-id <id> --base-ledger-sha <sha> --path <path> [--base-blob-sha256 <sha>]", summary: "Submit one selected document through the resident daemon.", method: "repo.task.run" }, { id: "doc-show", phase: "DocSync-B", path: ["doc", "show"], usage: "ha doc show --path <path>", summary: "Show a canonical projected document.", method: "repo.task.run" },
  { id: "daemon-repo-register", phase: "W3", path: ["daemon", "repo", "register"], usage: "ha daemon repo register --repo-id <id> --root <path>", summary: "Register an initialized workspace.", method: "daemon.repo.register" }, { id: "daemon-repo-unregister", phase: "W3", path: ["daemon", "repo", "unregister"], usage: "ha daemon repo unregister --repo-id <id>", summary: "Disable a registered workspace.", method: "daemon.repo.unregister" }, { id: "daemon-start", phase: "W3", path: ["daemon", "start"], usage: "ha daemon start --service", summary: "Explicitly start the resident daemon.", method: "protocol.hello" }, { id: "daemon-status", phase: "W3", path: ["daemon", "status"], usage: "ha daemon status", summary: "Show daemon and RepoCell status.", method: "daemon.status" },
  { id: "daemon-stop", phase: "W3", path: ["daemon", "stop"], usage: "ha daemon stop", summary: "Stop the resident daemon.", method: "protocol.hello" }
] as const);
export const thinCliCommands = Object.freeze(daemonProtocolCommands.map(({ usage, summary }) => ({ usage, summary })));
export function resolveThinCliCommand(args: readonly string[]): (typeof daemonProtocolCommands)[number] | undefined { return daemonProtocolCommands.find((entry) => entry.path.every((token, index) => args[index] === token)); }
type RpcShape = { readonly fields: Readonly<Record<string, "string" | "number" | RpcShape>>; readonly open?: boolean };
const shape = (fields: RpcShape["fields"], open = false): RpcShape => ({ fields, open });
export type DaemonGuiReadResultMap = {
  readonly "repo.tasks.list": { readonly ok: true } & import("../../../kernel/src/projection/rebuildable-task-projection.ts").TaskProjectionListRead;
  readonly "repo.triadic.relationGraph": { readonly ok: true } & ReturnType<typeof import("../../../kernel/src/projection/sqlite-task-projection.ts").readRelationGraphProjection>;
  readonly "repo.decisions.list": { readonly ok: true; readonly decisions: ReturnType<typeof import("../../../kernel/src/projection/sqlite-task-projection.ts").queryDecisionProjection>["rows"]; readonly warnings: ReturnType<typeof import("../../../kernel/src/projection/sqlite-task-projection.ts").queryDecisionProjection>["warnings"] }; readonly "repo.tasks.document.read": { readonly ok: true; readonly status: "ready" | "pending"; readonly taskId: string; readonly path: string; readonly body: string; readonly blobSha256: string | null; readonly watermark: number; readonly sourceRevision: number };
  readonly "repo.agentRuntime.overview": AgentRuntimeOverviewResult; readonly "repo.agentRuntime.sessions.read": AgentRuntimeSessionResult; readonly "repo.agentRuntime.events.read": AgentRuntimeEventsResult;
};
export type DaemonGuiReadMethod = keyof DaemonGuiReadResultMap;
export type DaemonGuiStreamResultMap = { readonly "repo.agentRuntime.attach": AgentRuntimeAttachResult }; export type DaemonGuiStreamMethod = keyof DaemonGuiStreamResultMap;
export interface DaemonProtocolErrorResult { readonly schema: "command-receipt/v2"; readonly ok: false; readonly command: string; readonly outcome: "rejected"; readonly opId: "N/A"; readonly origin: "daemon"; readonly code: string; readonly evidence: string; readonly error: { readonly code: string; readonly hint: string }; readonly nextAction: string } export const DAEMON_TASK_SNAPSHOT_LIST_SCHEMA = Object.freeze({ id: "daemon.task-snapshot-list/v1", required: Object.freeze(["ok", "status", "rows", "watermark", "sourceRevision", "warnings"]) });
export const DAEMON_RELATION_GRAPH_SCHEMA = Object.freeze({ id: "daemon.relation-graph/v1", required: Object.freeze(["ok", "edges", "coverageRows", "factAnchors", "warnings"]) }), DAEMON_DECISION_LIST_SCHEMA = Object.freeze({ id: "daemon.decision-list/v1", required: Object.freeze(["ok", "decisions", "warnings"]) }), DAEMON_DOCUMENT_READ_SCHEMA = Object.freeze({ id: "daemon.document-read/v1", required: Object.freeze(["ok", "status", "taskId", "path", "body", "blobSha256", "watermark", "sourceRevision"]) }), DAEMON_PROTOCOL_ERROR_SCHEMA = Object.freeze({ id: "daemon.protocol-error/v1", required: Object.freeze(["schema", "ok", "command", "outcome", "opId", "origin", "code", "evidence", "error", "nextAction"]) });
export const DAEMON_AGENT_RUNTIME_OVERVIEW_SCHEMA = Object.freeze({ id: "daemon.agent-runtime-overview/v1" }), DAEMON_AGENT_RUNTIME_SESSION_SCHEMA = Object.freeze({ id: "daemon.agent-runtime-session/v1" }), DAEMON_AGENT_RUNTIME_EVENTS_SCHEMA = Object.freeze({ id: "daemon.agent-runtime-events/v1" }), DAEMON_AGENT_RUNTIME_ATTACH_SCHEMA = Object.freeze({ id: "daemon.agent-runtime-attach/v1" }), DAEMON_AGENT_RUNTIME_ATTACH_EVENT_SCHEMA = Object.freeze({ id: "daemon.agent-runtime-attach-event/v1" });
export const daemonGuiReadMethods = Object.freeze([
  { id: "tasks.list", phase: "W2-GUI", method: "repo.tasks.list", requiresRepo: true, params: shape({ repo: shape({ repoId: "string" }) }), guiBridgeMethod: "getTasks", httpMethod: "GET", path: "/api/tasks", inputSchemaId: "gui.empty/v1", outputSchemaId: DAEMON_TASK_SNAPSHOT_LIST_SCHEMA.id, errorSchemaId: DAEMON_PROTOCOL_ERROR_SCHEMA.id, serviceMethod: "listTasks", auth: "local-session-token", commandClass: "repo-read" },
  { id: "triadic.relationGraph", phase: "W2-GUI", method: "repo.triadic.relationGraph", requiresRepo: true, params: shape({ repo: shape({ repoId: "string" }) }), guiBridgeMethod: "getRelationGraph", httpMethod: "GET", path: "/api/triadic/relation-graph", inputSchemaId: "gui.empty/v1", outputSchemaId: DAEMON_RELATION_GRAPH_SCHEMA.id, errorSchemaId: DAEMON_PROTOCOL_ERROR_SCHEMA.id, serviceMethod: "readRelationGraph", auth: "local-session-token", commandClass: "repo-read" },
  { id: "decisions.list", phase: "W2-GUI", method: "repo.decisions.list", requiresRepo: true, params: shape({ repo: shape({ repoId: "string" }) }), guiBridgeMethod: "getDecisions", httpMethod: "GET", path: "/api/decisions", inputSchemaId: "gui.empty/v1", outputSchemaId: DAEMON_DECISION_LIST_SCHEMA.id, errorSchemaId: DAEMON_PROTOCOL_ERROR_SCHEMA.id, serviceMethod: "listDecisions", auth: "local-session-token", commandClass: "repo-read" }, { id: "tasks.document.read", phase: "DocSync-B", method: "repo.tasks.document.read", requiresRepo: true, params: shape({ repo: shape({ repoId: "string" }), payload: shape({ taskId: "string", path: "string" }) }), guiBridgeMethod: "getTaskDocument", httpMethod: "GET", path: "/api/tasks/:taskId/documents/:path", inputSchemaId: "gui.task-document/v1", outputSchemaId: DAEMON_DOCUMENT_READ_SCHEMA.id, errorSchemaId: DAEMON_PROTOCOL_ERROR_SCHEMA.id, serviceMethod: "readDocument", auth: "local-session-token", commandClass: "repo-read" },
  { id: "agentRuntime.overview", phase: "Runtime-B", method: "repo.agentRuntime.overview", requiresRepo: true, params: shape({ repo: shape({ repoId: "string" }), payload: shape({}, true) }), guiBridgeMethod: "getAgentRuntimeOverview", httpMethod: "GET", path: "/api/agent-runtime", inputSchemaId: "gui.agent-runtime-overview/v1", outputSchemaId: DAEMON_AGENT_RUNTIME_OVERVIEW_SCHEMA.id, errorSchemaId: DAEMON_PROTOCOL_ERROR_SCHEMA.id, serviceMethod: "readAgentRuntimeOverview", auth: "local-session-token", commandClass: "repo-read" },
  { id: "agentRuntime.sessions.read", phase: "Runtime-B", method: "repo.agentRuntime.sessions.read", requiresRepo: true, params: shape({ repo: shape({ repoId: "string" }), payload: shape({ runtimeSessionId: "string" }) }), guiBridgeMethod: "getAgentRuntimeSession", httpMethod: "GET", path: "/api/agent-runtime/sessions/:id", inputSchemaId: "gui.agent-runtime-session/v1", outputSchemaId: DAEMON_AGENT_RUNTIME_SESSION_SCHEMA.id, errorSchemaId: DAEMON_PROTOCOL_ERROR_SCHEMA.id, serviceMethod: "readAgentRuntimeSession", auth: "local-session-token", commandClass: "repo-read" },
  { id: "agentRuntime.events.read", phase: "Runtime-B", method: "repo.agentRuntime.events.read", requiresRepo: true, params: shape({ repo: shape({ repoId: "string" }), payload: shape({ runtimeSessionId: "string", afterCursor: "string" }) }), guiBridgeMethod: "getAgentRuntimeEvents", httpMethod: "GET", path: "/api/agent-runtime/sessions/:id/events", inputSchemaId: "gui.agent-runtime-events/v1", outputSchemaId: DAEMON_AGENT_RUNTIME_EVENTS_SCHEMA.id, errorSchemaId: DAEMON_PROTOCOL_ERROR_SCHEMA.id, serviceMethod: "readAgentRuntimeEvents", auth: "local-session-token", commandClass: "repo-read" }
] as const satisfies ReadonlyArray<{ readonly method: DaemonGuiReadMethod; readonly [key: string]: unknown }>);
export const daemonGuiStreamFacets = Object.freeze([{ id: "agentRuntime.attach", phase: "Runtime-B", method: "repo.agentRuntime.attach", eventMethod: "repo.agentRuntime.attach.frame", requiresRepo: true, params: shape({ repo: shape({ repoId: "string" }), payload: shape({ runtimeSessionId: "string", afterCursor: "string" }) }), guiBridgeMethod: "attachAgentRuntime", httpMethod: "STREAM", path: "/api/agent-runtime/sessions/:id/attach", inputSchemaId: "gui.agent-runtime-attach/v1", outputSchemaId: DAEMON_AGENT_RUNTIME_ATTACH_SCHEMA.id, eventSchemaId: DAEMON_AGENT_RUNTIME_ATTACH_EVENT_SCHEMA.id, errorSchemaId: DAEMON_PROTOCOL_ERROR_SCHEMA.id, serviceMethod: "attachAgentRuntime", auth: "local-session-token", commandClass: "repo-read" }] as const);
const recordWith = (value: unknown, fields: readonly string[]): value is JsonObject => isJsonObject(value) && fields.every((field) => Object.hasOwn(value, field));
const nonEmpty = (value: unknown): value is string => typeof value === "string" && value.length > 0, integer = (value: unknown): value is number => Number.isInteger(value);
const stringArray = (value: unknown): value is readonly string[] => Array.isArray(value) && value.every(nonEmpty), warningArray = (value: unknown): boolean => Array.isArray(value) && value.every((warning) => recordWith(warning, ["code", "source", "severity", "message"]) && nonEmpty(warning.code) && nonEmpty(warning.source) && nonEmpty(warning.severity) && nonEmpty(warning.message));
const snapshot = (value: unknown): boolean => recordWith(value, ["revision", "task", "executions", "reviews", "edgesTaken", "lease"]) && integer(value.revision) && (value.task === null || isJsonObject(value.task)) && Array.isArray(value.executions) && Array.isArray(value.reviews) && Array.isArray(value.edgesTaken) && (value.lease === null || isJsonObject(value.lease));
export function validateDaemonTaskSnapshotList(value: unknown): readonly string[] { if (!recordWith(value, DAEMON_TASK_SNAPSHOT_LIST_SCHEMA.required) || value.ok !== true || (value.status !== "ready" && value.status !== "pending") || !integer(value.watermark) || !integer(value.sourceRevision) || !warningArray(value.warnings) || !Array.isArray(value.rows) || value.rows.some((row) => !recordWith(row, ["taskId", "workspaceRevision", "updatedAt", "snapshot"]) || !nonEmpty(row.taskId) || !integer(row.workspaceRevision) || !nonEmpty(row.updatedAt) || !snapshot(row.snapshot))) return ["daemon task snapshot list is invalid"]; return []; }
export function validateDaemonRelationGraph(value: unknown): readonly string[] { if (!recordWith(value, DAEMON_RELATION_GRAPH_SCHEMA.required) || value.ok !== true || !warningArray(value.warnings) || !Array.isArray(value.edges) || value.edges.some((edge) => !recordWith(edge, ["relationId", "sourceRef", "targetRef", "relationType", "direction", "strength", "origin", "state", "rationale", "ownerRef", "sourcePath", "recordIndex"]) || !integer(edge.recordIndex) || ["relationId", "sourceRef", "targetRef", "relationType", "direction", "strength", "origin", "state", "rationale", "ownerRef", "sourcePath"].some((field) => !nonEmpty(edge[field]))) || !Array.isArray(value.coverageRows) || value.coverageRows.some((row) => !recordWith(row, ["decisionRef", "claimRef", "status", "relationPath"]) || !nonEmpty(row.decisionRef) || !nonEmpty(row.claimRef) || (row.status !== "covered" && row.status !== "uncovered") || !stringArray(row.relationPath) || (row.coveringFactRef !== undefined && !nonEmpty(row.coveringFactRef))) || !Array.isArray(value.factAnchors) || value.factAnchors.some((row) => !recordWith(row, ["factRef", "taskId", "factId", "sourcePath"]) || ["factRef", "taskId", "factId", "sourcePath"].some((field) => !nonEmpty(row[field])))) return ["daemon relation graph is invalid"]; return []; }
export function validateDaemonDecisionList(value: unknown): readonly string[] { if (!recordWith(value, DAEMON_DECISION_LIST_SCHEMA.required) || value.ok !== true || !warningArray(value.warnings) || !Array.isArray(value.decisions) || value.decisions.some((row) => !recordWith(row, ["schema", "decisionId", "state", "title", "question", "chosen", "rejected", "path", "moduleKeys", "productLineKeys"]) || row.schema !== "d4-decision-row/v1" || ["decisionId", "state", "title", "question", "path"].some((field) => !nonEmpty(row[field])) || !stringArray(row.chosen) || !Array.isArray(row.rejected) || !stringArray(row.moduleKeys) || !stringArray(row.productLineKeys))) return ["daemon decision list is invalid"]; return []; } export function validateDaemonDocumentRead(value: unknown): readonly string[] { if (!recordWith(value, DAEMON_DOCUMENT_READ_SCHEMA.required) || value.ok !== true || (value.status !== "ready" && value.status !== "pending") || !nonEmpty(value.taskId) || !nonEmpty(value.path) || typeof value.body !== "string" || (value.blobSha256 !== null && (typeof value.blobSha256 !== "string" || !/^[0-9a-f]{64}$/u.test(value.blobSha256))) || !integer(value.watermark) || !integer(value.sourceRevision)) return ["daemon document read is invalid"]; return []; }
export function validateDaemonProtocolError(value: unknown): readonly string[] { if (!recordWith(value, DAEMON_PROTOCOL_ERROR_SCHEMA.required) || value.schema !== "command-receipt/v2" || value.ok !== false || value.outcome !== "rejected" || value.opId !== "N/A" || value.origin !== "daemon" || !recordWith(value.error, ["code", "hint"]) || [value.command, value.code, value.evidence, value.nextAction, value.error.code, value.error.hint].some((item) => !nonEmpty(item)) || value.code !== value.error.code) return ["daemon protocol error is invalid"]; return []; }
type ResultValidator = (value: unknown) => readonly string[];
const resultValidators = { "repo.tasks.list": validateDaemonTaskSnapshotList, "repo.triadic.relationGraph": validateDaemonRelationGraph, "repo.decisions.list": validateDaemonDecisionList, "repo.tasks.document.read": validateDaemonDocumentRead, "repo.agentRuntime.overview": validateAgentRuntimeOverview, "repo.agentRuntime.sessions.read": validateAgentRuntimeSession, "repo.agentRuntime.events.read": validateAgentRuntimeEvents } satisfies Record<DaemonGuiReadMethod, ResultValidator>;
export function parseDaemonGuiReadResult<M extends DaemonGuiReadMethod>(method: M, value: unknown): DaemonGuiReadResultMap[M] { const errors = resultValidators[method](value); if (errors.length) throw new DaemonProtocolContractError("invalid_result", errors.join("; ")); return value as DaemonGuiReadResultMap[M]; }
export function parseDaemonGuiReadResponse<M extends DaemonGuiReadMethod>(method: M, value: unknown): DaemonGuiReadResultMap[M] | DaemonProtocolErrorResult { const errors = isJsonObject(value) && value.ok === false ? validateDaemonProtocolError(value) : resultValidators[method](value); if (errors.length) throw new DaemonProtocolContractError("invalid_result", errors.join("; ")); return value as DaemonGuiReadResultMap[M] | DaemonProtocolErrorResult; }
export function parseDaemonGuiStreamResult<M extends DaemonGuiStreamMethod>(method: M, value: unknown): DaemonGuiStreamResultMap[M] { const errors = method === "repo.agentRuntime.attach" ? validateAgentRuntimeAttach(value) : ["unknown stream facet"]; if (errors.length) throw new DaemonProtocolContractError("invalid_result", errors.join("; ")); return value as DaemonGuiStreamResultMap[M]; } export function parseDaemonGuiStreamEvent(value: unknown): AgentRuntimeAttachEvent { const errors = validateAgentRuntimeAttachEvent(value); if (errors.length) throw new DaemonProtocolContractError("invalid_result", errors.join("; ")); return value as AgentRuntimeAttachEvent; }
function serializeSchema(value: unknown, validate: ResultValidator): string { const errors = validate(value); if (errors.length) throw new DaemonProtocolContractError("invalid_result", errors.join("; ")); return `${JSON.stringify(value)}\n`; }
export const serializeDaemonTaskSnapshotList = (value: unknown): string => serializeSchema(value, validateDaemonTaskSnapshotList), serializeDaemonRelationGraph = (value: unknown): string => serializeSchema(value, validateDaemonRelationGraph), serializeDaemonDecisionList = (value: unknown): string => serializeSchema(value, validateDaemonDecisionList), serializeDaemonDocumentRead = (value: unknown): string => serializeSchema(value, validateDaemonDocumentRead), serializeDaemonProtocolError = (value: unknown): string => serializeSchema(value, validateDaemonProtocolError);
export function daemonProtocolError(command: string, code: string, hint: string): DaemonProtocolErrorResult { return { schema: "command-receipt/v2", ok: false, command, outcome: "rejected", opId: "N/A", origin: "daemon", code, evidence: `rejection:${code}`, error: { code, hint }, nextAction: hint }; }
export const daemonProtocolMethods = Object.freeze([
  { id: "protocol.hello", phase: "W3", method: "protocol.hello", requiresRepo: false, params: shape({ protocolVersion: "number" }) }, { id: "daemon.status", phase: "W3", method: "daemon.status", requiresRepo: false, params: shape({}) }, { id: "daemon.repo.bootstrap", phase: "W3", method: "daemon.repo.bootstrap", requiresRepo: false, params: shape({ rootDir: "string", repoId: "string", personId: "string", displayName: "string" }) }, { id: "daemon.repo.register", phase: "W3", method: "daemon.repo.register", requiresRepo: false, params: shape({ rootDir: "string", repoId: "string" }) }, { id: "daemon.repo.unregister", phase: "W3", method: "daemon.repo.unregister", requiresRepo: false, params: shape({ repoId: "string" }) },
  { id: "repo.task.run", phase: "W3", method: "repo.task.run", requiresRepo: true, params: shape({ repo: shape({ repoId: "string" }), payload: shape({ action: shape({ kind: "string" }, true) }) }) }
] as const);
const allDaemonProtocolMethods = Object.freeze([...daemonProtocolMethods, ...daemonGuiReadMethods, ...daemonGuiStreamFacets]);
export const jsonRpcMethodContracts = Object.freeze(allDaemonProtocolMethods.map(({ method, requiresRepo }) => ({ method, requiresRepo })));
export function isDaemonGuiReadMethod(method: string): method is DaemonGuiReadMethod { return daemonGuiReadMethods.some((entry) => entry.method === method); }
export function isDaemonGuiStreamMethod(method: string): method is DaemonGuiStreamMethod { return daemonGuiStreamFacets.some((entry) => entry.method === method); }
export function validateDaemonRpcCall(value: unknown): readonly string[] { if (!isJsonObject(value) || typeof value.method !== "string") return ["RPC method is required"]; const method = allDaemonProtocolMethods.find((entry) => entry.method === value.method); if (!method) return ["RPC method is not contracted"];
  return validateShape(value.params === undefined ? {} : value.params, method.params, "params"); }
export function parseDaemonRpcParams(method: string, params: unknown): { readonly ok: true; readonly params: JsonObject } | { readonly ok: false; readonly errors: readonly string[] } { const candidateParams = params === undefined ? {} : params, errors = validateDaemonRpcCall({ method, params: candidateParams });
  return errors.length ? { ok: false, errors } : { ok: true, params: candidateParams as JsonObject }; }
function validateShape(value: unknown, expected: RpcShape, prefix: string): string[] { if (!isJsonObject(value)) return [`${prefix} must be an object`]; const errors: string[] = []; if (!expected.open) for (const field of Object.keys(value)) if (!Object.hasOwn(expected.fields, field)) errors.push(`${prefix}.${field} is not allowed`);
  for (const [field, rule] of Object.entries(expected.fields)) { const item = value[field]; if (rule === "string" || rule === "number") { if (typeof item !== rule || (rule === "string" && !item)) errors.push(`${prefix}.${field} must be ${rule}`); }
    else errors.push(...validateShape(item, rule, `${prefix}.${field}`)); } return errors; }
export const DAEMON_RPC_SCHEMA = Object.freeze({ id: "w3-daemon-rpc/v1", methods: allDaemonProtocolMethods.map(({ method, params }) => ({ method, params })) });
export function serializeDaemonRpcCall(value: unknown): string { const errors = validateDaemonRpcCall(value); if (errors.length) throw new DaemonProtocolContractError("invalid_rpc", errors.join("; ")); return `${JSON.stringify(value)}\n`; }
export class DaemonProtocolContractError extends Error { readonly code: string; constructor(code: string, message: string) { super(message); this.name = "DaemonProtocolContractError"; this.code = code; } }
export const daemonGuiReadSchemas = Object.freeze([{ id: DAEMON_TASK_SNAPSHOT_LIST_SCHEMA.id, schema: "packages/daemon/src/protocol/daemon-protocol.contract.ts#DAEMON_TASK_SNAPSHOT_LIST_SCHEMA", parser: "packages/daemon/src/protocol/daemon-protocol.contract.ts#validateDaemonTaskSnapshotList", writer: "packages/daemon/src/protocol/daemon-protocol.contract.ts#serializeDaemonTaskSnapshotList", error: "packages/daemon/src/protocol/daemon-protocol.contract.ts#DaemonProtocolContractError", negativeFixtures: Object.freeze(["packages/daemon/fixtures/contracts/daemon-task-snapshot-list-invalid.json"]) },
  { id: DAEMON_RELATION_GRAPH_SCHEMA.id, schema: "packages/daemon/src/protocol/daemon-protocol.contract.ts#DAEMON_RELATION_GRAPH_SCHEMA", parser: "packages/daemon/src/protocol/daemon-protocol.contract.ts#validateDaemonRelationGraph", writer: "packages/daemon/src/protocol/daemon-protocol.contract.ts#serializeDaemonRelationGraph", error: "packages/daemon/src/protocol/daemon-protocol.contract.ts#DaemonProtocolContractError", negativeFixtures: Object.freeze(["packages/daemon/fixtures/contracts/daemon-relation-graph-invalid.json"]) },
  { id: DAEMON_DECISION_LIST_SCHEMA.id, schema: "packages/daemon/src/protocol/daemon-protocol.contract.ts#DAEMON_DECISION_LIST_SCHEMA", parser: "packages/daemon/src/protocol/daemon-protocol.contract.ts#validateDaemonDecisionList", writer: "packages/daemon/src/protocol/daemon-protocol.contract.ts#serializeDaemonDecisionList", error: "packages/daemon/src/protocol/daemon-protocol.contract.ts#DaemonProtocolContractError", negativeFixtures: Object.freeze(["packages/daemon/fixtures/contracts/daemon-decision-list-invalid.json"]) },
  { id: DAEMON_DOCUMENT_READ_SCHEMA.id, schema: "packages/daemon/src/protocol/daemon-protocol.contract.ts#DAEMON_DOCUMENT_READ_SCHEMA", parser: "packages/daemon/src/protocol/daemon-protocol.contract.ts#validateDaemonDocumentRead", writer: "packages/daemon/src/protocol/daemon-protocol.contract.ts#serializeDaemonDocumentRead", error: "packages/daemon/src/protocol/daemon-protocol.contract.ts#DaemonProtocolContractError", negativeFixtures: Object.freeze(["packages/daemon/fixtures/contracts/daemon-document-read-invalid.json"]) }, { id: DAEMON_PROTOCOL_ERROR_SCHEMA.id, schema: "packages/daemon/src/protocol/daemon-protocol.contract.ts#DAEMON_PROTOCOL_ERROR_SCHEMA", parser: "packages/daemon/src/protocol/daemon-protocol.contract.ts#validateDaemonProtocolError", writer: "packages/daemon/src/protocol/daemon-protocol.contract.ts#serializeDaemonProtocolError", error: "packages/daemon/src/protocol/daemon-protocol.contract.ts#DaemonProtocolContractError", negativeFixtures: Object.freeze(["packages/daemon/fixtures/contracts/daemon-protocol-error-invalid.json"]) },
  { id: DAEMON_AGENT_RUNTIME_OVERVIEW_SCHEMA.id, schema: "packages/daemon/src/protocol/daemon-protocol.contract.ts#DAEMON_AGENT_RUNTIME_OVERVIEW_SCHEMA", parser: "packages/daemon/src/agent-runtime-read.ts#validateAgentRuntimeOverview", writer: "packages/daemon/src/agent-runtime-read.ts#serializeAgentRuntimeOverview", error: "packages/daemon/src/protocol/daemon-protocol.contract.ts#DaemonProtocolContractError", negativeFixtures: Object.freeze(["packages/daemon/fixtures/contracts/daemon-agent-runtime-overview-invalid.json"]) }, { id: DAEMON_AGENT_RUNTIME_SESSION_SCHEMA.id, schema: "packages/daemon/src/protocol/daemon-protocol.contract.ts#DAEMON_AGENT_RUNTIME_SESSION_SCHEMA", parser: "packages/daemon/src/agent-runtime-read.ts#validateAgentRuntimeSession", writer: "packages/daemon/src/agent-runtime-read.ts#serializeAgentRuntimeSession", error: "packages/daemon/src/protocol/daemon-protocol.contract.ts#DaemonProtocolContractError", negativeFixtures: Object.freeze(["packages/daemon/fixtures/contracts/daemon-agent-runtime-session-invalid.json"]) },
  { id: DAEMON_AGENT_RUNTIME_EVENTS_SCHEMA.id, schema: "packages/daemon/src/protocol/daemon-protocol.contract.ts#DAEMON_AGENT_RUNTIME_EVENTS_SCHEMA", parser: "packages/daemon/src/agent-runtime-read.ts#validateAgentRuntimeEvents", writer: "packages/daemon/src/agent-runtime-read.ts#serializeAgentRuntimeEvents", error: "packages/daemon/src/protocol/daemon-protocol.contract.ts#DaemonProtocolContractError", negativeFixtures: Object.freeze(["packages/daemon/fixtures/contracts/daemon-agent-runtime-events-invalid.json"]) }, { id: DAEMON_AGENT_RUNTIME_ATTACH_SCHEMA.id, schema: "packages/daemon/src/protocol/daemon-protocol.contract.ts#DAEMON_AGENT_RUNTIME_ATTACH_SCHEMA", parser: "packages/daemon/src/agent-runtime-stream.ts#validateAgentRuntimeAttach", writer: "packages/daemon/src/agent-runtime-stream.ts#serializeAgentRuntimeAttach", error: "packages/daemon/src/protocol/daemon-protocol.contract.ts#DaemonProtocolContractError", negativeFixtures: Object.freeze(["packages/daemon/fixtures/contracts/daemon-agent-runtime-attach-invalid.json"]) }, { id: DAEMON_AGENT_RUNTIME_ATTACH_EVENT_SCHEMA.id, schema: "packages/daemon/src/protocol/daemon-protocol.contract.ts#DAEMON_AGENT_RUNTIME_ATTACH_EVENT_SCHEMA", parser: "packages/daemon/src/agent-runtime-stream.ts#validateAgentRuntimeAttachEvent", writer: "packages/daemon/src/agent-runtime-stream.ts#serializeAgentRuntimeAttachEvent", error: "packages/daemon/src/protocol/daemon-protocol.contract.ts#DaemonProtocolContractError", negativeFixtures: Object.freeze(["packages/daemon/fixtures/contracts/daemon-agent-runtime-attach-event-invalid.json"]) }]);
export default Object.freeze({ id: "w3-daemon-protocol", phases: Object.freeze(["W3", "W2-GUI", "DocSync-B", "Runtime-B"]), commands: daemonProtocolCommands, methods: allDaemonProtocolMethods, gates: Object.freeze([]), guards: Object.freeze([]), schemas: Object.freeze([{ id: DAEMON_RPC_SCHEMA.id,
    schema: "packages/daemon/src/protocol/daemon-protocol.contract.ts#DAEMON_RPC_SCHEMA", parser: "packages/daemon/src/protocol/daemon-protocol.contract.ts#validateDaemonRpcCall", writer: "packages/daemon/src/protocol/daemon-protocol.contract.ts#serializeDaemonRpcCall", error: "packages/daemon/src/protocol/daemon-protocol.contract.ts#DaemonProtocolContractError",
    negativeFixtures: Object.freeze(["packages/daemon/fixtures/contracts/w3-daemon-rpc-invalid.json"]) }, ...daemonGuiReadSchemas]) });
