import {
  CATALOG_REREAD_RECEIPT_SCHEMA,
  DAEMON_AGENDA_SCHEMA,
  DAEMON_AGENT_ENTITY_CATALOG_SCHEMA,
  DAEMON_AGENT_ENTITY_DETAIL_SCHEMA,
  DAEMON_AGENT_RUNTIME_ATTACH_EVENT_SCHEMA,
  DAEMON_AGENT_RUNTIME_ATTACH_SCHEMA,
  DAEMON_AGENT_RUNTIME_EVENTS_SCHEMA,
  DAEMON_AGENT_RUNTIME_OVERVIEW_SCHEMA,
  DAEMON_AGENT_RUNTIME_SESSION_GROUPS_SCHEMA,
  DAEMON_AGENT_RUNTIME_SESSION_SCHEMA,
  DAEMON_AGENT_SKILL_CATALOG_SCHEMA,
  DAEMON_CONTROL_RECEIPT_SCHEMA,
  DAEMON_CI_OBSERVATORY_SCHEMA,
  DAEMON_DECISION_LIST_SCHEMA,
  DAEMON_DOCUMENT_READ_SCHEMA,
  DAEMON_OBSERVE_TAIL_SCHEMA,
  DAEMON_GUI_COMMAND_RECEIPT_SCHEMA,
  DAEMON_PROTOCOL_ERROR_SCHEMA,
  DAEMON_RELATION_GRAPH_SCHEMA,
  DAEMON_SCHEDULES_LIST_SCHEMA,
  DAEMON_SQUAD_ENTITY_CATALOG_SCHEMA,
  DAEMON_SQUAD_ENTITY_DETAIL_SCHEMA,
  DAEMON_SQUAD_RUN_LIST_SCHEMA,
  DAEMON_SQUAD_RUN_READ_SCHEMA,
  DAEMON_TASK_DISPATCHES_SCHEMA,
  DAEMON_TASK_DOCUMENT_LIST_SCHEMA,
  DAEMON_TASK_SNAPSHOT_LIST_SCHEMA,
  DAEMON_WORKSPACE_SUMMARY_SCHEMA,
  GUI_CATALOG_PRESET_SCHEMA,
  GUI_CATALOG_SNAPSHOT_SCHEMA,
  GUI_SYSTEM_STATUS_SCHEMA,
  TERMINAL_ATTACH_EVENT_SCHEMA,
  TERMINAL_ATTACH_SCHEMA,
  TERMINAL_CONTROL_RECEIPT_SCHEMA,
  TERMINAL_DETACH_ACK_SCHEMA,
  TERMINAL_INPUT_ACK_SCHEMA,
  TERMINAL_SESSION_LIST_SCHEMA,
} from "./daemon-protocol-schema-ids.ts";

export const daemonGuiReadSchemas = Object.freeze([
  {
    id: DAEMON_CI_OBSERVATORY_SCHEMA.id,
    schema: "packages/daemon/src/protocol/daemon-protocol-schema-ids.ts#DAEMON_CI_OBSERVATORY_SCHEMA",
    parser: "packages/daemon/src/ci-observatory-read.ts#validateCiObservatoryRead",
    writer: "packages/daemon/src/ci-observatory-read.ts#serializeCiObservatoryRead",
    error: "packages/daemon/src/ci-observatory-read.ts#CiObservatoryContractError",
    negativeFixtures: Object.freeze(["packages/daemon/fixtures/contracts/daemon-ci-observatory-invalid.json"]),
  },
  {
    id: GUI_SYSTEM_STATUS_SCHEMA.id,
    schema: "packages/daemon/src/protocol/daemon-protocol.contract.ts#GUI_SYSTEM_STATUS_SCHEMA",
    parser: "packages/daemon/src/gui-s3-control.ts#validateSystemStatus",
    writer: "packages/daemon/src/gui-s3-control.ts#writeSystemStatus",
    error: "packages/daemon/src/gui-s3-control.ts#GuiS3ContractError",
    negativeFixtures: Object.freeze(["packages/daemon/fixtures/contracts/gui-system-status-invalid.json"]),
  },
  {
    id: DAEMON_CONTROL_RECEIPT_SCHEMA.id,
    schema: "packages/daemon/src/protocol/daemon-protocol.contract.ts#DAEMON_CONTROL_RECEIPT_SCHEMA",
    parser: "packages/daemon/src/gui-s3-control.ts#validateDaemonControlReceipt",
    writer: "packages/daemon/src/gui-s3-control.ts#writeDaemonControlReceipt",
    error: "packages/daemon/src/gui-s3-control.ts#GuiS3ContractError",
    negativeFixtures: Object.freeze(["packages/daemon/fixtures/contracts/daemon-control-receipt-invalid.json"]),
  },
  {
    id: DAEMON_OBSERVE_TAIL_SCHEMA.id,
    schema: "packages/daemon/src/protocol/daemon-protocol-schema-ids.ts#DAEMON_OBSERVE_TAIL_SCHEMA",
    parser: "packages/daemon/src/protocol/daemon-protocol.contract.ts#validateObserveTailResult",
    writer: "packages/daemon/src/protocol/daemon-protocol.contract.ts#serializeObserveTailResult",
    error: "packages/daemon/src/protocol/daemon-protocol.contract.ts#DaemonProtocolContractError",
    negativeFixtures: Object.freeze(["packages/daemon/fixtures/contracts/daemon-observe-tail-invalid.json"]),
  },
  {
    id: GUI_CATALOG_SNAPSHOT_SCHEMA.id,
    schema: "packages/daemon/src/protocol/daemon-protocol.contract.ts#GUI_CATALOG_SNAPSHOT_SCHEMA",
    parser: "packages/daemon/src/gui-s3-control.ts#validateCatalogSnapshot",
    writer: "packages/daemon/src/gui-s3-control.ts#writeCatalogSnapshot",
    error: "packages/daemon/src/gui-s3-control.ts#GuiS3ContractError",
    negativeFixtures: Object.freeze(["packages/daemon/fixtures/contracts/gui-catalog-snapshot-invalid.json"]),
  },
  {
    id: GUI_CATALOG_PRESET_SCHEMA.id,
    schema: "packages/daemon/src/protocol/daemon-protocol.contract.ts#GUI_CATALOG_PRESET_SCHEMA",
    parser: "packages/daemon/src/gui-s3-control.ts#validateCatalogPreset",
    writer: "packages/daemon/src/gui-s3-control.ts#writeCatalogPreset",
    error: "packages/daemon/src/gui-s3-control.ts#GuiS3ContractError",
    negativeFixtures: Object.freeze(["packages/daemon/fixtures/contracts/gui-catalog-preset-invalid.json"]),
  },
  {
    id: TERMINAL_SESSION_LIST_SCHEMA.id,
    schema: "packages/daemon/src/protocol/daemon-protocol.contract.ts#TERMINAL_SESSION_LIST_SCHEMA",
    parser: "packages/daemon/src/gui-s3-control.ts#validateTerminalSessionList",
    writer: "packages/daemon/src/gui-s3-control.ts#writeTerminalSessionList",
    error: "packages/daemon/src/gui-s3-control.ts#GuiS3ContractError",
    negativeFixtures: Object.freeze(["packages/daemon/fixtures/contracts/terminal-session-list-invalid.json"]),
  },
  {
    id: DAEMON_TASK_SNAPSHOT_LIST_SCHEMA.id,
    schema: "packages/daemon/src/protocol/daemon-protocol.contract.ts#DAEMON_TASK_SNAPSHOT_LIST_SCHEMA",
    parser: "packages/daemon/src/protocol/daemon-protocol.contract.ts#validateDaemonTaskSnapshotList",
    writer: "packages/daemon/src/protocol/daemon-protocol.contract.ts#serializeDaemonTaskSnapshotList",
    error: "packages/daemon/src/protocol/daemon-protocol.contract.ts#DaemonProtocolContractError",
    negativeFixtures: Object.freeze(["packages/daemon/fixtures/contracts/daemon-task-snapshot-list-invalid.json"]),
  },
  {
    id: DAEMON_WORKSPACE_SUMMARY_SCHEMA.id,
    schema: "packages/daemon/src/protocol/daemon-protocol.contract.ts#DAEMON_WORKSPACE_SUMMARY_SCHEMA",
    parser: "packages/daemon/src/protocol/daemon-protocol.contract.ts#validateDaemonWorkspaceSummary",
    writer: "packages/daemon/src/protocol/daemon-protocol.contract.ts#serializeDaemonWorkspaceSummary",
    error: "packages/daemon/src/protocol/daemon-protocol.contract.ts#DaemonProtocolContractError",
    negativeFixtures: Object.freeze(["packages/daemon/fixtures/contracts/daemon-workspace-summary-invalid.json"]),
  },
  {
    id: DAEMON_AGENDA_SCHEMA.id,
    schema: "packages/daemon/src/protocol/daemon-protocol.contract.ts#DAEMON_AGENDA_SCHEMA",
    parser: "packages/daemon/src/protocol/daemon-protocol.contract.ts#validateDaemonAgenda",
    writer: "packages/daemon/src/protocol/daemon-protocol.contract.ts#serializeDaemonAgenda",
    error: "packages/daemon/src/protocol/daemon-protocol.contract.ts#DaemonProtocolContractError",
    negativeFixtures: Object.freeze(["packages/daemon/fixtures/contracts/daemon-agenda-invalid.json"]),
  },
  {
    id: DAEMON_RELATION_GRAPH_SCHEMA.id,
    schema: "packages/daemon/src/protocol/daemon-protocol.contract.ts#DAEMON_RELATION_GRAPH_SCHEMA",
    parser: "packages/daemon/src/protocol/daemon-protocol.contract.ts#validateDaemonRelationGraph",
    writer: "packages/daemon/src/protocol/daemon-protocol.contract.ts#serializeDaemonRelationGraph",
    error: "packages/daemon/src/protocol/daemon-protocol.contract.ts#DaemonProtocolContractError",
    negativeFixtures: Object.freeze(["packages/daemon/fixtures/contracts/daemon-relation-graph-invalid.json"]),
  },
  {
    id: DAEMON_DECISION_LIST_SCHEMA.id,
    schema: "packages/daemon/src/protocol/daemon-protocol.contract.ts#DAEMON_DECISION_LIST_SCHEMA",
    parser: "packages/daemon/src/protocol/daemon-protocol.contract.ts#validateDaemonDecisionList",
    writer: "packages/daemon/src/protocol/daemon-protocol.contract.ts#serializeDaemonDecisionList",
    error: "packages/daemon/src/protocol/daemon-protocol.contract.ts#DaemonProtocolContractError",
    negativeFixtures: Object.freeze(["packages/daemon/fixtures/contracts/daemon-decision-list-invalid.json"]),
  },
  {
    id: DAEMON_DOCUMENT_READ_SCHEMA.id,
    schema: "packages/daemon/src/protocol/daemon-protocol.contract.ts#DAEMON_DOCUMENT_READ_SCHEMA",
    parser: "packages/daemon/src/protocol/daemon-protocol.contract.ts#validateDaemonDocumentRead",
    writer: "packages/daemon/src/protocol/daemon-protocol.contract.ts#serializeDaemonDocumentRead",
    error: "packages/daemon/src/protocol/daemon-protocol.contract.ts#DaemonProtocolContractError",
    negativeFixtures: Object.freeze(["packages/daemon/fixtures/contracts/daemon-document-read-invalid.json"]),
  },
  {
    id: DAEMON_TASK_DOCUMENT_LIST_SCHEMA.id,
    schema: "packages/daemon/src/protocol/daemon-protocol.contract.ts#DAEMON_TASK_DOCUMENT_LIST_SCHEMA",
    parser: "packages/daemon/src/protocol/daemon-protocol.contract.ts#validateDaemonTaskDocumentList",
    writer: "packages/daemon/src/protocol/daemon-protocol.contract.ts#serializeDaemonTaskDocumentList",
    error: "packages/daemon/src/protocol/daemon-protocol.contract.ts#DaemonProtocolContractError",
    negativeFixtures: Object.freeze(["packages/daemon/fixtures/contracts/daemon-task-document-list-invalid.json"]),
  },
  {
    id: DAEMON_PROTOCOL_ERROR_SCHEMA.id,
    schema: "packages/daemon/src/protocol/daemon-protocol.contract.ts#DAEMON_PROTOCOL_ERROR_SCHEMA",
    parser: "packages/daemon/src/protocol/daemon-protocol.contract.ts#validateDaemonProtocolError",
    writer: "packages/daemon/src/protocol/daemon-protocol.contract.ts#serializeDaemonProtocolError",
    error: "packages/daemon/src/protocol/daemon-protocol.contract.ts#DaemonProtocolContractError",
    negativeFixtures: Object.freeze(["packages/daemon/fixtures/contracts/daemon-protocol-error-invalid.json"]),
  },
  {
    id: DAEMON_TASK_DISPATCHES_SCHEMA.id,
    schema: "packages/daemon/src/protocol/daemon-protocol.contract.ts#DAEMON_TASK_DISPATCHES_SCHEMA",
    parser: "packages/daemon/src/protocol/daemon-protocol.contract.ts#validateDaemonTaskDispatches",
    writer: "packages/daemon/src/protocol/daemon-protocol.contract.ts#serializeDaemonTaskDispatches",
    error: "packages/daemon/src/protocol/daemon-protocol.contract.ts#DaemonProtocolContractError",
    negativeFixtures: Object.freeze(["packages/daemon/fixtures/contracts/daemon-task-dispatches-invalid.json"]),
  },
  {
    id: DAEMON_AGENT_RUNTIME_OVERVIEW_SCHEMA.id,
    schema: "packages/daemon/src/protocol/daemon-protocol.contract.ts#DAEMON_AGENT_RUNTIME_OVERVIEW_SCHEMA",
    parser: "packages/daemon/src/agent-runtime-contract.ts#validateAgentRuntimeOverview",
    writer: "packages/daemon/src/agent-runtime-contract.ts#serializeAgentRuntimeOverview",
    error: "packages/daemon/src/protocol/daemon-protocol.contract.ts#DaemonProtocolContractError",
    negativeFixtures: Object.freeze([
      "packages/daemon/fixtures/contracts/daemon-agent-runtime-overview-invalid.json",
      "packages/daemon/fixtures/contracts/daemon-agent-runtime-overview-profiles-invalid.json",
    ]),
  },
  {
    id: DAEMON_AGENT_RUNTIME_SESSION_GROUPS_SCHEMA.id,
    schema: "packages/daemon/src/protocol/daemon-protocol.contract.ts#DAEMON_AGENT_RUNTIME_SESSION_GROUPS_SCHEMA",
    parser: "packages/daemon/src/agent-runtime-contract.ts#validateAgentRuntimeSessionGroups",
    writer: "packages/daemon/src/agent-runtime-contract.ts#serializeAgentRuntimeSessionGroups",
    error: "packages/daemon/src/protocol/daemon-protocol.contract.ts#DaemonProtocolContractError",
    negativeFixtures: Object.freeze([
      "packages/daemon/fixtures/contracts/daemon-agent-runtime-session-groups-invalid.json",
    ]),
  },
  {
    id: DAEMON_AGENT_RUNTIME_SESSION_SCHEMA.id,
    schema: "packages/daemon/src/protocol/daemon-protocol.contract.ts#DAEMON_AGENT_RUNTIME_SESSION_SCHEMA",
    parser: "packages/daemon/src/agent-runtime-contract.ts#validateAgentRuntimeSession",
    writer: "packages/daemon/src/agent-runtime-contract.ts#serializeAgentRuntimeSession",
    error: "packages/daemon/src/protocol/daemon-protocol.contract.ts#DaemonProtocolContractError",
    negativeFixtures: Object.freeze(["packages/daemon/fixtures/contracts/daemon-agent-runtime-session-invalid.json"]),
  },
  {
    id: DAEMON_AGENT_RUNTIME_EVENTS_SCHEMA.id,
    schema: "packages/daemon/src/protocol/daemon-protocol.contract.ts#DAEMON_AGENT_RUNTIME_EVENTS_SCHEMA",
    parser: "packages/daemon/src/agent-runtime-contract.ts#validateAgentRuntimeEvents",
    writer: "packages/daemon/src/agent-runtime-contract.ts#serializeAgentRuntimeEvents",
    error: "packages/daemon/src/protocol/daemon-protocol.contract.ts#DaemonProtocolContractError",
    negativeFixtures: Object.freeze(["packages/daemon/fixtures/contracts/daemon-agent-runtime-events-invalid.json"]),
  },
  {
    id: DAEMON_AGENT_RUNTIME_ATTACH_SCHEMA.id,
    schema: "packages/daemon/src/protocol/daemon-protocol.contract.ts#DAEMON_AGENT_RUNTIME_ATTACH_SCHEMA",
    parser: "packages/daemon/src/agent-runtime-stream.ts#validateAgentRuntimeAttach",
    writer: "packages/daemon/src/agent-runtime-stream.ts#serializeAgentRuntimeAttach",
    error: "packages/daemon/src/protocol/daemon-protocol.contract.ts#DaemonProtocolContractError",
    negativeFixtures: Object.freeze(["packages/daemon/fixtures/contracts/daemon-agent-runtime-attach-invalid.json"]),
  },
  {
    id: DAEMON_AGENT_RUNTIME_ATTACH_EVENT_SCHEMA.id,
    schema: "packages/daemon/src/protocol/daemon-protocol.contract.ts#DAEMON_AGENT_RUNTIME_ATTACH_EVENT_SCHEMA",
    parser: "packages/daemon/src/agent-runtime-stream.ts#validateAgentRuntimeAttachEvent",
    writer: "packages/daemon/src/agent-runtime-stream.ts#serializeAgentRuntimeAttachEvent",
    error: "packages/daemon/src/protocol/daemon-protocol.contract.ts#DaemonProtocolContractError",
    negativeFixtures: Object.freeze([
      "packages/daemon/fixtures/contracts/daemon-agent-runtime-attach-event-invalid.json",
    ]),
  },
  {
    id: DAEMON_AGENT_ENTITY_CATALOG_SCHEMA.id,
    schema: "packages/daemon/src/protocol/daemon-protocol.contract.ts#DAEMON_AGENT_ENTITY_CATALOG_SCHEMA",
    parser: "packages/daemon/src/agent-entities.contract.ts#validateAgentEntityCatalog",
    writer: "packages/daemon/src/agent-entities.contract.ts#serializeAgentEntityCatalog",
    error: "packages/daemon/src/protocol/daemon-protocol.contract.ts#DaemonProtocolContractError",
    negativeFixtures: Object.freeze(["packages/daemon/fixtures/contracts/daemon-agent-entity-catalog-invalid.json"]),
  },
  {
    id: DAEMON_AGENT_ENTITY_DETAIL_SCHEMA.id,
    schema: "packages/daemon/src/protocol/daemon-protocol.contract.ts#DAEMON_AGENT_ENTITY_DETAIL_SCHEMA",
    parser: "packages/daemon/src/agent-entities.contract.ts#validateAgentEntityDetail",
    writer: "packages/daemon/src/agent-entities.contract.ts#serializeAgentEntityDetail",
    error: "packages/daemon/src/protocol/daemon-protocol.contract.ts#DaemonProtocolContractError",
    negativeFixtures: Object.freeze(["packages/daemon/fixtures/contracts/daemon-agent-entity-detail-invalid.json"]),
  },
  {
    id: DAEMON_AGENT_SKILL_CATALOG_SCHEMA.id,
    schema: "packages/daemon/src/protocol/daemon-protocol.contract.ts#DAEMON_AGENT_SKILL_CATALOG_SCHEMA",
    parser: "packages/daemon/src/agent-entities.contract.ts#validateAgentSkillCatalog",
    writer: "packages/daemon/src/agent-entities.contract.ts#serializeAgentSkillCatalog",
    error: "packages/daemon/src/protocol/daemon-protocol.contract.ts#DaemonProtocolContractError",
    negativeFixtures: Object.freeze(["packages/daemon/fixtures/contracts/daemon-agent-skill-catalog-invalid.json"]),
  },
  {
    id: DAEMON_SQUAD_ENTITY_CATALOG_SCHEMA.id,
    schema: "packages/daemon/src/protocol/daemon-protocol.contract.ts#DAEMON_SQUAD_ENTITY_CATALOG_SCHEMA",
    parser: "packages/daemon/src/agent-entities.contract.ts#validateSquadEntityCatalog",
    writer: "packages/daemon/src/agent-entities.contract.ts#serializeSquadEntityCatalog",
    error: "packages/daemon/src/protocol/daemon-protocol.contract.ts#DaemonProtocolContractError",
    negativeFixtures: Object.freeze(["packages/daemon/fixtures/contracts/daemon-squad-entity-catalog-invalid.json"]),
  },
  {
    id: DAEMON_SQUAD_ENTITY_DETAIL_SCHEMA.id,
    schema: "packages/daemon/src/protocol/daemon-protocol.contract.ts#DAEMON_SQUAD_ENTITY_DETAIL_SCHEMA",
    parser: "packages/daemon/src/agent-entities.contract.ts#validateSquadEntityDetail",
    writer: "packages/daemon/src/agent-entities.contract.ts#serializeSquadEntityDetail",
    error: "packages/daemon/src/protocol/daemon-protocol.contract.ts#DaemonProtocolContractError",
    negativeFixtures: Object.freeze(["packages/daemon/fixtures/contracts/daemon-squad-entity-detail-invalid.json"]),
  },
  {
    id: DAEMON_SQUAD_RUN_LIST_SCHEMA.id,
    schema: "packages/daemon/src/protocol/daemon-protocol.contract.ts#DAEMON_SQUAD_RUN_LIST_SCHEMA",
    parser: "packages/daemon/src/squad-run-contract.ts#validateSquadRunsList",
    writer: "packages/daemon/src/squad-run-contract.ts#serializeSquadRunsList",
    error: "packages/daemon/src/protocol/daemon-protocol.contract.ts#DaemonProtocolContractError",
    negativeFixtures: Object.freeze(["packages/daemon/fixtures/contracts/daemon-squad-run-list-invalid.json"]),
  },
  {
    id: DAEMON_SQUAD_RUN_READ_SCHEMA.id,
    schema: "packages/daemon/src/protocol/daemon-protocol.contract.ts#DAEMON_SQUAD_RUN_READ_SCHEMA",
    parser: "packages/daemon/src/squad-run-contract.ts#validateSquadRunRead",
    writer: "packages/daemon/src/squad-run-contract.ts#serializeSquadRunRead",
    error: "packages/daemon/src/protocol/daemon-protocol.contract.ts#DaemonProtocolContractError",
    negativeFixtures: Object.freeze(["packages/daemon/fixtures/contracts/daemon-squad-run-read-invalid.json"]),
  },
  {
    id: DAEMON_SCHEDULES_LIST_SCHEMA.id,
    schema: "packages/daemon/src/protocol/daemon-protocol-schema-ids.ts#DAEMON_SCHEDULES_LIST_SCHEMA",
    parser: "packages/daemon/src/protocol/schedules-gui-contract.ts#validateSchedulesList",
    writer: "packages/daemon/src/protocol/schedules-gui-contract.ts#serializeSchedulesList",
    error: "packages/daemon/src/protocol/daemon-protocol.contract.ts#DaemonProtocolContractError",
    negativeFixtures: Object.freeze(["packages/daemon/fixtures/contracts/daemon-schedules-list-invalid.json"]),
  },
]);

export const s3Schema = (id: string, schema: string, parser: string, writer: string, fixture: string) => ({
  id,
  schema: `packages/daemon/src/protocol/daemon-protocol.contract.ts#${schema}`,
  parser: `packages/daemon/src/gui-s3-control.ts#${parser}`,
  writer: `packages/daemon/src/gui-s3-control.ts#${writer}`,
  error: "packages/daemon/src/gui-s3-control.ts#GuiS3ContractError",
  negativeFixtures: Object.freeze([`packages/daemon/fixtures/contracts/${fixture}`]),
});

export const daemonGuiActionSchemas = Object.freeze([
  {
    id: DAEMON_GUI_COMMAND_RECEIPT_SCHEMA.id,
    schema: "packages/daemon/src/protocol/daemon-protocol.contract.ts#DAEMON_GUI_COMMAND_RECEIPT_SCHEMA",
    parser: "packages/daemon/src/protocol/daemon-protocol.contract.ts#validateDaemonGuiCommandReceipt",
    writer: "packages/daemon/src/protocol/daemon-protocol-validate-results.ts#serializeDaemonGuiCommandReceipt",
    error: "packages/daemon/src/protocol/daemon-protocol.contract.ts#DaemonProtocolContractError",
    negativeFixtures: Object.freeze(["packages/daemon/fixtures/contracts/daemon-gui-command-receipt-invalid.json"]),
  },
  s3Schema(
    CATALOG_REREAD_RECEIPT_SCHEMA.id,
    "CATALOG_REREAD_RECEIPT_SCHEMA",
    "validateCatalogRereadReceipt",
    "writeCatalogRereadReceipt",
    "catalog-reread-receipt-v1-invalid.json",
  ),
  s3Schema(
    TERMINAL_CONTROL_RECEIPT_SCHEMA.id,
    "TERMINAL_CONTROL_RECEIPT_SCHEMA",
    "validateTerminalControlReceipt",
    "writeTerminalControlReceipt",
    "terminal-control-receipt-v1-invalid.json",
  ),
  s3Schema(
    TERMINAL_INPUT_ACK_SCHEMA.id,
    "TERMINAL_INPUT_ACK_SCHEMA",
    "validateTerminalInputAck",
    "writeTerminalInputAck",
    "terminal-input-ack-v1-invalid.json",
  ),
  s3Schema(
    TERMINAL_DETACH_ACK_SCHEMA.id,
    "TERMINAL_DETACH_ACK_SCHEMA",
    "validateTerminalDetachAck",
    "writeTerminalDetachAck",
    "terminal-detach-ack-v1-invalid.json",
  ),
  s3Schema(
    TERMINAL_ATTACH_SCHEMA.id,
    "TERMINAL_ATTACH_SCHEMA",
    "validateTerminalAttach",
    "writeTerminalAttach",
    "terminal-attach-v1-invalid.json",
  ),
  s3Schema(
    TERMINAL_ATTACH_EVENT_SCHEMA.id,
    "TERMINAL_ATTACH_EVENT_SCHEMA",
    "validateTerminalAttachEvent",
    "writeTerminalAttachEvent",
    "terminal-attach-event-v1-invalid.json",
  ),
]);
