import { shape } from "./daemon-protocol-gui-types.ts";
import {
  CATALOG_REREAD_RECEIPT_SCHEMA,
  DAEMON_CONTROL_RECEIPT_SCHEMA,
  DAEMON_GUI_COMMAND_RECEIPT_SCHEMA,
  DAEMON_PROTOCOL_ERROR_SCHEMA,
  guiAction,
  guiS3Action,
  TERMINAL_ATTACH_EVENT_SCHEMA,
  TERMINAL_ATTACH_SCHEMA,
  TERMINAL_CONTROL_RECEIPT_SCHEMA,
  TERMINAL_DETACH_ACK_SCHEMA,
  TERMINAL_INPUT_ACK_SCHEMA,
} from "./daemon-protocol-schema-ids.ts";
export const daemonGuiActionMethods = Object.freeze([
  {
    id: "gui.control.request",
    phase: "W5-GUI-S3",
    method: "daemon.gui.control.request",
    actionKind: "daemon-control-request",
    requiresRepo: false,
    params: shape({
      payload: shape({
        kind: "string",
        authorityRepoId: "string",
        reason: "string?",
      }),
    }),
    guiBridgeMethod: "requestDaemonControl",
    httpMethod: "POST",
    path: "/api/system/control",
    inputSchemaId: "gui.daemon-control-request/v1",
    outputSchemaId: DAEMON_CONTROL_RECEIPT_SCHEMA.id,
    errorSchemaId: DAEMON_PROTOCOL_ERROR_SCHEMA.id,
    serviceMethod: "requestDaemonControl",
    auth: "local-session-token",
    commandClass: "admin",
  },
  guiAction(
    "task.start",
    "repo.task.start",
    "task-start",
    shape({ taskId: "string", executionId: "string" }),
    "startTask",
    "/api/tasks/:taskId/start",
    "repo-write",
  ),
  guiAction(
    "task.progress.append",
    "repo.task.progress.append",
    "task-progress-append",
    shape({
      taskId: "string",
      executionId: "string?",
      text: "string",
      evidence: "array?",
      baseDocumentSha256: "string-null?",
    }),
    "appendTaskProgress",
    "/api/tasks/:taskId/progress",
    "repo-write",
  ),
  guiAction(
    "task.submit",
    "repo.task.submit",
    "task-submit",
    shape({ taskId: "string", executionId: "string", submission: "json" }),
    "submitTask",
    "/api/tasks/:taskId/submit",
    "repo-write",
  ),
  // Pin/unpin is a named ingress onto task-amend, not a second path; the closed
  // payload and actionDefaults keep WriteCoordinator/event/projection canonical.
  guiAction(
    "task.pin",
    "repo.task.pin",
    "task-amend",
    shape({ taskId: "string" }),
    "pinTask",
    "/api/tasks/:taskId/pin",
    "repo-write",
    { patches: [{ field: "pinned", value: "true" }] },
  ),
  guiAction(
    "task.unpin",
    "repo.task.unpin",
    "task-amend",
    shape({ taskId: "string" }),
    "unpinTask",
    "/api/tasks/:taskId/unpin",
    "repo-write",
    { patches: [{ field: "pinned", value: "false" }] },
  ),
  guiAction(
    "decision.list",
    "repo.decision.list",
    "decision-list",
    shape({
      search: "string?",
      legacyId: "string?",
      legacyRange: "json?",
      state: "string?",
      module: "string?",
      productLine: "string?",
    }),
    "listDecisions",
    "/api/decision-control",
    "repo-read",
  ),
  guiAction(
    "decision.show",
    "repo.decision.show",
    "decision-show",
    shape({ decisionId: "string", includeBody: "boolean?" }),
    "showDecision",
    "/api/decision-control/:decisionId",
    "repo-read",
  ),
  guiAction(
    "decision.propose",
    "repo.decision.propose",
    "decision-propose",
    shape({
      title: "string",
      question: "string",
      riskTier: "string",
      urgency: "string",
      vertical: "string",
      preset: "string",
      appliesTo: "json",
      decisionClass: "string",
      chosen: "array",
      rejected: "array",
      body: "string",
      claims: "array",
      fulfillments: "array",
      relations: "array",
    }),
    "proposeDecision",
    "/api/decision-control/propose",
    "repo-write",
  ),
  guiAction(
    "decision.accept",
    "repo.decision.accept",
    "decision-accept",
    shape({
      decisionId: "string",
      rationale: "string",
      judgmentOnlyRationale: "string?",
    }),
    "acceptDecision",
    "/api/decision-control/:decisionId/accept",
    "arbiter",
  ),
  guiAction(
    "decision.reject",
    "repo.decision.reject",
    "decision-reject",
    shape({ decisionId: "string", reason: "string" }),
    "rejectDecision",
    "/api/decision-control/:decisionId/reject",
    "arbiter",
  ),
  guiAction(
    "decision.defer",
    "repo.decision.defer",
    "decision-defer",
    shape({ decisionId: "string", reason: "string" }),
    "deferDecision",
    "/api/decision-control/:decisionId/defer",
    "arbiter",
  ),
  guiAction(
    "receipt.show",
    "repo.receipt.show",
    "receipt-show",
    shape({ opId: "string" }),
    "showReceipt",
    "/api/receipts/:opId",
    "repo-read",
  ),
  guiS3Action(
    "settings.update",
    "repo.settings.update",
    "settings-update",
    shape({
      defaultVertical: "string?",
      defaultPreset: "string?",
      defaultProfile: "string?",
      locale: "string?",
      taskScaffold: "string?",
      repositoryScaffold: "string?",
      walFlushAdaptive: "boolean?",
      walFlushEvents: "number?",
      walFlushBytes: "number?",
      walFlushMilliseconds: "number?",
      idempotencyKey: "string",
    }),
    "updateSettings",
    "/api/settings",
    "repo-write",
    DAEMON_GUI_COMMAND_RECEIPT_SCHEMA.id,
  ),
  guiS3Action(
    "gui.catalog.reread",
    "repo.gui.catalog.reread",
    "catalog-reread",
    shape({ expectedDigest: "string?" }),
    "rereadCatalog",
    "/api/catalog/reread",
    "repo-read",
    CATALOG_REREAD_RECEIPT_SCHEMA.id,
  ),
  guiS3Action(
    "agentRuntime.spawn",
    "repo.agentRuntime.spawn",
    "runtime-spawn",
    shape({
      runtimeInstanceId: "string?",
      dispatchId: "string?",
      agentId: "string?",
      targetAgentId: "string?",
      squadId: "string?",
      model: "string?",
      effort: "string?",
      fast: "boolean?",
      permissionMode: "string?",
      cwd: "json",
      prompt: "string?",
      promptSource: "string?",
      missionName: "string?",
      waitProjectionMs: "number?",
      onExitCommand: "string?",
      taskId: "string-null?",
      idempotencyKey: "string",
      providerSessionId: "string?",
      executor: "json?",
    }),
    "spawnAgentRuntime",
    "/api/agent-runtime/spawn",
    "repo-write",
    DAEMON_GUI_COMMAND_RECEIPT_SCHEMA.id,
  ),
  guiS3Action(
    "agent.entity.write",
    "repo.agent.entity.write",
    "agent-install",
    shape({ declaration: "json" }),
    "saveAgent",
    "/api/agents",
    "repo-write",
    DAEMON_GUI_COMMAND_RECEIPT_SCHEMA.id,
  ),
  guiS3Action(
    "squad.entity.write",
    "repo.squad.entity.write",
    "squad-install",
    shape({ declaration: "json" }),
    "saveSquad",
    "/api/squads",
    "repo-write",
    DAEMON_GUI_COMMAND_RECEIPT_SCHEMA.id,
  ),
  guiAction(
    "schedule.create",
    "repo.schedule.create",
    "schedule-create",
    shape({
      scheduleId: "string",
      name: "string",
      mode: "string",
      everyMs: "number?",
      cronExpression: "string?",
      timezone: "string?",
      agentId: "string",
      runtimeInstanceId: "string",
      mission: "string",
      model: "string?",
      reasoningEffort: "string?",
      fast: "boolean?",
      cwd: "string?",
      idempotencyKey: "string",
    }),
    "createSchedule",
    "/api/schedules",
    "repo-write",
  ),
  guiAction(
    "schedule.update",
    "repo.schedule.update",
    "schedule-update",
    shape({
      scheduleId: "string",
      name: "string",
      mode: "string",
      everyMs: "number?",
      cronExpression: "string?",
      timezone: "string?",
      agentId: "string",
      runtimeInstanceId: "string",
      mission: "string",
      model: "string-null?",
      reasoningEffort: "string-null?",
      fast: "boolean?",
      cwd: "string-null?",
      idempotencyKey: "string",
    }),
    "updateSchedule",
    "/api/schedules/:scheduleId",
    "repo-write",
  ),
  guiAction(
    "schedule.delete",
    "repo.schedule.delete",
    "schedule-delete",
    shape({ scheduleId: "string", reason: "string?", idempotencyKey: "string" }),
    "deleteSchedule",
    "/api/schedules/:scheduleId",
    "repo-write",
  ),
  guiAction(
    "schedule.enable",
    "repo.schedule.enable",
    "schedule-enable",
    shape({ scheduleId: "string", idempotencyKey: "string" }),
    "enableSchedule",
    "/api/schedules/:scheduleId/enable",
    "repo-write",
  ),
  guiAction(
    "schedule.disable",
    "repo.schedule.disable",
    "schedule-disable",
    shape({ scheduleId: "string", idempotencyKey: "string" }),
    "disableSchedule",
    "/api/schedules/:scheduleId/disable",
    "repo-write",
  ),
  guiAction(
    "schedule.runNow",
    "repo.schedule.runNow",
    "schedule-run-now",
    shape({ scheduleId: "string", idempotencyKey: "string" }),
    "runScheduleNow",
    "/api/schedules/:scheduleId/run-now",
    "repo-write",
  ),
  guiS3Action(
    "agentRuntime.cancel",
    "repo.agentRuntime.cancel",
    "runtime-cancel",
    shape({ runtimeSessionId: "string" }),
    "cancelAgentRuntime",
    "/api/agent-runtime/sessions/:id/cancel",
    "repo-write",
    DAEMON_GUI_COMMAND_RECEIPT_SCHEMA.id,
  ),
  guiS3Action(
    "terminal.spawn",
    "repo.terminal.spawn",
    "terminal-spawn",
    shape({
      idempotencyKey: "string",
      backend: "string",
      name: "string?",
      cwd: "json",
      shellProfileId: "string?",
      taskId: "string?",
    }),
    "spawnTerminal",
    "/api/terminal/sessions",
    "repo-write",
    TERMINAL_CONTROL_RECEIPT_SCHEMA.id,
  ),
  guiS3Action(
    "terminal.input",
    "repo.terminal.input",
    "terminal-input",
    shape({ sessionId: "string", clientSeq: "number", utf8: "string" }),
    "sendTerminalInput",
    "/api/terminal/sessions/:id/input",
    "repo-write",
    TERMINAL_INPUT_ACK_SCHEMA.id,
  ),
  guiS3Action(
    "terminal.resize",
    "repo.terminal.resize",
    "terminal-resize",
    shape({ sessionId: "string", cols: "number", rows: "number" }),
    "resizeTerminal",
    "/api/terminal/sessions/:id/resize",
    "repo-write",
    TERMINAL_CONTROL_RECEIPT_SCHEMA.id,
  ),
  guiS3Action(
    "terminal.detach",
    "repo.terminal.detach",
    "terminal-detach",
    shape({ sessionId: "string", attachmentId: "string" }),
    "detachTerminal",
    "/api/terminal/sessions/:id/detach",
    "repo-read",
    TERMINAL_DETACH_ACK_SCHEMA.id,
  ),
  guiS3Action(
    "terminal.terminate",
    "repo.terminal.terminate",
    "terminal-terminate",
    shape({ sessionId: "string", confirmed: "boolean?" }),
    "terminateTerminal",
    "/api/terminal/sessions/:id/terminate",
    "repo-write",
    TERMINAL_CONTROL_RECEIPT_SCHEMA.id,
  ),
] as const);
export const daemonStreamFacets = Object.freeze([
  {
    id: "agentRuntime.attach",
    phase: "Runtime-B",
    method: "repo.agentRuntime.attach",
    eventMethod: "repo.agentRuntime.attach.frame",
    requiresRepo: true,
    params: shape({
      repo: shape({ repoId: "string" }),
      payload: shape({ runtimeSessionId: "string", afterCursor: "string" }),
    }),
  },
  {
    id: "terminal.attach",
    phase: "W5-GUI-S3",
    method: "repo.terminal.attach",
    eventMethod: "repo.terminal.attach.frame",
    requiresRepo: true,
    params: shape({
      repo: shape({ repoId: "string" }),
      payload: shape({ sessionId: "string", afterSeq: "number" }),
    }),
    guiBridgeMethod: "attachTerminal",
    httpMethod: "STREAM",
    path: "/api/terminal/sessions/:id/attach",
    inputSchemaId: "gui.terminal-attach/v1",
    outputSchemaId: TERMINAL_ATTACH_SCHEMA.id,
    eventSchemaId: TERMINAL_ATTACH_EVENT_SCHEMA.id,
    errorSchemaId: DAEMON_PROTOCOL_ERROR_SCHEMA.id,
    serviceMethod: "attachTerminal",
    auth: "local-session-token",
    commandClass: "repo-read",
  },
] as const);

type DaemonGuiStreamFacet = Extract<(typeof daemonStreamFacets)[number], { readonly guiBridgeMethod: string }>;
// The GUI routes are a projection; daemonStreamFacets is the only stream descriptor registry.
export const daemonGuiStreamFacets = Object.freeze(
  daemonStreamFacets.filter((facet): facet is DaemonGuiStreamFacet => "guiBridgeMethod" in facet),
);
