import path from "node:path";
import { createRuntime, decodePresetPackageV3, installPresetPackage, validatePresetPackage } from "./preset-resolver.ts";
import { consumeKnownError, type AgentDeclarationV1, type PresetCatalogEntryV1, type PresetKind, type SquadDeclarationV1 } from "./preset.contract.ts";

const verticalId = "software/coding";
type IdentityKind = Extract<PresetKind, "agent" | "squad">;
interface IdentityValidationReport { readonly schema: "preset-validate-report/v1"; readonly valid: boolean; readonly source: string; readonly kind?: IdentityKind; readonly preset?: { readonly id: string; readonly verticalId: string; readonly version: string; readonly digest: string }; readonly issues: readonly { readonly code: string; readonly message: string }[] }
export type AgentCatalogRow = Omit<AgentDeclarationV1, "instructions"> & Pick<PresetCatalogEntryV1, "layer" | "source" | "validity" | "issues">;
export type SquadCatalogRow = Omit<SquadDeclarationV1, "roster"> & Pick<PresetCatalogEntryV1, "layer" | "source" | "validity" | "issues">;

export function readAgentDeclaration(input: { readonly rootDir: string; readonly agentId: string }): AgentDeclarationV1 {
  const manifest = identityManifest(input.rootDir, input.agentId, "agent"); return manifest.agent!;
}
export function readSquadDeclaration(input: { readonly rootDir: string; readonly squadId: string }): SquadDeclarationV1 {
  const manifest = identityManifest(input.rootDir, input.squadId, "squad"), squad = manifest.squad!, missing = [squad.leader, ...squad.workers].filter((id) => { try { readAgentDeclaration({ rootDir: input.rootDir, agentId: id }); return false; } catch (error) { consumeKnownError(error); return true; } }); if (missing.length) throw identityError("squad_agent_not_found", `Squad ${squad.id} references unavailable agents: ${[...new Set(missing)].join(", ")}.`); return squad;
}
export async function listAgentDeclarations(rootDir: string): Promise<readonly AgentCatalogRow[]> { return (await listDeclarations(rootDir, "agent")).map(({ declaration, entry }) => ({ ...declaration as AgentDeclarationV1, instructions: undefined, layer: entry.layer, source: entry.source, validity: entry.validity, issues: entry.issues })).map(({ instructions: _instructions, ...row }) => row); }
export async function listSquadDeclarations(rootDir: string): Promise<readonly SquadCatalogRow[]> { return (await listDeclarations(rootDir, "squad")).map(({ declaration, entry }) => ({ ...declaration as SquadDeclarationV1, roster: undefined, layer: entry.layer, source: entry.source, validity: entry.validity, issues: entry.issues })).map(({ roster: _roster, ...row }) => row); }
export function validateIdentityPackage(input: { readonly source: string; readonly kind: IdentityKind }): IdentityValidationReport { const report = validatePresetPackage({ source: input.source }); if (!report.valid) return { schema: report.schema, valid: false, source: report.source, issues: report.issues.map(({ code, message }) => ({ code, message })) }; const decoded = decodePresetPackageV3(input.source); return decoded.manifest.kind === input.kind ? { schema: report.schema, valid: true, source: report.source, kind: input.kind, preset: report.preset, issues: [] } : { schema: "preset-validate-report/v1", valid: false, source: path.resolve(input.source), issues: [{ code: "identity_kind_mismatch", message: `Expected ${input.kind}, received ${decoded.manifest.kind}.` }] }; }
export function installIdentityPackage(input: { readonly source: string; readonly rootDir: string; readonly kind: IdentityKind; readonly dryRun?: boolean }) { const validated = validateIdentityPackage({ source: input.source, kind: input.kind }); if (!validated.valid) throw identityError(validated.issues[0]?.code ?? "invalid_identity_package", validated.issues[0]?.message ?? "Identity package is invalid."); return installPresetPackage({ source: input.source, userRoot: identityUserRoot(input.rootDir), dryRun: input.dryRun }); }

function identityManifest(rootDir: string, id: string, kind: IdentityKind) { const resolved = identityRuntime(rootDir).resolveInternal({ presetId: id, verticalId, locale: "en-US", purpose: "inspect" }), manifest = resolved.manifest; if (manifest.kind !== kind || kind === "agent" && !manifest.agent || kind === "squad" && !manifest.squad) throw identityError(`${kind}_not_found`, `${id} is not an installed ${kind}.`); return manifest; }
async function listDeclarations(rootDir: string, kind: IdentityKind) { const runtime = identityRuntime(rootDir), entries = await runtime.resolver.list({ verticalId }); return entries.flatMap((entry) => { if (entry.validity !== "valid" || entry.kind !== kind) return []; const manifest = runtime.resolveInternal({ presetId: entry.id, verticalId, locale: "en-US", purpose: "inspect" }).manifest, declaration = kind === "agent" ? manifest.agent : manifest.squad; return declaration ? [{ declaration, entry }] : []; }); }
function identityRuntime(rootDir: string) { return createRuntime({ userRoot: identityUserRoot(rootDir) }); }
function identityUserRoot(rootDir: string): string { return path.join(path.resolve(rootDir), ".harness/presets"); }
function identityError(code: string, message: string): Error & { readonly code: string } { return Object.assign(new Error(message), { code }); }
