import { createHash, randomUUID } from "node:crypto";
import { cpSync, existsSync, lstatSync, mkdirSync, readFileSync, readdirSync, renameSync, rmSync, unlinkSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { Schema } from "effect";
import { TemplateCatalogSchema, VerticalDefinitionSchema, planTemplateMaterialization, validateExtensionInputShape, validateTemplateCatalog, validateVerticalDefinition, type TemplateCatalog, type VerticalDefinition } from "../../kernel/src/index.ts";
import { canonicalPresetBytes, parsePresetManifestV3, validatePresetDocumentV1, type CanonicalPresetResolver, type CapabilityRefV1, type ExecutablePackageHandle, type PresetCatalogEntryV1, type PresetDocumentV1, type PresetLayer, type PresetManifestV3, type PresetResolveResultV1, type PresetSnapshotV1, type ResolvePresetRequestV1, type TemplateSelectionV1 } from "./preset.contract.ts";

declare const decodedPackageBrand: unique symbol;
export interface DecodedPresetPackageV3 { readonly manifest: PresetManifestV3; readonly document: PresetDocumentV1; readonly root: string; readonly packageDigest: string; readonly manifestSha256: string; readonly [decodedPackageBrand]: true }
export interface PresetResolverOptions { readonly bundledRoot?: string; readonly userRoot: string; readonly assetsRoot?: string; readonly kernelVersion?: string; readonly projectScaffold?: string; readonly projectRoot?: string }
interface Candidate { readonly id: string; readonly verticalId: string; readonly layer: PresetLayer; readonly decoded?: DecodedPresetPackageV3; readonly error?: PresetFailure; readonly shadow?: { readonly title: string } }
interface PresetFailure { readonly code: string; readonly message: string }
interface CatalogSource { readonly catalog: TemplateCatalog; readonly root: string; readonly sha256: string }
interface CanonicalAssets { readonly vertical: VerticalDefinition; readonly verticalSha256: string; readonly catalog: CatalogSource; readonly providers: readonly Provider[] }
interface ScaffoldSelection { readonly selection: TemplateSelectionV1; readonly owner: "doc-sync"; readonly source?: CatalogSource; readonly requiredAnchors?: readonly string[]; readonly project?: { readonly body: string; readonly mediaType: "text/markdown" | "text/plain"; readonly ref: string } }
interface Provider { readonly id: string; readonly kind: CapabilityRefV1["kind"]; readonly version: string; readonly templateOverrides?: Readonly<Record<string, string>>; readonly requiredTaskClass?: "milestone" | "epic"; readonly actionKind?: string; readonly payloadFields?: readonly string[] }
type ManifestEntrypoint = NonNullable<PresetManifestV3["entrypoints"]>[string];
interface OwnedEntrypoint { readonly definition: ManifestEntrypoint; readonly root: string; readonly packageDigest: string }
export interface InternalPresetResolution { readonly snapshot: PresetSnapshotV1; readonly documents: readonly { readonly slot: string; readonly path: string; readonly body: string; readonly mediaType: "text/markdown" | "text/plain"; readonly owner: "doc-sync"; readonly requiredAnchors: readonly string[]; readonly templateRef: string }[]; readonly requiredTaskClass?: "milestone" | "epic"; readonly packageRoot: string; readonly packageDigest: string; readonly produceActions: Readonly<Record<string, { readonly actionKind: string; readonly payloadFields: readonly string[] }>> }
const defaultAssets = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../assets/software-coding"), defaultBundled = path.join(defaultAssets, "presets");

export function createCanonicalPresetResolver(options: PresetResolverOptions): CanonicalPresetResolver { return createRuntime(options).resolver; }
export function installPresetPackage(input: { readonly source: string; readonly userRoot: string; readonly killpoint?: (point: "after-object" | "after-pointer") => void }): { readonly presetId: string; readonly digest: string } {
  const decoded = decodePresetPackageV3(input.source), userRoot = path.resolve(input.userRoot), objects = path.join(userRoot, "preset-objects"), active = path.join(userRoot, "active"), objectRoot = path.join(objects, decoded.packageDigest), temporaryObject = path.join(objects, `.install-${randomUUID()}`), pointer = path.join(active, `${decoded.manifest.id}.json`), temporaryPointer = path.join(active, `.${decoded.manifest.id}-${randomUUID()}.tmp`);
  for (const directory of [userRoot, objects, active]) ensureInstallDirectory(directory);
  try { if (!existsSync(objectRoot)) { cpSync(decoded.root, temporaryObject, { recursive: true, errorOnExist: true }); const copied = decodePresetPackageV3(temporaryObject); if (copied.packageDigest !== decoded.packageDigest) throw failure("digest_mismatch", "Copied preset package does not match its preflight digest."); renameSync(temporaryObject, objectRoot); } else if (decodePresetPackageV3(objectRoot).packageDigest !== decoded.packageDigest) throw failure("digest_mismatch", "Immutable preset object does not match its directory digest."); input.killpoint?.("after-object"); writeFileSync(temporaryPointer, `${JSON.stringify({ schema: "preset-active-pointer/v1", presetId: decoded.manifest.id, verticalId: decoded.manifest.vertical, digest: decoded.packageDigest })}\n`); renameSync(temporaryPointer, pointer); input.killpoint?.("after-pointer"); return { presetId: decoded.manifest.id, digest: decoded.packageDigest }; }
  finally { if (existsSync(temporaryObject)) rmSync(temporaryObject, { recursive: true, force: true }); if (existsSync(temporaryPointer)) rmSync(temporaryPointer, { force: true }); }
}
export function uninstallPresetPackage(input: { readonly presetId: string; readonly userRoot: string }): boolean { if (!/^[a-z0-9][a-z0-9-]{0,127}$/u.test(input.presetId)) throw failure("invalid_preset_id", "Preset id is invalid."); const pointer = path.join(path.resolve(input.userRoot), "active", `${input.presetId}.json`); if (!existsSync(pointer)) return false; if (!lstatSync(pointer).isFile() || lstatSync(pointer).isSymbolicLink()) throw failure("invalid_pointer", "Active pointer is not a regular file."); unlinkSync(pointer); return true; }

export function createRuntime(options: PresetResolverOptions): { readonly resolver: CanonicalPresetResolver; readonly resolveInternal: (request: ResolvePresetRequestV1) => InternalPresetResolution } {
  const bundledRoot = path.resolve(options.bundledRoot ?? defaultBundled), userRoot = path.resolve(options.userRoot), assetsRoot = path.resolve(options.assetsRoot ?? defaultAssets), kernelVersion = options.kernelVersion ?? "1.0.0";
  let cachedAssets: CanonicalAssets | undefined;
  const resolveInternal = (request: ResolvePresetRequestV1): InternalPresetResolution => {
    const inventory = effectiveCatalog(bundledRoot, userRoot), selected = inventory.get(key(request.verticalId, request.presetId)); if (!selected) throw failure("preset_not_found", `Preset ${request.presetId} is not installed.`); if (!selected.decoded) throw selected.error ?? failure("shadow_invalid", `User shadow ${request.presetId} is invalid.`);
    const ancestry = resolveAncestry(inventory, selected, request.verticalId); for (const item of ancestry) { const manifest = item.decoded!.manifest; if (compareVersion(kernelVersion, manifest.kernelVersionRange.min) < 0 || manifest.kernelVersionRange.maxExclusive && compareVersion(kernelVersion, manifest.kernelVersionRange.maxExclusive) >= 0) throw failure("incompatible_kernel", `Preset ${manifest.id} is incompatible with kernel ${kernelVersion}.`); }
    const assets = cachedAssets ??= loadCanonicalAssets(assetsRoot); if (assets.vertical.id !== request.verticalId) throw failure("missing_vertical", `Vertical ${request.verticalId} is unavailable.`);
    const leaf = ancestry.at(-1)!.decoded!, profiles = ancestry.map((item) => profileFor(item.decoded!.manifest, item === ancestry.at(-1) ? request.profileId : undefined)), profile = profiles.at(-1)!, imports = ancestry.flatMap((item, index) => [...item.decoded!.manifest.capabilityImports, ...profiles[index]!.capabilityImports ?? []]), providerMap = new Map(assets.providers.map((item) => [item.id, item]));
    let requiredTaskClass: "milestone" | "epic" | undefined; for (const imported of imports) { const provider = providerMap.get(imported.id); if (!provider || provider.kind !== imported.kind || provider.version !== imported.version) { if (!("required" in imported) || imported.required) throw failure("missing_provider", `Capability provider ${imported.id} is unavailable.`); continue; } requiredTaskClass = provider.requiredTaskClass ?? requiredTaskClass; }
    const taskScaffold = assets.vertical.packageScaffolds.find((item) => item.entityKind === "task"); if (!taskScaffold) throw failure("invalid_vertical", "Vertical task package scaffold is unavailable.");
    const selections = new Map<string, ScaffoldSelection>(taskScaffold.templateSelections.map((selection) => [selection.slot, { selection, owner: "doc-sync", source: assets.catalog }])), overlay = readProjectScaffold(options, selections);
    for (const [index, selectedProfile] of profiles.entries()) { const candidate = ancestry[index]!, source = candidate.layer === "user" && selectedProfile.templateSelections.length ? loadPackageCatalog(candidate.decoded!) : assets.catalog; for (const selection of selectedProfile.templateSelections) { const previous = selections.get(selection.slot); if (previous && previous.selection.templateRef !== selection.templateRef) { const allowed = imports.some((item) => providerMap.get(item.id)?.templateOverrides?.[selection.slot] === selection.templateRef); if (!allowed) throw failure("slot_conflict", `Template slot ${selection.slot} conflicts without a provider.`); } selections.set(selection.slot, { selection, owner: previous?.owner ?? "doc-sync", source }); } }
    const documents = materializeSelections([...selections.values()], normalizeLocale(request.locale)), catalogDigests = [...new Set([...selections.values()].flatMap((item) => item.source ? [item.source.sha256] : []))].sort(), templateCatalogSha256 = catalogDigests.length === 1 ? catalogDigests[0]! : hash(canonicalPresetBytes(catalogDigests));
    const entrypoints: Record<string, OwnedEntrypoint> = Object.assign({}, ...ancestry.map((item) => Object.fromEntries(Object.entries(item.decoded!.manifest.entrypoints ?? {}).map(([name, definition]) => [name, { definition, root: item.decoded!.root, packageDigest: item.decoded!.packageDigest }])))); if (request.purpose === "script-run" && (!request.entrypoint || !entrypoints[request.entrypoint])) throw failure("entrypoint_not_found", `Entrypoint ${request.entrypoint ?? "<missing>"} is not declared.`);
    for (const [name, owned] of Object.entries(entrypoints)) { const command = path.resolve(owned.root, owned.definition.command); if (!inside(owned.root, command) || !existsSync(command) || !lstatSync(command).isFile() || lstatSync(command).isSymbolicLink()) throw failure("missing_script", `Entrypoint ${name} command is missing or unsafe.`); for (const capability of [...owned.definition.requires, ...owned.definition.produces, ...owned.definition.sideEffects]) { const provider = providerMap.get(capability.id); if (!provider || provider.kind !== capability.kind || provider.version !== capability.version) throw failure("missing_provider", `Entrypoint capability ${capability.id} is unavailable.`); } }
    const resolvedSelectionDigest = `sha256:${hash(canonicalPresetBytes(documents.map((item) => ({ slot: item.selection.slot, path: item.selection.materializeAs, templateRef: item.selection.templateRef, locale: item.locale, owner: item.owner, requiredAnchors: item.requiredAnchors, sha256: hash(item.body) }))))}` as const, withoutDigest = { schema: "preset-snapshot/v1" as const, identity: { id: leaf.manifest.id, version: leaf.manifest.version, verticalId: request.verticalId, layer: selected.layer }, profile: { id: profile.id, outputShape: leaf.manifest.outputShape, completionGateIds: profile.completionGates }, guidance: { description: leaf.document.description, whenToUse: leaf.document.whenToUse, bodySha256: hash(leaf.document.body) }, scaffold: { baseVersion: "software-coding/v1" as const, overlayDigest: overlay.digest, resolvedSelectionDigest }, templates: documents.map((item) => ({ slot: item.selection.slot, path: item.selection.materializeAs, templateRef: item.selection.templateRef, locale: item.locale, owner: item.owner, requiredAnchors: item.requiredAnchors, content: { sha256: hash(item.body), size: Buffer.byteLength(item.body), mediaType: item.mediaType } })), entrypoints: Object.fromEntries(Object.entries(entrypoints).map(([name, { definition: item, root }]) => { const commandBody = requiredRegularFile(path.resolve(root, item.command), "missing_script"); return [name, { type: "script" as const, intent: item.intent, inputs: item.inputs, requires: item.requires, produces: item.produces, sideEffects: item.sideEffects, commandRef: item.command, commandSha256: hash(commandBody) }]; })), provenance: { manifestSha256: leaf.manifestSha256, packageSha256: leaf.packageDigest, verticalSha256: assets.verticalSha256, templateCatalogSha256, resolverVersion: "1" as const, ancestry: ancestry.map((item) => item.id) } }, digest = `sha256:${hash(canonicalPresetBytes(withoutDigest))}` as const;
    const executablePackage = request.purpose === "script-run" && request.entrypoint ? entrypoints[request.entrypoint]! : leaf; return { snapshot: { ...withoutDigest, digest }, documents: documents.map((item) => ({ slot: item.selection.slot, path: item.selection.materializeAs, body: item.body, mediaType: item.mediaType, owner: item.owner, requiredAnchors: item.requiredAnchors, templateRef: item.selection.templateRef })), ...(requiredTaskClass ? { requiredTaskClass } : {}), packageRoot: executablePackage.root, packageDigest: executablePackage.packageDigest, produceActions: Object.fromEntries(assets.providers.filter((provider) => provider.actionKind).map((provider) => [provider.id, { actionKind: provider.actionKind!, payloadFields: provider.payloadFields ?? [] }])) };
  };
  const resolver: CanonicalPresetResolver = { list: async ({ verticalId }) => listCatalog(effectiveCatalog(bundledRoot, userRoot), verticalId), resolve: async (request): Promise<PresetResolveResultV1> => { try { const resolved = resolveInternal(request); const packageHandle: ExecutablePackageHandle | null = request.purpose === "script-run" ? { packageDigest: resolved.packageDigest, opaque: Symbol("preset-package") } : null; return { ok: true, snapshot: resolved.snapshot, package: packageHandle }; } catch (error) { const known = asFailure(error); return { ok: false, error: { code: known.code, hint: known.message, nextAction: known.message } }; } } }; return { resolver, resolveInternal };
}

function loadCanonicalAssets(root: string): CanonicalAssets {
  const verticalBody = requiredRegularFile(path.join(root, "vertical.json"), "missing_vertical"), catalogBody = requiredRegularFile(path.join(root, "template-catalog.json"), "missing_template_catalog"), providersBody = requiredRegularFile(path.join(root, "capabilities.json"), "missing_provider_catalog"), verticalRaw = json(verticalBody, "invalid_vertical"), catalog = decodeCatalog(catalogBody, root), verticalShape = validateExtensionInputShape("vertical-definition", verticalRaw); if (!verticalShape.ok) throw failure("invalid_vertical", verticalShape.issues.map((item) => item.message).join("; "));
  let vertical: VerticalDefinition; try { vertical = Schema.decodeUnknownSync(VerticalDefinitionSchema)(verticalRaw); } catch { throw failure("invalid_vertical", "Vertical contract is invalid."); } const verticalValidation = validateVerticalDefinition(vertical); if (!verticalValidation.ok) throw failure("invalid_vertical", verticalValidation.issues.map((item) => item.message).join("; "));
  return { vertical, verticalSha256: hash(verticalBody), catalog, providers: decodeProviders(json(providersBody, "invalid_provider_catalog")) };
}
function decodeCatalog(body: string, root: string): CatalogSource { const raw = json(body, "invalid_template_catalog"), shape = validateExtensionInputShape("template-catalog", raw); if (!shape.ok) throw failure("invalid_template_catalog", shape.issues.map((item) => item.message).join("; ")); let catalog: TemplateCatalog; try { catalog = Schema.decodeUnknownSync(TemplateCatalogSchema)(raw); } catch { throw failure("invalid_template_catalog", "Template catalog is invalid."); } const source = { catalog, root, sha256: hash(body) }, validation = validateTemplateCatalog(catalog, { resolveBody: ({ locale }) => requiredRegularFile(safeTemplatePath(root, locale.bodyPath, `${catalog.package.id}/${locale.locale}`), "missing_template") }); if (!validation.ok) throw failure("invalid_template_catalog", validation.issues.map((item) => item.message).join("; ")); return source; }
function loadPackageCatalog(decoded: DecodedPresetPackageV3): CatalogSource { const target = path.join(decoded.root, "template-catalog.json"); if (!existsSync(target)) throw failure("missing_template_catalog", `User preset ${decoded.manifest.id} must provide template-catalog.json for its template selections.`); return decodeCatalog(requiredRegularFile(target, "missing_template_catalog"), decoded.root); }
function profileFor(manifest: PresetManifestV3, requested?: string) { const id = requested ?? manifest.defaultProfile, profile = manifest.profiles.find((item) => item.id === id); if (!profile) throw failure("missing_profile", `Profile ${id} is unavailable.`); return profile; }
function resolveAncestry(catalog: Map<string, Candidate>, selected: Candidate, verticalId: string): Candidate[] { const ancestry: Candidate[] = [], seen = new Set<string>(); let current: Candidate | undefined = selected; while (current) { if (seen.has(current.id)) throw failure("extends_cycle", `Preset extends cycle includes ${current.id}.`); seen.add(current.id); ancestry.unshift(current); const parentId = current.decoded!.manifest.extends; if (!parentId) break; const parent = catalog.get(key(verticalId, parentId)); if (!parent?.decoded) throw failure("missing_parent", `Preset parent ${parentId} is missing or invalid.`); current = parent; } return ancestry; }
function materializeSelections(entries: readonly ScaffoldSelection[], locale: "zh-CN" | "en-US") {
  const groups = new Map<CatalogSource, ScaffoldSelection[]>(), plannedBySlot = new Map<string, ReturnType<typeof planTemplateMaterialization>["documents"][number]>(); for (const item of entries) if (!item.project) { if (!item.source) throw failure("missing_template_catalog", `Template ${item.selection.templateRef} has no catalog source.`); const group = groups.get(item.source) ?? []; group.push(item); groups.set(item.source, group); }
  for (const [source, selected] of groups) { const result = planTemplateMaterialization({ catalog: source.catalog, selections: selected.map((item) => item.selection), locale, resolveBody: ({ locale: variant }) => requiredRegularFile(safeTemplatePath(source.root, variant.bodyPath, source.catalog.package.id), "missing_template") }); if (!result.ok) throw failure(result.issues.some((item) => item.code === "missing_template") ? "missing_template" : "invalid_template_catalog", result.issues.map((item) => item.message).join("; ")); for (const document of result.documents) plannedBySlot.set(document.slot, document); }
  const usedPaths = new Set<string>(); return entries.map((item) => { safeMaterializedPath(item.selection.materializeAs, usedPaths); if (item.project) { const requiredAnchors = item.requiredAnchors ?? []; for (const anchor of requiredAnchors) if (!item.project.body.includes(anchor)) throw failure("required_anchor", `Template ${item.selection.templateRef} is missing required anchor ${anchor}.`); return { ...item, body: item.project.body, mediaType: item.project.mediaType, locale: "project", requiredAnchors }; } const planned = plannedBySlot.get(item.selection.slot); if (!planned) throw failure("missing_template", `Template ${item.selection.templateRef} was not materialized.`); return { ...item, body: planned.body, mediaType: catalogMediaType(item.source!, item.selection.templateRef, planned.locale), locale: planned.locale, requiredAnchors: planned.requiredAnchors }; });
}
function catalogMediaType(source: CatalogSource, ref: string, locale: string): "text/markdown" | "text/plain" { const document = source.catalog.documents.find((item) => `template://${item.id}@${item.version}` === ref), variant = document?.locales.find((item) => item.locale === locale), bodyPath = variant?.bodyPath; if (!bodyPath || !/\.(?:md|txt)$/u.test(bodyPath)) throw failure("missing_template", `Template ${ref} is not task prose.`); return document?.documentKind === "keep-file" || bodyPath.endsWith(".txt") ? "text/plain" : "text/markdown"; }

function effectiveCatalog(bundledRoot: string, userRoot: string): Map<string, Candidate> { const result = new Map<string, Candidate>(); for (const item of enumerateBundled(bundledRoot)) result.set(key(item.verticalId, item.id), item); for (const item of enumerateUser(userRoot)) { const targets = item.verticalId === "*" ? [...result].filter(([, candidate]) => candidate.id === item.id).map(([catalogKey]) => catalogKey) : [key(item.verticalId, item.id)]; if (targets.length === 0) targets.push(key("*", item.id)); for (const target of targets) { const shadowed = result.get(target); result.set(target, item.decoded ? item : { ...item, verticalId: shadowed?.verticalId ?? item.verticalId, ...(shadowed?.decoded ? { shadow: { title: shadowed.decoded.manifest.title } } : {}), error: failure("shadow_invalid", `${item.error?.message ?? "User package is invalid"}${shadowed ? `; bundled ${shadowed.id} remains blocked` : ""}.`) }); } } return result; }
function enumerateBundled(root: string): Candidate[] { if (!existsSync(root)) return []; return readdirSync(root, { withFileTypes: true }).filter((entry) => entry.isDirectory() && !entry.isSymbolicLink()).map((entry) => decodeCandidate(path.join(root, entry.name), "bundled", entry.name)); }
function enumerateUser(root: string): Candidate[] { const active = path.join(root, "active"); if (!existsSync(active)) return []; if (!lstatSync(active).isDirectory() || lstatSync(active).isSymbolicLink()) throw failure("invalid_pointer_root", "Active preset inventory is not a regular directory."); return readdirSync(active, { withFileTypes: true }).filter((entry) => entry.name.endsWith(".json")).map((entry) => { const id = entry.name.slice(0, -5); let verticalId = "*"; try { if (entry.isSymbolicLink() || !entry.isFile()) throw failure("invalid_pointer", `Active pointer ${id} is not a regular file.`); const pointer = json(readFileSync(path.join(active, entry.name), "utf8"), "invalid_pointer") as Record<string, unknown>; if (typeof pointer.verticalId === "string") verticalId = pointer.verticalId; if (Object.keys(pointer).length !== 4 || pointer.schema !== "preset-active-pointer/v1" || pointer.presetId !== id || verticalId === "*" || typeof pointer.digest !== "string" || !/^[0-9a-f]{64}$/u.test(pointer.digest)) throw failure("invalid_pointer", `Active pointer ${id} is invalid.`); return decodeCandidate(path.join(root, "preset-objects", pointer.digest), "user", id, verticalId, pointer.digest); } catch (error) { return { id, verticalId, layer: "user", error: asFailure(error) }; } }); }
function decodeCandidate(root: string, layer: PresetLayer, directoryId: string, pointerVertical?: unknown, pointerDigest?: unknown): Candidate { try { const decoded = decodePackage(root, layer === "user"); if (decoded.manifest.id !== directoryId) throw failure("path_id_mismatch", `Package directory ${directoryId} does not match ${decoded.manifest.id}.`); if (pointerVertical !== undefined && decoded.manifest.vertical !== pointerVertical) throw failure("invalid_pointer", `Pointer vertical does not match package ${directoryId}.`); if (pointerDigest !== undefined && decoded.packageDigest !== pointerDigest) throw failure("digest_mismatch", `Pointer digest does not match package ${directoryId}.`); return { id: decoded.manifest.id, verticalId: decoded.manifest.vertical, layer, decoded }; } catch (error) { return { id: directoryId, verticalId: typeof pointerVertical === "string" ? pointerVertical : "software/coding", layer, error: asFailure(error) }; } }
export function decodePresetPackageV3(root: string): DecodedPresetPackageV3 { return decodePackage(path.resolve(root), true); }
function decodePackage(root: string, requireLocalCatalog = false): DecodedPresetPackageV3 { const files = scan(root), manifestBody = file(files, "preset.json", "missing_manifest"), presetBody = file(files, "PRESET.md", "missing_preset_document"), manifest = parsePresetManifestV3(json(manifestBody, "invalid_manifest")), document = parseDocument(presetBody); for (const [name, entrypoint] of Object.entries(manifest.entrypoints ?? {})) if (!files.has(entrypoint.command)) throw failure("missing_script", `Entrypoint ${name} command ${entrypoint.command} is missing.`); if (manifest.policyPath && !files.has(manifest.policyPath)) throw failure("missing_policy", `Policy ${manifest.policyPath} is missing.`); const catalogBody = files.get("template-catalog.json"), hasSelections = manifest.profiles.some((profile) => profile.templateSelections.length > 0); if (requireLocalCatalog && hasSelections && catalogBody === undefined) throw failure("missing_template_catalog", `User preset ${manifest.id} must provide template-catalog.json for its template selections.`); if (catalogBody !== undefined) decodeCatalog(catalogBody, root); const digest = createHash("sha256"); for (const [name, body] of [...files].sort(([left], [right]) => left.localeCompare(right))) digest.update(`${name}\0${Buffer.byteLength(body)}\0`).update(body); return { manifest, document, root, packageDigest: digest.digest("hex"), manifestSha256: hash(canonicalPresetBytes(manifest)) } as DecodedPresetPackageV3; }
function scan(root: string): Map<string, string> { if (!existsSync(root) || !lstatSync(root).isDirectory() || lstatSync(root).isSymbolicLink()) throw failure("invalid_package", `Preset package ${root} is not a regular directory.`); const files = new Map<string, string>(), visit = (directory: string) => { for (const entry of readdirSync(directory, { withFileTypes: true })) { const absolute = path.join(directory, entry.name), relative = path.relative(root, absolute).split(path.sep).join("/"); if (entry.isSymbolicLink() || !entry.isDirectory() && !entry.isFile()) throw failure("symlink_forbidden", `Preset package entry ${relative} is not regular.`); if (entry.isDirectory()) visit(absolute); else files.set(relative, readFileSync(absolute, "utf8")); } }; visit(root); return files; }
function parseDocument(body: string): PresetDocumentV1 { const match = /^---\nschema:\s*(.+)\ndescription:\s*(.+)\nwhenToUse:\s*(.+)\n---\n([\s\S]*)$/u.exec(body), value = match ? { schema: match[1], description: match[2], whenToUse: match[3], body: match[4] } : null, errors = validatePresetDocumentV1(value); if (errors.length) throw failure("invalid_preset_document", errors.join("; ")); return value as PresetDocumentV1; }
function readProjectScaffold(options: PresetResolverOptions, selections: Map<string, ScaffoldSelection>): { readonly digest: `sha256:${string}` | null } { if (!options.projectScaffold) return { digest: null }; const target = path.resolve(options.projectScaffold), projectRoot = path.resolve(options.projectRoot ?? path.dirname(target)), raw = json(requiredRegularFile(target, "missing_task_scaffold"), "invalid_task_scaffold"); if (!record(raw) || !exact(raw, ["schema", "replaceTemplate", "addDocument"]) || raw.schema !== "task-scaffold/v1" || !Array.isArray(raw.replaceTemplate) || !Array.isArray(raw.addDocument)) throw failure("invalid_task_scaffold", "Project task scaffold fields are invalid."); const bound: { readonly ref: string; readonly sha256: string }[] = [];
  for (const item of raw.replaceTemplate) { if (!record(item) || !exact(item, ["slot", "template"]) || typeof item.slot !== "string" || typeof item.template !== "string") throw failure("invalid_task_scaffold", "replaceTemplate may only name slot and template."); const previous = selections.get(item.slot); if (!previous) throw failure("invalid_task_scaffold", `Cannot replace unknown base slot ${item.slot}.`); const source = projectTemplate(projectRoot, item.template), anchors = previous.requiredAnchors ?? catalogAnchors(previous.source, previous.selection.templateRef); bound.push({ ref: source.ref, sha256: hash(source.body) }); selections.set(item.slot, { selection: { ...previous.selection, templateRef: source.ref }, owner: previous.owner, requiredAnchors: anchors, project: source }); }
  for (const item of raw.addDocument) { if (!record(item) || !exact(item, ["slot", "path", "template", "requiredAnchors"]) || typeof item.slot !== "string" || typeof item.path !== "string" || typeof item.template !== "string" || !strings(item.requiredAnchors)) throw failure("invalid_task_scaffold", "addDocument may only name slot, path, template, and requiredAnchors."); if (selections.has(item.slot) || !/\.(?:md|txt)$/u.test(item.path)) throw failure("invalid_task_scaffold", `Added slot ${item.slot} must be unique prose.`); const source = projectTemplate(projectRoot, item.template); bound.push({ ref: source.ref, sha256: hash(source.body) }); selections.set(item.slot, { selection: { slot: item.slot, templateRef: source.ref, materializeAs: item.path, localePolicy: { prefer: "project", fallback: "en-US" } }, owner: "doc-sync", requiredAnchors: item.requiredAnchors, project: source }); }
  return { digest: `sha256:${hash(canonicalPresetBytes({ overlay: raw, templates: bound.sort((left, right) => left.ref.localeCompare(right.ref)) }))}` };
}
function catalogAnchors(source: CatalogSource | undefined, ref: string): readonly string[] { const anchors = source?.catalog.documents.find((item) => `template://${item.id}@${item.version}` === ref)?.requiredAnchors; if (!anchors) throw failure("invalid_task_scaffold", `Base anchors for ${ref} are unavailable.`); return anchors; }
function projectTemplate(root: string, value: string) { const normalized = value.normalize("NFC"), target = path.resolve(root, normalized); if (value !== normalized || !inside(root, target) || !/\.(?:md|txt)$/u.test(value)) throw failure("invalid_task_scaffold", `Project template ${value} is unsafe.`); return { body: requiredRegularFile(target, "missing_task_scaffold_template"), mediaType: value.endsWith(".md") ? "text/markdown" as const : "text/plain" as const, ref: `project://${value.split(path.sep).join("/")}` }; }
function decodeProviders(value: unknown): Provider[] { if (!record(value) || value.schema !== "preset-capabilities/v1" || !Array.isArray(value.providers) || !value.providers.every((item) => !!item && typeof item === "object" && typeof (item as Provider).id === "string" && typeof (item as Provider).kind === "string" && typeof (item as Provider).version === "string" && ((item as Provider).actionKind === undefined || typeof (item as Provider).actionKind === "string" && Array.isArray((item as Provider).payloadFields) && (item as Provider).payloadFields!.every((field) => typeof field === "string")))) throw failure("invalid_provider_catalog", "Capability provider catalog is invalid."); return value.providers as Provider[]; }
function listCatalog(catalog: Map<string, Candidate>, verticalId: string): PresetCatalogEntryV1[] { return [...catalog.values()].filter((item) => item.verticalId === verticalId).map((item): PresetCatalogEntryV1 => item.decoded ? { id: item.id, title: item.decoded.manifest.title, description: item.decoded.document.description, verticalId, layer: item.layer, validity: "valid" } : { id: item.id, title: item.id, description: item.error?.message ?? "Invalid package", verticalId, layer: item.layer, validity: "blocked", errorCode: item.error?.code ?? "invalid_package", ...(item.shadow ? { shadows: { layer: "bundled" as const, title: item.shadow.title } } : {}) }).sort((left, right) => left.id.localeCompare(right.id)); }
function safeMaterializedPath(value: string, used: Set<string>): void { const normalized = value.normalize("NFC"), parts = value.split("/"), folded = normalized.toLocaleLowerCase("en-US"); if (value !== normalized || path.posix.isAbsolute(value) || value.includes("\\") || parts.some((part) => !part || part === "." || part === "..") || /^(?:harness\/)?(?:events|objects)\//u.test(value) || /^(?:index\.md|task-contract\.json|facts\.md|progress\.md|code-doc-anchors\.json|executions(?:\/|$)|reviews(?:\/|$))$/iu.test(value) || used.has(folded)) throw failure("reserved_path", `Template path ${value} is unsafe or duplicated.`); used.add(folded); }
function safeTemplatePath(root: string, value: string, ref: string): string { const target = path.resolve(root, value); if (!inside(root, target)) throw failure("missing_template", `Template ${ref} escapes the asset root.`); return target; }
function requiredRegularFile(target: string, code: string): string { if (!existsSync(target) || !lstatSync(target).isFile() || lstatSync(target).isSymbolicLink()) throw failure(code, `Required regular file ${target} is unavailable.`); return readFileSync(target, "utf8"); }
function ensureInstallDirectory(target: string): void { if (existsSync(target) && (!lstatSync(target).isDirectory() || lstatSync(target).isSymbolicLink())) throw failure("invalid_install_root", `Preset install directory ${target} is not regular.`); mkdirSync(target, { recursive: true }); }
function file(files: Map<string, string>, name: string, code: string): string { const body = files.get(name); if (body === undefined) throw failure(code, `Preset package is missing ${name}.`); return body; }
function json(body: string, code: string): unknown { try { return JSON.parse(body); } catch { throw failure(code, "JSON input is invalid."); } }
function hash(body: string): string { return createHash("sha256").update(body).digest("hex"); }
function key(verticalId: string, id: string): string { return `${verticalId}\0${id}`; }
function inside(root: string, target: string): boolean { const relative = path.relative(root, target); return relative !== "" && !relative.startsWith("..") && !path.isAbsolute(relative); }
function failure(code: string, message: string): PresetFailure { return { code, message }; }
function asFailure(error: unknown): PresetFailure { return error && typeof error === "object" && "code" in error && "message" in error ? error as PresetFailure : failure("invalid_package", error instanceof Error ? error.message : String(error)); }
function record(value: unknown): value is Record<string, unknown> { return value !== null && typeof value === "object" && !Array.isArray(value); }
function exact(value: Record<string, unknown>, fields: readonly string[]): boolean { return Object.keys(value).length === fields.length && fields.every((field) => Object.hasOwn(value, field)); }
function strings(value: unknown): value is string[] { return Array.isArray(value) && value.every((item) => typeof item === "string" && item.trim().length > 0); }
function normalizeLocale(value: string): "zh-CN" | "en-US" { return value === "zh-CN" ? "zh-CN" : "en-US"; }
function compareVersion(left: string, right: string): number { const a = left.split(".").map(Number), b = right.split(".").map(Number); for (let index = 0; index < Math.max(a.length, b.length); index += 1) if ((a[index] ?? 0) !== (b[index] ?? 0)) return (a[index] ?? 0) > (b[index] ?? 0) ? 1 : -1; return 0; }
