import { REPLAY_TASK_GRAPH, sha256Text, taskBootstrapWritePlan, validateTaskBootstrapEvent, validateTaskIdSyntax, type ActorIdentity, type FrozenWritePlan, type TaskBootstrapBlob, type TaskBootstrapEventV1, type TaskClass, type WriteSource } from "../../kernel/src/index.ts";
import { serializePresetSnapshotV1, type PresetSnapshotV1 } from "./preset.contract.ts";
import { createRuntime, type PresetResolverOptions } from "./preset-resolver.ts";

export interface CompileTaskBootstrapInput extends PresetResolverOptions { readonly taskId: string; readonly title: string; readonly taskClass?: TaskClass; readonly presetId: string; readonly verticalId: string; readonly profileId?: string; readonly locale: string; readonly actor: ActorIdentity; readonly source: WriteSource; readonly workspaceRevision: number; readonly eventId: string; readonly opId: string; readonly occurredAt: string }
export interface CompiledTaskBootstrap { readonly event: TaskBootstrapEventV1; readonly plan: FrozenWritePlan<"TaskBootstrap">; readonly blobs: readonly TaskBootstrapBlob[]; readonly snapshot: PresetSnapshotV1; readonly documents: readonly { readonly path: string; readonly body: string; readonly mediaType: "text/markdown" | "text/plain" }[] }
export function compileTaskBootstrap(input: CompileTaskBootstrapInput): CompiledTaskBootstrap { validateTaskIdSyntax(input.taskId); if (!input.title.trim()) throw bootstrapFailure("invalid_title", "Task title is required."); const resolved = createRuntime(input).resolveInternal({ presetId: input.presetId, verticalId: input.verticalId, ...(input.profileId ? { profileId: input.profileId } : {}), locale: input.locale, purpose: "task-create" }); if (resolved.requiredTaskClass && input.taskClass === undefined) throw bootstrapFailure("task_class_required", `Preset requires caller-supplied taskClass=${resolved.requiredTaskClass}.`); if (resolved.requiredTaskClass && input.taskClass !== resolved.requiredTaskClass) throw bootstrapFailure("task_class_mismatch", `Preset requires taskClass=${resolved.requiredTaskClass}.`);
  const snapshotBody = serializePresetSnapshotV1(resolved.snapshot), snapshotSha = sha256Text(snapshotBody), snapshotClaim = { digest: resolved.snapshot.digest, sha256: snapshotSha, size: Buffer.byteLength(snapshotBody), mediaType: "application/json" as const }, documents = resolved.documents.map((document) => ({ ...document, path: `tasks/${input.taskId}/${document.path}`, body: document.body.replaceAll("{{title}}", input.title) })), initialDocumentClaims = documents.map((document) => ({ path: document.path, sha256: sha256Text(document.body), size: Buffer.byteLength(document.body), mediaType: document.mediaType, policyId: "markdown-additive/v1" as const }));
  const event: TaskBootstrapEventV1 = { schema: "task-bootstrap-event/v1", eventId: input.eventId, workspaceRevision: input.workspaceRevision, opId: input.opId, taskId: input.taskId, type: "task_bootstrapped", actor: input.actor, source: input.source, occurredAt: input.occurredAt, payload: { task: { schema: "task/v1", taskId: input.taskId, title: input.title, taskClass: input.taskClass ?? "standard", status: "planned", graph: REPLAY_TASK_GRAPH, currentNode: "implementation", iteration: 0, createdBy: input.actor, completionGateIds: resolved.snapshot.profile.completionGateIds, presetSnapshotDigest: resolved.snapshot.digest }, presetSnapshotClaim: snapshotClaim, initialDocumentClaims } }; const issues = validateTaskBootstrapEvent(event); if (issues.length) throw bootstrapFailure("invalid_bootstrap", issues.join("; "));
  const bodies = [{ ...snapshotClaim, body: snapshotBody }, ...documents.map((document, index) => ({ ...initialDocumentClaims[index]!, body: document.body }))], blobs = [...new Map(bodies.map((blob) => [blob.sha256, blob])).values()]; return { event, plan: taskBootstrapWritePlan(event), blobs, snapshot: resolved.snapshot, documents };
}
function bootstrapFailure(code: string, message: string): Error & { readonly code: string } { return Object.assign(new Error(message), { code }); }
