import { existsSync, readFileSync } from "node:fs";
import path from "node:path";
import { resolveHarnessLayout, type ActorIdentity, type TaskClass, type WriteSource } from "../../kernel/src/index.ts";
import { compileTaskBootstrap, type CompiledTaskBootstrap } from "./preset-bootstrap.ts";
import { createCanonicalPresetResolver, installPresetPackage, uninstallPresetPackage } from "./preset-resolver.ts";

type Action = Readonly<Record<string, unknown>> & { readonly kind: string }; interface Defaults { readonly verticalId: string; readonly presetId: string; readonly profileId: string; readonly locale: string; readonly taskScaffold: string }
export async function runPresetAction(input: { readonly rootDir: string; readonly action: Action }): Promise<unknown> { const defaults = presetRuntimeDefaults(input.rootDir), resolver = createCanonicalPresetResolver(presetResolverOptions(input.rootDir, defaults)), action = input.action; if (action.kind === "preset-list") return resolver.list({ verticalId: text(action.verticalId) ?? defaults.verticalId }); if (action.kind === "preset-install") return installPresetPackage({ source: path.resolve(input.rootDir, required(action.packageSource, "packageSource")), userRoot: presetUserRoot(input.rootDir) }); if (action.kind === "preset-uninstall") return { presetId: required(action.presetId, "presetId"), removed: uninstallPresetPackage({ presetId: required(action.presetId, "presetId"), userRoot: presetUserRoot(input.rootDir) }) }; if (action.kind !== "preset-inspect" && action.kind !== "preset-check") throw coded("unsupported_command", `No preset lifecycle contract exists for ${action.kind}.`); const request = { presetId: required(action.presetId, "presetId"), verticalId: text(action.verticalId) ?? defaults.verticalId, profileId: text(action.profileId) ?? defaults.profileId, locale: text(action.locale) ?? defaults.locale, purpose: "inspect" as const }, result = await resolver.resolve(request); if (!result.ok) throw coded(result.error.code, result.error.hint); return action.kind === "preset-check" ? { valid: true, digest: result.snapshot.digest } : result.snapshot; }
export function compileRepoTaskBootstrap(input: { readonly rootDir: string; readonly action: Action; readonly taskId: string; readonly actor: ActorIdentity; readonly source: WriteSource; readonly workspaceRevision: number; readonly eventId: string; readonly opId: string; readonly occurredAt: string }): CompiledTaskBootstrap { const defaults = presetRuntimeDefaults(input.rootDir), taskClass = optionalTaskClass(input.action.taskClass); return compileTaskBootstrap({ ...presetResolverOptions(input.rootDir, defaults), taskId: input.taskId, title: required(input.action.title, "title"), ...(taskClass ? { taskClass } : {}), presetId: text(input.action.presetId) ?? defaults.presetId, verticalId: text(input.action.verticalId) ?? defaults.verticalId, profileId: text(input.action.profileId) ?? defaults.profileId, locale: text(input.action.locale) ?? defaults.locale, actor: input.actor, source: input.source, workspaceRevision: input.workspaceRevision, eventId: input.eventId, opId: input.opId, occurredAt: input.occurredAt }); }
export function presetUserRoot(rootDir: string): string { return path.join(path.resolve(rootDir), ".harness/presets"); }
export function presetRuntimeDefaults(rootDir: string): Defaults { const target = path.join(resolveHarnessLayout(rootDir).authoredRoot, "harness.yaml"), body = existsSync(target) ? readFileSync(target, "utf8") : ""; return { verticalId: setting(body, "defaultVertical") ?? "software/coding", presetId: setting(body, "defaultPreset") ?? "standard-task", profileId: setting(body, "defaultProfile") ?? "baseline", locale: setting(body, "locale") ?? "en-US", taskScaffold: setting(body, "taskScaffold") ?? "governance/task-scaffold.json" }; }
function presetResolverOptions(rootDir: string, defaults: Defaults) { const projectRoot = resolveHarnessLayout(rootDir).authoredRoot, projectScaffold = path.resolve(projectRoot, defaults.taskScaffold), relative = path.relative(projectRoot, projectScaffold); if (relative.startsWith("..") || path.isAbsolute(relative)) throw coded("invalid_task_scaffold", "settings.taskScaffold must remain inside the authored root."); const configured = defaults.taskScaffold !== "governance/task-scaffold.json" || existsSync(projectScaffold); return { userRoot: presetUserRoot(rootDir), projectRoot, ...(configured ? { projectScaffold } : {}) }; }
function setting(body: string, key: string): string | undefined { return new RegExp(`^  ${key}:\\s*([^#\\r\\n]+?)\\s*$`, "mu").exec(body)?.[1]; } function text(value: unknown): string | undefined { return typeof value === "string" && value.trim() ? value : undefined; } function required(value: unknown, field: string): string { const result = text(value); if (!result) throw coded("invalid_command", `${field} is required.`); return result; } function optionalTaskClass(value: unknown): TaskClass | undefined { if (value === undefined) return undefined; if (value === "standard" || value === "milestone" || value === "epic") return value; throw coded("invalid_task_class", "taskClass must be standard, milestone, or epic."); } function coded(code: string, message: string): Error & { readonly code: string } { return Object.assign(new Error(message), { code }); }
