#!/usr/bin/env node
import { randomUUID } from "node:crypto";
import { existsSync, readFileSync, realpathSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import type { AgentRuntimeSessionResult } from "../../daemon/src/agent-runtime-contract.ts";
import type { JsonObject } from "../../daemon/src/protocol/json-rpc-types.ts";
import { cliCommandDomains, deriveCliCapabilities, firstCliCommand, helpDomain, parseThinCommand, renderThinCapabilities, renderThinHelp, unsupportedCommandHint, type ThinCommand } from "./cli/thin-command.ts";
import { consumeKnownError, daemonAutostartFailureCode, relayRuntimeAuthTerminal, runCommandThroughDaemon, streamRuntimeThroughDaemon } from "./daemon/client.ts";

export async function main(argv: readonly string[] = process.argv.slice(2)): Promise<number> {
  const command = firstCliCommand(argv); if (argv.includes("--version") || argv.includes("-v") || command === "version") return emitMeta("version", argv.includes("--json")); if (command === "capabilities") return emitMeta("capabilities", argv.includes("--json"));
  if (argv.length === 0 || argv.includes("--help")) { const domain = helpDomain(argv);
    if (domain !== undefined && !cliCommandDomains().includes(domain)) { emit(cliFailure("help", "unsupported_command", unsupportedCommandHint([domain])), argv.includes("--json")); return 2; }
    const rows = await taskCreateHelpCatalog(argv); console.log(rows.length === 0 && domain === undefined ? renderThinHelp() : renderThinHelp(rows, domain)); return 0; }
  if (command === "daemon" || command === "gui") { const { runDaemonControl } = await import("./daemon/control.ts"); return runDaemonControl(argv, emit); }
  const parsed = parseThinCommand(argv);
  if (!parsed.ok) { emit(cliFailure("parse", parsed.code, parsed.nextAction), parsed.json); return 2; }
  try { const receipt = isRuntimeFacadeCommand(parsed.command) ? await runRuntimeFacadeCommand(parsed.command) : await runCommandThroughDaemon(parsed.command, (phase) => emit(phase, parsed.command.json)); emit(receipt, parsed.command.json); return Number.isInteger(receipt.exitCode) ? Number(receipt.exitCode) : receipt.ok === true ? 0 : 1; } catch (error) { const autostartCode = daemonAutostartFailureCode(error); emit(cliFailure(parsed.command.action.kind, autostartCode ?? "daemon_unavailable", autostartCode ? error instanceof Error ? error.message : String(error) : `Local daemon request failed. Cause: ${error instanceof Error ? error.message : String(error)}`), parsed.command.json); return 1; }
}

export function resolveCliVersion(): string { let dir = path.dirname(fileURLToPath(import.meta.url)); for (let depth = 0; depth < 8; depth += 1) { const candidate = path.join(dir, "package.json"); if (existsSync(candidate)) { const pkg = JSON.parse(readFileSync(candidate, "utf8")) as { readonly name?: unknown; readonly version?: unknown }; if (pkg.name === "@harness-anything/cli" && typeof pkg.version === "string") return pkg.version; } const parent = path.dirname(dir); if (parent === dir) break; dir = parent; } throw new Error("CLI version could not be derived from package.json."); }
function emitMeta(command: "version" | "capabilities", json: boolean): number { if (command === "capabilities") { const capabilities = deriveCliCapabilities(); console.log(json ? JSON.stringify(capabilities) : renderThinCapabilities()); return 0; } const version = resolveCliVersion(); console.log(json ? JSON.stringify({ ok: true, command, version }) : version); return 0; }

async function taskCreateHelpCatalog(argv: readonly string[]): Promise<Array<{ id: string; title: string; description: string; validity: string; errorCode?: string }>> { if (argv[0] !== "task" || argv[1] !== "create") return []; const globals = argv.flatMap((value, index) => value === "--json" ? [value] : value === "--root" || value === "--repo" ? [value, argv[index + 1] ?? ""] : []), parsed = parseThinCommand(["preset", "list", ...globals]); if (!parsed.ok) return []; try { const receipt = await runCommandThroughDaemon(parsed.command, undefined, { autostart: false }), rows = typeof receipt.evidence === "string" ? JSON.parse(receipt.evidence) as unknown : null; return Array.isArray(rows) ? rows.filter((row): row is { id: string; title: string; description: string; validity: string; errorCode?: string } => !!row && typeof row === "object" && ["id", "title", "description", "validity"].every((key) => typeof (row as Record<string, unknown>)[key] === "string")) : []; } catch { return []; } }
function cliFailure(command: string, code: string, nextAction: string): Record<string, unknown> { return { schema: "command-receipt/v2", ok: false, command, outcome: "op_rejected", opId: "N/A", origin: "cli", code, evidence: `rejection:${code}`, error: { code, hint: nextAction }, nextAction }; }
export function emit(receipt: Record<string, unknown>, json: boolean): void {
  if (json) console.log(JSON.stringify(receipt));
  else if (receipt.ok === true || receipt.command === "migrate-import" && typeof receipt.summary === "string") { const summary = contractMigrationDryRunSummary(receipt); console.log(String(summary ?? (receipt.command === "doc-show" ? receipt.evidence : receipt.command === "init" ? [String(receipt.summary), `outcome: ${receipt.outcome ?? "applied"}`, ...["created", "updated", "preserved", "drifted"].map((key) => `${key}: ${JSON.stringify(receipt[key] ?? [])}`), `commit: ${String(receipt.commit ?? "none")}`, `next: ${String(receipt.next ?? "")}`].join("\n") : receipt.summary ?? `${receipt.command ?? "command"}: ${receipt.outcome ?? "applied"}`))); }
  else console.error(`error code=${String((receipt.error as { code?: unknown } | undefined)?.code ?? "unknown")} hint=${String(receipt.nextAction ?? receipt.next ?? "Command failed.")}`);
}
function isRuntimeFacadeCommand(command: ThinCommand): boolean { return command.method.startsWith("repo.agentRuntime.") || command.method.startsWith("repo.runtimeInstance.auth."); }
async function runRuntimeFacadeCommand(command: ThinCommand, writeActivity: (text: string) => void = (text) => process.stderr.write(text)): Promise<JsonObject> { const action = command.action;
  if (command.method.startsWith("repo.runtimeInstance.auth.")) return runRuntimeAuthCommand(command, writeActivity);
  if (action.kind === "runtime-status") { if (action.wait === true) return waitForRuntime(command, String(action.runtimeSessionId), !command.json && action.noStream !== true, writeActivity); const { wait: _wait, noStream: _noStream, ...readAction } = action, result = await runCommandThroughDaemon({ ...command, action: readAction }); return result.ok === true ? { ...result, command: action.kind, summary: renderRuntimeStatus(result) } : result; }
  if (action.kind === "runtime-cancel") { const { noStream: _noStream, ...rpcAction } = action; const result = await runCommandThroughDaemon({ ...command, action: rpcAction }); return result.ok === true ? { ...result, summary: `runtime-cancel: ${String(result.detail ?? "cancelled")}` } : result; }
  let prompt: string; try { prompt = typeof action.prompt === "string" ? action.prompt : readFileSync(path.resolve(command.rootDir, String(action.promptFile)), "utf8"); } catch (error) { return runtimeRejected(action.kind, "prompt_file_unreadable", `Could not read --prompt-file: ${error instanceof Error ? error.message : String(error)}`); }
  const { promptFile: _promptFile, noStream: _noStream, ...spawnAction } = action, spawned = await runCommandThroughDaemon({ ...command, action: { ...spawnAction, prompt, ...(typeof action.promptFile === "string" ? { promptSource: action.promptFile } : {}), idempotencyKey: action.idempotencyKey ?? `runtime-cli-${randomUUID()}` } }); if (spawned.ok !== true || typeof spawned.runtimeSessionId !== "string") return spawned;
  return waitForRuntime(command, spawned.runtimeSessionId, !command.json && action.noStream !== true, writeActivity, spawned);
}
async function waitForRuntime(command: ThinCommand, runtimeSessionId: string, stream: boolean, writeActivity: (text: string) => void, spawned?: JsonObject): Promise<JsonObject> { const readCommand = { ...command, method: "repo.agentRuntime.sessions.read", action: { kind: "runtime-status", runtimeSessionId } }, read = () => runCommandThroughDaemon(readCommand), attaching = stream ? streamRuntimeThroughDaemon(command, runtimeSessionId, (value) => renderRuntimeFrames(value, writeActivity)).then((detach) => ({ detach }), (error: unknown) => ({ error })) : undefined; let current = await read(); if (current.ok !== true) { const attached = await attaching; if (attached && "detach" in attached) attached.detach(); return current; } let detach: (() => void) | undefined;
  if (attaching) { const attached = await attaching; if ("detach" in attached) detach = attached.detach; else try { detach = await streamRuntimeThroughDaemon(command, runtimeSessionId, (value) => renderRuntimeFrames(value, writeActivity)); } catch (error) { consumeKnownError(error); writeActivity(`[stream] ${error instanceof Error ? error.message : String(error)}\n`); } }
  try { while (((current as unknown as AgentRuntimeSessionResult).session.activity.outcome) === null) { await new Promise((resolve) => setTimeout(resolve, 50)); current = await read(); if (current.ok !== true) return current; } } finally { detach?.(); }
  const result = current as unknown as AgentRuntimeSessionResult, outcome = result.session.activity.outcome!, text = result.result?.text ?? "", commandName = spawned ? "runtime-run" : "runtime-status"; return { ...current, command: commandName, outcome, runtimeSessionId, ...(spawned ? { spawn: spawned } : {}), summary: text || `${commandName}: ${outcome}`, exitCode: outcome === "succeeded" ? 0 : 1 };
}
function renderRuntimeFrames(value: unknown, write: (text: string) => void): void { if (!value || typeof value !== "object") return; const record = value as Record<string, unknown>; if (Array.isArray(record.events)) { for (const event of record.events) renderRuntimeFrames(event, write); return; } if (record.type === "activity" && typeof record.content === "string") write(`[${String(record.activity)}] ${record.content}\n`); }
// Sign-in is interactive by design: the daemon spawns the provider CLI on the instance's isolated
// state root inside a daemon-owned PTY, and this bridge puts the operator's terminal in front of
// it. The person completes the provider's own prompts; the CLI never sees or handles credentials.
async function runRuntimeAuthCommand(command: ThinCommand, writeActivity: (text: string) => void): Promise<JsonObject> { const spawned = await runCommandThroughDaemon({ ...command, action: { ...command.action, idempotencyKey: typeof command.action.idempotencyKey === "string" ? command.action.idempotencyKey : `runtime-auth-${randomUUID()}` } });
  if (spawned.ok !== true || typeof spawned.sessionId !== "string") return spawned;
  try { const exitCode = await relayRuntimeAuthTerminal(command, spawned.sessionId, writeActivity); return { ...spawned, command: command.action.kind, exitCode, summary: `${command.action.kind}: provider terminal exited ${exitCode}` }; }
  catch (error) { return runtimeRejected(command.action.kind, "daemon_disconnect", `The sign-in terminal stream failed: ${error instanceof Error ? error.message : String(error)}. The isolated state root keeps whatever the provider already stored; re-run the command to try again.`); }
}
function renderRuntimeStatus(value: JsonObject): string { if (value.session && typeof value.session === "object") { const session = value.session as Record<string, unknown>, activity = session.activity as Record<string, unknown>; return [`session: ${session.runtimeSessionId}`, `instance: ${session.instanceId}`, `provider-session: ${session.providerSessionId ?? "-"}`, `liveness: ${session.liveness}`, `outcome: ${activity.outcome ?? "running"}`, `result: ${activity.resultRef ?? "-"}`].join("\n"); } const sessions = Array.isArray(value.sessions) ? value.sessions as Record<string, unknown>[] : []; return sessions.length ? ["SESSION\tINSTANCE\tLIVENESS\tOUTCOME\tRESULT", ...sessions.map((session) => { const activity = session.activity as Record<string, unknown>; return `${session.runtimeSessionId}\t${session.instanceId}\t${session.liveness}\t${activity.outcome ?? "running"}\t${activity.resultRef ?? "-"}`; })].join("\n") : "No runtime sessions."; }
function runtimeRejected(command: string, code: string, hint: string): JsonObject { return { schema: "command-receipt/v2", ok: false, command, outcome: "op_rejected", opId: "N/A", origin: "cli", code, evidence: `rejection:${code}`, error: { code, hint }, nextAction: hint }; }
function contractMigrationDryRunSummary(receipt: Record<string, unknown>): string | undefined {
  if (receipt.command !== "task-contract-migrate" || typeof receipt.evidence !== "string") return undefined;
  let payload: unknown; try { payload = JSON.parse(receipt.evidence); } catch (error) { consumeKnownError(error); return undefined; }
  if (!payload || typeof payload !== "object" || Array.isArray(payload)) return undefined;
  const report = (payload as Record<string, unknown>).report, manual = (payload as Record<string, unknown>).manual;
  if ((payload as Record<string, unknown>).applied !== false || !Array.isArray(report) || !Array.isArray(manual)) return undefined;
  const rows = report.map(renderReceiptRow), scalars = Object.entries(payload).filter(([key, value]) => key !== "report" && key !== "manual" && (value === null || typeof value !== "object")).map(([key, value]) => `${key}=${String(value)}`).join("  ");
  return [`report:\n${rows.length ? rows.join("\n") : "(none)"}`, scalars].filter(Boolean).join("\n");
}
function renderReceiptRow(row: unknown): string { return row && typeof row === "object" && !Array.isArray(row) ? Object.values(row).filter((value) => value === null || typeof value !== "object").map((value) => String(value)).join("\t") : String(row); }
function isCliEntrypoint(): boolean { const invoked = process.argv[1]; if (!invoked) return false; try { return realpathSync(invoked) === realpathSync(fileURLToPath(import.meta.url)); } catch { return invoked.endsWith("packages/cli/src/index.ts"); } }
if (isCliEntrypoint()) process.exitCode = await main();
