import { createHash } from "node:crypto";
import { appendFileSync, closeSync, existsSync, fsyncSync, lstatSync, mkdirSync, openSync, readFileSync, renameSync, statSync, writeFileSync } from "node:fs";
import path from "node:path";
import { createServer, type Server, type TLSSocket } from "node:tls";
import { resolveHarnessLayout, sha256Bytes, type WriteReceipt } from "../../../kernel/src/index.ts";
import type { DaemonHost } from "../daemon-host.ts";
import { FLEET_CHUNK_BYTES, FLEET_FRAME_BYTES, FleetUtf8LineDecoder, fleetManifestDigest, parseFleetFrame, serializeFleetFrame, type FleetAssignmentBinding, type FleetBlob, type FleetCut, type FleetDescriptor, type FleetEntry, type FleetFrameV1 } from "./contract.ts";

export interface FleetAssignmentRecord extends FleetAssignmentBinding { readonly viewId: string; readonly expiresAt: string }
export interface FleetCenterOptions { readonly host: Pick<DaemonHost, "run" | "status">; readonly stateRoot: string; readonly key: string | Buffer; readonly cert: string | Buffer; readonly port?: number; readonly hostname?: string; readonly now?: () => string; readonly authenticate: (nodeId: string, credential: string) => boolean | Promise<boolean>; readonly isNodeActive?: (nodeId: string) => boolean | Promise<boolean>; readonly resolveAssignment: (assignmentId: string) => FleetAssignmentRecord | null | Promise<FleetAssignmentRecord | null> }
export interface FleetTlsCenter { readonly port: number; readonly close: () => Promise<void>; readonly replicaReceipt: (nodeId: string, viewId: string, repoId: string) => WriteReceipt | null }
type BodyEntry = FleetEntry & { readonly body: string }; type Upload = { nodeId: string; assignmentId: string; repoId: string; content: FleetBlob; descriptor: FleetDescriptor | null };
type Transfer = { nodeId: string; repoId: string; viewId: string; transferId: string; cut: FleetCut; digest: string; fromTransferId: string | null; entries: BodyEntry[]; receipt: WriteReceipt; acked: boolean };
type Cursor = { nodeId: string; repoId: string; viewId: string; transferId: string; cut: FleetCut; digest: string }; type State = { uploads: Record<string, Upload>; transfers: Record<string, Transfer>; cursors: Record<string, Cursor> };
type SessionWindow = { readonly uploads: Set<string>; readonly transfers: Set<string> };
class FleetFault extends Error { readonly code: string; readonly retryable: boolean; readonly resumeOffset: number | null; constructor(code: string, message: string, retryable = false, resumeOffset: number | null = null) { super(message); this.code = code; this.retryable = retryable; this.resumeOffset = resumeOffset; } }

export async function listenFleetTls(options: FleetCenterOptions): Promise<FleetTlsCenter> {
  mkdirSync(options.stateRoot, { recursive: true }); const stateFile = path.join(options.stateRoot, "state.json"), state = loadState(stateFile), now = options.now ?? (() => new Date().toISOString());
  const persist = () => durableJson(stateFile, state), cursorKey = (nodeId: string, viewId: string, repoId: string) => `${nodeId}\0${viewId}\0${repoId}`;
  const auth = (assignment: FleetAssignmentRecord) => ({ transportKind: "fleet-tls" as const, assignmentBinding: assignment });
  const assignment = async (nodeId: string, assignmentId: string) => { const value = await options.resolveAssignment(assignmentId); if (!value || value.nodeId !== nodeId || value.paths.length === 0 || value.paths.length > 128 || Date.parse(value.expiresAt) <= Date.parse(now())) throw new FleetFault("assignment_rejected", "Assignment is absent, expired, or bound to another node."); return value; };
  const repoRoot = (repoId: string) => { const found = options.host.status().repos.find((repo) => repo.repoId === repoId && repo.state === "attached"); if (!found) throw new FleetFault("repo_unavailable", `Repo ${repoId} is unavailable.`, true); return found.rootDir; };
  const safeLocal = (repoId: string, child: string) => { const local = resolveHarnessLayout(repoRoot(repoId)).localRoot, target = path.join(local, child); if (existsSync(local) && lstatSync(local).isSymbolicLink() || existsSync(target) && lstatSync(target).isSymbolicLink()) throw new FleetFault("unsafe_staging", "Fleet staging cannot traverse a symbolic link."); return target; }, uploadPath = (uploadId: string, upload = state.uploads[uploadId]) => { if (!upload) throw new FleetFault("upload_unknown", "Upload metadata is missing."); return path.join(safeLocal(upload.repoId, "fleet-uploads"), `${uploadId}.part`); };
  const handle = async (nodeId: string, frame: FleetFrameV1, window: SessionWindow): Promise<readonly FleetFrameV1[]> => {
    if (frame.schema === "fleet.assignment.get/v1") { const a = await assignment(nodeId, frame.assignmentId), status = await options.host.run(a.repoId, { kind: "doc-status", paths: a.paths }, auth(a)), baseLedgerSha = status.detail?.kind === "doc_sync" ? status.detail.currentLedgerSha : null; if (!baseLedgerSha) throw new FleetFault("projection_pending", "Current ledger cut is unavailable.", true); return [{ schema: "fleet.assignment.result/v1", messageId: mid(frame.messageId, "assignment"), inReplyTo: frame.messageId, assignmentId: a.assignmentId, repoId: a.repoId, taskId: a.taskId, executionId: a.executionId, paths: a.paths, baseLedgerSha, expiresAt: a.expiresAt }]; }
    if (frame.schema === "fleet.upload.begin/v1") { const a = await assignment(nodeId, frame.assignmentId), uploadId = digestId(nodeId, a.assignmentId, frame.content.sha256, String(frame.content.size), frame.content.mediaType); let upload = state.uploads[uploadId]; if (upload && JSON.stringify(upload.content) !== JSON.stringify(frame.content)) throw new FleetFault("upload_conflict", "Upload identity conflicts with persisted metadata."); if (!upload && Object.keys(state.uploads).length >= 64) throw new FleetFault("busy", "Upload recovery window is full.", true); if (!upload) upload = state.uploads[uploadId] = { nodeId, assignmentId: a.assignmentId, repoId: a.repoId, content: frame.content, descriptor: null }; const file = uploadPath(uploadId, upload); if (upload.descriptor && !existsSync(path.join(safeLocal(a.repoId, "doc-sync-claims"), path.basename(upload.descriptor.ref)))) upload.descriptor = null; if (!upload.descriptor) { mkdirSync(path.dirname(file), { recursive: true }); if (!existsSync(file)) writeFileSync(file, ""); } persist();
      if (!window.uploads.has(uploadId) && window.uploads.size >= 8) throw new FleetFault("busy", "Session already has eight active uploads.", true, existsSync(file) ? statSync(file).size : 0); window.uploads.add(uploadId); return [{ schema: "fleet.upload.ready/v1", messageId: mid(frame.messageId, "ready"), inReplyTo: frame.messageId, uploadId, resumeOffset: upload.descriptor ? upload.content.size : existsSync(file) ? statSync(file).size : 0, status: upload.descriptor ? "already_staged" : "receiving" }]; }
    if (frame.schema === "fleet.upload.chunk/v1") { ownedUpload(state, nodeId, frame.uploadId); const file = uploadPath(frame.uploadId), bytes = Buffer.from(frame.dataBase64, "base64"), length = existsSync(file) ? statSync(file).size : 0; if (frame.offset > length) throw new FleetFault("upload_gap", "Chunk offset is beyond the durable prefix.", true, length); if (frame.offset < length) { const prior = readFileSync(file).subarray(frame.offset, frame.offset + bytes.length); if (!prior.equals(bytes)) throw new FleetFault("upload_replay_mismatch", "Replayed chunk differs from durable bytes."); } else { appendFileSync(file, bytes); syncFile(file); } return [{ schema: "fleet.upload.ready/v1", messageId: mid(frame.messageId, "chunk"), inReplyTo: frame.messageId, uploadId: frame.uploadId, resumeOffset: statSync(file).size, status: "receiving" }]; }
    if (frame.schema === "fleet.upload.finish/v1") { const upload = state.uploads[frame.uploadId]; if (!upload || upload.nodeId !== nodeId) throw new FleetFault("upload_unknown", "Upload is unknown or belongs to another node."); const wasStaged = upload.descriptor !== null, file = uploadPath(frame.uploadId, upload), a = await assignment(nodeId, upload.assignmentId), descriptor = upload.descriptor ?? { ref: `doc-sync-claims/${frame.uploadId}`, ...upload.content }, target = path.join(safeLocal(a.repoId, "doc-sync-claims"), frame.uploadId); if (!upload.descriptor) { const source = existsSync(file) ? file : target; if (!existsSync(source)) throw new FleetFault("upload_missing", "Durable upload prefix is missing.", true, 0); const bytes = readFileSync(source); if (bytes.byteLength !== upload.content.size || sha256Bytes(bytes) !== upload.content.sha256) throw new FleetFault("content_claim_mismatch", "Upload size or digest does not match the declaration.", true, bytes.byteLength); mkdirSync(path.dirname(target), { recursive: true }); if (source !== target) { renameSync(source, target); syncDir(path.dirname(source)); } syncDir(path.dirname(target)); upload.descriptor = descriptor; persist(); } window.uploads.delete(frame.uploadId); return [{ schema: "fleet.upload.result/v1", messageId: mid(frame.messageId, "result"), inReplyTo: frame.messageId, status: wasStaged ? "already_staged" : "staged", descriptor }]; }
    if (frame.schema === "fleet.doc.submit/v1") { const a = await assignment(nodeId, frame.assignmentId), key = cursorKey(nodeId, a.viewId, a.repoId), previous = state.cursors[key]; if (!previous && Object.keys(state.cursors).length >= 64 || window.transfers.size >= 8) throw new FleetFault("busy", "Replica transfer window is full.", true); if (!previous && JSON.stringify(frame.changes.map((change) => change.path).sort()) !== JSON.stringify([...a.paths].sort())) throw new FleetFault("snapshot_required", "The first view cut must cover every assignment path."); reserveTransferSpace(state); const changed: BodyEntry[] = [], completedUploadIds: string[] = []; for (const change of frame.changes) { const owned = Object.entries(state.uploads).find(([, candidate]) => candidate.nodeId === nodeId && candidate.assignmentId === a.assignmentId && candidate.descriptor?.ref === change.candidate.ref), upload = owned?.[1]; if (!owned || !upload || JSON.stringify(upload.descriptor) !== JSON.stringify(change.candidate)) throw new FleetFault("claim_not_owned", "Descriptor was not issued to this assignment."); completedUploadIds.push(owned[0]); const claim = path.join(safeLocal(a.repoId, "doc-sync-claims"), path.basename(change.candidate.ref)); if (existsSync(claim)) changed.push({ path: change.path, blob: { sha256: change.candidate.sha256, size: change.candidate.size, mediaType: change.candidate.mediaType }, body: readFileSync(claim, "utf8") }); }
      const receipt = await options.host.run(a.repoId, { kind: "doc-submit", executionId: a.executionId, baseLedgerSha: frame.baseLedgerSha, changes: frame.changes }, auth(a)); let transfer: Transfer | null = null; if (receipt.outcome === "applied") transfer = makeTransfer(state, a, receipt, key, changed); if (transfer) { for (const uploadId of completedUploadIds) delete state.uploads[uploadId]; window.transfers.add(transfer.transferId); persist(); } return [{ schema: "fleet.doc.result/v1", messageId: mid(frame.messageId, "doc"), inReplyTo: frame.messageId, outcome: receipt.outcome, opId: receipt.opId, revision: receipt.revision ?? null, code: receipt.code ?? null, transferId: transfer?.transferId ?? null }, ...(transfer ? transferFrames(transfer, state) : [])]; }
    if (frame.schema === "fleet.ack/v1") { const transfer = state.transfers[frame.transferId]; if (!transfer || transfer.nodeId !== nodeId) throw new FleetFault("invalid_ack", "ACK does not match an authenticated transfer."); const key = cursorKey(nodeId, transfer.viewId, transfer.repoId), prior = state.cursors[key]; if (prior && frame.cut.revision < prior.cut.revision) return [ackResult(frame.messageId, "current", state.transfers[prior.transferId]!, prior)]; if (JSON.stringify(frame.cut) !== JSON.stringify(transfer.cut) || frame.manifestDigest !== transfer.digest) throw new FleetFault("invalid_ack", "ACK cut or manifest differs from the issued transfer."); const cursor = state.cursors[key] = { nodeId, repoId: transfer.repoId, viewId: transfer.viewId, transferId: transfer.transferId, cut: transfer.cut, digest: transfer.digest }; transfer.acked = true; persist(); window.transfers.delete(frame.transferId); return [ackResult(frame.messageId, "applied", transfer, cursor)]; }
    throw new FleetFault("unexpected_direction", `Frame ${frame.schema} is not accepted by the center.`);
  };
  const server: Server = createServer({ key: options.key, cert: options.cert }, (socket) => serve(socket, options, handle)); await new Promise<void>((resolve, reject) => { server.once("error", reject); server.listen(options.port ?? 0, options.hostname ?? "127.0.0.1", () => { server.off("error", reject); resolve(); }); }); const address = server.address(); if (!address || typeof address === "string") throw new Error("Fleet TLS server did not bind a TCP port");
  return { port: address.port, close: () => new Promise((resolve, reject) => server.close((error) => error ? reject(error) : resolve())), replicaReceipt: (nodeId, viewId, repoId) => { const cursor = state.cursors[cursorKey(nodeId, viewId, repoId)], transfer = cursor && state.transfers[cursor.transferId]; return transfer ? replicaReceipt(transfer) : null; } };
}

async function serve(socket: TLSSocket, options: FleetCenterOptions, handle: (nodeId: string, frame: FleetFrameV1, window: SessionWindow) => Promise<readonly FleetFrameV1[]>): Promise<void> { let nodeId: string | null = null; const reader = new FleetUtf8LineDecoder(), window = { uploads: new Set<string>(), transfers: new Set<string>() }, send = async (frame: FleetFrameV1) => { if (socket.write(serializeFleetFrame(frame))) return; await new Promise<void>((resolve) => socket.once("drain", resolve)); };
  socket.on("data", (chunk) => { try { for (const line of reader.push(chunk)) void dispatch(line); } catch (error) { consumeKnownError(error); socket.destroy(error instanceof Error ? error : new Error(String(error))); } }); socket.on("end", () => { try { reader.finish(); } catch (error) { consumeKnownError(error); socket.destroy(error instanceof Error ? error : new Error(String(error))); } });
  const dispatch = async (line: string) => { let frame: FleetFrameV1 | null = null; try { frame = parseFleetFrame(line); if (nodeId === null) { if (frame.schema !== "fleet.session.hello/v1" || !await options.authenticate(frame.nodeId, frame.credential)) throw new FleetFault("authentication_failed", "Machine credential was rejected."); nodeId = frame.nodeId; return send({ schema: "fleet.session.ready/v1", messageId: mid(frame.messageId, "session"), inReplyTo: frame.messageId, sessionId: digestId(nodeId, String(Date.now())), maxFrameBytes: FLEET_FRAME_BYTES, chunkBytes: FLEET_CHUNK_BYTES }); } if (frame.schema === "fleet.session.hello/v1") throw new FleetFault("hello_replayed", "Session hello is only valid as the first frame."); if (options.isNodeActive && !await options.isNodeActive(nodeId)) throw new FleetFault("credential_revoked", "Node credential was revoked."); for (const response of await handle(nodeId, frame, window)) await send(response); }
    catch (error) { consumeKnownError(error); const fault = error instanceof FleetFault ? error : new FleetFault("invalid_frame", error instanceof Error ? error.message : String(error)); await send({ schema: "fleet.error/v1", messageId: mid(frame?.messageId ?? "invalid", "error"), inReplyTo: frame?.messageId ?? "invalid", code: fault.code, retryable: fault.retryable, resumeOffset: fault.resumeOffset, nextAction: fault.message }); if (fault.code === "authentication_failed" || fault.code === "credential_revoked") socket.end(); } };
}
function loadState(file: string): State { if (!existsSync(file)) return { uploads: {}, transfers: {}, cursors: {} }; const value = JSON.parse(readFileSync(file, "utf8")) as State; if (!value.uploads || !value.transfers || !value.cursors || [value.uploads, value.transfers, value.cursors].some((items) => Object.keys(items).length > 64)) throw new Error("Fleet durable state exceeds its 64-item recovery window"); return value; }
function durableJson(file: string, value: unknown): void { mkdirSync(path.dirname(file), { recursive: true }); const temp = `${file}.${process.pid}.tmp`, fd = openSync(temp, "w"); try { writeFileSync(fd, `${JSON.stringify(value)}\n`); fsyncSync(fd); } finally { closeSync(fd); } renameSync(temp, file); syncDir(path.dirname(file)); }
function syncFile(file: string): void { const fd = openSync(file, "r"); try { fsyncSync(fd); } finally { closeSync(fd); } } function syncDir(directory: string): void { const fd = openSync(directory, "r"); try { fsyncSync(fd); } finally { closeSync(fd); } }
function ownedUpload(state: State, nodeId: string, uploadId: string): Upload { const upload = state.uploads[uploadId]; if (!upload || upload.nodeId !== nodeId || upload.descriptor) throw new FleetFault("upload_unknown", "Upload is unknown, completed, or belongs to another node."); return upload; }
function makeTransfer(state: State, assignment: FleetAssignmentRecord, receipt: WriteReceipt, cursorKey: string, changed: readonly BodyEntry[]): Transfer { const existing = Object.values(state.transfers).find((value) => value.nodeId === assignment.nodeId && value.repoId === assignment.repoId && value.viewId === assignment.viewId && value.receipt.opId === receipt.opId); if (existing) return existing; if (receipt.revision === undefined || receipt.detail?.kind !== "doc_sync" || changed.length === 0) throw new FleetFault("receipt_invalid", "Applied doc receipt lacks its durable cut or frozen claim bytes."); const previous = state.cursors[cursorKey], entries = previous ? [...state.transfers[previous.transferId]!.entries] : []; for (const entry of changed) { const index = entries.findIndex((candidate) => candidate.path === entry.path); if (index < 0) entries.push(entry); else entries[index] = entry; }
  entries.sort((a, b) => a.path.localeCompare(b.path)); const digest = fleetManifestDigest(entries), cut = { revision: receipt.revision, commitSha: receipt.detail.currentLedgerSha, headDigest: `sha256:${digest}` }, transferId = digestId(assignment.nodeId, assignment.repoId, assignment.viewId, String(cut.revision), digest), transfer = { nodeId: assignment.nodeId, repoId: assignment.repoId, viewId: assignment.viewId, transferId, cut, digest, fromTransferId: previous?.transferId ?? null, entries, receipt, acked: false }; state.transfers[transferId] = transfer; return transfer; }
function transferFrames(transfer: Transfer, state: State): FleetFrameV1[] { const previous = transfer.fromTransferId, frames: FleetFrameV1[] = []; if (!previous) { frames.push({ schema: "fleet.snapshot.begin/v1", messageId: mid(transfer.transferId, "begin"), transferId: transfer.transferId, repoId: transfer.repoId, viewId: transfer.viewId, cut: transfer.cut, manifest: { digest: transfer.digest, entryCount: transfer.entries.length, totalBytes: transfer.entries.reduce((sum, entry) => sum + entry.blob.size, 0) } }, { schema: "fleet.snapshot.page/v1", messageId: mid(transfer.transferId, "page0"), transferId: transfer.transferId, pageIndex: 0, entries: transfer.entries.map(({ path: itemPath, blob }) => ({ path: itemPath, blob })) }); for (const entry of transfer.entries) frames.push(...chunks("snapshot", transfer.transferId, entry)); frames.push({ schema: "fleet.snapshot.finish/v1", messageId: mid(transfer.transferId, "finish"), transferId: transfer.transferId, manifestDigest: transfer.digest }); return frames; }
  const priorTransfer = state.transfers[previous]; if (!priorTransfer) throw new FleetFault("snapshot_required", "Previous acknowledged cut is outside retention.", true); const prior = priorTransfer.entries, priorMap = new Map(prior.map((entry) => [entry.path, entry])), nextMap = new Map(transfer.entries.map((entry) => [entry.path, entry])), changes = [...transfer.entries.filter((entry) => priorMap.get(entry.path)?.blob.sha256 !== entry.blob.sha256).map(({ path: itemPath, blob }) => ({ op: "put" as const, path: itemPath, blob })), ...prior.filter((entry) => !nextMap.has(entry.path)).map((entry) => ({ op: "delete" as const, path: entry.path }))]; frames.push({ schema: "fleet.delta.begin/v1", messageId: mid(transfer.transferId, "begin"), transferId: transfer.transferId, repoId: transfer.repoId, viewId: transfer.viewId, fromCut: priorTransfer.cut, toCut: transfer.cut, changeCount: changes.length, resultManifestDigest: transfer.digest }, { schema: "fleet.delta.page/v1", messageId: mid(transfer.transferId, "page0"), transferId: transfer.transferId, pageIndex: 0, changes }); for (const entry of transfer.entries.filter((candidate) => changes.some((change) => change.op === "put" && change.blob.sha256 === candidate.blob.sha256))) frames.push(...chunks("delta", transfer.transferId, entry)); frames.push({ schema: "fleet.delta.finish/v1", messageId: mid(transfer.transferId, "finish"), transferId: transfer.transferId, resultManifestDigest: transfer.digest }); return frames; }
function chunks(kind: "snapshot" | "delta", transferId: string, entry: BodyEntry): FleetFrameV1[] { const bytes = Buffer.from(entry.body), frames: FleetFrameV1[] = []; for (let offset = 0; offset < bytes.length; offset += FLEET_CHUNK_BYTES) frames.push({ schema: `fleet.${kind}.chunk/v1`, messageId: mid(transferId, `chunk${offset}`), transferId, blobSha256: entry.blob.sha256, offset, dataBase64: bytes.subarray(offset, offset + FLEET_CHUNK_BYTES).toString("base64") } as FleetFrameV1); return frames; }
function ackResult(inReplyTo: string, outcome: "applied" | "current", transfer: Transfer, cursor: Cursor): FleetFrameV1 { return { schema: "fleet.ack.result/v1", messageId: mid(inReplyTo, "ack"), inReplyTo, outcome, opId: transfer.receipt.opId, revision: transfer.receipt.revision ?? cursor.cut.revision, viewId: cursor.viewId, ackCut: cursor.cut.revision, code: null }; }
function replicaReceipt(transfer: Transfer): WriteReceipt { return { ...transfer.receipt, visibility: { kind: "replica", viewId: transfer.viewId }, proof: { ...transfer.receipt.proof!, ackCut: transfer.cut.revision, worktreeVisible: true } }; }
function reserveTransferSpace(state: State): void { if (Object.keys(state.transfers).length < 64) return; const retained = new Set(Object.values(state.cursors).map((cursor) => cursor.transferId)), removable = Object.keys(state.transfers).find((transferId) => state.transfers[transferId]?.acked && !retained.has(transferId)); if (!removable) throw new FleetFault("busy", "Transfer retention is full of active or current ACK state.", true); delete state.transfers[removable]; }
function digestId(...parts: string[]): string { return createHash("sha256").update(parts.join("\0")).digest("hex").slice(0, 32); } function mid(seed: string, suffix: string): string { return `${seed.slice(0, 64)}_${suffix}`.slice(0, 96); }
function consumeKnownError(error: unknown): void { void error; }
