import { createHash } from "node:crypto";
import { appendFileSync, closeSync, existsSync, fsyncSync, lstatSync, mkdirSync, openSync, readFileSync, renameSync, statSync, writeFileSync } from "node:fs";
import path from "node:path";
import { createServer, type Server, type TLSSocket } from "node:tls";
import { consumeKnownError } from "../../../kernel/src/index.ts";
import { resolveHarnessLayout, sha256Bytes, type WriteReceipt } from "../../../kernel/src/index.ts";
import type { DaemonHost } from "../daemon-host.ts";
import { FLEET_CHUNK_BYTES, FLEET_FRAME_BYTES, FLEET_KEY_SEND_WINDOW_BYTES, FLEET_SESSION_SEND_WINDOW_BYTES, FleetUtf8LineDecoder, fleetManifestDigest, parseFleetFrame, serializeFleetFrame, type FleetAssignmentBinding, type FleetBlob, type FleetCut, type FleetDescriptor, type FleetEntry, type FleetFrameV1 } from "./contract.ts";
import { openFleetLeaseBroker, type FleetLeaseBroker } from "./lease-broker.ts";
import { openReplicaAckStore, type ReplicaAckStore, type ReplicaDeliveryKey, type ReplicaOffer } from "./replica-ack-store.ts";
import type { ReplicaCutSource, SnapshotCut } from "./replica-cut-store.ts";

export interface FleetAssignmentRecord extends FleetAssignmentBinding { readonly viewId: string; readonly expiresAt: string }
export interface FleetCenterOptions { readonly host: Pick<DaemonHost, "replica" | "run" | "status">; readonly stateRoot: string; readonly key: string | Buffer; readonly cert: string | Buffer; readonly replicaDiskQuotaBytes?: number; readonly port?: number; readonly hostname?: string; readonly now?: () => string; readonly authenticate: (nodeId: string, credential: string) => boolean | Promise<boolean>; readonly isNodeActive?: (nodeId: string) => boolean | Promise<boolean>; readonly resolveAssignment: (assignmentId: string) => FleetAssignmentRecord | null | Promise<FleetAssignmentRecord | null> }
export interface FleetReplicaStatus extends ReplicaDeliveryKey { readonly centerRevision: number; readonly centerEventAt: string | null; readonly centerManifestBytes: number; readonly ackRevision: number | null; readonly ackCutEventAt: string | null; readonly ackedAt: string | null; readonly lagRevisions: number; readonly lagMs: number | null; readonly catchUpBytes: number; readonly delivery: "current" | "delta" | "snapshot_required" | "busy" | "degraded"; readonly activeTransfers: number; readonly sendWindowBytes: number; readonly sendQuotaBytes: number; readonly diskQuotaBytes: number | null }
export interface FleetTlsCenter { readonly port: number; readonly close: () => Promise<void>; readonly replicaReceipt: (opId: string, nodeId: string, viewId: string, repoId: string) => WriteReceipt; readonly status: () => { readonly replicas: readonly FleetReplicaStatus[]; readonly leases: ReturnType<FleetLeaseBroker["status"]> } }
type Upload = { nodeId: string; assignmentId: string; repoId: string; content: FleetBlob; descriptor: FleetDescriptor | null }; type State = { uploads: Record<string, Upload> };
type SessionWindow = { readonly uploads: Set<string>; readonly keys: Set<string>; readonly offers: Map<string, ReplicaDeliveryKey> }; type Delivery = { readonly key: string | null; readonly frames: AsyncIterable<FleetFrameV1> };
class FleetFault extends Error { readonly code: string; readonly retryable: boolean; readonly resumeOffset: number | null; constructor(code: string, message: string, retryable = false, resumeOffset: number | null = null) { super(message); this.code = code; this.retryable = retryable; this.resumeOffset = resumeOffset; } }

export async function listenFleetTls(options: FleetCenterOptions): Promise<FleetTlsCenter> {
  mkdirSync(options.stateRoot, { recursive: true }); const stateFile = path.join(options.stateRoot, "state.json"), state = loadState(stateFile), ackStore = openReplicaAckStore(options.stateRoot), now = options.now ?? (() => new Date().toISOString()), knownKeys = new Map<string, ReplicaDeliveryKey>();
  const leaseBroker = openFleetLeaseBroker({ stateRoot: options.stateRoot, host: options.host, resolveAssignment: options.resolveAssignment, now, env: process.env });
  const persist = () => writeCenterDurableJson(stateFile, state), keyId = (key: ReplicaDeliveryKey) => `${key.nodeId}\0${key.viewId}\0${key.repoId}`, auth = (assignment: FleetAssignmentRecord) => ({ transportKind: "fleet-tls" as const, assignmentBinding: assignment });
  const assignment = async (nodeId: string, assignmentId: string) => { const value = await options.resolveAssignment(assignmentId); if (!value || value.nodeId !== nodeId || value.paths.length === 0 || value.paths.length > 128 || Date.parse(value.expiresAt) <= Date.parse(now())) throw new FleetFault("assignment_rejected", "Assignment is absent, expired, or bound to another node."); return value; };
  const repoRoot = (repoId: string) => { const found = options.host.status().repos.find((repo) => repo.repoId === repoId && repo.state === "attached"); if (!found) throw new FleetFault("repo_unavailable", `Repo ${repoId} is unavailable.`, true); return found.rootDir; };
  const safeLocal = (repoId: string, child: string) => { const local = resolveHarnessLayout(repoRoot(repoId)).localRoot, target = path.join(local, child); if (existsSync(local) && lstatSync(local).isSymbolicLink() || existsSync(target) && lstatSync(target).isSymbolicLink()) throw new FleetFault("unsafe_staging", "Fleet staging cannot traverse a symbolic link."); return target; }, uploadPath = (uploadId: string, upload = state.uploads[uploadId]) => { if (!upload) throw new FleetFault("upload_unknown", "Upload metadata is missing."); return path.join(safeLocal(upload.repoId, "fleet-uploads"), `${uploadId}.part`); };
  const handle = async (nodeId: string, frame: FleetFrameV1, window: SessionWindow, clientGone: () => boolean = () => false): Promise<Delivery> => {
    if (frame.schema === "fleet.assignment.get/v1") { const a = await assignment(nodeId, frame.assignmentId), status = await options.host.run(a.repoId, { kind: "doc-status", paths: a.paths }, auth(a)), baseLedgerSha = status.detail?.kind === "doc_sync" ? status.detail.currentLedgerSha : null; if (!baseLedgerSha) throw new FleetFault("projection_pending", "Current ledger cut is unavailable.", true); return immediate({ schema: "fleet.assignment.result/v1", messageId: mid(frame.messageId, "assignment"), inReplyTo: frame.messageId, assignmentId: a.assignmentId, repoId: a.repoId, taskId: a.taskId, executionId: a.executionId, paths: a.paths, baseLedgerSha, expiresAt: a.expiresAt }); }
    if (frame.schema === "fleet.upload.begin/v1") { const a = await assignment(nodeId, frame.assignmentId), uploadId = digestId(nodeId, a.assignmentId, frame.content.sha256, String(frame.content.size), frame.content.mediaType); let upload = state.uploads[uploadId]; if (upload && JSON.stringify(upload.content) !== JSON.stringify(frame.content)) throw new FleetFault("upload_conflict", "Upload identity conflicts with persisted metadata."); if (!upload && Object.keys(state.uploads).length >= 64) throw new FleetFault("busy", "Upload recovery window is full.", true); if (!upload) upload = state.uploads[uploadId] = { nodeId, assignmentId: a.assignmentId, repoId: a.repoId, content: frame.content, descriptor: null }; const file = uploadPath(uploadId, upload); if (upload.descriptor && !existsSync(path.join(safeLocal(a.repoId, "doc-sync-claims"), path.basename(upload.descriptor.ref)))) upload.descriptor = null; if (!upload.descriptor) { mkdirSync(path.dirname(file), { recursive: true }); if (!existsSync(file)) writeFileSync(file, ""); } persist(); if (!window.uploads.has(uploadId) && window.uploads.size >= 8) throw new FleetFault("busy", "Session already has eight active uploads.", true, existsSync(file) ? statSync(file).size : 0); window.uploads.add(uploadId); return immediate({ schema: "fleet.upload.ready/v1", messageId: mid(frame.messageId, "ready"), inReplyTo: frame.messageId, uploadId, resumeOffset: upload.descriptor ? upload.content.size : existsSync(file) ? statSync(file).size : 0, status: upload.descriptor ? "already_staged" : "receiving" }); }
    if (frame.schema === "fleet.upload.chunk/v1") { ownedUpload(state, nodeId, frame.uploadId); const file = uploadPath(frame.uploadId), bytes = Buffer.from(frame.dataBase64, "base64"), length = existsSync(file) ? statSync(file).size : 0; if (frame.offset > length) throw new FleetFault("upload_gap", "Chunk offset is beyond the durable prefix.", true, length); if (frame.offset < length) { if (!readFileSync(file).subarray(frame.offset, frame.offset + bytes.length).equals(bytes)) throw new FleetFault("upload_replay_mismatch", "Replayed chunk differs from durable bytes."); } else { appendFileSync(file, bytes); syncFile(file); } return immediate({ schema: "fleet.upload.ready/v1", messageId: mid(frame.messageId, "chunk"), inReplyTo: frame.messageId, uploadId: frame.uploadId, resumeOffset: statSync(file).size, status: "receiving" }); }
    if (frame.schema === "fleet.upload.finish/v1") { const upload = state.uploads[frame.uploadId]; if (!upload || upload.nodeId !== nodeId) throw new FleetFault("upload_unknown", "Upload is unknown or belongs to another node."); const wasStaged = upload.descriptor !== null, file = uploadPath(frame.uploadId, upload), a = await assignment(nodeId, upload.assignmentId), descriptor = upload.descriptor ?? { ref: `doc-sync-claims/${frame.uploadId}`, ...upload.content }, target = path.join(safeLocal(a.repoId, "doc-sync-claims"), frame.uploadId); if (!upload.descriptor) { const source = existsSync(file) ? file : target; if (!existsSync(source)) throw new FleetFault("upload_missing", "Durable upload prefix is missing.", true, 0); const bytes = readFileSync(source); if (bytes.byteLength !== upload.content.size || sha256Bytes(bytes) !== upload.content.sha256) throw new FleetFault("content_claim_mismatch", "Upload size or digest does not match the declaration.", true, bytes.byteLength); mkdirSync(path.dirname(target), { recursive: true }); if (source !== target) { renameSync(source, target); syncDir(path.dirname(source)); } syncDir(path.dirname(target)); upload.descriptor = descriptor; persist(); } window.uploads.delete(frame.uploadId); return immediate({ schema: "fleet.upload.result/v1", messageId: mid(frame.messageId, "result"), inReplyTo: frame.messageId, status: wasStaged ? "already_staged" : "staged", descriptor }); }
    if (frame.schema === "fleet.doc.submit/v1") { const a = await assignment(nodeId, frame.assignmentId), completed: string[] = []; for (const change of frame.changes) { const owned = Object.entries(state.uploads).find(([, candidate]) => candidate.nodeId === nodeId && candidate.assignmentId === a.assignmentId && candidate.descriptor?.ref === change.candidate.ref), upload = owned?.[1]; if (!owned || !upload || JSON.stringify(upload.descriptor) !== JSON.stringify(change.candidate)) throw new FleetFault("claim_not_owned", "Descriptor was not issued to this assignment."); completed.push(owned[0]); } const receipt = await options.host.run(a.repoId, { kind: "doc-submit", executionId: a.executionId, baseLedgerSha: frame.baseLedgerSha, changes: frame.changes }, auth(a)); if (receipt.outcome === "applied") { for (const uploadId of completed) delete state.uploads[uploadId]; persist(); } return immediate({ schema: "fleet.doc.result/v1", messageId: mid(frame.messageId, "doc"), inReplyTo: frame.messageId, outcome: receipt.outcome, opId: receipt.opId, revision: receipt.revision ?? null, code: receipt.code ?? null }); }
    if (frame.schema === "fleet.replica.pull/v1") { if (!Number.isSafeInteger(options.replicaDiskQuotaBytes) || options.replicaDiskQuotaBytes! <= 0) throw new FleetFault("replica_quota_required", "Replica admission requires an explicit persistent disk quota."); const a = await assignment(nodeId, frame.assignmentId), replica = options.host.replica(a.repoId); replica.activate(); const exactRevision = replica.exactRevision(); if (exactRevision === null) throw new FleetFault("replica_pending", "No exact center cut is ready.", true); const latest = await replica.waitForCut(exactRevision), key = { nodeId, viewId: a.viewId, repoId: a.repoId }, id = keyId(key); if (!window.keys.has(id) && window.keys.size >= 8) throw new FleetFault("busy", "Session already has eight active replica keys.", true); if (latest.manifest.totalBytes * 2 + FLEET_SESSION_SEND_WINDOW_BYTES > options.replicaDiskQuotaBytes!) throw new FleetFault("replica_quota_insufficient", "Replica quota cannot hold current, incoming, and staging reserve."); window.keys.add(id); knownKeys.set(id, key); ackStore.register(key, latest.revision); const cursor = ackStore.cursor(key); if (cursor?.revision === latest.revision && cursor.headDigest === latest.headDigest && cursor.manifestDigest === latest.manifest.digest) { window.keys.delete(id); return immediate({ schema: "fleet.replica.current/v1", messageId: mid(frame.messageId, "current"), inReplyTo: frame.messageId, repoId: key.repoId, viewId: key.viewId, cut: wireCut(latest), manifestDigest: latest.manifest.digest }); } let active = ackStore.offerFor(key); if (active && (!replica.cut(active.toCut.revision) || replica.cut(active.toCut.revision)?.manifest.digest !== active.manifestDigest || active.fromCut && replica.changes(active.fromCut.revision, active.toCut.revision) === null)) { ackStore.clearOffer(key); active = null; } const next = active ?? makeOffer(key, cursor, latest, replica, now()); const offer = active ?? ackStore.offer(key, next); window.offers.set(offer.transferId, key); return { key: id, frames: offerFrames(offer, replica) }; }
    if (frame.schema === "fleet.task.command/v1") { const result = await leaseBroker.handleTaskCommand(nodeId, frame, clientGone); return immediate({ schema: "fleet.task.result/v1", messageId: mid(frame.messageId, "task"), inReplyTo: frame.messageId, ...result }); }
    if (frame.schema === "fleet.ack/v1") { const key = window.offers.get(frame.transferId); if (!key || key.nodeId !== nodeId) throw new FleetFault("invalid_ack", "ACK does not match an offer issued in this authenticated session."); const cutEventAt = options.host.replica(key.repoId).eventAt(frame.cut.revision); if (!cutEventAt) throw new FleetFault("invalid_ack", "ACK cut is no longer exact at the center."); const result = ackStore.ack(key, frame.transferId, frame.cut, frame.manifestDigest, now(), cutEventAt); if (result.outcome === "op_rejected" || !result.cursor) throw new FleetFault("invalid_ack", "ACK cut or manifest differs from its exact active offer."); window.offers.delete(frame.transferId); window.keys.delete(keyId(key)); return immediate({ schema: "fleet.ack.result/v1", messageId: mid(frame.messageId, "ack"), inReplyTo: frame.messageId, outcome: result.outcome, viewId: key.viewId, ackCut: result.cursor.revision, code: null }); }
    throw new FleetFault("unexpected_direction", `Frame ${frame.schema} is not accepted by the center.`);
  };
  const server: Server = createServer({ key: options.key, cert: options.cert }, (socket) => serve(socket, options, handle)); await new Promise<void>((resolve, reject) => { server.once("error", reject); server.listen(options.port ?? 0, options.hostname ?? "127.0.0.1", () => { server.off("error", reject); resolve(); }); }); const address = server.address(); if (!address || typeof address === "string") throw new Error("Fleet TLS server did not bind a TCP port"); let closed = false;
  return { port: address.port, close: async () => { if (closed) return; closed = true; leaseBroker.close(); await new Promise<void>((resolve, reject) => server.close((error) => error ? reject(error) : resolve())); ackStore.close(); }, replicaReceipt: (opId, nodeId, viewId, repoId) => deriveReplicaReceipt(options.host.replica(repoId), ackStore, { nodeId, viewId, repoId }, opId), status: () => { const keys = new Map(ackStore.keys().map((key) => [keyId(key), key])); for (const [id, key] of knownKeys) keys.set(id, key); return { replicas: [...keys.values()].map((key) => replicaStatus(options.host.replica(key.repoId), ackStore, key, options.replicaDiskQuotaBytes ?? null)), leases: leaseBroker.status() }; } };
}

function makeOffer(key: ReplicaDeliveryKey, cursor: ReturnType<ReplicaAckStore["cursor"]>, latest: SnapshotCut, replica: ReplicaCutSource, issuedAt: string): Omit<ReplicaOffer, keyof ReplicaDeliveryKey> { let fromCut: FleetCut | null = null, to = latest, kind: "snapshot" | "delta" = "snapshot"; if (cursor) { const retained = replica.cut(cursor.revision), next = replica.cut(cursor.revision + 1); if (retained && retained.headDigest === cursor.headDigest && retained.manifest.digest === cursor.manifestDigest && next && replica.changes(cursor.revision, next.revision) !== null) { fromCut = wireCut(retained); to = next; kind = "delta"; } } const toCut = wireCut(to), manifestDigest = to.manifest.digest; return { transferId: digestId(key.nodeId, key.viewId, key.repoId, String(fromCut?.revision ?? 0), String(toCut.revision), manifestDigest), fromCut, toCut, manifestDigest, kind, issuedAt }; }
async function* offerFrames(offer: ReplicaOffer, replica: ReplicaCutSource): AsyncGenerator<FleetFrameV1> { const entries = replica.manifest(offer.toCut.revision); if (!entries || fleetManifestDigest(entries) !== offer.manifestDigest) throw new FleetFault("snapshot_required", "Replica cut manifest is unavailable or corrupt.", true); if (offer.kind === "snapshot") { yield { schema: "fleet.snapshot.begin/v1", messageId: mid(offer.transferId, "begin"), transferId: offer.transferId, repoId: offer.repoId, viewId: offer.viewId, cut: offer.toCut, manifest: { digest: offer.manifestDigest, entryCount: entries.length, totalBytes: entries.reduce((sum, entry) => sum + entry.blob.size, 0) } }; for (let offset = 0; offset < entries.length; offset += 128) yield { schema: "fleet.snapshot.page/v1", messageId: mid(offer.transferId, `page${offset / 128}`), transferId: offer.transferId, pageIndex: offset / 128, entries: entries.slice(offset, offset + 128) }; for (const entry of entries) yield* blobFrames("snapshot", offer.transferId, entry, replica.content(entry.blob)); yield { schema: "fleet.snapshot.finish/v1", messageId: mid(offer.transferId, "finish"), transferId: offer.transferId, manifestDigest: offer.manifestDigest }; return; } const changes = offer.fromCut && replica.changes(offer.fromCut.revision, offer.toCut.revision); if (!offer.fromCut || !changes) throw new FleetFault("snapshot_required", "Adjacent replica changelog is outside retention.", true); yield { schema: "fleet.delta.begin/v1", messageId: mid(offer.transferId, "begin"), transferId: offer.transferId, repoId: offer.repoId, viewId: offer.viewId, fromCut: offer.fromCut, toCut: offer.toCut, changeCount: changes.length, resultManifestDigest: offer.manifestDigest }; for (let offset = 0; offset < changes.length; offset += 128) yield { schema: "fleet.delta.page/v1", messageId: mid(offer.transferId, `page${offset / 128}`), transferId: offer.transferId, pageIndex: offset / 128, changes: changes.slice(offset, offset + 128) }; for (const change of changes) if (change.op === "put") yield* blobFrames("delta", offer.transferId, { path: change.path, blob: change.blob }, replica.content(change.blob)); yield { schema: "fleet.delta.finish/v1", messageId: mid(offer.transferId, "finish"), transferId: offer.transferId, resultManifestDigest: offer.manifestDigest }; }
function* blobFrames(kind: "snapshot" | "delta", transferId: string, entry: FleetEntry, bytes: Uint8Array): Generator<FleetFrameV1> { const body = Buffer.from(bytes); for (let offset = 0; offset < body.length; offset += FLEET_CHUNK_BYTES) yield { schema: `fleet.${kind}.chunk/v1`, messageId: mid(transferId, `chunk${offset}`), transferId, blobSha256: entry.blob.sha256, offset, dataBase64: body.subarray(offset, offset + FLEET_CHUNK_BYTES).toString("base64") } as FleetFrameV1; }
function deriveReplicaReceipt(replica: ReplicaCutSource, ackStore: ReplicaAckStore, key: ReplicaDeliveryKey, opId: string): WriteReceipt { const basis = replica.receiptBasis(opId), reject = (code: string, nextAction: string): WriteReceipt => ({ outcome: "op_rejected", opId, code, origin: "fleet-replica", evidence: `replica:${key.repoId}:${key.viewId}`, nextAction }); if (!basis) return reject("operation_not_published", "Query the center receipt or retry after publication."); const revision = basis.event.workspaceRevision, registration = ackStore.registrationRevision(key); if (registration === null || revision <= registration) return reject("replica_not_registered_at_revision", "Use the center receipt; this view did not subscribe at that revision."); const cut = replica.cut(revision), proof = cut && ackStore.proof(key, revision), base = { opId, revision, visibility: { kind: "replica" as const, viewId: key.viewId }, evidence: `event-object:${opId};replica-cut:${revision}` }; if (basis.applied && cut && proof && proof.headDigest === cut.headDigest && proof.manifestDigest === cut.manifest.digest) return { outcome: "applied", ...base, proof: { committedRevision: revision, appliedCut: revision, ackCut: revision, durable: true, canonicalVisible: true, worktreeVisible: true } }; return { outcome: "pending", ...base, proof: { committedRevision: revision, appliedCut: basis.applied ? revision : 0, durable: true, canonicalVisible: true, worktreeVisible: false }, nextAction: "Pull and ACK the exact replica cut, then retry this opId query." }; }
function replicaStatus(replica: ReplicaCutSource, ackStore: ReplicaAckStore, key: ReplicaDeliveryKey, diskQuotaBytes: number | null): FleetReplicaStatus { const latest = replica.latest(), cursor = ackStore.cursor(key); if (!latest) return { ...key, centerRevision: 0, centerEventAt: null, centerManifestBytes: 0, ackRevision: cursor?.revision ?? null, ackCutEventAt: cursor?.cutEventAt ?? null, ackedAt: cursor?.ackedAt ?? null, lagRevisions: 0, lagMs: null, catchUpBytes: 0, delivery: "degraded", activeTransfers: ackStore.offerFor(key) ? 1 : 0, sendWindowBytes: FLEET_KEY_SEND_WINDOW_BYTES, sendQuotaBytes: FLEET_SESSION_SEND_WINDOW_BYTES, diskQuotaBytes }; const changes = cursor && replica.changes(cursor.revision, latest.revision), current = cursor?.revision === latest.revision, centerEventAt = replica.eventAt(latest.revision), ackCutEventAt = cursor?.cutEventAt ?? null, catchUpBytes = current ? 0 : changes ? changes.reduce((sum, change) => sum + (change.op === "put" ? change.blob.size : 0), 0) : latest.manifest.totalBytes; return { ...key, centerRevision: latest.revision, centerEventAt, centerManifestBytes: latest.manifest.totalBytes, ackRevision: cursor?.revision ?? null, ackCutEventAt, ackedAt: cursor?.ackedAt ?? null, lagRevisions: Math.max(0, latest.revision - (cursor?.revision ?? 0)), lagMs: centerEventAt && ackCutEventAt ? Math.max(0, Date.parse(centerEventAt) - Date.parse(ackCutEventAt)) : null, catchUpBytes, delivery: current ? "current" : changes ? "delta" : "snapshot_required", activeTransfers: ackStore.offerFor(key) ? 1 : 0, sendWindowBytes: FLEET_KEY_SEND_WINDOW_BYTES, sendQuotaBytes: FLEET_SESSION_SEND_WINDOW_BYTES, diskQuotaBytes }; }
async function serve(socket: TLSSocket, options: FleetCenterOptions, handle: (nodeId: string, frame: FleetFrameV1, window: SessionWindow, clientGone: () => boolean) => Promise<Delivery>): Promise<void> { let nodeId: string | null = null, pumping = false; const reader = new FleetUtf8LineDecoder(), window: SessionWindow = { uploads: new Set(), keys: new Set(), offers: new Map() }, jobs: Array<{ delivery: Delivery; iterator: AsyncIterator<FleetFrameV1>; resolve: () => void; reject: (error: unknown) => void }> = [], send = async (frame: FleetFrameV1) => { const line = serializeFleetFrame(frame), bytes = Buffer.byteLength(line); if (bytes > FLEET_KEY_SEND_WINDOW_BYTES) throw new FleetFault("busy", "Per-key send window is full.", true); if (socket.writableLength + bytes > FLEET_SESSION_SEND_WINDOW_BYTES) await new Promise<void>((resolve) => socket.once("drain", resolve)); if (!socket.write(line)) await new Promise<void>((resolve) => socket.once("drain", resolve)); }, enqueue = (delivery: Delivery) => new Promise<void>((resolve, reject) => { jobs.push({ delivery, iterator: delivery.frames[Symbol.asyncIterator](), resolve, reject }); void pump(); }), pump = async () => { if (pumping) return; pumping = true; try { while (jobs.length) { const job = jobs.shift()!; try { const next = await job.iterator.next(); if (next.done) job.resolve(); else { await send(next.value); jobs.push(job); } } catch (error) { consumeKnownError(error); job.reject(error); } } } finally { pumping = false; } };
  socket.on("data", (chunk) => { try { for (const line of reader.push(chunk)) void dispatch(line); } catch (error) { consumeKnownError(error); socket.destroy(error instanceof Error ? error : new Error(String(error))); } }); socket.on("end", () => { try { reader.finish(); } catch (error) { consumeKnownError(error); socket.destroy(error instanceof Error ? error : new Error(String(error))); } });
  const dispatch = async (line: string) => { let frame: FleetFrameV1 | null = null; try { frame = parseFleetFrame(line); if (nodeId === null) { if (frame.schema !== "fleet.session.hello/v1" || !await options.authenticate(frame.nodeId, frame.credential)) throw new FleetFault("authentication_failed", "Machine credential was rejected."); nodeId = frame.nodeId; return enqueue(immediate({ schema: "fleet.session.ready/v1", messageId: mid(frame.messageId, "session"), inReplyTo: frame.messageId, sessionId: digestId(nodeId, String(Date.now())), maxFrameBytes: FLEET_FRAME_BYTES, chunkBytes: FLEET_CHUNK_BYTES })); } if (frame.schema === "fleet.session.hello/v1") throw new FleetFault("hello_replayed", "Session hello is only valid as the first frame."); if (options.isNodeActive && !await options.isNodeActive(nodeId)) throw new FleetFault("credential_revoked", "Node credential was revoked."); await enqueue(await handle(nodeId, frame, window, () => socket.destroyed)); } catch (error) { consumeKnownError(error); const fault = error instanceof FleetFault ? error : new FleetFault("invalid_frame", error instanceof Error ? error.message : String(error)); await enqueue(immediate({ schema: "fleet.error/v1", messageId: mid(frame?.messageId ?? "invalid", "error"), inReplyTo: frame?.messageId ?? "invalid", code: fault.code, retryable: fault.retryable, resumeOffset: fault.resumeOffset, nextAction: fault.message })); if (fault.code === "authentication_failed" || fault.code === "credential_revoked") socket.end(); } }; }
function immediate(frame: FleetFrameV1): Delivery { return { key: null, frames: (async function* () { yield frame; })() }; }
function loadState(file: string): State { if (!existsSync(file)) return { uploads: {} }; const value = JSON.parse(readFileSync(file, "utf8")) as State & Record<string, unknown>; if (!value.uploads || Object.keys(value.uploads).length > 64 || "transfers" in value || "cursors" in value) throw new Error("Fleet durable state contains retired delivery state"); return { uploads: value.uploads }; }
function writeCenterDurableJson(file: string, value: unknown): void { mkdirSync(path.dirname(file), { recursive: true }); const temp = `${file}.${process.pid}.tmp`, fd = openSync(temp, "w"); try { writeFileSync(fd, `${JSON.stringify(value)}\n`); fsyncSync(fd); } finally { closeSync(fd); } renameSync(temp, file); syncDir(path.dirname(file)); }
function syncFile(file: string): void { const fd = openSync(file, "r"); try { fsyncSync(fd); } finally { closeSync(fd); } } function syncDir(directory: string): void { const fd = openSync(directory, "r"); try { fsyncSync(fd); } finally { closeSync(fd); } }
function ownedUpload(state: State, nodeId: string, uploadId: string): Upload { const upload = state.uploads[uploadId]; if (!upload || upload.nodeId !== nodeId || upload.descriptor) throw new FleetFault("upload_unknown", "Upload is unknown, completed, or belongs to another node."); return upload; }
function wireCut(cut: SnapshotCut): FleetCut { return { revision: cut.revision, headDigest: cut.headDigest }; } function digestId(...parts: string[]): string { return createHash("sha256").update(parts.join("\0")).digest("hex").slice(0, 32); } function mid(seed: string, suffix: string): string { return `${seed.slice(0, 64)}_${suffix}`.slice(0, 96); }
