import { execFileSync } from "node:child_process";
import { createHash } from "node:crypto";
import { accessSync, chmodSync, constants, existsSync, mkdirSync, readFileSync, realpathSync, renameSync, rmSync, writeFileSync } from "node:fs";
import path from "node:path";
import { consumeKnownError } from "../../kernel/src/index.ts";
import type { AgentDefinitionSnapshot } from "../../kernel/src/index.ts";
import { credentialPort, isCredentialReferenceText } from "./agent-runtime-credential-port.ts";
export type RuntimeInstanceKind = "claude" | "codex"; export type RuntimeInstanceAuth = { readonly mode: "subscription" } | { readonly mode: "api-key"; readonly credentialRef: string };
export interface RuntimeInstanceConfig { readonly schemaVersion: 1; readonly instanceId: string; readonly name: string; readonly kindId: RuntimeInstanceKind; readonly installationId: string; readonly providerId: string; readonly model: string; readonly reasoningEffort?: string; readonly baseUrl?: string; readonly auth: RuntimeInstanceAuth } export interface RuntimeInstallationWitness { readonly installationId: string; readonly kindId: RuntimeInstanceKind; readonly executablePath: string; readonly version: string; readonly observedAt: string }
export interface RuntimeAuthReadiness { readonly status: "ready" | "not-ready"; readonly code: string | null; readonly hint: string | null }
export interface RuntimeInstanceSummary { readonly schemaVersion: 1; readonly instanceId: string; readonly name: string; readonly kindId: RuntimeInstanceKind; readonly installationId: string; readonly providerId: string; readonly model: string; readonly reasoningEffort: string | null; readonly baseUrl: string | null; readonly authMode: RuntimeInstanceAuth["mode"]; readonly authState: "configured" | "unknown"; readonly authReadiness: RuntimeAuthReadiness; readonly baseUrlConfigured: boolean; readonly isolationState: "enforced" } export interface PreparedRuntimeLaunch { readonly definition: AgentDefinitionSnapshot; readonly installation: RuntimeInstallationWitness; readonly executablePath: string; readonly args: readonly string[]; readonly env: NodeJS.ProcessEnv; readonly cwd: string; readonly prompt: string }
export interface PreparedRuntimeAuthCommand { readonly instanceId: string; readonly name: string; readonly executablePath: string; readonly args: readonly string[]; readonly env: NodeJS.ProcessEnv; readonly cwd: string }

export function discoverRuntimeInstallations(input: { readonly env?: NodeJS.ProcessEnv; readonly now?: () => string; readonly platform?: NodeJS.Platform } = {}): readonly RuntimeInstallationWitness[] {
  const env = input.env ?? process.env, platform = input.platform ?? process.platform, observedAt = (input.now ?? (() => new Date().toISOString()))(), seen = new Set<string>(), result: RuntimeInstallationWitness[] = [], suffixes = platform === "win32" ? ["", ".cmd", ".exe"] : [""];
  for (const directory of (env.PATH ?? "").split(path.delimiter).filter(Boolean)) for (const kindId of ["claude", "codex"] as const) for (const suffix of suffixes) { const candidate = path.resolve(directory, `${kindId}${suffix}`); try { accessSync(candidate, constants.X_OK); const executablePath = realpathSync.native(candidate), key = `${kindId}\0${executablePath}`; if (seen.has(key)) continue; const version = runExecutableSync(platform, executablePath, ["--version"], { env: versionProbeEnvironment(env, platform), timeoutMs: 5_000, captureOutput: true }); if (!version) continue; seen.add(key); const installationId = `${kindId}_${createHash("sha256").update(`${key}\0${version}`).digest("hex").slice(0, 24)}`; result.push({ installationId, kindId, executablePath, version, observedAt }); } catch (error) { consumeKnownError(error); } }
  return result.sort((a, b) => a.installationId.localeCompare(b.installationId));
}
function versionProbeEnvironment(env: NodeJS.ProcessEnv, platform: NodeJS.Platform): NodeJS.ProcessEnv { const result: NodeJS.ProcessEnv = { PATH: env.PATH ?? "", LANG: "C", LC_ALL: "C" }; if (platform === "win32") for (const key of ["SYSTEMROOT", "SYSTEMDRIVE", "COMSPEC", "PATHEXT", "TEMP", "TMP"]) if (env[key]) result[key] = env[key]; return result; }
// Executes a witnessed runtime executable across platforms without `shell: true`:
// native executables spawn argv-direct, while Windows command shims (.cmd/.bat)
// run through an explicit cmd.exe argv with a fully controlled command line.
function runExecutableSync(platform: NodeJS.Platform, executablePath: string, args: readonly string[], options: { readonly env: NodeJS.ProcessEnv; readonly timeoutMs: number; readonly captureOutput: boolean }): string {
  const shim = platform === "win32" && /\.(?:cmd|bat)$/iu.test(executablePath);
  const stdout = execFileSync(shim ? "cmd.exe" : executablePath, shim ? ["/d", "/s", "/c", `"${executablePath}" ${args.join(" ")}`] : [...args], { encoding: "utf8", env: options.env, stdio: ["ignore", options.captureOutput ? "pipe" : "ignore", "ignore"], timeout: options.timeoutMs, windowsHide: true, ...(shim ? { windowsVerbatimArguments: true } : {}) });
  return options.captureOutput ? stdout.trim() : "";
}

export function openRuntimeInstanceStore(input: { readonly userRoot: string; readonly discover: () => readonly RuntimeInstallationWitness[]; readonly env?: NodeJS.ProcessEnv; readonly platform?: NodeJS.Platform; readonly resolveCredential?: (reference: string) => string; readonly subscriptionReady?: (input: { readonly installation: RuntimeInstallationWitness; readonly env: NodeJS.ProcessEnv }) => boolean }) {
  const platform = input.platform ?? process.platform, resolveCredential = input.resolveCredential ?? credentialPort(platform).resolve, target = path.join(input.userRoot, "runtime-instances.json"), instancesRoot = path.join(input.userRoot, "runtime-instances"), readiness = new Map<string, RuntimeAuthReadiness>();
  function create(candidate: RuntimeInstanceConfig): RuntimeInstanceConfig { const config = runtimeInstanceConfig(candidate), instances = read(); if (instances.some(({ instanceId }) => instanceId === config.instanceId)) throw runtimeInstanceError("runtime_instance_exists", `Runtime instance ${config.instanceId} already exists.`); const installation = input.discover().find(({ installationId }) => installationId === config.installationId); if (!installation || installation.kindId !== config.kindId) throw runtimeInstanceError("runtime_installation_not_found", `Runtime installation ${config.installationId} is not currently witnessed for ${config.kindId}.`); ensureStateRoot(config.instanceId); persist([...instances, config]); return config; }
  function readOne(instanceId: string): RuntimeInstanceConfig | null { return read().find((config) => config.instanceId === runtimeInstanceId(instanceId)) ?? null; }
  function remove(instanceId: string): RuntimeInstanceConfig { const id = runtimeInstanceId(instanceId), instances = read(), config = instances.find((entry) => entry.instanceId === id); if (!config) throw runtimeInstanceError("runtime_instance_not_found", `Runtime instance ${id} does not exist.`); persist(instances.filter((entry) => entry.instanceId !== id)); readiness.delete(id); rmSync(path.join(instancesRoot, id), { recursive: true, force: true }); return config; }
  function authStatus(instanceId: string): RuntimeAuthReadiness { const config = readOne(instanceId); if (!config) throw runtimeInstanceError("runtime_instance_not_found", `Runtime instance ${instanceId} does not exist.`); const installation = input.discover().find((entry) => entry.installationId === config.installationId && entry.kindId === config.kindId); if (!installation) return rememberAuthReadiness(config.instanceId, unavailable("runtime_installation_not_found", `Runtime installation ${config.installationId} is no longer witnessed.`)); ensureStateRoot(config.instanceId); const env = authEnvironment(config); if (config.auth.mode === "subscription") { let ready = false; try { ready = (input.subscriptionReady ?? ((probe) => providerSubscriptionReady(probe, platform)))({ installation, env }); } catch (error) { consumeKnownError(error); } return rememberAuthReadiness(config.instanceId, ready ? available() : unavailable("runtime_subscription_required", "Provider subscription authentication is unavailable in this instance state root.")); } try { const secret = resolveCredential(config.auth.credentialRef); return rememberAuthReadiness(config.instanceId, secret ? available() : unavailable("runtime_credential_unavailable", credentialUnavailableHint)); } catch (error) { consumeKnownError(error); return rememberAuthReadiness(config.instanceId, unavailable("runtime_credential_unavailable", credentialHint(error))); } }
  function prepareAuthCommand(instanceId: string, action: "login" | "reauth" | "logout"): PreparedRuntimeAuthCommand { const config = readOne(instanceId); if (!config) throw runtimeInstanceError("runtime_instance_not_found", `Runtime instance ${instanceId} does not exist.`); if (config.auth.mode !== "subscription") throw runtimeInstanceError("runtime_auth_mode_mismatch", "Provider-native sign-in is available only for subscription instances."); const installation = input.discover().find((entry) => entry.installationId === config.installationId && entry.kindId === config.kindId); if (!installation) throw runtimeInstanceError("runtime_installation_not_found", `Runtime installation ${config.installationId} is no longer witnessed.`); ensureStateRoot(config.instanceId); rememberAuthReadiness(config.instanceId, unavailable("runtime_auth_in_progress", `Provider-native ${action} is running in this instance terminal.`)); const args = config.kindId === "codex" ? [action === "logout" ? "logout" : "login"] : ["auth", action === "logout" ? "logout" : "login"]; return { instanceId: config.instanceId, name: config.name, executablePath: installation.executablePath, args, env: authEnvironment(config), cwd: path.join(instancesRoot, config.instanceId) }; }
  function prepareLaunch(instanceId: string, request: { readonly cwd: string; readonly prompt: string }): PreparedRuntimeLaunch { const config = readOne(instanceId); if (!config) throw runtimeInstanceError("runtime_instance_not_found", `Runtime instance ${instanceId} does not exist.`); const installation = input.discover().find((entry) => entry.installationId === config.installationId && entry.kindId === config.kindId); if (!installation) { rememberAuthReadiness(config.instanceId, unavailable("runtime_installation_not_found", `Runtime installation ${config.installationId} is no longer witnessed.`)); throw runtimeInstanceError("runtime_installation_not_found", `Runtime installation ${config.installationId} is no longer witnessed.`); } if (!path.isAbsolute(request.cwd) || !request.prompt) throw runtimeInstanceError("invalid_runtime_launch", "Runtime cwd must be absolute and prompt is required."); ensureStateRoot(config.instanceId); const env = authEnvironment(config), args = launchArgs(config), definition = definitionSnapshot(config); if (config.auth.mode === "subscription") { let ready = false; try { ready = (input.subscriptionReady ?? ((probe) => providerSubscriptionReady(probe, platform)))({ installation, env }); } catch (error) { consumeKnownError(error); } if (!ready) { rememberAuthReadiness(config.instanceId, unavailable("runtime_subscription_required", "Provider subscription authentication is unavailable in this instance state root.")); throw runtimeInstanceError("runtime_subscription_required", "Provider subscription authentication is unavailable in this instance state root."); } rememberAuthReadiness(config.instanceId, available()); return { definition, installation, executablePath: installation.executablePath, args, env, cwd: request.cwd, prompt: request.prompt }; } let secret: string; try { secret = resolveCredential(config.auth.credentialRef); } catch (error) { consumeKnownError(error); rememberAuthReadiness(config.instanceId, unavailable("runtime_credential_unavailable", credentialHint(error))); throw runtimeInstanceError("runtime_credential_unavailable", credentialHint(error)); } if (!secret) { rememberAuthReadiness(config.instanceId, unavailable("runtime_credential_unavailable", credentialUnavailableHint)); throw runtimeInstanceError("runtime_credential_unavailable", credentialUnavailableHint); } env[config.kindId === "claude" ? "ANTHROPIC_API_KEY" : "OPENAI_API_KEY"] = secret; rememberAuthReadiness(config.instanceId, available()); return { definition, installation, executablePath: installation.executablePath, args, env, cwd: request.cwd, prompt: request.prompt }; }
  function command(action: Readonly<Record<string, unknown>>): Record<string, unknown> { const kind = String(action.kind), base = { schema: "command-receipt/v2", ok: true, command: kind, outcome: "applied", opId: `${kind}:${typeof action.instanceId === "string" ? action.instanceId : "all"}`, nextAction: null }; if (kind === "runtime-instance-create") { if (!["subscription", "api-key"].includes(String(action.authMode)) || action.authMode === "subscription" && action.credentialRef !== undefined) throw runtimeInstanceError("invalid_runtime_auth", "Runtime instance auth must select exactly subscription or an opaque API-key reference."); const auth = action.authMode === "subscription" ? { mode: "subscription" as const } : { mode: "api-key" as const, credentialRef: action.credentialRef }, config = create({ schemaVersion: 1, instanceId: action.instanceId, name: action.name, kindId: action.kindId, installationId: action.installationId, providerId: action.providerId, model: action.model, reasoningEffort: action.reasoningEffort, baseUrl: action.baseUrl, auth } as RuntimeInstanceConfig), instance = publicConfig(config, readiness.get(config.instanceId)); return { ...base, instance, evidence: JSON.stringify(instance), summary: `runtime-instance-create: ${config.instanceId}` }; } if (kind === "runtime-instance-list") { const instances = read().map((config) => publicConfig(config, readiness.get(config.instanceId))), installations = input.discover().map(({ executablePath: _path, ...installation }) => installation); return { ...base, instances, installations, evidence: JSON.stringify({ instances, installations }), summary: `runtime-instance-list: ${instances.length}` }; } const instanceId = requiredRuntimeInstanceText(action.instanceId, "instanceId"); if (kind === "runtime-instance-status") { const authReadiness = authStatus(instanceId); return { ...base, instanceId, authReadiness, evidence: JSON.stringify({ instanceId, authReadiness }), summary: `runtime-instance-status: ${instanceId}` }; } if (kind === "runtime-instance-show") { const config = readOne(instanceId); if (!config) throw runtimeInstanceError("runtime_instance_not_found", `Runtime instance ${instanceId} does not exist.`); const instance = publicConfig(config, readiness.get(config.instanceId)); return { ...base, instance, evidence: JSON.stringify(instance), summary: `runtime-instance-show: ${instanceId}` }; } if (kind === "runtime-instance-delete") { remove(instanceId); return { ...base, deletedInstanceId: instanceId, evidence: `runtime-instance-deleted:${instanceId}`, summary: `runtime-instance-delete: ${instanceId}` }; } throw runtimeInstanceError("unsupported_command", `Unsupported runtime instance command: ${kind}.`); }
  return { create, list: read, listPublic: (): readonly RuntimeInstanceSummary[] => read().map((config) => publicConfig(config, readiness.get(config.instanceId))), read: readOne, delete: remove, authStatus, prepareAuthCommand, prepareLaunch, command };
  function read(): RuntimeInstanceConfig[] { if (!existsSync(target)) return []; chmodSync(target, 0o600); const value: unknown = JSON.parse(readFileSync(target, "utf8")); if (!isRuntimeInstanceRecord(value) || value.schema !== "runtime-instances/v1" || !Array.isArray(value.instances) || Object.keys(value).some((key) => !["schema", "instances"].includes(key))) throw runtimeInstanceError("invalid_runtime_instance_store", "Runtime instance metadata is invalid."); return value.instances.map(runtimeInstanceConfig).sort((a, b) => a.instanceId.localeCompare(b.instanceId)); }
  function persist(instances: readonly RuntimeInstanceConfig[]): void { mkdirSync(input.userRoot, { recursive: true, mode: 0o700 }); const temp = `${target}.${process.pid}.tmp`; writeFileSync(temp, `${JSON.stringify({ schema: "runtime-instances/v1", instances: [...instances].sort((a, b) => a.instanceId.localeCompare(b.instanceId)) }, null, 2)}\n`, { encoding: "utf8", mode: 0o600 }); renameSync(temp, target); chmodSync(target, 0o600); }
  function ensureStateRoot(instanceId: string): void { const root = path.join(instancesRoot, instanceId); for (const directory of [root, ...["home", "tmp", "run"].map((name) => path.join(root, name))]) { mkdirSync(directory, { recursive: true, mode: 0o700 }); chmodSync(directory, 0o700); } }
  function authEnvironment(config: RuntimeInstanceConfig): NodeJS.ProcessEnv { const env = isolatedEnvironment(input.env ?? process.env, path.join(instancesRoot, config.instanceId), config.kindId, platform); if (config.baseUrl) env[config.kindId === "claude" ? "ANTHROPIC_BASE_URL" : "OPENAI_BASE_URL"] = config.baseUrl; return env; }
  function rememberAuthReadiness(instanceId: string, state: RuntimeAuthReadiness): RuntimeAuthReadiness { readiness.set(instanceId, state); return state; }
}

function publicConfig(config: RuntimeInstanceConfig, authReadiness: RuntimeAuthReadiness = unavailable("runtime_auth_not_checked", "Authentication has not been verified in this daemon generation.")): RuntimeInstanceSummary { return { schemaVersion: config.schemaVersion, instanceId: config.instanceId, name: config.name, kindId: config.kindId, installationId: config.installationId, providerId: config.providerId, model: config.model, reasoningEffort: config.reasoningEffort ?? null, baseUrl: config.baseUrl ?? null, authMode: config.auth.mode, authState: config.auth.mode === "api-key" ? "configured" : "unknown", authReadiness, baseUrlConfigured: config.baseUrl !== undefined, isolationState: "enforced" }; }
function definitionSnapshot(config: RuntimeInstanceConfig): AgentDefinitionSnapshot { return { schema: "agent-definition-snapshot/v1", configVersion: config.schemaVersion, instanceId: config.instanceId, installationId: config.installationId, kindId: config.kindId, providerId: config.providerId, model: config.model, reasoningEffort: config.reasoningEffort ?? null, baseUrl: config.baseUrl ?? null, authMode: config.auth.mode }; }

// Platform-derived isolation environment. POSIX keeps HOME/TMPDIR/XDG_RUNTIME_DIR
// semantics; Windows derives the same guarantees from USERPROFILE/TEMP/APPDATA and
// must not inject XDG_RUNTIME_DIR. Pass-through stays an explicit allowlist of
// machine/user-neutral variables; host credentials never leak in.
function isolatedEnvironment(source: NodeJS.ProcessEnv, stateRoot: string, kindId: RuntimeInstanceKind, platform: NodeJS.Platform): NodeJS.ProcessEnv { const home = path.join(stateRoot, "home"), tmp = path.join(stateRoot, "tmp"), kind = kindId === "codex" ? { CODEX_HOME: path.join(home, ".codex") } : { CLAUDE_CONFIG_DIR: path.join(home, ".claude") }; if (platform === "win32") { const result: NodeJS.ProcessEnv = { USERPROFILE: home, TEMP: tmp, TMP: tmp, APPDATA: path.join(home, "AppData", "Roaming"), LOCALAPPDATA: path.join(home, "AppData", "Local"), ...kind }; for (const key of ["PATH", "PATHEXT", "LANG", "LC_ALL", "SYSTEMROOT", "SYSTEMDRIVE", "COMSPEC"]) if (source[key]) result[key] = source[key]; return result; } const result: NodeJS.ProcessEnv = { HOME: home, TMPDIR: tmp, XDG_RUNTIME_DIR: path.join(stateRoot, "run"), ...kind }; for (const key of ["PATH", "LANG", "LC_ALL"]) if (source[key]) result[key] = source[key]; return result; }
function launchArgs(config: RuntimeInstanceConfig): string[] { if (config.kindId === "claude") return ["-p", "--verbose", "--output-format", "stream-json", "--model", config.model, ...(config.reasoningEffort ? ["--effort", config.reasoningEffort] : []), ...(config.auth.mode === "api-key" ? ["--bare"] : [])]; return ["exec", "--json", "--model", config.model, "-c", `model_provider="${config.providerId}"`, ...(config.reasoningEffort ? ["-c", `model_reasoning_effort="${config.reasoningEffort}"`] : []), "-"]; }
function providerSubscriptionReady(input: { readonly installation: RuntimeInstallationWitness; readonly env: NodeJS.ProcessEnv }, platform: NodeJS.Platform): boolean { try { runExecutableSync(platform, input.installation.executablePath, input.installation.kindId === "codex" ? ["login", "status"] : ["auth", "status", "--json"], { env: input.env, timeoutMs: 5_000, captureOutput: false }); return true; } catch (error) { consumeKnownError(error); return false; } }
const credentialUnavailableHint = "The configured runtime API credential is unavailable.";
function credentialHint(error: unknown): string { return typeof error === "object" && error !== null && "code" in error && (error as { code: unknown }).code === "runtime_credential_unavailable" && error instanceof Error && error.message ? error.message : credentialUnavailableHint; }

export function secureRuntimeBaseUrl(value: unknown): string { const text = requiredRuntimeInstanceText(value, "baseUrl"); let parsed: URL; try { parsed = new URL(text); } catch { throw runtimeInstanceError("invalid_base_url", "baseUrl must be an absolute HTTPS URL."); } if (parsed.username || parsed.password || parsed.search || parsed.hash || parsed.protocol !== "https:" && !(parsed.protocol === "http:" && ["127.0.0.1", "::1", "localhost"].includes(parsed.hostname))) throw runtimeInstanceError("invalid_base_url", "baseUrl must use HTTPS or loopback HTTP and cannot contain credentials, query, or fragment."); return parsed.toString(); }
function runtimeInstanceConfig(value: unknown): RuntimeInstanceConfig { if (!isRuntimeInstanceRecord(value)) throw runtimeInstanceError("invalid_runtime_instance", "Runtime instance must be an object."); const allowed = ["schemaVersion", "instanceId", "name", "kindId", "installationId", "providerId", "model", "reasoningEffort", "baseUrl", "auth"]; if (Object.keys(value).some((key) => !allowed.includes(key)) || value.schemaVersion !== 1 || !["claude", "codex"].includes(String(value.kindId)) || !isRuntimeInstanceRecord(value.auth)) throw runtimeInstanceError("invalid_runtime_instance", "Runtime instance metadata is invalid."); const auth = value.auth.mode === "subscription" && Object.keys(value.auth).length === 1 ? { mode: "subscription" as const } : value.auth.mode === "api-key" && Object.keys(value.auth).every((key) => ["mode", "credentialRef"].includes(key)) ? { mode: "api-key" as const, credentialRef: credentialReference(value.auth.credentialRef) } : null; if (!auth) throw runtimeInstanceError("invalid_runtime_auth", "Runtime instance auth must select exactly subscription or an opaque API-key reference."); const effort = value.reasoningEffort === undefined ? undefined : identifier(value.reasoningEffort, "reasoningEffort"), baseUrl = value.baseUrl === undefined ? undefined : secureRuntimeBaseUrl(value.baseUrl); return { schemaVersion: 1, instanceId: runtimeInstanceId(value.instanceId), name: requiredRuntimeInstanceText(value.name, "name"), kindId: value.kindId as RuntimeInstanceKind, installationId: identifier(value.installationId, "installationId"), providerId: identifier(value.providerId, "providerId"), model: requiredRuntimeInstanceText(value.model, "model"), ...(effort ? { reasoningEffort: effort } : {}), ...(baseUrl ? { baseUrl } : {}), auth }; }
function runtimeInstanceId(value: unknown): string { const id = requiredRuntimeInstanceText(value, "instanceId"); if (!/^[a-z0-9](?:[a-z0-9-]{0,62}[a-z0-9])?$/u.test(id)) throw runtimeInstanceError("invalid_runtime_instance_id", "instanceId must be lowercase kebab-case."); return id; }
function identifier(value: unknown, field: string): string { const text = requiredRuntimeInstanceText(value, field); if (!/^[A-Za-z0-9][A-Za-z0-9._:-]{0,239}$/u.test(text)) throw runtimeInstanceError("invalid_runtime_instance", `${field} is invalid.`); return text; }
function credentialReference(value: unknown): string { const text = requiredRuntimeInstanceText(value, "credentialRef"); if (!isCredentialReferenceText(text)) throw runtimeInstanceError("invalid_credential_reference", "credentialRef must be an opaque credential:v1 reference (legacy keychain: references resolve on macOS only)."); return text; }
function requiredRuntimeInstanceText(value: unknown, field: string): string { if (typeof value === "string" && value.trim().length) return value.trim(); throw runtimeInstanceError("invalid_runtime_instance", `${field} is required.`); }
function isRuntimeInstanceRecord(value: unknown): value is Record<string, unknown> { return value !== null && typeof value === "object" && !Array.isArray(value); }
function runtimeInstanceError(code: string, message: string): Error { return Object.assign(new Error(message), { code }); }
function available(): RuntimeAuthReadiness { return { status: "ready", code: null, hint: null }; }
function unavailable(code: string, hint: string): RuntimeAuthReadiness { return { status: "not-ready", code, hint }; }
