import { createHash } from "node:crypto";
import { existsSync, lstatSync, mkdirSync, realpathSync, rmSync, symlinkSync, writeFileSync } from "node:fs";
import path from "node:path";
import { resolveHarnessLayout } from "../../kernel/src/index.ts";
import type { AgentSkillDeclarationV1 } from "./agent-entities.contract.ts";

export interface ResolvedAgentSkill { readonly id: string; readonly sourceDir: string; readonly skillFile: string; readonly rootDir: string }
export interface RuntimeSkillMount { readonly claudePluginDir?: string; readonly agyWorkspaceDir?: string }

export function resolveAgentSkillRoot(rootDir: string): string { return resolveHarnessLayout(rootDir).authoredRoot; }
export function resolveAgentSkills(input: { readonly rootDir: string; readonly skills?: readonly AgentSkillDeclarationV1[] }): readonly ResolvedAgentSkill[] { const lexicalRoot = path.resolve(resolveAgentSkillRoot(input.rootDir)), rootDir = existsSync(lexicalRoot) ? realpathSync(lexicalRoot) : lexicalRoot, skills = input.skills ?? []; return skills.map((skill) => resolveAgentSkill(rootDir, skill)); }
export function materializeAgentSkills(input: { readonly kindId: "claude" | "codex" | "agy"; readonly stateRoot: string; readonly skillRoot?: string; readonly skills?: readonly ResolvedAgentSkill[] }): RuntimeSkillMount { const skills = input.skills ?? []; if (input.kindId === "codex" && skills.length === 0) { replaceSkillLinks(path.join(input.stateRoot, "home", ".codex", "skills"), []); return {}; } if (skills.length === 0) return {}; if (!input.skillRoot) throw skillError("agent_skill_root_missing", "Agent skills require the project authored root; retry from a registered repository with its authored root available."); const rootDir = realpathSync(path.resolve(input.skillRoot)); skills.forEach((skill) => assertResolvedSkill(rootDir, skill)); const digest = createHash("sha256").update(skills.map(({ id, sourceDir }) => `${id}\0${sourceDir}`).join("\0")).digest("hex").slice(0, 16); if (input.kindId === "codex") { replaceSkillLinks(path.join(input.stateRoot, "home", ".codex", "skills"), skills); return {}; } if (input.kindId === "claude") { const pluginDir = path.join(input.stateRoot, "home", ".claude", "agent-skills", digest); mkdirSync(path.join(pluginDir, ".claude-plugin"), { recursive: true, mode: 0o700 }); writeFileSync(path.join(pluginDir, ".claude-plugin", "plugin.json"), `${JSON.stringify({ name: `harness-agent-skills-${digest}`, version: "1.0.0", description: "Agent-declared skills" })}\n`, { mode: 0o600 }); replaceSkillLinks(path.join(pluginDir, "skills"), skills); return { claudePluginDir: pluginDir }; } const workspaceDir = path.join(input.stateRoot, "agy-workspaces", digest); replaceSkillLinks(path.join(workspaceDir, ".agents", "skills"), skills); return { agyWorkspaceDir: workspaceDir }; }
function resolveAgentSkill(rootDir: string, skill: AgentSkillDeclarationV1): ResolvedAgentSkill { const candidate = path.resolve(rootDir, skill.path), relative = path.relative(rootDir, candidate); if (!relative || relative.startsWith("..") || path.isAbsolute(relative) || skill.path.split(/[\\/]+/u).includes("..")) throw skillError("agent_skill_path_outside_root", `Agent skill "${skill.id}" path "${skill.path}" escapes restricted skill root "${rootDir}"; set path to a relative directory under the authored root, for example skills/${skill.id}.`); if (!existsSync(candidate)) throw skillError("agent_skill_not_found", `Agent skill "${skill.id}" was not found at "${candidate}"; create that directory under the authored root and add SKILL.md, or correct the declaration path.`); const stat = lstatSync(candidate), resolved = realpathSync(candidate); if (!stat.isDirectory()) throw skillError("agent_skill_not_found", `Agent skill "${skill.id}" is not a directory at "${candidate}"; create a directory containing SKILL.md and update the declaration path.`); if (!isInside(rootDir, resolved)) throw skillError("agent_skill_path_outside_root", `Agent skill "${skill.id}" resolves outside restricted skill root "${rootDir}"; move it under the authored root and update the declaration path.`); const skillFile = path.join(resolved, "SKILL.md"); if (!existsSync(skillFile) || !lstatSync(skillFile).isFile() || lstatSync(skillFile).isSymbolicLink()) throw skillError("agent_skill_manifest_missing", `Agent skill "${skill.id}" directory "${resolved}" has no regular SKILL.md; add SKILL.md there or point the declaration at a complete skill directory.`); return { id: skill.id, sourceDir: resolved, skillFile, rootDir }; }
function assertResolvedSkill(rootDir: string, skill: ResolvedAgentSkill): void { if (skill.rootDir !== rootDir || !isInside(rootDir, skill.sourceDir) || !existsSync(skill.skillFile) || !lstatSync(skill.skillFile).isFile()) throw skillError("agent_skill_path_outside_root", `Agent skill "${skill.id}" is not contained by restricted skill root "${rootDir}"; move it under the authored root and update the declaration path.`); }
function replaceSkillLinks(targetRoot: string, skills: readonly ResolvedAgentSkill[]): void { rmSync(targetRoot, { recursive: true, force: true }); mkdirSync(targetRoot, { recursive: true, mode: 0o700 }); for (const skill of skills) symlinkSync(skill.sourceDir, path.join(targetRoot, skill.id), "dir"); }
function isInside(rootDir: string, candidate: string): boolean { const relative = path.relative(rootDir, candidate); return relative === "" || !relative.startsWith("..") && !path.isAbsolute(relative); }
function skillError(code: string, message: string): Error & { readonly code: string } { return Object.assign(new Error(message), { code }); }
