import { type AgentDefinitionSnapshot, type CanonicalEventStore, type RuntimeInstallation, type RuntimeSession, type TaskProjection } from "../../kernel/src/index.ts";
import { coded, type AgentRuntimeEventsResult, type AgentRuntimeInstallationDto, type AgentRuntimeOverviewResult, type AgentRuntimeSessionDto, type AgentRuntimeSessionResult } from "./agent-runtime-contract.ts"; import type { AgentRuntimeStreamHub } from "./agent-runtime-stream.ts";
import { runtimeKindForInstallation } from "./runtime-inventory.ts";
import type { RuntimeInstanceSummary } from "./agent-runtime-instances.ts";

export function makeAgentRuntimeReadModel(input: { readonly projection: TaskProjection; readonly store: CanonicalEventStore; readonly stream: AgentRuntimeStreamHub; readonly runtimeInstances?: () => readonly RuntimeInstanceSummary[] }) {
  const synchronize = () => input.projection.list();
  const installationDto = (installation: RuntimeInstallation): AgentRuntimeInstallationDto => ({ installationId: installation.installationId, kindId: runtimeKindForInstallation(installation).kindId, protocolFamily: installation.protocolFamily, version: installation.version, attachCapability: installation.effectiveCapabilities.includes("attach") ? "supported" : "unsupported", lastObservedAt: installation.lastObservedAt });
  const sessionDto = (session: RuntimeSession): AgentRuntimeSessionDto => { const installation = input.projection.readRuntimeInstallation(session.installationId); if (!installation) throw coded("runtime_installation_not_found", `Runtime installation ${session.installationId} was not found.`);
    const definitionSnapshot = definitionFor(session); return { runtimeSessionId: session.runtimeSessionId, providerSessionId: session.providerSessionId, instanceId: session.instanceId, installationId: session.installationId, kindId: runtimeKindForInstallation(installation).kindId, definitionSnapshotRef: session.definitionSnapshotRef, definitionSnapshot, liveness: session.liveness, attachCapability: session.attachable && installation.effectiveCapabilities.includes("attach") ? "supported" : "unsupported", streamCursor: input.stream.latestCursor(session.runtimeSessionId), associations: session.taskBindings.map((binding) => { const lease = input.projection.currentLease(binding.taskId), actor = lease?.actor; return { taskId: binding.taskId, executionId: binding.executionId, holder: actor ? { personId: actor.principal.personId, executorId: actor.executor?.id ?? null } : null, lease: lease ? { phase: lease.phase, expiresAt: lease.expiresAt } : null }; }), activity: { lastObservedAt: session.lastObservedAt, outcome: session.outcome, resultRef: session.resultRef } }; };
  const definitionFor = (session: RuntimeSession): AgentDefinitionSnapshot => { const dispatch = input.projection.readRuntimeDispatch(session.runtimeSessionId, session.definitionSnapshotRef); if (!dispatch || dispatch.type !== "runtime_dispatch_requested") throw coded("runtime_definition_snapshot_not_found", `Runtime definition snapshot ${session.definitionSnapshotRef} was not found.`); return dispatch.payload.definitionSnapshot; };
  return {
    overview: (payload: Readonly<Record<string, unknown>>): AgentRuntimeOverviewResult => { const taskId = optionalTaskId(payload), cut = synchronize(), sessions = taskId ? input.projection.readRuntimeSessionsForTask(taskId) : input.projection.readRuntimeSessions(), installationIds = new Set(sessions.map(({ installationId }) => installationId)); return { ok: true, status: cut.status, installations: input.projection.readRuntimeInstallations().filter((installation) => !taskId || installationIds.has(installation.installationId)).map(installationDto), instances: taskId ? [] : [...input.runtimeInstances?.() ?? []], sessions: sessions.map(sessionDto), watermark: cut.watermark, sourceRevision: cut.sourceRevision }; },
    session: (payload: Readonly<Record<string, unknown>>): AgentRuntimeSessionResult => { const runtimeSessionIdValue = requiredRuntimeReadField(payload, "runtimeSessionId"), cut = synchronize(), session = input.projection.readRuntimeSession(runtimeSessionIdValue); if (!session) throw coded("runtime_session_not_found", `Runtime session ${runtimeSessionIdValue} was not found.`); return { ok: true, status: cut.status, session: sessionDto(session), watermark: cut.watermark, sourceRevision: cut.sourceRevision }; },
    events: (payload: Readonly<Record<string, unknown>>): AgentRuntimeEventsResult => { const runtimeSessionIdValue = requiredRuntimeReadField(payload, "runtimeSessionId"), after = lifecycleCursor(requiredRuntimeReadField(payload, "afterCursor")), source = input.store.readHead()?.revision ?? 0; if (after > source) throw coded("invalid_cursor", `Lifecycle cursor lifecycle:${after} is ahead of lifecycle:${source}.`); synchronize(); const matching = input.projection.readRuntimeSessionEvents(runtimeSessionIdValue, after, 65), selected = matching.slice(0, 64), done = selected.length === matching.length, end = done ? source : selected.at(-1)!.workspaceRevision; return { ok: true, runtimeSessionId: runtimeSessionIdValue, events: selected.map((event) => ({ cursor: `lifecycle:${event.workspaceRevision}`, runtimeSessionId: runtimeSessionIdValue, type: event.type, occurredAt: event.occurredAt })), cursor: `lifecycle:${end}`, sourceCursor: `lifecycle:${source}`, done }; }
  };
}

function optionalTaskId(payload: Readonly<Record<string, unknown>>): string | null { const keys = Object.keys(payload); if (keys.some((key) => key !== "taskId") || (payload.taskId !== undefined && (typeof payload.taskId !== "string" || !payload.taskId))) throw coded("invalid_request", "Agent runtime overview accepts only an optional taskId."); return typeof payload.taskId === "string" ? payload.taskId : null; }
function requiredRuntimeReadField(payload: Readonly<Record<string, unknown>>, field: string): string { const value = payload[field]; if (typeof value !== "string" || !value) throw coded("invalid_request", `Agent runtime ${field} is required.`); return value; }
function lifecycleCursor(value: string): number { const match = /^lifecycle:(\d+)$/u.exec(value), revision = match ? Number(match[1]) : Number.NaN; if (!Number.isSafeInteger(revision)) throw coded("invalid_cursor", `Invalid lifecycle cursor: ${value}.`); return revision; }
