import { execFileSync } from "node:child_process";
import { createHash } from "node:crypto";
import { accessSync, chmodSync, constants, existsSync, mkdirSync, readFileSync, realpathSync, renameSync, rmSync, writeFileSync } from "node:fs";
import path from "node:path";
import type { AgentDefinitionSnapshot } from "../../kernel/src/index.ts";
export type RuntimeInstanceKind = "claude" | "codex"; export type RuntimeInstanceAuth = { readonly mode: "subscription" } | { readonly mode: "api-key"; readonly credentialRef: string };
export interface RuntimeInstanceConfig { readonly schemaVersion: 1; readonly instanceId: string; readonly name: string; readonly kindId: RuntimeInstanceKind; readonly installationId: string; readonly providerId: string; readonly model: string; readonly reasoningEffort?: string; readonly baseUrl?: string; readonly auth: RuntimeInstanceAuth } export interface RuntimeInstallationWitness { readonly installationId: string; readonly kindId: RuntimeInstanceKind; readonly executablePath: string; readonly version: string; readonly observedAt: string }
export interface RuntimeInstanceSummary { readonly schemaVersion: 1; readonly instanceId: string; readonly name: string; readonly kindId: RuntimeInstanceKind; readonly installationId: string; readonly providerId: string; readonly model: string; readonly reasoningEffort: string | null; readonly baseUrl: string | null; readonly authMode: RuntimeInstanceAuth["mode"]; readonly authState: "configured" | "unknown"; readonly baseUrlConfigured: boolean; readonly isolationState: "enforced" } export interface PreparedRuntimeLaunch { readonly definition: AgentDefinitionSnapshot; readonly installation: RuntimeInstallationWitness; readonly executablePath: string; readonly args: readonly string[]; readonly env: NodeJS.ProcessEnv; readonly cwd: string; readonly prompt: string }

export function discoverRuntimeInstallations(input: { readonly env?: NodeJS.ProcessEnv; readonly now?: () => string } = {}): readonly RuntimeInstallationWitness[] {
  const env = input.env ?? process.env, observedAt = (input.now ?? (() => new Date().toISOString()))(), seen = new Set<string>(), result: RuntimeInstallationWitness[] = [];
  for (const directory of (env.PATH ?? "").split(path.delimiter).filter(Boolean)) for (const kindId of ["claude", "codex"] as const) { const candidate = path.resolve(directory, kindId); try { accessSync(candidate, constants.X_OK); const executablePath = realpathSync.native(candidate), key = `${kindId}\0${executablePath}`; if (seen.has(key)) continue; const version = execFileSync(executablePath, ["--version"], { encoding: "utf8", env: { PATH: env.PATH ?? "", LANG: "C", LC_ALL: "C" }, stdio: ["ignore", "pipe", "ignore"], timeout: 2_000 }).trim(); if (!version) continue; seen.add(key); const installationId = `${kindId}_${createHash("sha256").update(`${key}\0${version}`).digest("hex").slice(0, 24)}`; result.push({ installationId, kindId, executablePath, version, observedAt }); } catch (error) { consumeKnownError(error); } }
  return result.sort((a, b) => a.installationId.localeCompare(b.installationId));
}

export function openRuntimeInstanceStore(input: { readonly userRoot: string; readonly discover: () => readonly RuntimeInstallationWitness[]; readonly env?: NodeJS.ProcessEnv; readonly resolveCredential?: (reference: string) => string; readonly subscriptionReady?: (input: { readonly installation: RuntimeInstallationWitness; readonly env: NodeJS.ProcessEnv }) => boolean }) {
  const target = path.join(input.userRoot, "runtime-instances.json"), instancesRoot = path.join(input.userRoot, "runtime-instances");
  function create(candidate: RuntimeInstanceConfig): RuntimeInstanceConfig { const config = runtimeInstanceConfig(candidate), instances = read(); if (instances.some(({ instanceId }) => instanceId === config.instanceId)) throw coded("runtime_instance_exists", `Runtime instance ${config.instanceId} already exists.`); const installation = input.discover().find(({ installationId }) => installationId === config.installationId); if (!installation || installation.kindId !== config.kindId) throw coded("runtime_installation_not_found", `Runtime installation ${config.installationId} is not currently witnessed for ${config.kindId}.`); ensureStateRoot(config.instanceId); persist([...instances, config]); return config; }
  function readOne(instanceId: string): RuntimeInstanceConfig | null { return read().find((config) => config.instanceId === runtimeInstanceId(instanceId)) ?? null; }
  function remove(instanceId: string): RuntimeInstanceConfig { const id = runtimeInstanceId(instanceId), instances = read(), config = instances.find((entry) => entry.instanceId === id); if (!config) throw coded("runtime_instance_not_found", `Runtime instance ${id} does not exist.`); persist(instances.filter((entry) => entry.instanceId !== id)); rmSync(path.join(instancesRoot, id), { recursive: true, force: true }); return config; }
  function prepareLaunch(instanceId: string, request: { readonly cwd: string; readonly prompt: string }): PreparedRuntimeLaunch { const config = readOne(instanceId); if (!config) throw coded("runtime_instance_not_found", `Runtime instance ${instanceId} does not exist.`); const installation = input.discover().find((entry) => entry.installationId === config.installationId && entry.kindId === config.kindId); if (!installation) throw coded("runtime_installation_not_found", `Runtime installation ${config.installationId} is no longer witnessed.`); if (!path.isAbsolute(request.cwd) || !request.prompt) throw coded("invalid_runtime_launch", "Runtime cwd must be absolute and prompt is required."); ensureStateRoot(config.instanceId); const root = path.join(instancesRoot, config.instanceId), env = isolatedEnvironment(input.env ?? process.env, root, config.kindId), args = launchArgs(config), definition = definitionSnapshot(config); if (config.baseUrl) env[config.kindId === "claude" ? "ANTHROPIC_BASE_URL" : "OPENAI_BASE_URL"] = config.baseUrl; if (config.auth.mode === "subscription") { let ready = false; try { ready = (input.subscriptionReady ?? providerSubscriptionReady)({ installation, env }); } catch (error) { consumeKnownError(error); } if (!ready) throw coded("runtime_subscription_required", "Provider subscription authentication is unavailable in this instance state root."); return { definition, installation, executablePath: installation.executablePath, args, env, cwd: request.cwd, prompt: request.prompt }; } let secret: string; try { secret = (input.resolveCredential ?? resolveKeychainCredential)(config.auth.credentialRef); } catch (error) { consumeKnownError(error); throw coded("runtime_credential_unavailable", "The configured runtime API credential is unavailable."); } if (!secret) throw coded("runtime_credential_unavailable", "The configured runtime API credential is unavailable."); env[config.kindId === "claude" ? "ANTHROPIC_API_KEY" : "OPENAI_API_KEY"] = secret; return { definition, installation, executablePath: installation.executablePath, args, env, cwd: request.cwd, prompt: request.prompt }; }
  function command(action: Readonly<Record<string, unknown>>): Record<string, unknown> { const kind = String(action.kind), base = { schema: "command-receipt/v2", ok: true, command: kind, outcome: "applied", opId: `${kind}:${typeof action.instanceId === "string" ? action.instanceId : "all"}`, nextAction: null }; if (kind === "runtime-instance-create") { if (!["subscription", "api-key"].includes(String(action.authMode)) || action.authMode === "subscription" && action.credentialRef !== undefined) throw coded("invalid_runtime_auth", "Runtime instance auth must select exactly subscription or an opaque API-key reference."); const auth = action.authMode === "subscription" ? { mode: "subscription" as const } : { mode: "api-key" as const, credentialRef: action.credentialRef }, config = create({ schemaVersion: 1, instanceId: action.instanceId, name: action.name, kindId: action.kindId, installationId: action.installationId, providerId: action.providerId, model: action.model, reasoningEffort: action.reasoningEffort, baseUrl: action.baseUrl, auth } as RuntimeInstanceConfig), instance = publicConfig(config); return { ...base, instance, evidence: JSON.stringify(instance), summary: `runtime-instance-create: ${config.instanceId}` }; } if (kind === "runtime-instance-list") { const instances = read().map(publicConfig), installations = input.discover().map(({ executablePath: _path, ...installation }) => installation); return { ...base, instances, installations, evidence: JSON.stringify({ instances, installations }), summary: `runtime-instance-list: ${instances.length}` }; } const instanceId = required(action.instanceId, "instanceId"); if (kind === "runtime-instance-show") { const config = readOne(instanceId); if (!config) throw coded("runtime_instance_not_found", `Runtime instance ${instanceId} does not exist.`); const instance = publicConfig(config); return { ...base, instance, evidence: JSON.stringify(instance), summary: `runtime-instance-show: ${instanceId}` }; } if (kind === "runtime-instance-delete") { remove(instanceId); return { ...base, deletedInstanceId: instanceId, evidence: `runtime-instance-deleted:${instanceId}`, summary: `runtime-instance-delete: ${instanceId}` }; } throw coded("unsupported_command", `Unsupported runtime instance command: ${kind}.`); }
  return { create, list: read, listPublic: (): readonly RuntimeInstanceSummary[] => read().map(publicConfig), read: readOne, delete: remove, stateRoot: (instanceId: string): string => path.join(instancesRoot, runtimeInstanceId(instanceId)), prepareLaunch, command };
  function read(): RuntimeInstanceConfig[] { if (!existsSync(target)) return []; chmodSync(target, 0o600); const value: unknown = JSON.parse(readFileSync(target, "utf8")); if (!record(value) || value.schema !== "runtime-instances/v1" || !Array.isArray(value.instances) || Object.keys(value).some((key) => !["schema", "instances"].includes(key))) throw coded("invalid_runtime_instance_store", "Runtime instance metadata is invalid."); return value.instances.map(runtimeInstanceConfig).sort((a, b) => a.instanceId.localeCompare(b.instanceId)); }
  function persist(instances: readonly RuntimeInstanceConfig[]): void { mkdirSync(input.userRoot, { recursive: true, mode: 0o700 }); const temp = `${target}.${process.pid}.tmp`; writeFileSync(temp, `${JSON.stringify({ schema: "runtime-instances/v1", instances: [...instances].sort((a, b) => a.instanceId.localeCompare(b.instanceId)) }, null, 2)}\n`, { encoding: "utf8", mode: 0o600 }); renameSync(temp, target); chmodSync(target, 0o600); }
  function ensureStateRoot(instanceId: string): void { const root = path.join(instancesRoot, instanceId); for (const directory of [root, ...["home", "tmp", "run"].map((name) => path.join(root, name))]) { mkdirSync(directory, { recursive: true, mode: 0o700 }); chmodSync(directory, 0o700); } }
}

function publicConfig(config: RuntimeInstanceConfig): RuntimeInstanceSummary { return { schemaVersion: config.schemaVersion, instanceId: config.instanceId, name: config.name, kindId: config.kindId, installationId: config.installationId, providerId: config.providerId, model: config.model, reasoningEffort: config.reasoningEffort ?? null, baseUrl: config.baseUrl ?? null, authMode: config.auth.mode, authState: config.auth.mode === "api-key" ? "configured" : "unknown", baseUrlConfigured: config.baseUrl !== undefined, isolationState: "enforced" }; }
function definitionSnapshot(config: RuntimeInstanceConfig): AgentDefinitionSnapshot { return { schema: "agent-definition-snapshot/v1", configVersion: config.schemaVersion, instanceId: config.instanceId, installationId: config.installationId, kindId: config.kindId, providerId: config.providerId, model: config.model, reasoningEffort: config.reasoningEffort ?? null, baseUrl: config.baseUrl ?? null, authMode: config.auth.mode }; }

function isolatedEnvironment(source: NodeJS.ProcessEnv, stateRoot: string, kindId: RuntimeInstanceKind): NodeJS.ProcessEnv { const home = path.join(stateRoot, "home"), result: NodeJS.ProcessEnv = { HOME: home, TMPDIR: path.join(stateRoot, "tmp"), XDG_RUNTIME_DIR: path.join(stateRoot, "run"), ...(kindId === "codex" ? { CODEX_HOME: path.join(home, ".codex") } : { CLAUDE_CONFIG_DIR: path.join(home, ".claude") }) }; for (const key of ["PATH", "LANG", "LC_ALL"]) if (source[key]) result[key] = source[key]; return result; }
function launchArgs(config: RuntimeInstanceConfig): string[] { if (config.kindId === "claude") return ["-p", "--model", config.model, ...(config.reasoningEffort ? ["--effort", config.reasoningEffort] : []), ...(config.auth.mode === "api-key" ? ["--bare"] : [])]; return ["exec", "--model", config.model, "-c", `model_provider="${config.providerId}"`, ...(config.reasoningEffort ? ["-c", `model_reasoning_effort="${config.reasoningEffort}"`] : []), "-"]; }
function providerSubscriptionReady(input: { readonly installation: RuntimeInstallationWitness; readonly env: NodeJS.ProcessEnv }): boolean { try { execFileSync(input.installation.executablePath, input.installation.kindId === "codex" ? ["login", "status"] : ["auth", "status", "--json"], { env: input.env, stdio: "ignore", timeout: 5_000 }); return true; } catch (error) { consumeKnownError(error); return false; } }
function resolveKeychainCredential(reference: string): string { if (process.platform !== "darwin") throw coded("runtime_credential_unavailable", "Native credential resolution is unavailable on this platform."); const [service, account, ...extra] = reference.slice("keychain:".length).split("/"); if (!service || !account || extra.length) throw coded("invalid_credential_reference", "Native credential reference is invalid."); return execFileSync("/usr/bin/security", ["find-generic-password", "-w", "-s", service, "-a", account], { encoding: "utf8", stdio: ["ignore", "pipe", "ignore"] }).replace(/[\r\n]+$/u, ""); }

export function secureRuntimeBaseUrl(value: unknown): string { const text = required(value, "baseUrl"); let parsed: URL; try { parsed = new URL(text); } catch { throw coded("invalid_base_url", "baseUrl must be an absolute HTTPS URL."); } if (parsed.username || parsed.password || parsed.search || parsed.hash || parsed.protocol !== "https:" && !(parsed.protocol === "http:" && ["127.0.0.1", "::1", "localhost"].includes(parsed.hostname))) throw coded("invalid_base_url", "baseUrl must use HTTPS or loopback HTTP and cannot contain credentials, query, or fragment."); return parsed.toString(); }
function runtimeInstanceConfig(value: unknown): RuntimeInstanceConfig { if (!record(value)) throw coded("invalid_runtime_instance", "Runtime instance must be an object."); const allowed = ["schemaVersion", "instanceId", "name", "kindId", "installationId", "providerId", "model", "reasoningEffort", "baseUrl", "auth"]; if (Object.keys(value).some((key) => !allowed.includes(key)) || value.schemaVersion !== 1 || !["claude", "codex"].includes(String(value.kindId)) || !record(value.auth)) throw coded("invalid_runtime_instance", "Runtime instance metadata is invalid."); const auth = value.auth.mode === "subscription" && Object.keys(value.auth).length === 1 ? { mode: "subscription" as const } : value.auth.mode === "api-key" && Object.keys(value.auth).every((key) => ["mode", "credentialRef"].includes(key)) ? { mode: "api-key" as const, credentialRef: credentialReference(value.auth.credentialRef) } : null; if (!auth) throw coded("invalid_runtime_auth", "Runtime instance auth must select exactly subscription or an opaque API-key reference."); const effort = value.reasoningEffort === undefined ? undefined : identifier(value.reasoningEffort, "reasoningEffort"), baseUrl = value.baseUrl === undefined ? undefined : secureRuntimeBaseUrl(value.baseUrl); return { schemaVersion: 1, instanceId: runtimeInstanceId(value.instanceId), name: required(value.name, "name"), kindId: value.kindId as RuntimeInstanceKind, installationId: identifier(value.installationId, "installationId"), providerId: identifier(value.providerId, "providerId"), model: required(value.model, "model"), ...(effort ? { reasoningEffort: effort } : {}), ...(baseUrl ? { baseUrl } : {}), auth }; }
function runtimeInstanceId(value: unknown): string { const id = required(value, "instanceId"); if (!/^[a-z0-9](?:[a-z0-9-]{0,62}[a-z0-9])?$/u.test(id)) throw coded("invalid_runtime_instance_id", "instanceId must be lowercase kebab-case."); return id; }
function identifier(value: unknown, field: string): string { const text = required(value, field); if (!/^[A-Za-z0-9][A-Za-z0-9._:-]{0,239}$/u.test(text)) throw coded("invalid_runtime_instance", `${field} is invalid.`); return text; }
function credentialReference(value: unknown): string { const text = required(value, "credentialRef"); if (!/^keychain:[A-Za-z0-9._/-]{1,240}$/u.test(text)) throw coded("invalid_credential_reference", "credentialRef must be an opaque native keychain reference."); return text; }
function required(value: unknown, field: string): string { if (typeof value === "string" && value.trim().length) return value.trim(); throw coded("invalid_runtime_instance", `${field} is required.`); }
function record(value: unknown): value is Record<string, unknown> { return value !== null && typeof value === "object" && !Array.isArray(value); }
function coded(code: string, message: string): Error { return Object.assign(new Error(message), { code }); }
function consumeKnownError(error: unknown): void { void error; }
