import { randomUUID } from "node:crypto";
import { consumeKnownError, readDaemonRegistry, registerDaemonRepo, resolveHarnessLayout, unregisterDaemonRepo, type DaemonRepoMode, type InvalidDaemonRegistryRepo, type WriteReceipt, type WriteSource } from "../../kernel/src/index.ts";
import { canonicalRoot, commandClassForAction, workspaceId, type DaemonGuiReadMethod, type DaemonGuiReadResultMap } from "./protocol/daemon-protocol.contract.ts"; import { compileRepoRepositoryScaffold, compileRepoTaskPackage, presetUserRoot, recoverPresetRunStatus } from "../../preset/src/index.ts";
import { resolveRepoBootstrap, type RepoBootstrapReceipt, type RepoBootstrapRequest } from "./repo-bootstrap.ts";
import { loadPeopleRoster } from "./identity/people-roster.ts";
import { makeTransportDerivedIdentityProvider } from "./identity/transport-derived-provider.ts";
import type { DaemonCommandClass } from "./identity/types.ts";
import type { DaemonAuthenticationContext } from "./transport/auth-context.ts";
import { causeClassOf, latchReprobeThrottleMs, openRepoCell, type RepoCell, type RepoCellBinding, type RepoCellStatus, type RepoTaskAction } from "./repo-cell.ts";
import { yieldToEventLoop } from "./process-port.ts";
import { startFleetCenterAdmission, syncFleetEdgeMirror, type FleetCenterAdmissionRequest, type FleetEdgeSyncRequest } from "./fleet-center-admission.ts"; import type { FleetTlsCenter } from "./fleet/center.ts";
import { openDocSyncWatcher, type DocSyncWatcher } from "./doc-sync-watcher.ts";
import type { AgentRuntimeAttachEvent, AgentRuntimeAttachSubscription, AgentRuntimeNativeSignal, AgentRuntimeWitnessBinding, AgentRuntimeWitnessToken } from "./agent-runtime-stream.ts";
import { currentDaemonProtocolVersion } from "./protocol/version.ts";
import type { JsonObject } from "./protocol/json-rpc-types.ts";
import { discoverRuntimeInstallations, openRuntimeInstanceStore, type RuntimeInstallationWitness } from "./agent-runtime-instances.ts";
import type { DaemonControlReceipt, TerminalAttachSubscription } from "./gui-s3-control.ts";
import type { RuntimeLauncher } from "./runtime-spawn.ts";
import { admitRepoMode, type RepoModeAdmission } from "./repo-mode.ts";
import { makeRecoveryProbe } from "./recovery-state.ts";
import type { DaemonLifecycleRecorder } from "./lifecycle-log.ts";
export interface DaemonHost {
  readonly run: (repoId: string, action: RepoTaskAction, auth: DaemonAuthenticationContext) => Promise<WriteReceipt>; readonly presetRun: (repoId: string, action: RepoTaskAction, auth: DaemonAuthenticationContext) => ReturnType<RepoCell["presetRun"]>;
  readonly replica: (repoId: string) => RepoCell["replica"];
  readonly read: <M extends DaemonGuiReadMethod>(repoId: string, method: M, payload: Readonly<Record<string, unknown>>, auth: DaemonAuthenticationContext) => Promise<DaemonGuiReadResultMap[M]>;
  readonly attach: (repoId: string, runtimeSessionId: string, afterCursor: string, auth: DaemonAuthenticationContext) => Promise<AgentRuntimeAttachSubscription>;
  readonly spawnRuntime: (repoId: string, payload: JsonObject, auth: DaemonAuthenticationContext) => Promise<JsonObject>;
  readonly cancelRuntime: (repoId: string, payload: JsonObject, auth: DaemonAuthenticationContext) => Promise<JsonObject>;
  readonly terminalAttach: (repoId: string, sessionId: string, afterSeq: number, auth: DaemonAuthenticationContext) => Promise<TerminalAttachSubscription>;
  readonly terminalAction: (repoId: string, method: string, payload: JsonObject, auth: DaemonAuthenticationContext) => Promise<JsonObject>;
  readonly runtimeInstanceAuth: (repoId: string, method: string, payload: JsonObject, auth: DaemonAuthenticationContext) => Promise<JsonObject>;
  readonly system: (auth: DaemonAuthenticationContext) => JsonObject; readonly runtimeInstance: (method: string, payload: JsonObject, auth: DaemonAuthenticationContext) => JsonObject; readonly requestControl: (payload: JsonObject, auth: DaemonAuthenticationContext) => Promise<DaemonControlReceipt>; readonly controlReceipt: (operationId: string, auth: DaemonAuthenticationContext) => DaemonControlReceipt;
  readonly issueRuntimeWitness: (repoId: string, runtimeSessionId: string, auth: DaemonAuthenticationContext) => Promise<AgentRuntimeWitnessToken>; readonly bindRuntimeWitness: (repoId: string, token: string) => AgentRuntimeWitnessBinding; readonly publishRuntimeWitness: (repoId: string, token: string, signal: AgentRuntimeNativeSignal) => AgentRuntimeAttachEvent;
  readonly bootstrap: (request: RepoBootstrapRequest, auth: DaemonAuthenticationContext) => Promise<Record<string, unknown>>;
  readonly admin: (request: { readonly kind: "register"; readonly rootDir: string; readonly repoId: string; readonly mode?: DaemonRepoMode } | { readonly kind: "unregister"; readonly repoId: string }, auth: DaemonAuthenticationContext) => Promise<Record<string, unknown>>;
  readonly fleet: { readonly startCenter: (payload: JsonObject, auth: DaemonAuthenticationContext) => Promise<Record<string, unknown>>; readonly edgeSync: (payload: JsonObject, auth: DaemonAuthenticationContext) => Promise<Record<string, unknown>> };
  readonly status: () => { readonly daemonId: string; readonly pid: number; readonly repos: readonly RepoCellStatus[]; readonly summary: string };
  readonly close: () => Promise<void>;
}
export async function openDaemonHost(input: { readonly daemonId: string; readonly userRoot: string; readonly endpoint?: string; readonly startedAt?: string; readonly now?: () => string; readonly watchOwnerUid?: number; readonly watchDebounceMs?: number; readonly runtimeLaunch?: RuntimeLauncher; readonly runtimeDiscover?: () => readonly RuntimeInstallationWitness[]; readonly shutdownRequested?: () => boolean; readonly recordLifecycle?: DaemonLifecycleRecorder }): Promise<DaemonHost> {
  const cells = new Map<string, RepoCell>(), watchers = new Map<string, DocSyncWatcher>(), watchFailures = new Map<string, string>(), ownerUid = input.watchOwnerUid ?? process.getuid?.() ?? 0;
  const unavailable = new Map<string, RepoCellStatus>(), unavailableProbes = new Map<string, ReturnType<typeof makeRecoveryProbe>>(), controls = new Map<string, DaemonControlReceipt>(), discover = input.runtimeDiscover ?? (() => discoverRuntimeInstallations()), instances = openRuntimeInstanceStore({ userRoot: input.userRoot, discover }), runtimePorts = { runtimeInstances: instances.listPublic, prepareRuntimeLaunch: instances.prepareLaunch }, startedAt = input.startedAt ?? new Date().toISOString(), now = input.now ?? (() => new Date().toISOString()), initialRegistry = readDaemonRegistry({ userRoot: input.userRoot }); let latestControl: DaemonControlReceipt | null = null; let fleetCenter: FleetTlsCenter | null = null;
  // An unavailable row reports no writer generation or queue: the cell that would own them
  // never opened, so a zero would be a fabricated measurement rather than an unknown.
  const unavailableStatus = (repoId: string, rootDir: string, mode: DaemonRepoMode, error: unknown): RepoCellStatus => ({ repoId, rootDir, mode, state: "unavailable", generation: null, queueDepth: null, recoveryMs: null, lastError: daemonErrorMessage(error), causeClass: causeClassOf(error) });
  const latchUnavailable = (repoId: string, status: RepoCellStatus): void => { unavailable.set(repoId, status); const probe = makeRecoveryProbe(latchReprobeThrottleMs); probe.latch(); unavailableProbes.set(repoId, probe); };
  for (const repo of initialRegistry.invalidRepos) if (repo.state !== "disabled") latchUnavailable(invalidRepoId(repo), invalidRegistryStatus(repo)); const repos = initialRegistry.repos.filter((repo) => repo.state === "enabled");
  // Attach one workspace per event-loop turn: attachment replays synchronously,
  // and a SIGTERM that lands mid-startup must reach its handler between repos
  // instead of waiting out the whole registry. Cell bodies are synchronous, so
  // Promise.all would interleave them on microtasks and never yield at all.
  for (const [index, repo] of repos.entries()) {
    if (input.shutdownRequested?.()) break;
    try { await openRegistered(repo, { attachIndex: index + 1, attachTotal: repos.length }); }
    catch (error) { consumeKnownError(error); latchUnavailable(repo.repoId, unavailableStatus(repo.repoId, repo.canonicalRoot, repo.mode, error)); }
    await yieldToEventLoop();
  }
  const attach = async (rootDir: string, repoId: string, mode?: DaemonRepoMode) => { const root = canonicalRoot(rootDir), id = workspaceId(repoId);
    const registered = registerDaemonRepo({ canonicalRoot: root, repoId, mode, userRoot: input.userRoot, createConvenienceLinks: false });
    const loaded = cells.get(repoId); if (loaded && loaded.status().mode !== registered.repo.mode) await closeCell(repoId);
    if (!cells.has(repoId)) try { await openRegistered({ ...registered.repo, repoId: id, canonicalRoot: root }); }
    catch (error) { consumeKnownError(error); latchUnavailable(repoId, unavailableStatus(repoId, root, registered.repo.mode, error)); }
    return registered; };
  const point = () => ({ daemonId: input.daemonId, pid: process.pid, startedAt });
  const system = (auth: DaemonAuthenticationContext): JsonObject => { localOnly(auth); const registry = readDaemonRegistry({ userRoot: input.userRoot }), observedAt = new Date().toISOString(), validRows = registry.repos.map((repo) => { const status = cells.get(repo.repoId)?.status() ?? unavailable.get(repo.repoId), disabled = repo.state === "disabled", attached = status?.state === "attached"; return { repoId: repo.repoId, displayName: repo.displayName, canonicalRoot: repo.canonicalRoot, authoredBranch: repo.authoredBranch, registrationState: repo.state, cellState: disabled ? "not_loaded" : attached ? "attached" : "unavailable", generation: disabled ? null : status?.generation ?? null, queueDepth: disabled ? null : status?.queueDepth ?? null, lockState: disabled ? "not_applicable" : attached ? "held" : "unknown", recoveryMs: disabled ? null : status?.recoveryMs ?? null, lastError: disabled ? null : status?.lastError ?? null, unavailableReason: disabled ? null : status?.lastError ?? "unknown / not projected" }; }), invalidRows = registry.invalidRepos.map(invalidRegistrySystemRow); return { schema: "gui-system-status/v1", ok: true, observedAt, daemon: { ...point(), protocolVersion: currentDaemonProtocolVersion, uptimeMs: Math.max(0, Date.parse(observedAt) - Date.parse(startedAt)), endpoint: input.endpoint ?? auth.endpoint ?? "local-unix-socket", build: { version: process.env.npm_package_version ?? "0.0.0", commitSha: process.env.HARNESS_BUILD_COMMIT ?? null }, activeControl: latestControl ? { kind: latestControl.kind, operationId: latestControl.operationId, phase: latestControl.phase, requestedAt: latestControl.requestedAt, error: latestControl.error } : null }, repos: [...validRows, ...invalidRows].sort((a, b) => a.repoId.localeCompare(b.repoId)) }; };
  const host: DaemonHost = {
    bootstrap: async (request, auth) => {
      const prepared = resolveRepoBootstrap(request, auth); await watchers.get(prepared.repoId)?.close(); watchers.delete(prepared.repoId); watchFailures.delete(prepared.repoId); await cells.get(prepared.repoId)?.close(); cells.delete(prepared.repoId); unavailable.delete(prepared.repoId); let published: RepoBootstrapReceipt | undefined, cell: RepoCell; try { cell = await openRepoCell({ repoId: prepared.repoId, rootDir: prepared.rootDir,
        mode: "local", ownerId: input.daemonId, bootstrap: prepared, onBootstrap: (receipt) => { published = receipt; }, ...runtimePorts, ...(input.runtimeLaunch ? { runtimeLaunch: input.runtimeLaunch } : {}) }); } catch (error) { if (!published?.publication.ok) throw error; return failedConfigureVerify(published, prepared.repoId, prepared.rootDir, false, error, [], "daemon-l2-readiness"); }
      let registered; try { registered = registerDaemonRepo({ canonicalRoot: prepared.rootDir, repoId: prepared.repoId, mode: "local", userRoot: input.userRoot, createConvenienceLinks: false }); cells.set(prepared.repoId, cell); await startWatch(prepared.repoId, cell); unavailable.delete(prepared.repoId); }
      catch (error) { await cell.close(); throw error; }
      const receipt = cell.bootstrapReceipt!; if (!receipt.publication.ok) return { schema: "command-receipt/v2", ok: false, command: "init", repoId: registered.repo.repoId, rootDir: prepared.rootDir, registryChanged: registered.changed, ...receipt };
      const steps = ["publication-readback"]; try { const layout = resolveHarnessLayout(prepared.rootDir), reparsed = compileRepoRepositoryScaffold(prepared.rootDir), expected = new Map(prepared.repositoryPlan.documents.map((document) => [document.slot, document.path])); if (reparsed.documents.length !== expected.size || reparsed.documents.some((document) => expected.get(document.slot) !== document.path || document.disposition === "created")) throw hostCodedError("configure_verify_layout", "Canonical repository slots did not resolve to the published paths."); steps.push("canonical-layout"); const readiness = await cell.verifyReadiness(); steps.push("daemon-l2-readiness"); const smoke = compileRepoTaskPackage({ rootDir: prepared.rootDir, taskId: "configure-verify-smoke", action: { kind: "task-create", title: "Configure Verify" } }); steps.push("task-bootstrap-dry-run"); return { schema: "command-receipt/v2", ok: true, command: "init", repoId: registered.repo.repoId, rootDir: prepared.rootDir, registryChanged: registered.changed, ...receipt, configureVerify: { ok: true, steps, roots: { contextRoot: layout.contextRoot, governanceRoot: layout.governanceRoot, standardsRoot: layout.standardsRoot, adrRoot: layout.adrRoot, milestonesRoot: layout.milestonesRoot }, requiredSlots: reparsed.documents.map(({ slot, path: target }) => ({ slot, path: target })), l2: readiness, compiledDocuments: smoke.documents.length } }; }
      catch (error) { return failedConfigureVerify(receipt, registered.repo.repoId, prepared.rootDir, registered.changed, error, steps); }
    },
    admin: async (request, auth) => { const registry = request.kind === "unregister" ? readDaemonRegistry({ userRoot: input.userRoot }) : undefined, rootDir = request.kind === "register" ? request.rootDir : registry?.repos.find((repo) => repo.repoId === request.repoId)?.canonicalRoot ?? registry?.invalidRepos.find((repo) => repo.repoId === request.repoId)?.canonicalRoot;
      if (!rootDir) throw hostCodedError("repo_namespace_unknown", `Unknown repo namespace: ${request.repoId}.`); await binding(rootDir, auth, "admin");
      if (request.kind === "register") { const result = await attach(request.rootDir, request.repoId, request.mode); return { schema: "command-receipt/v2", ok: true, command: "daemon-repo-register", outcome: "applied", repo: result.repo, changed: result.changed, summary: `repo register: repoId=${result.repo.repoId} canonicalRoot=${result.repo.canonicalRoot} mode=${result.repo.mode} changed=${result.changed}` }; }
      const result = unregisterDaemonRepo(request.repoId, { userRoot: input.userRoot, createConvenienceLinks: false }); await closeCell(request.repoId); watchFailures.delete(request.repoId); unavailable.delete(request.repoId);
      const repo = publicRegistryRepo(result.repo); return { schema: "command-receipt/v2", ok: true, command: "daemon-repo-unregister", outcome: "applied", repo, changed: result.changed, summary: `repo unregister: repoId=${repo.repoId} canonicalRoot=${String(repo.canonicalRoot)} changed=${result.changed}` }; },
    run: async (repoId, action, auth) => {
      const commandClass = commandClassForAction(action.kind), modeAdmission = admitHostMode(repoId, commandClass, auth);
      if (!modeAdmission.ok) return rejectHostAction(action, modeAdmission.code, modeAdmission.nextAction);
      await attemptHostRecovery(repoId);
      const cell = cells.get(repoId);
      if (!cell) return rejectHostAction(action, unavailable.has(repoId) ? "repo_unavailable" : "repo_namespace_unknown",
        unavailable.get(repoId)?.lastError ?? `Unknown repo namespace: ${repoId}.`);
      const spoof = ["actor", "root", "canonicalRoot", "workspaceId", "expectedRevision", "eventId", "occurredAt", "gitCredential", "credential"]
        .find((field) => Object.hasOwn(action, field));
      if (spoof) return rejectHostAction(action, "ingress_binding_forbidden", `Payload cannot report ${spoof}; daemon binds principal authority, root, revision, and time.`);
      try { const { executor: declared, ...intent } = action, executor = declaredExecutor(declared);
        return await cell.run(intent as RepoTaskAction, await binding(cell.status().rootDir, auth, commandClass, action.kind === "doc-submit", executor)); }
      catch (error) { return rejectHostAction(action, code(error), daemonErrorMessage(error)); }
    },
    replica: (repoId) => requiredCell(cells, unavailable, repoId).replica,
    presetRun: async (repoId, action, auth) => {
      const hostAdmission = admitHostMode(repoId, action.kind === "preset-run-status" ? "repo-read" : "repo-write", auth); if (!hostAdmission.ok) return rejectPresetRun(typeof action.runId === "string" ? action.runId : "run_invalid", hostAdmission.code, hostAdmission.nextAction);
      await attemptHostRecovery(repoId);
      const cell = cells.get(repoId), missing = unavailable.get(repoId), recoveryRunId = recoverableRunId(action);
      try { const { executor: declared, ...intent } = action, executor = declaredExecutor(declared), routed = intent as RepoTaskAction;
        if (!cell) { if (missing && recoveryRunId) { await binding(missing.rootDir, auth, commandClassForAction(routed.kind), false, executor); return recoverPresetRunStatus({ rootDir: missing.rootDir, userRoot: presetUserRoot(missing.rootDir) }, recoveryRunId); } return rejectPresetRun("run_invalid", missing ? "repo_unavailable" : "repo_namespace_unknown", missing?.lastError ?? `Unknown repo namespace: ${repoId}.`); }
        return await cell.presetRun(routed, await binding(cell.status().rootDir, auth, commandClassForAction(routed.kind), false, executor));
      } catch (error) { return rejectPresetRun(typeof action.runId === "string" ? action.runId : "run_invalid", code(error), daemonErrorMessage(error)); }
    },
    read: async (repoId, method, payload, auth) => { requireHostMode(repoId, "repo-read", auth); await attemptHostRecovery(repoId); const cell = cells.get(repoId);
      if (!cell) throw hostCodedError(unavailable.has(repoId) ? "repo_unavailable" : "repo_namespace_unknown", unavailable.get(repoId)?.lastError ?? `Unknown repo namespace: ${repoId}.`);
      await binding(cell.status().rootDir, auth, "repo-read"); if (method === "repo.gui.catalog.snapshot") return await cell.catalog.snapshot() as unknown as DaemonGuiReadResultMap[typeof method]; if (method === "repo.gui.catalog.preset.read") return await cell.catalog.preset(payload as JsonObject) as unknown as DaemonGuiReadResultMap[typeof method]; if (method === "repo.terminal.sessions.list") return cell.terminal.list() as DaemonGuiReadResultMap[typeof method]; return cell.read(method as import("./repo-cell.ts").RepoCellReadMethod, payload) as Promise<DaemonGuiReadResultMap[typeof method]>; },
    attach: async (repoId, runtimeSessionId, afterCursor, auth) => { requireHostMode(repoId, "repo-read", auth); await attemptHostRecovery(repoId); const cell = requiredCell(cells, unavailable, repoId); await binding(cell.status().rootDir, auth, "repo-read"); return cell.attach(runtimeSessionId, afterCursor); },
    spawnRuntime: async (repoId, payload, auth) => { requireHostMode(repoId, "repo-write", auth); await attemptHostRecovery(repoId); const cell = requiredCell(cells, unavailable, repoId), { executor: declared, ...intent } = payload, executor = declaredExecutor(declared); return cell.spawnRuntime(intent, await binding(cell.status().rootDir, auth, "repo-write", false, executor)); },
    cancelRuntime: async (repoId, payload, auth) => { requireHostMode(repoId, "repo-write", auth); await attemptHostRecovery(repoId); const cell = requiredCell(cells, unavailable, repoId), { executor: declared, ...intent } = payload, executor = declaredExecutor(declared); return cell.cancelRuntime(intent, await binding(cell.status().rootDir, auth, "repo-write", false, executor)); },
    terminalAttach: async (repoId, sessionId, afterSeq, auth) => { requireHostMode(repoId, "repo-read", auth); await attemptHostRecovery(repoId); const cell = requiredCell(cells, unavailable, repoId); await binding(cell.status().rootDir, auth, "repo-read"); return cell.terminal.attach(sessionId, afterSeq); },
    terminalAction: async (repoId, method, payload, auth) => { const commandClass = method === "repo.gui.catalog.reread" || method === "repo.terminal.detach" ? "repo-read" : "repo-write"; requireHostMode(repoId, commandClass, auth); await attemptHostRecovery(repoId); const cell = requiredCell(cells, unavailable, repoId), serverBinding = await binding(cell.status().rootDir, auth, commandClass); if (method === "repo.gui.catalog.reread") return cell.catalog.reread(payload) as Promise<JsonObject>; if (method === "repo.terminal.spawn") return cell.terminal.spawn(payload, serverBinding); if (method === "repo.terminal.input") return cell.terminal.input(payload, serverBinding); if (method === "repo.terminal.resize") return cell.terminal.resize(payload, serverBinding); if (method === "repo.terminal.detach") return cell.terminal.detach(payload); if (method === "repo.terminal.terminate") return cell.terminal.terminate(payload, serverBinding); throw hostCodedError("unsupported_command", `Unsupported terminal or catalog method: ${method}.`); },
    fleet: { startCenter: async (payload, auth) => { localOnly(auth); if (fleetCenter) throw hostCodedError("fleet_center_running", "A fleet center is already listening on this daemon; stop the daemon before starting a replacement."); const request = payload as unknown as FleetCenterAdmissionRequest["payload"], started = await startFleetCenterAdmission({ host, userRoot: input.userRoot, payload: request }); fleetCenter = started.center; return { schema: "command-receipt/v2", ok: true, command: "daemon-fleet-center-start", outcome: "applied", port: started.center.port, bind: request.bind ?? "127.0.0.1", stateRoot: started.stateRoot, quotaBytes: request.quotaBytes, nodes: started.roster.nodes.length, assignments: started.roster.assignments.length, replicas: started.center.status().replicas }; }, edgeSync: async (payload, auth) => { localOnly(auth); return syncFleetEdgeMirror({ payload: payload as unknown as FleetEdgeSyncRequest["payload"] }); } },
    system,
    runtimeInstance: (method, payload, auth) => { localOnly(auth); const operation = method.replace("daemon.runtimeInstance.", ""); if (!["create", "list", "show", "delete", "status"].includes(operation)) throw hostCodedError("unsupported_command", `Unsupported runtime instance method: ${method}.`); return instances.command({ ...payload, kind: `runtime-instance-${operation}` }) as JsonObject; },
    runtimeInstanceAuth: async (repoId, method, payload, auth) => { requireHostMode(repoId, "repo-write", auth); await attemptHostRecovery(repoId); const cell = requiredCell(cells, unavailable, repoId), serverBinding = await binding(cell.status().rootDir, auth, "repo-write"); const operation = method.slice("repo.runtimeInstance.auth.".length); if (!["login", "reauth", "logout"].includes(operation)) throw hostCodedError("unsupported_command", `Unsupported runtime auth method: ${method}.`); const command = instances.prepareAuthCommand(requiredText(payload.instanceId, "instanceId"), operation as "login" | "reauth" | "logout"), env = Object.fromEntries(Object.entries(command.env).filter((entry): entry is [string, string] => typeof entry[1] === "string")); return cell.terminal.spawnTrusted({ idempotencyKey: requiredText(payload.idempotencyKey, "idempotencyKey"), name: `${command.name} · ${operation === "logout" ? "Sign out" : operation === "reauth" ? "Re-auth" : "Sign in"}`, executablePath: command.executablePath, args: command.args, env, cwd: command.cwd, publicCwd: `runtime-instance:${command.instanceId}`, profile: "runtime-auth" }, serverBinding) as JsonObject; },
    requestControl: async (payload, auth) => { localOnly(auth); const authorityRepoId = requiredText(payload.authorityRepoId, "authorityRepoId"), repo = readDaemonRegistry({ userRoot: input.userRoot }).repos.find((entry) => entry.repoId === authorityRepoId); if (!repo) throw hostCodedError("repo_namespace_unknown", `Unknown authority repo: ${authorityRepoId}.`); await binding(repo.canonicalRoot, auth, "admin"); const kind = payload.kind; if (kind !== "refresh" && kind !== "restart") throw hostCodedError("invalid_control", "kind must be refresh or restart."); const requestedAt = new Date().toISOString(), operationId = `daemon-control-${randomUUID()}`, before = point(); if (kind === "restart") { const rejectedReceipt: DaemonControlReceipt = { schema: "daemon-control-receipt/v1", ok: false, outcome: "op_rejected", kind, operationId, phase: "failed", requestedAt, completedAt: requestedAt, before, after: null, error: { code: "supervisor_required", hint: "Electron main must own restart and its receipt." }, nextAction: "Request restart through the local Electron supervisor." }; controls.set(operationId, rejectedReceipt); latestControl = rejectedReceipt; return rejectedReceipt; } if (latestControl?.phase === "queued" || latestControl?.phase === "draining" || latestControl?.phase === "starting") { const busy: DaemonControlReceipt = { schema: "daemon-control-receipt/v1", ok: false, outcome: "op_rejected", kind, operationId, phase: "failed", requestedAt, completedAt: requestedAt, before, after: null, error: { code: "control_busy", hint: `Wait for ${latestControl.operationId}.` }, nextAction: `Poll ${latestControl.operationId}.` }; controls.set(operationId, busy); return busy; } const pending: DaemonControlReceipt = { schema: "daemon-control-receipt/v1", ok: true, outcome: "pending", kind, operationId, phase: "queued", requestedAt, completedAt: null, before, after: null, error: null, nextAction: `Poll ${operationId}.` }; controls.set(operationId, pending); latestControl = pending; void refreshRegistry().then(() => settleControl(pending, true), (error) => settleControl(pending, false, error)); return pending; },
    controlReceipt: (operationId, auth) => { localOnly(auth); const receipt = controls.get(operationId); if (receipt) return receipt; const now = new Date().toISOString(); return { schema: "daemon-control-receipt/v1", ok: false, outcome: "op_rejected", kind: "refresh", operationId, phase: "failed", requestedAt: now, completedAt: now, before: null, after: null, error: { code: "operation_not_found", hint: "No daemon control receipt exists for this operationId." }, nextAction: null }; },
    issueRuntimeWitness: async (repoId, runtimeSessionId, auth) => { requireHostMode(repoId, "repo-write", auth); await attemptHostRecovery(repoId); const cell = requiredCell(cells, unavailable, repoId), serverBinding = await binding(cell.status().rootDir, auth, "repo-write"); if (serverBinding.roles?.some((role) => role === "$admin" || role === "$arbiter")) throw hostCodedError("rbac_forbidden", "Admin and arbiter identities cannot become runtime witnesses."); return cell.runtime.issueWitnessToken(runtimeSessionId, { principalId: serverBinding.actor.principal.personId, source: serverBinding.source }); }, bindRuntimeWitness: (repoId, token) => requiredCell(cells, unavailable, repoId).runtime.bindWitness(token), publishRuntimeWitness: (repoId, token, signal) => { const cell = requiredCell(cells, unavailable, repoId), witness = cell.runtime.bindWitness(token); return cell.runtime.publish(witness.runtimeSessionId, signal); },
    status: () => ({ daemonId: input.daemonId, pid: process.pid,
      repos: [...[...cells.entries()].map(([repoId, cell]) => ({ ...cell.status(), docSync: watchers.get(repoId)?.status() ?? (cell.status().mode === "local" ? { state: "blocked", nextAction: watchFailures.get(repoId) ?? "register the Unix socket owner in the repository prose writer role" } : { state: "disabled", nextAction: "Local doc watching is disabled by repository mode." }) })), ...unavailable.values()].sort((a, b) => a.repoId.localeCompare(b.repoId)),
      summary: `daemon status: pid=${process.pid} repos=${cells.size + unavailable.size}` }),
    close: async () => { if (fleetCenter) await fleetCenter.close(); await Promise.all([...watchers.values()].map((watcher) => watcher.close())); await Promise.all([...cells.values()].map((cell) => cell.close())); }
  };
  return host;
  async function closeCell(repoId: string): Promise<void> { const cell = cells.get(repoId), closing = cell?.close(); await watchers.get(repoId)?.close(); watchers.delete(repoId); if (closing) await closing; cells.delete(repoId); }
  async function startWatch(repoId: string, cell: RepoCell): Promise<void> { if (cell.status().mode !== "local") { watchers.delete(repoId); watchFailures.delete(repoId); return; } try { const base = await binding(cell.status().rootDir, { transportKind: "unix-socket", unixSocketOwnerBoundary: { ownerUid, source: "unix-socket-filesystem-owner-boundary" } }, "repo-write", true); watchers.set(repoId, openDocSyncWatcher({ rootDir: cell.status().rootDir, personId: base.actor.principal.personId, debounceMs: input.watchDebounceMs, run: (action, attribution) => cell.run(action, attribution ? { ...base, source: { kind: "watch_session", sessionId: attribution.sessionId, path: attribution.path, fingerprint: attribution.fingerprint } } : base) })); watchFailures.delete(repoId); } catch (error) { consumeKnownError(error); watchFailures.set(repoId, error instanceof Error ? error.message : String(error)); } }
  async function openRegistered(repo: { readonly repoId: string; readonly canonicalRoot: string; readonly authoredBranch: string; readonly mode: DaemonRepoMode }, progress?: { readonly attachIndex: number; readonly attachTotal: number }): Promise<void> {
    const started = performance.now(), lifecycle = { repoId: repo.repoId, rootDir: repo.canonicalRoot, ...(progress ?? {}) }; input.recordLifecycle?.({ event: "repo_attach_started", ...lifecycle });
    try { const cell = await openRepoCell({ repoId: workspaceId(repo.repoId), rootDir: canonicalRoot(repo.canonicalRoot), mode: repo.mode, ownerId: input.daemonId, authoredBranch: repo.authoredBranch, ...(input.shutdownRequested ? { shouldStop: input.shutdownRequested } : {}), ...runtimePorts, ...(input.runtimeLaunch ? { runtimeLaunch: input.runtimeLaunch } : {}) }); cells.set(repo.repoId, cell); unavailable.delete(repo.repoId); await startWatch(repo.repoId, cell); input.recordLifecycle?.({ event: "repo_attach_completed", ...lifecycle, durationMs: performance.now() - started }); }
    catch (error) { input.recordLifecycle?.({ event: "repo_attach_failed", ...lifecycle, durationMs: performance.now() - started, error: error instanceof Error ? error.stack ?? error.message : String(error) }); throw error; }
  }
  async function refreshRegistry(): Promise<void> { const registry = readDaemonRegistry({ userRoot: input.userRoot }), enabled = new Map(registry.repos.filter((repo) => repo.state === "enabled").map((repo) => [repo.repoId, repo])), invalid = new Map(registry.invalidRepos.filter((repo) => repo.state !== "disabled").map((repo) => [invalidRepoId(repo), repo])); for (const [repoId, cell] of [...cells]) { const repo = enabled.get(repoId); if (!repo || cell.status().mode !== repo.mode) { await closeCell(repoId); unavailable.delete(repoId); unavailableProbes.delete(repoId); } } for (const repoId of [...unavailable.keys()]) if (!enabled.has(repoId) && !invalid.has(repoId)) { unavailable.delete(repoId); unavailableProbes.delete(repoId); } for (const repo of invalid.values()) latchUnavailable(invalidRepoId(repo), invalidRegistryStatus(repo)); for (const repo of enabled.values()) if (!cells.has(repo.repoId)) try { await openRegistered(repo); } catch (error) { consumeKnownError(error); latchUnavailable(repo.repoId, unavailableStatus(repo.repoId, repo.canonicalRoot, repo.mode, error)); } }
  // Host-level latch self-heal, mirroring RepoCell's attemptRecovery cadence: a repo parked in
  // `unavailable` is re-opened (openRegistered) when a command touches it, throttled to one probe
  // per interval; a fresh latch earns one immediate probe, a failed probe keeps its stamp. Success
  // moves the repo into `cells` and out of `unavailable`; failure refreshes the reported cause.
  async function attemptHostRecovery(repoId: string): Promise<void> {
    if (cells.has(repoId) || !unavailable.has(repoId)) return;
    const probe = unavailableProbes.get(repoId) ?? makeRecoveryProbe(latchReprobeThrottleMs);
    unavailableProbes.set(repoId, probe); if (!probe.begin(Date.parse(now()))) return;
    const repo = readDaemonRegistry({ userRoot: input.userRoot }).repos.find((repo) => repo.repoId === repoId && repo.state === "enabled");
    if (!repo) return;
    try { await openRegistered(repo); unavailableProbes.delete(repoId); }
    catch (error) { consumeKnownError(error); unavailable.set(repoId, unavailableStatus(repoId, repo.canonicalRoot, repo.mode, error)); }
  }
  function admitHostMode(repoId: string, commandClass: DaemonCommandClass, auth: DaemonAuthenticationContext): RepoModeAdmission { const persisted = readDaemonRegistry({ userRoot: input.userRoot }).repos.find((entry) => entry.repoId === repoId && entry.state === "enabled"), fallback = unavailable.get(repoId); if (!persisted?.mode && !fallback?.mode) return { ok: false, code: "repo_namespace_unknown", nextAction: `Unknown repo namespace: ${repoId}.` }; const source: WriteSource = auth.assignmentBinding ? { kind: "assignment", nodeId: auth.assignmentBinding.nodeId, assignmentId: auth.assignmentBinding.assignmentId } : "local"; return admitRepoMode(persisted?.mode ?? fallback!.mode!, commandClass, source); }
  function requireHostMode(repoId: string, commandClass: DaemonCommandClass, auth: DaemonAuthenticationContext): void { const admission = admitHostMode(repoId, commandClass, auth); if (!admission.ok) throw hostCodedError(admission.code, admission.nextAction); }
  function settleControl(pending: DaemonControlReceipt, ok: boolean, error?: unknown): void { const completedAt = new Date().toISOString(), settled: DaemonControlReceipt = { ...pending, ok, outcome: ok ? "pending" : "op_rejected", phase: ok ? "settled" : "failed", completedAt, after: ok ? point() : null, error: ok ? null : { code: code(error), hint: daemonErrorMessage(error) }, nextAction: ok ? null : "Repair the reported registry or RepoCell error, then request a new refresh." }; controls.set(pending.operationId, settled); latestControl = settled; }
}
async function binding(rootDir: string, auth: DaemonAuthenticationContext, required: DaemonCommandClass, returnDeniedDocDetail = false, executor: RepoCellBinding["actor"]["executor"] = null): Promise<RepoCellBinding> {
  if (auth.assignmentBinding) { if (required === "admin" || required === "arbiter") throw hostCodedError("rbac_forbidden", `Assignment ingress cannot perform ${required}.`); return { actor: auth.assignmentBinding.actor,
    source: { kind: "assignment", nodeId: auth.assignmentBinding.nodeId, assignmentId: auth.assignmentBinding.assignmentId }, docWriteAllowed: true, assignmentScope: { repoId: auth.assignmentBinding.repoId, taskId: auth.assignmentBinding.taskId, executionId: auth.assignmentBinding.executionId, paths: auth.assignmentBinding.paths } }; }
  const roster = loadPeopleRoster({ rootDir });
  const resolved = await makeTransportDerivedIdentityProvider(roster).resolveActor({ authContext: auth,
    command: required === "admin" ? { method: "daemon.repo.admin", namespace: "admin", requiresRepo: true } : { method: "repo.task.run", namespace: "repo", requiresRepo: true } });
  if (!resolved.ok) throw hostCodedError(resolved.code, resolved.message);
  const allowed = resolved.actor.roles.some((role) => roster.roleAllows(role, required)); if (!allowed && !returnDeniedDocDetail) {
    throw hostCodedError("rbac_forbidden", `Principal ${resolved.actor.personId} lacks ${required}.`);
  }
  return { actor: { principal: { personId: resolved.actor.personId }, executor },
    roles: [...resolved.actor.roles, ...(resolved.actor.roles.some((role) => roster.roleAllows(role, "arbiter")) ? ["$arbiter"] : []), ...(resolved.actor.roles.some((role) => roster.roleAllows(role, "admin")) ? ["$admin"] : [])],
    source: "local", docWriteAllowed: allowed };
}
function declaredExecutor(value: unknown): RepoCellBinding["actor"]["executor"] {
  if (value === undefined || value === null) return null;
  if (!value || typeof value !== "object" || Array.isArray(value)) throw hostCodedError("invalid_executor", "Executor must be null or an agent declaration.");
  const record = value as Record<string, unknown>, id = typeof record.id === "string" ? record.id.trim() : "";
  if (record.kind !== "agent" || !/^[A-Za-z0-9][A-Za-z0-9._:-]*$/u.test(id) || Object.keys(record).some((field) => field !== "kind" && field !== "id")) throw hostCodedError("invalid_executor", "Executor must be { kind: \"agent\", id: string }.");
  return { kind: "agent", id };
}
function rejectHostAction(action: RepoTaskAction, errorCode: string, nextAction: string): WriteReceipt { return { outcome: "op_rejected", opId: `rejected:${action.kind}`,
  code: errorCode, origin: "daemon", evidence: `rejection:${errorCode}`, nextAction }; } function rejectPresetRun(runId: string, code: string, nextAction: string) { return { schema: "preset-run-receipt/v1" as const, runId, outcome: "op_rejected" as const, phase: "op_rejected" as const, phases: ["op_rejected"] as const, code, nextAction }; }
function hostCodedError(errorCode: string, text: string): Error { const error = new Error(text) as Error & { code: string }; error.code = errorCode; return error; } function recoverableRunId(action: RepoTaskAction): string | undefined { return action.kind === "preset-run-status" && typeof action.runId === "string" ? action.runId : undefined; }
function code(error: unknown): string { return typeof error === "object" && error !== null && "code" in error && typeof error.code === "string" ? error.code : "daemon_error"; }
function daemonErrorMessage(error: unknown): string { return error instanceof Error ? error.message : String(error); }
function failedConfigureVerify(receipt: RepoBootstrapReceipt, repoId: string, rootDir: string, registryChanged: boolean, error: unknown, steps: readonly string[], failedAt = ["publication-readback", "canonical-layout", "daemon-l2-readiness", "task-bootstrap-dry-run"].find((step) => !steps.includes(step))) { const hint = `init Configure-Verify smoke failed: ${daemonErrorMessage(error)}`, next = `${receipt.next} # Repair the reported config or scaffold error, then rerun init.`; return { schema: "command-receipt/v2", ok: false, command: "init", repoId, rootDir, registryChanged, ...receipt, outcome: "partial", summary: hint, next, code: "configure_verify_failed", error: { code: "configure_verify_failed", hint }, nextAction: next, configureVerify: { ok: false, steps, failedAt, causeCode: code(error) } }; }
function requiredCell(cells: Map<string, RepoCell>, unavailable: Map<string, RepoCellStatus>, repoId: string): RepoCell { const cell = cells.get(repoId); if (!cell) throw hostCodedError(unavailable.has(repoId) ? "repo_unavailable" : "repo_namespace_unknown", unavailable.get(repoId)?.lastError ?? `Unknown repo namespace: ${repoId}.`); return cell; } function invalidRepoId(repo: InvalidDaemonRegistryRepo): string { return repo.repoId ?? `invalid-registry-entry-${repo.entryIndex + 1}`; } function invalidRegistryStatus(repo: InvalidDaemonRegistryRepo): RepoCellStatus { return { repoId: invalidRepoId(repo), rootDir: repo.canonicalRoot ?? "<invalid>", mode: repo.mode ?? null, state: "unavailable", generation: null, queueDepth: null, recoveryMs: null, lastError: repo.error, causeClass: "infrastructure" }; } function invalidRegistrySystemRow(repo: InvalidDaemonRegistryRepo) { const disabled = repo.state === "disabled"; return { repoId: invalidRepoId(repo), displayName: repo.displayName ?? invalidRepoId(repo), canonicalRoot: repo.canonicalRoot ?? "<invalid>", authoredBranch: repo.authoredBranch ?? "<invalid>", registrationState: disabled ? "disabled" as const : "enabled" as const, cellState: disabled ? "not_loaded" as const : "unavailable" as const, generation: null, queueDepth: null, lockState: disabled ? "not_applicable" as const : "unknown" as const, recoveryMs: null, lastError: repo.error, unavailableReason: repo.error }; } function publicRegistryRepo(repo: ReturnType<typeof unregisterDaemonRepo>["repo"]) { if (!("raw" in repo)) return repo; return { repoId: invalidRepoId(repo), canonicalRoot: repo.canonicalRoot ?? null, displayName: repo.displayName ?? null, authoredBranch: repo.authoredBranch ?? null, mode: repo.mode ?? null, state: repo.state ?? null, registeredAt: repo.registeredAt ?? null, unavailableReason: repo.error }; }
function localOnly(auth: DaemonAuthenticationContext): void { if (auth.transportKind !== "unix-socket" || auth.assignmentBinding) throw hostCodedError("local_transport_required", "This control is available only through the local session token."); }
function requiredText(value: unknown, field: string): string { if (typeof value === "string" && value.length) return value; throw hostCodedError("invalid_request", `${field} is required.`); }
