import { randomUUID } from "node:crypto";
import { readDaemonRegistry, registerDaemonRepo, resolveHarnessLayout, unregisterDaemonRepo, type WriteReceipt } from "../../kernel/src/index.ts";
import { canonicalRoot, commandClassForAction, workspaceId, type DaemonGuiReadMethod, type DaemonGuiReadResultMap } from "./protocol/daemon-protocol.contract.ts"; import { compileRepoRepositoryScaffold, compileRepoTaskPackage, presetUserRoot, recoverPresetRunStatus } from "../../preset/src/index.ts";
import { resolveRepoBootstrap, type RepoBootstrapReceipt, type RepoBootstrapRequest } from "./repo-bootstrap.ts";
import { loadPeopleRoster } from "./identity/people-roster.ts";
import { makeTransportDerivedIdentityProvider } from "./identity/transport-derived-provider.ts";
import type { DaemonCommandClass } from "./identity/types.ts";
import type { DaemonAuthenticationContext } from "./transport/auth-context.ts";
import { openRepoCell, type RepoCell, type RepoCellBinding, type RepoCellStatus, type RepoTaskAction } from "./repo-cell.ts";
import { openDocSyncWatcher, type DocSyncWatcher } from "./doc-sync-watcher.ts";
import type { AgentRuntimeAttachEvent, AgentRuntimeAttachSubscription, AgentRuntimeNativeSignal, AgentRuntimeWitnessBinding, AgentRuntimeWitnessToken } from "./agent-runtime-stream.ts";
import { currentDaemonProtocolVersion } from "./protocol/version.ts";
import type { JsonObject } from "./protocol/json-rpc-types.ts";
import { openRuntimeCredentialBindings } from "./runtime-credentials.ts";
import type { DaemonControlReceipt, RuntimeCredentialReceipt, TerminalAttachSubscription } from "./gui-s3-control.ts";
import type { RuntimeLauncher } from "./runtime-spawn.ts";
export interface DaemonHost {
  readonly run: (repoId: string, action: RepoTaskAction, auth: DaemonAuthenticationContext) => Promise<WriteReceipt>; readonly presetRun: (repoId: string, action: RepoTaskAction, auth: DaemonAuthenticationContext) => ReturnType<RepoCell["presetRun"]>;
  readonly replica: (repoId: string) => RepoCell["replica"];
  readonly read: <M extends DaemonGuiReadMethod>(repoId: string, method: M, payload: Readonly<Record<string, unknown>>, auth: DaemonAuthenticationContext) => Promise<DaemonGuiReadResultMap[M]>;
  readonly attach: (repoId: string, runtimeSessionId: string, afterCursor: string, auth: DaemonAuthenticationContext) => Promise<AgentRuntimeAttachSubscription>;
  readonly spawnRuntime: (repoId: string, payload: JsonObject, auth: DaemonAuthenticationContext) => Promise<JsonObject>;
  readonly terminalAttach: (repoId: string, sessionId: string, afterSeq: number, auth: DaemonAuthenticationContext) => Promise<TerminalAttachSubscription>;
  readonly terminalAction: (repoId: string, method: string, payload: JsonObject, auth: DaemonAuthenticationContext) => Promise<JsonObject>;
  readonly system: (auth: DaemonAuthenticationContext) => JsonObject; readonly requestControl: (payload: JsonObject, auth: DaemonAuthenticationContext) => Promise<DaemonControlReceipt>; readonly controlReceipt: (operationId: string, auth: DaemonAuthenticationContext) => DaemonControlReceipt; readonly bindRuntimeCredential: (payload: JsonObject, auth: DaemonAuthenticationContext) => Promise<RuntimeCredentialReceipt>;
  readonly issueRuntimeWitness: (repoId: string, runtimeSessionId: string, auth: DaemonAuthenticationContext) => Promise<AgentRuntimeWitnessToken>; readonly bindRuntimeWitness: (repoId: string, token: string) => AgentRuntimeWitnessBinding; readonly publishRuntimeWitness: (repoId: string, token: string, signal: AgentRuntimeNativeSignal) => AgentRuntimeAttachEvent;
  readonly bootstrap: (request: RepoBootstrapRequest, auth: DaemonAuthenticationContext) => Promise<Record<string, unknown>>;
  readonly admin: (request: { readonly kind: "register"; readonly rootDir: string; readonly repoId: string } | { readonly kind: "unregister"; readonly repoId: string }, auth: DaemonAuthenticationContext) => Promise<Record<string, unknown>>;
  readonly status: () => { readonly daemonId: string; readonly pid: number; readonly repos: readonly RepoCellStatus[] };
  readonly close: () => Promise<void>;
}
export async function openDaemonHost(input: { readonly daemonId: string; readonly userRoot: string; readonly endpoint?: string; readonly startedAt?: string; readonly watchOwnerUid?: number; readonly watchDebounceMs?: number; readonly runtimeLaunch?: RuntimeLauncher }): Promise<DaemonHost> {
  const cells = new Map<string, RepoCell>(), watchers = new Map<string, DocSyncWatcher>(), watchFailures = new Map<string, string>(), ownerUid = input.watchOwnerUid ?? process.getuid?.() ?? 0;
  const unavailable = new Map<string, RepoCellStatus>(), controls = new Map<string, DaemonControlReceipt>(), credentials = openRuntimeCredentialBindings({ userRoot: input.userRoot }), startedAt = input.startedAt ?? new Date().toISOString(); let latestControl: DaemonControlReceipt | null = null;
  const repos = readDaemonRegistry({ userRoot: input.userRoot }).repos.filter((repo) => repo.state === "enabled");
  await Promise.all(repos.map(async (repo) => {
    try { await openRegistered(repo); }
    catch (error) { unavailable.set(repo.repoId, { repoId: repo.repoId, rootDir: repo.canonicalRoot, state: "unavailable", generation: 0,
      queueDepth: 0, recoveryMs: 0, lastError: consumeKnownError(error) }); }
  }));
  const attach = async (rootDir: string, repoId: string) => { const root = canonicalRoot(rootDir), id = workspaceId(repoId);
    const registered = registerDaemonRepo({ canonicalRoot: root, repoId, userRoot: input.userRoot, createConvenienceLinks: false });
    if (!cells.has(repoId)) try { const cell = await openRepoCell({ repoId: id, rootDir: root, ownerId: input.daemonId, authoredBranch: registered.repo.authoredBranch, runtimeCredential: credentials.read, ...(input.runtimeLaunch ? { runtimeLaunch: input.runtimeLaunch } : {}) }); cells.set(repoId, cell); await startWatch(repoId, cell); unavailable.delete(repoId); }
    catch (error) { unavailable.set(repoId, { repoId, rootDir: root, state: "unavailable", generation: 0, queueDepth: 0, recoveryMs: 0, lastError: consumeKnownError(error) }); }
    return registered; };
  const point = () => ({ daemonId: input.daemonId, pid: process.pid, startedAt });
  const system = (auth: DaemonAuthenticationContext): JsonObject => { localOnly(auth); const registry = readDaemonRegistry({ userRoot: input.userRoot }), observedAt = new Date().toISOString(); return { schema: "gui-system-status/v1", ok: true, observedAt, daemon: { ...point(), protocolVersion: currentDaemonProtocolVersion, uptimeMs: Math.max(0, Date.parse(observedAt) - Date.parse(startedAt)), endpoint: input.endpoint ?? auth.endpoint ?? "local-unix-socket", build: { version: process.env.npm_package_version ?? "0.0.0", commitSha: process.env.HARNESS_BUILD_COMMIT ?? null }, activeControl: latestControl ? { kind: latestControl.kind, operationId: latestControl.operationId, phase: latestControl.phase, requestedAt: latestControl.requestedAt, error: latestControl.error } : null }, repos: registry.repos.map((repo) => { const status = cells.get(repo.repoId)?.status() ?? unavailable.get(repo.repoId), disabled = repo.state === "disabled", attached = status?.state === "attached"; return { repoId: repo.repoId, displayName: repo.displayName, canonicalRoot: repo.canonicalRoot, authoredBranch: repo.authoredBranch, registrationState: repo.state, cellState: disabled ? "not_loaded" : attached ? "attached" : "unavailable", generation: disabled ? null : status?.generation ?? null, queueDepth: disabled ? null : status?.queueDepth ?? null, lockState: disabled ? "not_applicable" : attached ? "held" : "unknown", recoveryMs: disabled ? null : status?.recoveryMs ?? null, lastError: disabled ? null : status?.lastError ?? null, unavailableReason: disabled ? null : status?.lastError ?? "unknown / not projected" }; }).sort((a, b) => a.repoId.localeCompare(b.repoId)) }; };
  return {
    bootstrap: async (request, auth) => {
      const prepared = resolveRepoBootstrap(request, auth); await watchers.get(prepared.repoId)?.close(); watchers.delete(prepared.repoId); watchFailures.delete(prepared.repoId); await cells.get(prepared.repoId)?.close(); cells.delete(prepared.repoId); unavailable.delete(prepared.repoId); let published: RepoBootstrapReceipt | undefined, cell: RepoCell; try { cell = await openRepoCell({ repoId: prepared.repoId, rootDir: prepared.rootDir,
        ownerId: input.daemonId, bootstrap: prepared, onBootstrap: (receipt) => { published = receipt; }, runtimeCredential: credentials.read, ...(input.runtimeLaunch ? { runtimeLaunch: input.runtimeLaunch } : {}) }); } catch (error) { if (!published?.publication.ok) throw error; return failedConfigureVerify(published, prepared.repoId, prepared.rootDir, false, error, [], "daemon-l2-readiness"); }
      let registered; try { registered = registerDaemonRepo({ canonicalRoot: prepared.rootDir, repoId: prepared.repoId, userRoot: input.userRoot, createConvenienceLinks: false }); cells.set(prepared.repoId, cell); await startWatch(prepared.repoId, cell); unavailable.delete(prepared.repoId); }
      catch (error) { await cell.close(); throw error; }
      const receipt = cell.bootstrapReceipt!; if (!receipt.publication.ok) return { schema: "command-receipt/v2", ok: false, command: "init", repoId: registered.repo.repoId, rootDir: prepared.rootDir, registryChanged: registered.changed, ...receipt };
      const steps = ["publication-readback"]; try { const layout = resolveHarnessLayout(prepared.rootDir), reparsed = compileRepoRepositoryScaffold(prepared.rootDir), expected = new Map(prepared.repositoryPlan.documents.map((document) => [document.slot, document.path])); if (reparsed.documents.length !== expected.size || reparsed.documents.some((document) => expected.get(document.slot) !== document.path || document.disposition === "created")) throw hostCodedError("configure_verify_layout", "Canonical repository slots did not resolve to the published paths."); steps.push("canonical-layout"); const readiness = await cell.verifyReadiness(); steps.push("daemon-l2-readiness"); const smoke = compileRepoTaskPackage({ rootDir: prepared.rootDir, taskId: "configure-verify-smoke", action: { kind: "task-create", title: "Configure Verify" } }); steps.push("task-bootstrap-dry-run"); return { schema: "command-receipt/v2", ok: true, command: "init", repoId: registered.repo.repoId, rootDir: prepared.rootDir, registryChanged: registered.changed, ...receipt, configureVerify: { ok: true, steps, roots: { contextRoot: layout.contextRoot, governanceRoot: layout.governanceRoot, standardsRoot: layout.standardsRoot, adrRoot: layout.adrRoot, milestonesRoot: layout.milestonesRoot }, requiredSlots: reparsed.documents.map(({ slot, path: target }) => ({ slot, path: target })), l2: readiness, compiledDocuments: smoke.documents.length } }; }
      catch (error) { return failedConfigureVerify(receipt, registered.repo.repoId, prepared.rootDir, registered.changed, error, steps); }
    },
    admin: async (request, auth) => { const rootDir = request.kind === "register" ? request.rootDir : readDaemonRegistry({ userRoot: input.userRoot }).repos.find((repo) => repo.repoId === request.repoId)?.canonicalRoot;
      if (!rootDir) throw hostCodedError("repo_namespace_unknown", `Unknown repo namespace: ${request.repoId}.`); await binding(rootDir, auth, "admin");
      if (request.kind === "register") { const result = await attach(request.rootDir, request.repoId); return { schema: "command-receipt/v2", ok: true, command: "daemon-repo-register", outcome: "applied", repo: result.repo, changed: result.changed }; }
      const result = unregisterDaemonRepo(request.repoId, { userRoot: input.userRoot, createConvenienceLinks: false }); await watchers.get(request.repoId)?.close(); watchers.delete(request.repoId); watchFailures.delete(request.repoId); await cells.get(request.repoId)?.close(); cells.delete(request.repoId); unavailable.delete(request.repoId);
      return { schema: "command-receipt/v2", ok: true, command: "daemon-repo-unregister", outcome: "applied", repo: result.repo, changed: result.changed }; },
    run: async (repoId, action, auth) => {
      const cell = cells.get(repoId);
      if (!cell) return reject(action, unavailable.has(repoId) ? "repo_unavailable" : "repo_namespace_unknown",
        unavailable.get(repoId)?.lastError ?? `Unknown repo namespace: ${repoId}.`);
      const spoof = ["actor", "root", "canonicalRoot", "source", "workspaceId", "expectedRevision", "eventId", "occurredAt", "gitCredential", "credential"]
        .find((field) => Object.hasOwn(action, field));
      if (spoof) return reject(action, "ingress_binding_forbidden", `Payload cannot report ${spoof}; daemon binds actor, root, source, revision, and time.`);
      try { return await cell.run(action, await binding(cell.status().rootDir, auth, commandClassForAction(action.kind), action.kind === "doc-submit")); }
      catch (error) { return reject(action, code(error), consumeKnownError(error)); }
    },
    replica: (repoId) => requiredCell(cells, unavailable, repoId).replica,
    presetRun: async (repoId, action, auth) => { const cell = cells.get(repoId), missing = unavailable.get(repoId), recoveryRunId = recoverableRunId(action); if (!cell) { if (missing && recoveryRunId) try { await binding(missing.rootDir, auth, commandClassForAction(action.kind)); return recoverPresetRunStatus({ rootDir: missing.rootDir, userRoot: presetUserRoot(missing.rootDir) }, recoveryRunId); } catch (error) { return rejectPresetRun(recoveryRunId, code(error), consumeKnownError(error)); } return rejectPresetRun("run_invalid", missing ? "repo_unavailable" : "repo_namespace_unknown", missing?.lastError ?? `Unknown repo namespace: ${repoId}.`); } try { return await cell.presetRun(action, await binding(cell.status().rootDir, auth, commandClassForAction(action.kind))); } catch (error) { return rejectPresetRun(typeof action.runId === "string" ? action.runId : "run_invalid", code(error), consumeKnownError(error)); } },
    read: async (repoId, method, payload, auth) => { const cell = cells.get(repoId);
      if (!cell) throw hostCodedError(unavailable.has(repoId) ? "repo_unavailable" : "repo_namespace_unknown", unavailable.get(repoId)?.lastError ?? `Unknown repo namespace: ${repoId}.`);
      await binding(cell.status().rootDir, auth, "repo-read"); if (method === "repo.gui.catalog.snapshot") return await cell.catalog.snapshot() as unknown as DaemonGuiReadResultMap[typeof method]; if (method === "repo.gui.catalog.preset.read") return await cell.catalog.preset(payload as JsonObject) as unknown as DaemonGuiReadResultMap[typeof method]; if (method === "repo.terminal.sessions.list") return cell.terminal.list() as DaemonGuiReadResultMap[typeof method]; return cell.read(method as import("./repo-cell.ts").RepoCellReadMethod, payload) as Promise<DaemonGuiReadResultMap[typeof method]>; },
    attach: async (repoId, runtimeSessionId, afterCursor, auth) => { const cell = requiredCell(cells, unavailable, repoId); await binding(cell.status().rootDir, auth, "repo-read"); return cell.attach(runtimeSessionId, afterCursor); },
    spawnRuntime: async (repoId, payload, auth) => { const cell = requiredCell(cells, unavailable, repoId); return cell.spawnRuntime(payload, await binding(cell.status().rootDir, auth, "repo-write")); },
    terminalAttach: async (repoId, sessionId, afterSeq, auth) => { const cell = requiredCell(cells, unavailable, repoId); await binding(cell.status().rootDir, auth, "repo-read"); return cell.terminal.attach(sessionId, afterSeq); },
    terminalAction: async (repoId, method, payload, auth) => { const cell = requiredCell(cells, unavailable, repoId), commandClass = method === "repo.gui.catalog.reread" || method === "repo.terminal.detach" ? "repo-read" : "repo-write"; await binding(cell.status().rootDir, auth, commandClass); if (method === "repo.gui.catalog.reread") return cell.catalog.reread(payload) as Promise<JsonObject>; if (method === "repo.terminal.spawn") return cell.terminal.spawn(payload); if (method === "repo.terminal.input") return cell.terminal.input(payload); if (method === "repo.terminal.resize") return cell.terminal.resize(payload); if (method === "repo.terminal.detach") return cell.terminal.detach(payload); if (method === "repo.terminal.terminate") return cell.terminal.terminate(payload); throw hostCodedError("unsupported_command", `Unsupported terminal or catalog method: ${method}.`); },
    system,
    requestControl: async (payload, auth) => { localOnly(auth); const authorityRepoId = requiredText(payload.authorityRepoId, "authorityRepoId"), repo = readDaemonRegistry({ userRoot: input.userRoot }).repos.find((entry) => entry.repoId === authorityRepoId); if (!repo) throw hostCodedError("repo_namespace_unknown", `Unknown authority repo: ${authorityRepoId}.`); await binding(repo.canonicalRoot, auth, "admin"); const kind = payload.kind; if (kind !== "refresh" && kind !== "restart") throw hostCodedError("invalid_control", "kind must be refresh or restart."); const requestedAt = new Date().toISOString(), operationId = `daemon-control-${randomUUID()}`, before = point(); if (kind === "restart") { const rejectedReceipt: DaemonControlReceipt = { schema: "daemon-control-receipt/v1", ok: false, outcome: "rejected", kind, operationId, phase: "failed", requestedAt, completedAt: requestedAt, before, after: null, error: { code: "supervisor_required", hint: "Electron main must own restart and its receipt." }, nextAction: "Request restart through the local Electron supervisor." }; controls.set(operationId, rejectedReceipt); latestControl = rejectedReceipt; return rejectedReceipt; } if (latestControl?.phase === "queued" || latestControl?.phase === "draining" || latestControl?.phase === "starting") { const busy: DaemonControlReceipt = { schema: "daemon-control-receipt/v1", ok: false, outcome: "rejected", kind, operationId, phase: "failed", requestedAt, completedAt: requestedAt, before, after: null, error: { code: "control_busy", hint: `Wait for ${latestControl.operationId}.` }, nextAction: `Poll ${latestControl.operationId}.` }; controls.set(operationId, busy); return busy; } const pending: DaemonControlReceipt = { schema: "daemon-control-receipt/v1", ok: true, outcome: "pending", kind, operationId, phase: "queued", requestedAt, completedAt: null, before, after: null, error: null, nextAction: `Poll ${operationId}.` }; controls.set(operationId, pending); latestControl = pending; void refreshRegistry().then(() => settleControl(pending, true), (error) => settleControl(pending, false, error)); return pending; },
    controlReceipt: (operationId, auth) => { localOnly(auth); const receipt = controls.get(operationId); if (receipt) return receipt; const now = new Date().toISOString(); return { schema: "daemon-control-receipt/v1", ok: false, outcome: "rejected", kind: "refresh", operationId, phase: "failed", requestedAt: now, completedAt: now, before: null, after: null, error: { code: "operation_not_found", hint: "No daemon control receipt exists for this operationId." }, nextAction: null }; },
    bindRuntimeCredential: async (payload, auth) => { localOnly(auth); const authorityRepoId = requiredText(payload.authorityRepoId, "authorityRepoId"), repo = readDaemonRegistry({ userRoot: input.userRoot }).repos.find((entry) => entry.repoId === authorityRepoId); if (!repo) throw hostCodedError("repo_namespace_unknown", `Unknown authority repo: ${authorityRepoId}.`); await binding(repo.canonicalRoot, auth, "admin"); return credentials.bind(payload); },
    issueRuntimeWitness: async (repoId, runtimeSessionId, auth) => { const cell = requiredCell(cells, unavailable, repoId), serverBinding = await binding(cell.status().rootDir, auth, "repo-write"); if (serverBinding.roles?.some((role) => role === "$admin" || role === "$arbiter")) throw hostCodedError("rbac_forbidden", "Admin and arbiter identities cannot become runtime witnesses."); return cell.runtime.issueWitnessToken(runtimeSessionId, { principalId: serverBinding.actor.principal.personId, source: serverBinding.source }); }, bindRuntimeWitness: (repoId, token) => requiredCell(cells, unavailable, repoId).runtime.bindWitness(token), publishRuntimeWitness: (repoId, token, signal) => { const cell = requiredCell(cells, unavailable, repoId), witness = cell.runtime.bindWitness(token); return cell.runtime.publish(witness.runtimeSessionId, signal); },
    status: () => ({ daemonId: input.daemonId, pid: process.pid,
      repos: [...[...cells.entries()].map(([repoId, cell]) => ({ ...cell.status(), docSync: watchers.get(repoId)?.status() ?? { state: "blocked", nextAction: watchFailures.get(repoId) ?? "register the Unix socket owner in the repository prose writer role" } })), ...unavailable.values()].sort((a, b) => a.repoId.localeCompare(b.repoId)) }),
    close: async () => { await Promise.all([...watchers.values()].map((watcher) => watcher.close())); await Promise.all([...cells.values()].map((cell) => cell.close())); }
  };
  async function startWatch(repoId: string, cell: RepoCell): Promise<void> { try { const base = await binding(cell.status().rootDir, { transportKind: "unix-socket", unixSocketOwnerBoundary: { ownerUid, source: "unix-socket-filesystem-owner-boundary" } }, "repo-write", true); watchers.set(repoId, openDocSyncWatcher({ rootDir: cell.status().rootDir, personId: base.actor.principal.personId, debounceMs: input.watchDebounceMs, run: (action, attribution) => cell.run(action, attribution ? { ...base, source: { kind: "watch_session", sessionId: attribution.sessionId, path: attribution.path, fingerprint: attribution.fingerprint } } : base) })); watchFailures.delete(repoId); } catch (error) { consumeKnownError(error); watchFailures.set(repoId, error instanceof Error ? error.message : String(error)); } }
  async function openRegistered(repo: { readonly repoId: string; readonly canonicalRoot: string; readonly authoredBranch: string }): Promise<void> { const cell = await openRepoCell({ repoId: workspaceId(repo.repoId), rootDir: canonicalRoot(repo.canonicalRoot), ownerId: input.daemonId, authoredBranch: repo.authoredBranch, runtimeCredential: credentials.read, ...(input.runtimeLaunch ? { runtimeLaunch: input.runtimeLaunch } : {}) }); cells.set(repo.repoId, cell); unavailable.delete(repo.repoId); await startWatch(repo.repoId, cell); }
  async function refreshRegistry(): Promise<void> { const registry = readDaemonRegistry({ userRoot: input.userRoot }), enabled = new Map(registry.repos.filter((repo) => repo.state === "enabled").map((repo) => [repo.repoId, repo])); for (const repoId of [...cells.keys()]) if (!enabled.has(repoId)) { await watchers.get(repoId)?.close(); watchers.delete(repoId); await cells.get(repoId)?.close(); cells.delete(repoId); unavailable.delete(repoId); } for (const repoId of [...unavailable.keys()]) if (!enabled.has(repoId)) unavailable.delete(repoId); for (const repo of enabled.values()) if (!cells.has(repo.repoId)) try { await openRegistered(repo); } catch (error) { unavailable.set(repo.repoId, { repoId: repo.repoId, rootDir: repo.canonicalRoot, state: "unavailable", generation: 0, queueDepth: 0, recoveryMs: 0, lastError: consumeKnownError(error) }); } }
  function settleControl(pending: DaemonControlReceipt, ok: boolean, error?: unknown): void { const completedAt = new Date().toISOString(), settled: DaemonControlReceipt = { ...pending, ok, outcome: ok ? "pending" : "rejected", phase: ok ? "settled" : "failed", completedAt, after: ok ? point() : null, error: ok ? null : { code: code(error), hint: consumeKnownError(error) }, nextAction: ok ? null : "Repair the reported registry or RepoCell error, then request a new refresh." }; controls.set(pending.operationId, settled); latestControl = settled; }
}
async function binding(rootDir: string, auth: DaemonAuthenticationContext, required: DaemonCommandClass, returnDeniedDocDetail = false): Promise<RepoCellBinding> {
  if (auth.assignmentBinding) { if (required === "admin" || required === "arbiter") throw hostCodedError("rbac_forbidden", `Assignment ingress cannot perform ${required}.`); return { actor: auth.assignmentBinding.actor,
    source: { kind: "assignment", nodeId: auth.assignmentBinding.nodeId, assignmentId: auth.assignmentBinding.assignmentId }, docWriteAllowed: true, assignmentScope: { repoId: auth.assignmentBinding.repoId, taskId: auth.assignmentBinding.taskId, executionId: auth.assignmentBinding.executionId, paths: auth.assignmentBinding.paths } }; }
  const roster = loadPeopleRoster({ rootDir });
  const resolved = await makeTransportDerivedIdentityProvider(roster).resolveActor({ authContext: auth,
    command: required === "admin" ? { method: "daemon.repo.admin", namespace: "admin", requiresRepo: true } : { method: "repo.task.run", namespace: "repo", requiresRepo: true } });
  if (!resolved.ok) throw hostCodedError(resolved.code, resolved.message);
  const allowed = resolved.actor.roles.some((role) => roster.roleAllows(role, required)); if (!allowed && !returnDeniedDocDetail) {
    throw hostCodedError("rbac_forbidden", `Principal ${resolved.actor.personId} lacks ${required}.`);
  }
  return { actor: { principal: { personId: resolved.actor.personId }, executor: null },
    roles: [...resolved.actor.roles, ...(resolved.actor.roles.some((role) => roster.roleAllows(role, "arbiter")) ? ["$arbiter"] : []), ...(resolved.actor.roles.some((role) => roster.roleAllows(role, "admin")) ? ["$admin"] : [])],
    source: "local", docWriteAllowed: allowed };
}
function reject(action: RepoTaskAction, errorCode: string, nextAction: string): WriteReceipt { return { outcome: "rejected", opId: `rejected:${action.kind}`,
  code: errorCode, origin: "daemon", evidence: `rejection:${errorCode}`, nextAction }; } function rejectPresetRun(runId: string, code: string, nextAction: string) { return { schema: "preset-run-receipt/v1" as const, runId, outcome: "rejected" as const, phase: "rejected" as const, phases: ["rejected"] as const, code, nextAction }; }
function hostCodedError(errorCode: string, text: string): Error { const error = new Error(text) as Error & { code: string }; error.code = errorCode; return error; } function recoverableRunId(action: RepoTaskAction): string | undefined { return action.kind === "preset-run-status" && typeof action.runId === "string" ? action.runId : undefined; }
function code(error: unknown): string { return typeof error === "object" && error !== null && "code" in error && typeof error.code === "string" ? error.code : "daemon_error"; }
function consumeKnownError(error: unknown): string { return error instanceof Error ? error.message : String(error); }
function failedConfigureVerify(receipt: RepoBootstrapReceipt, repoId: string, rootDir: string, registryChanged: boolean, error: unknown, steps: readonly string[], failedAt = ["publication-readback", "canonical-layout", "daemon-l2-readiness", "task-bootstrap-dry-run"].find((step) => !steps.includes(step))) { const hint = `init Configure-Verify smoke failed: ${consumeKnownError(error)}`, next = `${receipt.next} # Repair the reported config or scaffold error, then rerun init.`; return { schema: "command-receipt/v2", ok: false, command: "init", repoId, rootDir, registryChanged, ...receipt, outcome: "partial", summary: hint, next, code: "configure_verify_failed", error: { code: "configure_verify_failed", hint }, nextAction: next, configureVerify: { ok: false, steps, failedAt, causeCode: code(error) } }; }
function requiredCell(cells: Map<string, RepoCell>, unavailable: Map<string, RepoCellStatus>, repoId: string): RepoCell { const cell = cells.get(repoId); if (!cell) throw hostCodedError(unavailable.has(repoId) ? "repo_unavailable" : "repo_namespace_unknown", unavailable.get(repoId)?.lastError ?? `Unknown repo namespace: ${repoId}.`); return cell; }
function localOnly(auth: DaemonAuthenticationContext): void { if (auth.transportKind !== "unix-socket" || auth.assignmentBinding) throw hostCodedError("local_transport_required", "This control is available only through the local session token."); }
function requiredText(value: unknown, field: string): string { if (typeof value === "string" && value.length) return value; throw hostCodedError("invalid_request", `${field} is required.`); }
