import { decisionDocumentProse, decisionMachineDigest, deriveRelationId, readFrontmatter, readScalar, stableStringify, type DecisionAmendableSnapshot, type DecisionListFilters, type DecisionProjectionRow, type TaskProjection } from "../../kernel/src/index.ts";

interface DecisionReadService { readonly show: (selector: string) => { readonly status: "ready" | "pending"; readonly watermark: number; readonly sourceRevision: number; readonly decision: DecisionProjectionRow }; readonly list: (filters: DecisionListFilters) => { readonly status: "ready" | "pending"; readonly watermark: number; readonly sourceRevision: number; readonly decisions: readonly DecisionProjectionRow[] } }

export function prepareDecisionAmend(action: Readonly<Record<string, unknown>>, current: DecisionProjectionRow): Readonly<Record<string, unknown>> {
  let title = current.title, decisionClass = current.decisionClass, chosen = [...current.chosen], rejected = [...current.rejected], claims = current.claims.map((claim) => ({ ...claim }));
  if (typeof action.title === "string") title = action.title;
  const sets = stringArray(action.sets, "sets"); if (typeof action.title === "string" && sets.some((entry) => entry.startsWith("title:"))) fail("Specify title with either --title or --set, not both."); for (const patch of sets) { const parsed = splitPatch(patch); if (parsed.field !== "title") fail(`replace is not supported for Decision field: ${parsed.field}`); title = parsed.value; }
  if (action.standingPolicy === true) decisionClass = "standing_policy";
  for (const patch of stringArray(action.appends, "appends")) { const { field, value } = splitPatch(patch), row = jsonObject(value); if (field === "chosen") { const id = optionalId(row.id) ?? nextId("CH", chosen.map(({ id: valueId }) => valueId)), text = required(row.text, "chosen.text"); chosen = [...chosen, { id, text, ...(typeof row.rationale === "string" && row.rationale.trim() ? { rationale: row.rationale } : {}) }]; continue; } if (field === "rejected") { const id = optionalId(row.id) ?? nextId("RJ", rejected.map(({ id: valueId }) => valueId)), text = required(row.text, "rejected.text"), whyNot = required(row.whyNot ?? row.why_not, "rejected.whyNot"); rejected = [...rejected, { id, text, whyNot }]; continue; } if (field === "claims") { const id = optionalId(row.id) ?? nextId("C", claims.map(({ id: valueId }) => valueId)), text = required(row.text, "claims.text"), loadBearing = typeof row.loadBearing === "boolean" ? row.loadBearing : typeof row.load_bearing === "boolean" ? row.load_bearing : true; claims = [...claims, { id, text, loadBearing, fulfillment: null }]; continue; } fail(`append is not supported for Decision field: ${field}`); }
  if (action.loadBearing && typeof action.loadBearing === "object" && !Array.isArray(action.loadBearing)) { const patch = action.loadBearing as Readonly<Record<string, unknown>>, claimId = required(patch.claimId, "loadBearing.claimId"); let found = false; claims = claims.map((claim) => claim.id === claimId ? (found = true, { ...claim, loadBearing: patch.value === true }) : claim); if (!found) fail(`Claim ${claimId} does not exist.`); }
  for (const value of array(action.fulfillments, "fulfillments")) { const fulfillment = jsonObjectValue(value, "fulfillment"), claimId = required(fulfillment.claimId, "fulfillment.claimId"), mode = fulfillment.mode; if (!["evidenced", "delivered", "standing_policy"].includes(String(mode))) fail(`Fulfillment mode for ${claimId} is invalid.`); let found = false; claims = claims.map((claim) => { if (claim.id !== claimId) return claim; found = true; if (claim.fulfillment !== null) fail(`Claim ${claimId} already has a fulfillment.`); return { ...claim, fulfillment: mode as "evidenced" | "delivered" | "standing_policy" }; }); if (!found) fail(`Claim ${claimId} does not exist.`); }
  const next: DecisionAmendableSnapshot = { title, decisionClass, chosen, rejected, claims }, fields = [title !== current.title ? "title" : null, decisionClass !== current.decisionClass ? "decisionClass" : null, JSON.stringify(chosen) !== JSON.stringify(current.chosen) ? "chosen" : null, JSON.stringify(rejected) !== JSON.stringify(current.rejected) ? "rejected" : null, JSON.stringify(claims) !== JSON.stringify(current.claims) ? "claims" : null, typeof action.body === "string" ? "body" : null].filter((field): field is string => field !== null); if (!fields.length) fail("Decision amend produced no effective machine-field or prose change."); return { ...action, next, fields };
}

export function validateDecisionPackages(action: Readonly<Record<string, unknown>>, service: DecisionReadService, projection: TaskProjection) { const selection = typeof action.decisionId === "string" ? service.show(action.decisionId) : service.list({}), decisions = "decision" in selection ? [selection.decision] : selection.decisions, graph = projection.readDecisionGraph(), rows = decisions.map((decision) => validateOne(decision, projection, graph.edges)); return { status: selection.status, watermark: Math.min(selection.watermark, graph.watermark), sourceRevision: Math.max(selection.sourceRevision, graph.sourceRevision), rows, report: { schema: "decision-validation-report/v1", checkedDecisionCount: rows.length, validDecisionCount: rows.filter(({ valid }) => valid).length, warningCount: rows.reduce((sum, row) => sum + row.warnings.length, 0), errorCount: rows.reduce((sum, row) => sum + row.errors.length, 0), readOnly: true } }; }

function validateOne(decision: DecisionProjectionRow, projection: TaskProjection, edges: ReturnType<TaskProjection["readDecisionGraph"]>["edges"]) { const errors: string[] = [], warnings: string[] = [], document = projection.readDocument(decision.path).document, relations = edges.filter((edge) => edge.ownerRef === `decision/${decision.decisionId}`).map((edge) => ({ relation_id: edge.relationId, source: edge.sourceRef, target: edge.targetRef, type: edge.relationType, strength: edge.strength, direction: edge.direction, origin: edge.origin, rationale: edge.rationale, state: edge.state })); if (!document) errors.push("decision package document is missing"); let frontmatter: string | null = null; try { frontmatter = document ? readFrontmatter(document.body) : null; } catch (error) { consumeKnownError(error); errors.push("decision frontmatter is malformed"); } if (!frontmatter) errors.push("decision frontmatter is missing"); else { if (readScalar(frontmatter, "schema") !== "decision-package/v1") errors.push("schema must be decision-package/v1"); if (readScalar(frontmatter, "decision_id") !== decision.decisionId) errors.push("decision_id does not match the package identity"); for (const [field, expected] of [["state", decision.state], ["title", decision.title], ["decisionClass", decision.decisionClass]] as const) if (unquote(readScalar(frontmatter, field)) !== expected) errors.push(`${field} does not match the live projection`); for (const [field, expected] of [["chosen", decision.chosen], ["rejected", decision.rejected], ["claims", decision.claims], ["relations", relations]] as const) if (!jsonEqual(readScalar(frontmatter, field), expected)) errors.push(`${field} does not match the live projection`); if (decision.amendments && !jsonEqual(readScalar(frontmatter, "amendments"), decision.amendments)) errors.push("amendment chain does not match the live projection"); if (decision.contentPins && !jsonEqual(readScalar(frontmatter, "contentPins"), decision.contentPins)) errors.push("content pin chain does not match the live projection"); }
  for (const relation of relations) if (relation.relation_id !== deriveRelationId(relation)) errors.push(`relation ${relation.relation_id} is not deterministic`); if (document && frontmatter && !decisionDocumentProse(document.body).trim()) warnings.push("Decision markdown body is empty. Add a human-readable narrative with background, trade-offs, and a plain-language conclusion."); const { body: _body, readiness: _readiness, ...state } = decision, digest = decisionMachineDigest({ ...state, relations }), latestPin = decision.contentPins?.at(-1); if (!latestPin && decision.state !== "proposed") warnings.push("terminal Decision has no content pin (legacy v1 event)"); if (latestPin && latestPin.digest !== digest) warnings.push("latest content pin is stale; run decision repin with migration evidence"); return { decisionId: decision.decisionId, path: decision.path, state: decision.state, valid: errors.length === 0, errors, warnings, latestDigest: digest, latestPinId: latestPin?.pinId ?? null }; }
function splitPatch(value: string): { readonly field: string; readonly value: string } { const at = value.indexOf(":"); if (at < 1 || !value.slice(at + 1).trim()) fail("Decision amend patch must be <field>:<value>."); return { field: value.slice(0, at).trim(), value: value.slice(at + 1).trim() }; }
function nextId(prefix: "CH" | "RJ" | "C", ids: readonly string[]): string { for (let index = 1; ; index += 1) { const candidate = `${prefix}${index}`; if (!ids.includes(candidate)) return candidate; } }
function optionalId(value: unknown): string | null { return typeof value === "string" && value.trim() ? value : null; }
function jsonObject(value: string): Readonly<Record<string, unknown>> { let parsed: unknown; try { parsed = JSON.parse(value); } catch (error) { consumeKnownError(error); fail("Decision append value must be a JSON object."); } return jsonObjectValue(parsed, "append"); }
function jsonObjectValue(value: unknown, field: string): Readonly<Record<string, unknown>> { if (value && typeof value === "object" && !Array.isArray(value)) return value as Readonly<Record<string, unknown>>; fail(`${field} must be an object.`); }
function stringArray(value: unknown, field: string): readonly string[] { if (Array.isArray(value) && value.every((entry) => typeof entry === "string")) return value; fail(`${field} must be an array of strings.`); }
function array(value: unknown, field: string): readonly unknown[] { if (Array.isArray(value)) return value; fail(`${field} must be an array.`); }
function required(value: unknown, field: string): string { if (typeof value === "string" && value.trim()) return value; fail(`${field} is required.`); }
function jsonEqual(value: string, expected: unknown): boolean { try { return stableStringify(JSON.parse(value)) === stableStringify(expected); } catch (error) { consumeKnownError(error); return false; } }
function unquote(value: string): string { try { const parsed = JSON.parse(value); return typeof parsed === "string" ? parsed : value; } catch (error) { consumeKnownError(error); return value; } }
function fail(message: string): never { const error = new Error(message) as Error & { code: string }; error.code = "invalid_command"; throw error; }
function consumeKnownError(error: unknown): void { void error; }
