import { execFileSync } from "node:child_process";
import { existsSync, lstatSync, readFileSync, readdirSync } from "node:fs";
import path from "node:path";
import { DOC_POLICY_ID, decideDocWrite, documentPath, parseDocWriteIntent, resolveDocRoute, resolveHarnessLayout, resolveLedgerGitLayout, sha256Bytes,
  type ActorIdentity, type CanonicalEventStore, type DocWriteIntent, type LedgerCommitSha, type TaskProjection, type WriteSource } from "../../kernel/src/index.ts";

export type DocCandidateState = "clean" | "eligible" | "blocked" | "deletion" | "conflict";
export interface DocCandidateRow { readonly path: string; readonly state: DocCandidateState; readonly reason: string | null; readonly baseBlobSha256: string | null; readonly candidateBlobSha256: string | null; readonly size: number | null; readonly mediaType: "text/markdown" | "text/plain" | null; readonly conflicts: readonly string[] }
export interface ScannedDocCandidate extends DocCandidateRow { readonly bytes: Uint8Array | null; readonly rejectionCode: string | null; readonly requiredRoute: string | null }
export interface DocCandidateScan { readonly baseLedgerSha: LedgerCommitSha; readonly executionId: string | null; readonly lease: ReturnType<TaskProjection["currentLeaseForExecution"]>; readonly rows: readonly ScannedDocCandidate[] }

export function scanDocCandidates(input: { readonly rootDir: string; readonly workspaceId: string; readonly store: CanonicalEventStore; readonly projection: TaskProjection; readonly actor: ActorIdentity; readonly source: WriteSource; readonly now: string; readonly selection?: readonly string[]; readonly executionId?: string }): DocCandidateScan {
  const layout = resolveHarnessLayout(input.rootDir), ledger = resolveLedgerGitLayout(input.rootDir), selected = input.selection?.map((value) => documentPath(value)), candidates = selected?.length ? [...new Set(selected)] : dirtyPaths(ledger.rootDir, ledger.authoredPrefix), paths = candidates.filter((value) => selected?.length || prosePath(value) || !resolveDocRoute(documentPath(value)).allowed).sort(), baseLedgerSha = input.store.currentCommit(), execution = executionBinding(paths, input.executionId, input.projection, input.now), rows = paths.map((logical) => scanOne(logical));
  return { baseLedgerSha, executionId: execution.id, lease: execution.lease, rows };
  function scanOne(logical: string): ScannedDocCandidate {
    const route = resolveDocRoute(documentPath(logical)), target = path.join(layout.authoredRoot, ...logical.split("/")), projected = input.projection.readDocument(documentPath(logical)), conflicts = conflictsFor(logical), safe = directFile(layout.authoredRoot, logical), bytes = safe && existsSync(target) ? readFileSync(target) : null, base = projected.document?.blobSha256 ?? null, candidate = bytes === null ? null : sha256Bytes(bytes);
    if (!route.allowed) return safe && candidate !== null && candidate === base ? scannedCandidateRow("clean", null, bytes, base, candidate, logical.endsWith(".md") ? "text/markdown" : "text/plain") : scannedCandidateRow("blocked", safe ? `path is owned by ${route.requiredRoute}` : "path contains a symbolic link or is not a regular file", bytes, base, candidate, null, null, route.requiredRoute);
    if (!prosePath(logical)) return scannedCandidateRow("blocked", "path is not canonical prose", null, projected.document?.blobSha256 ?? null, null);
    if (projected.watermark !== projected.sourceRevision) return scannedCandidateRow("blocked", "canonical projection is pending", null, projected.document?.blobSha256 ?? null, null);
    if (!safe) return scannedCandidateRow("blocked", "path contains a symbolic link or is not a regular file", null, projected.document?.blobSha256 ?? null, null);
    if (bytes === null) return scannedCandidateRow(projected.document ? "deletion" : "clean", projected.document ? "canonical document is missing from the worktree" : null, null, base, null, null, projected.document ? "deletion_forbidden" : null);
    const mediaType = logical.endsWith(".md") ? "text/markdown" as const : "text/plain" as const; if (candidate === base) return scannedCandidateRow(conflicts.length ? "conflict" : "clean", conflicts.length ? "local conflict scratch requires resolution" : null, bytes, base, candidate, mediaType);
    const intent = parseDocWriteIntent({ schema: "doc-write-intent/v1", executionId: execution.id, baseLedgerSha: baseLedgerSha.sha, changes: [{ path: logical, baseBlobSha256: base, policyId: DOC_POLICY_ID, candidate: { ref: `doc-sync-claims/${candidate}`, sha256: candidate, size: bytes.byteLength, mediaType } }] }, input.workspaceId), decision = decideDocWrite({ intent, opId: "scan", eventId: "scan", workspaceRevision: (input.store.readHead()?.revision ?? 0) + 1, actor: input.actor, source: input.source, occurredAt: input.now, currentLedgerSha: baseLedgerSha, lease: execution.lease, documents: [projected.document], claims: [bytes], resolvedTaskIds: [input.projection.taskIdForDocumentPath(logical)] });
    return decision.accepted ? scannedCandidateRow("eligible", null, bytes, base, candidate, mediaType) : scannedCandidateRow(decision.code === "deletion_forbidden" ? "deletion" : "blocked", decision.detail.unresolvedTouches[0]?.reason ?? decision.detail.nextAction, bytes, base, candidate, mediaType, decision.code, decision.detail.unresolvedTouches[0]?.requiredRoute ?? null);
    function scannedCandidateRow(state: DocCandidateState, reason: string | null, body: Uint8Array | null, baseHash: string | null, candidateHash: string | null, media: "text/markdown" | "text/plain" | null = null, rejectionCode: string | null = null, requiredRoute: string | null = null): ScannedDocCandidate { return { path: logical, state, reason, baseBlobSha256: baseHash, candidateBlobSha256: candidateHash, size: body?.byteLength ?? null, mediaType: media, conflicts, bytes: body, rejectionCode, requiredRoute }; }
  }
  function conflictsFor(logical: string): string[] { const target = path.join(layout.authoredRoot, ...logical.split("/")), extension = path.extname(target), stem = path.basename(target, extension), directory = path.dirname(target); if (!existsSync(directory)) return []; return readdirSync(directory).filter((name) => name.startsWith(`${stem}.conflict-`) && name.endsWith(extension) && /^[0-9a-f]{8}$/u.test(name.slice(`${stem}.conflict-`.length, -extension.length))).map((name) => relative(input.rootDir, path.join(directory, name))).sort(); }
}

export function intentFromScan(scan: DocCandidateScan, workspaceId: string): { readonly intent: DocWriteIntent; readonly claims: readonly Uint8Array[] } { const eligible = scan.rows.filter((row) => row.state === "eligible"); return { intent: parseDocWriteIntent({ schema: "doc-write-intent/v1", executionId: scan.executionId, baseLedgerSha: scan.baseLedgerSha.sha, changes: eligible.map((row) => ({ path: row.path, baseBlobSha256: row.baseBlobSha256, policyId: DOC_POLICY_ID, candidate: { ref: `doc-sync-claims/${row.candidateBlobSha256}`, sha256: row.candidateBlobSha256, size: row.size, mediaType: row.mediaType } })) }, workspaceId), claims: eligible.map((row) => row.bytes!) }; }
export function publicScan(scan: DocCandidateScan): { readonly baseLedgerSha: string; readonly rows: readonly DocCandidateRow[] } { return { baseLedgerSha: scan.baseLedgerSha.sha, rows: scan.rows.map(({ bytes: _bytes, rejectionCode: _rejectionCode, requiredRoute: _requiredRoute, ...row }) => row) }; }

function executionBinding(paths: readonly string[], explicit: string | undefined, projection: TaskProjection, now: string) { if (explicit) return { id: explicit, lease: projection.currentLeaseForExecution(explicit, now) }; const tasks = [...new Set(paths.flatMap((value) => projection.taskIdForDocumentPath(value) ?? []))], current = tasks.length === 1 ? projection.currentLease(tasks[0]!, now) : null, lease = current?.phase === "held" ? current : null; return { id: lease?.executionId ?? null, lease }; }
function dirtyPaths(repoRoot: string, authoredPrefix: string): string[] { const scope = authoredPrefix || ".", changed = gitNames(repoRoot, ["diff", "--name-only", "-z", "HEAD", "--", scope]), untracked = gitNames(repoRoot, ["ls-files", "--others", "--exclude-standard", "-z", "--", scope]), prefix = authoredPrefix ? `${authoredPrefix}/` : ""; return [...new Set([...changed, ...untracked].filter((value) => (!prefix || value.startsWith(prefix)) && !value.includes(".conflict-")).map((value) => value.slice(prefix.length)).concat(conflictLogicalPaths(path.join(repoRoot, authoredPrefix))))]; }
function conflictLogicalPaths(authoredRoot: string): string[] { const found: string[] = []; const visit = (directory: string) => { if (!existsSync(directory)) return; for (const entry of readdirSync(directory, { withFileTypes: true })) { const target = path.join(directory, entry.name); if (entry.isDirectory()) visit(target); else if (entry.isFile() && /\.conflict-[0-9a-f]{8}\.(?:md|txt)$/u.test(entry.name)) found.push(relative(authoredRoot, target).replace(/\.conflict-[0-9a-f]{8}(?=\.(?:md|txt)$)/u, "")); } }; visit(authoredRoot); return found; }
function gitNames(repoRoot: string, args: readonly string[]): string[] { return execFileSync("git", ["-C", repoRoot, ...args], { encoding: "utf8" }).split("\0").filter(Boolean); }
function prosePath(value: string): boolean { return value.endsWith(".md") || value.endsWith(".txt"); }
function relative(root: string, target: string): string { return path.relative(root, target).split(path.sep).join("/"); }
function directFile(authoredRoot: string, logical: string): boolean { let target = authoredRoot; if (existsSync(target) && lstatSync(target).isSymbolicLink()) return false; for (const segment of logical.split("/")) { target = path.join(target, segment); if (existsSync(target) && lstatSync(target).isSymbolicLink()) return false; } return !existsSync(target) || lstatSync(target).isFile(); }
