import { execFileSync } from "node:child_process";
import { existsSync, lstatSync, readFileSync, realpathSync, unlinkSync } from "node:fs";
import path from "node:path";
import { classifyTextualArtifactPath, consumeKnownError } from "../../kernel/src/index.ts";
import { DOC_POLICY_ID, canonicalEventCut, decideDocWrite, docSyncWritePlan, documentPath, isDocEvent, ledgerGitPath, normalizeCommandEnvelope, parseDocWriteIntent, resolveDocRoute, resolveHarnessLayout, resolveLedgerGitLayout, sha256Bytes, stableStringify,
  type ActorIdentity, type DocClaimRef, type DocEventV1, type DocSyncReceiptDetail, type DocWriteIntent, type EventPublicationKillpoint, type LedgerCutIdentity, type VerticalScriptActionV1, type VerticalScriptChangeV1, type WriteReceipt, type WriteSource } from "../../kernel/src/index.ts";
import type { CanonicalEventStore, TaskProjection } from "../../kernel/src/index.ts";
import type { FleetAssignmentScope } from "./fleet/contract.ts";
import { intentFromScan, publicScan, scanDocCandidates, type DocCandidateScan } from "./doc-sync-candidate-scanner.ts";

export const DOC_COMMAND_FRAME_MAX_BYTES = 256 * 1024; type Action = Readonly<Record<string, unknown>> & { readonly kind: string };
interface Binding { readonly actor: ActorIdentity; readonly source: WriteSource; readonly docWriteAllowed?: boolean; readonly assignmentScope?: FleetAssignmentScope }
type Input = { readonly action: Action; readonly binding: Binding; readonly workspaceId: string; readonly rootDir: string; readonly store: CanonicalEventStore; readonly projection: TaskProjection; readonly now: () => string; readonly killpoint?: (point: EventPublicationKillpoint) => void };
export type DocSettlementReceipt = WriteReceipt & { readonly commitSha?: string | null; readonly settlement?: WriteReceipt["outcome"]; readonly receiptId?: string; readonly summary?: string };
export type ArtifactAddReceipt = DocSettlementReceipt & { readonly source?: string; readonly destination?: string };
export interface RuntimeDispatchArchive { readonly dispatchId: string; readonly taskId: string; readonly executionId: string; readonly agentId?: string; readonly agentName?: string; readonly delegatedByAgentId?: string; readonly delegatedByAgentName?: string; readonly squadId?: string; readonly instanceId: string; readonly model: string; readonly reasoningEffort: string | null; readonly cwd: string; readonly prompt: string; readonly promptSource?: string; readonly runtimeSessionId: string; readonly providerSessionId: string | null; readonly startedAt: string; readonly endedAt: string; readonly outcome: "succeeded" | "failed" | "unknown" | "cancelled"; readonly exitCode: number | null; readonly resultRef: string; readonly resultText: string; readonly eventStreamRef?: string }

export function isDocAction(kind: string): boolean { return kind === "doc-status" || kind === "doc-dry-run" || kind === "doc-submit" || kind === "doc-materialize" || kind === "doc-show" || kind === "doc-retire"; }
export async function runDocAction(input: Input): Promise<WriteReceipt> {
  if (Buffer.byteLength(JSON.stringify(input.action)) > DOC_COMMAND_FRAME_MAX_BYTES) throw docSyncError("invalid_command", "doc command frame exceeds the descriptor-only limit");
  if (input.action.kind === "doc-materialize") { if (!hasExactDocSyncActionFields(input.action, ["kind"])) throw docSyncError("invalid_command", "doc materialize takes no options"); const result = input.store.materialize(), revision = input.store.readHead()?.revision ?? 0; return { outcome: "applied", opId: `materialize:${result.commitSha.sha}`, revision, evidence: `doc-materialize:${stableStringify({ changed: result.changed, conflicts: result.conflicts })}`, visibility: "center", proof: proof(revision, revision, true, true) }; }
  if (input.action.kind === "doc-retire") return runDocRetire(input);
  if (input.action.kind !== "doc-submit") return readAction(input);
  const scan = localProseSource(input.binding.source) ? scannerSubmit(input) : null;
  if (scan && input.binding.docWriteAllowed === false) { const rejected = scanDetail(input, scan, "rbac_forbidden"); return rejectDocSyncAction(`scan:${scan.baseLedgerSha.headDigest}`, "rbac_forbidden", { ...rejected, unresolvedTouches: scan.rows.map((row) => touch(row.path, "repo-write", "principal lacks repo-write")), nextAction: "use a repo-write principal holding the active execution lease" }, "use a repo-write principal holding the active execution lease"); }
  if (scan && !scan.rows.some((row) => row.state === "eligible")) { const code = scan.rows.map((row) => row.rejectionCode).find((candidate) => candidate === "lease_conflict" || candidate === "deletion_forbidden"), blocked = scanDetail(input, scan, code ?? "preview_blocked"); return scan.rows.some((row) => row.state === "blocked" || row.state === "deletion") ? Array.isArray(input.action.paths) && input.action.paths.length === 0 ? skippedNoOp(input, scan) : rejectDocSyncAction(`scan:${scan.baseLedgerSha.headDigest}`, code ?? "preview_blocked", blocked, blocked.nextAction) : noOp(input, scan); }
  const prepared = scan ? intentFromScan(scan, input.workspaceId) : null, intent = prepared?.intent ?? assignmentIntent(input);
  const receipt = publishDocIntent(input, intent, prepared?.claims ?? intent.changes.map((change) => change.candidate === null ? null : claimBytes(input.rootDir, change.candidate.ref)), scan?.lease ?? (intent.executionId === null ? null : input.projection.currentLeaseForExecution(intent.executionId, input.now())));
  return scan && (receipt.outcome === "applied" || receipt.outcome === "pending") ? scannerSettlement(input, scan, receipt) : receipt;
}

function runDocRetire(input: Input): DocSettlementReceipt {
  if (!hasExactDocSyncActionFields(input.action, ["kind", "path", "reason"])) throw docSyncError("invalid_command", "doc retire requires path and reason");
  const reason = requiredDocSyncText(input.action.reason, "reason").trim(); let target: ReturnType<typeof documentPath>;
  try { target = documentPath(requiredDocSyncText(input.action.path, "path")); } catch { throw docSyncError("invalid_command", "doc retire requires one valid doc-sync path"); }
  if (!directPaths(input.rootDir, [target]) || !resolveDocRoute(target).allowed) throw docSyncError("invalid_command", "doc retire requires one valid doc-sync path");
  const read = input.projection.readDocument(target); if (read.watermark !== read.sourceRevision) throw docSyncError("projection_pending", "retry after the canonical projection catches up"); if (read.document === null) throw docSyncError("document_not_found", `canonical document does not exist: ${target}`);
  const authoredTarget = path.join(resolveHarnessLayout(input.rootDir).authoredRoot, ...target.split("/")); if (existsSync(authoredTarget) && sha256Bytes(readFileSync(authoredTarget)) !== read.document.blobSha256) throw docSyncError("retirement_local_modified", `restore or sync the locally modified document before retiring it: ${target}`);
  const intent = parseDocWriteIntent({ schema: "doc-write-intent/v1", executionId: null, baseLedgerSha: input.store.currentCut(), changes: [{ path: target, baseBlobSha256: read.document.blobSha256, policyId: read.document.policyId, candidate: null }] }, input.workspaceId);
  return publishDocIntent(input, intent, [null], null, reason);
}

export function runArtifactAdd(input: Input): ArtifactAddReceipt { const taskId = requiredDocSyncText(input.action.taskId, "taskId"), sourceValue = requiredDocSyncText(input.action.source, "source"), destinationValue = requiredDocSyncText(input.action.destination, "destination"); if (!hasExactDocSyncActionFields(input.action, ["kind", "taskId", "source", "destination"])) throw docSyncError("invalid_command", "task artifact add requires taskId, source, and destination"); const task = input.projection.read(taskId); if (task.watermark !== task.sourceRevision || !task.packagePath || !task.snapshot.task) throw docSyncError("content_not_ready", `Task ${taskId} is not ready for artifact add`);
  const relativeDestination = destinationValue.startsWith("artifacts/") ? destinationValue : `artifacts/${destinationValue}`; let destination: ReturnType<typeof documentPath>; try { destination = documentPath(`${task.packagePath}/${relativeDestination}`); } catch { throw docSyncError("invalid_artifact_path", "destination must be a UTF-8 textual artifact path under the current task artifacts/ directory"); } const classification = classifyTextualArtifactPath(destination); if (!destination.startsWith(`${task.packagePath}/artifacts/`) || classification === null || !directPaths(input.rootDir, [destination])) throw docSyncError("invalid_artifact_path", "destination must be a UTF-8 textual artifact path under the current task artifacts/ directory"); const layout = resolveHarnessLayout(input.rootDir), ledger = resolveLedgerGitLayout(input.rootDir), source = artifactSource(input, sourceValue), authoredTarget = path.join(layout.authoredRoot, ...destination.split("/")), gitTarget = ledgerGitPath(ledger, destination), projected = input.projection.readDocument(destination), tracked = gitTracked(ledger.rootDir, gitTarget);
  const projectedEdit = projected.document !== null && existsSync(authoredTarget) && sha256Bytes(readFileSync(authoredTarget)) !== projected.document.blobSha256; if (projectedEdit || tracked && gitModified(ledger.rootDir, gitTarget)) throw docSyncError("artifact_tracked_edit", `destination is a tracked edit; use ha doc sync --submit --path ${destination}`); if (tracked || existsSync(authoredTarget) || projected.document !== null) throw docSyncError("artifact_collision", `artifact destination already exists: ${destination}`); if (projected.watermark !== projected.sourceRevision) return { outcome: "indeterminate", opId: `artifact:${input.store.currentCut().headDigest}`, code: "projection_pending", origin: "N/A", nextAction: "retry after the canonical projection catches up" }; const bytes = readFileSync(source.absolute); try { new TextDecoder("utf-8", { fatal: true }).decode(bytes); } catch { throw docSyncError("artifact_invalid_utf8", "artifact source must be valid UTF-8"); } const sha = sha256Bytes(bytes), base = input.store.currentCut(), lease = input.projection.currentLease(taskId, input.now()), intent = parseDocWriteIntent({ schema: "doc-write-intent/v1", executionId: lease?.executionId ?? null, baseLedgerSha: base, changes: [{ path: destination, baseBlobSha256: null, policyId: classification.policyId, candidate: { ref: `doc-sync-claims/${sha}`, sha256: sha, size: bytes.byteLength, mediaType: classification.mediaType } }] }, input.workspaceId), receipt = publishDocIntent(input, intent, [bytes], lease); return receipt.outcome === "applied" || receipt.outcome === "pending" ? { ...receipt, source: source.relative, destination } : receipt;
}
export function archiveRuntimeDispatch(input: Omit<Input, "action"> & { readonly archive: RuntimeDispatchArchive }): DocSettlementReceipt { const value = input.archive, task = input.projection.read(value.taskId); if (task.watermark !== task.sourceRevision || !task.packagePath || !task.snapshot.task) throw docSyncError("content_not_ready", `Task ${value.taskId} is not ready for runtime archive`); const existingMissionRef = runtimeArchiveMissionRef(input, task.packagePath, value), missionRef = existingMissionRef ?? `${task.packagePath}/artifacts/missions/${value.dispatchId}.md`, dispatch = { schema: "runtime-dispatch/v1", dispatchId: value.dispatchId, taskId: value.taskId, executionId: value.executionId, ...(value.agentId ? { agentId: value.agentId, agentName: value.agentName } : {}), ...(value.delegatedByAgentId ? { delegatedByAgentId: value.delegatedByAgentId, delegatedByAgentName: value.delegatedByAgentName, squadId: value.squadId } : {}), instanceId: value.instanceId, model: value.model, reasoningEffort: value.reasoningEffort, cwd: value.cwd, missionRef, runtimeSessionId: value.runtimeSessionId, providerSessionId: value.providerSessionId, startedAt: value.startedAt, endedAt: value.endedAt, outcome: value.outcome, exitCode: value.exitCode, resultRef: value.resultRef, ...(value.eventStreamRef ? { eventStreamRef: value.eventStreamRef } : {}) }, documents = [...(existingMissionRef === null ? [{ path: missionRef, body: runtimeArchiveText(value.prompt), mediaType: "text/markdown" as const }] : []), { path: `${task.packagePath}/artifacts/dispatches/${value.dispatchId}.json`, body: `${JSON.stringify(dispatch, null, 2)}\n`, mediaType: "text/plain" as const }, { path: `${task.packagePath}/artifacts/reports/${value.dispatchId}.md`, body: runtimeArchiveText(value.resultText), mediaType: "text/markdown" as const }].map((document) => ({ ...document, path: documentPath(document.path), bytes: Buffer.from(document.body) })), layout = resolveHarnessLayout(input.rootDir), reads = documents.map((document) => input.projection.readDocument(document.path));
  if (!directPaths(input.rootDir, documents.map(({ path: target }) => target)) || documents.some(({ path: target }) => !resolveDocRoute(target).allowed) || documents.some(({ path: target }, index) => reads[index]!.status !== "ready" || reads[index]!.document !== null || existsSync(path.join(layout.authoredRoot, ...target.split("/"))))) throw docSyncError("runtime_archive_collision", `Runtime archive ${value.dispatchId} is not a fresh task artifact set`); const lease = input.projection.currentLease(value.taskId, input.now()), intent = parseDocWriteIntent({ schema: "doc-write-intent/v1", executionId: lease?.executionId ?? null, baseLedgerSha: input.store.currentCut(), changes: documents.map(({ path: target, bytes, mediaType }) => { const sha = sha256Bytes(bytes); return { path: target, baseBlobSha256: null, policyId: classifyTextualArtifactPath(target)?.policyId ?? DOC_POLICY_ID, candidate: { ref: `doc-sync-claims/${sha}`, sha256: sha, size: bytes.byteLength, mediaType } }; }) }, input.workspaceId); return publishDocIntent({ ...input, action: { kind: "runtime-archive" } }, intent, documents.map(({ bytes }) => bytes), lease);
}
export function publishVerticalScriptChanges(input: Omit<Input, "action">, action: VerticalScriptActionV1, changes: readonly VerticalScriptChangeV1[]): DocSettlementReceipt { const paths = changes.map(({ path: target }) => documentPath(target)); if (!directPaths(input.rootDir, paths) || paths.some((target) => !resolveDocRoute(target).allowed)) throw docSyncError("script_scope_violation", "Script output is outside canonical document routes"); const reads = paths.map((target) => input.projection.readDocument(target)); if (reads.some((read, index) => read.status !== "ready" || (changes[index]!.disposition === "create") !== (read.document === null))) throw docSyncError("script_plan_stale", "Script plan disposition no longer matches the canonical projection"); const bytes = changes.map(({ body }) => Buffer.from(body)), lease = action.taskId === null ? null : input.projection.currentLease(action.taskId, input.now()), intent = parseDocWriteIntent({ schema: "doc-write-intent/v1", executionId: lease?.executionId ?? null, baseLedgerSha: input.store.currentCut(), changes: changes.map((change, index) => ({ path: paths[index], baseBlobSha256: reads[index]!.document?.blobSha256 ?? null, policyId: classifyTextualArtifactPath(paths[index]!)?.policyId ?? DOC_POLICY_ID, candidate: { ref: `doc-sync-claims/${sha256Bytes(bytes[index]!)}`, sha256: sha256Bytes(bytes[index]!), size: bytes[index]!.byteLength, mediaType: change.mediaType } })) }, input.workspaceId); return publishDocIntent({ ...input, action: { kind: "script-run" } }, intent, bytes, lease); }

function publishDocIntent(input: Input, intent: DocWriteIntent, claims: readonly (Uint8Array | null)[], lease: ReturnType<TaskProjection["currentLeaseForExecution"]>, retirementReason?: string): DocSettlementReceipt { const baseRevision = intent.baseLedgerSha.revision, command = retirementReason === undefined ? intent : { ...intent, retirementReason }, envelope = normalizeCommandEnvelope({ workspaceId: input.workspaceId,
    actor: input.binding.actor, source: input.binding.source, expectedRevision: baseRevision ?? 0, command: command as unknown as Readonly<Record<string, unknown>> }), existing = input.store.readEvent(envelope.opId);
  if (existing !== null) { if (!isDocEvent(existing) || !matches(existing, intent, input.binding.actor, input.binding.source, retirementReason)) { recycleClaims(input.rootDir, intent); return rejectDocSyncAction(envelope.opId, "op_conflict", detail(intent, input.store.currentCut(), "op_conflict", null), "query the existing operation before resubmitting"); }
    if (input.projection.readOperation(existing.opId) === null) input.projection.apply(existing, docSyncWritePlan(existing)); const receipt = readDocReceipt(input, existing); recycleClaims(input.rootDir, intent); return receipt; }
  const adjudication = adjudicateDocIntent(input, intent, claims, lease, envelope.opId, retirementReason);
  if (!adjudication.accepted) { if (adjudication.code === "projection_pending") return { outcome: "indeterminate", opId: envelope.opId, receiptId: envelope.opId, code: "projection_pending", origin: "N/A", nextAction: `run ha receipt show ${envelope.opId} after the canonical projection catches up` }; recycleClaims(input.rootDir, intent); return rejectDocSyncAction(envelope.opId, adjudication.code, adjudication.detail, adjudication.detail.nextAction); }
  input.store.append({ event: adjudication.decision.event, plan: adjudication.decision.plan, blobs: adjudication.decision.blobs }); input.projection.apply(adjudication.decision.event, adjudication.decision.plan); postCommit(input, "after_sqlite_commit", envelope.opId); postCommit(input, "before_response_write", envelope.opId);
  const applied = readDocReceipt(input, adjudication.decision.event); postCommit(input, "after_response_write", envelope.opId); recycleClaims(input.rootDir, intent); return applied;
}

// Pure adjudication of one doc write intent against the current canonical
// state: projection readiness, assignment-scope admission, and the domain
// decideDocWrite judgment (lease channel, ledger base, per-path bases, region
// proofs). Both the standalone doc submit and the class-A task bundle consume
// the same verdict, so a carried document set can never pass a weaker check
// than an explicit `ha doc sync` submission.
//
// Task-package documents have exactly ONE fleet entry: the lease-brokered task
// command (design §3 — 绕过自动入口的提交直接拒绝). A fleet doc submit that
// touches a task package without naming the held execution is refused here;
// the local repo-prose channel keeps its pre-start edit flow.
export type DocIntentChannel = "doc-submit" | "task-command";
export type DocIntentAdjudication = { readonly accepted: false; readonly code: string; readonly detail: DocSyncReceiptDetail } | { readonly accepted: true; readonly decision: { readonly event: DocEventV1; readonly plan: ReturnType<typeof docSyncWritePlan>; readonly blobs: readonly { readonly sha256: string; readonly size: number; readonly mediaType: string; readonly body: string }[] } };
export function adjudicateDocIntent(input: Omit<Input, "action"> & { readonly taskDocumentChannel?: DocIntentChannel }, intent: DocWriteIntent, claims: readonly (Uint8Array | null)[], lease: ReturnType<TaskProjection["currentLeaseForExecution"]>, opId: string, retirementReason?: string): DocIntentAdjudication {
  const documents = intent.changes.map((change) => input.projection.readDocument(change.path));
  if (documents.some((read) => read.watermark !== read.sourceRevision)) { const pending = detail(intent, input.store.currentCut(), "projection_pending", lease); return { accepted: false, code: "projection_pending", detail: { ...pending, nextAction: `run ha receipt show ${opId} after the canonical projection catches up` } }; }
  const admission = admissionRejection(input, intent, lease);
  if (admission) return { accepted: false, code: admission.code, detail: admission.detail };
  const decision = decideDocWrite({ intent, opId, eventId: `event-${sha256Bytes(Buffer.from(opId))}`, workspaceRevision: (input.store.readHead()?.revision ?? 0) + 1,
    actor: input.binding.actor, source: input.binding.source, occurredAt: input.now(), currentLedgerSha: input.store.currentCut(), lease, documents: documents.map((read) => read.document), claims, retirementReason,
    resolvedTaskIds: intent.changes.map((change) => input.projection.taskIdForDocumentPath(change.path)) });
  return decision.accepted ? { accepted: true, decision } : { accepted: false, code: decision.code, detail: decision.detail };
}

function readAction(input: Input): WriteReceipt {
  if (input.action.kind !== "doc-show") { const scan = scannerRead(input); return scanReceipt(input, scan); }
  const rawPaths = input.action.kind === "doc-show" ? [input.action.path] : input.action.paths;
  if (!hasExactDocSyncActionFields(input.action, input.action.kind === "doc-show" ? ["kind", "path"] : ["kind", "paths"]) || !Array.isArray(rawPaths) || !rawPaths.length || rawPaths.some((item) => typeof item !== "string")) throw docSyncError("invalid_command", `${input.action.kind} requires valid doc-sync paths`);
  let paths; try { paths = rawPaths.map((item) => documentPath(String(item))); } catch { throw docSyncError("invalid_command", `${input.action.kind} requires valid doc-sync paths`); }
  if (!directPaths(input.rootDir, paths) || paths.some((candidate) => !resolveDocRoute(candidate).allowed)) throw docSyncError("invalid_command", `${input.action.kind} requires valid doc-sync paths`);
  const current = input.store.currentCut(), lease = input.binding.assignmentScope ? input.projection.currentLeaseForExecution(input.binding.assignmentScope.executionId, input.now()) : null;
  const scope = scopeTouches(input, paths); if (scope.length) return rejectDocSyncAction(`read:${input.action.kind}:${current.headDigest}`, "assignment_scope_mismatch", readDetail(input, paths, current, lease, scope), "read only paths in the authenticated assignment scope");
  const reads = paths.map((candidate) => input.projection.readDocument(candidate)), revision = input.store.readHead()?.revision ?? 0, ready = reads.every((read) => read.status === "ready");
  const receiptDetail = readDetail(input, paths, current, lease, []), worktreeVisible = observe(input.rootDir, input.binding.source, reads.map((read) => read.document));
  if (input.action.kind === "doc-show" && ready && reads[0]?.document === null) return rejectDocSyncAction(`read:doc-show:${current.headDigest}`, "document_not_found", receiptDetail, "sync the document before showing it");
  const evidence = input.action.kind === "doc-show" ? reads[0]?.document?.body ?? "document:not-found" : `document-cut:${current.headDigest}`;
  return ready ? { outcome: "applied", opId: `read:${input.action.kind}:${current.headDigest}`, revision, evidence, visibility: "center", proof: proof(revision, revision, true, worktreeVisible), detail: receiptDetail }
    : { outcome: "pending", opId: `read:${input.action.kind}:${current.headDigest}`, revision, evidence, visibility: "center", proof: proof(revision, Math.min(...reads.map((read) => read.watermark)), false, worktreeVisible), detail: receiptDetail, nextAction: receiptDetail.nextAction };
}

export function readDocReceipt(input: Omit<Input, "action">, event: DocEventV1): DocSettlementReceipt {
  const retirement = event.payload.retirementReason === undefined ? null : event.payload.changes[0]!, reads = event.payload.changes.map((change) => input.projection.readDocument(change.path)), canonicalVisible = reads.every((read, index) => { const candidate = event.payload.changes[index]!.candidate; return read.status === "ready" && (candidate === null ? read.document === null : read.document?.blobSha256 === candidate.sha256) && read.watermark >= event.workspaceRevision; }), appliedCut = Math.min(...reads.map((read) => read.watermark)), current = input.store.currentCut(), lease = event.payload.executionId === null ? null : input.projection.currentLeaseForExecution(event.payload.executionId, input.now());
  const receiptDetail: DocSyncReceiptDetail = { kind: "doc_sync", code: canonicalVisible ? retirement === null ? "applied" : "retired" : "projection_pending", baseLedgerSha: event.payload.baseLedgerSha, currentLedgerSha: current,
    paths: event.payload.changes.map((change, index) => ({ path: change.path, baseBlobSha256: change.baseBlobSha256, currentBlobSha256: reads[index]?.document?.blobSha256 ?? null, candidateBlobSha256: change.candidate?.sha256 ?? null })), holder: holder(lease), differences: [], unresolvedTouches: [], deletions: retirement === null ? [] : [{ path: retirement.path, baseBlobSha256: retirement.baseBlobSha256!, source: "intent" }], nextAction: canonicalVisible ? "no action required" : `run ha receipt show ${event.opId} after projection catch-up` };
  const retirementReceipt = retirement === null ? null : { schema: "doc-retirement-receipt/v1", path: retirement.path, baseBlobSha256: retirement.baseBlobSha256, reason: event.payload.retirementReason }, worktreeVisible = retirement === null ? observe(input.rootDir, input.binding.source, reads.map((read) => read.document)) : localProseSource(input.binding.source) ? !existsSync(path.join(resolveHarnessLayout(input.rootDir).authoredRoot, ...retirement.path.split("/"))) : null;
  const common = { opId: event.opId, revision: event.workspaceRevision, evidence: retirementReceipt === null ? `event-object:${event.opId}` : `doc-retirement:${stableStringify(retirementReceipt)}`, visibility: "center" as const, proof: proof(event.workspaceRevision, appliedCut, canonicalVisible, worktreeVisible), detail: receiptDetail };
  const settlement = canonicalVisible ? "applied" as const : "pending" as const, materialized = input.store.publication(event), identity = { commitSha: materialized.commitSha?.sha ?? null, cut: canonicalEventCut(current.repoId, event), settlement, receiptId: event.opId }; return canonicalVisible ? { outcome: "applied", ...common, ...identity } : { outcome: "pending", ...common, ...identity, nextAction: receiptDetail.nextAction };
}

export function readProjectedDocument(projection: TaskProjection, payload: Readonly<Record<string, unknown>>) { const taskId = requiredDocSyncText(payload.taskId, "taskId"), requested = requiredDocSyncText(payload.path, "path"), task = projection.read(taskId); if (!task.packagePath) throw docSyncError("task_not_found", `Task ${taskId} has no projected package path.`); const read = projection.readDocument(documentPath(`${task.packagePath}/${requested}`));
  return { ok: true as const, status: read.status, taskId, path: requested, body: read.document?.body ?? "", blobSha256: read.document?.blobSha256 ?? null, watermark: read.watermark, sourceRevision: read.sourceRevision }; }

/** GUI read repo.tasks.documents.list: projected documents under one task package, paths relative to the package root. */
export function listProjectedTaskDocuments(projection: TaskProjection, payload: Readonly<Record<string, unknown>>): import("./protocol/daemon-protocol.contract.ts").DaemonTaskDocumentListResult { const taskId = requiredDocSyncText(payload.taskId, "taskId"), task = projection.read(taskId); if (!task.packagePath) throw docSyncError("task_not_found", `Task ${taskId} has no projected package path.`);
  const prefix = `${task.packagePath}/`, basis = projection.readReplicaBasis(null), documents = basis.documents.filter((row) => row.path.startsWith(prefix)).map((row) => ({ path: row.path.slice(prefix.length), blobSha256: row.blobSha256, size: row.size, mediaType: row.mediaType })).sort((left, right) => left.path.localeCompare(right.path));
  return { ok: true, status: task.status, taskId, documents, watermark: basis.watermark, sourceRevision: basis.sourceRevision }; }

function assignmentIntent(input: Input): DocWriteIntent {
  try {
    if (!hasExactDocSyncActionFields(input.action, ["kind", "executionId", "baseLedgerSha", "changes"])) throw new Error("assignment doc submit requires staged claim descriptors");
    const intent = parseDocWriteIntent({ schema: "doc-write-intent/v1", executionId: input.action.executionId, baseLedgerSha: input.action.baseLedgerSha, changes: input.action.changes }, input.workspaceId);
    if (!directPaths(input.rootDir, intent.changes.map((change) => change.path))) throw new Error("document path contains a symbolic link"); return intent;
  } catch (error) { throw docSyncError("invalid_command", error instanceof Error ? error.message : String(error)); }
}
function scannerRead(input: Input): DocCandidateScan { if (!hasExactDocSyncActionFields(input.action, ["kind", "paths"]) || !Array.isArray(input.action.paths) || input.action.paths.some((item) => typeof item !== "string")) throw docSyncError("invalid_command", `${input.action.kind} requires authored-root-relative paths`); return scanDocCandidates({ rootDir: input.rootDir, workspaceId: input.workspaceId, store: input.store, projection: input.projection, actor: input.binding.actor, source: input.binding.source, now: input.now(), selection: input.action.paths as string[] }); }
function scannerSubmit(input: Input): DocCandidateScan { const fields = Object.hasOwn(input.action, "executionId") ? ["kind", "executionId", "paths"] : ["kind", "paths"]; if (!hasExactDocSyncActionFields(input.action, fields) || !Array.isArray(input.action.paths) || input.action.paths.some((item) => typeof item !== "string") || input.action.executionId !== undefined && typeof input.action.executionId !== "string") throw docSyncError("invalid_command", "local doc submit requires scanner paths and an optional executionId");
  return scanDocCandidates({ rootDir: input.rootDir, workspaceId: input.workspaceId, store: input.store, projection: input.projection, actor: input.binding.actor, source: input.binding.source, now: input.now(), selection: input.action.paths as string[], ...(typeof input.action.executionId === "string" ? { executionId: input.action.executionId } : {}) }); }
function scanReceipt(input: Input, scan: DocCandidateScan): WriteReceipt { const revision = input.store.readHead()?.revision ?? 0, report = publicScan(scan), opId = `scan:${input.action.kind}:${scan.baseLedgerSha.headDigest}`, detail = scanDetail(input, scan, input.action.kind); return input.action.kind === "doc-dry-run" ? { outcome: "pending", opId, revision, evidence: `doc-scan:${stableStringify(report)}`, visibility: "center", proof: { committedRevision: revision, appliedCut: revision, durable: false, canonicalVisible: false, worktreeVisible: false }, detail, nextAction: detail.nextAction } : { outcome: "applied", opId, revision, evidence: `doc-scan:${stableStringify(report)}`, visibility: "center", proof: proof(revision, revision, true, scan.rows.every((row) => row.state === "clean")), detail }; }
function scanDetail(input: Input, scan: DocCandidateScan, code: string): DocSyncReceiptDetail { const hasConflict = scan.rows.some((row) => row.conflicts.length), deletion = scan.rows.find((row) => row.state === "deletion"); return { kind: "doc_sync", code, baseLedgerSha: scan.baseLedgerSha, currentLedgerSha: input.store.currentCut(), paths: scan.rows.map((row) => ({ path: row.path, baseBlobSha256: row.baseBlobSha256, currentBlobSha256: row.baseBlobSha256, candidateBlobSha256: row.candidateBlobSha256 })), holder: holder(scan.lease), differences: [], unresolvedTouches: scan.rows.filter((row) => row.state === "blocked" || row.state === "conflict").map((row) => touch(row.path, row.state === "conflict" ? "local-conflict-resolution" : row.requiredRoute ?? resolveDocRoute(documentPath(row.path)).requiredRoute, row.state === "conflict" ? `${row.reason}: ${row.conflicts.join(", ")}` : row.reason ?? "candidate is blocked")), deletions: scan.rows.filter((row) => row.state === "deletion" && row.baseBlobSha256).map((row) => ({ path: row.path, baseBlobSha256: row.baseBlobSha256!, source: "intent" as const })), nextAction: hasConflict ? "merge the listed conflict scratch into the canonical file, run ha doc sync --dry-run --path <path> for a fresh base, then save to submit a new opId" : deletion ? `run ha doc retire --path ${deletion.path} --reason "<reason>" for intentional retirement, or restore the document, then run ha doc status` : scan.rows.some((row) => row.state === "blocked") ? "resolve the listed blocked candidates through their requiredRoute, then run ha doc status" : scan.rows.some((row) => row.state === "eligible") ? "submit this selection against the reported automatic base" : scan.rows.some((row) => row.state === "inapplicable") ? "no action required; inapplicable candidates are outside doc sync" : "no action required" }; }
function noOp(input: Input, scan: DocCandidateScan): WriteReceipt { const revision = input.store.readHead()?.revision ?? 0; return { outcome: "applied", opId: `noop:${scan.baseLedgerSha.headDigest}`, revision, evidence: "doc-sync:no-op", visibility: "center", proof: proof(revision, revision, true, true), detail: scanDetail(input, scan, "no_op") }; }
function skippedNoOp(input: Input, scan: DocCandidateScan): DocSettlementReceipt { return { ...noOp(input, scan), summary: submitSummary("applied", [], scan) }; }
function scannerSettlement(input: Input, scan: DocCandidateScan, receipt: DocSettlementReceipt): DocSettlementReceipt { const scanned = scanDetail(input, scan, receipt.outcome), skipped = scanned.unresolvedTouches.length + scanned.deletions.length, detail = receipt.detail && { ...receipt.detail, unresolvedTouches: scanned.unresolvedTouches, deletions: scanned.deletions, nextAction: skipped ? scanned.nextAction : receipt.detail.nextAction }; return { ...receipt, ...(detail ? { detail } : {}), summary: submitSummary(receipt.outcome, receipt.detail?.paths.map((row) => row.path) ?? [], scan) }; }
function submitSummary(outcome: WriteReceipt["outcome"], applied: readonly string[], scan: DocCandidateScan): string { const skipped = scan.rows.filter((row) => row.state === "blocked" || row.state === "deletion" || row.state === "conflict"), inapplicable = scan.rows.filter((row) => row.state === "inapplicable"); return [`doc-submit: ${outcome}`, "applied:", ...(applied.length ? applied : ["(none)"]), "skipped:", ...(skipped.length ? skipped.map((row) => `${row.path}\t${row.state}\t${row.reason ?? "candidate is not eligible"}`) : ["(none)"]), "inapplicable:", ...(inapplicable.length ? inapplicable.map((row) => `${row.path}\t${row.reason}`) : ["(none)"])].join("\n"); }
function admissionRejection(input: Pick<Input, "binding" | "workspaceId" | "store" | "projection"> & { readonly taskDocumentChannel?: DocIntentChannel }, intent: DocWriteIntent, lease: ReturnType<TaskProjection["currentLeaseForExecution"]>): { readonly code: string; readonly detail: DocSyncReceiptDetail } | null {
  if (input.binding.docWriteAllowed === false) { const rejected = detail(intent, input.store.currentCut(), "rbac_forbidden", lease, intent.changes.map((change) => touch(change.path, "repo-write", "principal lacks repo-write")));
    return { code: "rbac_forbidden", detail: { ...rejected, nextAction: "use a repo-write principal holding the active execution lease" } }; }
  // Task-context authority is the dynamically acquired execution lease
  // (decideDocWrite re-checks the holder); the assignment scope gates only
  // which paths a node may touch, so a W3-B lease on any task rides the same
  // path-scoped admission as shared-surface prose. The one exception is the
  // fleet doc-submit channel: task-package documents over fleet ingress must
  // ride the lease-brokered task command (class A); an explicit submit that
  // names the currently held execution keeps decideDocWrite's holder check as
  // its authority, while a channel-less (null execution) submit is refused.
  if ((input.taskDocumentChannel ?? "doc-submit") === "doc-submit" && typeof input.binding.source === "object" && input.binding.source.kind === "assignment") {
    // Fleet assignment ingress treats the whole authored `tasks/<package>/`
    // namespace as class A, including a package that has not projected yet.
    // Relying only on taskIdForDocumentPath would leave a ghost package as an
    // unheld shared-surface write path.
    const taskTouches = intent.changes.filter((change) => intent.executionId === null && (input.projection.taskIdForDocumentPath(change.path) !== null || isTaskPackagePath(change.path)));
    if (taskTouches.length > 0) { const rejected = detail(intent, input.store.currentCut(), "task_docs_require_task_command", lease, taskTouches.map((change) => touch(change.path, "task-command", "task-context documents ride the lease-brokered task command; the doc-submit channel cannot write them without naming the held execution")));
      return { code: "task_docs_require_task_command", detail: { ...rejected, nextAction: "run the task command (it carries its task documents automatically), or submit with the held --execution-id as the current holder" } }; }
  }
  const touches = scopeTouches(input, intent.changes.map((change) => change.path)); if (!touches.length) return null;
  const rejected = detail(intent, input.store.currentCut(), "assignment_scope_mismatch", lease, touches); return { code: "assignment_scope_mismatch", detail: { ...rejected, nextAction: "submit only paths in the authenticated assignment scope" } };
}
function scopeTouches(input: Pick<Input, "binding" | "workspaceId">, paths: readonly string[]) { if (localProseSource(input.binding.source)) return [];
  const scope = input.binding.assignmentScope, assignmentId = typeof input.binding.source === "object" && input.binding.source.kind === "assignment" ? input.binding.source.assignmentId : "remote-direct", route = `assignment:${assignmentId}:${scope?.paths.join(",") ?? "scope-missing"}`;
  return paths.filter((candidate) => !scope || scope.repoId !== input.workspaceId || !scope.paths.some((allowed) => candidate === allowed || candidate.startsWith(`${allowed}/`))).map((candidate) => touch(candidate, route, "path is outside the authenticated assignment scope")); }
function readDetail(input: Input, paths: readonly string[], current: LedgerCutIdentity, lease: ReturnType<TaskProjection["currentLeaseForExecution"]>, unresolvedTouches: DocSyncReceiptDetail["unresolvedTouches"]): DocSyncReceiptDetail { const reads = paths.map((candidate) => input.projection.readDocument(candidate));
  return { kind: "doc_sync", code: unresolvedTouches.length ? "assignment_scope_mismatch" : input.action.kind, baseLedgerSha: current, currentLedgerSha: current,
    paths: reads.map((read, index) => ({ path: paths[index]!, baseBlobSha256: read.document?.blobSha256 ?? null, currentBlobSha256: read.document?.blobSha256 ?? null, candidateBlobSha256: null })), holder: holder(lease), differences: [], unresolvedTouches, deletions: [], nextAction: reads.every((read) => read.status === "ready") ? "submit against this base cut" : "retry after projection catch-up" }; }
function detail(intent: DocWriteIntent, current: LedgerCutIdentity, code: string, lease: ReturnType<TaskProjection["currentLeaseForExecution"]>, unresolvedTouches: DocSyncReceiptDetail["unresolvedTouches"] = []): DocSyncReceiptDetail { return { kind: "doc_sync", code,
  baseLedgerSha: intent.baseLedgerSha, currentLedgerSha: current, paths: intent.changes.map((change) => ({ path: change.path, baseBlobSha256: change.baseBlobSha256, currentBlobSha256: null, candidateBlobSha256: change.candidate?.sha256 ?? null })), holder: holder(lease), differences: [], unresolvedTouches, deletions: [], nextAction: "run ha doc status, then ha doc sync --dry-run --path <path> and resubmit with a new opId" }; }
function touch(pathValue: string, requiredRoute: string, reason: string): DocSyncReceiptDetail["unresolvedTouches"][number] { return { path: pathValue, regionId: null, anchor: null, reason, requiredRoute, policy: DOC_POLICY_ID }; }
function isTaskPackagePath(value: string): boolean { const parts = value.split("/"); return parts.length >= 3 && parts[0] === "tasks" && parts[1]!.length > 0; }
function holder(lease: ReturnType<TaskProjection["currentLeaseForExecution"]>): DocSyncReceiptDetail["holder"] { return lease && { taskId: lease.taskId, executionId: lease.executionId, personId: lease.actor.principal.personId, executorId: lease.actor.executor?.id ?? null, source: lease.source, expiresAt: lease.expiresAt, version: lease.version }; }
export function claimBytes(rootDir: string, ref: DocClaimRef): Uint8Array | null { const target = claimFile(rootDir, ref); return target && lstatSync(target).isFile() ? readFileSync(target) : null; }
function claimFile(rootDir: string, ref: string): string | null { let target = resolveHarnessLayout(rootDir).localRoot; if (existsSync(target) && lstatSync(target).isSymbolicLink()) return null;
  for (const segment of ref.split("/")) { target = path.join(target, segment); if (!existsSync(target) || lstatSync(target).isSymbolicLink()) return null; } return target; }
export function recycleClaims(rootDir: string, intent: DocWriteIntent): void { for (const change of intent.changes) { const target = change.candidate && claimFile(rootDir, change.candidate.ref); if (target) unlinkSync(target); } }
function directPaths(rootDir: string, paths: readonly string[]): boolean { const authored = resolveHarnessLayout(rootDir).authoredRoot; if (existsSync(authored) && lstatSync(authored).isSymbolicLink()) return false;
  return paths.every((document) => { let target = authored; for (const segment of document.split("/")) { target = path.join(target, segment); if (existsSync(target) && lstatSync(target).isSymbolicLink()) return false; } return true; }); }
function observe(rootDir: string, source: WriteSource, documents: readonly ({ readonly path: string; readonly blobSha256: string } | null)[]): boolean | null { if (!localProseSource(source) || documents.some((document) => document === null)) return null;
  const authored = resolveHarnessLayout(rootDir).authoredRoot; return documents.every((document) => { const target = path.join(authored, document!.path); return existsSync(target) && sha256Bytes(readFileSync(target)) === document!.blobSha256; }); }
function matches(event: DocEventV1, intent: DocWriteIntent, actor: ActorIdentity, source: WriteSource, retirementReason?: string): boolean { return event.payload.executionId === intent.executionId && event.payload.retirementReason === retirementReason && stableStringify(event.payload.baseLedgerSha) === stableStringify(intent.baseLedgerSha) && stableStringify(event.actor) === stableStringify(actor) && stableStringify(event.source) === stableStringify(source) && stableStringify(event.payload.changes.map((change) => ({ path: change.path, baseBlobSha256: change.baseBlobSha256, policyId: change.policyId, candidate: change.candidate }))) === stableStringify(intent.changes.map((change) => ({ path: change.path, baseBlobSha256: change.baseBlobSha256, policyId: change.policyId, candidate: change.candidate && { sha256: change.candidate.sha256, size: change.candidate.size, mediaType: change.candidate.mediaType } }))); }
function localProseSource(source: WriteSource): boolean { return source === "local"; }
function runtimeArchiveText(value: string): string { return value.replace(/\r\n?/gu, "\n"); }
function runtimeArchiveMissionRef(input: Omit<Input, "action">, packagePath: string, archive: RuntimeDispatchArchive): string | null { if (!archive.promptSource) return null; const authored = resolveHarnessLayout(input.rootDir).authoredRoot, absolute = path.resolve(input.rootDir, archive.promptSource), relative = path.relative(authored, absolute).split(path.sep).join("/"); if (!relative.startsWith(`${packagePath}/artifacts/`)) return null; let candidate; try { candidate = documentPath(relative); } catch (error) { consumeKnownError(error); return null; } const read = input.projection.readDocument(candidate); return read.status === "ready" && read.document?.body === runtimeArchiveText(archive.prompt) ? candidate : null; }
function artifactSource(input: Pick<Input, "rootDir" | "projection">, value: string): { readonly absolute: string; readonly relative: string } { const root = realpathSync.native(input.rootDir), candidate = path.resolve(input.rootDir, value); let absolute: string; try { absolute = realpathSync.native(candidate); } catch { throw docSyncError("artifact_source_missing", "artifact source must be an existing untracked regular file"); } if (!(absolute.startsWith(`${root}${path.sep}`)) || lstatSync(candidate).isSymbolicLink() || !lstatSync(candidate).isFile()) throw docSyncError("artifact_source_invalid", "artifact source must be a direct regular file inside the repository"); const relative = path.relative(root, absolute).split(path.sep).join("/"), authoredRoot = realpathSync.native(resolveHarnessLayout(input.rootDir).authoredRoot), authoredRelative = path.relative(authoredRoot, absolute).split(path.sep).join("/"), projected = !authoredRelative.startsWith("../") && !path.isAbsolute(authoredRelative) ? input.projection.readDocument(authoredRelative).document : null; if (projected !== null || gitTracked(input.rootDir, relative)) throw docSyncError("artifact_source_tracked", "artifact source must be untracked; use ha doc sync for tracked edits"); return { absolute, relative }; }
function gitTracked(rootDir: string, target: string): boolean { try { execFileSync("git", ["-C", rootDir, "ls-files", "--error-unmatch", "--", target], { stdio: "ignore", windowsHide: true }); return true; } catch { return false; } }
function gitModified(rootDir: string, target: string): boolean { try { execFileSync("git", ["-C", rootDir, "diff", "--quiet", "HEAD", "--", target], { stdio: "ignore", windowsHide: true }); return false; } catch (error) { consumeKnownError(error); return true; } }
function postCommit(input: Pick<Input, "killpoint">, point: EventPublicationKillpoint, opId: string): void { try { input.killpoint?.(point); } catch (cause) { const error = docSyncError("publication_indeterminate", `publication result is unknown; run ha receipt show ${opId} before retrying`) as Error & { opId: string; cause?: unknown }; error.opId = opId; error.cause = cause; throw error; } }
function proof(committedRevision: number, appliedCut: number, canonicalVisible: boolean, worktreeVisible: boolean | null) { return { committedRevision, appliedCut, durable: true, canonicalVisible, worktreeVisible }; }
export function rejectDocSyncAction(opId: string, code: string, receiptDetail: DocSyncReceiptDetail, nextAction: string): WriteReceipt { return { outcome: "op_rejected", opId, code, origin: "doc-sync-contract", evidence: `contract-rejection:${code}`, nextAction, detail: receiptDetail }; }
function requiredDocSyncText(value: unknown, name: string): string { if (typeof value === "string" && value.trim()) return value; throw docSyncError("invalid_command", `${name} is required`); }
function hasExactDocSyncActionFields(value: Action, fields: readonly string[]): boolean { return Object.keys(value).length === fields.length && fields.every((field) => Object.hasOwn(value, field)); }
function docSyncError(code: string, message: string): Error { const error = new Error(message) as Error & { code: string }; error.code = code; return error; }
