import { existsSync, readFileSync } from "node:fs";
import path from "node:path";
import { decideDocWrite, isDocEvent, normalizeCommandEnvelope, resolveDocRoute, resolveHarnessLayout, sha256Bytes, stableStringify, validateDocWriteIntent,
  type ActorIdentity, type DocEventV1, type DocSyncReceiptDetail, type DocWriteIntent, type EventPublicationKillpoint, type WriteReceipt, type WriteSource } from "../../kernel/src/index.ts";
import type { CanonicalEventStore, TaskProjection } from "../../kernel/src/index.ts";
type Action = Readonly<Record<string, unknown>> & { readonly kind: string };
export function isDocAction(kind: string): boolean { return kind === "doc-status" || kind === "doc-submit"; }
export async function runDocAction(input: { readonly action: Action; readonly binding: { readonly actor: ActorIdentity; readonly source: WriteSource }; readonly workspaceId: string; readonly rootDir: string; readonly store: CanonicalEventStore; readonly projection: TaskProjection; readonly now: () => string; readonly killpoint?: (point: EventPublicationKillpoint) => void }): Promise<WriteReceipt> {
  if (input.action.kind === "doc-status") return status(input, strings(input.action.paths));
  const intent = intentFrom(input.action), issues = validateDocWriteIntent(intent); if (issues.length) throw coded("invalid_command", issues.join("; "));
  const baseRevision = input.store.revisionAt(intent.baseLedgerSha), envelope = normalizeCommandEnvelope({ workspaceId: input.workspaceId, actor: input.binding.actor, source: input.binding.source, expectedRevision: baseRevision ?? 0, command: intent as unknown as Readonly<Record<string, unknown>> }), existing = input.store.readEvent(envelope.opId);
  if (existing !== null) { if (!isDocEvent(existing) || !matches(existing, intent, input.binding.actor, input.binding.source)) return reject(envelope.opId, "op_conflict", emptyDetail(intent, input.store.currentCommit(), "op_conflict", null), "query the existing operation before resubmitting"); if (input.projection.readOperation(existing.opId) === null) input.projection.apply(existing); return readDocReceipt(input, existing); }
  const documents = intent.changes.map((change) => input.projection.readDocument(change.path)); if (documents.some((read) => read.status !== "ready")) return { outcome: "indeterminate", opId: envelope.opId, code: "projection_pending", origin: "N/A", nextAction: "retry after the canonical projection catches up" };
  const lease = input.projection.currentLeaseForExecution(intent.executionId, input.now()), claims = intent.changes.map((change) => change.candidate === null ? null : claimBytes(input.rootDir, change.candidate.ref));
  const decision = decideDocWrite({ intent, opId: envelope.opId, eventId: `event-${sha256Bytes(Buffer.from(envelope.opId))}`, workspaceRevision: (input.store.readHead()?.revision ?? 0) + 1,
    actor: input.binding.actor, source: input.binding.source, occurredAt: input.now(), currentLedgerSha: input.store.currentCommit(), lease, documents: documents.map((read) => read.document), claims });
  if (!decision.accepted) return reject(envelope.opId, decision.code, decision.detail, decision.detail.nextAction);
  input.store.append(decision.event, decision.blobs); input.projection.apply(decision.event); input.killpoint?.("after_sqlite_commit"); input.killpoint?.("before_response_write");
  const applied = readDocReceipt(input, decision.event); input.killpoint?.("after_response_write"); return applied;
}
function status(input: Parameters<typeof runDocAction>[0], paths: readonly string[]): WriteReceipt { if (!paths.length || paths.some((documentPath) => !resolveDocRoute(documentPath).allowed)) throw coded("invalid_command", "doc-status requires valid doc-sync paths"); const reads = paths.map((documentPath) => input.projection.readDocument(documentPath)), revision = input.store.readHead()?.revision ?? 0, current = input.store.currentCommit(), ready = reads.every((read) => read.status === "ready");
  const detail: DocSyncReceiptDetail = { kind: "doc_sync", code: "status", baseLedgerSha: current, currentLedgerSha: current, paths: reads.map((read, index) => ({ path: paths[index]!, baseBlobSha256: read.document?.blobSha256 ?? null, currentBlobSha256: read.document?.blobSha256 ?? null, candidateBlobSha256: null })), holder: null, differences: [], unresolvedTouches: [], deletions: [], nextAction: ready ? "submit against this base cut" : "retry status after projection catch-up" };
  const worktreeVisible = observe(input.rootDir, input.binding.source, reads.map((read) => read.document)); return ready ? { outcome: "applied", opId: `read:doc-status:${current}`, revision, evidence: `document-cut:${current}`, visibility: "center", proof: proof(revision, revision, true, worktreeVisible), detail }
    : { outcome: "pending", opId: `read:doc-status:${current}`, revision, evidence: `document-cut:${current}`, visibility: "center", proof: proof(revision, Math.min(...reads.map((read) => read.watermark)), false, worktreeVisible), detail, nextAction: detail.nextAction };
}
export function readDocReceipt(input: Omit<Parameters<typeof runDocAction>[0], "action">, event: DocEventV1): WriteReceipt { const reads = event.payload.changes.map((change) => input.projection.readDocument(change.path)), canonicalVisible = reads.every((read, index) => read.status === "ready" && read.document?.blobSha256 === event.payload.changes[index]!.candidate.sha256 && read.watermark >= event.workspaceRevision), appliedCut = Math.min(...reads.map((read) => read.watermark)), current = input.store.currentCommit(), lease = input.projection.currentLeaseForExecution(event.payload.executionId, input.now());
  const detail: DocSyncReceiptDetail = { kind: "doc_sync", code: canonicalVisible ? "applied" : "projection_pending", baseLedgerSha: event.payload.baseLedgerSha, currentLedgerSha: current, paths: event.payload.changes.map((change, index) => ({ path: change.path, baseBlobSha256: change.baseBlobSha256, currentBlobSha256: reads[index]?.document?.blobSha256 ?? null, candidateBlobSha256: change.candidate.sha256 })), holder: holder(lease), differences: [], unresolvedTouches: [], deletions: [], nextAction: canonicalVisible ? "no action required" : "retry receipt show after projection catch-up" };
  const common = { opId: event.opId, revision: event.workspaceRevision, evidence: `event-object:${event.opId}`, visibility: "center" as const, proof: proof(event.workspaceRevision, appliedCut, canonicalVisible, observe(input.rootDir, input.binding.source, reads.map((read) => read.document))), detail };
  return canonicalVisible ? { outcome: "applied", ...common } : { outcome: "pending", ...common, nextAction: detail.nextAction };
}
function intentFrom(action: Action): DocWriteIntent { return { schema: "doc-write-intent/v1", executionId: String(action.executionId ?? ""), baseLedgerSha: String(action.baseLedgerSha ?? ""), changes: Array.isArray(action.changes) ? action.changes as DocWriteIntent["changes"] : [] }; }
function claimBytes(rootDir: string, ref: string): Uint8Array | null { if (!/^doc-sync-claims\/[A-Za-z0-9._/-]+$/u.test(ref) || ref.split("/").includes("..")) return null; const localRoot = resolveHarnessLayout(rootDir).localRoot, target = path.resolve(localRoot, ref); return target.startsWith(`${path.resolve(localRoot)}${path.sep}`) && existsSync(target) ? readFileSync(target) : null; }
function observe(rootDir: string, source: WriteSource, documents: readonly ({ readonly path: string; readonly blobSha256: string } | null)[]): boolean | null { if (source !== "local" || documents.some((document) => document === null)) return null; const authored = resolveHarnessLayout(rootDir).authoredRoot; return documents.every((document) => { const target = path.join(authored, document!.path); return existsSync(target) && sha256Bytes(readFileSync(target)) === document!.blobSha256; }); }
function matches(event: DocEventV1, intent: DocWriteIntent, actor: ActorIdentity, source: WriteSource): boolean { return event.payload.executionId === intent.executionId && event.payload.baseLedgerSha === intent.baseLedgerSha && stableStringify(event.actor) === stableStringify(actor) && stableStringify(event.source) === stableStringify(source) && stableStringify(event.payload.changes.map((change) => ({ path: change.path, baseBlobSha256: change.baseBlobSha256, policyId: change.policyId, candidate: change.candidate }))) === stableStringify(intent.changes.map((change) => ({ path: change.path, baseBlobSha256: change.baseBlobSha256, policyId: change.policyId, candidate: change.candidate && { sha256: change.candidate.sha256, size: change.candidate.size, mediaType: change.candidate.mediaType } }))); }
function emptyDetail(intent: DocWriteIntent, current: string, code: string, lease: ReturnType<TaskProjection["currentLeaseForExecution"]>): DocSyncReceiptDetail { return { kind: "doc_sync", code, baseLedgerSha: /^[0-9a-f]{40}$/u.test(intent.baseLedgerSha) ? intent.baseLedgerSha : current, currentLedgerSha: current, paths: intent.changes.map((change) => ({ path: change.path, baseBlobSha256: change.baseBlobSha256, currentBlobSha256: null, candidateBlobSha256: change.candidate?.sha256 ?? null })), holder: holder(lease), differences: [], unresolvedTouches: [], deletions: [], nextAction: "refresh status and resubmit with a new opId" }; }
function holder(lease: ReturnType<TaskProjection["currentLeaseForExecution"]>): DocSyncReceiptDetail["holder"] { return lease && { taskId: lease.taskId, executionId: lease.executionId, personId: lease.actor.principal.personId, executorId: lease.actor.executor?.id ?? null, source: lease.source, expiresAt: lease.expiresAt, version: lease.version }; }
function proof(committedRevision: number, appliedCut: number, canonicalVisible: boolean, worktreeVisible: boolean | null) { return { committedRevision, appliedCut, durable: true, canonicalVisible, worktreeVisible }; }
function reject(opId: string, code: string, detail: DocSyncReceiptDetail, nextAction: string): WriteReceipt { return { outcome: "rejected", opId, code, origin: "doc-sync-contract", evidence: `contract-rejection:${code}`, nextAction, detail }; }
function strings(value: unknown): readonly string[] { return Array.isArray(value) && value.every((item) => typeof item === "string") ? value : []; }
function coded(code: string, message: string): Error { const error = new Error(message) as Error & { code: string }; error.code = code; return error; }
