import { createHash } from "node:crypto";
import { makeDecisionService, makeFactService } from "../../application/src/index.ts";
import { deriveRelationId, factMemoryTags, type ActorIdentity, type CanonicalEventStore, type DecisionEventV1, type EventPublicationKillpoint, type FactConfidence, type FactEventV1, type FactMemoryClass, type TaskProjection, type WriteReceipt, type WriteSource } from "../../kernel/src/index.ts";

interface Binding { readonly actor: ActorIdentity; readonly source: WriteSource }
export function makeFactActions(input: { readonly store: CanonicalEventStore; readonly projection: TaskProjection; readonly now: () => string; readonly killpoint?: (point: EventPublicationKillpoint) => void }) {
  const service = makeFactService({ eventStore: input.store, projection: input.projection });
  const run = (action: Readonly<Record<string, unknown>> & { readonly kind: string }, binding: Binding, opId: string): WriteReceipt => {
    if (action.kind === "fact-search") return readReceipt("fact-search", service.search(filters(action)));
    if (action.kind === "fact-show") return readReceipt("fact-show", service.show(required(action.taskId, "taskId"), required(action.factId, "factId")));
    if (action.kind !== "fact-record") throw coded("unsupported_command", "Use fact record, search, or show.");
    const existing = input.store.readEvent(opId), occurredAt = existing?.occurredAt ?? input.now();
    const event = existing?.schema === "fact-event/v1" ? existing : factEvent(action, binding, opId, occurredAt, (input.store.readHead()?.revision ?? 0) + 1);
    const result = service.record(event); input.killpoint?.("after_sqlite_commit"); input.killpoint?.("before_response_write"); input.killpoint?.("after_response_write");
    return { outcome: "applied", opId, revision: result.revision, evidence: JSON.stringify(result.fact), visibility: "center", proof: { committedRevision: result.revision, appliedCut: result.watermark, durable: true, canonicalVisible: true, worktreeVisible: null } };
  };
  return Object.freeze({ run });
}
export function makeDecisionActions(input: { readonly store: CanonicalEventStore; readonly projection: TaskProjection; readonly now: () => string; readonly killpoint?: (point: EventPublicationKillpoint) => void }) {
  const service = makeDecisionService({ eventStore: input.store, projection: input.projection }), facts = makeFactService({ eventStore: input.store, projection: input.projection });
  const run = (action: Readonly<Record<string, unknown>> & { readonly kind: string }, binding: Binding & { readonly roles?: readonly string[] }, opId: string): WriteReceipt => {
    if (action.kind === "decision-search") return readReceipt("decision-search", service.search(decisionFilters(action)));
    if (action.kind === "decision-show") { const read = service.show(required(action.decisionId, "decisionId")), shown = { ...read, decision: { ...read.decision, body: action.includeBody === true ? read.decision.body : null } }; return readReceipt("decision-show", shown); }
    if (action.kind === "decision-reckon") { const graph = service.graph(), id = required(action.decisionId, "decisionId"), rows = graph.coverageRows.filter((row) => row.decisionRef === `decision/${id}`), basisRevision = graph.watermark, occurredAt = input.now(), event = reckonFact(action, binding, opId, occurredAt, (input.store.readHead()?.revision ?? 0) + 1, rows, basisRevision), result = facts.record(event); return applied(opId, result.revision, result.watermark, result.fact); }
    if (["decision-accept", "decision-reject", "decision-defer"].includes(action.kind) && !binding.roles?.includes("$arbiter")) throw coded("actor_unauthorized", "Decision outcome requires a transport-bound $arbiter.");
    const existing = input.store.readEvent(opId), occurredAt = existing?.occurredAt ?? input.now(), event = existing?.schema === "decision-event/v1" ? existing : decisionEvent(action, binding, opId, occurredAt, (input.store.readHead()?.revision ?? 0) + 1), result = service.record(event); input.killpoint?.("after_sqlite_commit"); input.killpoint?.("before_response_write"); input.killpoint?.("after_response_write"); return applied(opId, result.revision, result.watermark, result.decision);
  };
  return Object.freeze({ run });
}
function decisionEvent(action: Readonly<Record<string, unknown>>, binding: Binding, opId: string, occurredAt: string, workspaceRevision: number): DecisionEventV1 {
  const decisionId = action.kind === "decision-propose" ? `dec_${createHash("sha256").update(opId).digest("hex").slice(0, 26).toUpperCase()}` : required(action.decisionId, "decisionId"), base = { schema: "decision-event/v1" as const, eventId: `event-${createHash("sha256").update(opId).digest("hex")}`, workspaceRevision, opId, decisionId, actor: binding.actor, source: binding.source, occurredAt };
  if (action.kind === "decision-propose") return { ...base, type: "decision_proposed", payload: { title: required(action.title, "title"), question: required(action.question, "question"), riskTier: choice(action.riskTier, ["low", "medium", "high"], "riskTier"), urgency: choice(action.urgency, ["low", "medium", "high"], "urgency"), vertical: required(action.vertical, "vertical"), preset: required(action.preset, "preset"), appliesTo: object(action.appliesTo, "appliesTo") as never, decisionClass: choice(action.decisionClass, ["ordinary", "standing_policy"], "decisionClass"), chosen: array(action.chosen, "chosen") as never, rejected: array(action.rejected, "rejected") as never } };
  if (action.kind === "decision-accept") return { ...base, type: "decision_accepted", payload: { rationale: required(action.rationale, "rationale") } };
  if (action.kind === "decision-reject") return { ...base, type: "decision_rejected", payload: { reason: required(action.reason, "reason") } };
  if (action.kind === "decision-defer") return { ...base, type: "decision_deferred", payload: { reason: required(action.reason, "reason") } };
  if (action.kind === "decision-retire") return { ...base, type: "decision_retired", payload: { reason: required(action.reason, "reason") } };
  if (action.kind === "decision-claim-add") return { ...base, type: "decision_claim_declared", payload: { claimId: required(action.claimId, "claimId"), text: required(action.text, "text"), loadBearing: action.loadBearing !== false } };
  if (action.kind === "decision-claim-fulfill") return { ...base, type: "decision_claim_fulfillment_declared", payload: { claimId: required(action.claimId, "claimId"), mode: choice(action.mode, ["evidenced", "delivered", "standing_policy"], "mode") } };
  if (action.kind === "decision-relate") { const source = action.anchor ? `decision/${decisionId}/${required(action.anchor, "anchor")}` : `decision/${decisionId}`, identity = { source, target: required(action.target, "target"), type: required(action.relationType, "relationType") as never, direction: "directed" as const }; return { ...base, type: "decision_related", payload: { relation: { relation_id: deriveRelationId(identity), ...identity, strength: "strong", origin: "declared", rationale: required(action.rationale, "rationale"), state: "active" } } }; }
  if (action.kind === "decision-relation-retire") return { ...base, type: "decision_relation_retired", payload: { relationId: required(action.relationId, "relationId"), reason: required(action.reason, "reason") } };
  throw coded("invalid_command", "Use a canonical Decision command.");
}
function reckonFact(action: Readonly<Record<string, unknown>>, binding: Binding, opId: string, occurredAt: string, workspaceRevision: number, rows: readonly { readonly claimRef: string; readonly status: string; readonly basisRevision: number }[], basisRevision: number): FactEventV1 { const decisionId = required(action.decisionId, "decisionId"), taskId = required(action.taskId, "taskId"), report = rows.map((row) => `${row.claimRef}=${row.status}`).join(", ") || "no load-bearing claims"; return { schema: "fact-event/v1", eventId: `event-${createHash("sha256").update(opId).digest("hex")}`, workspaceRevision, opId, taskId, factId: `F-${createHash("sha256").update(opId).digest("hex").slice(0, 8).toUpperCase()}`, type: "fact_recorded", actor: binding.actor, source: binding.source, occurredAt, payload: { statement: `Decision ${decisionId} coverage at basisRevision ${basisRevision}: ${report}.`, evidenceSource: `decision/${decisionId}@${basisRevision}`, observedAt: occurredAt, confidence: "high", memoryClass: "semantic", memoryTags: ["abstract_rule"], provenance: [{ runtime: runtime(binding), sessionId: typeof binding.source === "object" ? binding.source.assignmentId : `transport:${binding.actor.principal.personId}`, boundAt: occurredAt }] } }; }
function applied(opId: string, revision: number, watermark: number, evidence: unknown): WriteReceipt { return { outcome: "applied", opId, revision, evidence: JSON.stringify(evidence), visibility: "center", proof: { committedRevision: revision, appliedCut: watermark, durable: true, canonicalVisible: true, worktreeVisible: null } }; }
function decisionFilters(action: Readonly<Record<string, unknown>>) { return { ...(typeof action.query === "string" ? { query: action.query } : {}), ...(typeof action.state === "string" ? { state: action.state as never } : {}), ...(typeof action.riskTier === "string" ? { riskTier: action.riskTier as never } : {}), ...(typeof action.vertical === "string" ? { vertical: action.vertical } : {}) }; }
function factEvent(action: Readonly<Record<string, unknown>>, binding: Binding, opId: string, occurredAt: string, workspaceRevision: number): FactEventV1 {
  const confidence = action.confidence as FactConfidence, memoryClass = action.memoryClass as FactMemoryClass, memoryTags = strings(action.memoryTags);
  if (!(["low", "medium", "high"] as const).includes(confidence) || !(["semantic", "episodic", "procedural"] as const).includes(memoryClass)
    || memoryTags.some((tag) => !factMemoryTags.includes(tag as never))) throw coded("invalid_command", "Fact classification is invalid.");
  const runtime = binding.actor.executor && (["claude-code", "codex", "zcode", "antigravity"] as const).includes(binding.actor.executor.id as never) ? binding.actor.executor.id as "claude-code" | "codex" | "zcode" | "antigravity" : "human";
  return { schema: "fact-event/v1", eventId: `event-${createHash("sha256").update(opId).digest("hex")}`, workspaceRevision, opId, taskId: required(action.taskId, "taskId"),
    factId: `F-${createHash("sha256").update(opId).digest("hex").slice(0, 8).toUpperCase()}`, type: "fact_recorded", actor: binding.actor, source: binding.source, occurredAt,
    payload: { statement: required(action.statement, "statement"), evidenceSource: required(action.evidenceSource, "evidenceSource"), observedAt: typeof action.observedAt === "string" ? action.observedAt : occurredAt,
      confidence, memoryClass, memoryTags: memoryTags as FactEventV1["payload"]["memoryTags"], provenance: [{ runtime, sessionId: typeof binding.source === "object" ? binding.source.assignmentId : `transport:${binding.actor.principal.personId}`, boundAt: occurredAt }],
      ...(action.supersedes && typeof action.supersedes === "object" ? { supersedes: action.supersedes as { readonly factRef: string; readonly rationale: string } } : {}) } };
}
function filters(action: Readonly<Record<string, unknown>>) { return { ...(typeof action.query === "string" ? { query: action.query } : {}), ...(typeof action.taskId === "string" ? { taskId: action.taskId } : {}), ...(typeof action.confidence === "string" ? { confidence: action.confidence as FactConfidence } : {}), ...(typeof action.memoryClass === "string" ? { memoryClass: action.memoryClass as FactMemoryClass } : {}) }; }
function readReceipt(command: string, read: { readonly status: "ready" | "pending"; readonly watermark: number; readonly sourceRevision: number }): WriteReceipt { const base = { opId: `read:${command}`, revision: read.sourceRevision, evidence: JSON.stringify(read), visibility: "center" as const, proof: { committedRevision: read.sourceRevision, appliedCut: read.watermark, durable: true, canonicalVisible: read.status === "ready", worktreeVisible: null } }; return read.status === "ready" ? { outcome: "applied", ...base } : { outcome: "pending", ...base, nextAction: `Retry ${command} after projection catch-up.` }; }
function required(value: unknown, field: string): string { if (typeof value === "string" && value.trim()) return value; throw coded("invalid_command", `${field} is required.`); }
function strings(value: unknown): readonly string[] { return Array.isArray(value) && value.every((item) => typeof item === "string") ? value : []; }
function array(value: unknown, field: string): readonly unknown[] { if (Array.isArray(value) && value.length) return value; throw coded("invalid_command", `${field} must be a non-empty array.`); } function object(value: unknown, field: string): Readonly<Record<string, unknown>> { if (value && typeof value === "object" && !Array.isArray(value)) return value as Readonly<Record<string, unknown>>; throw coded("invalid_command", `${field} must be an object.`); } function choice<T extends string>(value: unknown, choices: readonly T[], field: string): T { if (typeof value === "string" && choices.includes(value as T)) return value as T; throw coded("invalid_command", `${field} is invalid.`); } function runtime(binding: Binding): "human" | "claude-code" | "codex" | "zcode" | "antigravity" { const id = binding.actor.executor?.id; return id && ["claude-code", "codex", "zcode", "antigravity"].includes(id) ? id as never : "human"; }
function coded(code: string, message: string): Error { const error = new Error(message) as Error & { code: string }; error.code = code; return error; }
