import { createHash } from "node:crypto";
import { localAdapterProviderMetadata } from "../../adapters/local/src/index.ts";
import { multicaAdapterProviderMetadata } from "../../adapters/multica/src/index.ts";
import { runPresetAction } from "../../preset/src/index.ts";
import { presetRuntimeDefaults } from "../../preset/src/preset-system.ts";
import { writeCatalogPreset, writeCatalogRereadReceipt, writeCatalogSnapshot, type CatalogRereadReceipt } from "./gui-s3-control.ts";
import type { JsonObject } from "./protocol/json-rpc-types.ts";

type PresetEntry = { readonly id: string; readonly title: string; readonly description: string; readonly verticalId: string; readonly layer: "bundled" | "user"; readonly validity: "valid" | "unavailable" | "blocked"; readonly version?: string; readonly kind?: string; readonly defaultProfile?: string; readonly entrypoints?: readonly string[]; readonly issues: readonly JsonObject[]; readonly shadows?: { readonly layer: "bundled"; readonly title: string } };
export function openGuiCatalog(input: { readonly repoId: string; readonly rootDir: string; readonly now?: () => string }) {
  const now = input.now ?? (() => new Date().toISOString()); let lastDigest: string | null = null;
  const snapshot = async () => { const defaults = presetRuntimeDefaults(input.rootDir), presets = await runPresetAction({ rootDir: input.rootDir, action: { kind: "preset-list", verticalId: defaults.verticalId } }) as readonly PresetEntry[], vertical = await runPresetAction({ rootDir: input.rootDir, action: { kind: "vertical-validate" } }) as JsonObject, templates = await runPresetAction({ rootDir: input.rootDir, action: { kind: "template-list" } }) as readonly JsonObject[], verticalRow = vertical.vertical as JsonObject;
    const projectedPresets = presets.map((entry) => ({ id: entry.id, title: entry.title, description: entry.description, verticalId: entry.verticalId, sourceKind: entry.layer === "bundled" ? "bundled" : entry.shadows ? "user-shadow" : "user", validity: entry.validity, version: entry.version ?? null, kind: entry.kind ?? null, defaultProfile: entry.defaultProfile ?? null, entrypoints: entry.entrypoints ?? [], issues: entry.issues, shadows: entry.shadows ?? null }));
    const body = { defaults: { verticalId: defaults.verticalId, presetId: defaults.presetId, profileId: defaults.profileId ?? null, locale: defaults.locale }, presets: projectedPresets, verticals: [{ id: verticalRow.id, title: verticalRow.title, version: verticalRow.version, source: "builtin", available: vertical.available === true, valid: vertical.valid === true, issues: Array.isArray(vertical.issues) ? vertical.issues : [] }], templates, adapters: [localAdapterProviderMetadata, multicaAdapterProviderMetadata].map((adapter) => ({ adapterId: adapter.id, registered: true, capabilities: [...adapter.capabilities], writability: adapter.writable ? "read-write" : adapter.readonly ? "read-only" : "unknown", defaultProvider: "defaultProvider" in adapter ? adapter.defaultProvider : false, unavailableReason: null })) };
    const catalogDigest = `sha256:${createHash("sha256").update(JSON.stringify(body)).digest("hex")}`; lastDigest = catalogDigest; return writeCatalogSnapshot({ schema: "gui-catalog-snapshot/v1", ok: true, status: "ready", repoId: input.repoId, observedAt: now(), catalogDigest, ...body } as const); };
  const preset = async (payload: JsonObject) => { const presetId = requiredCatalogText(payload.presetId, "presetId"), defaults = presetRuntimeDefaults(input.rootDir), inspected = await runPresetAction({ rootDir: input.rootDir, action: { kind: "preset-inspect", presetId, verticalId: defaults.verticalId, ...(text(payload.profileId) ? { profileId: payload.profileId } : {}), ...(text(payload.locale) ? { locale: payload.locale } : {}) } }) as { readonly manifest: JsonObject; readonly snapshot: JsonObject; readonly entrypoints: readonly string[] }, manifest = inspected.manifest, resolved = inspected.snapshot;
    return writeCatalogPreset({ schema: "gui-catalog-preset/v1", ok: true, repoId: input.repoId, preset: { id: manifest.id, title: manifest.title, verticalId: manifest.vertical, version: typeof manifest.version === "string" ? manifest.version : null, extends: typeof manifest.extends === "string" ? manifest.extends : null, capabilityImports: "capabilityImports" in manifest ? manifest.capabilityImports as readonly unknown[] : [], profiles: "profiles" in manifest ? manifest.profiles as readonly unknown[] : [] }, resolved: { identity: resolved.identity, profile: resolved.profile, templates: resolved.templates, entrypoints: inspected.entrypoints, provenance: resolved.provenance, digest: resolved.digest } } as const); };
  const reread = async (payload: JsonObject): Promise<CatalogRereadReceipt> => { const before = lastDigest ?? (await snapshot()).catalogDigest, expected = text(payload.expectedDigest); if (expected && expected !== before) return receipt(false, "op_rejected", before, before, "catalog_digest_changed", "Reread the current catalog before requesting refresh."); const after = (await snapshot()).catalogDigest; return receipt(true, "applied", before, after); };
  return { snapshot, preset, reread };
  function receipt(ok: boolean, outcome: "applied" | "op_rejected", beforeDigest: string, afterDigest: string, code?: string, hint?: string): CatalogRereadReceipt { const observedAt = now(); return writeCatalogRereadReceipt<CatalogRereadReceipt>({ schema: "catalog-reread-receipt/v1", ok, outcome, operationId: `catalog-${createHash("sha256").update(`${input.repoId}\0${beforeDigest}\0${afterDigest}\0${observedAt}`).digest("hex").slice(0, 20)}`, repoId: input.repoId, beforeDigest, afterDigest, observedAt, error: code && hint ? { code, hint } : null }); }
}
function requiredCatalogText(value: unknown, field: string): string { if (typeof value === "string" && value.length) return value; throw Object.assign(new Error(`${field} is required.`), { code: "invalid_catalog_request" }); }
function text(value: unknown): string | undefined { return typeof value === "string" && value.length ? value : undefined; }
