import { createHash } from "node:crypto";
import { closeSync, openSync, readFileSync, realpathSync, unlinkSync, writeFileSync } from "node:fs";
import path from "node:path";
import { makeTaskLifecycleService, type TaskLifecycleServiceProof } from "../../application/src/task-lifecycle-service.ts";
import { assertCurrentWriter, bindWriterGenerationToken, canonicalGateReceipts, compileCompletionGateWitness, completionBlockers, compileTaskProgress, isTaskEvent, isTaskProgressEvent, makeTaskEventStore, makeTaskProjection, normalizeCommandEnvelope,
  normalizeTaskLifecycleCommand, readRelationGraphProjection, reviewDigest, type ActorIdentity, type CompleteTaskCommand, type CompletionReadinessContext, type EventPublicationKillpoint, type ProofFor,
  type TaskLifecycleCommand, type TaskProgressEvidence, type TaskProgressEventV1, VcsCommandError, type WriteReceipt, type WriteSource, type WriterGeneration } from "../../kernel/src/index.ts";
import { compileRepoPresetSnapshotUpgrade, compileRepoTaskBootstrap, compileRepoTaskPackage, createPresetProcessService, presetUserRoot, runPresetAction, type PresetRunReceiptV1 } from "../../preset/src/index.ts";
import { commandClassForAction, type CanonicalRoot, type DaemonGuiReadMethod, type DaemonGuiReadResultMap, type DaemonTaskSnapshotListResult, type GuiSubmissionV1, type TaskPlacementSupplement, validateGuiSubmission, type WorkspaceId } from "./protocol/daemon-protocol.contract.ts";
import { bootstrapRepo, type RepoBootstrapInput, type RepoBootstrapReceipt } from "./repo-bootstrap.ts";
import { isDocAction, readDocReceipt, readProjectedDocument, runArtifactAdd, runDocAction } from "./doc-sync-actions.ts";
import { scanDocCandidates } from "./doc-sync-candidate-scanner.ts";
import { makeAgentRuntimeReadModel } from "./agent-runtime-read.ts"; import { makeAgentRuntimeStreamHub, type AgentRuntimeAttachSubscription, type AgentRuntimeStreamHub } from "./agent-runtime-stream.ts";
import { makeDecisionActions, makeFactActions } from "./fact-actions.ts";
import type { FleetAssignmentScope } from "./fleet/contract.ts";
import { openReplicaCutSource, type ReplicaCutSource } from "./fleet/replica-cut-store.ts";
import { runVerticalScriptAction } from "./vertical-script-actions.ts";
export type RepoTaskAction = Readonly<Record<string, unknown>> & { readonly kind: string }; export interface RepoCellBinding { readonly actor: ActorIdentity; readonly source: WriteSource; readonly roles?: readonly string[]; readonly docWriteAllowed?: boolean; readonly assignmentScope?: FleetAssignmentScope }
type TaskCreateReceipt = WriteReceipt & { readonly summary: string; readonly taskId: string; readonly status: "planned"; readonly packagePath: string; readonly generatedPaths: readonly string[]; readonly presetDigest: string; readonly scaffoldDigest: string; readonly completionGates: readonly string[]; readonly commitSha: string | null; readonly dryRun: boolean };
type TaskProgressReceipt = WriteReceipt & { readonly summary: string; readonly taskId: string; readonly executionId: string; readonly progressPath: string; readonly eventId: string; readonly commitSha: string; readonly worktreeVisible: true };
export interface RepoCellStatus { readonly repoId: string; readonly rootDir: string; readonly state: "attached" | "unavailable" | "closed"; readonly generation: number; readonly queueDepth: number; readonly lastError: string | null; readonly recoveryMs: number }
export interface RepoCell { readonly bootstrapReceipt?: RepoBootstrapReceipt; readonly run: (action: RepoTaskAction, binding: RepoCellBinding) => Promise<WriteReceipt>; readonly presetRun: (action: RepoTaskAction, binding: RepoCellBinding) => Promise<PresetRunReceiptV1>; readonly read: <M extends DaemonGuiReadMethod>(method: M, payload?: Readonly<Record<string, unknown>>) => Promise<DaemonGuiReadResultMap[M]>; readonly replica: ReplicaCutSource; readonly verifyReadiness: () => Promise<{ readonly cellState: "attached"; readonly l2State: "ready" }>; readonly attach: (runtimeSessionId: string, afterCursor: string) => Promise<AgentRuntimeAttachSubscription>; readonly runtime: Pick<AgentRuntimeStreamHub, "publish" | "issueWitnessToken" | "bindWitness">; readonly status: () => RepoCellStatus; readonly close: () => Promise<void> }
type DaemonGuiReadHandlers = { readonly [M in DaemonGuiReadMethod]: (payload: Readonly<Record<string, unknown>>) => DaemonGuiReadResultMap[M] };
const leaseTtlMs = 30 * 60 * 1_000; type Snapshot = Awaited<ReturnType<ReturnType<typeof makeTaskLifecycleService>["read"]>>["snapshot"];
export async function openRepoCell(input: { readonly repoId: WorkspaceId; readonly rootDir: CanonicalRoot; readonly ownerId: string;
  readonly authoredBranch?: string;
  readonly bootstrap?: RepoBootstrapInput; readonly onBootstrap?: (receipt: RepoBootstrapReceipt) => void;
  readonly now?: () => string; readonly killpoint?: (point: EventPublicationKillpoint) => void }): Promise<RepoCell> {
  const rootDir = input.rootDir, lock = await acquireWorkspaceLock(rootDir), generation = Date.now() * 1_000 + process.pid % 1_000;
  const activeWriter: WriterGeneration = { workspaceId: input.repoId, generation, ownerId: input.ownerId }, writerToken = bindWriterGenerationToken(activeWriter), now = input.now ?? (() => new Date().toISOString());
  let authoredBranch = input.authoredBranch, bootstrapReceipt: RepoBootstrapReceipt | undefined;
  try { if (input.bootstrap) { bootstrapReceipt = bootstrapRepo(input.bootstrap, activeWriter, writerToken, authoredBranch); authoredBranch = bootstrapReceipt.authoredBranch; input.onBootstrap?.(bootstrapReceipt); } }
  catch (error) { await lock.close(); throw error; }
  let initialized; try { initialized = (() => { const store = makeTaskEventStore({ repoId: input.repoId, rootDir, authoredBranch, killpoint: input.killpoint }), recovery = store.recover(), projection = makeTaskProjection({ rootDir, eventStore: store, now });
    const factActions = makeFactActions({ store, projection, now, killpoint: input.killpoint }), decisionActions = makeDecisionActions({ store, projection, now, killpoint: input.killpoint });
    const runtimeStream = makeAgentRuntimeStreamHub({ readSession: (runtimeSessionId) => { projection.list(); return projection.readRuntimeSession(runtimeSessionId); }, canAttach: (session) => session.attachable && Boolean(projection.readRuntimeInstallation(session.installationId)?.effectiveCapabilities.includes("attach")), now: () => new Date(now()) }), runtimeReads = makeAgentRuntimeReadModel({ projection, store, stream: runtimeStream }), service = makeTaskLifecycleService({ eventStore: store, projection, killpoint: input.killpoint }), presetProcess = createPresetProcessService({ rootDir, userRoot: presetUserRoot(rootDir) }), replica = openReplicaCutSource({ repoId: input.repoId, localRoot: path.dirname(path.dirname(projection.path)), readBasis: projection.readReplicaBasis, readContentBlob: store.readContentBlob, readEvent: store.readEvent, readApplied: projection.readOperation }); return { store, recovery, projection, factActions, decisionActions, runtimeStream, runtimeReads, service, presetProcess, replica }; })(); }
  catch (error) { await lock.close(); throw error; }
  const { store, recovery, projection, factActions, decisionActions, runtimeStream, runtimeReads, service, presetProcess, replica } = initialized; let knownTaskIds: Set<string> | null = null, state: RepoCellStatus["state"] = recovery.status === "indeterminate" || recovery.elapsedMs > 250 ? "unavailable" : "attached";
  let lastError: string | null = state === "attached" ? null : `startup recovery ${recovery.status} after ${recovery.elapsedMs.toFixed(3)}ms`;
  let queueDepth = 0, tail = Promise.resolve();
  const run = (action: RepoTaskAction, binding: RepoCellBinding): Promise<WriteReceipt> => {
    if (state !== "attached") return Promise.resolve(rejected(operationId(action, binding, input.repoId, 0), "repo_unavailable", lastError ?? "RepoCell is unavailable."));
    queueDepth += 1;
    const pending = tail.then(async () => { queueDepth -= 1; assertCurrentWriter(activeWriter, writerToken, input.repoId); return executeAction(action, binding); });
    tail = pending.then(() => undefined, () => undefined); void pending.then(() => replica.kick(), () => replica.kick()); const result = pending.catch((error) => { if (fatalCellError(error)) { state = "unavailable"; lastError = cellErrorMessage(error); }
      return failed(errorOperationId(error) ?? operationId(action, binding, input.repoId, 0), error); });
    return result;
  };
  const presetRun: RepoCell["presetRun"] = async (action, binding) => action.kind === "preset-run-status" ? presetProcess.status(requiredString(action.runId, "runId")) : action.kind === "preset-run-start" ? presetProcess.start({ presetId: requiredString(action.presetId, "presetId"), entrypoint: requiredString(action.entrypoint, "entrypoint"), ...(typeof action.taskId === "string" ? { taskId: action.taskId } : {}), ...(action.inputs && typeof action.inputs === "object" && !Array.isArray(action.inputs) ? { inputs: action.inputs as Readonly<Record<string, unknown>> } : {}), idempotencyKey: requiredString(action.idempotencyKey, "idempotencyKey") }, { admitProduce: (kind) => { try { return commandClassForAction(kind) === "repo-write"; } catch { return false; } }, publish: (produced) => run(produced, binding) }) : { schema: "preset-run-receipt/v1", runId: "run_invalid", outcome: "rejected", phase: "rejected", phases: ["rejected"], code: "unsupported_command", nextAction: "Use repo.preset.run.start or repo.preset.run.status." };
  const readHandlers = { "repo.tasks.list": () => guiTasks(), "repo.triadic.relationGraph": () => { projection.readDecisionGraph(); const facts = projection.readFactGraph(), { taskRows: _taskRows, ...graph } = readRelationGraphProjection({ rootDir }); return { ok: true as const, ...graph, facts: facts.facts }; },
    "repo.decisions.list": () => { const read = projection.listDecisions({}); return { ok: true, decisions: read.decisions, warnings: [] }; }, "repo.tasks.document.read": (payload) => readProjectedDocument(projection, payload), "repo.agentRuntime.overview": runtimeReads.overview, "repo.agentRuntime.sessions.read": runtimeReads.session, "repo.agentRuntime.events.read": runtimeReads.events
  } satisfies DaemonGuiReadHandlers;
  const read: RepoCell["read"] = async (method, payload = {}) => { await tail; if (state !== "attached") throw cellCodedError("repo_unavailable", lastError ?? "RepoCell is unavailable."); return dispatchRead(readHandlers, method, payload); };
  function guiTasks(): DaemonTaskSnapshotListResult { const lifecycle = projection.list(), l2 = new Map(readRelationGraphProjection({ rootDir }).taskRows.map((row) => [row.taskId, row])), decisions = new Map(projection.listDecisions({}).decisions.map((row) => [row.decisionId, row])), edges = projection.readDecisionGraph().edges; return { ok: true, ...lifecycle, rows: lifecycle.rows.map((row) => { const source = l2.get(row.taskId), derived = edges.filter((edge) => edge.state === "active" && edge.direction === "directed" && edge.relationType === "derives" && edge.targetRef === `task/${row.taskId}`), scopes = derived.flatMap((edge) => { const id = /^decision\/([^/]+)/u.exec(edge.sourceRef)?.[1]; return id ? [decisions.get(id)] : []; }).filter((value) => value !== undefined), origin: TaskPlacementSupplement["origin"] = source?.source === "external-engine" ? "external" : source && source.packageDisposition !== "active" ? "archival" : "native", placement: TaskPlacementSupplement = { moduleKeys: [...new Set([source?.moduleKey, ...scopes.flatMap((scope) => scope.appliesTo.modules)].filter((value): value is string => !!value))].sort(), productLines: [...new Set(scopes.flatMap((scope) => scope.appliesTo.productLines))].sort(), parentTaskId: source?.parentTaskId ?? null, origin, engine: source?.lifecycleEngine ?? "kernel/task-lifecycle/v1", packageDisposition: source?.packageDisposition ?? "active", provenance: [...(source ? [{ kind: "l2" as const, ref: source.sourcePath }] : [{ kind: "canonical-event" as const, ref: `task/${row.taskId}` }]), ...derived.map((edge) => ({ kind: "decision-relation" as const, ref: edge.relationId }))] }; return { ...row, snapshotAvailability: { consents: "known", codeDocWitnesses: "known", gateWitnesses: "known" }, placement, executionEvidence: row.snapshot.executions.map((execution) => ({ executionId: execution.executionId, origin: origin === "archival" ? "archival" as const : "native" as const, outputs: (execution.submission?.outputs ?? []).map((locator, index) => ({ evidenceId: `evidence_${createHash("sha256").update(`${row.taskId}\0${execution.executionId}\0${index}\0${locator}`).digest("hex").slice(0, 24)}`, locator, substrate: evidenceSubstrate(locator), checkerReceiptRef: null, checkerResult: "unknown" as const })) })) }; }) }; }
  return { bootstrapReceipt, run, presetRun, read, replica, verifyReadiness: async () => { const projected = await read("repo.tasks.list"), ready = projected.status === "ready"; if (!ready) throw cellCodedError("repo_unavailable", "RepoCell L2 projection is not ready."); return { cellState: "attached", l2State: "ready" }; }, attach: async (runtimeSessionId, afterCursor) => { await tail; if (state !== "attached") throw cellCodedError("repo_unavailable", lastError ?? "RepoCell is unavailable."); return runtimeStream.attach(runtimeSessionId, afterCursor); }, runtime: runtimeStream,
    status: () => ({ repoId: input.repoId, rootDir, state, generation, queueDepth, lastError, recoveryMs: recovery.elapsedMs }),
    close: async () => { if (state === "closed") return; state = "closed"; runtimeStream.close(); await presetProcess.close(); await tail; replica.close(); await lock.close(); } };
  async function executeAction(action: RepoTaskAction, binding: RepoCellBinding): Promise<WriteReceipt> {
    if (action.kind === "receipt-show") return receiptForOperation(String(action.opId ?? ""), binding);
    if (action.kind === "task-show") return showTask(String(action.taskId ?? ""));
    if (action.kind.startsWith("fact-")) return factActions.run(action, binding, operationId(action, binding, input.repoId, action.kind === "fact-record" && typeof action.taskId === "string" ? projection.read(action.taskId).snapshot.revision : store.readHead()?.revision ?? 0));
    if (action.kind.startsWith("decision-")) { const resolved = decisionProposalAction(rootDir, action); return decisionActions.run(resolved, binding, operationId(resolved, binding, input.repoId, resolved.kind === "decision-reckon" ? store.readHead()?.revision ?? 0 : 0)); }
    if (action.kind === "preset-upgrade") return upgradePresetSnapshot(action, binding); if (action.kind === "script-run") return runVerticalScriptAction({ action, binding, workspaceId: input.repoId, rootDir, store, projection, now, killpoint: input.killpoint }); if (action.kind.startsWith("preset-") || /^(?:vertical-validate|template-(?:list|render)|script-(?:list|inspect))$/u.test(action.kind)) { const result = await runPresetAction({ rootDir, action }); return { outcome: "applied", opId: operationId(action, binding, input.repoId, store.readHead()?.revision ?? 0), revision: store.readHead()?.revision ?? 0, evidence: JSON.stringify(result), visibility: "center", proof: { committedRevision: store.readHead()?.revision ?? 0, appliedCut: projection.list().watermark, durable: true, canonicalVisible: true, worktreeVisible: action.dryRun !== true && ["preset-install", "preset-seed", "preset-uninstall"].includes(action.kind) } }; }
    if (action.kind === "task-create") return createTask(action, binding);
    if (isDocAction(action.kind)) return runDocAction({ action, binding, workspaceId: input.repoId, rootDir, store, projection, now, killpoint: input.killpoint }); if (action.kind === "task-artifact-add") return runArtifactAdd({ action, binding, workspaceId: input.repoId, rootDir, store, projection, now, killpoint: input.killpoint });
    if (action.kind === "task-progress-append") return appendProgress(action, binding);
    if (action.kind === "task-complete") return completeTask(action, binding); if (!taskWriteKind(action.kind)) return rejected(operationId(action, binding, input.repoId, 0), "unsupported_command", "No domain contract exists for this write command."); return lifecycleAction(action, binding);
  }
  async function lifecycleAction(action: RepoTaskAction, binding: RepoCellBinding): Promise<WriteReceipt> { const taskId = requiredString(action.taskId, "taskId"), current = await service.read(taskId), expectedRevision = current.snapshot.revision;
    const normalized = buildCommand(action, taskId, binding, input.repoId, expectedRevision, rootDir);
    const command = withServerMeta(normalized, store.readTaskEvent(normalized.opId), store.readHead()?.revision ?? 0, now());
    const result = await service.execute(command, await proofFor(command, current.snapshot, binding));
    if (result.outcome === "applied" && result.event && result.proof) return lifecycleReceipt(result.event, result.snapshot, store.currentCommit().sha, result.proof);
    if (result.outcome === "pending") return { outcome: "pending", opId: command.opId, revision: result.revision, evidence: result.evidence, visibility: result.visibility, proof: result.proof, nextAction: result.nextAction ?? "Retry receipt show." };
    return rejected(command.opId, result.code ?? "publication_unknown", result.nextAction ?? "Retry receipt show before resubmitting.");
  }
  function createTask(action: RepoTaskAction, binding: RepoCellBinding): WriteReceipt { const dryRun = action.dryRun === true, canonicalAction = withoutDryRun(action), canonicalOpId = operationId(canonicalAction, binding, input.repoId, 0), opId = dryRun ? `preview:${createHash("sha256").update(canonicalOpId).digest("hex")}` : canonicalOpId, existing = dryRun ? null : store.readEvent(opId); if (existing) { projection.list(); return receiptForOperation(opId, binding); } const taskId = createTaskId(canonicalAction, binding, input.repoId), taskIds = projectedTaskIds(); if (taskIds.has(taskId)) return rejected(opId, "task_exists", `Task ${taskId} already exists.`); const currentRevision = store.readHead()?.revision ?? 0, workspaceRevision = currentRevision + 1, eventId = `event-${createHash("sha256").update(opId).digest("hex")}`, compiled = compileRepoTaskBootstrap({ rootDir, action: canonicalAction, taskId, actor: binding.actor, source: binding.source, workspaceRevision, eventId, opId, occurredAt: now() }), common = { taskId, status: "planned" as const, packagePath: compiled.packagePath, generatedPaths: compiled.documents.map((document) => document.path), presetDigest: compiled.snapshot.digest, scaffoldDigest: compiled.scaffoldDigest, completionGates: compiled.snapshot.profile.completionGateIds, dryRun };
    if (dryRun) { const preview: TaskCreateReceipt = { outcome: "applied", opId, revision: currentRevision, evidence: JSON.stringify(common), visibility: "center", proof: { committedRevision: currentRevision, appliedCut: currentRevision, durable: true, canonicalVisible: true, worktreeVisible: false }, ...common, commitSha: null, summary: `would create task ${taskId} at ${compiled.packagePath}`, nextAction: "remove --dry-run to publish this exact resolved scaffold" }; return preview; }
    const appended = store.append({ event: compiled.event, plan: compiled.plan, blobs: compiled.blobs }); projection.apply(compiled.event, compiled.plan); taskIds.add(taskId); input.killpoint?.("after_sqlite_commit"); const receipt: TaskCreateReceipt = { outcome: "applied", opId, revision: appended.revision, evidence: `event-object:${opId}`, visibility: "center", proof: { committedRevision: appended.revision, appliedCut: appended.revision, durable: true, canonicalVisible: true, worktreeVisible: true }, ...common, commitSha: appended.commitSha.sha, summary: `created task ${taskId} at ${compiled.packagePath}`, nextAction: `edit ${compiled.packagePath}/task_plan.md, then run ha task start ${taskId} --execution-id <id>` }; input.killpoint?.("before_response_write"); input.killpoint?.("after_response_write"); return receipt; }
  function upgradePresetSnapshot(action: RepoTaskAction, binding: RepoCellBinding): WriteReceipt { const taskId = requiredString(action.taskId, "taskId"), projected = projection.read(taskId), taskReady = projected.status === "ready"; if (!projected.snapshot.task || !projected.packagePath || !taskReady) throw cellCodedError("content_not_ready", `Task ${taskId} is not ready for preset upgrade.`); const contract = projection.readDocument(`${projected.packagePath}/task-contract.json`), contractReady = contract.status === "ready"; if (!contract.document || !contractReady) throw cellCodedError("content_not_ready", `Task ${taskId} contract is not ready for preset upgrade.`); const opId = operationId(action, binding, input.repoId, projected.snapshot.revision), existing = store.readEvent(opId); if (existing) return receiptForOperation(opId, binding); const compiled = compileRepoPresetSnapshotUpgrade({ rootDir, task: projected.snapshot.task, taskContractBody: contract.document.body, actor: binding.actor, source: binding.source, workspaceRevision: (store.readHead()?.revision ?? 0) + 1, eventId: `event-${createHash("sha256").update(opId).digest("hex")}`, opId, occurredAt: now() }), appended = store.append(compiled); projection.apply(compiled.event, compiled.plan); return { outcome: "applied", opId, revision: appended.revision, evidence: JSON.stringify({ taskId, previousDigest: compiled.event.payload.previousDigest, digest: compiled.snapshot.digest }), visibility: "center", proof: { committedRevision: appended.revision, appliedCut: projection.read(taskId).watermark, durable: true, canonicalVisible: true, worktreeVisible: true }, nextAction: `Run ha preset check ${compiled.snapshot.identity.id} --snapshot-digest ${compiled.snapshot.digest}.` }; }
  function appendProgress(action: RepoTaskAction, binding: RepoCellBinding): WriteReceipt { const taskId = requiredString(action.taskId, "taskId"), task = projection.read(taskId), expectedRevision = task.snapshot.revision, opId = operationId(action, binding, input.repoId, expectedRevision), existing = store.readEvent(opId); if (existing) { if (!isTaskProgressEvent(existing)) throw cellCodedError("op_conflict", `opId ${opId} belongs to another event`); return progressReceipt(existing, store.currentCommit().sha); } if (task.watermark < task.sourceRevision || !task.snapshot.task || !task.packagePath) throw cellCodedError("content_not_ready", `Task ${taskId} is not ready for progress append.`); const at = now(), lease = projection.currentLease(taskId, at), progressPath = `${task.packagePath}/progress.md`, document = projection.readDocument(progressPath); if (document.watermark < document.sourceRevision) throw cellCodedError("content_not_ready", `Progress projection for ${taskId} is not ready.`); const compiled = compileTaskProgress({ taskId, executionId: typeof action.executionId === "string" ? action.executionId : lease?.executionId ?? "", packagePath: task.packagePath, text: requiredString(action.text, "text"), evidence: progressEvidence(action.evidence), ...(typeof action.baseDocumentSha256 === "string" || action.baseDocumentSha256 === null ? { expectedBaseSha256: action.baseDocumentSha256 } : {}), currentDocument: document.document && document.document.path === progressPath ? { path: progressPath, blobSha256: document.document.blobSha256, body: document.document.body } : null, activeLease: lease, actor: binding.actor, source: binding.source, eventId: `event-${createHash("sha256").update(opId).digest("hex")}`, opId, workspaceRevision: (store.readHead()?.revision ?? 0) + 1, occurredAt: at });
    const appended = store.append(compiled); projection.apply(compiled.event, compiled.plan); input.killpoint?.("after_sqlite_commit"); const receipt = progressReceipt(compiled.event, appended.commitSha.sha); input.killpoint?.("before_response_write"); input.killpoint?.("after_response_write"); return receipt; }
  async function completeTask(action: RepoTaskAction, binding: RepoCellBinding): Promise<WriteReceipt> { const taskId = requiredString(action.taskId, "taskId"), executionId = requiredString(action.executionId, "executionId"), allowed = ["kind", "taskId", "executionId", "verb", "commandType", "ci", "commitSha", "iteration", "paths"]; if (Object.keys(action).some((field) => !allowed.includes(field)) || action.ci !== undefined && action.ci !== "passed" || !reconcileFields(action)) throw cellCodedError("invalid_command", "Complete accepts --ci passed and a complete commit-sha/iteration/path reconcile set only."); const steps: WriteReceipt[] = [], facadeOpId = operationId({ kind: "task-complete", taskId, executionId, ...(action.ci === "passed" ? { ci: "passed" } : {}), ...(typeof action.commitSha === "string" ? { commitSha: action.commitSha, iteration: action.iteration, paths: action.paths } : {}) }, binding, input.repoId, (await service.read(taskId)).snapshot.revision);
    for (let dispatch = 0; dispatch < 5; dispatch += 1) { const current = await service.read(taskId), completed = [...store.read().events].reverse().find((event) => isTaskEvent(event) && event.type === "task_completed" && event.taskId === taskId && event.payload.execution.executionId === executionId); if (completed && isTaskEvent(completed)) return completionApplied(lifecycleReceipt(completed, current.snapshot, store.currentCommit().sha, receiptProof(completed.workspaceRevision)), current.snapshot, executionId, steps);
      const context = completionContext(taskId, current.snapshot, current.packagePath, binding), blocker = completionBlockers(current.snapshot, executionId, context)[0]; if (!blocker) { let completed: WriteReceipt; try { completed = await lifecycleAction({ kind: "task-complete", taskId, executionId }, binding); } catch (error) { const published = [...store.read().events].reverse().find((event) => isTaskEvent(event) && event.type === "task_completed" && event.taskId === taskId && event.payload.execution.executionId === executionId); if (!published) throw error; const unknown = failed(published.opId, cellCodedError("publication_indeterminate", `publication result is unknown; run ha receipt show ${published.opId} before retrying`)); return completionSettlement(unknown, (await service.read(taskId)).snapshot, executionId, [...steps, unknown], "complete-settlement"); } return completed.outcome === "applied" ? completionApplied(completed, projection.read(taskId).snapshot, executionId, [...steps, completed]) : completionSettlement(completed, current.snapshot, executionId, steps, "complete-settlement"); }
      if (blocker.code === "ci_missing" && action.ci === "passed") { const step = publishCiWitness(taskId, executionId, current.snapshot, current.packagePath, binding); steps.push(step); continue; }
      if (blocker.code === "code_doc_missing" && typeof action.commitSha === "string") { const step = await lifecycleAction({ kind: "task-code-doc-reconcile", taskId, executionId, commitSha: action.commitSha, iteration: action.iteration, paths: action.paths }, binding); steps.push(step); if (step.outcome === "applied") continue; return completionSettlement(step, current.snapshot, executionId, steps, "code-doc-settlement"); }
      if (blocker.code === "doc_sync_required") { let step: WriteReceipt; try { step = await runDocAction({ action: { kind: "doc-submit", paths: context.eligibleDirtyPaths }, binding, workspaceId: input.repoId, rootDir, store, projection, now, killpoint: input.killpoint }); } catch (error) { step = failed(errorOperationId(error) ?? facadeOpId, error); consumeKnownError(error); } steps.push(step); if (step.outcome === "applied") continue; return completionSettlement(step, current.snapshot, executionId, steps, "doc-sync-settlement"); }
      return completionStopped(facadeOpId, current.snapshot, executionId, blocker, steps);
    } return completionSettlement(rejected(facadeOpId, "facade_replay_exhausted", `ha receipt show ${facadeOpId}`), (await service.read(taskId)).snapshot, executionId, steps, "re-dispatch");
  }
  function completionContext(taskId: string, snapshot: Snapshot, packagePath: string | null, binding: RepoCellBinding): CompletionReadinessContext { if (!packagePath || !snapshot.task?.presetSnapshotDigest) throw cellCodedError("content_not_ready", `Task ${taskId} package metadata is not ready.`); const presetRead = projection.readPresetSnapshot(snapshot.task.presetSnapshotDigest), presetReady = presetRead.status === "ready", preset = presetRead.snapshot as { readonly templates?: readonly { readonly slot: string; readonly path: string; readonly content: { readonly sha256: string } }[] } | null, template = preset?.templates?.find((value) => value.slot === "task.closeout"), contractDocument = projection.readDocument(`${packagePath}/task-contract.json`).document; if (!presetReady || !template || !contractDocument) throw cellCodedError("content_not_ready", `Task ${taskId} closeout template is not ready.`); const contract = JSON.parse(contractDocument.body) as Record<string, unknown>, current = compileRepoTaskPackage({ rootDir, taskId, action: { kind: "task-create", title: contract.title, presetId: contract.presetId, verticalId: contract.verticalId, profileId: contract.profileId, locale: contract.locale, taskClass: contract.taskClass } }); if (current.snapshot.digest !== snapshot.task.presetSnapshotDigest) throw cellCodedError("preset_snapshot_mismatch", `Run ha preset upgrade ${taskId} before completion.`); const closeoutPath = `${packagePath}/${template.path}`, projected = projection.readDocument(closeoutPath), scan = scanDocCandidates({ rootDir, workspaceId: input.repoId, store, projection, actor: binding.actor, source: binding.source, now: now(), selection: undefined }), relevant = scan.rows.filter((row) => row.path === closeoutPath || row.path.startsWith(`${packagePath}/artifacts/`)), eligibleDirtyPaths = relevant.filter((row) => row.state === "eligible").map((row) => row.path), closeout = eligibleDirtyPaths.includes(closeoutPath) ? "dirty_eligible" : projected.document === null ? "missing" : projected.document.blobSha256 === template.content.sha256 ? "placeholder" : "ready"; return { closeout, closeoutPath, eligibleDirtyPaths }; }
  function publishCiWitness(taskId: string, executionId: string, snapshot: Snapshot, packagePath: string | null, binding: RepoCellBinding): WriteReceipt { const execution = snapshot.executions.find((value) => value.executionId === executionId && value.iteration === snapshot.task?.iteration); if (!execution?.submission) throw cellCodedError("invalid_transition", "CI witness requires a submitted execution."); const intent = { kind: "canonical-checker-receipt", taskId, executionId, gateId: "ci", result: "pass", commitSha: execution.submission.commitSha, iteration: execution.iteration }, opId = operationId(intent, binding, input.repoId, snapshot.revision), existing = store.readEvent(opId); if (existing) { if (!isTaskEvent(existing) || existing.type !== "completion_gate_verified") throw cellCodedError("op_conflict", `opId ${opId} belongs to another event`); if (!projection.readOperation(opId)) projection.apply(existing); return lifecycleReceipt(existing, projection.read(taskId).snapshot, store.currentCommit().sha, receiptProof(existing.workspaceRevision)); } const rawPaths = packagePath ? [`${packagePath}/INDEX.md`, `${packagePath}/executions/${executionId}.md`] : [], compiled = compileCompletionGateWitness({ snapshot, taskId, executionId, gateId: "ci", result: "pass", receiptId: opId, checkerId: "standard", commitSha: execution.submission.commitSha, iteration: execution.iteration, actor: binding.actor, source: binding.source, opId, eventId: `event-${createHash("sha256").update(opId).digest("hex")}`, workspaceRevision: (store.readHead()?.revision ?? 0) + 1, occurredAt: now(), packagePath, currentDocuments: rawPaths.flatMap((target) => { const document = projection.readDocument(target).document; return document ? [document] : []; }) }); const appended = store.append(compiled); projection.apply(compiled.event, compiled.plan); completionKillpoint("after_sqlite_commit", opId); const receipt = lifecycleReceipt(compiled.event, projection.read(taskId).snapshot, appended.commitSha.sha, receiptProof(compiled.event.workspaceRevision)); completionKillpoint("before_response_write", opId); completionKillpoint("after_response_write", opId); return receipt; }
  function completionKillpoint(point: EventPublicationKillpoint, opId: string): void { try { input.killpoint?.(point); } catch (cause) { const error = cellCodedError("publication_indeterminate", `publication result is unknown; run ha receipt show ${opId} before retrying`) as Error & { opId: string; cause?: unknown }; error.opId = opId; error.cause = cause; throw error; } }
  async function showTask(taskId: string): Promise<WriteReceipt> {
    const read = await service.read(requiredString(taskId, "taskId")), projected = projection.read(taskId), receipt = { opId: `read:${taskId}`, revision: read.sourceRevision, evidence: JSON.stringify({ ...read.snapshot, packagePath: projected.packagePath }), visibility: "center" as const, proof: { committedRevision: read.sourceRevision, appliedCut: read.watermark, durable: true, canonicalVisible: read.status === "ready", worktreeVisible: null } };
    return read.status === "ready" ? { outcome: "applied", ...receipt } : { outcome: "pending", ...receipt, nextAction: "Retry task show after projection catch-up." };
  }
  function receiptForOperation(opId: string, binding: RepoCellBinding): WriteReceipt {
    requiredString(opId, "opId"); const event = store.readEvent(opId);
    if (event === null) return rejected(opId, "operation_not_published", "No committed event exists; retry only if the original request was rejected.");
    if (event.schema === "doc-event/v1") return readDocReceipt({ binding, workspaceId: input.repoId, rootDir, store, projection, now, killpoint: input.killpoint }, event);
    const commitSha = store.commitForOperation(opId)?.sha ?? store.currentCommit().sha;
    if (isTaskProgressEvent(event)) return progressReceipt(event, commitSha);
    const applied = projection.readOperation(opId), visible = !!applied && applied.watermark >= event.workspaceRevision, proof = { committedRevision: event.workspaceRevision, appliedCut: applied?.watermark ?? 0, durable: true, canonicalVisible: visible, worktreeVisible: isTaskEvent(event) || event.schema === "decision-event/v1" ? true : null };
    if (isTaskEvent(event) && visible) return lifecycleReceipt(event, projection.read(event.taskId).snapshot, commitSha, proof);
    if (event.schema === "decision-event/v1" && visible) { const claim = event.payload.decisionDocumentClaim, consentId = "judgmentConsent" in event.payload ? event.payload.judgmentConsent.consentId : null; return { outcome: "applied", opId, revision: event.workspaceRevision, evidence: `event-object:${opId}`, visibility: "center", proof, path: claim.path, commitSha, documentSha256: claim.sha256, worktreeVisible: true, consentId } as WriteReceipt; }
    return applied && applied.watermark >= event.workspaceRevision
      ? { outcome: "applied", opId, revision: event.workspaceRevision, evidence: `event-object:${opId}`, visibility: "center", proof }
      : { outcome: "pending", opId, revision: event.workspaceRevision, evidence: `event-object:${opId}`, visibility: "center", proof, nextAction: "Retry receipt show after projection catch-up." };
  }
  function projectedTaskIds(): Set<string> { if (knownTaskIds) return knownTaskIds; let read = projection.list(); while (read.status === "pending") read = projection.list(); knownTaskIds = new Set(read.rows.map(({ taskId }) => taskId)); return knownTaskIds; }
  function progressReceipt(event: TaskProgressEventV1, commitSha: string): TaskProgressReceipt { const applied = projection.readOperation(event.opId), visible = !!applied && applied.watermark >= event.workspaceRevision; return { outcome: visible ? "applied" : "pending", opId: event.opId, revision: event.workspaceRevision, evidence: `event-object:${event.opId};file:${event.payload.resultDocumentClaim.path}`, visibility: "center", proof: { committedRevision: event.workspaceRevision, appliedCut: applied?.watermark ?? 0, durable: true, canonicalVisible: visible, worktreeVisible: true }, summary: `appended progress for ${event.payload.taskId} at ${event.payload.resultDocumentClaim.path}`, taskId: event.payload.taskId, executionId: event.payload.executionId, progressPath: event.payload.resultDocumentClaim.path, eventId: event.eventId, commitSha, worktreeVisible: true, nextAction: `ha task submit ${event.payload.taskId} --execution-id ${event.payload.executionId} ...` }; }
} function dispatchRead<M extends DaemonGuiReadMethod>(handlers: DaemonGuiReadHandlers, method: M, payload: Readonly<Record<string, unknown>>): DaemonGuiReadResultMap[M] { return handlers[method](payload); }
function buildCommand(action: RepoTaskAction, taskId: string, binding: RepoCellBinding, workspaceId: string, expectedRevision: number, rootDir: string): Omit<TaskLifecycleCommand, "eventId" | "workspaceRevision" | "occurredAt"> {
  const bound = { workspaceId, actor: binding.actor, source: binding.source, expectedRevision };
  if (action.kind === "task-start") return normalizeTaskLifecycleCommand(bound, { type: "StartExecution", taskId, executionId: requiredString(action.executionId, "executionId") });
  if (action.kind === "task-submit") return normalizeTaskLifecycleCommand(bound, { type: "SubmitExecution", taskId, executionId: requiredString(action.executionId, "executionId"), submission: submissionPacket(action, rootDir) });
  if (action.kind === "task-review-execution") { const packet = packetFile(rootDir, action.fromFile, ["verdict", "reason", "evidenceChecked", "commitSha", "iteration"]); return normalizeTaskLifecycleCommand(bound, { type: "RecordReview", taskId, executionId: requiredString(action.executionId, "executionId"), reviewId: requiredString(action.reviewId, "reviewId"), verdict: reviewVerdict(packet.value.verdict), reason: requiredString(packet.value.reason, "reason"), evidenceChecked: strings(packet.value.evidenceChecked), commitSha: requiredString(packet.value.commitSha, "commitSha"), iteration: iteration(packet.value.iteration), contentDigest: packet.digest }); }
  if (action.kind === "task-review-consent") { const packet = packetFile(rootDir, action.fromFile, ["reviewDigest", "contentDigest"]); return normalizeTaskLifecycleCommand(bound, { type: "RecordReviewConsent", taskId, executionId: requiredString(action.executionId, "executionId"), reviewId: requiredString(action.reviewId, "reviewId"), consentId: requiredString(action.consentId, "consentId"), reviewDigest: digest(packet.value.reviewDigest, "reviewDigest"), contentDigest: digest(packet.value.contentDigest, "contentDigest") }); }
  if (action.kind === "task-code-doc-reconcile") return normalizeTaskLifecycleCommand(bound, { type: "ReconcileCodeDoc", taskId, executionId: requiredString(action.executionId, "executionId"), witnessId: `code-doc-${createHash("sha256").update(JSON.stringify(action)).digest("hex").slice(0, 16)}`, commitSha: requiredString(action.commitSha, "commitSha"), iteration: iteration(action.iteration), paths: strings(action.paths) });
  if (action.kind === "task-complete") return normalizeTaskLifecycleCommand(bound, { type: "CompleteTask", taskId, executionId: requiredString(action.executionId, "executionId") });
  throw new Error(`unsupported lifecycle command ${action.kind}`);
}
function withServerMeta(command: Omit<TaskLifecycleCommand, "eventId" | "workspaceRevision" | "occurredAt">, existing: ReturnType<ReturnType<typeof makeTaskEventStore>["readTaskEvent"]>, revision: number, occurredAt: string): TaskLifecycleCommand {
  return { ...command, eventId: existing?.eventId ?? `event-${createHash("sha256").update(command.opId).digest("hex")}`, workspaceRevision: existing?.workspaceRevision ?? revision + 1, occurredAt: existing?.occurredAt ?? occurredAt } as TaskLifecycleCommand; }
async function proofFor(command: TaskLifecycleCommand, snapshot: Snapshot, binding: RepoCellBinding): Promise<TaskLifecycleServiceProof<typeof command>> {
  if (command.type === "CreateReplayTask") return { taskIdUnique: true, actorBinding: command.actor };
  if (command.type === "StartExecution") return { actorBinding: command.actor, reservation: { taskId: command.taskId, executionId: command.executionId, expiresAt: new Date(Date.parse(command.occurredAt) + leaseTtlMs).toISOString(), ttlMs: leaseTtlMs } };
  if (command.type === "SubmitExecution") { const lease = snapshot.lease; if (!lease || lease.phase !== "active" || lease.executionId !== command.executionId || !sameActor(lease.actor, command.actor)) throw cellCodedError("lease_required", "Submit requires the active execution lease bound to this actor.");
    return { actorBinding: command.actor, leaseVersion: lease.version, sessionDisposition: "unavailable" };
  }
  if (command.type === "RecordReview") { if (!binding.roles?.includes("$arbiter") || !independentReviewer(command.actor, snapshot)) throw cellCodedError("actor_unauthorized", "Execution Review requires an independent transport-bound arbiter."); return { actorBinding: command.actor, capability: "execution-review@v1", capabilityRef: `transport-reviewer:${command.actor.principal.personId}` }; }
  if (command.type === "RecordReviewConsent") { if (!snapshot.task || !sameActor(snapshot.task.createdBy, command.actor)) throw cellCodedError("actor_unauthorized", "Review consent requires the Task owner."); return { actorBinding: command.actor, capability: "execution-consent@v1", capabilityRef: `task-owner:${command.actor.principal.personId}` }; }
  if (command.type === "ReconcileCodeDoc") return { actorBinding: command.actor, capability: "code-doc-reconcile@v1", capabilityRef: `transport-writer:${command.actor.principal.personId}` };
  return completeProof(command, snapshot) as TaskLifecycleServiceProof<typeof command>;
}
function completeProof(command: CompleteTaskCommand, snapshot: Snapshot): ProofFor<CompleteTaskCommand> {
  if (snapshot.lease !== null) throw cellCodedError("active_lease", "Complete requires the execution lease to be released.");
  if (snapshot.task?.createdBy.principal.personId !== command.actor.principal.personId) throw cellCodedError("actor_unauthorized", "Complete requires the Task owner.");
  const execution = snapshot.executions.find((candidate) => candidate.executionId === command.executionId && candidate.submission !== null);
  if (!execution?.submission) throw cellCodedError("invalid_transition", "Complete requires a submitted execution.");
  const supplied = canonicalGateReceipts(snapshot, execution); if (supplied.length !== (snapshot.task?.completionGateIds.length ?? 0)) throw cellCodedError("gate_witness_missing", "Every completion gate requires a canonical typed witness; local receipt files are not authoritative.");
  return { capability: "task-complete@v1", capabilityRef: `task-created-by:${command.taskId}:${command.actor.principal.personId}`, actorRole: "owner", noActiveLease: true, gateReceipts: supplied };
}
function createTaskId(action: RepoTaskAction, binding: RepoCellBinding, workspaceId: string): string { if (typeof action.taskId === "string" && action.taskId) return action.taskId;
  return `task_${operationId(action, binding, workspaceId, 0).slice(-26)}`; }
function withoutDryRun(action: RepoTaskAction): RepoTaskAction { const { dryRun: _dryRun, ...canonical } = action; return canonical; }
function operationId(action: RepoTaskAction, binding: RepoCellBinding, workspaceId: string, expectedRevision: number): string { const { actor: _actor, source: _source, root: _root, workspaceId: _workspace, serverWorkspaceId: _server, ...intent } = action;
  return normalizeCommandEnvelope({ workspaceId, actor: binding.actor, source: binding.source, expectedRevision, command: intent }).opId; }
function reconcileFields(action: RepoTaskAction): boolean { const fields = [typeof action.commitSha === "string", action.iteration === 0 || action.iteration === 1, Array.isArray(action.paths) && action.paths.length > 0 && action.paths.every((value) => typeof value === "string")]; return fields.every(Boolean) || fields.every((value) => !value); }
function receiptProof(revision: number): NonNullable<WriteReceipt["proof"]> { return { committedRevision: revision, appliedCut: revision, durable: true, canonicalVisible: true, worktreeVisible: true }; }
function gateChecks(snapshot: Snapshot, executionId: string) { const execution = snapshot.executions.find((value) => value.executionId === executionId && value.iteration === snapshot.task?.iteration); return (snapshot.task?.completionGateIds ?? []).map((gate) => { const codeDoc = gate === "code-doc-reconciliation" ? snapshot.codeDocWitnesses.find((value) => value.executionId === executionId && value.commitSha === execution?.submission?.commitSha && value.iteration === execution?.iteration) : undefined, witness = gate !== "code-doc-reconciliation" ? snapshot.gateWitnesses.find((value) => value.gateId === gate && value.executionId === executionId && value.commitSha === execution?.submission?.commitSha && value.iteration === execution?.iteration) : undefined; return { gate, status: codeDoc || witness ? "pass" : "blocked", witnessRef: codeDoc ? `event:${codeDoc.witnessId}` : witness ? `event:${witness.receiptId}` : null }; }); }
function completionApplied(receipt: WriteReceipt, snapshot: Snapshot, executionId: string, steps: readonly WriteReceipt[]): WriteReceipt { return { ...receipt, taskId: snapshot.task?.taskId, executionId, reviewId: snapshot.reviews.find((value) => value.executionId === executionId)?.reviewId ?? null, gateChecks: gateChecks(snapshot, executionId), next: [], steps } as WriteReceipt; }
function completionSettlement(receipt: WriteReceipt, snapshot: Snapshot, executionId: string, steps: readonly WriteReceipt[], stoppedAt: string): WriteReceipt { const command = receipt.outcome === "pending" || receipt.outcome === "indeterminate" ? `ha receipt show ${receipt.opId}` : receipt.nextAction ?? `ha receipt show ${receipt.opId}`, reason = receipt.outcome === "indeterminate" ? "The publication outcome is unknown; query the stable receipt before any retry." : receipt.outcome === "pending" ? "Wait for canonical settlement, then query this receipt." : "Resolve the rejected canonical step before retrying completion.", state = `${snapshot.task?.status ?? "missing"}/${snapshot.task?.currentNode ?? "missing"}`; return { ...receipt, taskId: snapshot.task?.taskId, executionId, reviewId: snapshot.reviews.find((value) => value.executionId === executionId)?.reviewId ?? null, transition: { from: snapshot.task?.status === "done" ? "in_review/review" : state, to: state }, gateChecks: gateChecks(snapshot, executionId), next: [{ command, reason }], steps, stoppedAt } as WriteReceipt; }
function completionStopped(opId: string, snapshot: Snapshot, executionId: string, blocker: ReturnType<typeof completionBlockers>[number], steps: readonly WriteReceipt[]): WriteReceipt { return { ...rejected(opId, blocker.code, blocker.next.command), taskId: snapshot.task?.taskId, executionId, reviewId: snapshot.reviews.find((value) => value.executionId === executionId)?.reviewId ?? null, transition: { from: `${snapshot.task?.status ?? "missing"}/${snapshot.task?.currentNode ?? "missing"}`, to: `${snapshot.task?.status ?? "missing"}/${snapshot.task?.currentNode ?? "missing"}` }, gateChecks: gateChecks(snapshot, executionId), next: [blocker.next], steps, stoppedAt: blocker.code } as WriteReceipt; }
function taskWriteKind(kind: string): boolean { return ["task-start", "task-submit", "task-review-execution", "task-review-consent", "task-code-doc-reconcile", "task-complete"].includes(kind); }
function rejected(opId: string, code: string, nextAction: string): WriteReceipt { return { outcome: "rejected", opId, code, origin: "daemon", nextAction, evidence: `rejection:${code}` }; } function failed(opId: string, error: unknown): WriteReceipt { const code = cellErrorCode(error); return error instanceof VcsCommandError || code === "publication_indeterminate" ? { outcome: "indeterminate", opId, code, origin: error instanceof VcsCommandError ? error.origin : "daemon", evidence: error instanceof VcsCommandError ? `git-failure:${error.command}` : "publication-cut:indeterminate", nextAction: error instanceof VcsCommandError ? `repair the Git object store and retry: ${error.message}` : cellErrorMessage(error) } : rejected(opId, code, cellErrorMessage(error)); }
function requiredString(value: unknown, name: string): string { if (typeof value === "string" && value.trim()) return value; throw cellCodedError("invalid_command", `${name} is required.`); }
function strings(value: unknown): readonly string[] { return Array.isArray(value) && value.every((item) => typeof item === "string") ? value : []; }
function progressEvidence(value: unknown): readonly TaskProgressEvidence[] { if (value === undefined) return []; if (!Array.isArray(value)) throw cellCodedError("invalid_progress", "evidence must be an ordered list"); return value.map((entry) => { if (!entry || typeof entry !== "object") throw cellCodedError("invalid_progress", "evidence entries require type, path, and summary"); const item = entry as Record<string, unknown>; return { type: requiredString(item.type, "evidence.type"), path: requiredString(item.path, "evidence.path"), summary: requiredString(item.summary, "evidence.summary") }; }); }
function sameActor(left: ActorIdentity, right: ActorIdentity): boolean { return left.principal.personId === right.principal.personId && left.executor?.id === right.executor?.id; }
function independentReviewer(actor: ActorIdentity, snapshot: Snapshot): boolean { const execution = snapshot.executions.find((candidate) => candidate.iteration === snapshot.task?.iteration && candidate.submission !== null);
  return execution !== undefined && !sameActor(execution.actor, actor); }
function reviewVerdict(value: unknown): "approved" | "changes_requested" | "dismissed" { if (value === "approved" || value === "changes_requested" || value === "dismissed") return value;
  throw cellCodedError("invalid_command", "verdict must be approved, changes_requested, or dismissed."); }
function iteration(value: unknown): number { if (value === 0 || value === 1) return value; throw cellCodedError("invalid_command", "iteration must be 0 or 1."); }
function digest(value: unknown, name: string): `sha256:${string}` { if (typeof value === "string" && /^sha256:[0-9a-f]{64}$/u.test(value)) return value as `sha256:${string}`; throw cellCodedError("invalid_command", `${name} must be a SHA-256 digest.`); }
const decisionProposalFields = ["title", "question", "riskTier", "urgency", "vertical", "preset", "decisionClass", "appliesTo", "chosen", "rejected", "claims", "fulfillments", "relations"] as const;
function decisionProposalAction(rootDir: string, action: RepoTaskAction): RepoTaskAction { if (action.kind !== "decision-propose") { if (Object.hasOwn(action, "body") || Object.hasOwn(action, "bodyFile")) throw cellCodedError("invalid_command", "Only decision propose accepts an initial body; use doc sync after creation."); return action; } const allowed = ["kind", "fromFile", "jsonInput", "body", "bodyFile"], fromFile = typeof action.fromFile === "string", jsonInput = typeof action.jsonInput === "string", direct = !fromFile && !jsonInput; if (direct && Object.keys(action).sort().join("\0") === ["kind", ...decisionProposalFields, "body"].sort().join("\0") && typeof action.body === "string") return action; if (Object.keys(action).some((field) => !allowed.includes(field)) || fromFile === jsonInput || action.body !== undefined && typeof action.body !== "string" || action.bodyFile !== undefined && typeof action.bodyFile !== "string" || typeof action.body === "string" && typeof action.bodyFile === "string") throw cellCodedError("invalid_command", "Decision propose requires one structured packet and at most one body source."); const packet = fromFile ? packetFile(rootDir, action.fromFile, decisionProposalFields).value : packetJson(action.jsonInput, decisionProposalFields), body = typeof action.body === "string" ? action.body : typeof action.bodyFile === "string" ? workspaceText(rootDir, action.bodyFile, "bodyFile") : `\n# ${requiredString(packet.title, "title")}\n`; return { kind: "decision-propose", ...packet, body }; }
function packetJson(value: unknown, fields: readonly string[]): Record<string, unknown> { let parsed: unknown; try { parsed = JSON.parse(requiredString(value, "jsonInput")); } catch { throw cellCodedError("invalid_command", "jsonInput must contain one UTF-8 JSON object."); } if (!parsed || typeof parsed !== "object" || Array.isArray(parsed) || Object.keys(parsed).sort().join("\0") !== [...fields].sort().join("\0")) throw cellCodedError("invalid_command", `proposal packet requires exactly: ${fields.join(", ")}.`); return parsed as Record<string, unknown>; }
function workspaceText(rootDir: string, requestedValue: unknown, field: string): string { const requested = requiredString(requestedValue, field); let root: string, candidate: string, bytes: Uint8Array; try { root = realpathSync(rootDir); candidate = realpathSync(path.resolve(root, requested)); bytes = readFileSync(candidate); } catch { throw cellCodedError("invalid_command", `${field} must be a readable UTF-8 file.`); } if (candidate !== root && !candidate.startsWith(`${root}${path.sep}`)) throw cellCodedError("invalid_command", `${field} must stay inside the workspace.`); try { return new TextDecoder("utf-8", { fatal: true }).decode(bytes); } catch { throw cellCodedError("invalid_command", `${field} must be a readable UTF-8 file.`); } }
function packetFile(rootDir: string, value: unknown, fields: readonly string[]): { readonly value: Record<string, unknown>; readonly digest: `sha256:${string}` } { const body = workspaceText(rootDir, value, "fromFile"), parsed = packetJson(body, fields); return { value: parsed, digest: `sha256:${createHash("sha256").update(body).digest("hex")}` }; }
function submissionPacket(action: RepoTaskAction, rootDir: string): GuiSubmissionV1 { if (action.submission !== undefined && action.fromFile !== undefined) throw cellCodedError("invalid_command", "Submit accepts either submission or fromFile, not both."); const value = action.submission ?? packetFile(rootDir, action.fromFile, ["completionClaim", "deliverables", "outputs", "verificationNotes", "knownGaps", "residualRisks", "commitSha"]).value, issues = validateGuiSubmission(value); if (issues.length) throw cellCodedError("invalid_submission", issues[0]!); return value as unknown as GuiSubmissionV1; }
function evidenceSubstrate(locator: string): "repository-path" | "uri" | "canonical-event" | "opaque" { if (/^[a-z][a-z0-9+.-]*:\/\//iu.test(locator)) return "uri"; if (locator.startsWith("event:")) return "canonical-event"; if (!path.isAbsolute(locator) && !locator.split("/").includes("..") && /^[A-Za-z0-9._/-]+$/u.test(locator)) return "repository-path"; return "opaque"; }
function lifecycleReceipt(event: Extract<ReturnType<ReturnType<typeof makeTaskEventStore>["readEvent"]>, { readonly schema: "task-event/v1" }>, snapshot: Snapshot, commitSha: string, proof: NonNullable<WriteReceipt["proof"]>): WriteReceipt { const executionId = event.type === "task_created" ? null : event.payload.execution.executionId, currentReview = snapshot.reviews.find((value) => value.executionId === executionId), reviewId = currentReview?.reviewId ?? null, from = event.type === "execution_started" ? "planned/implementation" : event.type === "execution_submitted" ? "active/implementation" : "in_review/review", to = `${snapshot.task?.status ?? "missing"}/${snapshot.task?.currentNode ?? "missing"}`, checks = gateChecks(snapshot, executionId ?? ""), missingGate = checks.find((value) => value.status === "blocked")?.gate, nextCommand = snapshot.task?.status === "active" ? `ha task submit ${event.taskId} --execution-id ${executionId ?? "<id>"} --from-file <submission.json>` : snapshot.task?.status !== "in_review" ? null : !currentReview ? `ha task review-execution ${event.taskId} --execution-id ${executionId} --review-id <id> --from-file <review.json>` : !snapshot.consents.some((value) => value.reviewId === currentReview.reviewId) ? `ha task review-consent ${event.taskId} --execution-id ${executionId} --review-id ${reviewId} --consent-id <id> --from-file <consent.json>` : missingGate === "ci" ? `ha task complete ${event.taskId} --execution-id ${executionId} --ci passed` : missingGate === "code-doc-reconciliation" ? `ha task code-doc reconcile ${event.taskId} --execution-id ${executionId} --commit-sha <sha> --iteration <n> --path <path>` : `ha task complete ${event.taskId} --execution-id ${executionId}`, next = nextCommand ? [{ command: nextCommand, reason: "Run the canonical next command for this lifecycle state." }] : [], changedPaths = (event.payload.documentClaims ?? []).map((claim) => claim.path); return { outcome: "applied", opId: event.opId, revision: event.workspaceRevision, evidence: `event-object:${event.opId};files:${changedPaths.join(",")}`, visibility: "center", proof, taskId: event.taskId, executionId, reviewId, reviewDigest: currentReview ? reviewDigest(currentReview) : null, contentDigest: currentReview?.contentDigest ?? null, transition: { from, to }, gateChecks: checks, next, changedPaths, eventId: event.eventId, commitSha, worktreeVisible: true } as WriteReceipt; }
function cellCodedError(code: string, text: string): Error { const error = new Error(text) as Error & { code: string }; error.code = code; return error; }
function errorOperationId(error: unknown): string | null { return typeof error === "object" && error !== null && "opId" in error && typeof error.opId === "string" ? error.opId : null; }
function cellErrorCode(error: unknown): string { return typeof error === "object" && error !== null && "code" in error && typeof error.code === "string" ? error.code : "service_rejected"; }
function cellErrorMessage(error: unknown): string { return error instanceof Error ? error.message : String(error); }
function fatalCellError(error: unknown): boolean { if (error instanceof VcsCommandError) return true; if (!error || typeof error !== "object" || !("code" in error)) return true; return ["invalid_store", "legacy_shape", "op_conflict", "revision_conflict", "publication_indeterminate", "writer_rejected"].includes(String(error.code)); }
async function acquireWorkspaceLock(rootDir: CanonicalRoot): Promise<{ readonly close: () => Promise<void> }> { const lockPath = `${rootDir}.harness-anything-writer.lock`; let descriptor: number;
  try { descriptor = openSync(lockPath, "wx", 0o600); writeFileSync(descriptor, `${process.pid}\n`, "utf8"); }
  catch (error) { if (!staleWriterLock(lockPath)) throw cellCodedError("writer_rejected", `Workspace writer lock is held for ${rootDir}: ${cellErrorMessage(error)}`); consumeKnownError(error); unlinkSync(lockPath); try { descriptor = openSync(lockPath, "wx", 0o600); writeFileSync(descriptor, `${process.pid}\n`, "utf8"); } catch (retry) { throw cellCodedError("writer_rejected", `Workspace writer lock recovery raced for ${rootDir}: ${cellErrorMessage(retry)}`); } }
  let closed = false; return { close: async () => { if (closed) return; closed = true; closeSync(descriptor); try { unlinkSync(lockPath); } catch (error) { if (cellErrorCode(error) === "ENOENT") { consumeKnownError(error); return; } throw error; } } }; }
const consumeKnownError = (error: unknown): void => { void error; };
function staleWriterLock(target: string): boolean { let pid: number; try { pid = Number(readFileSync(target, "utf8").trim()); if (!Number.isSafeInteger(pid) || pid < 1) return false; process.kill(pid, 0); return false; } catch (error) { return typeof error === "object" && error !== null && "code" in error && error.code === "ESRCH"; } }
