import { createHash } from "node:crypto";
import { closeSync, openSync, readFileSync, realpathSync, unlinkSync, writeFileSync } from "node:fs";
import path from "node:path";
import { makeTaskLifecycleService, type TaskLifecycleServiceProof } from "../../application/src/task-lifecycle-service.ts";
import { assertCurrentWriter, bindWriterGenerationToken, compileTaskProgress, isTaskEvent, isTaskProgressEvent, makeTaskEventStore, makeTaskProjection, normalizeCommandEnvelope,
  normalizeTaskLifecycleCommand, readRelationGraphProjection, reviewDigest, type ActorIdentity, type CompleteTaskCommand, type EventPublicationKillpoint, type ProofFor,
  type TaskLifecycleCommand, type TaskProgressEvidence, type TaskProgressEventV1, VcsCommandError, type WriteReceipt, type WriteSource, type WriterGeneration } from "../../kernel/src/index.ts";
import { compileRepoTaskBootstrap, createPresetProcessService, presetUserRoot, runPresetAction, type PresetRunReceiptV1 } from "../../preset/src/index.ts";
import { commandClassForAction, type CanonicalRoot, type DaemonGuiReadMethod, type DaemonGuiReadResultMap, type WorkspaceId } from "./protocol/daemon-protocol.contract.ts";
import { bootstrapRepo, type RepoBootstrapInput, type RepoBootstrapReceipt } from "./repo-bootstrap.ts";
import { isDocAction, readDocReceipt, readProjectedDocument, runArtifactAdd, runDocAction } from "./doc-sync-actions.ts";
import { makeAgentRuntimeReadModel } from "./agent-runtime-read.ts"; import { makeAgentRuntimeStreamHub, type AgentRuntimeAttachSubscription, type AgentRuntimeStreamHub } from "./agent-runtime-stream.ts";
import { makeDecisionActions, makeFactActions } from "./fact-actions.ts";
import type { FleetAssignmentScope } from "./fleet/contract.ts";
export type RepoTaskAction = Readonly<Record<string, unknown>> & { readonly kind: string }; export interface RepoCellBinding { readonly actor: ActorIdentity; readonly source: WriteSource; readonly roles?: readonly string[]; readonly docWriteAllowed?: boolean; readonly assignmentScope?: FleetAssignmentScope }
type TaskCreateReceipt = WriteReceipt & { readonly summary: string; readonly taskId: string; readonly status: "planned"; readonly packagePath: string; readonly generatedPaths: readonly string[]; readonly presetDigest: string; readonly scaffoldDigest: string; readonly completionGates: readonly string[]; readonly commitSha: string | null; readonly dryRun: boolean };
type TaskProgressReceipt = WriteReceipt & { readonly summary: string; readonly taskId: string; readonly executionId: string; readonly progressPath: string; readonly eventId: string; readonly commitSha: string; readonly worktreeVisible: true };
export interface RepoCellStatus { readonly repoId: string; readonly rootDir: string; readonly state: "attached" | "unavailable" | "closed"; readonly generation: number; readonly queueDepth: number; readonly lastError: string | null; readonly recoveryMs: number }
export interface RepoCell { readonly bootstrapReceipt?: RepoBootstrapReceipt; readonly run: (action: RepoTaskAction, binding: RepoCellBinding) => Promise<WriteReceipt>; readonly presetRun: (action: RepoTaskAction, binding: RepoCellBinding) => Promise<PresetRunReceiptV1>; readonly read: <M extends DaemonGuiReadMethod>(method: M, payload?: Readonly<Record<string, unknown>>) => Promise<DaemonGuiReadResultMap[M]>; readonly verifyReadiness: () => Promise<{ readonly cellState: "attached"; readonly l2State: "ready" }>; readonly attach: (runtimeSessionId: string, afterCursor: string) => Promise<AgentRuntimeAttachSubscription>; readonly runtime: Pick<AgentRuntimeStreamHub, "publish" | "issueWitnessToken" | "bindWitness">; readonly status: () => RepoCellStatus; readonly close: () => Promise<void> }
type DaemonGuiReadHandlers = { readonly [M in DaemonGuiReadMethod]: (payload: Readonly<Record<string, unknown>>) => DaemonGuiReadResultMap[M] };
const leaseTtlMs = 30 * 60 * 1_000; type Snapshot = Awaited<ReturnType<ReturnType<typeof makeTaskLifecycleService>["read"]>>["snapshot"];
export async function openRepoCell(input: { readonly repoId: WorkspaceId; readonly rootDir: CanonicalRoot; readonly ownerId: string;
  readonly authoredBranch?: string;
  readonly bootstrap?: RepoBootstrapInput; readonly onBootstrap?: (receipt: RepoBootstrapReceipt) => void;
  readonly now?: () => string; readonly killpoint?: (point: EventPublicationKillpoint) => void }): Promise<RepoCell> {
  const rootDir = input.rootDir, lock = await acquireWorkspaceLock(rootDir), generation = Date.now() * 1_000 + process.pid % 1_000;
  const activeWriter: WriterGeneration = { workspaceId: input.repoId, generation, ownerId: input.ownerId }, writerToken = bindWriterGenerationToken(activeWriter), now = input.now ?? (() => new Date().toISOString());
  let authoredBranch = input.authoredBranch, bootstrapReceipt: RepoBootstrapReceipt | undefined;
  try { if (input.bootstrap) { bootstrapReceipt = bootstrapRepo(input.bootstrap, activeWriter, writerToken, authoredBranch); authoredBranch = bootstrapReceipt.authoredBranch; input.onBootstrap?.(bootstrapReceipt); } }
  catch (error) { await lock.close(); throw error; }
  let initialized; try { initialized = (() => { const store = makeTaskEventStore({ repoId: input.repoId, rootDir, authoredBranch, killpoint: input.killpoint }), recovery = store.recover(), projection = makeTaskProjection({ rootDir, eventStore: store, now });
    const factActions = makeFactActions({ store, projection, now, killpoint: input.killpoint }), decisionActions = makeDecisionActions({ store, projection, now, killpoint: input.killpoint });
    const runtimeStream = makeAgentRuntimeStreamHub({ readSession: (runtimeSessionId) => { projection.list(); return projection.readRuntimeSession(runtimeSessionId); }, canAttach: (session) => session.attachable && Boolean(projection.readRuntimeInstallation(session.installationId)?.effectiveCapabilities.includes("attach")), now: () => new Date(now()) }), runtimeReads = makeAgentRuntimeReadModel({ projection, store, stream: runtimeStream }), service = makeTaskLifecycleService({ eventStore: store, projection, killpoint: input.killpoint }), presetProcess = createPresetProcessService({ rootDir, userRoot: presetUserRoot(rootDir) }); return { store, recovery, projection, factActions, decisionActions, runtimeStream, runtimeReads, service, presetProcess }; })(); }
  catch (error) { await lock.close(); throw error; }
  const { store, recovery, projection, factActions, decisionActions, runtimeStream, runtimeReads, service, presetProcess } = initialized; let knownTaskIds: Set<string> | null = null, state: RepoCellStatus["state"] = recovery.status === "indeterminate" || recovery.elapsedMs > 250 ? "unavailable" : "attached";
  let lastError: string | null = state === "attached" ? null : `startup recovery ${recovery.status} after ${recovery.elapsedMs.toFixed(3)}ms`;
  let queueDepth = 0, tail = Promise.resolve();
  const run = (action: RepoTaskAction, binding: RepoCellBinding): Promise<WriteReceipt> => {
    if (state !== "attached") return Promise.resolve(rejected(operationId(action, binding, input.repoId, 0), "repo_unavailable", lastError ?? "RepoCell is unavailable."));
    queueDepth += 1;
    const pending = tail.then(async () => { queueDepth -= 1; assertCurrentWriter(activeWriter, writerToken, input.repoId); return executeAction(action, binding); });
    tail = pending.then(() => undefined, () => undefined); const result = pending.catch((error) => { if (fatalCellError(error)) { state = "unavailable"; lastError = cellErrorMessage(error); }
      return failed(errorOperationId(error) ?? operationId(action, binding, input.repoId, 0), error); });
    return result;
  };
  const presetRun: RepoCell["presetRun"] = async (action, binding) => action.kind === "preset-run-status" ? presetProcess.status(requiredString(action.runId, "runId")) : action.kind === "preset-run-start" ? presetProcess.start({ presetId: requiredString(action.presetId, "presetId"), entrypoint: requiredString(action.entrypoint, "entrypoint"), ...(typeof action.taskId === "string" ? { taskId: action.taskId } : {}), ...(action.inputs && typeof action.inputs === "object" && !Array.isArray(action.inputs) ? { inputs: action.inputs as Readonly<Record<string, unknown>> } : {}), idempotencyKey: requiredString(action.idempotencyKey, "idempotencyKey") }, { admitProduce: (kind) => { try { return commandClassForAction(kind) === "repo-write"; } catch { return false; } }, publish: (produced) => run(produced, binding) }) : { schema: "preset-run-receipt/v1", runId: "run_invalid", outcome: "rejected", phase: "rejected", phases: ["rejected"], code: "unsupported_command", nextAction: "Use repo.preset.run.start or repo.preset.run.status." };
  const readHandlers = { "repo.tasks.list": () => ({ ok: true, ...projection.list() }), "repo.triadic.relationGraph": () => { projection.readDecisionGraph(); const facts = projection.readFactGraph(), graph = readRelationGraphProjection({ rootDir }); return { ok: true as const, ...graph, facts: facts.facts }; },
    "repo.decisions.list": () => { const read = projection.searchDecisions({}); return { ok: true, decisions: read.decisions, warnings: [] }; }, "repo.tasks.document.read": (payload) => readProjectedDocument(projection, payload), "repo.agentRuntime.overview": runtimeReads.overview, "repo.agentRuntime.sessions.read": runtimeReads.session, "repo.agentRuntime.events.read": runtimeReads.events
  } satisfies DaemonGuiReadHandlers;
  const read: RepoCell["read"] = async (method, payload = {}) => { await tail; if (state !== "attached") throw cellCodedError("repo_unavailable", lastError ?? "RepoCell is unavailable."); return dispatchRead(readHandlers, method, payload); };
  return { bootstrapReceipt, run, presetRun, read, verifyReadiness: async () => { const projected = await read("repo.tasks.list"), ready = projected.status === "ready"; if (!ready) throw cellCodedError("repo_unavailable", "RepoCell L2 projection is not ready."); return { cellState: "attached", l2State: "ready" }; }, attach: async (runtimeSessionId, afterCursor) => { await tail; if (state !== "attached") throw cellCodedError("repo_unavailable", lastError ?? "RepoCell is unavailable."); return runtimeStream.attach(runtimeSessionId, afterCursor); }, runtime: runtimeStream,
    status: () => ({ repoId: input.repoId, rootDir, state, generation, queueDepth, lastError, recoveryMs: recovery.elapsedMs }),
    close: async () => { if (state === "closed") return; state = "closed"; runtimeStream.close(); await presetProcess.close(); await tail; await lock.close(); } };
  async function executeAction(action: RepoTaskAction, binding: RepoCellBinding): Promise<WriteReceipt> {
    if (action.kind === "receipt-show") return receiptForOperation(String(action.opId ?? ""), binding);
    if (action.kind === "task-show") return showTask(String(action.taskId ?? ""));
    if (action.kind.startsWith("fact-")) return factActions.run(action, binding, operationId(action, binding, input.repoId, action.kind === "fact-record" && typeof action.taskId === "string" ? projection.read(action.taskId).snapshot.revision : store.readHead()?.revision ?? 0));
    if (action.kind.startsWith("decision-")) return decisionActions.run(action, binding, operationId(action, binding, input.repoId, store.readHead()?.revision ?? 0));
    if (action.kind.startsWith("preset-")) { const result = await runPresetAction({ rootDir, action }); return { outcome: "applied", opId: operationId(action, binding, input.repoId, store.readHead()?.revision ?? 0), revision: store.readHead()?.revision ?? 0, evidence: JSON.stringify(result), visibility: "center", proof: { committedRevision: store.readHead()?.revision ?? 0, appliedCut: projection.list().watermark, durable: true, canonicalVisible: true, worktreeVisible: action.kind === "preset-install" || action.kind === "preset-uninstall" } }; }
    if (action.kind === "task-create") return createTask(action, binding);
    if (isDocAction(action.kind)) return runDocAction({ action, binding, workspaceId: input.repoId, rootDir, store, projection, now, killpoint: input.killpoint }); if (action.kind === "task-artifact-add") return runArtifactAdd({ action, binding, workspaceId: input.repoId, rootDir, store, projection, now, killpoint: input.killpoint });
    if (action.kind === "task-progress-append") return appendProgress(action, binding);
    if (!taskWriteKind(action.kind)) return rejected(operationId(action, binding, input.repoId, 0), "unsupported_command", "No domain contract exists for this write command.");
    const taskId = requiredString(action.taskId, "taskId"), current = await service.read(taskId), expectedRevision = current.snapshot.revision;
    const normalized = buildCommand(action, taskId, binding, input.repoId, expectedRevision, rootDir);
    const command = withServerMeta(normalized, store.readTaskEvent(normalized.opId), store.readHead()?.revision ?? 0, now());
    const result = await service.execute(command, await proofFor(command, current.snapshot, binding));
    if (result.outcome === "applied" && result.event && result.proof) return lifecycleReceipt(result.event, result.snapshot, store.currentCommit().sha, result.proof);
    if (result.outcome === "pending") return { outcome: "pending", opId: command.opId, revision: result.revision, evidence: result.evidence, visibility: result.visibility, proof: result.proof, nextAction: result.nextAction ?? "Retry receipt show." };
    return rejected(command.opId, result.code ?? "publication_unknown", result.nextAction ?? "Retry receipt show before resubmitting.");
  }
  function createTask(action: RepoTaskAction, binding: RepoCellBinding): WriteReceipt { const dryRun = action.dryRun === true, canonicalAction = withoutDryRun(action), canonicalOpId = operationId(canonicalAction, binding, input.repoId, 0), opId = dryRun ? `preview:${createHash("sha256").update(canonicalOpId).digest("hex")}` : canonicalOpId, existing = dryRun ? null : store.readEvent(opId); if (existing) { projection.list(); return receiptForOperation(opId, binding); } const taskId = createTaskId(canonicalAction, binding, input.repoId), taskIds = projectedTaskIds(); if (taskIds.has(taskId)) return rejected(opId, "task_exists", `Task ${taskId} already exists.`); const currentRevision = store.readHead()?.revision ?? 0, workspaceRevision = currentRevision + 1, eventId = `event-${createHash("sha256").update(opId).digest("hex")}`, compiled = compileRepoTaskBootstrap({ rootDir, action: canonicalAction, taskId, actor: binding.actor, source: binding.source, workspaceRevision, eventId, opId, occurredAt: now() }), common = { taskId, status: "planned" as const, packagePath: compiled.packagePath, generatedPaths: compiled.documents.map((document) => document.path), presetDigest: compiled.snapshot.digest, scaffoldDigest: compiled.scaffoldDigest, completionGates: compiled.snapshot.profile.completionGateIds, dryRun };
    if (dryRun) { const preview: TaskCreateReceipt = { outcome: "applied", opId, revision: currentRevision, evidence: JSON.stringify(common), visibility: "center", proof: { committedRevision: currentRevision, appliedCut: currentRevision, durable: true, canonicalVisible: true, worktreeVisible: false }, ...common, commitSha: null, summary: `would create task ${taskId} at ${compiled.packagePath}`, nextAction: "remove --dry-run to publish this exact resolved scaffold" }; return preview; }
    const appended = store.append({ event: compiled.event, plan: compiled.plan, blobs: compiled.blobs }); projection.apply(compiled.event, compiled.plan); taskIds.add(taskId); input.killpoint?.("after_sqlite_commit"); const receipt: TaskCreateReceipt = { outcome: "applied", opId, revision: appended.revision, evidence: `event-object:${opId}`, visibility: "center", proof: { committedRevision: appended.revision, appliedCut: appended.revision, durable: true, canonicalVisible: true, worktreeVisible: true }, ...common, commitSha: appended.commitSha.sha, summary: `created task ${taskId} at ${compiled.packagePath}`, nextAction: `edit ${compiled.packagePath}/task_plan.md, then run ha task start ${taskId} --execution-id <id>` }; input.killpoint?.("before_response_write"); input.killpoint?.("after_response_write"); return receipt; }
  function appendProgress(action: RepoTaskAction, binding: RepoCellBinding): WriteReceipt { const taskId = requiredString(action.taskId, "taskId"), task = projection.read(taskId), expectedRevision = task.snapshot.revision, opId = operationId(action, binding, input.repoId, expectedRevision), existing = store.readEvent(opId); if (existing) { if (!isTaskProgressEvent(existing)) throw cellCodedError("op_conflict", `opId ${opId} belongs to another event`); return progressReceipt(existing, store.currentCommit().sha); } if (task.watermark < task.sourceRevision || !task.snapshot.task || !task.packagePath) throw cellCodedError("content_not_ready", `Task ${taskId} is not ready for progress append.`); const at = now(), lease = projection.currentLease(taskId, at), progressPath = `${task.packagePath}/progress.md`, document = projection.readDocument(progressPath); if (document.watermark < document.sourceRevision) throw cellCodedError("content_not_ready", `Progress projection for ${taskId} is not ready.`); const compiled = compileTaskProgress({ taskId, executionId: typeof action.executionId === "string" ? action.executionId : lease?.executionId ?? "", packagePath: task.packagePath, text: requiredString(action.text, "text"), evidence: progressEvidence(action.evidence), ...(typeof action.baseDocumentSha256 === "string" || action.baseDocumentSha256 === null ? { expectedBaseSha256: action.baseDocumentSha256 } : {}), currentDocument: document.document && document.document.path === progressPath ? { path: progressPath, blobSha256: document.document.blobSha256, body: document.document.body } : null, activeLease: lease, actor: binding.actor, source: binding.source, eventId: `event-${createHash("sha256").update(opId).digest("hex")}`, opId, workspaceRevision: (store.readHead()?.revision ?? 0) + 1, occurredAt: at });
    const appended = store.append(compiled); projection.apply(compiled.event, compiled.plan); input.killpoint?.("after_sqlite_commit"); const receipt = progressReceipt(compiled.event, appended.commitSha.sha); input.killpoint?.("before_response_write"); input.killpoint?.("after_response_write"); return receipt; }
  async function showTask(taskId: string): Promise<WriteReceipt> {
    const read = await service.read(requiredString(taskId, "taskId")), projected = projection.read(taskId), receipt = { opId: `read:${taskId}`, revision: read.sourceRevision, evidence: JSON.stringify({ ...read.snapshot, packagePath: projected.packagePath }), visibility: "center" as const, proof: { committedRevision: read.sourceRevision, appliedCut: read.watermark, durable: true, canonicalVisible: read.status === "ready", worktreeVisible: null } };
    return read.status === "ready" ? { outcome: "applied", ...receipt } : { outcome: "pending", ...receipt, nextAction: "Retry task show after projection catch-up." };
  }
  function receiptForOperation(opId: string, binding: RepoCellBinding): WriteReceipt {
    requiredString(opId, "opId"); const event = store.readEvent(opId);
    if (event === null) return rejected(opId, "operation_not_published", "No committed event exists; retry only if the original request was rejected.");
    if (event.schema === "doc-event/v1") return readDocReceipt({ binding, workspaceId: input.repoId, rootDir, store, projection, now, killpoint: input.killpoint }, event);
    if (isTaskProgressEvent(event)) return progressReceipt(event, store.currentCommit().sha);
    const applied = projection.readOperation(opId), proof = { committedRevision: event.workspaceRevision, appliedCut: applied?.watermark ?? 0, durable: true, canonicalVisible: !!applied && applied.watermark >= event.workspaceRevision, worktreeVisible: isTaskEvent(event) ? true : null };
    if (isTaskEvent(event) && applied && applied.watermark >= event.workspaceRevision) return lifecycleReceipt(event, projection.read(event.taskId).snapshot, store.currentCommit().sha, proof);
    return applied && applied.watermark >= event.workspaceRevision
      ? { outcome: "applied", opId, revision: event.workspaceRevision, evidence: `event-object:${opId}`, visibility: "center", proof }
      : { outcome: "pending", opId, revision: event.workspaceRevision, evidence: `event-object:${opId}`, visibility: "center", proof, nextAction: "Retry receipt show after projection catch-up." };
  }
  function projectedTaskIds(): Set<string> { if (knownTaskIds) return knownTaskIds; let read = projection.list(); while (read.status === "pending") read = projection.list(); knownTaskIds = new Set(read.rows.map(({ taskId }) => taskId)); return knownTaskIds; }
  function progressReceipt(event: TaskProgressEventV1, commitSha: string): TaskProgressReceipt { const applied = projection.readOperation(event.opId), visible = !!applied && applied.watermark >= event.workspaceRevision; return { outcome: visible ? "applied" : "pending", opId: event.opId, revision: event.workspaceRevision, evidence: `event-object:${event.opId};file:${event.payload.resultDocumentClaim.path}`, visibility: "center", proof: { committedRevision: event.workspaceRevision, appliedCut: applied?.watermark ?? 0, durable: true, canonicalVisible: visible, worktreeVisible: true }, summary: `appended progress for ${event.payload.taskId} at ${event.payload.resultDocumentClaim.path}`, taskId: event.payload.taskId, executionId: event.payload.executionId, progressPath: event.payload.resultDocumentClaim.path, eventId: event.eventId, commitSha, worktreeVisible: true, nextAction: `ha task submit ${event.payload.taskId} --execution-id ${event.payload.executionId} ...` }; }
} function dispatchRead<M extends DaemonGuiReadMethod>(handlers: DaemonGuiReadHandlers, method: M, payload: Readonly<Record<string, unknown>>): DaemonGuiReadResultMap[M] { return handlers[method](payload); }
function buildCommand(action: RepoTaskAction, taskId: string, binding: RepoCellBinding, workspaceId: string, expectedRevision: number, rootDir: string): Omit<TaskLifecycleCommand, "eventId" | "workspaceRevision" | "occurredAt"> {
  const bound = { workspaceId, actor: binding.actor, source: binding.source, expectedRevision };
  if (action.kind === "task-start") return normalizeTaskLifecycleCommand(bound, { type: "StartExecution", taskId, executionId: requiredString(action.executionId, "executionId") });
  if (action.kind === "task-submit") { const packet = packetFile(rootDir, action.fromFile, ["completionClaim", "deliverables", "outputs", "verificationNotes", "knownGaps", "residualRisks", "commitSha"]); return normalizeTaskLifecycleCommand(bound, { type: "SubmitExecution", taskId, executionId: requiredString(action.executionId, "executionId"), submission: { completionClaim: requiredString(packet.value.completionClaim, "completionClaim"), deliverables: strings(packet.value.deliverables), outputs: strings(packet.value.outputs), verificationNotes: strings(packet.value.verificationNotes), knownGaps: strings(packet.value.knownGaps), residualRisks: strings(packet.value.residualRisks), commitSha: requiredString(packet.value.commitSha, "commitSha") } }); }
  if (action.kind === "task-review-execution") { const packet = packetFile(rootDir, action.fromFile, ["verdict", "reason", "evidenceChecked", "commitSha", "iteration"]); return normalizeTaskLifecycleCommand(bound, { type: "RecordReview", taskId, executionId: requiredString(action.executionId, "executionId"), reviewId: requiredString(action.reviewId, "reviewId"), verdict: reviewVerdict(packet.value.verdict), reason: requiredString(packet.value.reason, "reason"), evidenceChecked: strings(packet.value.evidenceChecked), commitSha: requiredString(packet.value.commitSha, "commitSha"), iteration: iteration(packet.value.iteration), contentDigest: packet.digest }); }
  if (action.kind === "task-review-consent") { const packet = packetFile(rootDir, action.fromFile, ["reviewDigest", "contentDigest"]); return normalizeTaskLifecycleCommand(bound, { type: "RecordReviewConsent", taskId, executionId: requiredString(action.executionId, "executionId"), reviewId: requiredString(action.reviewId, "reviewId"), consentId: requiredString(action.consentId, "consentId"), reviewDigest: digest(packet.value.reviewDigest, "reviewDigest"), contentDigest: digest(packet.value.contentDigest, "contentDigest") }); }
  if (action.kind === "task-code-doc-reconcile") return normalizeTaskLifecycleCommand(bound, { type: "ReconcileCodeDoc", taskId, executionId: requiredString(action.executionId, "executionId"), witnessId: `code-doc-${createHash("sha256").update(JSON.stringify(action)).digest("hex").slice(0, 16)}`, commitSha: requiredString(action.commitSha, "commitSha"), iteration: iteration(action.iteration), paths: strings(action.paths) });
  if (action.kind === "task-complete") return normalizeTaskLifecycleCommand(bound, { type: "CompleteTask", taskId, executionId: requiredString(action.executionId, "executionId") });
  throw new Error(`unsupported lifecycle command ${action.kind}`);
}
function withServerMeta(command: Omit<TaskLifecycleCommand, "eventId" | "workspaceRevision" | "occurredAt">, existing: ReturnType<ReturnType<typeof makeTaskEventStore>["readTaskEvent"]>, revision: number, occurredAt: string): TaskLifecycleCommand {
  return { ...command, eventId: existing?.eventId ?? `event-${createHash("sha256").update(command.opId).digest("hex")}`, workspaceRevision: existing?.workspaceRevision ?? revision + 1, occurredAt: existing?.occurredAt ?? occurredAt } as TaskLifecycleCommand; }
async function proofFor(command: TaskLifecycleCommand, snapshot: Snapshot, binding: RepoCellBinding): Promise<TaskLifecycleServiceProof<typeof command>> {
  if (command.type === "CreateReplayTask") return { taskIdUnique: true, actorBinding: command.actor };
  if (command.type === "StartExecution") return { actorBinding: command.actor, reservation: { taskId: command.taskId, executionId: command.executionId, expiresAt: new Date(Date.parse(command.occurredAt) + leaseTtlMs).toISOString(), ttlMs: leaseTtlMs } };
  if (command.type === "SubmitExecution") { const lease = snapshot.lease; if (!lease || lease.phase !== "active" || lease.executionId !== command.executionId || !sameActor(lease.actor, command.actor)) throw cellCodedError("lease_required", "Submit requires the active execution lease bound to this actor.");
    return { actorBinding: command.actor, leaseVersion: lease.version, sessionDisposition: "unavailable" };
  }
  if (command.type === "RecordReview") { if (!binding.roles?.includes("$arbiter") || !independentReviewer(command.actor, snapshot)) throw cellCodedError("actor_unauthorized", "Execution Review requires an independent transport-bound arbiter."); return { actorBinding: command.actor, capability: "execution-review@v1", capabilityRef: `transport-reviewer:${command.actor.principal.personId}` }; }
  if (command.type === "RecordReviewConsent") { if (!snapshot.task || !sameActor(snapshot.task.createdBy, command.actor)) throw cellCodedError("actor_unauthorized", "Review consent requires the Task owner."); return { actorBinding: command.actor, capability: "execution-consent@v1", capabilityRef: `task-owner:${command.actor.principal.personId}` }; }
  if (command.type === "ReconcileCodeDoc") return { actorBinding: command.actor, capability: "code-doc-reconcile@v1", capabilityRef: `transport-writer:${command.actor.principal.personId}` };
  return completeProof(command, snapshot) as TaskLifecycleServiceProof<typeof command>;
}
function completeProof(command: CompleteTaskCommand, snapshot: Snapshot): ProofFor<CompleteTaskCommand> {
  if (snapshot.lease !== null) throw cellCodedError("active_lease", "Complete requires the execution lease to be released.");
  if (snapshot.task?.createdBy.principal.personId !== command.actor.principal.personId) throw cellCodedError("actor_unauthorized", "Complete requires the Task owner.");
  const execution = snapshot.executions.find((candidate) => candidate.executionId === command.executionId && candidate.submission !== null);
  if (!execution?.submission) throw cellCodedError("invalid_transition", "Complete requires a submitted execution.");
  const supplied = (snapshot.task?.completionGateIds ?? []).map((gateId) => { const witness = gateId === "code-doc-reconciliation" ? snapshot.codeDocWitnesses.find((value) => value.executionId === execution.executionId && value.commitSha === execution.submission?.commitSha && value.iteration === execution.iteration) : undefined; if (!witness) throw cellCodedError("gate_witness_missing", `Gate ${gateId} requires a canonical typed witness; local receipt files are not authoritative.`); return { gateId, receiptRef: `event:${witness.witnessId}`, result: "pass" as const, executionId: execution.executionId, commitSha: execution.submission!.commitSha, iteration: execution.iteration }; });
  return { capability: "task-complete@v1", capabilityRef: `task-created-by:${command.taskId}:${command.actor.principal.personId}`, actorRole: "owner", noActiveLease: true, gateReceipts: supplied };
}
function createTaskId(action: RepoTaskAction, binding: RepoCellBinding, workspaceId: string): string { if (typeof action.taskId === "string" && action.taskId) return action.taskId;
  return `task_${operationId(action, binding, workspaceId, 0).slice(-26)}`; }
function withoutDryRun(action: RepoTaskAction): RepoTaskAction { const { dryRun: _dryRun, ...canonical } = action; return canonical; }
function operationId(action: RepoTaskAction, binding: RepoCellBinding, workspaceId: string, expectedRevision: number): string { const { actor: _actor, source: _source, root: _root, workspaceId: _workspace, serverWorkspaceId: _server, ...intent } = action;
  return normalizeCommandEnvelope({ workspaceId, actor: binding.actor, source: binding.source, expectedRevision, command: intent }).opId; }
function taskWriteKind(kind: string): boolean { return ["task-start", "task-submit", "task-review-execution", "task-review-consent", "task-code-doc-reconcile", "task-complete"].includes(kind); }
function rejected(opId: string, code: string, nextAction: string): WriteReceipt { return { outcome: "rejected", opId, code, origin: "daemon", nextAction, evidence: `rejection:${code}` }; } function failed(opId: string, error: unknown): WriteReceipt { const code = cellErrorCode(error); return error instanceof VcsCommandError || code === "publication_indeterminate" ? { outcome: "indeterminate", opId, code, origin: error instanceof VcsCommandError ? error.origin : "daemon", evidence: error instanceof VcsCommandError ? `git-failure:${error.command}` : "publication-cut:indeterminate", nextAction: error instanceof VcsCommandError ? `repair the Git object store and retry: ${error.message}` : cellErrorMessage(error) } : rejected(opId, code, cellErrorMessage(error)); }
function requiredString(value: unknown, name: string): string { if (typeof value === "string" && value.trim()) return value; throw cellCodedError("invalid_command", `${name} is required.`); }
function strings(value: unknown): readonly string[] { return Array.isArray(value) && value.every((item) => typeof item === "string") ? value : []; }
function progressEvidence(value: unknown): readonly TaskProgressEvidence[] { if (value === undefined) return []; if (!Array.isArray(value)) throw cellCodedError("invalid_progress", "evidence must be an ordered list"); return value.map((entry) => { if (!entry || typeof entry !== "object") throw cellCodedError("invalid_progress", "evidence entries require type, path, and summary"); const item = entry as Record<string, unknown>; return { type: requiredString(item.type, "evidence.type"), path: requiredString(item.path, "evidence.path"), summary: requiredString(item.summary, "evidence.summary") }; }); }
function sameActor(left: ActorIdentity, right: ActorIdentity): boolean { return left.principal.personId === right.principal.personId && left.executor?.id === right.executor?.id; }
function independentReviewer(actor: ActorIdentity, snapshot: Snapshot): boolean { const execution = snapshot.executions.find((candidate) => candidate.iteration === snapshot.task?.iteration && candidate.submission !== null);
  return execution !== undefined && !sameActor(execution.actor, actor); }
function reviewVerdict(value: unknown): "approved" | "changes_requested" | "dismissed" { if (value === "approved" || value === "changes_requested" || value === "dismissed") return value;
  throw cellCodedError("invalid_command", "verdict must be approved, changes_requested, or dismissed."); }
function iteration(value: unknown): number { if (value === 0 || value === 1) return value; throw cellCodedError("invalid_command", "iteration must be 0 or 1."); }
function digest(value: unknown, name: string): `sha256:${string}` { if (typeof value === "string" && /^sha256:[0-9a-f]{64}$/u.test(value)) return value as `sha256:${string}`; throw cellCodedError("invalid_command", `${name} must be a SHA-256 digest.`); }
function packetFile(rootDir: string, value: unknown, fields: readonly string[]): { readonly value: Record<string, unknown>; readonly digest: `sha256:${string}` } { const requested = requiredString(value, "fromFile"), root = realpathSync(rootDir), candidate = realpathSync(path.resolve(root, requested)); if (candidate !== root && !candidate.startsWith(`${root}${path.sep}`)) throw cellCodedError("invalid_command", "fromFile must stay inside the workspace."); const body = readFileSync(candidate, "utf8"); let parsed: unknown; try { parsed = JSON.parse(body); } catch { throw cellCodedError("invalid_command", "fromFile must contain UTF-8 JSON."); } if (!parsed || typeof parsed !== "object" || Array.isArray(parsed) || Object.keys(parsed).sort().join("\0") !== [...fields].sort().join("\0")) throw cellCodedError("invalid_command", `fromFile requires exactly: ${fields.join(", ")}.`); return { value: parsed as Record<string, unknown>, digest: `sha256:${createHash("sha256").update(body).digest("hex")}` }; }
function lifecycleReceipt(event: Extract<ReturnType<ReturnType<typeof makeTaskEventStore>["readEvent"]>, { readonly schema: "task-event/v1" }>, snapshot: Snapshot, commitSha: string, proof: NonNullable<WriteReceipt["proof"]>): WriteReceipt { const executionId = event.type === "task_created" ? null : event.payload.execution.executionId, currentReview = snapshot.reviews.find((value) => value.executionId === executionId), reviewId = currentReview?.reviewId ?? null, from = event.type === "execution_started" ? "planned/implementation" : event.type === "execution_submitted" ? "active/implementation" : "in_review/review", to = `${snapshot.task?.status ?? "missing"}/${snapshot.task?.currentNode ?? "missing"}`, next = snapshot.task?.status === "active" ? [`ha task submit ${event.taskId} --execution-id ${executionId ?? "<id>"} --from-file <submission.json>`] : snapshot.task?.status !== "in_review" ? [] : !currentReview ? [`ha task review-execution ${event.taskId} --execution-id ${executionId} --review-id <id> --from-file <review.json>`] : !snapshot.consents.some((value) => value.reviewId === currentReview.reviewId) ? [`ha task review-consent ${event.taskId} --execution-id ${executionId} --review-id ${reviewId} --consent-id <id> --from-file <consent.json>`] : snapshot.task.completionGateIds.includes("code-doc-reconciliation") && !snapshot.codeDocWitnesses.some((value) => value.executionId === executionId) ? [`ha task code-doc reconcile ${event.taskId} --execution-id ${executionId} --commit-sha <sha> --iteration <n> --path <path>`] : [`ha task complete ${event.taskId} --execution-id ${executionId}`]; const changedPaths = (event.payload.documentClaims ?? []).map((claim) => claim.path); return { outcome: "applied", opId: event.opId, revision: event.workspaceRevision, evidence: `event-object:${event.opId};files:${changedPaths.join(",")}`, visibility: "center", proof, taskId: event.taskId, executionId, reviewId, reviewDigest: currentReview ? reviewDigest(currentReview) : null, contentDigest: currentReview?.contentDigest ?? null, transition: { from, to }, next, changedPaths, eventId: event.eventId, commitSha, worktreeVisible: true } as WriteReceipt; }
function cellCodedError(code: string, text: string): Error { const error = new Error(text) as Error & { code: string }; error.code = code; return error; }
function errorOperationId(error: unknown): string | null { return typeof error === "object" && error !== null && "opId" in error && typeof error.opId === "string" ? error.opId : null; }
function cellErrorCode(error: unknown): string { return typeof error === "object" && error !== null && "code" in error && typeof error.code === "string" ? error.code : "service_rejected"; }
function cellErrorMessage(error: unknown): string { return error instanceof Error ? error.message : String(error); }
function fatalCellError(error: unknown): boolean { if (error instanceof VcsCommandError) return true; if (!(error instanceof Error) || !("code" in error)) return true; return ["invalid_store", "legacy_shape", "op_conflict", "revision_conflict", "publication_indeterminate", "writer_rejected"].includes(String(error.code)); }
async function acquireWorkspaceLock(rootDir: CanonicalRoot): Promise<{ readonly close: () => Promise<void> }> { const lockPath = `${rootDir}.harness-anything-writer.lock`; let descriptor: number;
  try { descriptor = openSync(lockPath, "wx", 0o600); writeFileSync(descriptor, `${process.pid}\n`, "utf8"); }
  catch (error) { if (!staleWriterLock(lockPath)) throw cellCodedError("writer_rejected", `Workspace writer lock is held for ${rootDir}: ${cellErrorMessage(error)}`); consumeKnownError(error); unlinkSync(lockPath); try { descriptor = openSync(lockPath, "wx", 0o600); writeFileSync(descriptor, `${process.pid}\n`, "utf8"); } catch (retry) { throw cellCodedError("writer_rejected", `Workspace writer lock recovery raced for ${rootDir}: ${cellErrorMessage(retry)}`); } }
  let closed = false; return { close: async () => { if (closed) return; closed = true; closeSync(descriptor); try { unlinkSync(lockPath); } catch (error) { if (cellErrorCode(error) === "ENOENT") { consumeKnownError(error); return; } throw error; } } }; }
const consumeKnownError = (error: unknown): void => { void error; };
function staleWriterLock(target: string): boolean { let pid: number; try { pid = Number(readFileSync(target, "utf8").trim()); if (!Number.isSafeInteger(pid) || pid < 1) return false; process.kill(pid, 0); return false; } catch (error) { return typeof error === "object" && error !== null && "code" in error && error.code === "ESRCH"; } }
