import { execFileSync, spawn } from "node:child_process";
import { createHash } from "node:crypto";
import path from "node:path";
import { canonicalEventWritePlan } from "../../kernel/src/index.ts";
import type { ActorIdentity, AgentRuntimeEventV1, CanonicalEventStore, TaskProjection, WriteSource } from "../../kernel/src/index.ts";
import type { JsonObject } from "./protocol/json-rpc-types.ts";
import type { RuntimeCredentialBinding } from "./runtime-credentials.ts";
import type { RuntimeInstallationWitness } from "./agent-runtime-instances.ts";
import { runtimeKindForInstallation } from "./runtime-inventory.ts";

export interface RuntimeProcess { readonly pid: number; readonly onExit: (listener: (code: number | null) => void) => void; readonly terminate: () => void }
export type RuntimeLauncher = (input: { readonly kindId: "claude" | "codex"; readonly installation: RuntimeInstallationWitness; readonly cwd: string; readonly prompt: string; readonly credential: RuntimeCredentialBinding | null }) => RuntimeProcess;
export function makeRuntimeSpawner(input: { readonly repoId: string; readonly rootDir: string; readonly daemonGeneration: number; readonly store: CanonicalEventStore; readonly projection: TaskProjection; readonly now: () => string; readonly launch?: RuntimeLauncher; readonly installation?: (installationId: string) => RuntimeInstallationWitness | null; readonly credential?: (kindId: "claude" | "codex") => RuntimeCredentialBinding | null; readonly schedule: (work: () => void) => void }) {
  const processes = new Map<string, RuntimeProcess>(), launch = input.launch ?? launchNative;
  return {
    spawn: (payload: JsonObject, binding: { readonly actor: ActorIdentity; readonly source: WriteSource }) => {
      const allowed = ["kindId", "installationId", "profileId", "cwd", "prompt", "taskId", "idempotencyKey"]; if (Object.keys(payload).some((key) => !allowed.includes(key))) throw coded("invalid_runtime_spawn", "Runtime spawn payload contains an unknown field.");
      const kindId = enumValue(payload.kindId, ["claude", "codex"] as const, "kindId"), installationId = required(payload.installationId, "installationId"), profileId = required(payload.profileId, "profileId"), prompt = required(payload.prompt, "prompt"), idempotencyKey = required(payload.idempotencyKey, "idempotencyKey"), taskId = payload.taskId === null ? null : required(payload.taskId, "taskId");
      input.projection.list(); const installation = input.projection.readRuntimeInstallation(installationId), credential = input.credential?.(kindId) ?? null; if (!installation || runtimeKindForInstallation(installation).kindId !== kindId) throw coded("runtime_installation_not_found", "The selected runtime installation is not in this repository runtime kind."); const witnessed = input.installation?.(installationId); if (!witnessed || witnessed.kindId !== kindId) throw coded("runtime_installation_not_found", "The selected runtime installation has no current machine witness."); if (!runtimeKindForInstallation(installation).profileKinds.includes(profileId)) throw coded("runtime_profile_not_found", "The selected profile is not in this runtime installation inventory."); if (installation.authState !== "configured" && !credential) throw coded("runtime_credential_required", "Configure this runtime credential before spawning.");
      const cwd = resolveCwd(input.rootDir, payload.cwd), lease = taskId ? input.projection.currentLease(taskId) : null; if (taskId && (!lease || lease.phase !== "active" || lease.actor.principal.personId !== binding.actor.principal.personId || lease.actor.executor?.id !== binding.actor.executor?.id)) throw coded("runtime_task_lease_required", "Task-bound runtime spawn requires the caller's active execution lease.");
      const hash = createHash("sha256").update(`${input.repoId}\0${idempotencyKey}`).digest("hex"), dispatchId = `dispatch_${hash.slice(0, 24)}`, runtimeSessionId = `runtime_${hash.slice(24, 48)}`, dispatchOpId = `runtime-spawn-${hash.slice(0, 32)}`, existing = input.store.readEvent(dispatchOpId); if (existing) return applied(dispatchOpId, runtimeSessionId, dispatchId, input.store.read().revision);
      const process = launch({ kindId, installation: witnessed, cwd, prompt, credential }); try { const events: AgentRuntimeEventV1[] = [];
        events.push(event("runtime_dispatch_requested", { dispatchId, runtimeSessionId, kindId, idempotencyKey, definitionSnapshotRef: `artifact:runtime-profile/${kindId}/${profileId}` }, dispatchOpId, binding, input.store.read().revision + 1));
        events.push(event("runtime_session_started", { runtimeSessionId, installationId, kindId, launchGeneration: input.daemonGeneration, attachable: false }, `${dispatchOpId}:started`, binding, events.at(-1)!.workspaceRevision + 1));
        if (taskId && lease) { const providerSessionId = `local-process-${process.pid}`, transcriptRef = `provider:local-process/${runtimeSessionId}`; events.push(event("runtime_session_provider_bound", { runtimeSessionId, providerSessionId, transcriptRef }, `${dispatchOpId}:provider`, binding, events.at(-1)!.workspaceRevision + 1)); events.push(event("runtime_session_task_bound", { runtimeSessionId, taskId, executionId: lease.executionId, providerSessionId, transcriptRef }, `${dispatchOpId}:task`, binding, events.at(-1)!.workspaceRevision + 1)); }
        for (const value of events) { input.store.append({ event: value, plan: canonicalEventWritePlan(value, "agent-runtime/v1", value.opId), blobs: [] }); input.projection.apply(value); }
      } catch (error) { process.terminate(); throw error; }
      processes.set(runtimeSessionId, process); process.onExit((code) => { if (processes.get(runtimeSessionId) === process) input.schedule(() => publishExit(runtimeSessionId, dispatchOpId, binding, code)); });
      return applied(dispatchOpId, runtimeSessionId, dispatchId, input.store.read().revision);
    },
    close: () => { const active = [...processes.values()]; processes.clear(); for (const process of active) process.terminate(); }
  };
  function publishExit(runtimeSessionId: string, opId: string, binding: { readonly actor: ActorIdentity; readonly source: WriteSource }, code: number | null): void { if (input.store.readEvent(`${opId}:exited`)) return; const revision = input.store.read().revision + 1, exited = event("runtime_session_exited", { runtimeSessionId }, `${opId}:exited`, binding, revision), outcome = event("runtime_session_outcome_observed", { runtimeSessionId, outcome: code === 0 ? "succeeded" : code === null ? "unknown" : "failed", resultRef: `provider:local-process/${runtimeSessionId}/exit/${code ?? "unknown"}` }, `${opId}:outcome`, binding, revision + 1); for (const value of [exited, outcome]) { input.store.append({ event: value, plan: canonicalEventWritePlan(value, "agent-runtime/v1", value.opId), blobs: [] }); input.projection.apply(value); } processes.delete(runtimeSessionId); }
  function applied(opId: string, runtimeSessionId: string, dispatchId: string, revision: number) { return { schema: "command-receipt/v2", ok: true, command: "runtime-spawn", outcome: "applied" as const, opId, runtimeSessionId, dispatchId, revision, evidence: `event-object:${opId}`, visibility: "center" as const, proof: { committedRevision: revision, appliedCut: revision, durable: true, canonicalVisible: true, worktreeVisible: null }, nextAction: null }; }
  function event<T extends AgentRuntimeEventV1["type"]>(type: T, payload: Extract<AgentRuntimeEventV1, { readonly type: T }>["payload"], opId: string, binding: { readonly actor: ActorIdentity; readonly source: WriteSource }, workspaceRevision: number): AgentRuntimeEventV1 { return { schema: "agent-runtime-event/v1", eventId: `event-${createHash("sha256").update(opId).digest("hex")}`, workspaceRevision, opId, type, actor: binding.actor, source: binding.source, occurredAt: input.now(), payload } as AgentRuntimeEventV1; }
}
function launchNative(input: { readonly kindId: "claude" | "codex"; readonly installation: RuntimeInstallationWitness; readonly cwd: string; readonly prompt: string; readonly credential: RuntimeCredentialBinding | null }): RuntimeProcess { const args = input.kindId === "codex" ? ["exec", "-"] : ["-p"], child = spawn(input.installation.executablePath, args, { cwd: input.cwd, stdio: ["pipe", "ignore", "ignore"], windowsHide: true, env: runtimeEnvironment(input.kindId, input.credential) }); child.stdin.end(input.prompt); return { pid: child.pid ?? 0, onExit: (listener) => { child.once("exit", listener); child.once("error", () => listener(null)); }, terminate: () => { if (!child.killed) child.kill("SIGTERM"); } }; }
function runtimeEnvironment(kindId: "claude" | "codex", binding: RuntimeCredentialBinding | null): NodeJS.ProcessEnv { const result: NodeJS.ProcessEnv = {}; for (const key of ["PATH", "HOME", "LANG", "LC_ALL", "TMPDIR"]) if (process.env[key]) result[key] = process.env[key]; if (!binding) return result; const secret = resolveKeychain(binding.credentialRef), key = kindId === "claude" ? "ANTHROPIC_API_KEY" : "OPENAI_API_KEY", base = kindId === "claude" ? "ANTHROPIC_BASE_URL" : "OPENAI_BASE_URL"; result[key] = secret; if (binding.baseUrl) result[base] = binding.baseUrl; return result; }
function resolveKeychain(reference: string): string { if (process.platform !== "darwin") throw coded("secure_prompt_unavailable", "Native credential resolution is unavailable on this platform."); const [service, account, ...extra] = reference.slice("keychain:".length).split("/"); if (!service || !account || extra.length) throw coded("invalid_credential_reference", "Native credential reference is invalid."); try { const secret = execFileSync("/usr/bin/security", ["find-generic-password", "-w", "-s", service, "-a", account], { encoding: "utf8", stdio: ["ignore", "pipe", "ignore"] }).replace(/[\r\n]+$/u, ""); if (secret) return secret; } catch (error) { consumeKnownError(error); } throw coded("runtime_credential_unavailable", "The native runtime credential could not be resolved."); }
function resolveCwd(root: string, value: unknown): string { if (!value || typeof value !== "object" || Array.isArray(value)) throw coded("invalid_runtime_cwd", "cwd requires a closed scope object."); const cwd = value as Record<string, unknown>, allowed = cwd.scope === "repo-root" ? ["scope"] : ["scope", "path"]; if (Object.keys(cwd).some((key) => !allowed.includes(key)) || !["repo-root", "repo-relative"].includes(String(cwd.scope))) throw coded("invalid_runtime_cwd", "Runtime cwd scope is invalid."); const resolved = cwd.scope === "repo-root" ? root : path.resolve(root, required(cwd.path, "cwd.path")); if (resolved !== root && !resolved.startsWith(`${root}${path.sep}`)) throw coded("invalid_runtime_cwd", "Runtime cwd must stay inside the repository."); return resolved; }
function enumValue<const T extends string>(value: unknown, allowed: readonly T[], field: string): T { if (allowed.includes(value as T)) return value as T; throw coded("invalid_runtime_spawn", `${field} is invalid.`); }
function required(value: unknown, field: string): string { if (typeof value === "string" && value.length) return value; throw coded("invalid_runtime_spawn", `${field} is required.`); }
function coded(code: string, message: string): Error { return Object.assign(new Error(message), { code }); }
function consumeKnownError(error: unknown): void { void error; }
