import { spawn } from "node:child_process";
import { createHash } from "node:crypto";
import path from "node:path";
import { canonicalEventWritePlan, consumeKnownError } from "../../kernel/src/index.ts";
import type { ActorIdentity, AgentRuntimeEventV1, CanonicalContentBlob, CanonicalEventStore, RuntimeResultClaim, TaskProjection, WriteSource } from "../../kernel/src/index.ts";
import type { AgentRuntimeNativeSignal, AgentRuntimeStreamHub } from "./agent-runtime-stream.ts";
import type { JsonObject } from "./protocol/json-rpc-types.ts";
import type { PreparedRuntimeLaunch, RuntimeInstanceKind } from "./agent-runtime-instances.ts";
import { archiveRuntimeDispatch } from "./doc-sync-actions.ts";

export interface RuntimeProcess { readonly pid: number; readonly onOutput: (listener: (chunk: string) => void) => void; readonly onExit: (listener: (code: number | null) => void) => void; readonly terminate: () => void }
export type RuntimeLauncher = (input: PreparedRuntimeLaunch) => RuntimeProcess;
type RuntimeBinding = { readonly actor: ActorIdentity; readonly source: WriteSource };
type ActiveRuntime = { readonly process: RuntimeProcess; readonly dispatchId: string; readonly runtimeSessionId: string; readonly dispatchOpId: string; readonly instanceId: string; readonly kindId: RuntimeInstanceKind; readonly binding: RuntimeBinding; readonly task: { readonly taskId: string; readonly executionId: string } | null; readonly cwd: string; readonly prompt: string; readonly promptSource?: string; readonly model: string; readonly reasoningEffort: string | null; readonly startedAt: string; buffer: string; providerSessionId: string | null; resumeProviderSessionId: string | null; finalText: string | null; providerOutcome: "succeeded" | "failed" | null; protocolError: boolean; cancelRequested: boolean; cancelBinding: RuntimeBinding | null };
type ProviderFrame = { readonly providerSessionId?: string; readonly signals?: readonly AgentRuntimeNativeSignal[]; readonly finalText?: string; readonly outcome?: "succeeded" | "failed" };
const resultMediaType = "text/plain; charset=utf-8" as const;

export function makeRuntimeSpawner(input: { readonly repoId: string; readonly rootDir: string; readonly daemonGeneration: number; readonly store: () => CanonicalEventStore; readonly projection: () => TaskProjection; readonly stream: Pick<AgentRuntimeStreamHub, "publish">; readonly now: () => string; readonly prepareLaunch: (instanceId: string, request: { readonly cwd: string; readonly prompt: string; readonly providerSessionId?: string }) => PreparedRuntimeLaunch; readonly launch?: RuntimeLauncher; readonly schedule: (work: () => void) => void }) {
  const processes = new Map<string, ActiveRuntime>(), launch = input.launch ?? launchNative;
  return {
    spawn: (payload: JsonObject, binding: RuntimeBinding) => {
      const allowed = ["runtimeInstanceId", "cwd", "prompt", "promptSource", "taskId", "idempotencyKey", "providerSessionId"]; if (Object.keys(payload).some((key) => !allowed.includes(key))) throw runtimeSpawnError("invalid_runtime_spawn", "Runtime spawn payload contains an unknown field.");
      const runtimeInstanceId = requiredRuntimeSpawnText(payload.runtimeInstanceId, "runtimeInstanceId"), prompt = requiredRuntimeSpawnText(payload.prompt, "prompt"), promptSource = payload.promptSource === undefined ? undefined : requiredRuntimeSpawnText(payload.promptSource, "promptSource"), idempotencyKey = requiredRuntimeSpawnText(payload.idempotencyKey, "idempotencyKey"), taskId = payload.taskId === null ? null : requiredRuntimeSpawnText(payload.taskId, "taskId"), providerSessionId = payload.providerSessionId === undefined ? undefined : requiredRuntimeSpawnText(payload.providerSessionId, "providerSessionId");
      const cwd = resolveRuntimeCwd(input.rootDir, payload.cwd), store = input.store(), projection = input.projection(), lease = taskId ? projection.currentLease(taskId) : null; if (taskId && (!lease || lease.phase !== "held" || lease.actor.principal.personId !== binding.actor.principal.personId || lease.actor.executor?.id !== binding.actor.executor?.id)) throw runtimeSpawnError("runtime_task_lease_required", "Task-bound runtime spawn requires the caller's active execution lease.");
      const hash = createHash("sha256").update(`${input.repoId}\0${idempotencyKey}`).digest("hex"), dispatchId = `dispatch_${hash.slice(0, 24)}`, runtimeSessionId = `runtime_${hash.slice(24, 48)}`, dispatchOpId = `runtime-spawn-${hash.slice(0, 32)}`, existing = store.readEvent(dispatchOpId); if (existing) return applied(dispatchOpId, runtimeSessionId, dispatchId, store.readHead()?.revision ?? 0);
      const prepared = input.prepareLaunch(runtimeInstanceId, { cwd, prompt, ...(providerSessionId ? { providerSessionId } : {}) }), definition = prepared.definition, installation = prepared.installation; if (definition.instanceId !== runtimeInstanceId || definition.installationId !== installation.installationId || definition.kindId !== installation.kindId || prepared.executablePath !== installation.executablePath || prepared.cwd !== cwd || prepared.prompt !== prompt) throw runtimeSpawnError("invalid_runtime_launch", "Prepared runtime launch does not match the closed spawn request."); const definitionSnapshotRef = `artifact:runtime-definition/${createHash("sha256").update(JSON.stringify(definition)).digest("hex")}`, protocolFamily = definition.kindId === "claude" ? "claude-compatible" as const : "codex" as const;
      publishRuntimeEvent(event("runtime_installation_observed", { installationId: installation.installationId, kindId: protocolFamily, protocolFamily, hostRef: "host:local", version: installation.version, discoverySource: "wrapper", capabilities: ["structured_witness", "resume", "attach"] }, `${dispatchOpId}:installation`, binding, (store.readHead()?.revision ?? 0) + 1));
      publishRuntimeEvent(event("runtime_dispatch_requested", { dispatchId, runtimeSessionId, instanceId: definition.instanceId, installationId: definition.installationId, kindId: definition.kindId, idempotencyKey, definitionSnapshotRef, definitionSnapshot: definition }, dispatchOpId, binding, (store.readHead()?.revision ?? 0) + 1));
      let process: RuntimeProcess; try { process = launch(prepared); } catch (error) { publishRuntimeEvent(event("runtime_dispatch_outcome_unknown", { dispatchId, runtimeSessionId }, `${dispatchOpId}:outcome-unknown`, binding, (store.readHead()?.revision ?? 0) + 1)); throw error; }
      const started = event("runtime_session_started", { runtimeSessionId, instanceId: definition.instanceId, installationId: definition.installationId, kindId: definition.kindId, definitionSnapshotRef, launchGeneration: input.daemonGeneration, attachable: true }, `${dispatchOpId}:started`, binding, (store.readHead()?.revision ?? 0) + 1); try { publishRuntimeEvent(started); }
      catch (error) { process.terminate(); throw error; }
      const active: ActiveRuntime = { process, dispatchId, runtimeSessionId, dispatchOpId, instanceId: definition.instanceId, kindId: definition.kindId, binding, task: taskId && lease ? { taskId, executionId: lease.executionId } : null, cwd, prompt, ...(promptSource ? { promptSource } : {}), model: definition.model, reasoningEffort: definition.reasoningEffort, startedAt: started.occurredAt, buffer: "", providerSessionId: null, resumeProviderSessionId: providerSessionId ?? null, finalText: null, providerOutcome: null, protocolError: false, cancelRequested: false, cancelBinding: null }; processes.set(runtimeSessionId, active);
      process.onOutput((chunk) => { if (processes.get(runtimeSessionId) === active) input.schedule(() => { if (processes.get(runtimeSessionId) === active) consumeChunk(active, chunk, false); }); }); process.onExit((code) => { if (processes.get(runtimeSessionId) === active) input.schedule(() => { if (processes.get(runtimeSessionId) !== active) return; consumeChunk(active, "", true); publishExit(active, code); }); });
      return applied(dispatchOpId, runtimeSessionId, dispatchId, store.readHead()?.revision ?? 0);
    },
    cancel: (payload: JsonObject, binding: RuntimeBinding) => { const allowed = ["runtimeSessionId"]; if (Object.keys(payload).some((key) => !allowed.includes(key))) throw runtimeSpawnError("invalid_runtime_cancel", "Runtime cancel payload contains an unknown field."); const runtimeSessionId = requiredRuntimeSpawnText(payload.runtimeSessionId, "runtimeSessionId"), hash = createHash("sha256").update(`${input.repoId}\0${runtimeSessionId}`).digest("hex"), opId = `runtime-cancel-${hash.slice(0, 32)}`, active = processes.get(runtimeSessionId); if (active) { active.cancelBinding = binding; active.cancelRequested = true; terminateActive(active, true); return controlApplied(opId, runtimeSessionId); } return controlApplied(opId, runtimeSessionId, "already-exited"); },
    close: () => { const active = [...processes.values()]; processes.clear(); for (const entry of active) terminateActive(entry, false); }
  };
  function publishRuntimeEvent(value: AgentRuntimeEventV1, blobs: readonly CanonicalContentBlob[] = []): void { const store = input.store(), projection = input.projection(); store.append({ event: value, plan: canonicalEventWritePlan(value, "agent-runtime/v1", value.opId), blobs }); projection.apply(value); }
  function consumeChunk(active: ActiveRuntime, chunk: string, flush: boolean): void { active.buffer += chunk; const lines = active.buffer.split(/\r?\n/u); active.buffer = flush ? "" : lines.pop() ?? ""; for (const line of lines) if (line.trim()) consumeLine(active, line); if (flush && active.buffer.trim()) consumeLine(active, active.buffer); }
  function consumeLine(active: ActiveRuntime, line: string): void { let parsed: ProviderFrame; try { parsed = parseProviderFrame(active.kindId, JSON.parse(line)); } catch (error) { consumeKnownError(error); markProtocolError(active); return; } if (parsed.providerSessionId) bindProvider(active, parsed.providerSessionId); for (const signal of parsed.signals ?? []) input.stream.publish(active.runtimeSessionId, signal); if (parsed.finalText !== undefined) active.finalText = parsed.finalText; if (parsed.outcome) active.providerOutcome = parsed.outcome; }
  function bindProvider(active: ActiveRuntime, providerSessionId: string): void { if (active.resumeProviderSessionId !== null && active.resumeProviderSessionId !== providerSessionId) { markProtocolError(active); return; } if (active.providerSessionId === providerSessionId) return; if (active.providerSessionId !== null) { markProtocolError(active); return; } active.providerSessionId = providerSessionId; const transcriptRef = `provider:${active.kindId}/${encodeURIComponent(providerSessionId)}`, store = input.store(); publishRuntimeEvent(event("runtime_session_provider_bound", { runtimeSessionId: active.runtimeSessionId, providerSessionId, transcriptRef }, `${active.dispatchOpId}:provider`, active.binding, (store.readHead()?.revision ?? 0) + 1)); if (active.task) publishRuntimeEvent(event("runtime_session_task_bound", { runtimeSessionId: active.runtimeSessionId, ...active.task, providerSessionId, transcriptRef }, `${active.dispatchOpId}:task`, active.binding, (input.store().readHead()?.revision ?? 0) + 1)); }
  function markProtocolError(active: ActiveRuntime): void { if (active.protocolError) return; active.protocolError = true; input.stream.publish(active.runtimeSessionId, { type: "error", code: "provider_protocol_error" }); }
  function terminateActive(active: ActiveRuntime, cancelled: boolean): void { if (cancelled) active.cancelRequested = true; active.process.terminate(); if (cancelled) publishExit(active, null); }
  function publishExit(active: ActiveRuntime, code: number | null): void { const store = input.store(); if (store.readEvent(`${active.dispatchOpId}:exited`)) return; const cancelled = active.cancelRequested, eventBinding = cancelled && active.cancelBinding ? active.cancelBinding : active.binding; if (!cancelled && code === null) input.stream.publish(active.runtimeSessionId, { type: "error", code: "provider_disconnected" }); if (!cancelled && (active.providerSessionId === null || code === 0 && (active.finalText === null || active.providerOutcome === null))) markProtocolError(active); let outcome = cancelled ? "cancelled" as const : code === null || active.protocolError ? "unknown" as const : code !== 0 ? "failed" as const : active.providerOutcome ?? "unknown" as const; const body = active.finalText ?? "", sha256 = createHash("sha256").update(body).digest("hex"), result: RuntimeResultClaim = { sha256, size: Buffer.byteLength(body), mediaType: resultMediaType }, resultRef = `artifact:runtime-result/sha256/${sha256}`, endedAt = input.now(); if (active.task) try { const archived = archiveRuntimeDispatch({ workspaceId: input.repoId, rootDir: input.rootDir, store, projection: input.projection(), binding: active.binding, now: input.now, archive: { dispatchId: active.dispatchId, ...active.task, instanceId: active.instanceId, model: active.model, reasoningEffort: active.reasoningEffort, cwd: active.cwd, prompt: active.prompt, ...(active.promptSource ? { promptSource: active.promptSource } : {}), runtimeSessionId: active.runtimeSessionId, providerSessionId: active.providerSessionId, startedAt: active.startedAt, endedAt, outcome, exitCode: cancelled ? null : code, resultRef, resultText: body } }); if (archived.outcome !== "applied") throw runtimeSpawnError("runtime_archive_failed", archived.nextAction ?? `Runtime archive ${active.dispatchId} was not applied.`); } catch (error) { consumeKnownError(error); outcome = "unknown"; } input.stream.publish(active.runtimeSessionId, { type: "exit", outcome }); let revision = (store.readHead()?.revision ?? 0) + 1; if (cancelled) { publishRuntimeEvent(event("runtime_session_cancelled", { runtimeSessionId: active.runtimeSessionId }, `${active.dispatchOpId}:cancelled`, eventBinding, revision)); revision += 1; } const exited = event("runtime_session_exited", { runtimeSessionId: active.runtimeSessionId }, `${active.dispatchOpId}:exited`, eventBinding, revision), observed = event("runtime_session_outcome_observed", { runtimeSessionId: active.runtimeSessionId, outcome, exitCode: cancelled ? null : code, resultRef, result }, `${active.dispatchOpId}:outcome`, eventBinding, revision + 1); publishRuntimeEvent(exited); publishRuntimeEvent(observed, [{ ...result, body }]); processes.delete(active.runtimeSessionId); }
  function applied(opId: string, runtimeSessionId: string, dispatchId: string, revision: number) { return { schema: "command-receipt/v2", ok: true, command: "runtime-spawn", outcome: "applied" as const, opId, runtimeSessionId, dispatchId, revision, evidence: `event-object:${opId}`, visibility: "center" as const, proof: { committedRevision: revision, appliedCut: revision, durable: true, canonicalVisible: true, worktreeVisible: null }, nextAction: null }; }
  function controlApplied(opId: string, runtimeSessionId: string, detail = "cancelled") { const revision = input.store().readHead()?.revision ?? 0; return { schema: "command-receipt/v2", ok: true, command: "runtime-cancel", outcome: "applied" as const, opId, runtimeSessionId, revision, evidence: `runtime-cancel:${detail}:${runtimeSessionId}`, visibility: "center" as const, proof: { committedRevision: revision, appliedCut: revision, durable: true, canonicalVisible: true, worktreeVisible: null }, nextAction: null, detail }; }
  function event<T extends AgentRuntimeEventV1["type"]>(type: T, payload: Extract<AgentRuntimeEventV1, { readonly type: T }>["payload"], opId: string, binding: RuntimeBinding, workspaceRevision: number): AgentRuntimeEventV1 { return { schema: "agent-runtime-event/v1", eventId: `event-${createHash("sha256").update(opId).digest("hex")}`, workspaceRevision, opId, type, actor: binding.actor, source: binding.source, occurredAt: input.now(), payload } as AgentRuntimeEventV1; }
}
function launchNative(input: PreparedRuntimeLaunch): RuntimeProcess { const child = spawn(input.executablePath, input.args, { cwd: input.cwd, stdio: ["pipe", "pipe", "ignore"], windowsHide: true, env: input.env }); child.stdout.setEncoding("utf8"); child.stdin.end(input.prompt); return { pid: child.pid ?? 0, onOutput: (listener) => { child.stdout.on("data", listener); }, onExit: (listener) => { child.once("close", listener); child.once("error", () => listener(null)); }, terminate: () => { if (!child.killed) child.kill("SIGTERM"); } }; }
function parseProviderFrame(kindId: RuntimeInstanceKind, value: unknown): ProviderFrame { if (!isPlainRecord(value) || typeof value.type !== "string") throw new Error("provider frame is not a structured event"); return kindId === "claude" ? parseClaudeFrame(value) : parseCodexFrame(value); }
function parseClaudeFrame(value: Record<string, unknown>): ProviderFrame { const providerSessionId = typeof value.session_id === "string" && value.session_id ? value.session_id : undefined; if (value.type === "system" && value.subtype === "init" && !providerSessionId || value.type === "result" && (typeof value.result !== "string" || !providerSessionId)) throw new Error("Claude frame is incomplete"); if (value.type === "assistant") { const message = isPlainRecord(value.message) ? value.message : null, content = message && Array.isArray(message.content) ? message.content : null; if (!content) throw new Error("Claude assistant frame is incomplete"); return { ...(providerSessionId ? { providerSessionId } : {}), signals: content.flatMap(claudeContent) }; } if (value.type === "result") return { providerSessionId, finalText: value.result as string, outcome: value.is_error === false && value.subtype === "success" ? "succeeded" : "failed" }; return providerSessionId ? { providerSessionId } : {}; }
function claudeContent(value: unknown): readonly AgentRuntimeNativeSignal[] { if (!isPlainRecord(value) || typeof value.type !== "string") return []; if (value.type === "text" && typeof value.text === "string") return [{ type: "activity", activity: "message", content: value.text }]; if (value.type === "thinking" && typeof value.thinking === "string") return [{ type: "activity", activity: "thinking", content: value.thinking }]; if (["tool_use", "tool_result", "server_tool_use", "web_search_tool_result"].includes(value.type)) return [{ type: "activity", activity: "tool", content: JSON.stringify(value) }]; return []; }
function parseCodexFrame(value: Record<string, unknown>): ProviderFrame { if (value.type === "thread.started") { const providerSessionId = value.thread_id; if (typeof providerSessionId !== "string" || !providerSessionId) throw new Error("Codex thread frame is incomplete"); return { providerSessionId }; } if (value.type === "item.completed") { const item = value.item; if (!isPlainRecord(item) || typeof item.type !== "string") throw new Error("Codex item frame is incomplete"); const itemType = item.type; if (itemType === "agent_message") { const text = item.text; if (typeof text !== "string") throw new Error("Codex message frame is incomplete"); return { signals: [{ type: "activity", activity: "message", content: text }], finalText: text }; } if (itemType === "reasoning") { const text = item.text; if (typeof text === "string") return { signals: [{ type: "activity", activity: "thinking", content: text }] }; } if (itemType === "error") { const message = item.message; if (typeof message === "string") return { signals: [{ type: "activity", activity: "message", content: message }] }; } if (["command_execution", "file_change", "mcp_tool_call", "web_search"].includes(itemType)) return { signals: [{ type: "activity", activity: "tool", content: JSON.stringify(item) }] }; return {}; } if (value.type === "turn.completed") return { outcome: "succeeded" }; if (value.type === "turn.failed") return { outcome: "failed", ...(isPlainRecord(value.error) ? { signals: [{ type: "activity" as const, activity: "message" as const, content: JSON.stringify(value.error) }] } : {}) }; return {}; }
function isPlainRecord(value: unknown): value is Record<string, unknown> { return value !== null && typeof value === "object" && !Array.isArray(value); }
function resolveRuntimeCwd(root: string, value: unknown): string { if (!value || typeof value !== "object" || Array.isArray(value)) throw runtimeSpawnError("invalid_runtime_cwd", "cwd requires a closed scope object."); const cwd = value as Record<string, unknown>, allowed = cwd.scope === "repo-root" ? ["scope"] : ["scope", "path"]; if (Object.keys(cwd).some((key) => !allowed.includes(key)) || !["repo-root", "repo-relative"].includes(String(cwd.scope))) throw runtimeSpawnError("invalid_runtime_cwd", "Runtime cwd scope is invalid."); const resolved = cwd.scope === "repo-root" ? root : path.resolve(root, requiredRuntimeSpawnText(cwd.path, "cwd.path")); if (resolved !== root && !resolved.startsWith(`${root}${path.sep}`)) throw runtimeSpawnError("invalid_runtime_cwd", "Runtime cwd must stay inside the repository."); return resolved; }
function requiredRuntimeSpawnText(value: unknown, field: string): string { if (typeof value === "string" && value.length) return value; throw runtimeSpawnError("invalid_runtime_spawn", `${field} is required.`); }
function runtimeSpawnError(code: string, message: string): Error { return Object.assign(new Error(message), { code }); }
