import { createHash, randomUUID } from "node:crypto";
import path from "node:path";
import * as pty from "node-pty";
import type { JsonObject } from "./protocol/json-rpc-types.ts";
import type { TerminalAttachSubscription, TerminalControlReceipt, TerminalSessionRow } from "./gui-s3-control.ts";

const scrollbackLimit = 1024 * 1024, replayLimit = 256 * 1024, subscriberLimit = 256 * 1024;
type Frame = JsonObject & { readonly schema: "terminal-attach-event/v1"; readonly sessionId: string; readonly seq: number; readonly kind: "output" | "gap" | "exit"; readonly utf8: string; readonly droppedThrough: number | null; readonly occurredAt: string };
type Session = { readonly sessionId: string; readonly name: string; readonly cwd: string; readonly shellProfile: string; readonly createdAt: string; readonly child: pty.IPty; running: boolean; lastActivityAt: string; exitCode: number | null; exitPublished: boolean; outputSeq: number; acceptedThrough: number; frames: Frame[]; frameBytes: number; readonly subscribers: Map<string, Subscriber> };
type Subscriber = { readonly id: string; readonly queue: Frame[]; bytes: number; waiter: ((frame: Frame | null) => void) | null; closed: boolean };
export interface TerminalHost {
  readonly list: () => JsonObject; readonly spawn: (payload: JsonObject) => TerminalControlReceipt; readonly input: (payload: JsonObject) => JsonObject; readonly resize: (payload: JsonObject) => TerminalControlReceipt; readonly detach: (payload: JsonObject) => JsonObject; readonly terminate: (payload: JsonObject) => TerminalControlReceipt; readonly attach: (sessionId: string, afterSeq: number) => TerminalAttachSubscription; readonly close: () => Promise<void>;
}
export function openTerminalHost(input: { readonly repoId: string; readonly rootDir: string; readonly daemonGeneration: number; readonly now?: () => string }): TerminalHost {
  const sessions = new Map<string, Session>(), idempotency = new Map<string, string>(), now = input.now ?? (() => new Date().toISOString());
  const list = (): JsonObject => ({ schema: "terminal-session-list/v1", ok: true, repoId: input.repoId, daemonGeneration: input.daemonGeneration, sessions: [...sessions.values()].map((session) => ({ ...row(session), repoId: input.repoId })).sort((a, b) => a.createdAt.localeCompare(b.createdAt)) });
  const spawnTerminal = (payload: JsonObject): TerminalControlReceipt => {
    const key = required(payload.idempotencyKey, "idempotencyKey"), existing = idempotency.get(key); if (existing) return control("applied", existing, "running", key);
    const cwd = resolveCwd(input.rootDir, payload.cwd), profile = optional(payload.shellProfileId) ?? "default", command = shell(profile), sessionId = `terminal_${createHash("sha256").update(`${input.repoId}\0${key}`).digest("hex").slice(0, 24)}`, createdAt = now();
    const child = pty.spawn(command, [], { name: "xterm-256color", cols: 80, rows: 24, cwd, env: terminalEnvironment() });
    const session: Session = { sessionId, name: optional(payload.name) ?? "Terminal", cwd: path.relative(input.rootDir, cwd) || ".", shellProfile: profile, createdAt, child, running: true, lastActivityAt: createdAt, exitCode: null, exitPublished: false, outputSeq: 0, acceptedThrough: 0, frames: [], frameBytes: 0, subscribers: new Map() };
    sessions.set(sessionId, session); idempotency.set(key, sessionId);
    child.onData((utf8) => publish(session, "output", utf8, null)); child.onExit(({ exitCode }) => { session.running = false; session.exitCode = exitCode; if (!session.exitPublished) { session.exitPublished = true; publish(session, "exit", "", null); } });
    return control("applied", sessionId, "running", key);
  };
  const attach = (sessionId: string, afterSeq: number): TerminalAttachSubscription => {
    const session = requiredSession(sessionId), attachmentId = `attach_${randomUUID()}`, subscriber: Subscriber = { id: attachmentId, queue: [], bytes: 0, waiter: null, closed: false }, earliest = session.frames[0]?.seq ?? session.outputSeq + 1, replayState = afterSeq < earliest - 1 ? "gap" : "attached";
    if (replayState === "gap") subscriber.queue.push({ schema: "terminal-attach-event/v1", sessionId, seq: earliest - 1, kind: "gap", utf8: "", droppedThrough: earliest - 1, occurredAt: now() });
    const selected: Frame[] = []; let bytes = 0; for (const item of session.frames.filter((candidate) => candidate.seq > afterSeq).reverse()) { const size = frameSize(item); if (bytes + size > replayLimit) break; selected.unshift(item); bytes += size; } subscriber.queue.push(...selected); subscriber.bytes = subscriber.queue.reduce((total, item) => total + frameSize(item), 0); session.subscribers.set(attachmentId, subscriber);
    return { initial: { schema: "terminal-attach/v1", ok: true, sessionId, attachmentId, daemonGeneration: input.daemonGeneration, status: replayState, replayFromSeq: selected[0]?.seq ?? session.outputSeq + 1, outputSeq: session.outputSeq }, next: () => next(subscriber), detach: () => detachSubscriber(session, subscriber) };
  };
  return {
    list, spawn: spawnTerminal, attach,
    input: (payload) => { const session = requiredSession(required(payload.sessionId, "sessionId")), clientSeq = positiveInteger(payload.clientSeq, "clientSeq"), utf8 = required(payload.utf8, "utf8"); if (!session.running) throw coded("terminal_exited", "Terminal session has exited."); if (clientSeq > session.acceptedThrough + 1) throw coded("terminal_input_gap", `Expected clientSeq ${session.acceptedThrough + 1}.`); if (clientSeq > session.acceptedThrough) { session.child.write(utf8); session.acceptedThrough = clientSeq; session.lastActivityAt = now(); } return { schema: "terminal-input-ack/v1", ok: true, sessionId: session.sessionId, acceptedThrough: session.acceptedThrough }; },
    resize: (payload) => { const session = requiredSession(required(payload.sessionId, "sessionId")); if (!session.running) return control("rejected", session.sessionId, "exited", String(payload.sessionId), "terminal_exited", "Start a new terminal session."); session.child.resize(dimension(payload.cols, "cols"), dimension(payload.rows, "rows")); session.lastActivityAt = now(); return control("applied", session.sessionId, "running", `${session.sessionId}:resize:${payload.cols}x${payload.rows}`); },
    detach: (payload) => { const session = requiredSession(required(payload.sessionId, "sessionId")), attachmentId = required(payload.attachmentId, "attachmentId"), subscriber = session.subscribers.get(attachmentId); if (!subscriber) throw coded("terminal_attachment_unknown", "Terminal attachment is not active."); detachSubscriber(session, subscriber); return { schema: "terminal-detach-ack/v1", ok: true, sessionId: session.sessionId, attachmentId, state: "detached" }; },
    terminate: (payload) => { const session = requiredSession(required(payload.sessionId, "sessionId")); if (payload.confirmed !== true) return control("rejected", session.sessionId, terminalState(session), `${session.sessionId}:terminate`, "confirmation_required", "Confirm terminal termination explicitly."); if (session.running) { session.running = false; session.exitPublished = true; session.child.kill(); publish(session, "exit", "", null); } return control("applied", session.sessionId, "exited", `${session.sessionId}:terminate`); },
    close: async () => { for (const session of sessions.values()) { for (const subscriber of session.subscribers.values()) detachSubscriber(session, subscriber); if (session.running) session.child.kill(); } sessions.clear(); }
  };
  function publish(session: Session, kind: Frame["kind"], utf8: string, droppedThrough: number | null): void { const item = frame(session, kind, utf8, droppedThrough); session.lastActivityAt = item.occurredAt; session.frames.push(item); session.frameBytes += frameSize(item); while (session.frameBytes > scrollbackLimit && session.frames.length > 1) session.frameBytes -= frameSize(session.frames.shift()!); for (const subscriber of session.subscribers.values()) push(subscriber, item); }
  function frame(session: Session, kind: Frame["kind"], utf8: string, droppedThrough: number | null): Frame { session.outputSeq += 1; return { schema: "terminal-attach-event/v1", sessionId: session.sessionId, seq: session.outputSeq, kind, utf8, droppedThrough, occurredAt: now() }; }
  function push(subscriber: Subscriber, item: Frame): void { if (subscriber.closed) return; if (subscriber.waiter) { const waiter = subscriber.waiter; subscriber.waiter = null; waiter(item); return; } subscriber.queue.push(item); subscriber.bytes += frameSize(item); if (subscriber.bytes <= subscriberLimit) return; const dropped = subscriber.queue.at(-1)?.seq ?? item.seq; subscriber.queue.splice(0); subscriber.bytes = 0; subscriber.queue.push({ ...item, kind: "gap", utf8: "", droppedThrough: dropped }); }
  function control(outcome: "applied" | "rejected", sessionId: string | null, state: string, seed: string, code?: string, hint?: string): TerminalControlReceipt { return { schema: "terminal-control-receipt/v1", ok: outcome === "applied", outcome, operationId: `terminal-op-${createHash("sha256").update(`${input.repoId}\0${seed}`).digest("hex").slice(0, 20)}`, sessionId, daemonGeneration: input.daemonGeneration, state, error: code && hint ? { code, hint } : null }; }
  function requiredSession(sessionId: string): Session { const session = sessions.get(sessionId); if (!session) throw coded("terminal_session_unknown", "This terminal belongs to another repo or daemon generation, or no longer exists."); return session; }
}
function next(subscriber: Subscriber): Promise<Frame | null> { if (subscriber.closed) return Promise.resolve(null); const item = subscriber.queue.shift(); if (item) { subscriber.bytes -= frameSize(item); return Promise.resolve(item); } return new Promise((resolve) => { subscriber.waiter = resolve; }); }
function detachSubscriber(session: Session, subscriber: Subscriber): void { if (subscriber.closed) return; subscriber.closed = true; session.subscribers.delete(subscriber.id); subscriber.waiter?.(null); subscriber.waiter = null; }
function row(session: Session): TerminalSessionRow { return { sessionId: session.sessionId, repoId: "", name: session.name, cwd: session.cwd, shellProfile: session.shellProfile, status: terminalState(session), createdAt: session.createdAt, lastActivityAt: session.lastActivityAt, exitCode: session.exitCode, outputSeq: session.outputSeq, durability: "daemon-process" }; }
function terminalState(session: Session): "running" | "exited" { return session.running ? "running" : "exited"; }
function resolveCwd(rootDir: string, value: unknown): string { if (!value || typeof value !== "object" || Array.isArray(value)) throw coded("invalid_cwd", "cwd requires a closed scope object."); const cwd = value as Record<string, unknown>, allowed = cwd.scope === "repo-root" ? ["scope"] : ["scope", "path"]; if (Object.keys(cwd).some((key) => !allowed.includes(key)) || !["repo-root", "repo-relative"].includes(String(cwd.scope))) throw coded("invalid_cwd", "cwd scope is invalid."); const resolved = cwd.scope === "repo-root" ? rootDir : path.resolve(rootDir, required(cwd.path, "cwd.path")); if (resolved !== rootDir && !resolved.startsWith(`${rootDir}${path.sep}`)) throw coded("invalid_cwd", "cwd must stay inside the repository."); return resolved; }
function shell(profile: string): string { if (process.platform === "win32") { if (profile !== "default" && profile !== "powershell") throw coded("shell_profile_unknown", "Use the default PowerShell profile."); return "powershell.exe"; } const selected = profile === "default" ? path.basename(process.env.SHELL ?? "zsh") : profile; if (!["zsh", "bash", "sh", "fish"].includes(selected)) throw coded("shell_profile_unknown", "Shell profile is not allowlisted."); return `/bin/${selected}`; }
function terminalEnvironment(): Record<string, string> { const result: Record<string, string> = { TERM: "xterm-256color" }; for (const key of ["PATH", "HOME", "LANG", "LC_ALL", "TMPDIR"]) if (process.env[key]) result[key] = process.env[key]!; return result; }
function frameSize(frame: Frame): number { return Buffer.byteLength(frame.utf8, "utf8") + 96; }
function required(value: unknown, field: string): string { if (typeof value === "string" && value.length) return value; throw coded("invalid_terminal_request", `${field} is required.`); }
function optional(value: unknown): string | undefined { return typeof value === "string" && value.length ? value : undefined; }
function positiveInteger(value: unknown, field: string): number { if (Number.isSafeInteger(value) && Number(value) >= 0) return Number(value); throw coded("invalid_terminal_request", `${field} must be a non-negative integer.`); }
function dimension(value: unknown, field: string): number { const result = positiveInteger(value, field); if (result < 2 || result > 500) throw coded("invalid_terminal_request", `${field} must be 2..500.`); return result; }
function coded(code: string, message: string): Error { return Object.assign(new Error(message), { code }); }
