import { useQuery } from "@tanstack/react-query";
import type { ReactNode } from "react";
import { agentEntityClient } from "../agent-entity-client.ts";
import type { AgentEntityRow, SquadEntityRow } from "../agent-entity-client.ts";

export function EntityLayersPanel({ repoId }: { readonly repoId: string }) {
  const agents = useQuery({ queryKey: ["agents", repoId], queryFn: () => agentEntityClient.listAgents(repoId), staleTime: 4_000 });
  const squads = useQuery({ queryKey: ["squads", repoId], queryFn: () => agentEntityClient.listSquads(repoId), staleTime: 4_000 });
  return <EntityLayersRows agents={agents.data ?? []} squads={squads.data ?? []} agentPending={agents.isLoading} squadPending={squads.isLoading} agentError={agents.error} squadError={squads.error} />;
}
export function EntityLayersRows({ agents, squads, agentPending = false, squadPending = false, agentError, squadError }: { readonly agents: readonly AgentEntityRow[]; readonly squads: readonly SquadEntityRow[]; readonly agentPending?: boolean; readonly squadPending?: boolean; readonly agentError?: unknown; readonly squadError?: unknown }) { return <div className="grid gap-4 border-b border-border bg-bg px-4 py-4 lg:grid-cols-2"><EntitySection title="Agents" subtitle="Repository declarations" error={agentError}>{agents.length ? agents.map((agent) => <AgentRow key={agent.id} agent={agent} />) : <Empty label={agentPending ? "Loading agents…" : "No declared agents."} />}</EntitySection><EntitySection title="Squads" subtitle="Repository rosters" error={squadError}>{squads.length ? squads.map((squad) => <SquadRow key={squad.id} squad={squad} />) : <Empty label={squadPending ? "Loading squads…" : "No declared squads."} />}</EntitySection></div>; }
function EntitySection({ title, subtitle, error, children }: { readonly title: string; readonly subtitle: string; readonly error: unknown; readonly children: ReactNode }) { return <section aria-label={title} className="min-w-0"><header className="mb-2 flex items-baseline gap-2 border-b border-border pb-1"><h2 className="ui-title font-semibold">{title}</h2><span className="text-[10px] uppercase text-text-faint">{subtitle}</span></header>{error ? <p className="text-[11px] text-status-blocked">{error instanceof Error ? error.message : String(error)}</p> : <div className="divide-y divide-border">{children}</div>}</section>; }
function AgentRow({ agent }: { readonly agent: AgentEntityRow }) { return <article className="flex items-center gap-3 py-2 text-[12px]"><span className="size-2 rounded-full bg-axis-authority" /><div className="min-w-0 flex-1"><b className="text-text">{agent.name}</b><code className="ml-2 text-[10px] text-text-faint">{agent.id}</code></div><span className="font-mono text-[11px] uppercase text-text-muted">{agent.runtimeType || "unknown"}</span><span className={agent.validity === "valid" ? "text-status-done" : "text-status-blocked"}>{agent.validity}</span></article>; }
function SquadRow({ squad }: { readonly squad: SquadEntityRow }) { return <article className="flex items-center gap-3 py-2 text-[12px]"><span className="size-2 rounded-sm bg-axis-execution" /><div className="min-w-0 flex-1"><b className="text-text">{squad.name}</b><code className="ml-2 text-[10px] text-text-faint">{squad.id}</code><p className="text-[10px] text-text-faint">leader={squad.leader || "—"} · {squad.workers.length} worker{squad.workers.length === 1 ? "" : "s"}</p></div><span className={squad.validity === "valid" ? "text-status-done" : "text-status-blocked"}>{squad.validity}</span></article>; }
function Empty({ label }: { readonly label: string }) { return <p className="py-2 text-[11px] text-text-faint">{label}</p>; }
