import { useState } from "react";
import { useQuery } from "@tanstack/react-query";
import type { ReactNode } from "react";
import { agentEntityClient } from "../agent-entity-client.ts";
import type { AgentEntityDetail, AgentEntityRow, SquadEntityDetail, SquadEntityRow } from "../agent-entity-client.ts";
import { t } from "../i18n/index.tsx";

// One declared-detail pane at a time per kind: the rows stay dense (the list is the
// survey surface), and expanding a row pulls the closed projection the daemon owns —
// the renderer never sees declaration files or host paths.
export interface EntityDetailPane { readonly id: string; readonly pending?: boolean; readonly error?: unknown; readonly agent?: AgentEntityDetail; readonly squad?: SquadEntityDetail }
export function EntityLayersPanel({ repoId, onDispatchAgent, onDispatchSquad }: { readonly repoId: string; readonly onDispatchAgent?: (agent: AgentEntityRow) => void; readonly onDispatchSquad?: (squad: SquadEntityRow) => void }) {
  const agents = useQuery({ queryKey: ["agents", repoId], queryFn: () => agentEntityClient.listAgents(repoId), staleTime: 4_000 });
  const squads = useQuery({ queryKey: ["squads", repoId], queryFn: () => agentEntityClient.listSquads(repoId), staleTime: 4_000 });
  const [openAgentId, setOpenAgentId] = useState<string | null>(null), [openSquadId, setOpenSquadId] = useState<string | null>(null);
  const agentDetail = useQuery({ queryKey: ["agent-entity-detail", repoId, openAgentId], queryFn: () => agentEntityClient.showAgent(repoId, openAgentId ?? ""), enabled: openAgentId !== null, staleTime: 4_000 });
  const squadDetail = useQuery({ queryKey: ["squad-entity-detail", repoId, openSquadId], queryFn: () => agentEntityClient.showSquad(repoId, openSquadId ?? ""), enabled: openSquadId !== null, staleTime: 4_000 });
  return <EntityLayersRows agents={agents.data ?? []} squads={squads.data ?? []} agentPending={agents.isLoading} squadPending={squads.isLoading} agentError={agents.error} squadError={squads.error} openAgentId={openAgentId} openSquadId={openSquadId} onToggleAgent={(id) => setOpenAgentId((current) => current === id ? null : id)} onToggleSquad={(id) => setOpenSquadId((current) => current === id ? null : id)} onDispatchAgent={onDispatchAgent} onDispatchSquad={onDispatchSquad} agentDetail={openAgentId ? { id: openAgentId, pending: agentDetail.isFetching && !agentDetail.data, error: agentDetail.error, ...(agentDetail.data ? { agent: agentDetail.data } : {}) } : null} squadDetail={openSquadId ? { id: openSquadId, pending: squadDetail.isFetching && !squadDetail.data, error: squadDetail.error, ...(squadDetail.data ? { squad: squadDetail.data } : {}) } : null} />;
}
export function EntityLayersRows({ agents, squads, agentPending = false, squadPending = false, agentError, squadError, openAgentId = null, openSquadId = null, onToggleAgent = () => undefined, onToggleSquad = () => undefined, onDispatchAgent, onDispatchSquad, agentDetail = null, squadDetail = null }: { readonly agents: readonly AgentEntityRow[]; readonly squads: readonly SquadEntityRow[]; readonly agentPending?: boolean; readonly squadPending?: boolean; readonly agentError?: unknown; readonly squadError?: unknown; readonly openAgentId?: string | null; readonly openSquadId?: string | null; readonly onToggleAgent?: (agentId: string) => void; readonly onToggleSquad?: (squadId: string) => void; readonly onDispatchAgent?: (agent: AgentEntityRow) => void; readonly onDispatchSquad?: (squad: SquadEntityRow) => void; readonly agentDetail?: EntityDetailPane | null; readonly squadDetail?: EntityDetailPane | null }) { return <div className="grid gap-4 border-b border-border bg-bg px-4 py-4 lg:grid-cols-2"><EntitySection title={t("components.entityLayers.agents")} subtitle={t("components.entityLayers.agentsSubtitle")} error={agentError}>{agents.length ? agents.map((agent) => <AgentRow key={agent.id} agent={agent} open={openAgentId === agent.id} onToggle={() => onToggleAgent(agent.id)} onDispatch={onDispatchAgent && agent.validity === "valid" ? () => onDispatchAgent(agent) : undefined} detail={openAgentId === agent.id ? agentDetail : null} />) : <Empty label={agentPending ? t("components.entityLayers.loadingAgents") : t("components.entityLayers.noAgents")} />}</EntitySection><EntitySection title={t("components.entityLayers.squads")} subtitle={t("components.entityLayers.squadsSubtitle")} error={squadError}>{squads.length ? squads.map((squad) => <SquadRow key={squad.id} squad={squad} open={openSquadId === squad.id} onToggle={() => onToggleSquad(squad.id)} onDispatch={onDispatchSquad && squad.validity === "valid" && squad.workers.length > 0 ? () => onDispatchSquad(squad) : undefined} detail={openSquadId === squad.id ? squadDetail : null} />) : <Empty label={squadPending ? t("components.entityLayers.loadingSquads") : t("components.entityLayers.noSquads")} />}</EntitySection></div>; }
function EntitySection({ title, subtitle, error, children }: { readonly title: string; readonly subtitle: string; readonly error: unknown; readonly children: ReactNode }) { return <section aria-label={title} className="min-w-0"><header className="mb-2 flex items-baseline gap-2 border-b border-border pb-1"><h2 className="ui-title font-semibold">{title}</h2><span className="text-[10px] uppercase text-text-faint">{subtitle}</span></header>{error ? <p className="text-[11px] text-status-blocked">{error instanceof Error ? error.message : String(error)}</p> : <div className="divide-y divide-border">{children}</div>}</section>; }
function AgentRow({ agent, open, onToggle, onDispatch, detail }: { readonly agent: AgentEntityRow; readonly open: boolean; readonly onToggle: () => void; readonly onDispatch?: () => void; readonly detail: EntityDetailPane | null }) { return <article className="py-2 text-[12px]"><div className="flex items-center gap-3"><span className="size-2 rounded-full bg-axis-authority" /><div className="min-w-0 flex-1"><b className="text-text">{agent.name}</b><code className="ml-2 text-[10px] text-text-faint">{agent.id}</code></div><span className="font-mono text-[11px] uppercase text-text-muted">{agent.runtimeType || "unknown"}</span><span className={agent.validity === "valid" ? "text-status-done" : "text-status-blocked"}>{agent.validity}</span><button type="button" aria-expanded={open} onClick={onToggle} className="rounded border border-border px-1.5 py-0.5 text-[10px] text-text-muted hover:border-border-strong">{open ? t("components.entityLayers.collapse") : t("components.entityLayers.declared")}</button>{onDispatch && <button type="button" data-testid={`dispatch-entry-${agent.id}`} onClick={onDispatch} className="rounded border border-accent/50 px-1.5 py-0.5 text-[10px] text-accent hover:bg-accent/10">{t("components.entityLayers.dispatch")}</button>}</div>{open && <AgentDeclaration detail={detail} />}</article>; }
function SquadRow({ squad, open, onToggle, onDispatch, detail }: { readonly squad: SquadEntityRow; readonly open: boolean; readonly onToggle: () => void; readonly onDispatch?: () => void; readonly detail: EntityDetailPane | null }) { return <article className="py-2 text-[12px]"><div className="flex items-center gap-3"><span className="size-2 rounded-sm bg-axis-execution" /><div className="min-w-0 flex-1"><b className="text-text">{squad.name}</b><code className="ml-2 text-[10px] text-text-faint">{squad.id}</code><p className="text-[10px] text-text-faint">leader={squad.leader || "—"} · {squad.workers.length} worker{squad.workers.length === 1 ? "" : "s"}</p></div><span className={squad.validity === "valid" ? "text-status-done" : "text-status-blocked"}>{squad.validity}</span><button type="button" aria-expanded={open} onClick={onToggle} className="rounded border border-border px-1.5 py-0.5 text-[10px] text-text-muted hover:border-border-strong">{open ? t("components.entityLayers.collapse") : t("components.entityLayers.roster")}</button>{onDispatch && <button type="button" data-testid={`squad-dispatch-entry-${squad.id}`} onClick={onDispatch} className="rounded border border-accent/50 px-1.5 py-0.5 text-[10px] text-accent hover:bg-accent/10">{t("components.entityLayers.launchSquad")}</button>}</div>{open && <SquadDeclaration detail={detail} />}</article>; }
function AgentDeclaration({ detail }: { readonly detail: EntityDetailPane | null }) { if (!detail) return <Empty label={t("components.entityLayers.loadingDeclaration")} />; if (detail.error) return <p className="mt-2 text-[11px] text-status-blocked">{detail.error instanceof Error ? detail.error.message : String(detail.error)}</p>; if (detail.pending && !detail.agent) return <Empty label={t("components.entityLayers.loadingDeclaration")} />; const agent = detail.agent; if (!agent) return <Empty label={t("components.entityLayers.loadingDeclaration")} />; return <aside aria-label={t("components.entityLayers.agentDeclaration", { id: agent.id })} className="mt-2 rounded border border-border bg-surface-raised p-2"><dl className="grid grid-cols-2 gap-x-3 gap-y-1 text-[10px]"><DeclaredField name="runtime_type" value={agent.runtimeType || "—"} /><DeclaredField name="preset" value={agent.preset ?? "—"} /><DeclaredField name="skills" value={agent.skills.join(", ") || "—"} /><DeclaredField name="prompts" value={agent.prompts.join(", ") || "—"} /></dl><div className="mt-1"><dt className="font-mono text-[10px] uppercase text-text-faint">instructions</dt><dd><pre className="mt-0.5 max-h-40 overflow-auto whitespace-pre-wrap break-words rounded bg-bg p-1.5 font-mono text-[10px] leading-snug text-text-muted">{agent.instructions}</pre></dd></div></aside>; }
function SquadDeclaration({ detail }: { readonly detail: EntityDetailPane | null }) { if (!detail) return <Empty label={t("components.entityLayers.loadingDeclaration")} />; if (detail.error) return <p className="mt-2 text-[11px] text-status-blocked">{detail.error instanceof Error ? detail.error.message : String(detail.error)}</p>; const squad = detail.squad; if (!squad) return <Empty label={t("components.entityLayers.loadingDeclaration")} />; return <aside aria-label={t("components.entityLayers.squadDeclaration", { id: squad.id })} className="mt-2 rounded border border-border bg-surface-raised p-2"><dl className="grid grid-cols-2 gap-x-3 gap-y-1 text-[10px]"><DeclaredField name="leader" value={squad.leader || "—"} /><DeclaredField name="workers" value={squad.workers.join(", ") || "—"} /></dl><div className="mt-1"><dt className="font-mono text-[10px] uppercase text-text-faint">roster</dt><dd><pre className="mt-0.5 max-h-40 overflow-auto whitespace-pre-wrap break-words rounded bg-bg p-1.5 font-mono text-[10px] leading-snug text-text-muted">{squad.roster}</pre></dd></div></aside>; }
function DeclaredField({ name, value }: { readonly name: string; readonly value: string }) { return <div><dt className="font-mono uppercase text-text-faint">{name}</dt><dd className="break-all text-text-muted">{value}</dd></div>; }
function Empty({ label }: { readonly label: string }) { return <p className="py-2 text-[11px] text-text-faint">{label}</p>; }
