import { useEffect, useState, type FormEvent, type ReactNode } from "react";
import { useMutation, useQuery } from "@tanstack/react-query";
import type { AgentDeclarationV1, SquadDeclarationV1 } from "../../../../daemon/src/agent-entities.contract.ts";
import type { AgentEntityDetail, SquadEntityDetail, EntitySaveResult } from "../agent-entity-client.ts";
import { agentEntityClient } from "../agent-entity-client.ts";
import { t } from "../i18n/index.tsx";

export type EntityAuthoringKind = "agent" | "squad";
type AgentDraft = { id: string; name: string; instructions: string; runtimeType: string; role: string; model: string; skills: string; prompts: string; preset: string };
type SquadDraft = { id: string; name: string; leader: string; workers: string; roster: string };
type Draft = AgentDraft | SquadDraft;
type Errors = Partial<Record<string, string>>;
type Props = { readonly repoId: string; readonly kind: EntityAuthoringKind; readonly entityId: string | null; readonly onClose: () => void; readonly onSaved: () => void };

export function EntityAuthoringDialog({ repoId, kind, entityId, onClose, onSaved }: Props) {
  const detail = useQuery<AgentEntityDetail | SquadEntityDetail>({ queryKey: ["entity-authoring", repoId, kind, entityId], queryFn: async () => kind === "agent" ? agentEntityClient.showAgent(repoId, entityId ?? "") : agentEntityClient.showSquad(repoId, entityId ?? ""), enabled: entityId !== null });
  const [draft, setDraft] = useState<Draft>(() => kind === "agent" ? emptyAgent() : emptySquad()), [errors, setErrors] = useState<Errors>({}), [serverError, setServerError] = useState<string | null>(null), [hydrated, setHydrated] = useState(entityId === null);
  useEffect(() => { if (!hydrated && detail.data) { setDraft(kind === "agent" ? agentDraft(detail.data as AgentEntityDetail) : squadDraft(detail.data as SquadEntityDetail)); setHydrated(true); } }, [detail.data, hydrated, kind]);
  const mutation = useMutation({ mutationFn: async (value: Draft): Promise<EntitySaveResult> => kind === "agent" ? agentEntityClient.saveAgent(repoId, agentDeclaration(value as AgentDraft)) : agentEntityClient.saveSquad(repoId, squadDeclaration(value as SquadDraft)), onSuccess: (result) => { if (result.outcome === "op_rejected") setServerError(result.error?.hint ?? t("components.entityAuthoring.saveRejected")); else onSaved(); }, onError: (error) => setServerError(error instanceof Error ? error.message : String(error)) });
  const update = (field: string, value: string) => { setDraft((current) => ({ ...current, [field]: value })); setErrors((current) => ({ ...current, [field]: undefined })); setServerError(null); };
  const submit = (event: FormEvent) => { event.preventDefault(); if (mutation.isPending) return; const nextErrors = kind === "agent" ? validateAgent(draft as AgentDraft) : validateSquad(draft as SquadDraft); setErrors(nextErrors); setServerError(null); if (Object.keys(nextErrors).length === 0) mutation.mutate(draft); };
  if (entityId !== null && detail.isError) return <DialogFrame title={t("components.entityAuthoring.editTitle", { kind: kindLabel(kind) })} onClose={onClose}><p role="alert" className="text-sm text-status-blocked">{detail.error instanceof Error ? detail.error.message : String(detail.error)}</p></DialogFrame>;
  if (entityId !== null && !hydrated) return <DialogFrame title={t("components.entityAuthoring.editTitle", { kind: kindLabel(kind) })} onClose={onClose}><p className="text-sm text-text-faint">{t("components.entityLayers.loadingDeclaration")}</p></DialogFrame>;
  return <DialogFrame title={t(entityId === null ? "components.entityAuthoring.newTitle" : "components.entityAuthoring.editTitle", { kind: kindLabel(kind) })} onClose={onClose}><form data-testid={`${kind}-authoring`} onSubmit={submit} className="grid gap-3"><div className="grid gap-3 sm:grid-cols-2"><Field label="id" value={draft.id} error={errors.id} onChange={(value) => update("id", value)} disabled={entityId !== null} data-testid={`${kind}-id`} /><Field label="name" value={draft.name} error={errors.name} onChange={(value) => update("name", value)} data-testid={`${kind}-name`} /></div>{kind === "agent" ? <AgentFields draft={draft as AgentDraft} errors={errors} update={update} /> : <SquadFields draft={draft as SquadDraft} errors={errors} update={update} />}{serverError && <p role="alert" className="rounded border border-status-blocked/40 bg-status-blocked/10 px-2 py-1.5 text-xs text-status-blocked">{serverError}</p>}<div className="flex justify-end gap-2 border-t border-border pt-3"><button type="button" onClick={onClose} className="rounded border border-border px-3 py-1.5 text-xs text-text-muted">{t("components.entityAuthoring.cancel")}</button><button type="submit" disabled={mutation.isPending} data-testid={`${kind}-save`} className="rounded bg-accent px-3 py-1.5 text-xs font-semibold text-accent-fg disabled:opacity-50">{mutation.isPending ? t("components.entityAuthoring.saving") : t("components.entityAuthoring.save")}</button></div></form></DialogFrame>;
}

function AgentFields({ draft, errors, update }: { readonly draft: AgentDraft; readonly errors: Errors; readonly update: (field: string, value: string) => void }) { return <><Field label="instructions" value={draft.instructions} error={errors.instructions} onChange={(value) => update("instructions", value)} multiline data-testid="agent-instructions" /><div className="grid gap-3 sm:grid-cols-3"><Field label="runtime_type" value={draft.runtimeType} error={errors.runtimeType} onChange={(value) => update("runtimeType", value)} hint={t("components.entityAuthoring.runtimeHint")} data-testid="agent-runtime-type" /><Field label="role" value={draft.role} error={errors.role} onChange={(value) => update("role", value)} hint={t("components.entityAuthoring.roleHint")} data-testid="agent-role" /><Field label="model" value={draft.model} error={errors.model} onChange={(value) => update("model", value)} hint={t("components.entityAuthoring.modelHint")} data-testid="agent-model" /></div></>; }
function SquadFields({ draft, errors, update }: { readonly draft: SquadDraft; readonly errors: Errors; readonly update: (field: string, value: string) => void }) { return <><Field label="leader" value={draft.leader} error={errors.leader} onChange={(value) => update("leader", value)} data-testid="squad-leader" /><Field label="workers" value={draft.workers} error={errors.workers} onChange={(value) => update("workers", value)} hint={t("components.entityAuthoring.workersHint")} data-testid="squad-workers" /><Field label="roster" value={draft.roster} error={errors.roster} onChange={(value) => update("roster", value)} multiline rows={10} hint={t("components.entityAuthoring.rosterHint")} data-testid="squad-roster" /></>; }
function Field({ label, value, error, hint, onChange, multiline = false, rows = 5, ...props }: { readonly label: string; readonly value: string; readonly error?: string; readonly hint?: string; readonly onChange: (value: string) => void; readonly multiline?: boolean; readonly rows?: number; readonly [key: string]: unknown }) { return <label className="grid gap-1 text-xs text-text-muted"><span className="font-mono text-[10px] uppercase text-text-faint">{label}</span>{multiline ? <textarea {...props} value={value} rows={rows} onChange={(event) => onChange(event.target.value)} className="w-full rounded border border-border-strong bg-surface px-2 py-1.5 text-sm text-text" /> : <input {...props} value={value} onChange={(event) => onChange(event.target.value)} className="w-full rounded border border-border-strong bg-surface px-2 py-1.5 text-sm text-text" />}{hint && <span className="text-[10px] text-text-faint">{hint}</span>}{error && <span className="text-[11px] text-status-blocked">{error}</span>}</label>; }
function DialogFrame({ title, onClose, children }: { readonly title: string; readonly onClose: () => void; readonly children: ReactNode }) { return <div role="dialog" aria-modal="true" className="fixed inset-0 z-50 grid place-items-center bg-black/50 p-4"><section className="max-h-[90dvh] w-full max-w-2xl overflow-y-auto rounded-lg border border-border bg-surface-raised p-4 shadow-xl"><header className="mb-3 flex items-center gap-2 border-b border-border pb-2"><h2 className="ui-title font-semibold text-text">{title}</h2><button type="button" aria-label={t("components.entityAuthoring.close")} onClick={onClose} className="ml-auto rounded border border-border px-2 py-0.5 text-text-muted">×</button></header>{children}</section></div>; }
function emptyAgent(): AgentDraft { return { id: "", name: "", instructions: "", runtimeType: "any", role: "worker", model: "", skills: "", prompts: "", preset: "" }; }
function emptySquad(): SquadDraft { return { id: "", name: "", leader: "", workers: "", roster: "" }; }
function agentDraft(value: AgentEntityDetail): AgentDraft { return { id: value.id, name: value.name, instructions: value.instructions, runtimeType: value.runtimeType, role: value.role, model: value.model ?? "", skills: value.skills.join("\n"), prompts: value.prompts.join("\n"), preset: value.preset ?? "" }; }
function squadDraft(value: SquadEntityDetail): SquadDraft { return { id: value.id, name: value.name, leader: value.leader, workers: value.workers.join(", "), roster: value.roster }; }
function agentDeclaration(value: AgentDraft): AgentDeclarationV1 { return { schema: "agent-declaration/v1", id: value.id.trim(), name: value.name.trim(), instructions: value.instructions, runtime_type: value.runtimeType.trim(), role: value.role as "worker" | "commander", ...(value.model.trim() ? { model: value.model.trim() } : {}), ...(lines(value.skills).length ? { skills: lines(value.skills) } : {}), ...(lines(value.prompts).length ? { prompts: lines(value.prompts) } : {}), ...(value.preset.trim() ? { preset: value.preset.trim() } : {}) } as AgentDeclarationV1; }
function squadDeclaration(value: SquadDraft): SquadDeclarationV1 { return { schema: "squad-declaration/v1", id: value.id.trim(), name: value.name.trim(), leader: value.leader.trim(), workers: workers(value.workers), roster: value.roster } as SquadDeclarationV1; }
function validateAgent(value: AgentDraft): Errors { const errors: Errors = {}; if (!slug(value.id)) errors.id = t("components.entityAuthoring.invalidId"); if (!value.name.trim()) errors.name = t("components.entityAuthoring.required"); if (!value.instructions.trim()) errors.instructions = t("components.entityAuthoring.required"); if (!runtime(value.runtimeType)) errors.runtimeType = t("components.entityAuthoring.invalidRuntime"); if (!["worker", "commander"].includes(value.role)) errors.role = t("components.entityAuthoring.invalidRole"); if (value.model.trim() === "" && value.model !== "") errors.model = t("components.entityAuthoring.invalidModel"); return errors; }
function validateSquad(value: SquadDraft): Errors { const errors: Errors = {}; if (!slug(value.id)) errors.id = t("components.entityAuthoring.invalidId"); if (!value.name.trim()) errors.name = t("components.entityAuthoring.required"); if (!slug(value.leader)) errors.leader = t("components.entityAuthoring.invalidLeader"); if (workers(value.workers).some((item) => !slug(item)) || new Set(workers(value.workers)).size !== workers(value.workers).length) errors.workers = t("components.entityAuthoring.invalidWorkers"); if (!value.roster.trim()) errors.roster = t("components.entityAuthoring.required"); return errors; }
function lines(value: string): string[] { return value.split(/\r?\n/u).map((item) => item.trim()).filter(Boolean); }
function workers(value: string): string[] { return value.split(/[\s,]+/u).map((item) => item.trim()).filter(Boolean); }
function slug(value: string): boolean { return /^[a-z0-9][a-z0-9-]{0,63}$/u.test(value.trim()); }
function runtime(value: string): boolean { return slug(value); }
function kindLabel(value: EntityAuthoringKind): string { return value === "agent" ? "Agent" : "Squad"; }
