import { useState } from "react";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { runtimeInstanceClient, type RuntimeInstanceCreateInput } from "../runtime-instance-client.ts";
import { t } from "../i18n/index.tsx";
import { RuntimeInstanceManagerPanel } from "./RuntimeInstanceManagerPanel.tsx";

export function RuntimeInstanceManager({ repoId }: { readonly repoId: string }) { const client = useQueryClient(), key = ["runtime-instances", "machine"] as const, query = useQuery({ queryKey: key, queryFn: runtimeInstanceClient.list, staleTime: 2_000 }), [busy, setBusy] = useState(false), [feedback, setFeedback] = useState<string | null>(null); const run = async (label: string, action: () => Promise<unknown>, refresh = true) => { setBusy(true); setFeedback(null); return action().then(async (result) => { const record = result as Record<string, unknown>, id = String(record.sessionId ?? record.opId ?? "applied"); setFeedback(record.sessionId ? t("components.runtimeInstanceManager.operationWithSession", { label, id }) : t("components.runtimeInstanceManager.operationApplied", { label, id })); if (refresh) await client.fetchQuery({ queryKey: key, queryFn: runtimeInstanceClient.list, staleTime: 0 }); return result; }, (error: unknown) => { setFeedback(t("components.runtimeInstanceManager.operationFailed", { label, error: error instanceof Error ? error.message : String(error) })); return null; }).finally(() => setBusy(false)); }; if (query.isError) return <section className="border-b border-border p-4 text-status-blocked">{t("components.runtimeInstanceManager.readFailed", { error: query.error instanceof Error ? query.error.message : String(query.error) })}</section>; if (!query.data) return <section className="border-b border-border p-4 text-text-faint">{t("components.runtimeInstanceManager.loading")}</section>;
  // Subscription instances sign in through the provider's own interactive login, so
  // creating one hands straight off to that terminal flow (product decision: the
  // user who wants to log in just logs in). Create and login keep separate
  // feedback: a login hiccup must not read as a failed create.
  const create = async (input: RuntimeInstanceCreateInput) => { const created = await run(t("components.runtimeInstanceManager.instanceCreated"), () => runtimeInstanceClient.create(input)); if (created && input.authMode === "subscription") await run(t("components.runtimeInstanceManager.providerTerminalStarted", { action: "login" }), () => runtimeInstanceClient.auth(repoId, input.instanceId, "login"), false); return created; };
  return <RuntimeInstanceManagerPanel instances={query.data.instances} installations={query.data.installations} busy={busy} feedback={feedback} onRefresh={() => run(t("components.runtimeInstanceManager.readinessRefreshed"), runtimeInstanceClient.list)} onCreate={create} onShow={(instanceId) => run(t("components.runtimeInstanceManager.safeInstanceDetail"), () => runtimeInstanceClient.show(instanceId), false)} onDelete={(instanceId) => run(t("components.runtimeInstanceManager.instanceDeleted"), () => runtimeInstanceClient.delete(instanceId))} onValidate={(instanceId) => run(t("components.runtimeInstanceManager.authenticationChecked"), () => runtimeInstanceClient.validate(instanceId))} onSetEnabled={(instanceId, enabled) => run(t(enabled ? "components.runtimeInstanceManager.instanceEnabled" : "components.runtimeInstanceManager.instanceDisabled"), () => runtimeInstanceClient.setEnabled(instanceId, enabled))} onSubscriptionAction={(instanceId, action) => run(t("components.runtimeInstanceManager.providerTerminalStarted", { action }), () => runtimeInstanceClient.auth(repoId, instanceId, action), false)}/>; }
