import { useMemo, useState, type FormEvent } from "react";
import type { AgentRuntimeOverviewResult } from "../../../../daemon/src/agent-runtime-contract.ts";
import type { RuntimeCredentialReceipt } from "../../../../daemon/src/gui-s3-control.ts";
import type { RuntimeSpawnInput, RuntimeSpawnSettlement } from "../runtime-control.ts";

type TaskOption = { readonly taskId: string; readonly title: string };
export function RuntimeControlPanel({ overview, tasks, busy, settlement, credentialReceipt, onSpawn, onConfigureCredential }: {
  readonly overview: AgentRuntimeOverviewResult; readonly tasks: readonly TaskOption[]; readonly busy: boolean; readonly settlement: RuntimeSpawnSettlement | null; readonly credentialReceipt: RuntimeCredentialReceipt | null;
  readonly onSpawn: (input: RuntimeSpawnInput) => Promise<unknown>; readonly onConfigureCredential: (kindId: "claude" | "codex", baseUrl?: string) => Promise<unknown>;
}) {
  const [kindId, setKindId] = useState<"claude" | "codex">("codex"), [installationChoice, setInstallationChoice] = useState(""), [profileChoice, setProfileChoice] = useState(""), [cwdScope, setCwdScope] = useState<"repo-root" | "repo-relative">("repo-root"), [cwdPath, setCwdPath] = useState(""), [taskId, setTaskId] = useState(""), [prompt, setPrompt] = useState(""), [baseUrl, setBaseUrl] = useState("");
  const installations = useMemo(() => overview.installations.filter((row) => row.kindId === kindId), [kindId, overview.installations]), installation = installations.find((row) => row.installationId === installationChoice) ?? installations[0] ?? null, profile = installation?.profiles.find((row) => row.profileId === profileChoice) ?? installation?.profiles[0] ?? null;
  const submit = (event: FormEvent) => { event.preventDefault(); if (!installation || !profile || !prompt.trim() || cwdScope === "repo-relative" && !cwdPath.trim()) return; void onSpawn({ kindId, installationId: installation.installationId, profileId: profile.profileId, cwd: cwdScope === "repo-root" ? { scope: "repo-root" } : { scope: "repo-relative", path: cwdPath.trim() }, prompt: prompt.trim(), taskId: taskId || null, idempotencyKey: `runtime-gui-${crypto.randomUUID()}` }); };
  const credentialError = credentialReceipt?.error as { readonly code?: string; readonly hint?: string } | null | undefined;
  return <section data-testid="runtime-control" className="border-b border-border bg-surface-raised/45 px-4 py-3"><div className="grid gap-4 xl:grid-cols-[minmax(0,1fr)_310px]">
    <form onSubmit={submit} className="grid min-w-0 gap-2"><div className="flex items-baseline gap-2"><h2 className="ui-title font-semibold">Spawn runtime</h2><span className="font-mono text-[10px] uppercase text-text-faint">inventory pinned</span></div>
      <div className="grid gap-2 sm:grid-cols-2 xl:grid-cols-4"><Select label="Kind" aria="Runtime kind" value={kindId} onChange={(value) => { setKindId(value as "claude" | "codex"); setInstallationChoice(""); setProfileChoice(""); }} options={[{ value: "claude", label: "Claude" }, { value: "codex", label: "Codex" }]}/><Select label="Installation" aria="Runtime installation" value={installation?.installationId ?? ""} onChange={(value) => { setInstallationChoice(value); setProfileChoice(""); }} options={installations.map((row) => ({ value: row.installationId, label: `${row.installationId} · ${row.version}` }))}/><Select label="Profile" aria="Runtime profile" value={profile?.profileId ?? ""} onChange={setProfileChoice} options={installation?.profiles.map((row) => ({ value: row.profileId, label: row.label })) ?? []}/><Select label="Task binding" aria="Runtime task" value={taskId} onChange={setTaskId} options={[{ value: "", label: "No task" }, ...tasks.map((task) => ({ value: task.taskId, label: `${task.taskId} · ${task.title}` }))]}/></div>
      <div className="grid gap-2 sm:grid-cols-[155px_minmax(0,1fr)]"><Select label="Working directory" aria="Runtime cwd scope" value={cwdScope} onChange={(value) => setCwdScope(value as "repo-root" | "repo-relative")} options={[{ value: "repo-root", label: "Repository root" }, { value: "repo-relative", label: "Repository relative" }]}/>{cwdScope === "repo-relative" && <label className="grid gap-1 text-[11px] text-text-muted">Relative path<input value={cwdPath} onChange={(event) => setCwdPath(event.target.value)} placeholder="packages/gui" className="rounded border border-border bg-surface px-2 py-1.5 font-mono text-sm text-text"/></label>}</div>
      <label className="grid gap-1 text-[11px] text-text-muted">Prompt<textarea aria-label="Runtime prompt" value={prompt} onChange={(event) => setPrompt(event.target.value)} rows={2} placeholder="Describe the bounded work for this native runtime…" className="resize-y rounded border border-border bg-surface px-2 py-1.5 text-sm text-text"/></label>
      <div className="flex flex-wrap items-center gap-2"><button disabled={busy || !installation || !profile || !prompt.trim()} className="rounded bg-accent px-3 py-1.5 text-sm font-semibold text-on-accent disabled:cursor-not-allowed disabled:opacity-50">{busy ? "Waiting for receipt…" : "Spawn"}</button>{settlement && <span className={`font-mono text-[11px] ${settlement.state === "applied" ? "text-status-done" : settlement.state === "rejected" ? "text-status-blocked" : "text-status-warning"}`}>{settlement.state} · {settlement.opId} · {settlement.hint}</span>}</div>
    </form>
    <aside className="border-l border-border pl-4"><h2 className="ui-title font-semibold">Credential broker</h2><p className="mt-1 text-[11px] leading-relaxed text-text-faint">The OS secure prompt owns credential entry. Renderer payloads carry only runtime kind and optional base URL.</p><dl className="mt-2 grid grid-cols-2 gap-x-3 gap-y-1 text-[11px]"><dt className="text-text-faint">Credential</dt><dd className="text-text">{installation?.credentialState ?? "unknown / 未投影"}</dd><dt className="text-text-faint">Base URL</dt><dd className="text-text">{installation ? installation.baseUrlConfigured ? "Base URL configured" : "Default endpoint" : "unknown / 未投影"}</dd></dl>
      <label className="mt-2 grid gap-1 text-[11px] text-text-muted">Optional base URL<input type="url" value={baseUrl} onChange={(event) => setBaseUrl(event.target.value)} placeholder="https://…" className="rounded border border-border bg-surface px-2 py-1.5 text-sm text-text"/></label><button type="button" disabled={busy} onClick={() => void onConfigureCredential(kindId, baseUrl.trim() || undefined)} className="mt-2 rounded border border-border-strong px-2.5 py-1.5 text-[12px] font-medium text-text hover:bg-surface disabled:opacity-50">Open secure prompt</button>
      {credentialReceipt && <p className={`mt-2 font-mono text-[10px] ${credentialReceipt.ok ? "text-status-done" : "text-status-blocked"}`}>{credentialReceipt.operationId} · {credentialReceipt.credentialState}</p>}{credentialError?.code === "secure_prompt_unavailable" && <p className="mt-2 text-[11px] text-status-warning">secure_prompt_unavailable · Configure with the Harness CLI or OS keychain, then reread this inventory. {credentialError.hint}</p>}
    </aside>
  </div></section>;
}
function Select({ label, aria, value, options, onChange }: { readonly label: string; readonly aria: string; readonly value: string; readonly options: readonly { readonly value: string; readonly label: string }[]; readonly onChange: (value: string) => void }) { return <label className="grid gap-1 text-[11px] text-text-muted">{label}<select aria-label={aria} value={value} onChange={(event) => onChange(event.target.value)} className="rounded border border-border bg-surface px-2 py-1.5 text-sm text-text">{options.length ? options.map((option) => <option key={option.value || "none"} value={option.value}>{option.label}</option>) : <option value="">unknown / 未投影</option>}</select></label>; }
