import { useMemo, useState, type FormEvent } from "react";
import type { AgentRuntimeOverviewResult } from "../../../../daemon/src/agent-runtime-contract.ts";
import type { RuntimeSpawnInput, RuntimeSpawnSettlement } from "../runtime-control.ts";

type TaskOption = { readonly taskId: string; readonly title: string };
export function RuntimeControlPanel({ overview, tasks, busy, settlement, onSpawn }: {
  readonly overview: AgentRuntimeOverviewResult; readonly tasks: readonly TaskOption[]; readonly busy: boolean; readonly settlement: RuntimeSpawnSettlement | null;
  readonly onSpawn: (input: RuntimeSpawnInput) => Promise<unknown>;
}) {
  const [instanceChoice, setInstanceChoice] = useState(""), [cwdScope, setCwdScope] = useState<"repo-root" | "repo-relative">("repo-root"), [cwdPath, setCwdPath] = useState(""), [taskId, setTaskId] = useState(""), [prompt, setPrompt] = useState("");
  const instance = useMemo(() => overview.instances.find((row) => row.instanceId === instanceChoice) ?? overview.instances[0] ?? null, [instanceChoice, overview.instances]);
  const submit = (event: FormEvent) => { event.preventDefault(); if (!instance || !prompt.trim() || cwdScope === "repo-relative" && !cwdPath.trim()) return; void onSpawn({ runtimeInstanceId: instance.instanceId, cwd: cwdScope === "repo-root" ? { scope: "repo-root" } : { scope: "repo-relative", path: cwdPath.trim() }, prompt: prompt.trim(), taskId: taskId || null, idempotencyKey: `runtime-gui-${crypto.randomUUID()}` }); };
  return <section data-testid="runtime-control" className="border-b border-border bg-surface-raised/45 px-4 py-3"><div className="grid gap-4 xl:grid-cols-[minmax(0,1fr)_310px]">
    <form onSubmit={submit} className="grid min-w-0 gap-2"><div className="flex items-baseline gap-2"><h2 className="ui-title font-semibold">Spawn runtime</h2><span className="font-mono text-[10px] uppercase text-text-faint">inventory pinned</span></div>
      <div className="grid gap-2 sm:grid-cols-2"><Select label="Runtime instance" aria="Runtime instance" value={instance?.instanceId ?? ""} onChange={setInstanceChoice} options={overview.instances.map((row) => ({ value: row.instanceId, label: `${row.name} · ${row.model}` }))}/><Select label="Task binding" aria="Runtime task" value={taskId} onChange={setTaskId} options={[{ value: "", label: "No task" }, ...tasks.map((task) => ({ value: task.taskId, label: `${task.taskId} · ${task.title}` }))]}/></div>
      <div className="grid gap-2 sm:grid-cols-[155px_minmax(0,1fr)]"><Select label="Working directory" aria="Runtime cwd scope" value={cwdScope} onChange={(value) => setCwdScope(value as "repo-root" | "repo-relative")} options={[{ value: "repo-root", label: "Repository root" }, { value: "repo-relative", label: "Repository relative" }]}/>{cwdScope === "repo-relative" && <label className="grid gap-1 text-[11px] text-text-muted">Relative path<input value={cwdPath} onChange={(event) => setCwdPath(event.target.value)} placeholder="packages/gui" className="rounded border border-border bg-surface px-2 py-1.5 font-mono text-sm text-text"/></label>}</div>
      <label className="grid gap-1 text-[11px] text-text-muted">Prompt<textarea aria-label="Runtime prompt" value={prompt} onChange={(event) => setPrompt(event.target.value)} rows={2} placeholder="Describe the bounded work for this native runtime…" className="resize-y rounded border border-border bg-surface px-2 py-1.5 text-sm text-text"/></label>
      <div className="flex flex-wrap items-center gap-2"><button disabled={busy || !instance || !prompt.trim()} className="rounded bg-accent px-3 py-1.5 text-sm font-semibold text-on-accent disabled:cursor-not-allowed disabled:opacity-50">{busy ? "Waiting for receipt…" : "Spawn"}</button>{settlement && <span className={`font-mono text-[11px] ${settlement.state === "applied" ? "text-status-done" : settlement.state === "rejected" ? "text-status-blocked" : "text-status-warning"}`}>{settlement.state} · {settlement.opId} · {settlement.hint}</span>}</div>
    </form>
    <aside className="border-l border-border pl-4"><h2 className="ui-title font-semibold">Frozen definition</h2><p className="mt-1 text-[11px] leading-relaxed text-text-faint">Spawn resolves one machine instance; model, installation, auth mode, and isolation cannot be recombined here.</p><dl className="mt-2 grid grid-cols-2 gap-x-3 gap-y-1 text-[11px]"><dt className="text-text-faint">Kind</dt><dd className="text-text">{instance?.kindId ?? "unknown / 未投影"}</dd><dt className="text-text-faint">Installation</dt><dd className="break-all text-text">{instance?.installationId ?? "unknown / 未投影"}</dd><dt className="text-text-faint">Auth</dt><dd className="text-text">{instance ? `${instance.authMode} · ${instance.authState}` : "unknown / 未投影"}</dd><dt className="text-text-faint">Isolation</dt><dd className="text-text">{instance?.isolationState ?? "unknown / 未投影"}</dd></dl></aside>
  </div></section>;
}
function Select({ label, aria, value, options, onChange }: { readonly label: string; readonly aria: string; readonly value: string; readonly options: readonly { readonly value: string; readonly label: string }[]; readonly onChange: (value: string) => void }) { return <label className="grid gap-1 text-[11px] text-text-muted">{label}<select aria-label={aria} value={value} onChange={(event) => onChange(event.target.value)} className="rounded border border-border bg-surface px-2 py-1.5 text-sm text-text">{options.length ? options.map((option) => <option key={option.value || "none"} value={option.value}>{option.label}</option>) : <option value="">unknown / 未投影</option>}</select></label>; }
