import { useMemo, useState, type FormEvent } from "react";
import type { AgentRuntimeOverviewResult } from "../../../../daemon/src/agent-runtime-contract.ts";
import type { RuntimeSpawnInput, RuntimeSpawnSettlement } from "../runtime-control.ts";
import { t } from "../i18n/index.tsx";

type TaskOption = { readonly taskId: string; readonly title: string };
export function RuntimeControlPanel({ overview, tasks, busy, settlement, onSpawn }: {
  readonly overview: AgentRuntimeOverviewResult; readonly tasks: readonly TaskOption[]; readonly busy: boolean; readonly settlement: RuntimeSpawnSettlement | null;
  readonly onSpawn: (input: RuntimeSpawnInput) => Promise<unknown>;
}) {
  const [instanceChoice, setInstanceChoice] = useState(""), [cwdScope, setCwdScope] = useState<"repo-root" | "repo-relative">("repo-root"), [cwdPath, setCwdPath] = useState(""), [taskId, setTaskId] = useState(""), [prompt, setPrompt] = useState(""), [effort, setEffort] = useState("");
  const instance = useMemo(() => overview.instances.find((row) => row.instanceId === instanceChoice) ?? overview.instances[0] ?? null, [instanceChoice, overview.instances]);
  const submit = (event: FormEvent) => { event.preventDefault(); if (!instance || !prompt.trim() || cwdScope === "repo-relative" && !cwdPath.trim()) return; void onSpawn({ runtimeInstanceId: instance.instanceId, ...(effort.trim() && (instance.kindId === "codex" || instance.kindId === "agy") ? { effort: effort.trim() } : {}), cwd: cwdScope === "repo-root" ? { scope: "repo-root" } : { scope: "repo-relative", path: cwdPath.trim() }, prompt: prompt.trim(), taskId: taskId || null, idempotencyKey: `runtime-gui-${crypto.randomUUID()}` }); };
  return <section data-testid="runtime-control" className="border-b border-border bg-surface-raised/45 px-4 py-3"><div className="grid gap-4 xl:grid-cols-[minmax(0,1fr)_310px]">
    <form onSubmit={submit} className="grid min-w-0 gap-2"><div className="flex items-baseline gap-2"><h2 className="ui-title font-semibold">{t("components.runtimeControlPanel.title")}</h2><span className="font-mono text-[10px] uppercase text-text-faint">{t("components.runtimeControlPanel.inventoryPinned")}</span></div>
      <div className="grid gap-2 sm:grid-cols-2"><Select label={t("views.agentRuntimeView.spawnKind")} aria={t("views.agentRuntimeView.spawnKind")} value={instance?.instanceId ?? ""} onChange={setInstanceChoice} options={overview.instances.map((row) => ({ value: row.instanceId, label: `${row.name} · ${row.defaultModel}` }))}/><Select label={t("components.runtimeControlPanel.taskBinding")} aria={t("components.runtimeControlPanel.runtimeTask")} value={taskId} onChange={setTaskId} options={[{ value: "", label: t("components.runtimeControlPanel.noTask") }, ...tasks.map((task) => ({ value: task.taskId, label: `${task.taskId} · ${task.title}` }))]}/></div>
      <div className="grid gap-2 sm:grid-cols-[155px_minmax(0,1fr)]"><Select label={t("views.agentRuntimeView.spawnCwd")} aria={t("components.runtimeControlPanel.runtimeCwdScope")} value={cwdScope} onChange={(value) => setCwdScope(value as "repo-root" | "repo-relative")} options={[{ value: "repo-root", label: t("components.runtimeControlPanel.repositoryRoot") }, { value: "repo-relative", label: t("components.runtimeControlPanel.repositoryRelative") }]}/>{cwdScope === "repo-relative" && <label className="grid gap-1 text-[11px] text-text-muted">{t("components.runtimeControlPanel.relativePath")}<input value={cwdPath} onChange={(event) => setCwdPath(event.target.value)} placeholder="packages/gui" className="rounded border border-border bg-surface px-2 py-1.5 font-mono text-sm text-text"/></label>}</div>
      {(instance?.kindId === "codex" || instance?.kindId === "agy") && <label className="grid gap-1 text-[11px] text-text-muted">Reasoning effort<input value={effort} onChange={(event) => setEffort(event.target.value)} placeholder={instance.kindId === "codex" ? instance.codex.reasoningEffort ?? "optional" : instance.agy.effort ?? "optional"} className="rounded border border-border bg-surface px-2 py-1.5 font-mono text-sm text-text"/></label>}
      <label className="grid gap-1 text-[11px] text-text-muted">{t("views.agentRuntimeView.spawnPrompt")}<textarea aria-label={t("components.runtimeControlPanel.runtimePrompt")} value={prompt} onChange={(event) => setPrompt(event.target.value)} rows={2} placeholder={t("views.agentRuntimeView.spawnPromptPlaceholder")} className="resize-y rounded border border-border bg-surface px-2 py-1.5 text-sm text-text"/></label>
      <div className="flex flex-wrap items-center gap-2"><button disabled={busy || !instance || !prompt.trim()} className="rounded bg-accent px-3 py-1.5 text-sm font-semibold text-on-accent disabled:cursor-not-allowed disabled:opacity-50">{busy ? t("views.agentRuntimeView.spawning") : t("views.agentRuntimeView.spawn")}</button>{settlement && <span className={`font-mono text-[11px] ${settlement.state === "applied" ? "text-status-done" : settlement.state === "op_rejected" ? "text-status-blocked" : "text-status-warning"}`}>{settlement.state} · {settlement.opId} · {settlement.hint}</span>}</div>
    </form>
    <aside className="border-l border-border pl-4"><h2 className="ui-title font-semibold">{t("components.runtimeControlPanel.frozenDefinition")}</h2><p className="mt-1 text-[11px] leading-relaxed text-text-faint">{t("components.runtimeControlPanel.frozenDefinitionDescription")}</p><dl className="mt-2 grid grid-cols-2 gap-x-3 gap-y-1 text-[11px]"><dt className="text-text-faint">{t("components.runtimeControlPanel.kind")}</dt><dd className="text-text">{instance?.kindId ?? t("components.runtimeControlPanel.unknownNotProjected")}</dd><dt className="text-text-faint">{t("components.runtimeControlPanel.installation")}</dt><dd className="break-all text-text">{instance?.installationId ?? t("components.runtimeControlPanel.unknownNotProjected")}</dd><dt className="text-text-faint">{t("components.runtimeControlPanel.auth")}</dt><dd className="text-text">{instance ? `${instance.authMode} · ${instance.authState}` : t("components.runtimeControlPanel.unknownNotProjected")}</dd><dt className="text-text-faint">{t("components.runtimeControlPanel.isolation")}</dt><dd className="text-text">{instance?.isolationState ?? t("components.runtimeControlPanel.unknownNotProjected")}</dd></dl></aside>
  </div></section>;
}
function Select({ label, aria, value, options, onChange }: { readonly label: string; readonly aria: string; readonly value: string; readonly options: readonly { readonly value: string; readonly label: string }[]; readonly onChange: (value: string) => void }) { return <label className="grid gap-1 text-[11px] text-text-muted">{label}<select aria-label={aria} value={value} onChange={(event) => onChange(event.target.value)} className="rounded border border-border bg-surface px-2 py-1.5 text-sm text-text">{options.length ? options.map((option) => <option key={option.value || "none"} value={option.value}>{option.label}</option>) : <option value="">{t("components.runtimeControlPanel.unknownNotProjected")}</option>}</select></label>; }
