import { useEffect, useState } from "react";
import type { AgentRuntimeOverviewResult, AgentRuntimeSessionDto } from "../../../../daemon/src/agent-runtime-contract.ts";
import type { AgentRuntimeAttachEvent } from "../../../../daemon/src/agent-runtime-stream.ts";
import { agentRuntimeClient, openAgentRuntimePane } from "../agent-runtime-client.ts";
import { t } from "../i18n/index.tsx";

const tone = { live: "text-status-done", stale: "text-stale", unknown: "text-status-unknown", exited: "text-text-faint" } as const;
export function AgentRuntimeView({ repoId }: { readonly repoId: string }) {
  const [overview, setOverview] = useState<AgentRuntimeOverviewResult | null>(null), [selectedId, setSelectedId] = useState<string | null>(null), [detail, setDetail] = useState<AgentRuntimeSessionDto | null>(null), [frames, setFrames] = useState<AgentRuntimeAttachEvent[]>([]), [attachStatus, setAttachStatus] = useState("detached"), [error, setError] = useState<string | null>(null);
  useEffect(() => { let active = true; setOverview(null); setSelectedId(null); setError(null); void agentRuntimeClient.overview(repoId).then((value) => { if (active) setOverview(value); }, (cause) => { if (active) setError(String(cause)); }); return () => { active = false; }; }, [repoId]);
  useEffect(() => { if (!selectedId) { setDetail(null); setFrames([]); setAttachStatus("detached"); return; } let active = true, detach: (() => void) | undefined;
    void Promise.all([agentRuntimeClient.session(repoId, selectedId), agentRuntimeClient.events(repoId, selectedId)]).then(([snapshot, lifecycle]) => { if (!active) return; setDetail(snapshot.session); setFrames([]); setAttachStatus(snapshot.session.attachCapability === "supported" ? "attaching" : "unsupported"); if (snapshot.session.attachCapability !== "supported") return;
      detach = openAgentRuntimePane(repoId, selectedId, snapshot.session.streamCursor, (value) => { if (!active) return; if ("ok" in value) { setAttachStatus(value.ok ? value.status : value.code); if (value.ok) { const caughtUp = value.events.filter((event) => event.type !== "gap"); if (caughtUp.length) setFrames((current) => [...current, ...caughtUp].slice(-32)); if (value.status === "gap") void refresh(repoId, selectedId, active, setDetail); } return; } if (value.type === "gap") void refresh(repoId, selectedId, active, setDetail); else setFrames((current) => [...current.slice(-31), value]); }).close; if (!lifecycle.done) setAttachStatus("lifecycle-catch-up"); }, (cause) => { if (active) setError(String(cause)); });
    return () => { active = false; detach?.(); };
  }, [repoId, selectedId]);
  if (error) return <section data-testid="agent-runtime-error" className="p-6 text-status-blocked">{t("views.agentRuntimeView.runtimeReadFailed", { error })}</section>;
  if (!overview) return <section className="p-6 text-text-faint">{t("views.agentRuntimeView.loadingRuntimeProjection")}</section>;
  return <AgentRuntimeProjection overview={overview} selectedId={selectedId} detail={detail} frames={frames} attachStatus={attachStatus} onSelect={setSelectedId} onClose={() => setSelectedId(null)}/>;
}
export function AgentRuntimeProjection({ overview, selectedId, detail, frames, attachStatus, onSelect, onClose }: { readonly overview: AgentRuntimeOverviewResult; readonly selectedId: string | null; readonly detail: AgentRuntimeSessionDto | null; readonly frames: readonly AgentRuntimeAttachEvent[]; readonly attachStatus: string; readonly onSelect: (runtimeSessionId: string) => void; readonly onClose: () => void }) { return <section data-testid="agent-runtime-view" data-selected={selectedId ?? "none"} className="flex min-h-0 flex-1 overflow-hidden">
    <div className="min-w-0 flex-1 overflow-auto p-5"><header className="mb-4"><h1 className="ui-heading font-semibold">{t("views.agentRuntimeView.sessionsTitle")}</h1><p className="text-sm text-text-muted">{t("views.agentRuntimeView.witnessedNativeRuntimes", { status: overview.status })}</p></header>
      <div className="grid grid-cols-[1.2fr_.7fr_1fr_1fr] border-b border-border px-3 py-2 font-mono text-xs uppercase text-text-faint"><span>{t("views.agentRuntimeView.instanceModel")}</span><span>{t("views.agentRuntimeView.session")}</span><span>{t("views.agentRuntimeView.holderLease")}</span><span>{t("views.agentRuntimeView.activity")}</span></div>
      {overview.sessions.length === 0 ? <p className="p-4 text-text-faint">{t("views.agentRuntimeView.noWitnessedSessions")}</p> : overview.sessions.map((session) => { const association = session.associations[0]; return <button key={session.runtimeSessionId} onClick={() => onSelect(session.runtimeSessionId)} className="grid w-full grid-cols-[1.2fr_.7fr_1fr_1fr] gap-3 border-b border-border px-3 py-3 text-left hover:bg-surface-raised">
        <span><b className="block">{session.instanceId}</b><small className="text-text-faint">{session.definitionSnapshot.model} · {session.installationId}</small></span><span className={tone[session.liveness]}>{session.liveness}</span><span><b className="block text-sm">{association?.holder?.personId ?? t("views.agentRuntimeView.unheld")}</b><small className="text-text-faint">{association?.lease ? `${association.lease.phase} · ${association.lease.expiresAt}` : t("views.agentRuntimeView.noLease")}</small></span><span><b className="block text-sm">{session.activity.outcome ?? "active"}</b><small className="text-text-faint">{session.activity.lastObservedAt}</small></span>
      </button>; })}
    </div>
    {detail && <aside data-testid="agent-runtime-detail" className="w-[360px] overflow-auto border-l border-border bg-surface p-4"><div className="mb-4 flex items-center justify-between"><h2 className="font-semibold">{t("views.agentRuntimeView.sessionDetail")}</h2><button data-testid="agent-runtime-pane-close" onClick={onClose} className="text-sm text-text-muted">{t("views.agentRuntimeView.closePane")}</button></div><dl className="grid gap-3 text-sm"><Field name={t("views.agentRuntimeView.fieldSession")} value={detail.runtimeSessionId}/><Field name={t("views.agentRuntimeView.fieldInstance")} value={detail.instanceId}/><Field name={t("views.agentRuntimeView.fieldInstallation")} value={detail.installationId}/><Field name={t("views.agentRuntimeView.fieldProvider")} value={detail.definitionSnapshot.providerId}/><Field name={t("views.agentRuntimeView.fieldModel")} value={detail.definitionSnapshot.model}/><Field name={t("views.agentRuntimeView.fieldAuthMode")} value={detail.definitionSnapshot.authMode}/><Field name={t("views.agentRuntimeView.fieldProviderSession")} value={detail.providerSessionId ?? t("views.agentRuntimeView.notBound")}/><Field name={t("views.agentRuntimeView.fieldLiveness")} value={detail.liveness}/><Field name={t("views.agentRuntimeView.fieldAttach")} value={attachStatus}/><Field name={t("views.agentRuntimeView.fieldLastActivity")} value={detail.activity.lastObservedAt}/></dl><h3 className="mt-5 mb-2 font-mono text-xs uppercase text-text-faint">{t("views.agentRuntimeView.readOnlyActivity")}</h3><div className="space-y-2">{frames.map((frame) => <div key={frame.cursor} className="rounded border border-border p-2 text-sm"><span className="text-text-faint">{frame.cursor}</span> · {frame.type === "activity" ? frame.activity : frame.type}</div>)}</div></aside>}
  </section>;
}
function Field({ name, value }: { readonly name: string; readonly value: string }) { return <div><dt className="font-mono text-xs uppercase text-text-faint">{name}</dt><dd className="break-all text-text">{value}</dd></div>; }
async function refresh(repoId: string, runtimeSessionId: string, active: boolean, update: (session: AgentRuntimeSessionDto) => void): Promise<void> { const snapshot = await agentRuntimeClient.session(repoId, runtimeSessionId); if (active) update(snapshot.session); }
