import { ArrowClockwise, Power } from "@phosphor-icons/react";
import { controlSucceeded, useDaemonControl, useSystemStatusQuery } from "../system-data.ts";
import { t } from "../i18n/index.tsx";

export function SystemView({ activeRepoId }: { readonly activeRepoId: string | null }) {
  const status = useSystemStatusQuery(), control = useDaemonControl(activeRepoId), receipt = control.receipt;
  if (status.isPending) return <div className="p-6 text-text-faint">{t("views.settingsView.systemLoading")}</div>;
  if (status.isError || !status.data) return <div className="p-6 text-status-blocked">{t("views.systemView.readFailed", { error: status.error instanceof Error ? status.error.message : t("views.settingsView.systemUnknownDash") })}</div>;
  const daemon = status.data.daemon;
  return <div className="flex flex-1 flex-col overflow-y-auto"><header className="border-b border-border px-4 py-3"><div className="flex flex-wrap items-center gap-2"><h1 className="ui-title font-semibold">{t("shell.nav.system")}</h1><span className="font-mono text-[11px] text-text-faint">daemon {daemon.daemonId} · pid {daemon.pid}</span><div className="ml-auto flex gap-2"><button disabled={!activeRepoId || control.busy} onClick={() => void control.request("refresh")} className="inline-flex items-center gap-1 rounded-md border border-border px-2 py-1 text-[12px] text-text-muted disabled:opacity-50"><ArrowClockwise/>{t("views.settingsView.systemRefresh")}</button><button disabled={!activeRepoId || control.busy} onClick={() => void control.request("restart")} className="inline-flex items-center gap-1 rounded-md border border-border px-2 py-1 text-[12px] text-text-muted disabled:opacity-50"><Power/>{t("views.settingsView.systemRestart")}</button></div></div><p className="mt-1 text-[12px] text-text-faint">{t("views.systemView.endpoint")} {daemon.endpoint} · {t("views.systemView.protocol")} {daemon.protocolVersion} · {t("views.systemView.build")} {daemon.build.version} / {daemon.build.commitSha ?? t("views.settingsView.systemUnknownDash")}</p>{receipt && <div className={`mt-2 rounded border px-2 py-1.5 font-mono text-[11px] ${controlSucceeded(receipt) ? "border-status-done/30 text-status-done" : receipt.phase === "failed" ? "border-status-blocked/30 text-status-blocked" : "border-stale/30 text-stale"}`}><span>{t("views.systemView.operationId")} {receipt.operationId} · {receipt.kind} · {receipt.phase}</span>{receipt.kind === "restart" && receipt.phase === "settled" && <span> · pid {receipt.before?.pid ?? t("views.settingsView.systemUnknownDash")} → {receipt.after?.pid ?? t("views.settingsView.systemUnknownDash")}</span>}{receipt.error && <span> · {receipt.error.code}: {receipt.error.hint}</span>}</div>}</header>
    <div className="mx-auto grid w-full max-w-6xl gap-4 p-4 lg:grid-cols-[22rem_minmax(0,1fr)]"><section className="rounded-lg border border-border bg-surface p-3"><h2 className="text-[13px] font-semibold">{t("views.systemView.daemonGeneration")}</h2><dl className="mt-3 grid gap-2"><Field name={t("views.systemView.started")} value={daemon.startedAt}/><Field name={t("views.systemView.uptime")} value={`${daemon.uptimeMs} ms`}/><Field name={t("views.systemView.activeControl")} value={daemon.activeControl ? `${daemon.activeControl.kind} · ${daemon.activeControl.operationId} · ${daemon.activeControl.phase}` : t("views.settingsView.systemUnknownDash")}/><Field name={t("views.systemView.observed")} value={status.data.observedAt}/></dl></section><section className="rounded-lg border border-border bg-surface"><h2 className="border-b border-border px-3 py-2 text-[13px] font-semibold">{t("views.systemView.repoCellRoster")}</h2>{status.data.repos.map((repo) => <div key={repo.repoId} className="border-b border-border px-3 py-2 last:border-0"><div className="flex flex-wrap items-center gap-2"><b>{repo.displayName}</b><code className="text-[11px] text-text-faint">{repo.repoId}</code><span className="ml-auto font-mono text-[10px] text-text-muted">{repo.registrationState} / {repo.cellState}</span></div><p className="mt-1 font-mono text-[11px] text-text-faint">{t("views.systemView.generation")} {repo.generation ?? t("views.settingsView.systemUnknownDash")} · {t("views.systemView.queue")} {repo.queueDepth ?? t("views.settingsView.systemUnknownDash")} · {t("views.systemView.lock")} {repo.lockState} · {t("views.systemView.recovery")} {repo.recoveryMs ?? t("views.settingsView.systemUnknownDash")} ms</p>{repo.cellState !== "attached" && <p className="mt-1 text-[11px] text-status-blocked">{repo.unavailableReason ?? repo.lastError ?? t("views.settingsView.systemUnknownDash")}</p>}</div>)}</section></div>
  </div>;
}
function Field({ name, value }: { readonly name: string; readonly value: string }) { return <div><dt className="font-mono text-[10px] uppercase text-text-faint">{name}</dt><dd className="break-all text-[12px] text-text-muted">{value}</dd></div>; }
