import { randomUUID } from "node:crypto";
import { consumeKnownError } from "../api/error-consumption.ts";
import { isMainProcessRecord } from "./value-validation.ts";
type Point = { readonly daemonId: string; readonly pid: number; readonly startedAt: string }; type Receipt = Record<string, unknown>;
export function createDaemonSupervisor(input: { readonly authorize: (payload: Record<string, unknown>) => Promise<Record<string, unknown>>; readonly restart: (authorityRepoId: string) => Promise<{ readonly before: Point; readonly after: Point }>; readonly now?: () => string }) {
  const receipts = new Map<string, Receipt>(), now = input.now ?? (() => new Date().toISOString()); let active: Receipt | null = null;
  return {
    request: async (payload: Record<string, unknown>): Promise<Receipt> => { if (payload.kind !== "restart" || typeof payload.authorityRepoId !== "string") return failed("restart", "invalid_control", "Restart requires authorityRepoId."); const authorized = await input.authorize(payload), authorizationCode = errorCode(authorized); if (authorizationCode !== "supervisor_required") return failed("restart", authorizationCode ?? "authorization_failed", errorHint(authorized) ?? "Daemon did not authorize local supervisor restart."); if (active && ["queued", "draining", "starting"].includes(String(active.phase))) return failed("restart", "control_busy", `Wait for ${String(active.operationId)}.`); const operationId = `daemon-control-${randomUUID()}`, requestedAt = now(), pending: Receipt = { schema: "daemon-control-receipt/v1", ok: true, outcome: "pending", kind: "restart", operationId, phase: "queued", requestedAt, completedAt: null, before: null, after: null, error: null, nextAction: `Poll ${operationId}.` }; receipts.set(operationId, pending); active = pending; void settle(pending, payload.authorityRepoId); return pending; },
    receipt: (operationId: string): Receipt | null => receipts.get(operationId) ?? null,
    overlaySystem: (value: Record<string, unknown>): Record<string, unknown> => { if (!active || !isMainProcessRecord(value.daemon)) return value; return { ...value, daemon: { ...value.daemon, activeControl: { kind: active.kind, operationId: active.operationId, phase: active.phase, requestedAt: active.requestedAt, error: active.error } } }; }
  };
  async function settle(pending: Receipt, authorityRepoId: string): Promise<void> { const operationId = String(pending.operationId); try { active = { ...pending, phase: "draining" }; receipts.set(operationId, active); const result = await input.restart(authorityRepoId); active = { ...pending, ok: true, phase: "settled", completedAt: now(), before: result.before, after: result.after, error: null, nextAction: null }; if (result.before.pid === result.after.pid || result.before.startedAt === result.after.startedAt) throw new Error("Daemon generation did not change."); } catch (error) { consumeKnownError(error); active = { ...pending, ok: false, outcome: "op_rejected", phase: "failed", completedAt: now(), error: { code: "restart_failed", hint: error instanceof Error ? error.message : "Daemon restart failed." }, nextAction: "Inspect daemon status; the next request starts the daemon automatically." }; } receipts.set(operationId, active); }
  function failed(kind: string, code: string, hint: string): Receipt { const at = now(), receipt = { schema: "daemon-control-receipt/v1", ok: false, outcome: "op_rejected", kind, operationId: `daemon-control-${randomUUID()}`, phase: "failed", requestedAt: at, completedAt: at, before: null, after: null, error: { code, hint }, nextAction: hint }; receipts.set(receipt.operationId, receipt); return receipt; }
}
function errorCode(value: Record<string, unknown>): string | null { return isMainProcessRecord(value.error) && typeof value.error.code === "string" ? value.error.code : null; }
function errorHint(value: Record<string, unknown>): string | null { return isMainProcessRecord(value.error) && typeof value.error.hint === "string" ? value.error.hint : null; }
