import { execFile, spawn } from "node:child_process";
import { randomUUID } from "node:crypto";
import { promisify } from "node:util";

type Kind = "claude" | "codex"; type CreatePayload = { readonly instanceId: string; readonly name: string; readonly kindId: Kind; readonly installationId: string; readonly providerId: string; readonly model: string; readonly reasoningEffort?: string; readonly baseUrl?: string; readonly authMode: "subscription" | "api-key" }; type Receipt = Readonly<Record<string, unknown>>;
export interface NativeCredentialBroker { readonly promptAndStore: (kindId: Kind) => Promise<string> }
export function createRuntimeInstanceCredentialController(input: { readonly broker?: NativeCredentialBroker; readonly create: (payload: Record<string, unknown>) => Promise<Receipt> }) { const broker = input.broker ?? nativeCredentialBroker(); return { create: async (payload: CreatePayload): Promise<Receipt> => { if (payload.authMode === "subscription") return input.create(payload); let credentialRef: string; try { credentialRef = await broker.promptAndStore(payload.kindId); } catch { return unavailable("secure_prompt_unavailable", "Use the native secure input on macOS, then retry. The instance was not created."); } return input.create({ ...payload, credentialRef }); } }; }
export function nativeCredentialBroker(platform: NodeJS.Platform = process.platform): NativeCredentialBroker { return { promptAndStore: async (kindId) => { if (platform !== "darwin") throw coded("secure_prompt_unavailable"); const script = `set answer to display dialog "Configure ${kindId} API credential" default answer "" with hidden answer buttons {"Cancel", "Save"} default button "Save"\nreturn text returned of answer`, { stdout } = await promisify(execFile)("/usr/bin/osascript", ["-e", script], { encoding: "utf8", windowsHide: true, maxBuffer: 64 * 1024 }), value = stdout.replace(/[\r\n]+$/u, ""); if (!value) throw coded("secure_prompt_unavailable"); const service = "com.harness-anything.runtime-instance", account = `${kindId}-${randomUUID()}`; await storeInKeychain(service, account, value); return `keychain:${service}/${account}`; } }; }
function storeInKeychain(service: string, account: string, value: string): Promise<void> { return new Promise((resolve, reject) => { const child = spawn("/usr/bin/security", ["add-generic-password", "-U", "-s", service, "-a", account, "-w"], { stdio: ["pipe", "ignore", "ignore"], windowsHide: true }); child.once("error", () => reject(coded("secure_prompt_unavailable"))); child.once("exit", (code) => code === 0 ? resolve() : reject(coded("secure_prompt_unavailable"))); child.stdin.end(`${value}\n`); }); }
function unavailable(code: string, hint: string): Receipt { return { schema: "command-receipt/v2", ok: false, command: "runtime-instance-create", outcome: "rejected", opId: `runtime-instance-create:${randomUUID()}`, code, origin: "electron-main", evidence: `rejection:${code}`, error: { code, hint }, nextAction: hint }; }
function coded(code: string): Error { return Object.assign(new Error(code), { code }); }
