import { execFile, spawn } from "node:child_process";
import { randomUUID } from "node:crypto";
import { promisify } from "node:util";

type Kind = "claude" | "codex"; type Payload = { readonly kindId: Kind; readonly baseUrl?: string }; type Receipt = Readonly<Record<string, unknown>>;
export interface NativeCredentialBroker { readonly promptAndStore: (kindId: Kind) => Promise<string> }
export function createRuntimeCredentialController(input: { readonly authorityRepoId: string; readonly broker?: NativeCredentialBroker; readonly bind: (payload: Record<string, unknown>) => Promise<Receipt> }) {
  const broker = input.broker ?? nativeCredentialBroker();
  return { configure: async (payload: Payload): Promise<Receipt> => { if (payload.kindId !== "claude" && payload.kindId !== "codex") return unavailable(payload.kindId, "invalid_runtime_kind", "Select Claude or Codex."); let credentialRef: string; try { credentialRef = await broker.promptAndStore(payload.kindId); } catch { return unavailable(payload.kindId, "secure_prompt_unavailable", "Configure the credential with the OS keychain or CLI, then retry."); } return input.bind({ authorityRepoId: input.authorityRepoId, kindId: payload.kindId, ...(payload.baseUrl ? { baseUrl: payload.baseUrl } : {}), credentialRef }); } };
}
export function nativeCredentialBroker(platform: NodeJS.Platform = process.platform): NativeCredentialBroker { return { promptAndStore: async (kindId) => { if (platform !== "darwin") throw coded("secure_prompt_unavailable"); const script = `set answer to display dialog "Configure ${kindId} credential" default answer "" with hidden answer buttons {"Cancel", "Save"} default button "Save"\nreturn text returned of answer`, { stdout } = await promisify(execFile)("/usr/bin/osascript", ["-e", script], { encoding: "utf8", windowsHide: true, maxBuffer: 64 * 1024 }), value = stdout.replace(/[\r\n]+$/u, ""); if (!value) throw coded("secure_prompt_unavailable"); const service = "com.harness-anything.runtime", account = `${kindId}-${randomUUID()}`; await storeInKeychain(service, account, value); return `keychain:${service}/${account}`; } }; }
function storeInKeychain(service: string, account: string, value: string): Promise<void> { return new Promise((resolve, reject) => { const child = spawn("/usr/bin/security", ["add-generic-password", "-U", "-s", service, "-a", account, "-w"], { stdio: ["pipe", "ignore", "ignore"], windowsHide: true }); child.once("error", () => reject(coded("secure_prompt_unavailable"))); child.once("exit", (code) => code === 0 ? resolve() : reject(coded("secure_prompt_unavailable"))); child.stdin.end(`${value}\n`); }); }
function unavailable(kindId: unknown, code: string, hint: string): Receipt { return { schema: "runtime-credential-receipt/v1", ok: false, outcome: "rejected", operationId: `runtime-credential-${randomUUID()}`, kindId, credentialState: "not_configured", baseUrlConfigured: false, error: { code, hint }, nextAction: hint }; }
function coded(code: string): Error { return Object.assign(new Error(code), { code }); }
